import type { StartMessages } from './start-copy.ts';

export const fr: StartMessages = {
  downloader: {
    consentFailed: (message) => `Impossible d’enregistrer votre consentement : ${message}`, installFailed: (message) => `Impossible de démarrer l’installation : ${message}`, pickTitle: 'Choisir yt-dlp', pickButton: 'Utiliser ceci', pickFailed: (message) => `Ce fichier ne peut pas être utilisé : ${message}`, manualUpdate: 'BaoCut ne peut pas mettre à jour cette copie de yt-dlp pour le moment. Exécutez la commande de la carte dans un terminal', commandChanged: 'La commande de mise à jour a changé. Vérifiez la nouvelle commande avant de l’exécuter', updateFailed: (message) => `Impossible de démarrer la mise à jour : ${message}`, stopFailed: (message) => `Impossible d’arrêter la mise à jour : ${message}`, dirFailed: (message) => `Impossible de changer l’emplacement de téléchargement : ${message}`, notInstalled: (message) => `L’outil de téléchargement n’a pas été installé : ${message}`, installFailedFallback: 'Échec de l’installation',
    badge: { checking: 'Vérification', unknown: 'Indisponible', installing: 'Préparation', updating: 'Mise à jour', install: 'Non installé', update: 'Mise à jour nécessaire', broken: 'Impossible d’exécuter', blocked: 'À vérifier', consent: 'En attente de vous', ready: 'Prêt' }, card: 'Outil de téléchargement vidéo', checkFailed: (message) => `Impossible de vérifier l’outil de téléchargement : ${message}`, preparing: 'Préparation de l’outil de téléchargement', recheck: 'Vérifier à nouveau', pick: 'Choisir l’emplacement…', pickUnavailable: 'Choisir l’emplacement (sélection de fichiers impossible ici)',
  },
  update: { stop: 'Arrêter la mise à jour', run: 'Exécuter cette commande', copy: 'Copier la commande', command: 'commande', updating: 'Mise à jour de yt-dlp', output: 'Sortie de la mise à jour', hideOutput: 'Masquer la sortie', showOutput: 'Afficher la sortie', close: 'Fermer', section: 'Mettre à jour yt-dlp' },
  link: { field: 'Lien vidéo', placeholder: 'Collez une page vidéo ou un lien direct, comme https://…', plan: 'Après le démarrage, le lien est vérifié, les informations vidéo sont récupérées, puis le téléchargement commence', waiting: 'En attente du téléchargement', invalid: 'Saisissez une adresse vidéo http:// ou https:// complète.', hint: 'Collez un lien vers une seule vidéo publique ou un lien direct vers un média.', downloadTo: (dir) => `Télécharger dans ${dir}`, change: 'Changer…' },
  flow: {
    reason: (parts) => parts.join(' : '), undo: 'Annuler', openVideo: 'Ouvrir la vidéo', viewTask: 'Afficher la tâche', createFailed: (message) => `Impossible de créer la vidéo : ${message}`, importFailed: (message) => `La vidéo a été créée, mais le média n’a pas été importé : ${message}`, waveFailed: (message) => `La forme d’onde n’a pas été ajoutée : ${message}. Vous pouvez l’ajouter à nouveau depuis le panneau Éléments de l’éditeur.`, blankCreated: 'Vidéo vide créée', a2vCreated: (wave) => `Vidéo créée · ${wave ? 'Arrière-plan et forme d’onde ajoutés' : 'Arrière-plan ajouté'}`, created: 'Vidéo créée', notSubmitted: 'La transcription n’a pas été soumise', transcribeNotStarted: (why) => `Vidéo créée, mais la transcription n’a pas démarré : ${why}`, chainQueued: (title) => `Vidéo créée · « ${title} » démarre automatiquement après la transcription`, a2vTranscribing: (wave) => `Vidéo créée · ${wave ? 'Forme d’onde ajoutée · ' : ''}Transcription des sous-titres`, transcribing: 'Vidéo créée · Transcription démarrée en arrière-plan', noDownload: 'L’import est terminé, mais le fichier téléchargé est introuvable', transcribeUnfinished: 'La transcription n’est pas terminée', noSpeech: 'Aucune parole reconnue ; il n’y a donc rien à traduire', noSpeechToast: (name) => `Aucune parole reconnue dans « ${name} » ; la traduction n’a donc pas démarré`, video: 'Vidéo',
    translateNotPlaced: (name, why) => `La traduction de « ${name} » n’a pas été ajoutée à la vidéo : ${why}. Ouvrez la vidéo et continuez dans le panneau Sous-titres.`, translateCancelled: 'Traduction annulée', translateBusy: 'Une autre traduction est toujours en cours', translateFailed: (message) => `Impossible de démarrer la traduction : ${message}`, openAndTranslate: 'Ouvrir la vidéo et traduire', notOpened: 'La vidéo ne s’est pas ouverte ; la traduction n’a donc pas démarré', noFile: 'Le fichier téléchargé est introuvable', noProject: 'Cet import n’appartient pas à un projet', createFailedShort: 'Impossible de créer la vidéo',
  }, templates: { skipped: (dir, message) => `${dir} : ${message}`, issues: (issues) => ` (${issues.join(' ; ')})` },
};
