import type { StartMessages } from './start-copy.ts';

export const vi: StartMessages = {
 downloader: { consentFailed: (message) => `Không ghi nhận được sự đồng ý của bạn: ${message}`, installFailed: (message) => `Không bắt đầu cài được: ${message}`, pickTitle: 'Chọn yt-dlp', pickButton: 'Dùng tệp này', pickFailed: (message) => `Không thể dùng tệp này: ${message}`, manualUpdate: 'Hiện BaoCut không thể cập nhật bản yt-dlp này. Hãy chạy lệnh trên thẻ trong terminal', commandChanged: 'Lệnh cập nhật đã đổi. Hãy kiểm tra lệnh mới trước khi chạy', updateFailed: (message) => `Không bắt đầu cập nhật được: ${message}`, stopFailed: (message) => `Không dừng cập nhật được: ${message}`, dirFailed: (message) => `Không đổi vị trí tải xuống được: ${message}`, notInstalled: (message) => `Công cụ tải xuống chưa được cài: ${message}`, installFailedFallback: 'Cài thất bại', badge: { checking: 'Đang kiểm tra', unknown: 'Không khả dụng', installing: 'Đang chuẩn bị', updating: 'Đang cập nhật', install: 'Chưa cài', update: 'Cần cập nhật', broken: 'Không thể chạy', blocked: 'Cần chú ý', consent: 'Đợi bạn', ready: 'Sẵn sàng' }, card: 'Công cụ tải xuống video', checkFailed: (message) => `Không kiểm tra công cụ tải xuống được: ${message}`, preparing: 'Đang chuẩn bị công cụ tải xuống', recheck: 'Kiểm tra lại', pick: 'Chọn vị trí…', pickUnavailable: 'Chọn vị trí (không thể chọn tệp ở đây)' },
 update: { stop: 'Dừng cập nhật', run: 'Chạy lệnh này', copy: 'Sao chép lệnh', command: 'lệnh', updating: 'Đang cập nhật yt-dlp', output: 'Đầu ra cập nhật', hideOutput: 'Ẩn đầu ra', showOutput: 'Hiện đầu ra', close: 'Đóng', section: 'Cập nhật yt-dlp' },
 link: { field: 'Liên kết video', placeholder: 'Dán trang video hoặc liên kết trực tiếp, như https://…', plan: 'Sau khi bắt đầu, liên kết được kiểm tra, thông tin video được lấy rồi video được tải xuống', waiting: 'Đợi tải xuống', invalid: 'Nhập địa chỉ video đầy đủ bắt đầu bằng http:// hoặc https://.', hint: 'Dán một liên kết video công khai hoặc liên kết tư liệu trực tiếp.', downloadTo: (dir) => `Tải xuống ${dir}`, change: 'Đổi…' },
 flow: { reason: (parts) => parts.join(': '), undo: 'Hoàn tác', openVideo: 'Mở video', viewTask: 'Xem tác vụ', createFailed: (message) => `Không tạo video được: ${message}`, importFailed: (message) => `Đã tạo video nhưng chưa nhập tư liệu: ${message}`, waveFailed: (message) => `Chưa thêm dạng sóng: ${message}. Bạn có thể thêm lại từ bảng Phần tử trong trình chỉnh sửa.`, blankCreated: 'Đã tạo video trống', a2vCreated: (wave) => `Đã tạo video · Đã thêm ${wave ? 'nền và dạng sóng' : 'nền'}`, created: 'Đã tạo video', notSubmitted: 'Chưa gửi yêu cầu chép lời', transcribeNotStarted: (why) => `Đã tạo video nhưng chưa bắt đầu chép lời: ${why}`, chainQueued: (title) => `Đã tạo video · “${title}” tự bắt đầu sau khi chép lời`, a2vTranscribing: (wave) => `Đã tạo video · ${wave ? 'Đã thêm dạng sóng · ' : ''}Đang chép lời phụ đề`, transcribing: 'Đã tạo video · Đã bắt đầu chép lời ở nền', noDownload: 'Đã nhập xong nhưng không tìm thấy tệp đã tải xuống', transcribeUnfinished: 'Chép lời chưa hoàn tất', noSpeech: 'Không nhận dạng được lời nói nên không có gì để dịch', noSpeechToast: (name) => `Không nhận dạng được lời nói trong “${name}” nên chưa bắt đầu dịch`, video: 'Video', translateNotPlaced: (name, why) => `Chưa thêm bản dịch của “${name}” vào video: ${why}. Hãy mở video và tiếp tục trong bảng Phụ đề.`, translateCancelled: 'Đã hủy dịch', translateBusy: 'Một bản dịch khác vẫn đang chạy', translateFailed: (message) => `Không bắt đầu dịch được: ${message}`, openAndTranslate: 'Mở video và dịch', notOpened: 'Video chưa mở nên chưa bắt đầu dịch', noFile: 'Không tìm thấy tệp đã tải xuống', noProject: 'Lần nhập này không thuộc dự án', createFailedShort: 'Không tạo video được' },
 templates: { skipped: (dir, message) => `${dir}: ${message}`, issues: (issues) => ` (${issues.join('; ')})` },
};
