import type { StartMessages } from './start-copy.ts';

export const pl: StartMessages = {
  downloader: {
    consentFailed: (message) => `Nie udało się zapisać zgody: ${message}`,
    installFailed: (message) => `Nie udało się rozpocząć instalacji: ${message}`,
    pickTitle: "Wybierz yt-dlp",
    pickButton: "Użyj tego",
    pickFailed: (message) => `Nie można użyć pliku: ${message}`,
    manualUpdate: "BaoCut nie może teraz zaktualizować tego yt-dlp. Uruchom polecenie z karty w terminalu",
    commandChanged: "Polecenie aktualizacji zmieniono. Sprawdź nowe przed uruchomieniem",
    updateFailed: (message) => `Nie udało się rozpocząć aktualizacji: ${message}`,
    stopFailed: (message) => `Nie udało się zatrzymać aktualizacji: ${message}`,
    dirFailed: (message) => `Nie udało się zmienić lokalizacji pobierania: ${message}`,
    notInstalled: (message) => `Narzędzie pobierania niezainstalowane: ${message}`,
    installFailedFallback: "Instalacja nie powiodła się",
    badge: {
      checking: "Sprawdzanie",
      unknown: "Niedostępne",
      installing: "Przygotowywanie",
      updating: "Aktualizowanie",
      install: "Nie zainstalowano",
      update: "Wymagana aktualizacja",
      broken: "Nie można uruchomić",
      blocked: "Wymaga uwagi",
      consent: "Czeka na Ciebie",
      ready: "Gotowe",
    },
    card: "Narzędzie pobierania wideo",
    checkFailed: (message) => `Nie udało się sprawdzić narzędzia pobierania: ${message}`,
    preparing: "Przygotowywanie narzędzia pobierania",
    recheck: "Sprawdź ponownie",
    pick: "Wybierz lokalizację…",
    pickUnavailable: "Wybierz lokalizację (tutaj nie można wybierać plików)",
  },
  update: {
    stop: "Zatrzymaj aktualizację",
    run: "Uruchom polecenie",
    copy: "Kopiuj polecenie",
    command: "polecenie",
    updating: "Aktualizowanie yt-dlp",
    output: "Wynik aktualizacji",
    hideOutput: "Ukryj wynik",
    showOutput: "Pokaż wynik",
    close: "Zamknij",
    section: "Zaktualizuj yt-dlp",
  },
  link: {
    field: "Link do wideo",
    placeholder: "Wklej stronę wideo lub link bezpośredni, np. https://…",
    plan: "Po rozpoczęciu link jest sprawdzany, informacje o wideo pobierane i zaczyna się pobieranie",
    waiting: "Oczekiwanie na pobieranie",
    invalid: "Wpisz pełny adres wideo http:// lub https://.",
    hint: "Wklej link do jednego publicznego wideo lub bezpośredni link do multimediów.",
    downloadTo: (dir) => `Pobierz do ${dir}`,
    change: "Zmień…",
  },
  flow: {
    reason: (parts) => parts.join(": "),
    undo: "Cofnij",
    openVideo: "Otwórz wideo",
    viewTask: "Zobacz zadanie",
    createFailed: (message) => `Nie udało się utworzyć wideo: ${message}`,
    importFailed: (message) => `Wideo utworzono, ale multimediów nie zaimportowano: ${message}`,
    waveFailed: (message) => `Nie dodano przebiegu fali: ${message}. Możesz dodać ponownie z panelu „Elementy” edytora.`,
    blankCreated: "Utworzono puste wideo",
    a2vCreated: (wave) => `Wideo utworzono · ${wave ? "Tło i przebieg fali" : "Tło"} dodano`,
    created: "Wideo utworzono",
    notSubmitted: "Nie przesłano transkrypcji",
    transcribeNotStarted: (why) => `Wideo utworzono, ale transkrypcja nie ruszyła: ${why}`,
    chainQueued: (title) => `Wideo utworzono · „${title}” rozpoczyna się automatycznie po transkrypcji`,
    a2vTranscribing: (wave) => `Wideo utworzono · ${wave ? "Przebieg fali dodano · " : ""}Transkrybowanie napisów`,
    transcribing: "Wideo utworzono · Transkrypcja rozpoczęta w tle",
    noDownload: "Import ukończony, ale pobranego pliku nie znaleziono",
    transcribeUnfinished: "Transkrypcja nie została ukończona",
    noSpeech: "Nie rozpoznano mowy, nie ma czego tłumaczyć",
    noSpeechToast: (name) => `Nie rozpoznano mowy w „${name}”, więc tłumaczenie nie ruszyło`,
    video: "Wideo",
    translateNotPlaced: (name, why) => `Tłumaczenie „${name}” nie zostało dodane do wideo: ${why}. Otwórz wideo i kontynuuj w panelu „Napisy”.`,
    translateCancelled: "Tłumaczenie anulowano",
    translateBusy: "Inne tłumaczenie nadal trwa",
    translateFailed: (message) => `Nie udało się rozpocząć tłumaczenia: ${message}`,
    openAndTranslate: "Otwórz wideo i przetłumacz",
    notOpened: "Wideo nie otworzyło się, tłumaczenie nie ruszyło",
    noFile: "Pobrany plik nieznaleziony",
    noProject: "Import nie należy do projektu",
    createFailedShort: "Nie udało się utworzyć wideo",
  },
  templates: {
    skipped: (dir, message) => `${dir}: ${message}`,
    issues: (issues) => ` (${issues.join("; ")})`,
  },
};
