import type { StartMessages } from './start-copy.ts';

export const ptBR: StartMessages = {
  downloader: {
    consentFailed: (message: string) => `Não foi possível registrar consentimento: ${message}`,
    installFailed: (message: string) => `Não foi possível iniciar instalação: ${message}`,
    pickTitle: "Escolher yt-dlp",
    pickButton: "Usar este",
    pickFailed: (message: string) => `Arquivo não utilizável: ${message}`,
    manualUpdate: "BaoCut não pode atualizar esta cópia agora. Execute o comando do cartão no terminal",
    commandChanged: "O comando mudou. Verifique o novo antes de executar",
    updateFailed: (message: string) => `Não foi possível iniciar atualização: ${message}`,
    stopFailed: (message: string) => `Não foi possível parar atualização: ${message}`,
    dirFailed: (message: string) => `Não foi possível mudar local de download: ${message}`,
    notInstalled: (message: string) => `Ferramenta não instalada: ${message}`,
    installFailedFallback: "A instalação falhou",
    badge: {
      checking: "Verificando",
      unknown: "Indisponível",
      installing: "Preparando",
      updating: "Atualizando",
      install: "Não instalado",
      update: "Atualização disponível",
      broken: "Não pode executar",
      blocked: "Precisa de atenção",
      consent: "Aguardando você",
      ready: "Pronto",
    },
    card: "Ferramenta de download de vídeo",
    checkFailed: (message: string) => `Não foi possível verificar a ferramenta: ${message}`,
    preparing: "Preparando ferramenta de download",
    recheck: "Verificar novamente",
    pick: "Escolher local…",
    pickUnavailable: "Escolher local (seletor indisponível aqui)",
  },
  update: {
    stop: "Parar atualização",
    run: "Executar este comando",
    copy: "Copiar comando",
    command: "Comandos",
    updating: "Atualizando yt-dlp",
    output: "Saída da atualização",
    hideOutput: "Ocultar saída",
    showOutput: "Mostrar saída",
    close: "Fechar",
    section: "Atualizar yt-dlp",
  },
  link: {
    field: "Link do vídeo",
    placeholder: "Cole a página do vídeo ou um link direto, ex.: https://…",
    plan: "Após iniciar, verifica o link, obtém informações e baixa",
    waiting: "Aguardando download",
    invalid: "Informe endereço completo http:// ou https://.",
    hint: "Cole link de vídeo público único ou mídia direta.",
    downloadTo: (dir: string) => `Baixar em ${dir}`,
    change: "Alterar…",
  },
  flow: {

    reason: (parts: readonly string[]) => parts.join(": "),
    undo: "Desfazer",
    openVideo: "Abrir vídeo",
    viewTask: "Ver tarefa",
    createFailed: (message: string) => `Não foi possível criar vídeo: ${message}`,
    importFailed: (message: string) => `Vídeo criado, mídia não importada: ${message}`,
    waveFailed: (message: string) => `Forma de onda não adicionada: ${message}. Adicione de novo em Elementos no editor.`,
    blankCreated: "Vídeo vazio criado",
    a2vCreated: (wave: boolean) => `Vídeo criado · ${wave ? "Fundo e forma de onda" : "Fundo"} adicionado`,
    created: "Vídeo criado",
    notSubmitted: "Transcrição não enviada",
    transcribeNotStarted: (why: string) => `Vídeo criado, mas transcrição não começou: ${why}`,
    chainQueued: (title: string) => `Vídeo criado · “${title}” inicia após transcrição`,
    a2vTranscribing: (wave: boolean) => `Vídeo criado · ${wave ? "Forma de onda adicionada · " : ""}Transcrevendo legendas`,
    transcribing: "Vídeo criado · transcrição em segundo plano",
    noDownload: "Importação concluída, arquivo baixado não encontrado",
    transcribeUnfinished: "Transcrição não terminou",
    noSpeech: "Sem fala reconhecida, nada para traduzir",
    noSpeechToast: (name: string) => `Sem fala reconhecida em “${name}”; tradução não começou`,
    video: "Vídeo",
    translateNotPlaced: (name: string, why: string) =>
      `A tradução de “${name}” não foi adicionada ao vídeo: ${why}. Abra o vídeo e continue em Legendas.`,
    translateCancelled: "Tradução cancelada",
    translateBusy: "Outra tradução ainda está em andamento",
    translateFailed: (message: string) => `Não foi possível começar tradução: ${message}`,
    openAndTranslate: "Abrir vídeo e traduzir",
    notOpened: "Vídeo não abriu; tradução não começou",
    noFile: "Arquivo baixado não encontrado",
    noProject: "Esta importação não pertence a um projeto",
    createFailedShort: "Não foi possível criar vídeo",
  },
  templates: {
    skipped: (dir: string, message: string) => `${dir}: ${message}`,
    issues: (issues: readonly string[]) => ` (${issues.join("; ")})`,
  },
};
