import type { StartMessages } from './start-copy.ts';

export const ja: StartMessages = {
  downloader: {
    consentFailed: (message) => `同意を記録できませんでした：${message}`,
    installFailed: (message) => `インストールを開始できませんでした：${message}`,
    pickTitle: 'yt-dlp を選択',
    pickButton: 'これを使用',
    pickFailed: (message) => `このファイルは使用できません：${message}`,
    manualUpdate: 'この yt-dlp は現在 BaoCut から更新できません。カードに表示されたコマンドをターミナルで実行してください',
    commandChanged: '更新コマンドが変わりました。新しいコマンドを確認してから実行してください',
    updateFailed: (message) => `更新を開始できませんでした：${message}`,
    stopFailed: (message) => `更新を停止できませんでした：${message}`,
    dirFailed: (message) => `ダウンロード先を変更できませんでした：${message}`,
    notInstalled: (message) => `ダウンロードツールはインストールされませんでした：${message}`,
    installFailedFallback: 'インストールに失敗しました',
    badge: {
      checking: '確認中',
      unknown: '利用不可',
      installing: '準備中',
      updating: '更新中',
      install: '未インストール',
      update: '要更新',
      broken: '実行できません',
      blocked: '対応が必要',
      consent: '同意待ち',
      ready: '準備完了',
    },
    card: '動画ダウンロードツール',
    checkFailed: (message) => `ダウンロードツールを確認できませんでした：${message}`,
    preparing: 'ダウンロードツールを準備中',
    recheck: '再確認',
    pick: '場所を指定…',
    pickUnavailable: '場所を指定（この環境ではファイルを選択できません）',
  },
  update: {
    stop: '更新を停止',
    run: 'このコマンドを実行',
    copy: 'コマンドをコピー',
    command: 'コマンド',
    updating: 'yt-dlp を更新中',
    output: '更新の出力',
    hideOutput: '出力を隠す',
    showOutput: '出力を表示',
    close: '閉じる',
    section: 'yt-dlp を更新',
  },
  link: {
    field: '動画リンク',
    placeholder: '動画ページまたは直リンクを貼り付け（例：https://…）',
    plan: '開始すると、リンクを確認し、動画の情報を取得してダウンロードします',
    waiting: 'ダウンロード待ち',
    invalid: 'http:// または https:// で始まる完全な動画アドレスを入力してください。',
    hint: '公開されている動画のリンク、またはメディアの直リンクを 1 つ貼り付けてください。',
    downloadTo: (dir) => `${dir} にダウンロード`,
    change: '変更…',
  },
  flow: {
    reason: (parts) => parts.join('：'),
    undo: '取り消す',
    openVideo: '動画を開く',
    viewTask: 'タスクを見る',
    createFailed: (message) => `動画を作成できませんでした：${message}`,
    importFailed: (message) => `動画は作成されましたが、メディアを読み込めませんでした：${message}`,
    waveFailed: (message) => `波形を追加できませんでした：${message}。エディタの要素パネルから追加し直せます。`,
    blankCreated: '空の動画を作成しました',
    a2vCreated: (wave) => `動画を作成しました · ${wave ? '背景と波形' : '背景'}を追加しました`,
    created: '動画を作成しました',
    notSubmitted: '文字起こしは送信されませんでした',
    transcribeNotStarted: (why) => `動画を作成しましたが、文字起こしは開始されませんでした：${why}`,
    chainQueued: (title) => `動画を作成しました · 文字起こしの完了後に「${title}」が自動で始まります`,
    a2vTranscribing: (wave) => `動画を作成しました · ${wave ? '波形を追加しました · ' : ''}字幕を文字起こし中`,
    transcribing: '動画を作成しました · バックグラウンドで文字起こしを開始しました',
    noDownload: '読み込みは完了しましたが、ダウンロードしたファイルが見つかりませんでした',
    transcribeUnfinished: '文字起こしが完了しませんでした',
    noSpeech: '音声が認識されなかったため、翻訳するものがありません',
    noSpeechToast: (name) => `「${name}」で音声が認識されなかったため、翻訳は開始されませんでした`,
    video: '動画',
    translateNotPlaced: (name, why) => `「${name}」の翻訳は動画に追加されませんでした：${why}。動画を開いて字幕パネルで続けてください。`,
    translateCancelled: '翻訳をキャンセルしました',
    translateBusy: '別の翻訳がまだ実行中です',
    translateFailed: (message) => `翻訳を開始できませんでした：${message}`,
    openAndTranslate: '動画を開いて翻訳',
    notOpened: '動画が開かなかったため、翻訳は開始されませんでした',
    noFile: 'ダウンロードしたファイルが見つかりませんでした',
    noProject: 'この読み込みはどのプロジェクトにも属していません',
    createFailedShort: '動画を作成できませんでした',
  },
  templates: {
    skipped: (dir, message) => `${dir}：${message}`,
    issues: (issues) => `（${issues.join('、')}）`,
  },
};
