import type { ToolsMessages } from './external-tools-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const ptBR: ToolsMessages = {
  help: `Uso:
  baocut external-tools [list]     Ferramentas externas (yt-dlp, ffmpeg): estado, versão, caminho,
                                   origem e se você concordou com o uso
  baocut external-tools detect [name]
                                   Detectar novamente
  baocut external-tools install <name> [--yes]
                                   Baixar uma cópia gerenciada para tools/ no Runtime Home: lista a origem, versão, tamanho e
                                   licença, baixa após a confirmação e verifica sha256 (--yes significa que você concorda).
                                   Origem do download: configuração tools.downloadEndpoint e variável de ambiente BAOCUT_TOOLS_ENDPOINT
  baocut external-tools update <name> [--yes]
                                   Atualizar a cópia do sistema pelo método de instalação (Homebrew, pipx, pip ou programa
                                   autônomo oficial): lista o comando completo, executado pelo Runtime após a confirmação
                                   (--yes confirma), mostra a saída linha por linha e detecta novamente ao concluir.
                                   Comandos que exigem direitos de administrador são apenas exibidos; execute-os em um terminal
  baocut external-tools path <name> <file>|--clear
                                   Usar uma cópia que você instalou (executa --version para verificar); --clear remove a substituição
  baocut external-tools remove <name>
                                   Excluir a cópia gerenciada (cópias do sistema e caminhos definidos não são alterados)
  baocut external-tools consent <name> [--revoke]
                                   Concordar com o uso de uma ferramenta de download ou retirar o consentimento (o que recusa imports de links)`,
  usage: 'Uso: baocut external-tools [list] | detect [name] | install <name> [--yes] | update <name> [--yes] | path <name> <file>|--clear | remove <name> | consent <name> [--revoke]', clearOrFile: 'Informe --clear ou um arquivo, não ambos', stateLabels: { installed: 'Instalado', missing: 'Não instalado', outdated: 'Atualização disponível', unavailable: 'Não disponível' }, sourceLabels: { system: 'PATH do sistema', user: 'caminho especificado', managed: 'cópia baixada pelo BaoCut', env: 'variável de ambiente' }, updateMethodLabels: { homebrew: 'Homebrew', pipx: 'pipx', pip: 'pip', standalone: 'versão autônoma oficial', winget: 'winget', scoop: 'Scoop', chocolatey: 'Chocolatey' }, statusHead: (name, state, version, source, purpose) => `${name}  ${state}${version ? ` ${version}` : ''}${source ? ` (${source})` : ''}  ${purpose}`,
  pathLine: (path) => `  Caminho: ${path}`, userPathLine: (path) => `  Caminho especificado: ${path}`, managedLine: (version, path) => `  Cópia gerenciada: ${version}  ${path}`, consentLine: (label) => `  Consentimento: ${label}`, installingLine: (jobId) => `  Instalando: tarefa ${jobId}`, updatingLine: (jobId) => `  Atualizando: tarefa ${jobId}`, updateLine: (command, method, runnable) => `  Atualização: ${command} (${method}${runnable ? '' : ', execute em um terminal'})`, reasonLine: (reason) => `  Motivo: ${reason}`, remedyLine: (remedy) => `  Solução: ${remedy}`, consentMissing: (name) => `Ainda não concedido (consinta antes do uso: baocut external-tools consent ${name})`, consentVia: { agent: 'pela aprovação do agente', cli: 'no CLI', app: 'no aplicativo' }, consentGranted: (at, via) => `Concedido (${at}, ${via})`, consentRevoked: (at) => `Retirado (${at})`, noTools: 'Nenhuma ferramenta externa registrada', cannotUpdate: (label, reason) => `Não foi possível atualizar ${label} por você: ${reason}`, runInTerminal: 'Execute em um terminal:', redetect: (name) => `Depois verifique novamente: baocut external-tools detect ${name}`, updatePlanHead: (method, label, version) => `Vai atualizar ${label}${version ? ` ${version}` : ''} pelo método de instalação (${method})`, runLine: (command) => `  Executar: ${command}`,
  updatePrompt: (label) => `Executar este comando neste computador para atualizar ${label}? [y/N] `, omittedLines: (n) => `…(${n} ${pluralForm('pt-BR', n, { one: 'linha omitida', other: 'linhas omitidas' })})`, updated: (label, before, after) => `Atualização de ${label}: ${before ?? 'versão desconhecida'} → ${after}`, upToDate: (label, version) => `A versão de ${label} está em dia${version ? ` (${version})` : ''}`, sizeEstimated: (size) => `cerca de ${size} (tamanho desconhecido, estimado)`, sizeAbout: (size) => `cerca de ${size}`, willDownload: (label, version) => `Vai baixar ${label} ${version}`, sourceLine: (url) => `  Origem: ${url ?? '(nenhum arquivo disponível para este computador)'}`, sizeLine: (size) => `  Tamanho: ${size}`, licenseLine: (license) => `  Licença: ${license}`, homepageLine: (url) => `  Página inicial: ${url}`, sha256Line: (hash) => `  sha256: ${hash}`, blockedLine: (reason) => `  Não foi possível baixar: ${reason}`, installPrompt: (label, version, size) => `Baixar e usar ${label} ${version} (${size})? [y/N] `, noExternalTool: (name) => `Ferramenta externa “${name}” não encontrada`, alreadyInstalling: (jobId) => `Já instalando (tarefa ${jobId}); mostrando a progressão`, installDone: 'Instalação concluída',
  notDownloadedByBaoCut: (label, remedy) => `O BaoCut não baixa ${label}: ${remedy ?? 'instale por conta própria'}`, cannotDownload: (label, reason) => `Não foi possível baixar ${label}: ${reason}`, notTtyAgreeDownload: 'Não está em um terminal: adicione --yes depois que o usuário concordar com o download', notTtyConfirmRun: 'Não está em um terminal: adicione --yes depois que o usuário confirmar a execução', notDownloaded: 'Não baixado', notRun: 'Não executado', remedy: (remedy) => `Para corrigir: ${remedy}`, partialDownloadKept: (name) => `A parte baixada foi mantida: execute baocut external-tools install ${name} para continuar`, alreadyUpdating: (jobId) => `Já atualizando (tarefa ${jobId}); mostrando a saída`, managedCopy: (label, name) => `A versão de ${label} em uso é uma cópia baixada pelo BaoCut: use baocut external-tools install ${name} para mudar de versão`, unknownInstall: (file, name) => `Não foi possível determinar como ${file} foi instalado: atualize em um terminal pelo método de instalação e execute baocut external-tools detect ${name}`, noRunnableTool: (label, remedy) => `Nenhuma versão executável de ${label} encontrada: ${remedy}`, updateManual: (label, command) => `Atualize ${label} por conta própria em um terminal: ${command}`, partialCommand: (name) => `O comando pode ter sido executado apenas em parte: execute baocut external-tools detect ${name} para ver a versão atual`,
};
