import { pluralForm } from '@baocut/protocol';
import type { ToolsMessages } from './external-tools-copy.ts';

export const ru: ToolsMessages = {
  help: "Использование:\n  baocut external-tools [list]     Внешние инструменты (yt-dlp, ffmpeg): статус, версия, путь,\n                                   источник и согласие на использование\n  baocut external-tools detect [name]\n                                   Обнаружить снова\n  baocut external-tools install <name> [--yes]\n                                   Скачать управляемую копию в tools/ в Runtime Home: показывает источник, версию, размер,\n                                   лицензию, после подтверждения скачивает и проверяет sha256 (--yes означает согласие).\n                                   Источник: tools.downloadEndpoint и переменная окружения BAOCUT_TOOLS_ENDPOINT\n  baocut external-tools update <name> [--yes]\n                                   Обновить системную копию способом установки (Homebrew, pipx, pip или официальный\n                                   отдельный файл): показывает полную команду, Runtime выполняет после\n                                   подтверждения (--yes подтверждает), печатает вывод построчно и обнаруживает снова.\n                                   Команды с правами администратора только показываются; выполните в терминале сами\n  baocut external-tools path <name> <file>|--clear\n                                   Использовать свою копию (--version проверяет один раз); --clear убирает переопределение\n  baocut external-tools remove <name>\n                                   Удалить управляемую копию (системные и переопределённые не затрагиваются)\n  baocut external-tools consent <name> [--revoke]\n                                   Согласиться на использование или отозвать согласие (после импорт по ссылкам отклоняется)",
  usage:
    "Использование: baocut external-tools [list] | detect [name] | install <name> [--yes] | update <name> [--yes] | path <name> <file>|--clear | remove <name> | consent <name> [--revoke]",
  clearOrFile: "Укажите --clear или файл, не оба",
  stateLabels: {
    installed: "Установлено",
    missing: "Не установлен",
    outdated: "Доступно обновление",
    unavailable: "Недоступно",
  },
  sourceLabels: {
    system: "системный PATH",
    user: "указанный путь",
    managed: "копия, скачанная BaoCut",
    env: "переменная окружения",
  },
  updateMethodLabels: {
    homebrew: "Homebrew",
    pipx: "pipx",
    pip: "pip",
    standalone: "официальная отдельная сборка",
    winget: "winget",
    scoop: "Scoop",
    chocolatey: "Chocolatey",
  },
  statusHead: (name: string, state: string, version: string | null, source: string | null, purpose: string) => `${name}  ${state}${version ? ` ${version}` : ""}${source ? ` (${source})` : ""}  ${purpose}`,
  pathLine: (path: string) => `  Путь: ${path}`,
  userPathLine: (path: string) => `  Указанный путь: ${path}`,
  managedLine: (version: string, path: string) => `  Управляемая копия: ${version}  ${path}`,
  consentLine: (label: string) => `  Согласие: ${label}`,
  installingLine: (jobId: string) => `  Установка: задача ${jobId}`,
  updatingLine: (jobId: string) => `  Обновление: задача ${jobId}`,
  updateLine: (command: string, method: string, runnable: boolean) => `  Обновление: ${command} (${method}${runnable ? "" : ", выполните самостоятельно в терминале"})`,
  reasonLine: (reason: string) => `  Причина: ${reason}`,
  remedyLine: (remedy: string) => `  Решение: ${remedy}`,
  consentMissing: (name: string) => `Ещё не выдано (подтвердите перед использованием: baocut external-tools consent ${name})`,
  consentVia: { agent: "через одобрение агента", cli: "в CLI", app: "в приложении" },
  consentGranted: (at: string, via: string) => `Выдано (${at}, ${via})`,
  consentRevoked: (at: string) => `Отозвано (${at})`,
  noTools: "Нет зарегистрированных внешних инструментов",
  cannotUpdate: (label: string, reason: string) => `Не удалось обновить ${label} за вас: ${reason}`,
  runInTerminal: "Выполните в терминале:",
  redetect: (name: string) => `Затем проверьте снова: baocut external-tools detect ${name}`,
  updatePlanHead: (method: string, label: string, version: string | null) => `Будет обновлено ${label}${version ? ` ${version}` : ""} способом установки (${method})`,
  runLine: (command: string) => `  Выполнить: ${command}`,
  updatePrompt: (label: string) => `Выполнить команду на компьютере для обновления ${label}? [y/N] `,
  omittedLines: (n: number) => `…(${n} ${pluralForm('ru', n, { one: "строка", few: "строки", many: "строк", other: "строки" })} пропущено)`,
  updated: (label: string, before: string | null, after: string) => `Обновлено: ${label}: ${before ?? 'unknown version'} → ${after}`,
  upToDate: (label: string, version: string | null) => `${label} актуален${version ? ` (${version})` : ""}`,
  sizeEstimated: (size: string) => `около ${size} (размер неизвестен, оценка)`,
  sizeAbout: (size: string) => `около ${size}`,
  willDownload: (label: string, version: string) => `Будет скачано ${label} ${version}`,
  sourceLine: (url: string | null) => `  Источник: ${url ?? '(no file available for this computer)'}`,
  sizeLine: (size: string) => `  Размер: ${size}`,
  licenseLine: (license: string) => `  Лицензия: ${license}`,
  homepageLine: (url: string) => `  Сайт: ${url}`,
  sha256Line: (hash: string) => `  sha256: ${hash}`,
  blockedLine: (reason: string) => `  Нельзя скачать: ${reason}`,
  installPrompt: (label: string, version: string, size: string) => `Скачать и использовать ${label} ${version} (${size})? [y/N] `,
  noExternalTool: (name) => `Нет внешнего инструмента «${name}"`,
  alreadyInstalling: (jobId) => `Установка уже выполняется (задача ${jobId}); показан прогресс`,
  installDone: "Установка завершена",
  notDownloadedByBaoCut: (label, remedy) => `BaoCut не скачивает ${label}: ${remedy ?? 'install it yourself'}`,
  cannotDownload: (label, reason) => `Нельзя скачать ${label}: ${reason}`,
  notTtyAgreeDownload: "Запуск вне терминала: добавьте --yes после согласия пользователя на скачивание",
  notTtyConfirmRun: "Запуск вне терминала: добавьте --yes после подтверждения запуска пользователем",
  notDownloaded: "Не скачано",
  notRun: "Не выполнено",
  remedy: (remedy) => `Как исправить: ${remedy}`,
  partialDownloadKept: (name) => `Скачанная часть сохранена: выполните baocut external-tools install ${name} для продолжения`,
  alreadyUpdating: (jobId) => `Обновление уже выполняется (задача ${jobId}); показан вывод`,
  managedCopy: (label, name) => `Компонент ${label} — используется копия BaoCut: примените baocut external-tools install ${name} для смены версии`,
  unknownInstall: (file, name) => `Не удалось определить, как ${file} установлен: обновите тем же способом в терминале, затем выполните baocut external-tools detect ${name}`,
  noRunnableTool: (label, remedy) => `Нет запускаемого ${label}: ${remedy}`,
  updateManual: (label, command) => `Обновление ${label} нужно выполнить самостоятельно в терминале: ${command}`,
  partialCommand: (name) => `Команда могла выполниться частично: выполните baocut external-tools detect ${name} для текущей версии`,
};
