import { pluralForm } from '@baocut/protocol';
import type { JobsMessages } from './jobs-copy.ts';

export const ru: JobsMessages = {
  help: "Использование:\n  baocut jobs resources            Состояние планирования ресурсов: ресурсы машины и их источник, резервирование,\n                                   выделения, резидентные Model Workers и ожидания задач в очереди\n  baocut jobs reconcile <jobId> retry|discard|apply\n                                   Обработать задачи с неизвестным результатом или неполным применением после\n                                   перезапуска: retry запускает снова (новый вызов с проверкой разрешений и бюджета),\n                                   discard отбрасывает внешние вызовы, ожидающие сверки (уже списанный бюджет\n                                   не возвращается), apply проверяет сохранённый результат и применяет к видео",
  usage: "Использование: baocut jobs resources | baocut jobs reconcile <jobId> retry|discard|apply",
  badDecision: (choices) => `Решение сверки должно быть одним из: ${choices.join(", ")}`,
  jobStates: {
    queued: "В очереди",
    running: "Выполняется",
    completed: "Готово",
    failed: "Ошибка",
    cancelled: "Отменено",
    interrupted: "Прервано",
    'needs-reconciliation': "Требует сверки",
  },
  applicationStates: {
    pending: "Ожидает",
    validating: "Запись",
    committed: "Применено",
    'stale-input': "Цель изменена",
    rejected: "Отклонено",
    cancelled: "Не применено",
  },
  remoteStates: {
    'not-applicable': "нет удалённого",
    'not-submitted': "не отправлено",
    cancelled: "отменено удалённо",
    'cancel-unsupported': "удалённо отменить нельзя",
    unknown: "удалённый статус неизвестен",
  },
  costStates: {
    none: "без оплаты",
    possible: "оплата могла начислиться",
    charged: "оплачено",
  },
  cancellation: (stoppedLocally, remote, cost) => `${stoppedLocally ? "остановлено локально" : "локально не остановлено"}, ${remote}, ${cost}`,
  cancellationLine: (text) => `Отмена: ${text}`,
  requeued: (attempt, jobId) => `Снова в очереди (попытка ${attempt}): ${jobId}`,
  discarded: (jobId) => `Отброшено: ${jobId}`,
  appliedTo: (videoId, recovered) => `Применено к видео ${videoId}${recovered ? " (уже записано в прошлый раз; подтверждение записано сейчас)" : ""}`,
  notApplied: (state, error) => `Не применено: ${state}${error ? ` (${error})` : ""}`,
  noApplicationRecord: "нет записи применения",
  statusLine: (state, code) => `Статус: ${state}${code ? `  ${code}` : ""}`,
  budgetSettled: (basis, calls) => `Бюджет рассчитан: ${basis}, ${pluralForm('ru', calls, { one: `${calls} вызов`, few: `${calls} вызова`, many: `${calls} вызовов`, other: `${calls} вызова` })}`,
  unknown: "неизвестно",
  amounts: (memory, gpuMemory, cpuThreads, disk) => `Память ${memory}  Память GPU ${gpuMemory}  CPU ${pluralForm('ru', cpuThreads, { one: `${cpuThreads} поток`, few: `${cpuThreads} потока`, many: `${cpuThreads} потоков`, other: `${cpuThreads} потока` })}  Диск ${disk}`,
  demandMemory: (value) => `память ${value}`,
  demandGpuMemory: (value) => `память GPU ${value}`,
  demandCpu: (threads) => `CPU ${pluralForm('ru', threads, { one: `${threads} поток`, few: `${threads} потока`, many: `${threads} потоков`, other: `${threads} потока` })}`,
  demandDisk: (value) => `диск ${value}`,
  demandNone: "не использует локальные ресурсы",
  listSep: ", ",
  clauseSep: ", ",
  sources: {
    system: "система",
    setting: "настройки",
    'unified-estimate': "оценено по объединённой памяти",
    unknown: "неизвестно",
    statfs: "свободное место на диске staging",
  },
  capacity: (amounts, unified) => `Ресурсы: ${amounts}${unified ? " (объединённая память: память GPU также считается основной)" : ""}`,
  capacitySources: (memory, gpuMemory, cpu, disk) => `  Источники: память ${memory}, память GPU ${gpuMemory}, CPU ${cpu}, диск ${disk}`,
  systemReserve: (amounts) => `Системный резерв: ${amounts}`,
  interactiveReserve: (amounts) => `Интерактивный резерв: ${amounts}`,
  leased: (amounts) => `Выделено: ${amounts}`,
  backgroundAvailable: (amounts) => `Доступно фоновым задачам: ${amounts}`,
  interactiveAvailable: (amounts) => `Доступно интерактивно: ${amounts}`,
  leasesHeader: "Выделенные ресурсы:",
  leasesNone: "Выделенные ресурсы: нет",
  leaseHolder: (holder) => `использует ${holder}`,
  leaseQueue: (queue) => `очередь ${queue}`,
  holdersHeader: "Резидентные процессы:",
  holderState: (users, processes) => `${users > 0 ? `Используется задачами: ${users}` : "простаивает"}, работающих процессов: ${processes}`,
  waitingHeader: "Ожидание:",
  waitingNone: "Ожидание: нет",
  waitingAdmission: "ожидает допуска",
};
