import type { JobsMessages } from './jobs-copy.ts';
import { pluralForm } from '@baocut/protocol';
export const es: JobsMessages = {
 help: `Uso:
  baocut jobs resources            Estado de planificación de recursos: capacidad del ordenador y su origen, reservas,
                                   asignaciones, Model Workers residentes y qué esperan las tareas en cola
  baocut jobs reconcile <jobId> retry|discard|apply
                                   Gestionar tareas cuyo resultado es incierto o no se aplicó por completo después de
                                   reiniciar: retry ejecuta de nuevo (una llamada nueva, con autorización y presupuesto revisados),
                                   discard abandona llamadas salientes pendientes de conciliación (no se devuelve
                                   el presupuesto ya cobrado), apply revalida el resultado conservado y lo aplica al vídeo`,
 usage: 'Uso: baocut jobs resources | baocut jobs reconcile <jobId> retry|discard|apply', badDecision: (choices) => `La decisión de conciliación debe ser una de: ${choices.join(', ')}`,
 jobStates: { queued: 'En cola', running: 'En curso', completed: 'Completado', failed: 'Fallido', cancelled: 'Cancelado', interrupted: 'Interrumpido', 'needs-reconciliation': 'Necesita conciliación' }, applicationStates: { pending: 'Pendiente', validating: 'Confirmando', committed: 'Aplicado', 'stale-input': 'Destino cambiado', rejected: 'Rechazado', cancelled: 'Sin aplicar' }, remoteStates: { 'not-applicable': 'sin servicio remoto', 'not-submitted': 'sin enviar', cancelled: 'cancelado remotamente', 'cancel-unsupported': 'el servicio remoto no puede cancelar', unknown: 'estado remoto desconocido' }, costStates: { none: 'sin cargo', possible: 'puede haberse cobrado', charged: 'cobrado' },
 cancellation: (stoppedLocally, remote, cost) => `${stoppedLocally ? 'detenido localmente' : 'sin detener localmente'}, ${remote}, ${cost}`, cancellationLine: (text) => `Cancelación: ${text}`, requeued: (attempt, jobId) => `De nuevo en cola (intento ${attempt}): ${jobId}`, discarded: (jobId) => `Descartado: ${jobId}`, appliedTo: (videoId, recovered) => `Aplicado al vídeo ${videoId}${recovered ? ' (ya se confirmó la última vez; el recibo se registró ahora)' : ''}`, notApplied: (state, error) => `Sin aplicar: ${state}${error ? ` (${error})` : ''}`, noApplicationRecord: 'sin registro de aplicación', statusLine: (state, code) => `Estado: ${state}${code ? `  ${code}` : ''}`, budgetSettled: (basis, calls) => `Presupuesto liquidado: ${basis}, ${calls} ${pluralForm('es', calls, { one: 'llamada', other: 'llamadas' })}`, unknown: 'desconocido',
 amounts: (memory, gpuMemory, cpuThreads, disk) => `Memoria ${memory}  Memoria de GPU ${gpuMemory}  CPU ${cpuThreads} ${pluralForm('es', cpuThreads, { one: 'hilo', other: 'hilos' })}  Disco ${disk}`, demandMemory: (value) => `memoria ${value}`, demandGpuMemory: (value) => `memoria de GPU ${value}`, demandCpu: (threads) => `CPU ${threads} ${pluralForm('es', threads, { one: 'hilo', other: 'hilos' })}`, demandDisk: (value) => `disco ${value}`, demandNone: 'no usa recursos locales', listSep: ', ', clauseSep: ', ', sources: { system: 'sistema', setting: 'ajustes', 'unified-estimate': 'estimado a partir de memoria unificada', unknown: 'desconocido', statfs: 'espacio libre en el volumen de staging' }, capacity: (amounts, unified) => `Capacidad: ${amounts}${unified ? ' (memoria unificada: la memoria de GPU también cuenta como memoria)' : ''}`, capacitySources: (memory, gpuMemory, cpu, disk) => `  Orígenes: memoria ${memory}, memoria de GPU ${gpuMemory}, CPU ${cpu}, disco ${disk}`, systemReserve: (amounts) => `Reserva del sistema: ${amounts}`, interactiveReserve: (amounts) => `Reserva interactiva: ${amounts}`, leased: (amounts) => `Asignado: ${amounts}`, backgroundAvailable: (amounts) => `Disponible para segundo plano: ${amounts}`, interactiveAvailable: (amounts) => `Disponible para interacción: ${amounts}`, leasesHeader: 'Asignaciones:', leasesNone: 'Asignaciones: ninguna', leaseHolder: (holder) => `usa ${holder}`, leaseQueue: (queue) => `cola ${queue}`, holdersHeader: 'Procesos residentes:', holderState: (users, processes) => `${users > 0 ? `en uso por ${users} ${pluralForm('es', users, { one: 'tarea', other: 'tareas' })}` : 'inactivo'}, ${processes} ${pluralForm('es', processes, { one: 'proceso sigue en ejecución', other: 'procesos siguen en ejecución' })}`, waitingHeader: 'En espera:', waitingNone: 'En espera: ninguno', waitingAdmission: 'esperando admisión',
};
