import type { JobsMessages } from './jobs-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const ptBR: JobsMessages = {
  help: `Uso:
  baocut jobs resources            Estado do agendamento de recursos: capacidade da máquina e sua origem, reservas,
                                   alocações, Model Workers residentes e o que os trabalhos na fila estão aguardando
  baocut jobs reconcile <jobId> retry|discard|apply
                                   Tratar trabalhos com resultado incerto ou não totalmente aplicado após um reinício:
                                   retry executa novamente (nova chamada, com autorizações e orçamento verificados de novo),
                                   discard abandona chamadas externas aguardando conciliação (o orçamento já cobrado
                                   não é devolvido), apply revalida o resultado mantido e o aplica ao vídeo`,
  usage: 'Uso: baocut jobs resources | baocut jobs reconcile <jobId> retry|discard|apply', badDecision: (choices) => `A decisão de conciliação deve ser uma de: ${choices.join(', ')}`, jobStates: { queued: 'Na fila', running: 'Em andamento', completed: 'Concluído', failed: 'Falhou', cancelled: 'Cancelado', interrupted: 'Interrompido', 'needs-reconciliation': 'Precisa de conciliação' }, applicationStates: { pending: 'Pendente', validating: 'Confirmando', committed: 'Aplicado', 'stale-input': 'Destino alterado', rejected: 'Rejeitado', cancelled: 'Não aplicado' }, remoteStates: { 'not-applicable': 'sem execução remota', 'not-submitted': 'não enviado', cancelled: 'cancelado remotamente', 'cancel-unsupported': 'a execução remota não permite cancelamento', unknown: 'estado remoto desconhecido' }, costStates: { none: 'sem cobrança', possible: 'pode ter sido cobrado', charged: 'cobrado' },
  cancellation: (stoppedLocally, remote, cost) => `${stoppedLocally ? 'parado localmente' : 'não parado localmente'}, ${remote}, ${cost}`, cancellationLine: (text) => `Cancelamento: ${text}`, requeued: (attempt, jobId) => `De volta à fila (tentativa ${attempt}): ${jobId}`, discarded: (jobId) => `Descartado: ${jobId}`, appliedTo: (videoId, recovered) => `Aplicado ao vídeo ${videoId}${recovered ? ' (já havia sido confirmado anteriormente; o recibo foi registrado agora)' : ''}`, notApplied: (state, error) => `Não aplicado: ${state}${error ? ` (${error})` : ''}`, noApplicationRecord: 'sem registro de aplicação', statusLine: (state, code) => `Estado: ${state}${code ? `  ${code}` : ''}`, budgetSettled: (basis, calls) => `Orçamento liquidado: ${basis}, ${calls} ${pluralForm('pt-BR', calls, { one: 'chamada', other: 'chamadas' })}`, unknown: 'desconhecido',
  amounts: (memory, gpuMemory, cpuThreads, disk) => `Memória ${memory}  Memória GPU ${gpuMemory}  CPU ${cpuThreads} ${pluralForm('pt-BR', cpuThreads, { one: 'thread', other: 'threads' })}  Disco ${disk}`, demandMemory: (value) => `memória ${value}`, demandGpuMemory: (value) => `memória GPU ${value}`, demandCpu: (threads) => `CPU ${threads} ${pluralForm('pt-BR', threads, { one: 'thread', other: 'threads' })}`, demandDisk: (value) => `disco ${value}`, demandNone: 'não usa recursos locais', listSep: ', ', clauseSep: ', ', sources: { system: 'sistema', setting: 'configurações', 'unified-estimate': 'estimado a partir da memória unificada', unknown: 'desconhecido', statfs: 'espaço livre no volume temporário' }, capacity: (amounts, unified) => `Capacidade: ${amounts}${unified ? ' (memória unificada: a memória GPU também conta como memória)' : ''}`, capacitySources: (memory, gpuMemory, cpu, disk) => `  Origens: memória ${memory}, memória GPU ${gpuMemory}, CPU ${cpu}, disco ${disk}`, systemReserve: (amounts) => `Reserva do sistema: ${amounts}`, interactiveReserve: (amounts) => `Reserva interativa: ${amounts}`, leased: (amounts) => `Alocado: ${amounts}`, backgroundAvailable: (amounts) => `Disponível em segundo plano: ${amounts}`, interactiveAvailable: (amounts) => `Disponível para interação: ${amounts}`, leasesHeader: 'Alocações:', leasesNone: 'Alocações: nenhuma', leaseHolder: (holder) => `usa ${holder}`, leaseQueue: (queue) => `fila ${queue}`, holdersHeader: 'Processos residentes:', holderState: (users, processes) => `${users > 0 ? `em uso por ${users} ${pluralForm('pt-BR', users, { one: 'tarefa', other: 'tarefas' })}` : 'ocioso'}, ${processes} ${pluralForm('pt-BR', processes, { one: 'processo ainda em execução', other: 'processos ainda em execução' })}`, waitingHeader: 'Aguardando:', waitingNone: 'Aguardando: nenhum', waitingAdmission: 'aguardando admissão',
};
