import type { JobsMessages } from './jobs-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const it: JobsMessages = {
  help: `Uso:
  baocut jobs resources            Stato della pianificazione delle risorse: capacità del computer e origine, riserve,
                                   allocazioni, Model Worker residenti e risorse attese dalle attività in coda
  baocut jobs reconcile <jobId> retry|discard|apply
                                   Gestisce attività con risultato incerto o non applicato completamente dopo un riavvio:
                                   retry esegue di nuovo (nuova chiamata, autorizzazioni e budget verificati di nuovo),
                                   discard abbandona le chiamate esterne in attesa di riconciliazione (il budget già addebitato
                                   non viene rimborsato), apply verifica di nuovo il risultato conservato e lo applica al video`,
  usage: 'Uso: baocut jobs resources | baocut jobs reconcile <jobId> retry|discard|apply', badDecision: (choices: readonly string[]) => `La decisione di riconciliazione deve essere una tra: ${choices.join(', ')}`,
  jobStates: { queued: 'In coda', running: 'In corso', completed: 'Completato', failed: 'Non riuscito', cancelled: 'Annullato', interrupted: 'Interrotto', 'needs-reconciliation': 'Richiede riconciliazione' }, applicationStates: { pending: 'In attesa', validating: 'Registrazione in corso', committed: 'Applicato', 'stale-input': 'Destinazione cambiata', rejected: 'Rifiutato', cancelled: 'Non applicato' }, remoteStates: { 'not-applicable': 'nessun servizio remoto', 'not-submitted': 'non inviato', cancelled: 'annullato da remoto', 'cancel-unsupported': 'il servizio remoto non può annullare', unknown: 'stato remoto sconosciuto' }, costStates: { none: 'nessun addebito', possible: 'potrebbe essere stato addebitato', charged: 'addebitato' }, cancellation: (stoppedLocally: boolean, remote: string, cost: string) => `${stoppedLocally ? 'interrotto localmente' : 'non interrotto localmente'}, ${remote}, ${cost}`, cancellationLine: (text: string) => `Annullamento: ${text}`, requeued: (attempt: number, jobId: string) => `Rimesso in coda (tentativo ${attempt}): ${jobId}`, discarded: (jobId: string) => `Scartato: ${jobId}`,
  appliedTo: (videoId: string, recovered: boolean) => `Applicato al video ${videoId}${recovered ? ' (era già stato registrato la volta precedente; la ricevuta è stata registrata ora)' : ''}`, notApplied: (state: string, error: string | null) => `Non applicato: ${state}${error ? ` (${error})` : ''}`, noApplicationRecord: 'nessun registro di applicazione', statusLine: (state: string, code: string | null) => `Stato: ${state}${code ? `  ${code}` : ''}`, budgetSettled: (basis: string, calls: number) => `Budget contabilizzato: ${basis}, ${pluralForm('it', calls, { one: `${calls} chiamata`, other: `${calls} chiamate` })}`, unknown: 'sconosciuto',
  amounts: (memory: string, gpuMemory: string, cpuThreads: number, disk: string) => `Memoria ${memory}  Memoria GPU ${gpuMemory}  CPU ${cpuThreads} thread  Disco ${disk}`, demandMemory: (value: string) => `memoria ${value}`, demandGpuMemory: (value: string) => `memoria GPU ${value}`, demandCpu: (threads: number) => `CPU ${threads} thread`, demandDisk: (value: string) => `disco ${value}`, demandNone: 'non usa risorse locali', listSep: ', ', clauseSep: ', ', sources: { system: 'sistema', setting: 'impostazioni', 'unified-estimate': 'stimato dalla memoria unificata', unknown: 'sconosciuto', statfs: 'spazio libero sul volume staging' },
  capacity: (amounts: string, unified: boolean) => `Capacità: ${amounts}${unified ? ' (memoria unificata: la memoria GPU viene conteggiata anche nella memoria)' : ''}`, capacitySources: (memory: string | undefined, gpuMemory: string | undefined, cpu: string | undefined, disk: string | undefined) => `  Origini: memoria ${memory}, memoria GPU ${gpuMemory}, CPU ${cpu}, disco ${disk}`, systemReserve: (amounts: string) => `Riserva di sistema: ${amounts}`, interactiveReserve: (amounts: string) => `Riserva interattiva: ${amounts}`, leased: (amounts: string) => `Allocato: ${amounts}`, backgroundAvailable: (amounts: string) => `Disponibile per il background: ${amounts}`, interactiveAvailable: (amounts: string) => `Disponibile per le operazioni interattive: ${amounts}`, leasesHeader: 'Allocazioni:', leasesNone: 'Allocazioni: nessuna', leaseHolder: (holder: string) => `usa ${holder}`, leaseQueue: (queue: string) => `coda ${queue}`, holdersHeader: 'Processi residenti:',
  holderState: (users: number, processes: number) => `${users > 0 ? `in uso da ${pluralForm('it', users, { one: `${users} attività`, other: `${users} attività` })}` : 'inattivo'}, ${pluralForm('it', processes, { one: `${processes} processo ancora in esecuzione`, other: `${processes} processi ancora in esecuzione` })}`, waitingHeader: 'In attesa:', waitingNone: 'In attesa: nessuna', waitingAdmission: 'in attesa di ammissione',
};
