import type { TasksMessages } from './tasks-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const it: TasksMessages = {
  help: `Uso:
  baocut tasks contract <task id> [--revision <n>]
                                   Mostra il contratto di un’attività: obiettivo, ambito, vincoli, elenco da non modificare,
                                   risultati da consegnare, modalità di accesso, budget e utilizzo, verifiche di accettazione e risultati
  baocut tasks history <task id>   Cronologia delle revisioni del contratto (chi ha cambiato quali campi e quando)
  baocut tasks list --conversation <session id>
                                   Ultimo contratto di ogni attività in una sessione`,
  usage: 'Uso: baocut tasks contract <task id> [--revision <n>] | history <task id> | list --conversation <session id>', revisionPositive: '--revision deve essere un intero positivo', changeBy: { user: 'te', agent: 'l’agente', runtime: 'Runtime (predefinito)' }, changeReason: { created: 'creato', updated: 'modificato', mode: 'modalità di accesso cambiata', goal: 'obiettivo cambiato' }, outcomeLabels: { passed: 'Superato', failed: 'Non riuscito', skipped: 'Saltato' }, change: (by: string, reason: string, fields: readonly string[], at: string) => `${reason} da ${by}${fields.length > 0 ? `: ${fields.join(', ')}` : ''}, ${at}`,
  wholeVideo: 'il video intero', entity: (id: string) => `entità ${id}`, entityProperties: (id: string, paths: readonly string[]) => `${paths.join(', ')} dell’entità ${id}`, frames: (sequenceId: string, from: number, to: number, trackIds: readonly string[]) => `fotogrammi ${from}–${to} della sequenza ${sequenceId}${trackIds.length ? ` (tracce ${trackIds.join(', ')})` : ''}`, protection: (id: string, videoId: string, what: string, note: string | null) => `${id}  video ${videoId}: ${what}${note ? ` (${note})` : ''}`, noBudget: 'Nessun limite (valgono solo i budget delle singole autorizzazioni)',
  calls: (calls: number, reserved: number, max: number | null) => `${calls}${reserved ? `+${reserved} ${pluralForm('it', reserved, { one: 'riservata', other: 'riservate' })}` : ''}${max !== null ? `/${max}` : ''} ${pluralForm('it', max === null ? calls + reserved : max, { one: 'chiamata', other: 'chiamate' })}`, budget: (calls: string, spent: string | null, reserved: string | null, cap: string | null, unknownCostCalls: number) => `${calls}${spent ? `, spesi ${spent}` : ''}${reserved ? `, riservati ${reserved}` : ''}${cap ? `, limite ${cap}` : ''}${unknownCostCalls ? ` (${unknownCostCalls} con costo sconosciuto)` : ''}`, latest: 'ultima', latestIs: (revision: number) => `l’ultima è la revisione ${revision}`, contractHead: (taskId: string, revision: number, latest: string, change: string) => `Attività ${taskId}  revisione del contratto ${revision} (${latest})  ${change}`, goal: (goal: string) => `Obiettivo: ${goal}`, sessionVideo: (conversationId: string, videoId: string | null, baseRevision: string | null) => `Sessione: ${conversationId}  Video: ${videoId ?? 'nessuno'}${baseRevision ? ` (versione ${baseRevision})` : ''}`,
  scope: (s) => `Ambito: ${s.videoId ? `video ${s.videoId}` : 'nessun video specificato'}${s.sequenceId ? `, sequenza ${s.sequenceId}` : ''}${s.itemIds.length ? `, selezionati ${s.itemIds.join(', ')}` : ''}${s.range ? `, ${s.range.from}–${s.range.to} s` : ''}`, access: (mode: string, scopeRef: string) => `Modalità di accesso: ${mode}  Ambito dei permessi: ${scopeRef}`, budgetLine: (budget: string) => `Budget: ${budget}`, supersedes: (taskId: string, stopped: boolean) => `Sostituisce: attività ${taskId} (il lavoro precedente ${stopped ? 'è stato interrotto' : 'rimane come candidato'})`, constraints: (empty: boolean) => empty ? 'Vincoli: nessuno' : 'Vincoli:', protectedRefs: (empty: boolean) => empty ? 'Da non modificare: nessuno' : 'Da non modificare:', deliverable: (kind: string, stage: string, language: string | null) => `${kind}→${stage}${language ? ` (${language})` : ''}`, deliverables: (items: readonly string[]) => items.length ? `Da consegnare: ${items.join(', ')}` : 'Da consegnare: non specificato', checks: (empty: boolean) => empty ? 'Verifiche di accettazione: nessuna' : 'Verifiche di accettazione:', outcome: (label: string, byAgent: boolean, note: string | null) => `${label} (registrato da ${byAgent ? 'l’agente' : 'te'}${note ? `: ${note}` : ''})`, notRecorded: 'non registrato', checkLine: (id: string, kind: string, required: boolean, description: string, outcome: string) => `  ${id}  [${kind}${required ? ', richiesto' : ''}] ${description} — ${outcome}`, noContracts: 'Nessun contratto', historyLine: (revision: number, change: string, mode: string) => `Revisione ${revision}  ${change}  modalità ${mode}`, noTasks: 'Questa sessione non ha ancora attività', listLine: (taskId: string, revision: number, mode: string, goal: string) => `${taskId}  revisione ${revision}  ${mode}  ${goal}`,
};
