import type { TasksMessages } from './tasks-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const ptBR: TasksMessages = {
  help: `Uso:
  baocut tasks contract <task id> [--revision <n>]
                                   Mostrar o contrato de uma tarefa: objetivo, escopo, restrições, lista do que não alterar,
                                   entregas, modo de acesso, orçamento e uso, verificações de aceitação e resultados
  baocut tasks history <task id>   Histórico de revisões do contrato (quem alterou quais campos e quando)
  baocut tasks list --conversation <session id>
                                   Contrato mais recente de cada tarefa de uma sessão`, usage: 'Uso: baocut tasks contract <task id> [--revision <n>] | history <task id> | list --conversation <session id>', revisionPositive: '--revision deve ser um inteiro positivo', changeBy: { user: 'você', agent: 'o agente', runtime: 'Runtime (padrão)' }, changeReason: { created: 'criado', updated: 'alterado', mode: 'modo de acesso alterado', goal: 'objetivo alterado' }, outcomeLabels: { passed: 'Passou', failed: 'Falhou', skipped: 'Ignorado' }, change: (by, reason, fields, at) => `${reason} por ${by}${fields.length > 0 ? `: ${fields.join(', ')}` : ''}, ${at}`, wholeVideo: 'o vídeo inteiro', entity: (id) => `entidade ${id}`, entityProperties: (id, paths) => `${paths.join(', ')} da entidade ${id}`, frames: (sequenceId, from, to, trackIds) => `quadros ${from}–${to} da sequência ${sequenceId}${trackIds.length ? ` (faixas ${trackIds.join(', ')})` : ''}`, protection: (id, videoId, what, note) => `${id}  vídeo ${videoId}: ${what}${note ? ` (${note})` : ''}`, noBudget: 'Sem limite (apenas o orçamento de cada autorização se aplica)', calls: (calls, reserved, max) => `${calls}${reserved ? `+${reserved} reservadas` : ''}${max !== null ? `/${max}` : ''} ${pluralForm('pt-BR', max ?? calls + reserved, { one: 'chamada', other: 'chamadas' })}`,
  budget: (calls, spent, reserved, cap, unknownCostCalls) => `${calls}${spent ? `, ${spent} gastos` : ''}${reserved ? `, ${reserved} reservados` : ''}${cap ? `, limite ${cap}` : ''}${unknownCostCalls ? ` (${unknownCostCalls} com custo desconhecido)` : ''}`, latest: 'mais recente', latestIs: (revision) => `a mais recente é a revisão ${revision}`, contractHead: (taskId, revision, latest, change) => `Tarefa ${taskId}  revisão do contrato ${revision} (${latest})  ${change}`, goal: (goal) => `Objetivo: ${goal}`, sessionVideo: (conversationId, videoId, baseRevision) => `Sessão: ${conversationId}  Vídeo: ${videoId ?? 'nenhum'}${baseRevision ? ` (versão ${baseRevision})` : ''}`, scope: (s) => `Escopo: ${s.videoId ? `vídeo ${s.videoId}` : 'nenhum vídeo especificado'}${s.sequenceId ? `, sequência ${s.sequenceId}` : ''}${s.itemIds.length ? `, selecionados ${s.itemIds.join(', ')}` : ''}${s.range ? `, ${s.range.from}–${s.range.to} s` : ''}`, access: (mode, scopeRef) => `Modo de acesso: ${mode}  Escopo de permissão: ${scopeRef}`, budgetLine: (budget) => `Orçamento: ${budget}`, supersedes: (taskId, stopped) => `Substitui: tarefa ${taskId} (o trabalho da tarefa anterior ${stopped ? 'foi parado' : 'é mantido como candidato'})`, constraints: (empty) => empty ? 'Restrições: nenhuma' : 'Restrições:', protectedRefs: (empty) => empty ? 'Não alterar: nenhum' : 'Não alterar:', deliverable: (kind, stage, language) => `${kind}→${stage}${language ? ` (${language})` : ''}`, deliverables: (items) => items.length ? `Entregas: ${items.join(', ')}` : 'Entregas: não especificadas', checks: (empty) => empty ? 'Verificações de aceitação: nenhuma' : 'Verificações de aceitação:', outcome: (label, byAgent, note) => `${label} (registrado por ${byAgent ? 'o agente' : 'você'}${note ? `: ${note}` : ''})`, notRecorded: 'não registrado', checkLine: (id, kind, required, description, outcome) => `  ${id}  [${kind}${required ? ', obrigatório' : ''}] ${description} — ${outcome}`, noContracts: 'Nenhum contrato', historyLine: (revision, change, mode) => `Revisão ${revision}  ${change}  modo ${mode}`, noTasks: 'Esta sessão não tem tarefas ainda', listLine: (taskId, revision, mode, goal) => `${taskId}  revisão ${revision}  ${mode}  ${goal}`,
};
