import { pluralForm } from '@baocut/protocol';
import type { TemplatesMessages } from './templates-copy.ts';
export const de: TemplatesMessages = {
 help: `Verwendung:
  baocut templates                 Verfügbare Vorlagen anzeigen (integriert und in <BAOCUT_HOME>/templates),
                                   dazu nicht geladene Vorlagenordner mit Fehlerursachen
  baocut templates show <id>       Wichtige Manifestangaben und den vollständigen Inhalt von prompt.md anzeigen`,
 kindLabels: { scene: 'Szenenvorlage', example: 'Beispiel' }, originLabels: { builtin: 'Integriert', user: 'Benutzer' }, spec: (ratio, seconds) => `${ratio ?? 'automatisches Seitenverhältnis'} · ${seconds ? `${seconds} s` : 'automatische Dauer'}`, summaryLine: (title, summary) => `${title}: ${summary}`, diagnosticHead: (origin, dir, code, message) => `Vorlage aus ${origin}: ${dir} (${code}): ${message}`, folder: (path) => `  Ordner: ${path}`, none: 'Keine Vorlagen verfügbar', skipped: (n) => pluralForm('de', n, { one: `${n} Vorlagenordner übersprungen:`, other: `${n} Vorlagenordner übersprungen:` }), detailHead: (title, id, version, kind, origin) => `${title} (${id} v${version}, ${kind}, ${origin})`, meta: (category, spec, language) => `Kategorie: ${category}  Seitenverhältnis und Dauer: ${spec}  Sprache: ${language}`, author: (author, source, license) => `Autor: ${author} (${source}, ${license})`, tags: (tags) => `Tags: ${tags.join(', ')}`, sample: (sample) => `Zum Beispiel: ${sample}`, cover: (file) => `Titelbild: ${file}`, preview: (file) => `Vorschau: ${file}`, asset: (path, type, note) => `Material: ${path} (${type})${note ? ` ${note}` : ''}`, verification: (v) => `Geprüft: ${v.date} ${v.engine} v${v.version} ${v.outcome}${v.output ? `, Export ${v.output.ratio} · ${v.output.seconds} s` : ''}${v.missing.length ? `, fehlt: ${v.missing.join(', ')}` : ''}`, templateFlag: (value) => `--template erwartet eine Vorlagen-ID (kebab-case, siehe baocut templates): ${value}`,
};
