import type { TemplatesMessages } from './templates-copy.ts';
import { pluralForm } from '@baocut/protocol';
export const es: TemplatesMessages = {
 help: `Uso:
  baocut templates                 Listar plantillas de creación disponibles (integradas y en <BAOCUT_HOME>/templates),
                                   junto con las carpetas de plantillas que no se cargaron y sus motivos
  baocut templates show <id>       Mostrar los puntos clave del manifiesto y prompt.md completo`,
 kindLabels: { scene: 'Plantilla de escena', example: 'Ejemplo' }, originLabels: { builtin: 'Integrada', user: 'Usuario' }, spec: (ratio, seconds) => `${ratio ?? 'relación automática'} · ${seconds ? `${seconds} s` : 'duración automática'}`, summaryLine: (title, summary) => `${title}: ${summary}`, diagnosticHead: (origin, dir, code, message) => `Plantilla ${origin} ${dir} (${code}): ${message}`, folder: (path) => `  Carpeta: ${path}`, none: 'No hay plantillas disponibles', skipped: (n) => `Se omitieron ${n} ${pluralForm('es', n, { one: 'carpeta de plantilla', other: 'carpetas de plantillas' })}:`, detailHead: (title, id, version, kind, origin) => `${title} (${id} v${version}, ${kind}, ${origin})`, meta: (category, spec, language) => `Categoría: ${category}  Relación y duración: ${spec}  Idioma: ${language}`, author: (author, source, license) => `Autor: ${author} (${source}, ${license})`, tags: (tags) => `Etiquetas: ${tags.join(', ')}`, sample: (sample) => `Prueba a decir: ${sample}`, cover: (file) => `Portada: ${file}`, preview: (file) => `Vista previa: ${file}`, asset: (path, type, note) => `Material: ${path} (${type})${note ? ` ${note}` : ''}`, verification: (v) => `Verificado: ${v.date} ${v.engine} v${v.version} ${v.outcome}${v.output ? `, exportación ${v.output.ratio} · ${v.output.seconds} s` : ''}${v.missing.length ? `, falta ${v.missing.join(', ')}` : ''}`, templateFlag: (value) => `--template acepta un ID de plantilla (kebab-case, consulta baocut templates): ${value}`,
};
