import { intlLocale } from '@baocut/protocol';
import { revealLabel } from '../../copy.ts';
import type { ToolsMessages } from './tools-copy.ts';

export const zhHans: ToolsMessages = {
  gallery: {
    title: '工具',
    lede: '给一份文件或一段文字，直接调用模型完成处理，结果保存到 Space。无需连接 Agent。',
    ledeNote: '生成的结果会自动列进 Space（存在这台电脑上），也可以下载另存一份。',
    planned: '即将推出',
    foot: '更多工具会陆续加进来：转换格式、抽取音轨、截取片段、批量加字幕等。',
    loading: '正在读取模型状态…',
    open: (name: string) => `打开${name}`,
  },
  page: {
    back: '工具',
    hotkey: '⌘↵',
  },
  planned: {
    title: '即将推出',
    body: (reason: string) => `${reason}。这个工具的页面会在能力接进来以后打开。`,
    back: '回到全部工具',
  },
  save: {
    view: '在 Space 中查看',
  },
  output: {
    title: '产物',
    savedIn: (dir: string) => `保存在 ${dir}`,
    movie: '写进的视频',
    open: '打开编辑',
    inSpace: '在 Space 中查看',
    get reveal() {
      return revealLabel();
    },
    revealFailed: (message: string) => `没能在文件夹中显示：${message}`,
    handover: '交给 Agent',
    handedOver: (created: boolean, name: string, title: string) =>
      created ? `已新建会话，带上了「${name}」：改好那句话再发送` : `回到「${title}」，带上了「${name}」：改好那句话再发送`,
    handoverFailed: (message: string) => `没能交给 Agent：${message}`,
    untitled: '未命名会话',
    nextLabel: '接着用',
    newMovieNote: '素材留在原处，新视频里只做链接，不复制文件。',
    newMovieGo: '新建并打开',
    newMovieCancel: '取消',
    newMovieDone: (name: string) => `已用 ${name} 新建视频`,
    newMovieEmpty: (reason: string) => `视频建好了，但没能放进素材：${reason}`,
    newMovieFailed: (message: string) => `没能新建视频：${message}`,
  },
  entryTool: {
    menu: '用工具处理…',
    menuLabel: (name: string) => `用工具处理「${name}」`,
    factTool: '工具',
    factPlace: '位置',
    saveDir: '（默认保存位置）',
    rerunHint: '回到工具页，参数已经填好；改不改都由你。',
  },
  record: {
    more: '更多',
    reuse: '带回左边再改一版',
    copyText: '复制文字',
    copyPrompt: '复制提示词',
    copied: '已复制',
    copyFailed: '复制失败',
    task: '在后台任务里查看',
    remove: '删除这条记录',
    removed: (name: string) => `已删除 ${name}`,
    removeNote: '只从这一页藏起来，后台任务里还在',
    cancel: '取消',
    cancelFailed: (message: string) => `取消失败：${message}`,
    requeue: '重新排队',
    retry: '再试一次',
    retried: '已重新提交',
    reconcile: '去处理',
    reconcileNote: '结果不明的这一条要你决定再试或放弃；处理之前不能删除。',
    ahead: (n: number) => (n ? `排队中 · 前面还有 ${n} 条` : '排队中'),
    download: (ext: string) => `下载 ${ext}`,
    downloadFailed: (message: string) => `下载失败：${message}`,
    openFailed: (message: string) => `打不开这个结果：${message}`,
    loadingMedia: '正在读取…',
    noFile: '没有生成文件',
    live: (n: number) => `${n} 条进行中`,
    count: (n: number) => `${n} 条`,
    progressLabel: (title: string, phase: string) => `「${title}」${phase}`,
    play: (title: string) => `播放「${title}」`,
    unsettled: (failure: string) => `${failure}。结果不明的这一条要你决定再试或放弃；处理之前不能删除。`,
  },
  tts: {
    title: '生成语音',
    submit: '生成语音',
    textLabel: '要念的文字',
    textPlaceholder: (max: number) => `输入要念的文字。按句号、问号或换行分段，一次最多 ${max} 字。`,
    clear: '清空',
    sample: '填一段示例',
    model: '模型',
    manage: '管理语音模型…',
    modelPicker: '语音合成模型',
    noModel: '还没有可用的语音合成模型',
    noModelBody: '在设置 › 模型 › 语音合成 › 云端模型里连接一家服务商（填密钥），这里就能选它的模型。',
    goConnect: '去连接',
    voice: '声音',
    voiceLabel: '音色',
    customVoice: '音色 ID',
    customVoicePlaceholder: '服务商账号里的音色 ID',
    style: '风格',
    stylePlaceholder: '可选 · 一句话描述语气，例如：像深夜电台一样慢一点',
    styleLabel: '风格说明',
    roll: '换一句',
    speed: '语速',
    speedRange: (provider: string, min: number, max: number, instruct: boolean) =>
      `${provider} 收 ${min}–${max}×${instruct ? ' · 也可以写进风格里' : ''}`,
    noSpeed: (provider: string) => `${provider} 没有数值语速 · 快慢写进风格里`,
    resetSpeed: '回到默认',
    options: '语言与细节',
    language: '语言',
    languageNote: (provider: string, langs: string, auto: boolean) => `${provider} 会念${langs}${auto ? ' · 自动时按文字判断' : ''}`,
    format: '格式',
    seed: '种子',
    seedPlaceholder: '留空随机',
    seedNote: '服务商尽力复现，不保证 · 同样的文字每次可能略有不同',
    noSeed: '云端服务不保证复现，没有种子 · 同样的文字每次可能略有不同',
    local: '本机合成',
    side: '生成记录',
    empty: '还没有生成过',
    emptyBody: '写好文字、选好声音，按「生成语音」。',
    sideFoot: '生成的音频存在保存位置，也列在 Space 的「音频」里；「下载」另存一份到你选的位置。云端合成走服务商的接口，按服务商的规则计费。',
    reused: (name: string) => `已带回 ${name} 的文字与设置`,
    submitted: '已开始生成',
    submitFailed: (message: string) => `没有开始：${message}`,
  },
  frame: {
    model: '模型',
    goSettings: '去设置',
    speechNoun: '语音合成模型',
    imageNoun: '生图模型',
    textNoun: '文本模型',
    saveTitle: '保存位置',
    saveTo: '保存到 ',
    defaultDir: '默认保存位置',
    settingDir: '设置里的保存位置',
    backToDefault: '改回默认',
    change: '更改…',
    pickTitle: '选择这次的保存位置',
    pickFailed: (message: string) => `没能选择文件夹：${message}`,
    saveNote: '结果作为 Space 条目出现，文件保存在这个目录；重名时加序号，不覆盖已有文件。',
    saveFoot: (note: string, once: boolean) => `${note}${once ? '只改这一次，' : ''}默认位置在设置 › 通用里改。`,
  },
  gate: {
    connected: '已连接',
    installed: '已安装',
    localGroup: '本机 · 不联网',
    localWhere: (why: string) => `${why} · 设置 › 模型 › 本地模型`,
    download: (name: string) => `先下载 ${name}`,
    downloadBody: '下载不占任务队列，装好后这一页的主按钮就能按；生成时与本机语音模型共用同一个重活槽，一次只跑一只。',
    downloadButton: '下载…',
    downloading: (pct: number | null) => (pct === null ? '正在下载…' : `正在下载 · ${pct}%`),
    downloadBodyPaused:
      '下载不占任务队列，装好后这一页的主按钮就能按；生成时与本机语音模型共用同一个重活槽，一次只跑一只。下载停在一半，继续下载会从这里续传。',
    resume: '继续下载…',
    manageLocal: '管理本地模型…',
    localUnavailable: (name: string) => `${name} 在这台电脑上不可用`,
    localUnavailableBody: (why: string) => `${why}。可以换用可用的云端模型。`,
    connect: (provider: string) => `先连接 ${provider}`,
    ttsBody: '在设置 › 模型 › 语音合成 › 云端模型里填这家的密钥；同一把密钥给语音识别 / 文本生成 / 图像生成共用。',
    imageBody: '在设置 › 模型 › 图像生成 › 云端模型里填这家的密钥；同一把密钥给语音识别 / 文本生成 / 语音合成共用。',
    textBody: '在设置 › 模型 › 文本生成 › 云端模型里填这家的密钥；同一把密钥给语音识别 / 语音合成 / 图像生成共用。',
    unavailable: (provider: string) => `${provider} 现在不可用`,
    goConnect: '去连接',
    switchTo: (name: string) => `换用可用的 ${name}`,
    downloadSize: (size: string) => `下载 ${size}`,
    switchToInstalled: (name: string) => `换用已装的 ${name}`,
    ttsDownloadBody: '下载不占任务队列，装好后这一页的主按钮就能按。',
    ttsDownloadBodyPaused: '下载不占任务队列，装好后这一页的主按钮就能按。下载停在一半，继续下载会从这里续传。',
  },
  image: {
    title: '生成图片',
    submit: '生成图片',
    promptLabel: '要画的画面',
    promptPlaceholder: '描述你要的画面：主体、场景、风格、光线、构图。写得越具体越像。',
    clear: '清空',
    sample: '填一句示例',
    refs: '参考图',
    pickRefs: '选参考图',
    refsNote: '这一版的生成接口还不带参考图',
    model: '模型',
    manage: '管理生图模型…',
    modelPicker: '生图模型',
    noModel: '还没有可用的生图模型',
    noModelBody: '在设置 › 模型 › 图像生成 › 云端模型里连接一家服务商（填密钥），这里就能选它的模型。',
    localNote: '局域网里的其他电脑还没有接进这一版；Codex 画图在会话里用。',
    aspect: '画幅',
    aspectAuto: '这只模型不让选尺寸，由服务商定',
    count: '数量',
    countNote: (max: number) => `一次最多 ${max} 张`,
    advanced: '高级',
    expand: '展开',
    collapse: '收起',
    seed: '种子',
    seedPlaceholder: '留空随机',
    seedNote: '云端不保证复现',
    seedNoteLocal: '同种子同权重可复现',
    steps: '步数',
    stepsNote: (def: number) => `默认 ${def} · 越多越慢`,
    side: '生成记录',
    empty: '还没有生成过',
    emptyBody: '写好画面、选好模型，按「生成图片」。',
    sideFoot: '生成的图片存在保存位置，也列在 Space 的「图片」里；「下载」另存一份到你选的位置。云端生成的图服务商可能留副本。',
    again: '再来一版',
    againDone: '已带回这一版的提示词与设置 · 种子留空重新随机',
    failed: (message: string) => `没生成出来 · ${message}`,
    retry: '再试一次',
    drop: '不要了',
    retried: '已重新提交',
    cancelled: '已取消',
    submitted: '已开始生成',
    submitFailed: (message: string) => `没有开始：${message}`,
    chars: (n: number, max: number | null) => (max ? `${n} / ${max} 字` : `${n} 字`),
    alt: (name: string, prompt: string) => `${name}：${prompt}`,
  },
  text: {
    title: '文本生成',
    submit: '生成文本',
    lede: '输入内容与要求，直接调用文本模型，生成的文档自动保存到 Space。',
    inputLabel: '生成要求',
    material: '附带素材',
    materialAdd: '从 Space 附上…',
    materialRemove: '不附了',
    materialNote: '可以附上 Space 里的一份文档或字幕，它的文字接在生成要求后面一起发给模型。',
    materialPicked: (name: string) => `附上「${name}」的文字`,
    inputPlaceholder: '描述要生成的内容，也可以粘贴原文并说明改写或摘要要求',
    sample: '填入示例',
    clear: '清空',
    model: '文本模型',
    manage: '管理文本模型',
    modelPicker: '文本模型',
    noModel: '还没有可用的文本模型',
    noModelBody: '在设置 › 模型 › 文本生成 › 云端模型里连接一家服务商（填密钥），这里就能选它的模型。',
    side: '生成记录',
    viewInSpace: '在 Space 中查看',
    empty: '还没有生成结果',
    emptyBody: '完成后会自动保存到 Space。',
    sideFoot: '全文存在这台电脑上，列在 Space 的「文档」里（文件名「生成文本-日期-时间」）；「下载」另存一份到你选的位置。云端调用走服务商的接口，按 token 计费。',
    waiting: '等待模型返回…',
    copy: '复制',
    download: '下载',
    copyFailed: (message: string) => `复制失败：${message}`,
    previewCut: (shown: number, total: number) => `这里只显示开头 ${shown.toLocaleString(intlLocale())} 字；复制与下载是全文（${total.toLocaleString(intlLocale())} 字）。`,
    truncated: '到了这只模型单次输出的上限，后面的内容被截断了。',
    failed: (message: string) => `没生成出来 · ${message}`,
    retry: '再试一次',
    drop: '不要了',
    retried: '已重新提交',
    cancelled: '已取消',
    againDone: '已带回这一条的要求与模型',
    submitted: '已开始生成',
    submitFailed: (message: string) => `没有开始：${message}`,
  },
  transcribe: {
    title: '转录',
    submit: '开始转录',
    lede: '把视频或音频变成可编辑的文稿与字幕。',
    drop: '拖入视频或音频',
    pick: '选择文件',
    change: '更换文件',
    clearFile: '不用这份',
    notMedia: '请选择视频或音频文件',
    noPath: '拿不到这份文件在磁盘上的路径（从网页或别的应用拖进来的不行），请用「选择文件」。',
    mode: '转录方式',
    local: '本地模型',
    cloud: '云端 API',
    model: '语音模型',
    noModels: '没有可选的模型',
    language: '语言',
    manageLocal: '管理语音模型',
    manageCloud: '管理 API 连接',
    side: '转录记录',
    empty: '还没有转录结果',
    emptyBody: '能直接转录一份文件以后，结果会列在这里。',
  },
  transcode: {
    compressTitle: '压缩视频',
    mergeTitle: '合并视频',
    extractTitle: '提取音频',
    switchLabel: '视频文件工具',
    switchCompress: '压缩',
    switchMerge: '合并',
    switchExtract: '提取音频',
    extractLede: '去掉画面，只留音轨：AAC、MP3、Opus、FLAC 原样复制进 .m4a、.mp3、.ogg、.flac，其余重新编码为 AAC（.m4a）。选几个文件就各取一份，原文件不动。',
    extractSubmit: '提取音频',
    filesExtract: '视频或音频文件',
    dropExtract: '把视频拖进来',
    dropExtractSub: '或者从电脑里选。取出其中的声音，保存成一个音频文件；选几个就各取一份。',
    extractAudio: '需要重新编码时',
    extractAudioHint: '放不进常见容器的音轨重新编码为 AAC，按这个码率。',
    compressLede: '把视频重新编码得小一些，发消息、传网盘前先压一压。选几个文件就各压一份，原文件不动。',
    mergeLede: '把几段视频按顺序首尾接成一个文件，不用先建视频。各段参数一致时直接流复制，快、画质不变；不一致时重新编码。',
    chip: '在这台电脑上用 ffmpeg 编码 · 不上传',
    compressSubmit: '压缩视频',
    mergeSubmit: '合并视频',
    filesCompress: '视频文件',
    filesMerge: '片段 · 按这个顺序首尾相接',
    dropCompress: '把视频拖进来',
    dropCompressSub: '或者从电脑里选。支持 mp4 / mov / mkv / webm 等常见格式；选几个就各压一份。',
    dropMerge: '把要接起来的视频拖进来',
    dropMergeSub: '至少两段。按这里的顺序首尾相接，之后还能拖着换顺序。',
    pick: '选择视频…',
    add: '添加视频…',
    dropMore: '还可以继续拖进来',
    dragLabel: (name: string) => `拖动以调整「${name}」的顺序`,
    clearAll: '全部移出',
    sortByName: '按文件名排',
    pathLabel: '或者粘贴文件的完整路径',
    pathPlaceholder: '/Users/…/clip.mp4',
    pathAdd: '加入',
    spaceAdd: '从 Space 添加…',
    spaceDone: '收起 Space',
    spaceItem: (kind: string) => `Space · ${kind}`,
    spaceGone: 'Space 里找不到这个条目了',
    moveUp: '上移',
    moveDown: '下移',
    remove: '移出',
    listLabel: '选好的视频',
    dragHint: '拖着这一列换顺序（也可以聚焦后按回车拖），或者用行尾的上下箭头。',
    files: (n: number) => `${n} 个文件`,
    clips: (n: number) => `${n} 段`,
    noPath: '拿不到这份文件在磁盘上的路径（从网页或别的应用拖进来的不行），请用「选择视频…」或粘贴路径。',
    rateTitle: '压到多小',
    byQuality: '按画质',
    byBitrate: '按码率',
    quality: '画质',
    videoKbps: '视频码率',
    bitrateHint: '体积约等于 码率 × 时长。界面读不到源文件的时长，没法按目标体积替你算码率。',
    more: '更多设置',
    expand: '展开',
    collapse: '收起',
    height: '分辨率',
    heightHint: '按画面高度封顶，只往下缩；竖屏视频也按高度算。',
    codec: '编码',
    audio: '音频',
    audioHint: '声音统一重编成 AAC。',
    saveNote: '结果作为 Space 条目出现，文件保存在这个目录；不覆盖已有的文件，重名时加序号（-2、-3）。',
    mergeHow: '怎么接',
    mergeHowBody:
      '由 Runtime 读完各段再决定：编码、分辨率、帧率、像素格式、音轨、采样率、声道都一致时直接流复制，下面的设置不生效；有不一致时按第一段的画面重新编码，其余各段缩放补边对齐，没有声音的段配上同样长的静音。用了哪一种、为什么，写在右边的记录里。',
    reencodeTitle: '需要重新编码时',
    ffmpegChecking: '正在检测 ffmpeg…',
    ffmpegCheckFailed: (message: string) => `没能检测 ffmpeg：${message}`,
    recheck: '重新检测',
    unavailable: '现在不能用',
    submitted: '已开始处理',
    submitFailed: (message: string) => `没能开始：${message}`,
    side: '处理记录',
    loading: '正在读取记录…',
    empty: '还没有处理过',
    emptyBody: '选好文件、按下按钮，进度会出现在这里。',
    sideFoot:
      '压缩、合并与提取音频的记录列在一起。结果保存到保存位置，不覆盖已有文件；在这里删除记录不会删文件，后台任务里也还在。',
    get reveal() {
      return revealLabel();
    },
    revealFailed: (message: string) => `没能在文件夹中显示：${message}`,
    copyCommand: '复制 ffmpeg 命令',
    commandNote: '路径只留了文件名',
    again: '带回左边再来一版',
    againDone: '已带回这一条的文件与设置',
    cancelledLine: '已取消 · 没有产出文件',
    requeue: '重新排队',
    retry: '再试一次',
    retried: '已重新提交',
    drop: '不要了',
    failed: (message: string) => `没有做完 · ${message}`,
    raw: 'ffmpeg 原文',
    noOutput: '没有输出文件',
  },
  toolsHome: {
    lede: '不经过会话，直接做一件确定的事，无需连接 Agent。结果保存到默认保存位置，并作为条目出现在 Space 里，可以接着用别的工具处理、以此新建视频，或交给 Agent 继续。',
    foot: 'Space 里的条目也能直接送进工具：在 Space 中打开一个条目，选「用工具处理…」。',
    statusFailed: (message: string) => `读不到工具状态，卡片上的现状可能不准：${message}`,
  },
  picker: {
    label: '选一个视频',
    spaceLabel: '从 Space 里选',
    countKinds: (kinds: string, n: number) => `收${kinds} · ${n} 个可选`,
    emptySpaceTitle: 'Space 里没有能用的条目',
    emptySpaceBody: (kinds: string) => `这个工具收${kinds}。换个名字搜索，或先从本机文件开始。`,
    search: '搜索 Space',
    searchPlaceholder: '按名字搜索',
    countTranscript: (n: number) => `${n} 个有文稿可选，其余置灰`,
    count: (n: number) => `${n} 个可选`,
    noProject: '未归入项目',
    minutes: (n: number) => `${n} 分钟`,
    emptyTitle: '没有匹配的视频',
    emptyBody: '换个名字搜索，或先在 Space 里新建一个。',
    loading: '正在读取视频…',
    failed: (message: string) => `读不到视频列表：${message}`,
    pending: (n: number) => `还有 ${n} 个视频没读完内容，文稿可能列不全`,
    scanning: 'Space 还在第一次扫描，列表可能不全',
    shown: (shown: number, total: number) => `列出 ${shown} / ${total} 个`,
    more: (n: number) => `再列 ${n} 个`,
  },
  source: { label: '从哪里开始' },
  project: {
    label: '放进哪个项目',
    noneBody: '新建的视频要放进一个项目。还没有项目：先在首页新建一个，再回来。',
  },
  grant: {
    label: '发送到在线服务前确认',
    title: '这次要把数据发到在线服务',
    to: (recipient: string) => `发给 ${recipient}`,
    what: (what: string) => `内容：${what}`,
    cost: (cost: string) => `预计费用：${cost}`,
    remember: '同意一次，同一家服务、同一种数据以后不再问；在设置 › 隐私里可以收回。',
    agree: '同意并继续',
    hintLocal: '不想发送就换一个本机模型，本机模型不发送任何数据。',
    hintCloud: '不想发送就先不做：这一步只有在线服务能做。',
  },
  run: {
    run: '运行',
    side: '运行记录',
    loading: '正在读取记录…',
    empty: '还没有运行过',
    emptyBody: '开始之后进度与结果都在这里，也在后台任务里。',
    olderInTasks: (n: number) => `更早的 ${n} 次在后台任务里`,
    steps: '处理步骤',
    progress: (title: string) => `${title}进度`,
    attempt: (n: number) => ` · 第 ${n} 次尝试`,
    background: '这次运行也在后台任务里，离开这一页照样跑完。',
    cancel: '取消',
    unknown: '没有说明原因',
    failedBody: (error: string, keepsVideo: boolean) =>
      `${error.replace(/[。.]$/, '')}。已完成的步骤${keepsVideo ? '与已经建好的视频' : ''}会保留，重试从这一步开始。`,
    cancelledBody: '已完成的步骤会保留，重试从停下的那一步开始。',
    retry: '从这一步重试',
    retried: '已从停下的那一步重新开始',
    retryFailed: (message: string) => `没能重试：${message}`,
    open: '打开编辑',
    noVideo: '在 Space 里还找不到这个视频，稍等一下再看。',
    noOutputs: '这次运行的产物还没列进 Space，稍等一下再看。',
    again: '再做一次',
    backToForm: '回到设置',
    inTasks: '在后台任务中查看',
    waiting: '已提交，正在等后台任务列出这次运行…',
    started: '已开始，进度在这一页与后台任务里',
    submitFailed: (message: string) => `没有开始：${message}`,
    ambiguousTitle: '这个视频的主轨上有几个素材',
    ambiguousBody: '选一个要转录的素材，用它重新开始一次。这里只拿得到素材 ID，名字请在编辑器的素材面板里对照。',
    asset: (i: number, id: string) => `素材 ${i} · ${id}`,
    useAsset: '用这个素材重新开始',
  },
  form: {
    loading: '正在读取工具现状…',
    needFile: '先选一个视频或音频文件',
    needUrl: '先粘贴一个以 http:// 或 https:// 开头的链接',
    needVideo: '先选一个视频',
    needEntry: '先从 Space 里选一个条目',
    needProject: '先选一个项目',
    needLang: '先选目标语言',
    sameLang: '目标语言和原文相同，换一门语言',
    needTool: '视频下载工具还没就绪，先在下面的卡片里准备',
    toolUpdating: '正在更新视频下载工具，完成后再开始',
    needGrant: '先在下面确认要发送的数据',
    ready: '准备好了',
    noPicker: '这个环境打不开选择文件的对话框，请把文件拖进来。',
    notInRuntime: '这一版 Runtime 的工具目录里没有它，暂时不能用',
  },
  transcribeTool: {
    lede: '把视频或音频转成文稿和字幕。缺省得到一份文稿和一份字幕，放在保存位置；也可以新建一个视频，或写进 Space 里已有的视频。',
    targetTitle: '结果',
    targetNone: '文稿（.txt）和字幕（.srt）保存在下面的位置，各是 Space 里的一个条目，以后可以拿去翻译、生成语音或新建视频。',
    createFile: '素材留在原处，视频里只做链接，不复制文件。结果是这个项目里的一个新视频，带文稿和一条可编辑的字幕层。',
    createLink: '媒体下载到保存位置，视频里链接它，不再复制一份。结果是这个项目里的一个新视频，名字取页面标题，带一份文稿。',
    linkNote:
      '从链接开始由「下载视频」下载、新建视频后转写；这条路径不建字幕层，之后可以在编辑器的字幕面板里生成。下载不代表取得使用许可，发布前确认你有权使用这段内容。',
    asrTitle: '用哪个模型识别',
    mode: '转录方式',
    local: '本机模型',
    cloud: '在线服务',
    model: '语音模型',
    language: '转录语言',
    noModels: '还没有可选的模型',
    statusCloud: (ok: boolean, provider: string) => `${ok ? '已连接' : '未连接'} · ${provider} · 音轨会发到这家服务`,
    statusLocal: (ok: boolean) => (ok ? '已安装 · 在这台电脑上识别，不发送任何数据' : '模型还没安装'),
    noCloud: '还没有在线语音识别服务',
    noLocal: '这台电脑上还没有语音识别模型',
    manageCloud: '管理连接',
    manageLocal: '管理语音模型',
    linkAsr: '从链接开始时用默认的语音识别模型、自动检测语言：下载视频还不能选模型与语言。',
    modelNotReady: '选的语音模型现在不能用',
    more: '更多选项',
    speakers: '识别说话人',
    downloadPack: '下载',
    resumePack: '继续下载',
    needSpeakers: '先下载「说话人区分」，或关掉「识别说话人」',
    submit: '开始转录',
    submitLink: '下载并转录',
    autoDetect: '自动检测',
  },
  translate: {
    title: '翻译字幕',
    ledeVideo: '给转录过的视频加一份译文和目标语言的字幕层，原文不动。',
    ledeFile: '翻译一个字幕文件，条数与时间码不变；译好的文件保存到保存位置，不覆盖已有文件。',
    from: (name: string, lang: string) => `从「${name}」的${lang}文稿翻译。`,
    fromPending: '这个视频的内容还没读完：开始时由 Runtime 选文稿（只有一份时用它）。',
    document: '用哪份文稿',
    target: '翻译成',
    hasTranslation: '已有译文 · 会新增一份',
    bilingual: '双语显示（原文与译文上下两行）',
    fileDrop: '拖入 SRT 或 VTT 字幕文件',
    filePick: '选择字幕文件',
    fileChange: '更换文件',
    fileClear: '不用这份',
    fileFormats: '支持 SRT、WebVTT · 保留时间码',
    notSubtitle: '请选择 SRT 或 VTT 字幕文件',
    model: '文本模型',
    manageModels: '管理文本模型',
    grantHint: '翻译只能用在线文本模型；不想发送就先不翻译，内容留在这台电脑上。',
    submit: '开始翻译',
    subtitleFiles: '字幕文件',
    docLang: (lang: string) => `${lang}文稿`,
  },
  dub: {
    title: '翻译配音',
    lede: '用译文给转录过的视频配一组新的声音。结果写进这个视频，原来的配音保留。',
    translation: '用哪份译文',
    newTranslation: '先翻译成另一种语言',
    stale: (n: number) => `${n} 句原文改过，译文空着`,
    pending: '这个视频的内容还没读完，列不出已有的译文；可以先翻译一份。',
    target: '翻译成',
    engine: '配音引擎',
    engineLine: (langs: string) => `在线服务 · 会念${langs}`,
    notSpeak: (name: string, lang: string) => `${name} 不会念${lang}，换一只会念的引擎。`,
    manageEngines: '管理配音引擎',
    original: '原声',
    originalOptions: { duck: '压低原声', mute: '静音原声', keep: '保留原声' },
    grantHint: '不想发送就先不配音；配音引擎与翻译用的文本模型这一版都是在线服务。',
    submit: '开始配音',
  },
  linkTool: {
    title: '下载视频',
    lede: '粘贴视频链接，下载到本机。需要文稿时，可以在下载完成后自动转录。',
    sourceNote: '支持单个视频页面与媒体直链。下载进度和结果保留在后台任务中。',
    submit: '开始下载',
    submitTranscribe: '下载并转录',
    cookies: '网站登录',
    detecting: '正在检测…',
    redetect: '重新检测浏览器',
    detectingFirst: '正在检测这台电脑上的浏览器…',
    detectFailed: (error: string | null) => `没能检测本机浏览器${error ? `：${error}` : ''}。现在只能匿名下载，可以点「重新检测浏览器」再试。`,
    detected: (n: number) => (n ? `检测到 ${n} 个浏览器` : '没有找到浏览器的 Cookie'),
    browsersLabel: '读取哪些浏览器的 Cookie',
    allBrowsers: '所有浏览器',
    transcribe: '下载后转录',
    transcribeNote: '使用默认语音识别模型，自动检测语言，保存 TXT 文稿和 SRT 字幕。转录失败时已下载的视频仍保留。',
    project: '转录结果放到项目（可选）',
    noProject: '不放到项目',
    projectNote: '仅关联项目，文件仍保存在上方指定的目录。',
    editLink: '修改链接或 Cookie 设置',
  },
  taskRun: {
    stopped: '运行停住了',
    viewResult: '查看结果',
    backToTool: '回到工具',
  },
  retranscribe: {
    destTitle: '落点',
    destLabel: '转录结果写到哪',
    nameLabel: '新视频的名字',
    newVideoNote: (project, video) =>
      `新视频放在${project ? `「${project}」` : '同一个项目'}里，链接同一份素材、不复制文件，带新文稿和一条可编辑的字幕层；「${video}」和它的译文、字幕、配音不动。`,
    impactTitle: '取代后会怎样',
    impactTranslations: '译文',
    impactDubs: '配音',
    impactNone: '这部视频没有译文',
    editedTitle: '你改过这部视频的文稿',
    editedBody: '改错字、润色、分段这些修改只在当前文稿里。取代会丢掉它们（撤销能回来）；想留着就改选「新建视频」。',
    editedAccept: '仍要取代',
    retryTitle: '上次转录失败',
    retryBody: (error, model, ago) =>
      `${error ?? '没有记下失败原因'}。${['上次', model, ago].filter(Boolean).join(' · ')}。模型、语言和识别说话人已按上次填好，可以改了再开始。`,
    undo: '撤销',
    refreshStale: '刷新过期译文',
  },
};
