import type { JobsDubMessages } from './dub.ts';
import { pluralForm } from '../../i18n.ts';

export const it: JobsDubMessages = {
  label: 'Doppiaggio tradotto',
  description: 'Doppia in un’altra lingua una trascrizione del video: la traduce prima se manca una traduzione, sintetizza la voce frase per frase, la allinea ai tempi delle frasi originali e la applica al video come gruppo di doppiaggio (una traccia di doppiaggio). Non viene avviato alcun agente.',
  stepFreezeSource: 'Leggi originale', stepTranslate: 'Traduci', stepAssemble: 'Assembla traduzione', stepWrite: 'Scrivi traduzione', stepCheck: 'Verifica traduzione', stepSeparate: 'Separa voce e sottofondo', stepSynthesize: 'Sintetizza frasi', stepAlign: 'Allinea tempi', stepApply: 'Applica doppiaggio',
  regroupConflict: (p: { params: string }) => `La rigenerazione della voce delle frasi (regroup) usa traduzione, lingua, voce e trattamento dell’audio originale dal piano di doppiaggio del gruppo, quindi non può essere combinata con ${p.params}`,
  orTranslationId: 'oppure deve essere specificato translationId', translationIdNoTranslate: 'Con translationId non viene tradotto nulla, quindi style, glossary, glossaries, textProvider e textModel non si applicano', mustBeBooleanValue: 'deve essere un booleano', mustBeObject: 'deve essere un oggetto', unitsCount: (p: { max: number }) => `deve contenere da 1 a ${p.max} ID di unità di traduzione`, mustBeUnique: 'non può contenere duplicati', seedInvalid: (p: { max: number }) => `deve essere 'new' o un intero da 0 a ${p.max}`,
  videoNotOpen: 'Il video non è aperto', translationFromOther: (p: { translationId: string; from: string; expected: string }) => `La traduzione ${p.translationId} è stata tradotta da ${p.from}, anziché ${p.expected}`, translationLanguage: (p: { translationId: string; language: string; expected: string }) => `La traduzione ${p.translationId} è in ${p.language}, anziché ${p.expected}`,
  noDocument: (p: { documentId: string }) => `Il video non contiene il documento ${p.documentId}`, notTranslation: (p: { documentId: string; kind: string }) => `Il documento ${p.documentId} è ${p.kind}, anziché una traduzione`, translationNotUsable: (p: { translationId: string; schema: string }) => `La traduzione ${p.translationId} non è ${p.schema}, quindi non può essere usata per il doppiaggio`,
  noPlan: (p: { groupId: string }) => `Il video non contiene un piano di doppiaggio per questo gruppo (${p.groupId})`, groupGone: (p: { groupId: string }) => `Questo gruppo di doppiaggio (${p.groupId}) non ha più elementi sulla timeline`, planNoTranslation: 'Il piano di doppiaggio non registra una traduzione',
  unitsNotInPlan: (p: { count: number; units: string }) => `${pluralForm('it', p.count, { one: `${p.count} frase non è`, other: `${p.count} frasi non sono` })} nel piano o nella traduzione di questo gruppo di doppiaggio: ${p.units}`,
  planNoVoice: 'Il piano di doppiaggio non registra provider, modello e voce usati per la sintesi', seedNotAccepted: (p: { model: string }) => `Il modello ${p.model} non accetta un seed`, videoClosed: 'Il video è stato chiuso', translationGone: 'Il documento della traduzione non è più nel video', translationNotSchema: (p: { schema: string }) => `La traduzione non è ${p.schema}`, translationNotFromTranscript: 'La traduzione non è stata creata da questa trascrizione', unitMissingIds: 'La traduzione contiene unità senza id o sourceSentenceId',
  separationNotConfigured: 'È stata richiesta la separazione di voce e sottofondo, ma non è configurata una capacità di separazione (separateAudio). Questo passaggio viene saltato e l’audio originale è trattato così com’è',
  unitsStale: (p: { count: number }) => pluralForm('it', p.count, { one: `${p.count} frase tradotta è obsoleta (l’originale o il glossario sono cambiati, oppure è stata segnata come obsoleta) e non è stata sintetizzata`, other: `${p.count} frasi tradotte sono obsolete (l’originale o il glossario sono cambiati, oppure sono state segnate come obsolete) e non sono state sintetizzate` }),
  nothingToDub: 'La traduzione non ha frasi da doppiare: sono tutte obsolete o vuote', separationUnavailable: 'La separazione di voce e sottofondo non è più disponibile', noSourceAsset: 'La trascrizione non ha un materiale di origine, quindi non può essere separata', sourceAssetMissing: 'Il materiale di origine della trascrizione non è disponibile', separationInvalid: 'Il risultato della separazione non rispetta il contratto', inputNoAudio: 'L’ingresso non contiene audio', stemNoAudio: (p: { name: string }) => `${p.name} non contiene audio`, stemSampleRate: (p: { name: string; rate: number; input: number }) => `La frequenza di campionamento di ${p.name} (${p.rate}) differisce da quella dell’ingresso (${p.input})`, stemDuration: (p: { name: string; duration: number; input: number }) => `${p.name} dura ${p.duration.toLocaleString('it')} secondi; l’ingresso dura ${p.input.toLocaleString('it')} secondi`,
  sentenceJob: (p: { n: number }) => `Frase ${p.n}`, audioUndecodable: 'Impossibile decodificare l’audio sintetizzato', outputNoAudio: 'Il risultato della sintesi non contiene audio',
  synthesisStopped: (p: { cause: string; synthesized: number; remaining: number }) => `${p.cause}. Frasi sintetizzate: ${p.synthesized}; frasi rimanenti: ${p.remaining}. Un nuovo tentativo sintetizza solo le rimanenti`, synthesisFailed: (p: { failed: number; synthesized: number }) => `Frasi con sintesi non riuscita: ${p.failed}. Le frasi sintetizzate correttamente (${p.synthesized}) vengono conservate; un nuovo tentativo sintetizza solo quelle non riuscite`,
  voicesUnavailableAll: (p: { speakers: string }) => `Le voci associate ai parlanti (${p.speakers}) non sono disponibili, quindi nessuna frase è stata sintetizzata. Correggi le voci (clonale di nuovo o aggiungi la dichiarazione di consenso), poi riprova`, voicesUnavailable: (p: { count: number; speakers: string }) => `Frasi non sintetizzate: ${p.count}, perché le voci associate ai loro parlanti (${p.speakers}) non sono disponibili; non è stata usata un’altra voce al loro posto`,
  mutedUnvoiced: (p: { count: number }) => `Elementi silenziati che contengono anche frasi non sintetizzate perché la loro voce non è disponibile: ${p.count}; anche l’audio originale di quelle frasi è stato silenziato`, unitsOverlong: (p: { count: number; tempo: number }) => `Frasi che ancora non rientrano nei tempi dopo l’accelerazione a ${p.tempo.toLocaleString('it')}× e l’uso del silenzio successivo: ${p.count}. Non sono state posizionate sulla timeline (occorre riscrivere il copione)`, unitsOffTimeline: (p: { count: number }) => `Le frasi originali di ${p.count} frasi tradotte non sono più sulla timeline, quindi queste non sono state posizionate`, nothingPlaced: 'Nessuna frase doppiata rientra nei tempi della timeline', artifactGone: (p: { artifactId: string }) => `Il risultato ${p.artifactId} non esiste più`, stretchNoAudio: 'Nessun audio dopo il cambio di velocità',
  videoClosedKept: 'Il video è stato chiuso; l’audio sintetizzato è conservato nei risultati', videoChanged: 'Il video è cambiato dopo l’allineamento, quindi non è stato applicato nulla. Un nuovo tentativo riallinea alla timeline attuale (l’audio sintetizzato viene riutilizzato)', sequenceGone: 'La sequenza non esiste più', backgroundMuted: 'L’audio originale è stato silenziato. Se contiene insieme voce, musica e suoni ambientali, anche il sottofondo scompare (il sottofondo non è stato separato)', noTrackOrPlanId: 'Non è stato ricevuto l’ID della traccia o del piano di doppiaggio dopo l’applicazione', applyRejected: 'La transazione di doppiaggio è stata rifiutata; l’audio sintetizzato è conservato nei risultati', planGone: 'Il piano di questo gruppo di doppiaggio non è più nel video', regroupRejected: 'La transazione per rigenerare il doppiaggio è stata rifiutata; l’audio sintetizzato è conservato nei risultati', planNotSchema: (p: { schema: string }) => `Il piano di doppiaggio non è ${p.schema}`,
  transactionLabel: (p: { language: string }) => `Doppiaggio (${p.language})`, regroupLabel: (p: { language: string }) => `Rigenera doppiaggio (${p.language})`, trackName: (p: { language: string }) => `Doppiaggio (${p.language})`, assetName: (p: { language: string; n: number }) => `Doppiaggio (${p.language}) frase ${p.n}`, takeAssetName: (p: { language: string; n: number; k: number }) => `Doppiaggio (${p.language}) frase ${p.n} · take ${p.k}`, itemName: (p: { n: number }) => `Doppiaggio ${p.n}`, backgroundName: (p: { language: string }) => `Sottofondo (${p.language})`, vocalsName: (p: { language: string }) => `Voce (${p.language})`, planName: (p: { language: string }) => `Piano di doppiaggio (${p.language})`, duckingName: (p: { language: string }) => `Il doppiaggio (${p.language}) attenua l’audio originale`,
};
