import type { JobsManagerMessages } from './job-manager.ts';

export const vi: JobsManagerMessages = {
runtimeStopping: 'Runtime đang tắt', jobNotFound: 'Tác vụ không tồn tại', noBundle: 'Không có gói mô hình này', noBundleId: (p) => `Không có gói mô hình này: ${p.bundleId}`, jobIdExists: 'ID tác vụ đã tồn tại', onlyHostedRerun: 'Chỉ tác vụ được lưu trữ mới chạy lại được theo cách này', notEnded: 'Tác vụ chưa hoàn tất', hintTooLong: 'Gợi ý thuật ngữ không được dài hơn 1200 ký tự', hintIgnored: (p) => `${p.model} không nhận gợi ý nhận dạng; gợi ý không được dùng`, onlyAudioVideo: 'Chỉ chép lời được tư liệu âm thanh hoặc video', pathNotAbsolute: 'Đường dẫn phải tuyệt đối', trackInvalid: 'track phải là số nguyên không âm', noGeneration: 'Runtime này không cung cấp khả năng tạo', videoNotOpen: 'Video chưa mở', contentHashInvalid: 'Mã băm nội dung phải là sha256:<hex>', timescaleInvalid: 'timescale phải là số nguyên dương', rangeInvalid: 'range không hợp lệ', bundleCannotTranscribe: 'Gói mô hình này không thể chép lời', bundleUnavailable: 'Gói mô hình hiện không khả dụng', localInferenceUnavailable: 'Suy luận cục bộ không khả dụng', invalidLanguageTag: (p) => `Thẻ ngôn ngữ BCP 47 không hợp lệ: ${p.tag}`, cannotReadInput: 'Không đọc được tệp đầu vào',
jobReconciling: 'Tác vụ này đang được khôi phục hoặc đối soát', openVideoToRetry: 'Video chưa mở; mở rồi thử lại', openVideoToApply: 'Video chưa mở; mở rồi áp dụng', receiptUnknownLater: 'Không tìm thấy biên nhận của lần lưu cuối; thử lại sau', receiptUnknown: 'Không tìm thấy biên nhận của lần lưu cuối', requeueCheckFailed: 'Kiểm tra trước khi xếp hàng lại thất bại', assetVersionGone: 'Tư liệu hoặc phiên bản không còn trong video', assetChanged: 'Nội dung tư liệu đã đổi', cannotRerun: 'Không thể chạy lại tác vụ này', cannotOpenVideoAfterRestart: 'Không mở được video sau khi khởi động lại', videoNotOpenNoPlace: 'Video chưa mở và chưa rõ vị trí', videoFolderGone: 'Thư mục video không còn tồn tại', videoReplaced: 'Vị trí ban đầu hiện có video khác', recoverFailed: 'Khôi phục tác vụ thất bại', interrupted: 'Tác vụ chưa hoàn tất trước khi Runtime dừng; bạn có thể gửi lại', needsReconciliation: 'Lệnh gọi gửi ra chưa phản hồi khi Runtime dừng nên chưa rõ phía từ xa đã chạy hoặc tính phí hay chưa. Chọn thử lại hoặc loại bỏ (không tự gửi lại)',
executeFailed: 'Chạy tác vụ thất bại', providerUnavailable: 'Nhà cung cấp không khả dụng', executorGone: 'Trình thực thi của tác vụ không còn', localCrashedAfterRetry: 'Tiến trình suy luận cục bộ vẫn gặp sự cố sau lần thử lại', transcribeFailedAfterRetry: 'Chép lời vẫn thất bại sau lần thử lại',
outputCountMismatch: (p) => `Có ${p.actual} đầu ra nhưng yêu cầu ${p.expected}`, outputNotInStaging: (p) => `Đầu ra ${p.n} không nằm trong thư mục staging`, outputMissing: (p) => `Đầu ra ${p.n} không tồn tại`, outputLengthMismatch: (p) => `Đầu ra ${p.n} có ${p.actual} byte nhưng khai báo ${p.declared}`, outputShaMismatch: (p) => `sha256 của đầu ra ${p.n} không khớp giá trị khai báo`, outputTypeMismatch: (p) => `Đầu ra ${p.n} là ${p.actual} nhưng yêu cầu ${p.expected}`, outputProblem: (p) => `Đầu ra ${p.n}: ${p.problem}`, noTextResult: 'Trình thực thi không trả về kết quả văn bản', textOutputCount: (p) => `Có ${p.actual} đầu ra; phải có 1`, textNotInStaging: 'Đầu ra không nằm trong thư mục staging', textMissing: 'Đầu ra không tồn tại', textLengthMismatch: (p) => `Đầu ra có ${p.actual} byte nhưng khai báo ${p.declared}`, textShaMismatch: 'sha256 của đầu ra không khớp giá trị khai báo', textTypeMismatch: (p) => `Đầu ra là ${p.actual} nhưng yêu cầu ${p.expected}`, notUtf8: 'Đầu ra không phải UTF-8 hợp lệ', notJson: 'Đầu ra không phải JSON hợp lệ', emptyOutput: 'Đầu ra rỗng', generatedInvalid: 'Đầu ra đã tạo không vượt qua kiểm tra giải mã',
asrFileNotInStaging: 'Tệp đầu ra không nằm trong thư mục staging', asrFileMissing: 'Tệp đầu ra không tồn tại', asrLengthMismatch: (p) => `Đầu ra có ${p.actual} byte nhưng phản hồi ghi ${p.declared}`, asrShaMismatch: 'sha256 của đầu ra không khớp phản hồi', asrContractInvalid: 'Đầu ra mô hình không đáp ứng baocut.asr-result/v1',
outputTruncated: (p) => `Đầu ra đạt giới hạn (${p.limit} token) và bị cắt; nội dung chưa đầy đủ`, saveCopyFailed: (p) => `Không ghi được bản sao trong ${p.dir}: ${p.reason}`,
applyError: 'Ghi vào video thất bại', transcribeLabel: 'Chép lời', voiceOverLabel: 'Tạo lồng tiếng', imageLabel: 'Tạo hình ảnh', videoClosed: 'Video đã đóng', assetGone: 'Tư liệu không còn trong video', assetChangedDuringTranscribe: 'Nội dung tư liệu đã đổi trong khi chép lời', generatedGone: 'Đầu ra đã tạo không còn tồn tại', asrGone: 'Đầu ra kết quả chép lời không còn tồn tại', asrNotJson: 'Đầu ra kết quả chép lời không phải JSON hợp lệ', asrInvalid: 'Đầu ra kết quả chép lời không khớp hợp đồng', targetGone: 'Đích không còn tồn tại', staleGeneratedKept: (p) => `${p.reason}; kết quả đã tạo được giữ lại`, protectedKept: (p) => `${p.generated ? 'Tạo' : 'Chép lời'} đã hoàn tất nhưng kết quả chạm đến phạm vi “không thay đổi” trong hợp đồng tác vụ nên chưa ghi vào video. Kết quả được giữ; người dùng quyết định có áp dụng hay không`, applyFailedKept: (p) => p.generated ? 'Đã tạo xong nhưng nhập vào video thất bại; kết quả được giữ' : 'Đã chép lời xong nhưng ghi vào video thất bại; kết quả được giữ',
};
