import type { JobsLocalProviderMessages } from './local-provider.ts';
import { pluralForm } from '../../i18n.ts';

export const it: JobsLocalProviderMessages = {
  assetUnreadable: 'Impossibile leggere il materiale', notHandled: (p) => `Il provider locale non esegue ${p.capability}`, referenceChanged: 'La registrazione di riferimento è cambiata dopo l’invio', referenceUnreadable: 'Impossibile leggere la registrazione di riferimento',
  speechOutputWrong: (p) => `L’output sintetizzato non è ${p.file} in staging`, stemOutputWrong: (p) => `L’output separato non è ${p.file} in staging`, speakersOutputWrong: (p) => `L’output dell’identificazione dei parlanti non è ${p.file} in staging`, imageNoInput: 'La generazione locale di immagini non ha un file di input', imageOutputWrong: (p) => `L’output immagine non è ${p.file} in staging`,
  runtimeStopping: 'Il Runtime si sta chiudendo', bundleRequired: 'L’inferenza locale richiede un pacchetto di modelli', bundleDisabled: 'Il pacchetto di modelli è disattivato', workerBusy: 'Il Worker di questo pacchetto di modelli sta eseguendo un’altra attività', workerVersionChanged: 'La versione del Worker è diversa dal primo tentativo, quindi non riproverà automaticamente',
  noOutput: 'job.run ha restituito completed senza un risultato', workerExitedDuringJob: 'Model Worker è terminato durante l’attività', inferenceFailed: (p) => `Inferenza non riuscita: ${p.code}`, stagingUnwritable: 'Impossibile scrivere l’output in staging; controlla lo spazio su disco', workerUnsupported: (p) => `Model Worker non supporta questa attività: ${p.message}`, jobRunReturned: (p) => `job.run ha restituito ${p.code}`,
  workerNotFound: 'Model Worker (model-worker) non trovato', workerCannotStart: 'Impossibile avviare Model Worker', workerExitedOnStart: 'Model Worker è terminato subito dopo l’avvio', handshakeFailed: 'Handshake di Model Worker non riuscito', contractMismatch: 'La versione del contratto di Model Worker non corrisponde', backendUnavailable: (p) => `Questo Model Worker non può usare il backend ${p.backend}`,
  cannotSeparate: 'Questo Model Worker non può ancora separare localmente voce e sottofondo con questo modello', cannotGenerateImage: 'Questo Model Worker non può ancora generare immagini localmente con questo modello', cannotDiarize: 'Questo Model Worker non può ancora identificare i parlanti localmente', cannotTranscribe: 'Questo Model Worker non può ancora trascrivere localmente con questo modello', cannotSynthesize: 'Questo Model Worker non può ancora eseguire la sintesi vocale locale con questo modello',
  loadFailed: (p) => `Caricamento del pacchetto di modelli non riuscito: ${p.reason}`, workerExitedOnLoad: 'Model Worker è terminato durante il caricamento',
  crashedRepeatedly: (p) => `${pluralForm('it', p.count, { one: `${p.count} arresto anomalo`, other: `${p.count} arresti anomali` })} in ${pluralForm('it', p.minutes, { one: `${p.minutes} minuto`, other: `${p.minutes} minuti` })}`,
  readingDroppedOne: (p) => `Il carattere ${p.at} non è stato sintetizzato con la lettura «${p.reading}» (${p.origin})`, readingDroppedRange: (p) => `I caratteri ${p.from}–${p.to} non sono stati sintetizzati con la lettura «${p.reading}» (${p.origin})`,
};
