import type { CommonMessages, ClientsMessages, ApprovalCardMessages, McpMessages, ModelApiMessages, WebMessages } from './services-copy.ts';

export const commonPtBR: CommonMessages = {
  copied: (label: string) => `${label} copiado`,
  copyFailed: "Não foi possível copiar. Selecione o texto e copie manualmente.",
  autostart: "Iniciar automaticamente ao abrir o BaoCut",
  stopsWithApp: "O serviço para quando você sai do BaoCut.",
  portLabel: "Porta",
  portIdle: (port: number) =>
    `Padrão é ${port}. Se ocupado, escolha outro: “Falha ao iniciar”, sem trocar porta automaticamente.`,
  portLive: "Mudar porta reinicia o serviço; conexões existentes caem.",
  portBusy: "Serviço iniciando ou parando. Tente em um momento.",
  portSaved: (port: number) => `Porta alterada para ${port}`,
  errorFix: "Tente outra porta ou feche o programa que está usando-a.",
  resetPort: "Usar Porta Padrão",
  portReset: (port: number) => `Porta redefinida ao padrão ${port}`,
  unavailableSub: "Este Runtime ainda não oferece o serviço; não pode iniciar.",
  started: (name: string) => `${name} iniciado`,
  stopped: (name: string) => `${name} parado`,
  startFailed: (reason: string) => `Não iniciou: ${reason}`,
  restartFailed: (reason: string) => `Salvo, mas não reiniciou com novas configurações: ${reason}`,
  section: {
    connect: "Conectar",
    clients: "Clientes e tokens",
    requests: "Solicitações recentes",
    settings: "Configurações",
  },

  levelLabel: "Operações permitidas",
  levelSaved: (title: string) => `Ações permitidas definidas para “${title}”. Efeito imediato.`,
  liveNote: "Alterações imediatas, sem reiniciar.",
  noRequests: "Ainda não há solicitações",
  requestMeta: (client: string, ago: string, outcome: string) => `${client} · ${ago} · ${outcome}`,
  needToken: "Exigir token de acesso",
  needTokenDesc: "Cada aplicativo envia seu token (Authorization: Bearer <token>) para conectar.",
  needTokenFixed:
    "Tokens sempre exigidos, não podem ser desativados. Cada aplicativo tem token revogável separadamente, mais seguro que sem token.",
  cancel: "Cancelar",

  lightsLabel: (labels: readonly string[]) => labels.join(", "),
};

export const clientsPtBR: ClientsMessages = {
  lede: "Dê token próprio a cada aplicativo. Mostrado só na criação, BaoCut guarda só hash. Revogue quando não precisar; aplicativo desconectado imediatamente.",
  empty: "Sem clientes. Crie e informe o token no aplicativo.",
  create: "Criar cliente",
  createTitle: "Criar cliente",
  nameLabel: "Nome do aplicativo",
  namePlaceholder: "Por exemplo, Claude Desktop",
  nameDesc: "Distingue chamadores no BaoCut. Histórico e aprovações mostram este nome.",
  confirmCreate: "Criar",
  cancel: "Cancelar",
  done: "Concluído",
  tokenTitle: (name: string) => `Token de “${name}”`,
  tokenOnce:
    "Token só visível agora. Fechar impede recuperação; se perder, revogue e crie outro.",
  tokenLabel: "Token",
  copyToken: "Copiar Token",
  copySnippetWithToken: "Copiar conexão (com token)",
  tokenCopiedLabel: "Token",
  snippetCopiedLabel: "Informações de conexão",
  meta: (created: string, used: string | null) => (used ? `Criado ${created} · Último uso ${used}` : `Criado ${created} · Nunca usado`),
  revoke: "Revogar",
  revokeTitle: (name: string) => `Revogar “${name}"?`,
  revokeBody:
    "Token para de funcionar e desconecta aplicativos. Irreversível; crie novo cliente e informe novo token para restaurar.",
  revokeConfirm: "Revogar",
  revoked: (name: string) => `Revogado “${name}”`,
};

export const approvalCardPtBR: ApprovalCardMessages = {
  title: (client: string, tool: string) => `${client} quer chamar “${tool}”`,
  noVideo: "Sem vídeo específico",
  video: (name: string) => `Vídeo “${name}”`,
  left: (s: number) => `${s} s restantes. Negado sem resposta.`,
  deny: "Negar",
  allow: "Permitir",
  allowOnce: "Permitir uma vez",
  allowPersist: "Permitir e lembrar",
  grantPersistNote:
    "“Permitir e lembrar” também autoriza permanentemente este vídeo (ou todos para chamadas sem vídeo), sem limites de gasto ou uso; a mesma saída não pergunta novamente.",
  allowed: "Solicitação permitida",
  denied: "Negado · cliente recebe erro",
  already: "Solicitação já terminou (expirou, tratada ou desconectada)",
};

export const mcpPtBR: McpMessages = {
  title: "Serviço MCP",
  lede: "BaoCut é servidor MCP para agentes de outras IAs: listar e ler vídeos, transcrições, editar, transcrever, exportar, sintetizar e gerar imagens com modelos disponíveis. Desativado por padrão. Todos os vídeos compartilhados, ou só escolhidos.",
  on: "O servidor MCP está em execução",
  off: "O servidor MCP está parado",
  error: "Falha ao iniciar o servidor MCP",
  connectHint:
    "Adicione em cliente HTTP MCP: endereço e token no cabeçalho (crie em “Clientes e tokens”). Endereço estável, sem nova configuração depois.",
  address: "Endereço MCP",
  copyAddress: "Copiar endereço do MCP",
  copySnippet: "Copiar informações de conexão",
  snippetLabel: "Informações de conexão",
  snippetNote: "Token fictício nos dados copiados; substitua pelo token deste aplicativo.",
  check: "Verificar servidor",
  checkReason: "Runtime ainda não oferece teste de integridade ao aplicativo. O cartão mostra o estado de escuta informado.",
  accessSection: "Escopo de acesso",
  scopeTitle: "Vídeos acessíveis",
  scopeDesc:
    "Todos compartilhados por padrão, inclusive futuros; agente usa videos_list. Pode marcar só alguns; outros não existem para clientes. Só projetos registrados aparecem.",
  scopeAll: "Todos os vídeos",
  scopeAllSub: (n: number) => `Incluindo futuros · ${n} agora`,
  scopePick: "Só vídeos marcados",
  scopeNone: "Sem vídeos em projetos registrados",
  scopeSaved: "Acesso atualizado. Efeito imediato.",
  levelDesc: "Essa permissão se aplica apenas a clientes MCP externos; não tem relação com o modo de acesso do agente integrado.",
  clientsTitle: "Clientes e tokens",
  toolsTitle: "Ferramentas",
  toolsLede:
    "Cliente conectado vê tools/list (muda com “Ações permitidas”). Parâmetro video vem de videos_list e aceita só “Vídeos acessíveis”.",
  toolsFixed:
    "Não pode configurar ferramentas individualmente nem ver parâmetros: abertas juntas por “Ações permitidas”; Runtime não fornece lista e parâmetros ao aplicativo.",
  toolsHiddenNote: "As ferramentas de escrita, tarefas e geração só são fornecidas quando “Operações permitidas” está definido como “Perguntar antes de alterar” ou “Permitir sem perguntar”.",
  copyTools: "Copiar tools/list",
  toggleTool: (name: string) => `Oferecer ${name}`,
};

export const modelApiPtBR: ModelApiMessages = {
  title: "API de modelos",
  lede: "Ferramentas OpenAI API (SDKs, CLI, aplicativos) usam modelos BaoCut para transcrever, sintetizar, gerar imagens e texto. Escuta só local. Só modelos locais por padrão; nuvem, nós e agentes ativados separadamente.",
  on: "API de modelos em execução",
  off: "API de modelos não iniciada",
  error: "API de modelos falhou ao iniciar",
  offSub: (base: string) => `Após iniciar, API compatível OpenAI em ${base}`,
  baseUrl: "URL base",
  copyBase: "Copiar Base URL",
  baseLede:
    "Caminhos iguais à OpenAI; só host e porta mudam. Use URL base e token como chave API. model deve ser de /v1/models (<provider>/<model> ou alias).",
  baseOff: "Acessível após iniciar. Veja configurações e documentação agora.",
  copySnippet: "Copiar variáveis de ambiente",
  snippetLabel: "Variáveis de ambiente",
  needKey: "Precisa de chave de API",
  needKeyFixed: "Chave API (token cliente) sempre exigida. Cada aplicativo tem sua chave revogável separadamente.",
  levels: {
    read: "Só lista modelos (GET /v1/models). Geração rejeitada.",
    ask: "Confirme cada geração no BaoCut. Negado após 50 segundos sem resposta.",
    auto: "Geração sem confirmação, melhor para uso individual.",
  },
  routingTitle: "Roteamento",
  routingLede:
    "Modelos locais sempre disponíveis. Ative cada tipo abaixo para encaminhar; desativado não aparece em /v1/models, pedido por nome retorna 404.",
  routingSaved: "Roteamento atualizado. Efeito imediato.",
  concurrency: "Solicitações simultâneas por cliente",
  concurrencyDesc: (max: number) => `Retorna 429 ao exceder. 1–${max}.`,
  limits: (upload: string, json: string) => `Envios de áudio até ${upload}; corpos JSON até ${json}.`,
  endpointsTitle: "Endpoints",
  endpointsLede: "Todos os caminhos sob a URL base.",
  endpointsFixed:
    "Não pode desligar por capacidade ou porta separada. Detalhes e “Testar” indisponíveis; aplicativo não vê token em texto e não envia pedidos.",
  modelsGroup: "Modelos",
  modelsGroupSub: "Listar e consultar modelos disponíveis e informações do serviço",
  capSwitch: (name: string) => `Oferecer ${name}`,
  ownPort: "Oferecer também em uma porta própria",
  aliasesTitle: "Aliases",
  aliasesLede:
    "model deve ser <provider>/<model> ou nome abaixo, senão 404. Cada nome aponta a modelo e capacidade. “Modelo padrão” segue o padrão do provedor.",
  aliasesEmpty: "Sem aliases; só <provider>/<model> funciona.",
  aliasName: "Nome",
  aliasCapability: "Capacidade",
  aliasTarget: "Aponta para",
  aliasAdd: "Adicionar nome",
  aliasAdded: (name: string) => `Adicionado “${name}”`,
  aliasRemove: (name: string) => `Excluir ${name}`,
  aliasRemoved: (name: string) => `Excluído “${name}”`,
  aliasNoTarget: "Sem provedores para esta capacidade",
  resetAliases: "Restaurar padrões",
  resetTitle: "Restaurar aliases padrão?",
  resetBody: "Volta à linha predefinida (whisper-1 para transcrição local padrão). Nomes adicionados excluídos.",
  resetDone: "Aliases padrão restaurados",
  modelsLoading: "Carregando modelos…",
};

export const webPtBR: WebMessages = {
  title: "Servidor Web",
  lede: "Abra BaoCut Web neste Mac para editar os mesmos vídeos. Escuta só local, sem acesso de outros dispositivos.",
  on: "O servidor Web está em execução",
  off: "O servidor Web está parado",
  error: "Falha ao iniciar o servidor Web",
  offSub: "Depois de iniciado, você pode abrir o BaoCut Web em um navegador.",
  open: "Abrir no Navegador",
  copyLink: "Copiar link de login",
  linkLabel: "Link de login",
  copyAddress: "Copiar Endereço",
  addressLabel: "Endereço",
  linkNote: "Primeiro entra por link de uso único, válido 2 minutos. Depois abra o endereço nas próximas 12 horas.",
  openFallback: "Não pode abrir navegador externo aqui. Link copiado; cole na barra de endereço.",
  sessionsTitle: "Sessões de navegador abertas",
  sessionsEmpty: "Nenhum navegador entrou. Clique “Abrir no navegador”.",
  revoke: "Sair",
  revokeTitle: "Desconectar este navegador?",
  revokeBody: "Conexão cai imediatamente. Para usar de novo, novo link de login.",
  revokeConfirm: "Sair",
  revoked: "Navegador desconectado",
  readOnly: "Somente leitura",
  readOnlyDesc: "Ativado: navegador só vê vídeos, transcrições e tarefas, sem alterar ou enviar tarefas.",
  readOnlySaved: (on: boolean): string => (on ? "Somente leitura definido. Efeito imediato." : "Navegadores podem alterar. Efeito imediato."),
  apiMoved: "A API compatível OpenAI agora é um serviço separado:",
  apiMovedLink: "API de modelos",
};
