import type { CommonMessages, ClientsMessages, ApprovalCardMessages, McpMessages, ModelApiMessages, WebMessages } from './services-copy.ts';

export const commonKo: CommonMessages = {
  copied: (label: string) => `${label} 복사됨`,
  copyFailed: '복사하지 못했습니다. 텍스트를 선택해 직접 복사하세요.',
  autostart: 'BaoCut을 열 때 자동으로 시작',
  stopsWithApp: 'BaoCut을 종료하면 서비스도 함께 멈춥니다.',
  portLabel: '포트',
  portIdle: (port: number) =>
    `기본값은 ${port}입니다. 사용 중이면 다른 포트를 고르세요. 서비스는 “시작 실패”로 표시되며 스스로 포트를 바꾸지 않습니다.`,
  portLive: '포트를 바꾸면 새 포트로 서비스가 다시 시작되며, 기존 연결은 끊깁니다.',
  portBusy: '서비스가 시작하거나 멈추는 중입니다. 잠시 후 다시 시도하세요.',
  portSaved: (port: number) => `포트를 ${port}(으)로 바꿨습니다`,
  errorFix: '다른 포트로 다시 시도하거나, 그 포트를 쓰는 앱을 먼저 종료하세요.',
  resetPort: '기본 포트 사용',
  portReset: (port: number) => `포트를 기본값 ${port}(으)로 되돌렸습니다`,
  unavailableSub: '이 버전의 BaoCut Runtime은 아직 이 서비스를 제공하지 않아 시작할 수 없습니다.',
  started: (name: string) => `${name} 시작됨`,
  stopped: (name: string) => `${name} 멈춤`,
  startFailed: (reason: string) => `시작하지 못했습니다: ${reason}`,
  restartFailed: (reason: string) => `저장했지만 새 설정으로 서비스를 다시 시작하지 못했습니다: ${reason}`,
  section: {
    connect: '연결',
    clients: '클라이언트와 토큰',
    requests: '최근 요청',
    settings: '설정',
  },
  levelLabel: '허용 동작',
  levelSaved: (title: string) => `허용 동작을 “${title}”(으)로 바꿨습니다. 바로 적용됩니다.`,
  liveNote: '변경 사항은 바로 적용되며 다시 시작할 필요가 없습니다.',
  noRequests: '아직 요청이 없습니다',
  requestMeta: (client: string, ago: string, outcome: string) => `${client} · ${ago} · ${outcome}`,
  needToken: '액세스 토큰 필요',
  needTokenDesc: '각 앱은 연결하려면 자기 토큰(Authorization: Bearer <token>)을 보내야 합니다.',
  needTokenFixed:
    '이 버전에서는 토큰이 항상 필요하며 끌 수 없습니다. 앱마다 따로 토큰을 받고 개별로 철회할 수 있어, 토큰을 쓰지 않는 것보다 안전합니다.',
  cancel: '취소',
  lightsLabel: (labels: readonly string[]) => labels.join(', '),
};

export const clientsKo: ClientsMessages = {
  lede: '연결할 앱마다 토큰을 하나씩 발급하세요. 토큰은 만들 때 한 번만 표시되며, BaoCut은 지문만 저장합니다. 더 이상 필요 없으면 철회하세요. 그 앱은 바로 연결이 끊깁니다.',
  empty: '아직 클라이언트가 없습니다. 하나를 만든 뒤, 연결할 앱에 그 토큰을 입력하세요.',
  create: '클라이언트 만들기',
  createTitle: '클라이언트 만들기',
  nameLabel: '앱 이름',
  namePlaceholder: '예: Claude Desktop',
  nameDesc: 'BaoCut에서 누가 호출하는지 구별하는 데만 쓰입니다. 요청 기록과 승인에 이 이름이 표시됩니다.',
  confirmCreate: '만들기',
  cancel: '취소',
  done: '완료',
  tokenTitle: (name: string) => `“${name}”의 토큰`,
  tokenOnce:
    '이 토큰은 지금 한 번만 볼 수 있습니다. 이 창을 닫으면 되찾을 수 없으니, 잃어버렸다면 철회하고 새로 만드세요.',
  tokenLabel: '토큰',
  copyToken: '토큰 복사',
  copySnippetWithToken: '연결 정보 복사(토큰 포함)',
  tokenCopiedLabel: '토큰',
  snippetCopiedLabel: '연결 정보',
  meta: (created: string, used: string | null) => (used ? `${created} 만듦 · 마지막 사용 ${used}` : `${created} 만듦 · 사용한 적 없음`),
  revoke: '철회',
  revokeTitle: (name: string) => `“${name}”을(를) 철회할까요?`,
  revokeBody:
    '이 클라이언트의 토큰은 바로 효력을 잃고, 이 토큰을 쓰는 앱은 즉시 연결이 끊깁니다. 이 작업은 되돌릴 수 없습니다. 다시 접근하려면 새 클라이언트를 만들고 새 토큰을 입력하세요.',
  revokeConfirm: '철회',
  revoked: (name: string) => `“${name}”을(를) 철회했습니다`,
};

export const approvalCardKo: ApprovalCardMessages = {
  title: (client: string, tool: string) => `${client}에서 “${tool}”을(를) 호출하려고 합니다`,
  noVideo: '특정 영상과 관련 없음',
  video: (name: string) => `영상 “${name}”`,
  left: (s: number) => `${s}초 남음. 응답이 없으면 거부됩니다.`,
  deny: '거부',
  allow: '허용',
  allowOnce: '이번만 허용',
  allowPersist: '허용하고 기억',
  grantPersistNote:
    '“허용하고 기억”을 고르면 지속 허가도 함께 발급됩니다. 범위는 이 영상(영상과 관련 없는 호출이면 모든 영상)이며, 비용과 사용 횟수 한도가 없고, 같은 외부 호출은 다시 묻지 않습니다.',
  allowed: '이 요청을 허용했습니다',
  denied: '거부됨 · 클라이언트는 오류를 받습니다',
  already: '이 요청은 이미 끝났습니다(시간 초과, 처리됨 또는 연결 끊김)',
};

export const mcpKo: McpMessages = {
  title: 'MCP 서비스',
  lede: 'BaoCut이 MCP 서버가 되어 다른 AI 앱의 Agent에게 도구를 제공합니다. 영상 목록 보기와 조회, 전사본 읽기, 편집, 전사와 내보내기 시작, 그리고 이 컴퓨터에서 쓸 수 있는 모델로 음성 합성과 이미지 생성을 할 수 있습니다. 기본으로 꺼져 있습니다. 기본으로 모든 영상을 공유하며, 일부만 공유할 수도 있습니다.',
  on: 'MCP 서비스 실행 중',
  off: 'MCP 서비스 시작 안 됨',
  error: 'MCP 서비스를 시작하지 못했습니다',
  connectHint:
    'HTTP MCP를 지원하는 클라이언트에서 서비스를 추가하세요. 주소를 입력하고 요청 헤더에 이 앱의 토큰을 넣으면 됩니다(“클라이언트와 토큰”에서 만듦). 주소는 바뀌지 않으므로 다음에 다시 설정할 필요가 없습니다.',
  address: 'MCP 주소',
  copyAddress: 'MCP 주소 복사',
  copySnippet: '연결 정보 복사',
  snippetLabel: '연결 정보',
  snippetNote: '복사한 설정에서 토큰은 자리 표시자입니다. 이 앱의 토큰으로 바꾸세요.',
  check: '서비스 확인',
  checkReason: 'Runtime은 아직 앱에 상태 점검 기능을 제공하지 않습니다. 서비스 카드의 상태는 Runtime이 보고하는 수신 대기 상태입니다.',
  accessSection: '접근 범위',
  scopeTitle: '접근 가능한 영상',
  scopeDesc:
    '기본으로 모든 영상(나중에 만드는 영상 포함)을 공유하며, Agent는 videos_list로 필요한 영상을 찾습니다. 일부만 체크할 수도 있으며, 선택하지 않은 영상은 클라이언트에게 존재하지 않는 것으로 보입니다. 등록된 프로젝트의 영상만 표시됩니다.',
  scopeAll: '모든 영상',
  scopeAllSub: (n: number) => `나중에 만드는 영상 포함 · 지금 ${n}개`,
  scopePick: '체크한 영상만',
  scopeNone: '등록된 프로젝트에 아직 영상이 없습니다',
  scopeSaved: '접근 범위를 업데이트했습니다. 바로 적용됩니다.',
  levelDesc: '이 설정은 외부 MCP 클라이언트에만 적용되며, 내장 Agent의 접근 모드에는 영향을 주지 않습니다.',
  clientsTitle: '클라이언트와 토큰',
  toolsTitle: '도구',
  toolsLede:
    '클라이언트가 연결되면 그 Agent가 tools/list에서 보는 도구는 아래와 같습니다(“허용 동작”에 따라 바뀜). video 파라미터는 videos_list에서 가져오며, “접근 가능한 영상”에 있는 영상만 받습니다.',
  toolsFixed:
    '이 버전에서는 도구를 하나씩 켜고 끄거나 각 도구의 파라미터를 볼 수 없습니다. 도구는 “허용 동작”에 따라 한꺼번에 열리며, Runtime은 도구 목록과 파라미터를 앱에 제공하지 않습니다.',
  toolsHiddenNote: '쓰기, 작업, 생성 도구는 “허용 동작”을 “변경 전 확인” 또는 “묻지 않고 허용”으로 설정해야 제공됩니다.',
  copyTools: 'tools/list 복사',
  toggleTool: (name: string) => `${name} 제공`,
};

export const modelApiKo: ModelApiMessages = {
  title: '모델 API',
  lede: 'OpenAI API를 쓰는 도구(SDK, 명령줄 도구, 다른 앱)가 BaoCut에서 쓸 수 있는 모델로 전사, 음성 합성, 이미지 생성, 텍스트 생성을 하게 합니다. 이 컴퓨터에서만 수신 대기합니다. 기본으로 이 컴퓨터의 모델만 쓰며, 클라우드, LAN 노드, Agent는 각각 켜야 합니다.',
  on: '모델 API 실행 중',
  off: '모델 API 시작 안 됨',
  error: '모델 API를 시작하지 못했습니다',
  offSub: (base: string) => `시작하면 ${base}에서 OpenAI 호환 API를 제공합니다`,
  baseUrl: 'Base URL',
  copyBase: 'Base URL 복사',
  baseLede:
    '경로는 OpenAI와 같고 호스트와 포트만 다릅니다. 도구의 Base URL을 이 주소로 바꾸고, API 키에는 이 앱의 토큰을 넣으세요. model에는 /v1/models가 나열하는 이름(<provider>/<model> 또는 아래의 별칭)을 쓰세요.',
  baseOff: '서비스를 시작해야 접근할 수 있습니다. 설정과 설명은 지금 볼 수 있습니다.',
  copySnippet: '환경 변수 복사',
  snippetLabel: '환경 변수',
  needKey: 'API 키 필요',
  needKeyFixed: '이 버전에서는 API 키(클라이언트 토큰)가 항상 필요하며 끌 수 없습니다. 앱마다 하나씩 받으며, 개별로 철회할 수 있습니다.',
  levels: {
    read: '모델 목록만 볼 수 있습니다(GET /v1/models). 생성 요청은 거부됩니다.',
    ask: '생성 요청마다 BaoCut에서 확인합니다. 50초 안에 아무도 응답하지 않으면 거부됩니다.',
    auto: '생성 요청을 확인 없이 실행합니다. 혼자만 쓸 때 알맞습니다.',
  },
  routingTitle: '라우팅',
  routingLede:
    '이 컴퓨터의 모델은 항상 쓸 수 있습니다. 아래의 각 유형으로 요청을 전달하려면 따로 켜야 합니다. 꺼진 유형은 /v1/models에 나타나지 않으며, 이름으로 요청하면 404가 반환됩니다.',
  routingSaved: '라우팅을 업데이트했습니다. 바로 적용됩니다.',
  concurrency: '클라이언트별 동시 요청 수',
  concurrencyDesc: (max: number) => `넘으면 429를 반환합니다. 1–${max}.`,
  limits: (upload: string, json: string) => `업로드(전사할 오디오)는 최대 ${upload}, JSON 요청 본문은 최대 ${json}입니다.`,
  endpointsTitle: '엔드포인트',
  endpointsLede: '모든 경로는 Base URL 아래에 있습니다.',
  endpointsFixed:
    '이 버전에서는 기능별로 엔드포인트를 끄거나 별도 포트에서 제공할 수 없습니다. 엔드포인트 세부 정보와 “사용해 보기”도 아직 없습니다(앱이 토큰 원문을 볼 수 없어 요청을 보낼 수 없음).',
  modelsGroup: '모델',
  modelsGroupSub: '사용할 수 있는 모델 나열 및 조회, 서비스 정보 확인',
  capSwitch: (name: string) => `${name} 제공`,
  ownPort: '별도 포트에서도 제공',
  aliasesTitle: '별칭',
  aliasesLede:
    '요청의 model은 <provider>/<model>이거나 아래 이름 중 하나여야 하며, 그 밖에는 404를 반환합니다. 이름 하나는 한 기능의 모델 하나를 가리킵니다. “기본 모델”을 가리키는 이름은 그 공급자의 기본값을 따릅니다.',
  aliasesEmpty: '아직 별칭이 없습니다. 지금은 <provider>/<model>만 쓸 수 있습니다.',
  aliasName: '이름',
  aliasCapability: '기능',
  aliasTarget: '대상',
  aliasAdd: '이름 추가',
  aliasAdded: (name: string) => `“${name}”을(를) 추가했습니다`,
  aliasRemove: (name: string) => `${name} 삭제`,
  aliasRemoved: (name: string) => `“${name}”을(를) 삭제했습니다`,
  aliasNoTarget: '이 기능에는 아직 공급자가 없습니다',
  resetAliases: '기본값 복원',
  resetTitle: '기본 별칭을 복원할까요?',
  resetBody: '표가 기본 행(이 컴퓨터의 기본 전사 모델을 가리키는 whisper-1)으로 되돌아갑니다. 추가한 이름은 삭제됩니다.',
  resetDone: '기본 별칭을 복원했습니다',
  modelsLoading: '모델을 불러오는 중…',
};

export const webKo: WebMessages = {
  title: 'Web 서비스',
  lede: '이 Mac의 브라우저에서 BaoCut Web을 열어 같은 영상을 편집합니다. 서비스는 이 컴퓨터에서만 수신 대기하므로, 네트워크의 다른 기기에서는 접근할 수 없습니다.',
  on: 'Web 서비스 실행 중',
  off: 'Web 서비스 시작 안 됨',
  error: 'Web 서비스를 시작하지 못했습니다',
  offSub: '시작하면 브라우저에서 BaoCut Web을 열 수 있습니다.',
  open: '브라우저에서 열기',
  copyLink: '로그인 링크 복사',
  linkLabel: '로그인 링크',
  copyAddress: '주소 복사',
  addressLabel: '주소',
  linkNote: '브라우저는 먼저 일회용 링크로 로그인합니다(2분 동안 유효, 한 번만 사용 가능). 그 뒤 12시간 동안은 주소만 열면 됩니다.',
  openFallback: '여기서는 외부 브라우저를 열 수 없습니다. 로그인 링크를 복사했으니 브라우저 주소창에 붙여 넣으세요.',
  sessionsTitle: '열린 브라우저 세션',
  sessionsEmpty: '아직 로그인한 브라우저가 없습니다. “브라우저에서 열기”를 클릭하세요.',
  revoke: '로그아웃',
  revokeTitle: '이 브라우저를 로그아웃할까요?',
  revokeBody: '연결이 바로 끊깁니다. 다시 쓰려면 새 로그인 링크를 열어야 합니다.',
  revokeConfirm: '로그아웃',
  revoked: '이 브라우저를 로그아웃했습니다',
  readOnly: '읽기 전용',
  readOnlyDesc: '켜면 브라우저에서는 영상, 전사본, 작업을 보기만 할 수 있으며, 변경하거나 작업을 제출할 수 없습니다.',
  readOnlySaved: (on: boolean): string => (on ? '읽기 전용으로 설정했습니다. 바로 적용됩니다.' : '이제 브라우저에서 변경할 수 있습니다. 바로 적용됩니다.'),
  apiMoved: 'OpenAI 호환 API는 이제 별도 서비스입니다:',
  apiMovedLink: '모델 API',
};
