import type { CommonMessages, ClientsMessages, ApprovalCardMessages, McpMessages, ModelApiMessages, WebMessages } from './services-copy.ts';

export const commonTr: CommonMessages = {
  copied: (label) => `${label} kopyalandı`,
  copyFailed: "Kopyalanamadı. Metni seçip kendiniz kopyalayın.",
  autostart: "BaoCut açılınca başlat",
  stopsWithApp: "BaoCut'tan çıktığınızda hizmet de durur.",
  portLabel: "Port",
  portIdle: (port) => `Varsayılan ${port}. Kullanımdaysa başka port seçin: hizmet “Başlatılamadı” gösterir, kendisi port değiştirmez.`,
  portLive: "Portu değiştirmek hizmeti yeni portta yeniden başlatır; mevcut bağlantılar kesilir.",
  portBusy: "Hizmet başlıyor veya duruyor. Biraz sonra yeniden deneyin.",
  portSaved: (port) => `Port ${port} olarak değişti`,
  errorFix: "Başka port deneyin veya kullanan uygulamayı kapatın.",
  resetPort: "Varsayılan portu kullan",
  portReset: (port) => `Port varsayılan ${port} olarak sıfırlandı`,
  unavailableSub: "Bu BaoCut Runtime sürümü henüz bu hizmeti sunmuyor; başlatılamaz.",
  started: (name) => `${name} başlatıldı`,
  stopped: (name) => `${name} durduruldu`,
  startFailed: (reason) => `Başlamadı: ${reason}`,
  restartFailed: (reason) => `Kaydedildi, ancak hizmet yeni ayarlarla yeniden başlatılamadı: ${reason}`,
  section: {
    connect: "Bağlan",
    clients: "İstemciler ve jetonlar",
    requests: "Son istekler",
    settings: "Ayarlar",
  },

  levelLabel: "İzinli işlemler",
  levelSaved: (title) => `İzinli işlemler “${title}” olarak ayarlandı. Hemen geçerli.`,
  liveNote: "Değişiklikler hemen geçerli; yeniden başlatma gerekmez.",
  noRequests: "Henüz istek yok",
  requestMeta: (client: string, ago: string, outcome: string) => `${client} · ${ago} · ${outcome}`,
  needToken: "Erişim jetonu iste",
  needTokenDesc: "Her uygulama bağlanmak için kendi jetonunu göndermeli (Authorization: Bearer <token>).",
  needTokenFixed: "Bu sürümde jeton her zaman gerekli; kapatılamaz. Her uygulama ayrı iptal edilebilir kendi jetonunu alır, jetonsuz kullanımdan güvenlidir.",
  cancel: "İptal",
  lightsLabel: (labels: readonly string[]) => labels.join(', '),
};

export const clientsTr: ClientsMessages = {
  lede: "Bağlanan her uygulamaya kendi jetonunu verin. Jeton yalnızca oluşturulurken gösterilir; BaoCut yalnızca parmak izini tutar. Gerekmediğinde iptal edin, uygulama hemen ayrılır.",
  empty: "Henüz istemci yok. Oluşturup jetonunu bağlanacak uygulamaya girin.",
  create: "İstemci oluştur",
  createTitle: "İstemci oluştur",
  nameLabel: "Uygulama adı",
  namePlaceholder: "Örneğin Claude Desktop",
  nameDesc: "Yalnızca BaoCut içinde çağıranları ayırmak için kullanılır. İstek geçmişi ve onaylar bu adı gösterir.",
  confirmCreate: "Oluştur",
  cancel: "İptal",
  done: "Tamamlandı",
  tokenTitle: (name) => `“${name}” için jeton`,
  tokenOnce: "Jetonu yalnızca şimdi görebilirsiniz. Pencere kapanınca kurtarılamaz; kaybolursa iptal edip yenisini oluşturun.",
  tokenLabel: "Belirteç",
  copyToken: "Belirteci kopyala",
  copySnippetWithToken: "Bağlantı bilgisini kopyala (jetonla)",
  tokenCopiedLabel: "Belirteç",
  snippetCopiedLabel: "Bağlantı bilgisi",
  meta: (created, used) => used ? `Oluşturuldu ${created} · son kullanım ${used}` : `Oluşturuldu ${created} · hiç kullanılmadı`,
  revoke: "İptal et",
  revokeTitle: (name) => `“${name}” iptal edilsin mi?`,
  revokeBody: "Jeton hemen çalışmayı bırakır; kullanan uygulamalar hemen ayrılır. Geri alınamaz; erişim için yeni istemci oluşturup yeni jetonu girin.",
  revokeConfirm: "İptal et",
  revoked: (name) => `“${name}” iptal edildi`,
};

export const approvalCardTr: ApprovalCardMessages = {
  title: (client, tool) => `${client} istemcisi “${tool}” çağırmak istiyor`,
  noVideo: "Belirli videoyla ilgili değil",
  video: (name) => `Video “${name}”`,
  left: (s) => `${s} sn kaldı. Yanıt yoksa reddedilir.`,
  deny: "Reddet",
  allow: "İzin Ver",
  allowOnce: "Bir kez izin ver",
  allowPersist: "İzin ver ve hatırla",
  grantPersistNote:
    "“İzin ver ve hatırla” sürekli izin de verir: bu videoyu (videoya bağlı olmayan çağrılarda tüm videoları) harcama veya kullanım sınırı olmadan kapsar; aynı dış çağrı yeniden sormaz.",
  allowed: "Bu isteğe izin verildi",
  denied: "Reddedildi · istemci hata alır",
  already: "Bu istek zaten bitti (zaman aşımı, işlendi veya bağlantı kesildi)",
};

export const mcpTr: McpMessages = {
  title: "MCP hizmeti",
  lede: "BaoCut MCP sunucusu olarak diğer AI uygulamalarının ajanlarına araçlar verir: video listeleme ve görüntüleme, döküm okuma, düzenleme, yazıya dökme ve dışa aktarma başlatma, bu bilgisayardaki modellerle konuşma sentezi veya görsel oluşturma. Varsayılan kapalı. Varsayılan tüm videolar paylaşılır; yalnızca bazılarını da seçebilirsiniz.",
  on: "MCP hizmeti çalışıyor",
  off: "MCP hizmeti başlatılmadı",
  error: "MCP hizmeti başlatılamadı",
  connectHint: "HTTP MCP destekleyen istemciye hizmet ekleyin: adresi girin, uygulamanın jetonunu istek başlığıyla gönderin (“İstemciler ve jetonlar” altında oluşturun). Adres değişmez; sonraki sefer yeniden ayarlamak gerekmez.",
  address: "MCP adresi",
  copyAddress: "MCP Adresini Kopyala",
  copySnippet: "Bağlantı bilgisini kopyala",
  snippetLabel: "Bağlantı bilgisi",
  snippetNote: "Kopyalanan yapılandırmada jeton yer tutucudur; uygulamanın jetonuyla değiştirin.",
  check: "Hizmeti denetle",
  checkReason: "Runtime henüz uygulamaya sağlık denetimi sunmaz. Karttaki durum Runtime tarafından bildirilen dinleme durumudur.",
  accessSection: "Erişim",
  scopeTitle: "Erişilebilir videolar",
  scopeDesc: "Varsayılan olarak tüm videolar paylaşılır (sonradan oluşturulanlar dahil); ajan videos_list ile gerekeni bulur. Birkaçını da işaretleyebilirsiniz; seçim dışındakiler istemci için yoktur. Yalnızca kayıtlı projelerin videoları listelenir.",
  scopeAll: "Tüm videolar",
  scopeAllSub: (n) => `Sonrakiler dahil · şimdi ${n}`,
  scopePick: "Yalnızca işaretli videolar",
  scopeNone: "Kayıtlı projelerde henüz video yok",
  scopeSaved: "Erişim güncellendi. Hemen geçerli.",
  levelDesc: "Yalnızca dış MCP istemcilerine uygulanır. Yerleşik ajanın erişim modunu etkilemez.",
  clientsTitle: "İstemciler ve jetonlar",
  toolsTitle: "Araçlar",
  toolsLede: "Bağlanınca ajanın tools/list içinde gördüğü araçlardır (“İzinli işlemler” ile değişir). Video parametresi videos_list içinden gelir; yalnızca “Erişilebilir videolar” kapsamını kabul eder.",
  toolsFixed: "Araçlar tek tek açılıp kapatılamaz, parametreleri gösterilemez: “İzinli işlemler” ile birlikte açılır; Runtime uygulamaya liste ve parametreleri vermez.",
  toolsHiddenNote: "Yazma, görev ve oluşturma araçları yalnızca “İzinli işlemler” → “Değişiklikten önce sor” veya “Sormadan izin ver” seçiliyken sunulur.",
  copyTools: "Tools/list'i Kopyala",
  toggleTool: (name) => `Sun: ${name}`,
};

export const modelApiTr: ModelApiMessages = {
  title: "Model API",
  lede: "OpenAI API kullanan araçlar (SDK, komut satırı, diğer uygulamalar) BaoCut modelleriyle yazıya döksün, konuşma sentezlesin, görsel ve metin oluştursun. Yalnızca bu bilgisayarda dinler. Varsayılan yalnızca yerel modellerdir; bulut, LAN düğümleri ve ajanlar ayrı açılmalıdır.",
  on: "Model API çalışıyor",
  off: "Model API başlatılmadı",
  error: "Model API başlatılamadı",
  offSub: (base) => `Başlayınca ${base} adresinde OpenAI uyumlu API sunar`,
  baseUrl: 'Base URL',
  copyBase: "Base URL’yi Kopyala",
  baseLede: "Yollar OpenAI ile aynıdır; yalnızca host ve port değişir. Aracın temel URL adresini buna ayarlayıp uygulama jetonunu API anahtarı olarak kullanın. model için /v1/models içindeki ad kullanın (<provider>/<model> veya aşağıdaki takma ad).",
  baseOff: "Hizmet başlayınca erişilir. Ayar ve belgeleri şimdi inceleyebilirsiniz.",
  copySnippet: "Ortam değişkenlerini kopyala",
  snippetLabel: "Ortam değişkenleri",
  needKey: "API anahtarı gerekli",
  needKeyFixed: "Bu sürümde API anahtarı (istemci jetonu) her zaman gerekli; kapatılamaz. Her uygulama ayrı alır ve ayrı iptal edilebilir.",
  levels: {
    read: "Yalnızca model listeler (GET /v1/models). Oluşturma istekleri reddedilir.",
    ask: "Her oluşturma isteğini BaoCut içinde onaylayın. 50 saniyede yanıt yoksa reddedilir.",
    auto: "Oluşturma istekleri onaysız çalışır. Yalnızca siz kullanıyorsanız uygundur.",
  },
  routingTitle: "Yönlendirme",
  routingLede: "Bu bilgisayardaki modeller her zaman kullanılabilir. Alttaki her türe iletme ayrı açılmalı; kapalı tür /v1/models içinde görünmez, adıyla istemek 404 döndürür.",
  routingSaved: "Yönlendirme güncellendi. Hemen geçerli.",
  concurrency: "İstemci başına eşzamanlı istek",
  concurrencyDesc: (max) => `Sınır aşılırsa 429 döner. 1–${max}.`,
  limits: (upload, json) => `Yüklemeler (yazıya dökülecek ses) en fazla ${upload}; JSON istek gövdeleri en fazla ${json}.`,
  endpointsTitle: "Uç noktalar",
  endpointsLede: "Tüm yollar temel URL altındadır.",
  endpointsFixed: "Bu sürüm yeteneğe göre uç nokta kapatamaz veya ayrı portta sunamaz. Ayrıntılar ve “Dene” henüz yok (uygulama jetonu düz metin göremez, istek gönderemez).",
  modelsGroup: "Modeller",
  modelsGroupSub: "Kullanılabilir modelleri listele ve bul, hizmet bilgisi al",
  capSwitch: (name) => `Sun: ${name}`,
  ownPort: "Ayrı portta da sun",
  aliasesTitle: "Takma adlar",
  aliasesLede: "İstekteki model <provider>/<model> veya alttaki adlardan biridir; diğerleri 404 döndürür. Her ad tek yeteneğin tek modeline işaret eder. “Varsayılan model” sağlayıcının varsayılanını izler.",
  aliasesEmpty: "Henüz takma ad yok. Yalnızca <provider>/<model> çalışır.",
  aliasName: "Ad",
  aliasCapability: "Yetenek",
  aliasTarget: "Hedef",
  aliasAdd: "Ad ekle",
  aliasAdded: (name) => `“${name}” eklendi`,
  aliasRemove: (name) => `Sil: ${name}`,
  aliasRemoved: (name) => `“${name}” silindi`,
  aliasNoTarget: "Bu yetenek için henüz sağlayıcı yok",
  resetAliases: "Varsayılanlara dön",
  resetTitle: "Varsayılan takma adlar geri yüklensin mi?",
  resetBody: "Tablo ön ayar satırına döner (whisper-1 bu bilgisayarın varsayılan yazıya dökme modeline işaret eder). Eklediğiniz adlar silinir.",
  resetDone: "Varsayılan takma adlar geri yüklendi",
  modelsLoading: "Modeller yükleniyor…",
};

export const webTr: WebMessages = {
  title: "Web hizmeti",
  lede: "Bu Mac üzerindeki tarayıcıda BaoCut Web açıp aynı videoları düzenleyin. Yalnızca bu bilgisayarda dinler; ağınızdaki diğer cihazlar erişemez.",
  on: "Web hizmeti çalışıyor",
  off: "Web hizmeti başlatılmadı",
  error: "Web hizmeti başlatılamadı",
  offSub: "Başlatıldıktan sonra BaoCut Web'i bir tarayıcıda açabilirsiniz.",
  open: "Tarayıcıda aç",
  copyLink: "Giriş bağlantısını kopyala",
  linkLabel: "Giriş bağlantısı",
  copyAddress: "Adresi kopyala",
  addressLabel: "Adres",
  linkNote: "Tarayıcı önce tek kullanımlık bağlantıyla giriş yapar (2 dakika geçerli, bir kez). Sonraki 12 saatte yalnızca adresi açın.",
  openFallback: "Buradan dış tarayıcı açılamıyor. Giriş bağlantısı kopyalandı; tarayıcı adres çubuğuna yapıştırın.",
  sessionsTitle: "Açık tarayıcı oturumları",
  sessionsEmpty: "Henüz tarayıcı giriş yapmadı. “Tarayıcıda aç” tıklayın.",
  revoke: "Çıkış yap",
  revokeTitle: "Bu tarayıcıdan çıkış yapılsın mı?",
  revokeBody: "Bağlantısı hemen kesilir. Yeniden kullanmak için yeni giriş bağlantısı açmalısınız.",
  revokeConfirm: "Çıkış yap",
  revoked: "Bu tarayıcıdan çıkış yapıldı",
  readOnly: "Salt okunur",
  readOnlyDesc: "Açıksa tarayıcı yalnızca video, döküm ve görevleri görür; değişiklik veya görev gönderemez.",
  readOnlySaved: (on) => on ? 'Salt okunur ayarlandı. Hemen geçerli.' : 'Tarayıcı artık değiştirebilir. Hemen geçerli.',
  apiMoved: "OpenAI uyumlu API artık ayrı hizmet:",
  apiMovedLink: "Model API",
};
