import type { SpaceMessages } from './space-copy.ts';
import { pluralForm } from '@baocut/protocol';
import { revealLabel } from '../../copy.ts';

const files = (n: number) => `${n} ${pluralForm('fr', n, { one: 'fichier', other: 'fichiers' })}`;
export const fr: SpaceMessages = {
  searchPlaceholder: 'Rechercher des noms, fichiers ou paroles dans les vidéos', searchLabel: 'Rechercher dans Space', openVideo: 'Ouvrir la vidéo', viewInfo: 'Afficher les informations', viewInfoFiles: 'Afficher les informations et les fichiers', filesButton: (n: number) => files(n), filesButtonLabel: (n: number, summary: string) => `${files(n)} : ${summary}`, filesLine: (n: number, summary: string) => `${files(n)} · ${summary}`, filesTitle: 'Fichiers', filesListLabel: 'Fichiers de cette vidéo', viewVideo: 'Afficher la vidéo', factFolder: 'Dossier', transcribe: { first: 'Transcrire…', redo: 'Retranscrire…', retry: 'Relancer la transcription…' }, info: 'Détails de la vidéo…', view: 'Afficher', continue: 'Continuer dans une session', favorite: 'Ajouter aux favoris', unfavorite: 'Retirer des favoris', rename: 'Renommer', get reveal() { return revealLabel(); }, viewTask: 'Afficher la tâche', trash: 'Déplacer dans la corbeille', restore: 'Restaurer depuis la corbeille', purge: 'Supprimer définitivement', clear: 'Effacer', columnMeasure: 'Durée ou dimensions', columnStatus: 'État', noValue: '—', favorited: 'Dans les favoris',
  statusPicker: 'État', refreshMenu: 'Actualiser', rescan: 'Réanalyser les dossiers de projets', rescanHint: 'Relire les fichiers de tous les dossiers de projets et sessions', rebuild: 'Reconstruire l’index', rebuildHint: 'Supprimer le catalogue dérivé et l’index de contenu, puis les reconstruire ; les favoris, noms affichés et la corbeille sont conservés', scanning: 'Analyse des dossiers de projets',
  rebuilt: (entries, pending) => `Index reconstruit · ${entries} ${pluralForm('fr', entries, { one: 'élément', other: 'éléments' })}${pending > 0 ? ` · index de contenu de ${pending} ${pluralForm('fr', pending, { one: 'vidéo', other: 'vidéos' })} toujours en cours de mise à jour en arrière-plan` : ''}`,
  newLabel: 'Nouveau', newBlank: 'Nouvelle vidéo vide', newBlankHint: 'Une vidéo vide en 16:9 qui s’ouvre immédiatement, sans transcription ni file d’attente', newFromFile: 'Nouvelle vidéo depuis un fichier', newFromFileHint: 'La vidéo ou l’audio est envoyé à la zone de message de Home pour préciser votre demande ; les images vont directement sur la timeline', newFromPackage: 'Nouvelle vidéo depuis un paquet portable', newFromPackageHint: 'Un .baocut exporté ailleurs, contenant tous ses médias', pickPackageTitle: 'Choisir un paquet portable', pickPackageButton: 'Ouvrir', pickPackageFilter: 'Paquet portable BaoCut', openPackage: 'Ouvrir comme nouvelle vidéo', packageBlocked: (reason) => `Ouvrir comme nouvelle vidéo : ${reason}`, packageOpening: (name) => `Ouverture de « ${name} »…`, packageOpened: (name) => `« ${name} » ouvert comme nouvelle vidéo`,
  importAssets: 'Importer des médias', importAssetsHint: 'Enregistrer les fichiers comme médias du projet ; les fichiers hors du projet sont copiés dans imports/', whichProject: 'Quel projet', noProject: 'Ouvrez d’abord un dossier de projet dans Home', pickNotMedia: 'Ce n’est pas un fichier vidéo, audio ou image', createdFromFile: (name) => `Vidéo « ${name} » créée et média placé`, createdEmpty: (reason) => `La vidéo a été créée, mais le média n’a pas été placé : ${reason}`,
  importTitle: 'Importer des médias', importProject: 'Importer dans le projet', importHint: 'Choisissez des vidéos, fichiers audio ou images. Les fichiers du dossier de projet sont enregistrés sur place ; les fichiers extérieurs sont copiés dans imports/ du projet et les originaux restent à leur emplacement. Rien n’est ajouté à une vidéo.', importPick: 'Choisir des fichiers…', importNoProject: 'Aucun projet : ouvrez d’abord un dossier de projet dans Home.', importing: 'Import en cours',
  factSource: 'Source', factFile: 'Fichier', factMeasure: 'Durée ou dimensions', factSize: 'Taille', factStatus: 'État', factActivity: 'Dernière activité', factConversation: 'Session source', factGenerated: 'Généré', factVersion: 'Version', factNote: 'Note', viewConversation: 'Afficher la session source', close: 'Fermer', editBlocked: (reason) => `Modifier à nouveau : ${reason}`, continueBlocked: (reason) => `Continuer dans une session : ${reason}`,
  version: (frozen, current) => current && current !== frozen ? `Version vidéo ${frozen} ; la vidéo est désormais ${current}` : `Version vidéo ${frozen}`, missingTitle: 'Impossible de trouver ce fichier', missingFile: 'Fichier introuvable', missingBody: 'L’élément est toujours ici. Son état sera rétabli lorsque le fichier sera de retour.', failedTitle: 'Échec de la génération', failedBody: 'Aucun fichier produit. Consultez la cause et réessayez sur la page Tâches, ou effacez l’élément s’il n’est plus nécessaire.', changedTitle: 'La vidéo source a changé depuis', changedBody: 'Ce résultat correspond à une version antérieure de la vidéo. Il fonctionne toujours, mais ne reflète plus la vidéo actuelle.', reexport: 'Exporter à nouveau depuis la vidéo source', noPreviewVideo: 'Les vidéos s’ouvrent dans l’éditeur.',
  capability: { synthesizeSpeech: 'Doublage', generateImage: 'Générer une image', generateText: 'Générer du texte', export: 'Export' }, trashed: (name) => `Déplacé dans la corbeille · ${name}`, undo: 'Annuler', restored: (name) => `Restauré · ${name}`, purged: (name) => `Supprimé définitivement · ${name}`, cleared: (name) => `Effacé · ${name}`, renamed: 'Renommé',
  continued: (created, name, title) => created ? `Nouvelle session démarrée avec « ${name} » joint : écrivez votre demande, puis envoyez` : `Retour dans « ${title} » avec « ${name} » joint : écrivez votre demande, puis envoyez`, sourceGone: 'La vidéo source ne se trouve actuellement dans aucun dossier de projet ou de session ; elle ne peut donc pas être ouverte', failed: (what, reason) => `Échec de ${what} : ${reason}`,
  trashVideoTitle: 'Supprimer cette vidéo ?', trashVideoBody: 'Le dossier entier de la vidéo est déplacé dans la corbeille du projet et peut être restauré. Les médias originaux liés restent à leur emplacement.', trashVideoRelated: (n) => `${n} ${pluralForm('fr', n, { one: 'élément exporté ou généré depuis cette vidéo restera', other: 'éléments exportés ou générés depuis cette vidéo resteront' })} dans Space et ${pluralForm('fr', n, { one: 'ne sera pas supprimé', other: 'ne seront pas supprimés' })} avec elle :`, trashVideoConfirm: 'Supprimer la vidéo',
  purgeTitle: 'Supprimer définitivement ?', purgeBody: (name) => `« ${name} » sera supprimé du disque et ne pourra pas être restauré. Si une vidéo ou une tâche en cours l’utilise encore, rien ne sera supprimé et les utilisations seront affichées.`, purgeVideoBody: (name) => `Le dossier entier de la vidéo « ${name} » sera supprimé du disque et ne pourra pas être restauré. Les médias originaux liés ne sont pas affectés.`, purgeConfirm: 'Supprimer définitivement', blockedTitle: 'Suppression impossible pour le moment', blockedBody: (name) => `« ${name} » est toujours utilisé ; rien n’a donc été supprimé :`, gotIt: 'Compris',
  renameTitle: 'Renommer', renameLabel: 'Nom affiché', renameHint: (fileName) => `Modifie uniquement le nom affiché dans Space ; le fichier reste inchangé. Laissez vide pour revenir à « ${fileName} ».`, save: 'Enregistrer', changedDialogTitle: 'La vidéo source a changé', changedDialogBody: (frozen, current) => `Ce résultat correspond à la version vidéo ${frozen ?? '(inconnue)'} ; la vidéo est désormais ${current ?? '(inconnue)'}. La copie de travail actuelle sera ouverte.`, changedOpenCurrent: 'Ouvrir la copie de travail actuelle', changedFromFrozen: 'Continuer depuis cette version', changedFromFrozenReason: 'Continuer depuis la version ayant produit cet export n’est pas encore possible (le Runtime n’a pas de commande pour revenir à une version). Vous pouvez ouvrir la copie de travail actuelle et consulter cette version dans l’historique.',
  hitsTitle: 'Paroles dans les vidéos', hitsCount: (n) => `${n} ${pluralForm('fr', n, { one: 'correspondance', other: 'correspondances' })}`, hitsSearching: 'Recherche dans l’index de contenu', hitsNone: 'Aucune parole dans les vidéos ne correspond', hitsError: (reason) => `Impossible de rechercher dans l’index de contenu : ${reason}`, hitUnopenable: 'Cette vidéo ne se trouve actuellement dans aucun dossier de projet ou de session, ou est dans la corbeille ; elle ne peut donc pas être ouverte', hitSourceClock: 'Ceci se trouve dans un média, pas sur la timeline : ouvrez la vidéo et recherchez-le', hitStale: 'La vidéo a changé depuis son indexation ; la position peut donc être décalée',
  hitsGrouped: (n, videos) => `${n} ${pluralForm('fr', n, { one: 'correspondance', other: 'correspondances' })} · ${videos} ${pluralForm('fr', videos, { one: 'vidéo', other: 'vidéos' })}`, hitKind: 'Type de document', hitKindAll: 'Tous les types', hitSpeaker: 'Locuteur', hitSpeakerAll: 'Tous les locuteurs', hitSpeakerNone: 'Aucune correspondance n’a de locuteur', hitsNoneFiltered: 'Aucune correspondance pour ce type ou ce locuteur. Essayez-en un autre.', hitsMore: (n) => `Afficher ${n} de plus`,
  cancel: 'Annuler', openForEdit: 'Ouvrir pour modifier', newVideo: 'Nouvelle vidéo', revealUnavailable: 'Ce fichier ne se trouve dans aucun dossier de projet ou de session ; aucun emplacement à afficher', sidebarLabel: 'Catégories de Space', kindsHeader: 'Catégories', mineHeader: 'Organiser', sidebarNote: 'Space affiche les vidéos, médias et résultats de tous vos projets. Les fichiers restent dans leurs dossiers de projet. Les fichiers exportés ou générés à partir d’une vidéo sont regroupés avec elle ; parcourez par type pour les voir un par un.', all: 'Tout', emptyFiltered: 'Aucun élément correspondant', emptyTrash: 'La corbeille est vide', emptyFavorite: 'Aucun favori', emptyAll: 'Aucun élément', emptyCategory: (label) => `Aucun élément dans ${label}`, emptyFilteredBody: 'Essayez d’autres mots-clés ou effacez les filtres de projet et d’état.', emptyTrashBody: 'Les éléments déplacés dans la corbeille apparaissent ici. Vous pouvez les restaurer ou les supprimer définitivement.', emptyBody: 'Demandez à l’Agent dans une session et ses résultats apparaîtront ici. Vous pouvez aussi importer des médias depuis « Nouveau » ou ouvrir un dossier existant dans Home.',
  projectPicker: 'Projet', allProjects: 'Tous les projets', sortPicker: 'Trier', viewPicker: 'Afficher', viewGrid: 'Grille', viewList: 'Liste', issuesTitle: (n) => `${n} ${pluralForm('fr', n, { one: 'dossier n’a pas été entièrement listé', other: 'dossiers n’ont pas été entièrement listés' })}`, issueTruncated: (detail) => `Trop de fichiers ; seule une partie a été listée : ${detail}`, issueUnreadable: (detail) => `Impossible de lire : ${detail}`, preparing: 'Préparation de Space…', preparingBody: 'La première fois, les dossiers de projets doivent être analysés. Cela prend un instant.',
  createIn: (project, hint) => `Dans « ${project} » · ${hint}`, whichProjectFor: (label) => `${label} : quel projet`, entryActions: (name) => `Actions de « ${name} »`, entriesLabel: 'Éléments de Space', columnName: 'Nom', columnKind: 'Type', columnSource: 'Source', columnActivity: 'Dernière activité', columnMenu: 'Actions', relatedMore: (n) => `…${n} au total`, importSummaryIn: (text, project) => `${text} (${project})`, activityAt: (ago, at) => `${ago} (${at})`, withReason: (reason, body) => `${reason}. ${body}`,
};
