import { revealLabel } from '../../copy.ts';
import type { ExportMessages } from './export-copy.ts';

import { pluralForm } from '@baocut/protocol';
const count = (n: number, one: string, many: string) => `${n} ${pluralForm('fr', n, { one, other: many })}`;
const list = (labels: readonly string[]) => new Intl.ListFormat('fr', { type: 'conjunction' }).format(labels);

export const fr: ExportMessages = {
  title: "Exporter",
  button: "Exporter",
  buttonBusyTitle: "Export en cours · ouvrez pour voir la progression ou annuler",
  tabsLabel: "Quoi exporter",

  cancel: "Annuler",
  close: "Fermer",
  done: "Terminé",
  again: "Exporter à nouveau",
  resetup: "Modifier les réglages",
  retry: "Réessayer",
  get reveal() {
    return revealLabel();
  },
  file: "Fichier",
  files: "Fichiers",
  more: "Plus",
  moreFiles: (n: number) => count(n, "fichier", "fichiers"),
  moreItems: (n: number) => `${n} de plus`,
  willExport: "Sera exporté",
  estimate: "Estimation",
  noEstimate: "Estimations de durée et taille indisponibles dans cette version",
  place: "Emplacement",
  defaultPlace: "exports/ du projet",
  pickPlace: "Choisir un emplacement",
  resetPlace: "Utiliser l’emplacement par défaut",
  pickFailed: (message: string) => `Impossible de choisir un emplacement : ${message}`,
  submitting: "Soumission…",
  notOpen: "La vidéo n’est pas entièrement ouverte ; export impossible",

  running: "Export en cours",
  queued: "Export en file d’attente",
  cancelling: "Annulation…",
  keepsRunning: "L’export continue si vous fermez cette fenêtre ·",
  goTasks: "Aller à Tâches en arrière-plan",
  cancelExport: "Annuler l'export",
  cancelConfirm: "Annuler cet export ?",
  cancelConfirmBody: "Fichiers inachevés supprimés ; vidéo inchangée. Les fichiers déjà en cours de sauvegarde ne peuvent pas être arrêtés et finiront de s’enregistrer.",
  keepExporting: "Continuer l'export",
  cancelFailed: (message: string) => `Impossible d’annuler : ${message}`,
  plannedFiles: (first: string, n: number) => `${first} et ${n - 1} de plus`,

  exported: "Export terminé",
  exportedToast: (name: string) => `Export terminé · ${name}`,
  failedToast: (title: string) => `Échec de l’export · ${title}`,
  interruptedToast: (title: string) => `Export interrompu · ${title}`,
  view: "Voir",
  waiting: "Soumis, attente de l’apparition de la tâche…",
  warnings: "Notes d’export",
  moreWarnings: (n: number) => `${n} de plus · tout voir dans Tâches en arrière-plan`,
  cancelled: "Export annulé",
  interrupted: "L’export a été interrompu",
  interruptedBody: "Le Runtime s’est arrêté ou a redémarré avant la fin. Aucune reprise ; exportez à nouveau si nécessaire.",
  partial: "Fichiers déjà enregistrés",
  pickDirAndRetry: "Exporter ailleurs",
  skipUnsupported: "Les ignorer et exporter à nouveau",
  skipMissing: "Ignorer les médias manquants et exporter à nouveau",
  useDocument: (name: string) => `Utiliser « ${name} »`,

  range: "Gamme",
  rangeChapters: "Chapitres",
  rangeClips: "Clips",
  pickChapters: "Cochez les chapitres ; les voisins sont réunis en une partie",
  pickClips: "Cochez les clips ; les voisins sont réunis en une partie",
  noChapters: "Cette séquence n’a aucun marqueur de chapitre",
  noClips: "Aucun clip vidéo activé sur la timeline",
  selectAll: "Sélectionner tout",
  clear: "Effacer",
  start: "Début",
  end: "Fin",
  startLabel: "Code temporel de début",
  endLabel: "Code temporel de fin",
  takeNow: "Utiliser la tête de lecture",
  takeNowHint: "Utiliser la position de la tête de lecture de l’éditeur",
  length: (text: string) => `Total ${text}`,
  multi: "Plusieurs parties",
  mergeOne: "Réunir en une seule",
  eachOne: "Un fichier chacun",
  eachNote: "Un fichier par partie",
  mergeBlocked: "Réunir des parties non adjacentes n’est pas encore disponible ; chaque partie est exportée dans son fichier",

  quality: "Qualité et taille",
  resolution: "Résolution",
  sourceResolution: "Résolution d'origine",
  ratio: "Rapport hauteur/largeur",
  followCanvas: "Comme le canevas",
  letterboxedTo: (ratio: string) => `${ratio} avec bandes noires`,
  letterboxNote: "Changer le format ne recadre pas : image agrandie à son rapport, centrée avec bandes noires ; la mise en page n’est pas réorganisée.",
  size: "Taille",
  upscaleNote: (label: string) => `La résolution est limitée à l’original ${label} · au-delà, simple agrandissement sans netteté supplémentaire`,
  pictureLanes: "Contenu de l’image",
  burnCaptions: "Incruster les sous-titres dans l’image",
  burnCaptionsFor: (label: string) => `Sous-titres incrustés : ${label}`,
  burnOff: "Pas d’incrustation cette fois",
  lanesNote: "Les interrupteurs suivent affichage et son de la timeline ; réglages par piste indisponibles, changez-les sur la timeline. L’incrustation de sous-titres se règle indépendamment ici",
  noLanes: "Rien sur la timeline pour l'instant",
  dubChannels: "Pistes audio de doublage",
  dubOne: "Une piste",
  dubMulti: "Une par langue",
  dubPick: "Mixé dans la piste principale",
  dubTrackDefault: "Par défaut",
  dubMultiBlocked: "Une piste audio par langue (MP4 multipiste) indisponible ; ce choix change seulement le son de l’export, image inchangée",
  exportMp4: "Exporter en MP4",
  captionsBurned: "Sous-titres incrustés",
  captionsNotBurned: "Sous-titres non incrustés",

  soundLanes: "Contenu du son",
  quick: "Choix rapide",
  musicOnly: "Musique seule",
  musicOnlyBlocked: "Export musique seule indisponible ; coupez d’abord les autres pistes sur la timeline",
  noSound: "Cette vidéo n’a aucun son",
  noSoundSub: "Aucune piste ou clip sonore sur la timeline",
  soundNote: "Les interrupteurs suivent le son de la timeline ; réglages par piste indisponibles, changez-les sur la timeline",
  sourceNote: "La source choisie décide des sons mixés ; la liste suit la timeline",
  formatQuality: "Format et qualité",
  format: "Formater",
  bitrate: "Débit",
  channels: "Canaux",
  stereo: "Stéréo",
  mono: "Mono",
  stereoNote: "Stéréo · conserve l’image gauche–droite du son et de la musique",
  monoNoteLossless: "Mono · moitié de taille · suffisant pour la parole seule",
  monoNoteLossy: "Mono conserve le débit ; tout le débit va à un canal pour des voix plus propres",
  exportAudio: (format: string) => `Exporter ${format}`,

  voiceSplit: "Fichiers vocaux",
  splitOne: "Mixer en un seul",
  splitEach: "Un par doublage",
  splitNoDub: "Aucun doublage dans cette vidéo ; un fichier par doublage en nécessite un",
  splitOneNote: "Mixe la source choisie dans un fichier",
  splitEachNote: "Un fichier par groupe de doublage ; seulement ce doublage, sans son original, musique ni fond (seule méthode disponible) ; exportez le son original séparément",
  splitEachRanges: "Pour des parties séparées, noms par défaut numérotés, sans indication du doublage contenu",
  splitQuickOff: "Choix rapide sans effet sur un fichier par doublage ; chaque son suit la liste ci-dessous",
  dubPartSub: (items: number) => count(items, "segment de doublage", "segments de doublage"),
  eachFiles: (n: number) => `${count(n, "fichier", "fichiers")} au total`,
  eachWhat: (labels: readonly string[]) => `Un fichier pour chaque ${list(labels)}`,
  eachStarted: (n: number) => `Soumis : ${count(n, "export", "exports")} · premier affiché ici, les autres dans Tâches en arrière-plan`,
  eachPartial: (done: number, left: number, reason: string) => `Soumis : ${done} ; les ${left} restants n’ont pas été exportés : ${reason}`,
  exportAudioEach: (n: number, format: string) => `Exporter ${n} ${format} ${pluralForm('fr', n, { one: "fichier", other: "fichiers" })}`,

  loudness: "Sonie",
  loudnessSwitch: "Normaliser le volume sonore",
  loudnessTarget: "Cible",
  truePeak: "Plafond de crête",
  defaultMark: "Par défaut",

  subtitleLanes: "Quelles pistes",
  subtitlesWhat: (labels: readonly string[]) => (labels.length === 2 ? `${labels.join(" + ")} bilingues` : labels.join(" + ")),
  hiddenOnTimeline: "Désactivée sur la timeline",
  noSubtitles: "Aucun sous-titre ni transcription",
  noSubtitlesSub: "Transcrivez d’abord ou ajoutez une piste de sous-titres sur la timeline",
  multiTrack: "Plusieurs pistes",
  bilingualNote: "Deux pistes réunies dans un fichier bilingue ; première = texte principal",
  eachBlocked: "Cette version exporte un fichier de sous-titres à la fois ; exportez plusieurs fois pour des fichiers séparés",
  tooMany: "Deux pistes maximum par fichier bilingue ; exportez les autres séparément",
  pickOne: "Activez au moins une piste",
  exportSubtitles: "Exporter les sous-titres",

  language: "Langue",
  original: "Originale",
  translation: "Traduction",
  originalSwitch: (name: string) => `Original : ${name}`,
  translationSwitch: (label: string) => `Traduction : ${label}`,
  transcriptPair: (source: string, translation: string) => `${source} + ${translation} côte à côte`,
  sourceLocked: "La transcription repose sur l’original ; une traduction peut seulement compléter une paire bilingue",
  oneTranslation: "Une seule traduction à la fois · en activer une autre remplace l’actuelle",
  sourceDocument: "Source de transcription",
  include: "Inclure",
  frontmatter: "Métadonnées initiales",
  chapters: "Titres de chapitres",
  timestamps: "Horodatage des paragraphes",
  speakers: "Locuteurs",
  skipCut: "Ignorer les parties coupées",
  frontmatterMdOnly: "Les métadonnées initiales ne sont écrites qu’en Markdown",
  transcriptNoChapters: "Cette vidéo n’a pas de chapitres · les titres viennent des marqueurs de chapitre de la timeline",
  keepCutNote: "Inclut les parties coupées de la timeline · les temps suivent le média d’origine",
  preview: "Aperçu",
  previewLoading: "Préparation de l’aperçu…",
  transcriptLength: "Longueur",
  copyText: "Copier le texte",
  copied: "Copié",
  noTranscript: "Aucune transcription",
  noTranscriptSub: "Transcrivez d’abord ou ajoutez une piste de sous-titres sur la timeline",
  exportTranscript: "Exporter la transcription",

  editors: "Exporter vers un éditeur",
  xmemlName: "Premiere Pro / DaVinci Resolve",
  xmemlMeta: "FCP7 XML (.xml)",
  portableName: "Paquet portable BaoCut",
  portableMeta: ".baocut · vidéo, documents et médias dans un fichier",
  plannedTarget: "Ce type de fichier projet n’est pas disponible",
  jianyingName: "Brouillon Jianying",
  capcutFolderMeta: "Dossier · .capcut",
  bake: "Éléments algorithmiques",
  bakeAuto: "Convertir en médias vidéo (recommandé)",
  bakeLossy: "Convertir aussi animations, masques et autres propriétés avec pertes",
  bakeNone: "Ne pas convertir, les retirer",
  bakeBlocked: "Conversion de textes, graphiques et compositions en vidéo indisponible ; contenus non représentables listés dans les notes d’export",
  xmemlNote: "Le projet contient vidéo, images et audio de la timeline · clips désactivés conservés · médias référencés par chemins absolus locaux · texte, graphiques, sous-titres, transitions et effets non écrits, listés dans les notes",
  portableNote: "Le paquet portable exclut chemins locaux, clés, licences et enregistrements de tâches · médias liés inclus · ouverture créant une nouvelle vidéo",
  missingAssets: "Médias illisibles",
  missingFail: "Arrêter et me prévenir",
  missingSkip: "Ignorer et marquer manquants dans la liste",
  exportProject: "Exporter le fichier projet",
  exportPortable: "Exporter le paquet portable",
};
