const list = (labels: readonly string[]) => new Intl.ListFormat('ru', { type: 'conjunction' }).format(labels);
import { pluralForm } from '@baocut/protocol';
import { revealLabel } from '../../copy.ts';
import type { ExportMessages } from './export-copy.ts';

export const ru: ExportMessages = {
  title: "Экспорт",
  button: "Экспорт",
  buttonBusyTitle: "Идёт экспорт · откройте, чтобы увидеть прогресс или отменить",
  tabsLabel: "Что экспортировать",

  cancel: "Отмена",
  close: "Закрыть",
  done: "Готово",
  again: "Экспортировать ещё раз",
  resetup: "Изменить настройки",
  retry: "Повторить попытку",
  get reveal() {
    return revealLabel();
  },
  file: "Файл",
  files: "Файлы",
  more: "Подробнее",
  moreFiles: (n: number) => pluralForm('ru', n, { one: `${n} файл`, few: `${n} файла`, many: `${n} файлов`, other: `${n} файла` }),
  moreItems: (n: number) => `${n} `,
  willExport: "Будет экспортировано",
  estimate: "Оценка",
  noEstimate: "Оценки времени и размера ещё недоступны",
  place: "Расположение",
  defaultPlace: "exports/ проекта",
  sourcePlace: (dir) => `Папка исходного видео · ${dir}`,
  pickPlace: "Выбрать расположение",
  resetPlace: "Использовать стандартное расположение",
  pickFailed: (message: string) => `Не удалось выбрать расположение: ${message}`,
  submitting: "Отправка…",
  notOpen: "Видео ещё не открыто полностью, экспорт невозможен",

  running: "Экспорт",
  queued: "В очереди на экспорт",
  cancelling: "Отмена…",
  keepsRunning: "Экспорт продолжится после закрытия окна ·",
  goTasks: "Перейти к фоновым задачам",
  cancelExport: "Отменить экспорт",
  cancelConfirm: "Отменить экспорт?",
  cancelConfirmBody: "Незавершённые файлы удалятся, видео не затронуто. Сохранение уже записываемых файлов нельзя остановить, оно завершится.",
  keepExporting: "Продолжить экспорт",
  cancelFailed: (message: string) => `Не удалось отменить: ${message}`,
  plannedFiles: (first: string, n: number) => `${first} и ${n - 1} `,

  exported: "Экспортировано",
  exportedToast: (name: string) => `Экспорт завершён · ${name}`,
  failedToast: (title: string) => `Ошибка экспорта · ${title}`,
  interruptedToast: (title: string) => `Экспорт прерван · ${title}`,
  view: "Открыть",
  waiting: "Отправлено, ожидание появления задачи…",
  warnings: "Примечания экспорта",
  moreWarnings: (n: number) => `${n} ещё · всё в фоновых задачах`,
  cancelled: "Экспорт отменён",
  interrupted: "Экспорт прерван",
  interruptedBody: "Runtime остановлен или перезапущен до завершения экспорта. Продолжения не будет; экспортируйте снова при необходимости.",
  partial: "Уже сохранённые файлы",
  pickDirAndRetry: "Экспортировать в другое место",
  skipUnsupported: "Пропустить и экспортировать снова",
  skipMissing: "Пропустить отсутствующие материалы и экспортировать снова",
  useDocument: (name: string) => `Использовать «${name}»`,

  range: "Диапазон",
  rangeChapters: "Главы",
  rangeClips: "Клипы",
  pickChapters: "Отметьте главы; соседние объединяются в одну часть",
  pickClips: "Отметьте клипы; соседние объединяются в одну часть",
  noChapters: "В последовательности ещё нет меток глав",
  noClips: "На таймлайне ещё нет включённых видеоклипов",
  selectAll: "Выбрать все",
  clear: "Очистить",
  start: "Начало",
  end: "Конец",
  startLabel: "Начальный таймкод",
  endLabel: "Конечный таймкод",
  takeNow: "Использовать курсор воспроизведения",
  takeNowHint: "Использовать позицию курсора редактора",
  length: (text: string) => `Всего ${text}`,
  multi: "Несколько частей",
  mergeOne: "Объединить в одну",
  eachOne: "Отдельным файлом",
  eachNote: "Файл на часть",
  mergeBlocked: "Объединение несоседних частей в один файл пока недоступно; каждая экспортируется отдельно",

  quality: "Качество и размер",
  resolution: "Разрешение",
  sourceResolution: "Исходное разрешение",
  ratio: "Соотношение сторон",
  followCanvas: "Как холст",
  letterboxedTo: (ratio: string) => `${ratio} с чёрными полосами`,
  letterboxNote: "Смена соотношения не обрезает: изображение масштабируется с исходным соотношением, центрируется с чёрными полосами; раскладка не перестраивается",
  size: "Размер",
  upscaleNote: (label: string) => `Разрешение до исходного ${label} · выше только масштабирование, резкость не вырастет`,
  pictureLanes: "Содержимое изображения",
  burnCaptions: "Встроить субтитры в изображение",
  burnCaptionsFor: (label: string) => `Встроить субтитры в изображение: ${label}`,
  burnOff: "В этот раз не встроены",
  lanesNote: "Переключатели следуют показу и звуку таймлайна · отдельные настройки дорожек пока недоступны, меняйте на таймлайне; встраивание субтитров задаётся здесь отдельно",
  noLanes: "На таймлайне пока ничего нет",
  dubChannels: "Аудиодорожки озвучки",
  dubOne: "Одна дорожка",
  dubMulti: "По одной на язык",
  dubPick: "Смешать в основную дорожку",
  dubTrackDefault: "По умолчанию",
  dubMultiBlocked: "Аудиодорожка на язык (многодорожечный MP4) ещё недоступна · выбор меняет только звук экспорта, изображение сохраняется",
  exportMp4: "Экспорт MP4",
  captionsBurned: "Субтитры встроены",
  captionsNotBurned: "Субтитры не встроены",

  soundLanes: "Содержимое звука",
  quick: "Быстрый выбор",
  musicOnly: "Только музыка",
  musicOnlyBlocked: "Экспорт только музыки пока недоступен; отключите остальные дорожки на таймлайне",
  noSound: "В видео нет звука",
  noSoundSub: "На таймлайне нет дорожек и клипов со звуком",
  soundNote: "Переключатели следуют отключению звука таймлайна · отдельные настройки дорожек недоступны, меняйте на таймлайне",
  sourceNote: "Источник выше определяет смешиваемые звуки; список следует таймлайну",
  formatQuality: "Формат и качество",
  format: "Формат",
  bitrate: "Битрейт",
  channels: "Каналы",
  stereo: "Стерео",
  mono: "Моно",
  stereoNote: "Стерео · сохраняет левый и правый каналы исходного звука и музыки",
  monoNoteLossless: "Моно · половина размера · достаточно для видео с речью",
  monoNoteLossy: "Моно сохраняет битрейт · весь идёт на один канал, голос чище",
  exportAudio: (format: string) => `Экспортировать ${format}`,

  voiceSplit: "Файлы голосов",
  splitOne: "Смешать в один",
  splitEach: "По одному на озвучку",
  splitNoDub: "В видео ещё нет озвучки · отдельный файл требует озвучки",
  splitOneNote: "Смешивает источник выше в один файл",
  splitEachNote: "Файл на группу озвучки · только озвучка, без оригинала, музыки и фона (единственный способ экспорта озвучки в версии) · исходный звук экспортируйте отдельно",
  splitEachRanges: "При отдельных частях имена — стандартное имя с номером, озвучка в имени не указана",
  splitQuickOff: "Быстрый выбор не действует при файле на озвучку: звук каждого по списку ниже",
  dubPartSub: (items: number) => pluralForm('ru', items, { one: `${items} сегмент озвучки`, few: `${items} сегмента озвучки`, many: `${items} сегментов озвучки`, other: `${items} сегмента озвучки` }),
  eachFiles: (n: number) => `${pluralForm('ru', n, { one: `${n} файл`, few: `${n} файла`, many: `${n} файлов`, other: `${n} файла` })} всего`,
  eachWhat: (labels: readonly string[]) => `Отдельный файл для каждого из ${list(labels)}`,
  eachStarted: (n: number) => `Отправлено: ${pluralForm('ru', n, { one: `${n} экспорт`, few: `${n} экспорта`, many: `${n} экспортов`, other: `${n} экспорта` })} · первый здесь, остальные в фоновых задачах`,
  eachPartial: (done: number, left: number, reason: string) => `Отправлено: ${done}; остальные ${left} не экспортированы: ${reason}`,
  exportAudioEach: (n: number, format: string) => `Экспортировать ${n} ${format} ${pluralForm('ru', n, { one: "файл", few: "файла", many: "файлов", other: "файла" })}`,

  loudness: "Громкость",
  loudnessSwitch: "Нормализовать громкость",
  loudnessTarget: "Цель",
  truePeak: "Предел пика",
  defaultMark: "По умолчанию",

  subtitleLanes: "Какие дорожки",
  subtitlesWhat: (labels: readonly string[]) => (labels.length === 2 ? `${labels.join(" + ")} двуязычные` : labels.join(" + ")),
  hiddenOnTimeline: "Отключено на таймлайне",
  noSubtitles: "Субтитров и расшифровки ещё нет",
  noSubtitlesSub: "Сначала расшифруйте или добавьте дорожку субтитров",
  multiTrack: "Несколько дорожек",
  bilingualNote: "Две дорожки объединяются в двуязычный файл, первая — основной текст",
  eachBlocked: "Версия экспортирует один файл субтитров за раз; для отдельных файлов повторите экспорт",
  tooMany: "Можно объединить максимум две дорожки (двуязычно); остальные отдельно",
  pickOne: "Включите хотя бы одну",
  exportSubtitles: "Экспорт субтитров",

  language: "Язык",
  original: "Оригинал",
  translation: "Перевод",
  originalSwitch: (name: string) => `Оригинал: ${name}`,
  translationSwitch: (label: string) => `Перевод: ${label}`,
  transcriptPair: (source: string, translation: string) => `${source} + ${translation} рядом`,
  sourceLocked: "Расшифровка основана на оригинале; перевод может быть только второй половиной пары",
  oneTranslation: "Один перевод за раз · другой заменит текущий",
  sourceDocument: "Источник расшифровки",
  include: "Включить",
  frontmatter: "Метаданные",
  chapters: "Заголовки глав",
  timestamps: "Время абзацев",
  speakers: "Спикеры",
  skipCut: "Пропускать вырезанное",
  frontmatterMdOnly: "Метаданные записываются только в Markdown",
  transcriptNoChapters: "В этом видео нет глав · заголовки глав берутся из маркеров глав на таймлайне",
  keepCutNote: "Включает вырезанное из таймлайна · время по исходному медиафайлу",
  preview: "Предварительный просмотр",
  previewLoading: "Готовим предпросмотр…",
  transcriptLength: "Объём",
  copyText: "Копировать текст",
  copied: "Скопировано",
  noTranscript: "Расшифровки ещё нет",
  noTranscriptSub: "Сначала расшифруйте или добавьте дорожку субтитров",
  exportTranscript: "Экспортировать расшифровку",

  editors: "Экспортировать в редактор",
  xmemlName: "Premiere Pro / DaVinci Resolve",
  xmemlMeta: "FCP7 XML (.xml)",
  portableName: "Переносимый пакет BaoCut",
  portableMeta: ".baocut · видео, все документы и материалы в одном файле",
  plannedTarget: "Этот вид файла проекта ещё недоступен",
  jianyingName: "Черновик Jianying",
  capcutFolderMeta: "Папка · .capcut",
  bake: "Алгоритмические элементы",
  bakeAuto: "Преобразовать в видеоматериалы (рекомендуется)",
  bakeLossy: "Также преобразовать анимацию, маски и другие теряемые свойства",
  bakeNone: "Не преобразовывать, пропустить",
  bakeBlocked: "Преобразование текста, графики и композиций в видео ещё недоступно; непредставимое перечисляется в примечаниях",
  xmemlNote: "Файл проекта переносит видео, изображения и аудио таймлайна · отключённые клипы сохраняются отключёнными · материалы по абсолютным путям компьютера · текст, графика, субтитры, переходы и эффекты не записываются, перечисляются в примечаниях",
  portableNote: "Переносимый пакет исключает локальные пути, ключи, лицензии и записи задач · связанные материалы тоже включены · открытие создаёт новое видео",
  missingAssets: "Нечитаемые материалы",
  missingFail: "Остановить и сообщить",
  missingSkip: "Пропустить и отметить отсутствующими",
  exportProject: "Экспортировать файл проекта",
  exportPortable: "Экспорт переносимого пакета",
};
