const count = (n: number, one: string, many: string) => `${n} ${pluralForm('de', n, { one, other: many })}`;
const list = (labels: readonly string[]) => new Intl.ListFormat('de', { type: 'conjunction' }).format(labels);
import { pluralForm } from '@baocut/protocol';
import { revealLabel } from '../../copy.ts';
import type { ExportMessages } from './export-copy.ts';

export const de: ExportMessages = {
  title: "Exportieren",
  button: "Exportieren",
  buttonBusyTitle: "Export läuft · zum Fortschritt ansehen oder abbrechen öffnen",
  tabsLabel: "Was exportiert werden soll",

  cancel: "Abbrechen",
  close: "Schließen",
  done: "Fertig",
  again: "Noch einmal exportieren",
  resetup: "Einstellungen ändern",
  retry: "Erneut versuchen",
  get reveal() {
    return revealLabel();
  },
  file: "Datei",
  files: "Dateien",
  more: "Mehr",
  moreFiles: (n: number) => count(n, "Datei", "Dateien"),
  moreItems: (n: number) => `${n} weitere`,
  willExport: "Wird exportiert",
  estimate: "Schätzung",
  noEstimate: "Zeit- und Größenschätzungen sind in dieser Version noch nicht verfügbar",
  place: "Speicherort",
  defaultPlace: "exports/ im Projekt",
  pickPlace: "Speicherort auswählen",
  resetPlace: "Standard-Speicherort verwenden",
  pickFailed: (message: string) => `Speicherort konnte nicht ausgewählt werden: ${message}`,
  submitting: "Wird eingereicht…",
  notOpen: "Das Video ist noch nicht vollständig geöffnet und kann nicht exportiert werden",

  running: "Wird exportiert",
  queued: "Zum Export eingereiht",
  cancelling: "Wird abgebrochen…",
  keepsRunning: "Export läuft beim Schließen dieses Fensters weiter ·",
  goTasks: "Zu Hintergrundaufgaben",
  cancelExport: "Export abbrechen",
  cancelConfirm: "Diesen Export abbrechen?",
  cancelConfirmBody: "Nicht abgeschlossene Dateien werden gelöscht; das Video bleibt unverändert. Bereits gespeicherte Dateien können nicht gestoppt werden und werden fertig gespeichert.",
  keepExporting: "Weiter exportieren",
  cancelFailed: (message: string) => `Abbrechen fehlgeschlagen: ${message}`,
  plannedFiles: (first: string, n: number) => `${first} und ${n - 1} weitere`,

  exported: "Exportiert",
  exportedToast: (name: string) => `Export abgeschlossen · ${name}`,
  failedToast: (title: string) => `Export fehlgeschlagen · ${title}`,
  interruptedToast: (title: string) => `Export unterbrochen · ${title}`,
  view: "Ansehen",
  waiting: "Eingereicht; wartet, bis die Aufgabe erscheint…",
  warnings: "Exporthinweise",
  moreWarnings: (n: number) => `${n} weitere · alle unter Hintergrundaufgaben anzeigen`,
  cancelled: "Export abgebrochen",
  interrupted: "Der Export wurde unterbrochen",
  interruptedBody: "Runtime wurde vor Abschluss des Exports gestoppt oder neu gestartet. Kein Fortsetzen; bei Bedarf erneut exportieren.",
  partial: "Bereits gespeicherte Dateien",
  pickDirAndRetry: "An einen anderen Speicherort exportieren",
  skipUnsupported: "Überspringen und erneut exportieren",
  skipMissing: "Fehlendes Material überspringen und erneut exportieren",
  useDocument: (name: string) => `Verwenden: „${name}“`,

  range: "Reichweite",
  rangeChapters: "Kapitel",
  rangeClips: "Clips",
  pickChapters: "Kapitel auswählen; benachbarte werden zu einem Teil verbunden",
  pickClips: "Clips auswählen; benachbarte werden zu einem Teil verbunden",
  noChapters: "Diese Sequenz hat noch keine Kapitelmarkierungen",
  noClips: "Noch keine aktivierten Videoclips in der Zeitleiste",
  selectAll: "Wählen Sie „Alle“ aus",
  clear: "Löschen",
  start: "Starten",
  end: "Ende",
  startLabel: "Startzeitcode",
  endLabel: "Endzeitcode",
  takeNow: "Abspielkopf verwenden",
  takeNowHint: "Abspielkopfposition des Editors verwenden",
  length: (text: string) => `Insgesamt ${text}`,
  multi: "Mehrere Teile",
  mergeOne: "Zu einem verbinden",
  eachOne: "Je eine Datei",
  eachNote: "Eine Datei pro Teil",
  mergeBlocked: "Nicht benachbarte Teile können in dieser Version noch nicht in einer Datei verbunden werden; jeder Teil wird als eigene Datei exportiert",

  quality: "Qualität & Größe",
  resolution: "Auflösung",
  sourceResolution: "Originalauflösung",
  ratio: "Seitenverhältnis",
  followCanvas: "Wie Arbeitsfläche",
  letterboxedTo: (ratio: string) => `${ratio} mit schwarzen Balken`,
  letterboxNote: "Ändern des Seitenverhältnisses schneidet nicht zu: Das Bild wird in seinem Verhältnis skaliert und mit schwarzen Balken zentriert; sein Layout wird nicht für das neue Verhältnis umgeordnet",
  size: "Größe",
  upscaleNote: (label: string) => `Auflösung höchstens in Originalgröße ${label} · höhere Werte skalieren nur hoch und werden nicht schärfer`,
  pictureLanes: "Bildinhalt",
  burnCaptions: "Untertitel ins Bild einbrennen",
  burnCaptionsFor: (label: string) => `Untertitel ins Bild einbrennen: ${label}`,
  burnOff: "Diesmal nicht eingebrannt",
  lanesNote: "Schalter folgen Sichtbarkeit und Stummschaltung in der Zeitleiste; spurweise Überschreibungen sind in dieser Version noch nicht verfügbar. Dort ändern; Einbrennen der Untertitel ist hier unabhängig einstellbar",
  noLanes: "Noch nichts auf der Zeitleiste",
  dubChannels: "Vertonungs-Audiospuren",
  dubOne: "Eine Spur",
  dubMulti: "Eine pro Sprache",
  dubPick: "In Hauptspur gemischt",
  dubTrackDefault: "Standard",
  dubMultiBlocked: "Eine Audiospur pro Sprache (MP4 mit mehreren Audiospuren) ist noch nicht verfügbar; die Auswahl ändert nur den Ton dieses Exports, das Bild bleibt gleich",
  exportMp4: "MP4 exportieren",
  captionsBurned: "Untertitel eingebrannt",
  captionsNotBurned: "Untertitel nicht eingebrannt",

  soundLanes: "Audioinhalt",
  quick: "Schnellauswahl",
  musicOnly: "Nur Musik",
  musicOnlyBlocked: "Nur Musik zu exportieren ist in dieser Version noch nicht verfügbar; zuerst andere Spuren in der Zeitleiste stummschalten",
  noSound: "Dieses Video hat keinen Ton",
  noSoundSub: "Keine Spuren oder Clips mit Ton in der Zeitleiste",
  soundNote: "Schalter folgen Stummschaltung in der Zeitleiste; spurweise Überschreibungen sind in dieser Version noch nicht verfügbar. Dort ändern",
  sourceNote: "Die obige Quelle entscheidet, welche Audiosignale gemischt werden; die Liste folgt der Zeitleiste",
  formatQuality: "Format & Qualität",
  format: "Formatieren",
  bitrate: "Bitrate",
  channels: "Kanäle",
  stereo: "Stereo",
  mono: "Mono",
  stereoNote: "Stereo · erhält das Links-Rechts-Klangbild von Originalton und Musik",
  monoNoteLossless: "Mono · halbe Größe · ausreichend für reine Sprachvideos",
  monoNoteLossy: "Mono behält die Bitrate; sie fließt vollständig in einen Kanal, damit Stimmen klarer klingen",
  exportAudio: (format: string) => `Exportieren: ${format}`,

  voiceSplit: "Vertonungsdateien",
  splitOne: "Zu einer mischen",
  splitEach: "Eine pro Vertonung",
  splitNoDub: "Dieses Video hat noch keine Vertonung; eine Datei pro Vertonung benötigt eine Vertonung",
  splitOneNote: "Mischt die obige Quelle in eine Datei",
  splitEachNote: "Eine Datei pro Vertonungsgruppe; nur diese Vertonung, ohne Originalton, Musik oder Hintergrund (einzige Exportart für Vertonungsquellen in dieser Version). Originalton separat exportieren",
  splitEachRanges: "Beim separaten Export von Teilen bestehen Dateinamen aus Standardname und Nummer; die enthaltene Vertonung ist nicht am Namen erkennbar",
  splitQuickOff: "Schnellauswahl gilt nicht für eine Datei pro Vertonung; der Ton jeder Datei folgt der Liste unten",
  dubPartSub: (items: number) => count(items, "Vertonungsabschnitt", "Vertonungsabschnitte"),
  eachFiles: (n: number) => `${count(n, "Datei", "Dateien")} insgesamt`,
  eachWhat: (labels: readonly string[]) => `Je eine Datei für ${list(labels)}`,
  eachStarted: (n: number) => `Eingereicht: ${count(n, "Export", "Exporte")} · der erste erscheint hier, die übrigen unter Hintergrundaufgaben`,
  eachPartial: (done: number, left: number, reason: string) => `Eingereicht: ${done}; verbleibende ${left} wurden nicht exportiert: ${reason}`,
  exportAudioEach: (n: number, format: string) => `Exportieren: ${n} ${format} ${pluralForm('de', n, { one: "Datei", other: "Dateien" })}`,

  loudness: "Lautheit",
  loudnessSwitch: "Lautheit normalisieren",
  loudnessTarget: "Ziel",
  truePeak: "Spitzenpegelgrenze",
  defaultMark: "Standard",

  subtitleLanes: "Welche Spuren",
  subtitlesWhat: (labels: readonly string[]) => (labels.length === 2 ? `${labels.join(" + ")} zweisprachig` : labels.join(" + ")),
  hiddenOnTimeline: "In Zeitleiste deaktiviert",
  noSubtitles: "Noch keine Untertitel oder Transkription",
  noSubtitlesSub: "Zuerst transkribieren oder eine Untertitelspur in der Zeitleiste hinzufügen",
  multiTrack: "Mehrere Spuren",
  bilingualNote: "Zwei Spuren werden in eine zweisprachige Untertiteldatei verbunden; die erste ist der Haupttext",
  eachBlocked: "Diese Version exportiert eine Untertiteldatei gleichzeitig; für getrennte Dateien mehrfach exportieren",
  tooMany: "Höchstens zwei Spuren gleichzeitig kombinierbar (zweisprachig); den Rest separat exportieren",
  pickOne: "Mindestens eine einschalten",
  exportSubtitles: "Untertitel exportieren",

  language: "Sprache",
  original: "Original",
  translation: "Übersetzung",
  originalSwitch: (name: string) => `Original: ${name}`,
  translationSwitch: (label: string) => `Übersetzung: ${label}`,
  transcriptPair: (source: string, translation: string) => `${source} + ${translation} nebeneinander`,
  sourceLocked: "Das Transkript basiert auf dem Original; eine Übersetzung kann nur die andere Hälfte eines zweisprachigen Paares sein",
  oneTranslation: "Nur eine Übersetzung gleichzeitig; eine andere einzuschalten ersetzt die aktuelle",
  sourceDocument: "Transkriptquelle",
  include: "Einbeziehen",
  frontmatter: "Metadatenkopf",
  chapters: "Kapitelüberschriften",
  timestamps: "Absatzzeitstempel",
  speakers: "Sprecher",
  skipCut: "Geschnittene Teile überspringen",
  frontmatterMdOnly: "Der Metadatenkopf wird nur in Markdown geschrieben",
  transcriptNoChapters: "Dieses Video hat keine Kapitel · Kapitelüberschriften stammen von Kapitelmarkern auf der Zeitleiste",
  keepCutNote: "Enthält die aus der Zeitleiste geschnittenen Teile · Zeiten beziehen sich auf das Originalmedium",
  preview: "Vorschau",
  previewLoading: "Vorschau wird vorbereitet…",
  transcriptLength: "Umfang",
  copyText: "Text kopieren",
  copied: "Kopiert",
  noTranscript: "Noch kein Transkript",
  noTranscriptSub: "Zuerst transkribieren oder eine Untertitelspur in der Zeitleiste hinzufügen",
  exportTranscript: "Transkript exportieren",

  editors: "Für einen Editor exportieren",
  xmemlName: "Premiere Pro / DaVinci Resolve",
  xmemlMeta: "FCP7 XML (.xml)",
  portableName: "Portables BaoCut-Paket",
  portableMeta: ".baocut · Video, alle Dokumente und Materialien in einer Datei",
  plannedTarget: "Dieser Projektdateityp ist in dieser Version noch nicht verfügbar",
  jianyingName: "Jianying-Entwurf",
  capcutFolderMeta: "Ordner · .capcut",
  bake: "Algorithmische Elemente",
  bakeAuto: "In Videomaterial umwandeln (empfohlen)",
  bakeLossy: "Auch Animationen, Masken und andere verlustbehaftete Eigenschaften umwandeln",
  bakeNone: "Nicht umwandeln, nur weglassen",
  bakeBlocked: "Umwandlung von Text, Grafik und Kompositionen in Videomaterial ist in dieser Version noch nicht verfügbar; nicht darstellbare Inhalte werden in den Exporthinweisen aufgeführt",
  xmemlNote: "Die Projektdatei enthält Video, Bilder und Audio aus der Zeitleiste; deaktivierte Clips bleiben deaktiviert. Materialien werden über absolute Pfade auf diesem Computer referenziert. Text, Grafik, Untertitel, Übergänge und Effekte werden nicht geschrieben und einzeln in den Exporthinweisen aufgeführt",
  portableNote: "Das portable Paket lässt lokale Pfade, Schlüssel, Lizenzen und Aufgabenprotokolle weg; auch verknüpfte Materialien sind enthalten. Öffnen erstellt ein neues Video",
  missingAssets: "Nicht lesbare Materialien",
  missingFail: "Stoppen und melden",
  missingSkip: "Überspringen und als fehlend markieren",
  exportProject: "Projektdatei exportieren",
  exportPortable: "Portables Paket exportieren",
};
