import type { AiToolsMessages } from './ai-tools-copy.ts';

export const ko: AiToolsMessages = {
  back: '뒤로',

  // 设置态
  who: '사용',
  whoAgent: 'Agent에게 맡기기',
  whoModel: '모델 직접 호출',
  whoModelSub: 'Runtime에 아직 이 작업의 워크플로가 없어 Agent만 할 수 있습니다',
  scope: '범위',
  scopeAll: '영상 전체',
  scopeChapter: (index: number, label: string) => `챕터 ${index} · ${label}`,
  scopeNoChapters: '타임라인에 아직 챕터가 없어 영상 전체만 선택할 수 있습니다',
  cta: 'Agent에게 맡기기',
  queued: 'Agent가 작업 중 · 메시지가 대기열에 있으며 이번 턴이 끝나면 보냅니다',
  noConversation: '이 영상은 어떤 프로젝트나 세션에도 속하지 않아 Agent에게 맡길 수 없습니다.',
  createFailed: (message: string) => `세션을 만들지 못했습니다: ${message}`,

  // 勾选项与自定义
  prePolish: '먼저 다듬기(자동 문단 나누기)',
  prePolishOn: '챕터를 문단 단위로 묶습니다',
  prePolishOff: '다듬지 않은 전사본은 문단이 1개뿐이라 챕터가 거칠게 나뉩니다',
  staleEdited: '원문이 수정된 문장',
  staleEditedSub: '전사본에서 단어를 바꿨지만 번역은 아직 이전 그대로입니다',
  staleCut: '원문에서 잘린 문장',
  staleCutSub: '컷이 문장 일부를 제거했습니다. 잘린 원문을 기준으로 다시 번역합니다',
  staleNone: '하나 이상 선택하세요',
  staleOnly: (language: string) => `${language} 번역만`,
  retranscribeModel: '음성 모델은 Agent가 이 컴퓨터에 설치된 모델 중에서 고릅니다. 직접 정하려면 아래 지시에 적으세요.',
  retranscribeSpeakers: '전사 후 화자 식별',

  // 写作与发布
  platform: '게시할 곳',
  platformPlaceholder: '게시할 플랫폼(선택 사항). 그 플랫폼의 규칙에 맞춰 쓰고 확인하도록 알려 드립니다',
  titleCount: '후보 수',
  titleCountNote: (min: number, max: number) => `${min}–${max}개, 각각 다른 관점`,
  coverCount: '개수',
  coverIdea: '전하고 싶은 한 가지',
  coverIdeaPlaceholder: '사람들이 이 영상을 클릭하게 만들 한 가지(선택 사항). 비워 두면 Agent가 전사본에서 찾습니다',
  coverRatio: '화면 비율',
  coverRatioProject: '영상 캔버스와 같게',
  coverText: '표지 텍스트',

  // 还做不了的
  soon: '곧 제공',
  chaptersPolishFirst: '먼저 다듬고 문단을 나눈 뒤 챕터를 생성하세요',

  session: '세션',
  promptLabel: 'Agent에게 전할 말',
  promptPlaceholder: '무엇을 어떻게 할지 적고, @로 챕터나 화자를 참조하세요',
  restoreDefault: '기본값 복원',
  skillNote: '이 도구의 방식',
  noSkill: 'skill가 없습니다. 위 프롬프트만 따릅니다.',
  addSkillBack: '이 도구의 skill 다시 추가',
  sentNew: 'Agent에게 넘겼습니다 · 새 세션',
  sentCurrent: 'Agent에게 넘겼습니다 · 현재 세션에서 계속',
  agentCardTitle: '아래 목록에 없는 일은 한 문장으로 Agent에게',
  agentCardSomeAgent: 'Agent',
  agentCardOutside: '이 영상이 속한 세션을 열고 영상을 맥락으로 씁니다 →',
  noTranscriptTitle: '이 영상에는 아직 스크립트가 없습니다',
  noTranscriptBody: '여기 도구는 모두 스크립트에서 출발합니다. 다듬기, 챕터, 요약, 제목 모두 먼저 전사가 필요합니다.',
  goTranscribe: '스크립트로 이동',
  stateRunning: '실행 중',
  stateReview: '검토 대기',
  agentCardNew: (agent) => `새 세션을 열고 이 영상을 맥락으로 씁니다. 이 컴퓨터의 ${agent}에서 실행되며 쓰기 전에 묻습니다 →`,
  stateChapters: (count) => `${count}개 챕터`,

  whyRetranscribe: '음성 모델이 필요하고, Runtime의 전사는 범위를 바꾸지 않고 새 전사를 통째로 추가하므로 Agent만 할 수 있습니다',
  whyCleanup: '잘라낼 곳을 찾으려면 앞뒤 맥락에서 하나씩 판단해야 하므로 Agent만 할 수 있습니다',
  whyStale: '오래된 문장만 다시 번역하는 흐름이 Runtime에 아직 없어 Agent만 할 수 있습니다',
  whyCover: '표지는 이미지를 생성하고 합성해야 하므로 Agent만 할 수 있습니다',
  modelPromptLabel: '프롬프트',
  modelPicker: '텍스트 모델',
  modelNone: '텍스트 모델 없음',
  modelNoStructured: '이 모델은 구조화된 출력을 지원하지 않습니다. 이 도구에는 필요합니다',
  modelPolishNote: '모델을 직접 호출하면 단어별로 오타와 문장 부호만 고치고 단락은 나누지 않습니다. 단락을 나누려면 Agent에게 맡기세요.',
  modelGateBody: '이 도구는 프롬프트와 전사를 텍스트 모델에 보냅니다.',
  skillsAsSystem: '붙인 Skill은 시스템 프롬프트로 모델에 보냅니다. SKILL.md와 쓰이는 references/만 보내고 다른 파일은 보내지 않습니다.',
  contextNone: '모델에 보내는 것: 위의 프롬프트뿐',
  contextLine: (items) => `모델에 보내는 것: 프롬프트 + ${items}`,
  contextTranscript: (count, scope) => `전사${scope ? ` · ${scope}` : ''} ${count}개 단락`,
  contextChapters: (count) => `챕터 ${count}개`,
  contextAttachments: (count) => `첨부 ${count}개`,
  contextSkills: (names) => `Skill ${names}`,
  contextImages: (count) => `; 이미지는 모델에 보내지 않으므로 이미지 ${count}개는 건너뜁니다`,
  modelHint: (model, applies, local) =>
    `${model ? `${model}을(를) 직접 호출합니다` : '모델을 직접 호출합니다'}(대화 없음). ${applies ? '끝나면 바로 적용되고 한 번에 실행 취소할 수 있습니다' : '결과는 읽고 복사하기 위한 것이며 영상에는 쓰지 않습니다'}. ${local ? '로컬 모델이라 이 컴퓨터 밖으로 나가지 않습니다.' : '클라우드 모델은 사용량에 따라 과금됩니다.'}`,
  ctaPolish: '다듬기',
  ctaChapters: '챕터 만들기',
  ctaSummary: '요약 쓰기',
  ctaBlog: '블로그 글 쓰기',
  ctaTitle: '제목 제안',
  ctaDesc: '설명 쓰기',
  noTextModel: '먼저 텍스트 모델을 연결하세요',
  runSubmitting: '시작하는 중…',
  runQueued: '대기 중',
  runRunning: (model) => `${model} 작업 중`,
  runBatches: (done, total) => `${total}개 중 ${done}번째`,
  runNote: '백그라운드에서 실행됩니다. 이 페이지를 떠났다가 다시 와도 됩니다.',
  cancel: '취소',
  cancelled: '취소됨',
  cancelFailed: (message) => `취소하지 못했습니다: ${message}`,
  submitFailed: '시작하지 못했습니다',
  failed: '실패',
  interrupted: '중단됨',
  needsDecision: '「작업」에서 결정이 필요합니다',
  openTasks: '작업 열기',
  retry: '다시 시도',
  dismiss: '닫기',
  badResult: 'Runtime이 돌려준 결과를 이 페이지에서 읽을 수 없습니다.',
  resultFrom: (model) => `${model} 결과 · 영상에는 쓰지 않음`,
  resultCut: '모델이 출력 한도에 닿아 끝부분이 잘렸을 수 있습니다.',
  resultSkipped: (skipped) => `첨부 ${skipped}개를 보내지 않았습니다(이미지와 바이너리 파일은 건너뜀).`,
  copy: '복사',
  copied: '복사됨',
  copyFailed: '복사하지 못했습니다',
  done: '완료',
  appliedPolish: (count) => `다듬음 · 단어 ${count}개 변경`,
  appliedChapters: (count) => `타임라인에 챕터 ${count}개를 설정했습니다`,
  appliedNothing: '모델이 바꿀 것을 제안하지 않아 아무것도 쓰지 않았습니다.',
  undo: '실행 취소',
  undone: '실행 취소됨',
  undoFailed: '실행 취소하지 못했습니다',
  stateResult: '결과 있음',
  statePercent: (percent) => `${percent}%`,
  statePending: (count) => `${count}곳 미정`,
  stateStale: (count) => `${count}문장 오래됨`,
  stateLast: (when) => `지난번 · ${when}`,
};
