import type { AiToolsMessages } from './ai-tools-copy.ts';

export const zhHans: AiToolsMessages = {
  back: '返回',

  // 设置态
  who: '用',
  whoAgent: '交给 Agent',
  whoModel: '直接调模型',
  whoModelSub: '这一项 Runtime 还没有对应的流程，只能交给 Agent',
  scope: '范围',
  scopeAll: '整篇',
  scopeChapter: (index: number, label: string) => `第 ${index} 章 · ${label}`,
  scopeNoChapters: '时间线上还没有章节，只能整篇',
  cta: '交给 Agent',
  queued: 'Agent 正在忙 · 这句话已排队，等这一轮结束再发',
  noConversation: '这个视频不在任何项目或会话里，没法交给 Agent。',
  createFailed: (message: string) => `没能新建会话：${message}`,

  // 勾选项与自定义
  prePolish: '先润色一遍（自动分段）',
  prePolishOn: '章节按段落聚合',
  prePolishOff: '还没润色过的文稿只有 1 段，章节会很粗',
  staleEdited: '原文改过的句子',
  staleEditedSub: '你在文稿里改过字，译文还是旧的',
  staleCut: '原文被剪切的句子',
  staleCutSub: '剪口播剪掉了半句；按剪后的原文重译',
  staleNone: '至少勾一类',
  staleOnly: (language: string) => `只处理${language}这一份译文`,
  retranscribeModel: '用哪个语音模型由 Agent 按本机装好的模型挑；想指定就写在下面的指令里。',
  /** 重新转录「更多选项」开着识别说话人、要由「说话人区分」来做时，加进发给 Agent 的那句话（设计稿 panel-aitools.jsx）。 */
  retranscribeSpeakers: '转写后识别说话人',

  // 写作与发布
  platform: '发到哪',
  platformPlaceholder: '要发的平台，可空；按它的规定写，写完提醒你核对',
  titleCount: '候选数',
  titleCountNote: (min: number, max: number) => `${min}–${max} 个，角度各不相同`,
  coverCount: '出几张',
  coverIdea: '要说的一件事',
  coverIdeaPlaceholder: '这支视频最想让人点开的那一点；可空，空着就让 Agent 从文稿里找',
  coverRatio: '画幅',
  coverRatioProject: '跟视频画布',
  coverText: '封面字',

  // 还做不了的
  soon: '即将推出',
  chaptersPolishFirst: '先润色并分段，再生成章节',

  session: '会话',
  promptLabel: '要对 Agent 说的话',
  promptPlaceholder: '要做什么、怎么做；@ 引用章节或说话人',
  restoreDefault: '恢复默认',
  skillNote: '这个工具的做法',
  noSkill: '没挂 skill：只按上面的提示词做。',
  addSkillBack: '加回这个工具的 skill',
  sentNew: '已交给 Agent · 新会话',
  sentCurrent: '已交给 Agent · 接着当前会话',
  agentCardTitle: '不在下面列表里的活，用一句话交给 Agent',
  agentCardSomeAgent: 'Agent',
  agentCardOutside: '打开这部视频所在的会话，视频作为上下文 →',
  noTranscriptTitle: '这部视频还没有文稿',
  noTranscriptBody: '这里的工具都从文稿出发：润色、分章、写总结、起标题都要先有转录。',
  goTranscribe: '去转录',
  stateRunning: '在跑',
  stateReview: '待处理',
  agentCardNew: (agent) => `新开一条会话，这部视频作为上下文；在本机 ${agent} 里跑，写入前会先问你 →`,
  stateChapters: (count) => `${count} 章`,

  whyRetranscribe: '要用语音模型，而 Runtime 的转录是整篇另加一份转写、不按范围替换，只能交给 Agent',
  whyCleanup: '找可剪的口要结合上下文逐处斟酌，只能交给 Agent',
  whyStale: '只重译过期句子这件事 Runtime 还没有对应的流程，只能交给 Agent',
  whyCover: '做封面要生成、合成图片，只能交给 Agent',
  modelPromptLabel: '提示词',
  modelPicker: '文本模型',
  modelNone: '没有文本模型',
  modelNoStructured: '这只模型不支持结构化输出，这个工具要用到',
  modelPolishNote: '直接调模型只逐词改错字、补标点，不分段；要分段请交给 Agent。',
  modelGateBody: '这个工具把提示词和文稿发给文本模型。',
  skillsAsSystem: '挂着的 Skill 会作为系统提示词发给模型：只带 SKILL.md 和用到的 references/，不带别的文件。',
  contextNone: '发给模型的：只有上面的提示词',
  contextLine: (items) => `发给模型的：提示词 + ${items}`,
  contextTranscript: (count, scope) => `文稿${scope ? ` · ${scope}` : ''} ${count} 段`,
  contextChapters: (count) => `章节 ${count} 章`,
  contextAttachments: (count) => `附件 ${count} 个`,
  contextSkills: (names) => `Skill ${names}`,
  contextImages: (count) => `；图片不发给模型，${count} 张图片会略过`,
  modelHint: (model, applies, local) =>
    `${model ? `直接调 ${model}` : '直接调模型'}，不经过对话；${applies ? '完成即应用，可一键撤销' : '结果给你读、拷走，不写进视频'}。${local ? '本机模型，不出本机。' : '云端模型按用量计费。'}`,
  ctaPolish: '润色',
  ctaChapters: '生成章节',
  ctaSummary: '写总结',
  ctaBlog: '写博客',
  ctaTitle: '起标题',
  ctaDesc: '写简介',
  noTextModel: '先连接一个文本模型',
  runSubmitting: '正在开始…',
  runQueued: '排队中',
  runRunning: (model) => `${model} 正在工作`,
  runBatches: (done, total) => `第 ${done} / ${total} 部分`,
  runNote: '在后台跑；可以离开这一页，回来再看。',
  cancel: '取消',
  cancelled: '已取消',
  cancelFailed: (message) => `没能取消：${message}`,
  submitFailed: '没能开始',
  failed: '失败',
  interrupted: '中断了',
  needsDecision: '要你在「任务」里决定',
  openTasks: '打开任务',
  retry: '重试',
  dismiss: '知道了',
  badResult: 'Runtime 返回的结果这一页读不懂。',
  resultFrom: (model) => `来自 ${model} · 没写进视频`,
  resultCut: '模型写到了输出上限，结尾可能被截断。',
  resultSkipped: (skipped) => `${skipped} 个附件没发出去（图片和二进制文件会略过）。`,
  copy: '复制',
  copied: '已复制',
  copyFailed: '没能复制',
  done: '完成',
  appliedPolish: (count) => `已润色 · 改了 ${count} 个词`,
  appliedChapters: (count) => `时间线上设了 ${count} 章`,
  appliedNothing: '模型没有提出改动，什么也没写。',
  undo: '撤销',
  undone: '已撤销',
  undoFailed: '没能撤销',
  stateResult: '有结果',
  statePercent: (percent) => `${percent}%`,
  statePending: (count) => `${count} 处待定`,
  stateStale: (count) => `${count} 句过期`,
  stateLast: (when) => `上次 · ${when}`,
};
