import { pluralForm } from '@baocut/protocol';
import type { AiToolsMessages } from './ai-tools-copy.ts';

export const ru: AiToolsMessages = {
  back: "Назад",

  who: "Выбрать",
  whoAgent: "Передать агенту",
  whoModel: "Вызвать модель напрямую",
  whoModelSub: "В Runtime ещё нет процесса для этого, выполнить может только агент",
  scope: "Область",
  scopeAll: "Всё видео",
  scopeChapter: (index: number, label: string) => `Глава ${index} · ${label}`,
  scopeNoChapters: "На таймлайне ещё нет глав, доступно только всё видео",
  cta: "Передать агенту",
  queued: "Агент занят · сообщение в очереди и отправится после итерации",
  noConversation: "Видео вне проекта или сессии, передать агенту нельзя.",
  createFailed: (message: string) => `Не удалось создать сессию: ${message}`,

  prePolish: "Сначала отредактировать (автоабзацы)",
  prePolishOn: "Главы группируются по абзацам",
  prePolishOff: "Неотредактированная расшифровка имеет только 1 абзац, главы будут грубыми",
  framesLabel: 'Добавить иллюстрации из ключевых кадров',
  framesSub: 'Берёт кадры из видео и вставляет их туда, где нужна иллюстрация; по умолчанию выключено',
  framesSubModel: 'При прямом вызове модели кадры из видео недоступны; чтобы добавить их, передайте задачу Agent',
  staleEdited: "Предложения с правками в оригинале",
  staleEditedSub: "Слова в расшифровке изменены, перевод ещё старый",
  staleCut: "Предложения с вырезанием из оригинала",
  staleCutSub: "Вырезана часть предложения; переведите заново из изменённого оригинала",
  staleNone: "Отметьте хотя бы одно",
  staleOnly: (language: string) => `Только ${language} — перевод`,
  retranscribeModel: "Агент выбирает речевую модель из установленных на компьютере; для выбора укажите в инструкциях ниже.",

  retranscribeSpeakers: "Определить говорящих после расшифровки",

  platform: "Где публиковать",
  platformPlaceholder: "Платформа публикации (по желанию); соблюдает правила и напоминает проверить",
  titleCount: "Варианты",
  titleCountNote: (min: number, max: number) => `${min}–${max}, каждый с другого ракурса`,
  coverCount: "Сколько",
  coverIdea: "Главная мысль",
  coverIdeaPlaceholder: "Что заставит открыть видео (по желанию); оставьте пустым, агент найдёт в расшифровке",
  coverRatio: "Соотношение сторон",
  coverRatioProject: "Как холст видео",
  coverText: "Текст на обложке",

  soon: "Скоро",
  chaptersPolishFirst: "Сначала отредактировать и разбить на абзацы, затем создать главы",

  session: 'Сессия',
  promptLabel: 'Что сказать агенту',
  promptPlaceholder: 'Что и как сделать; @ — ссылка на главу или говорящего',
  restoreDefault: 'Вернуть по умолчанию',
  skillNote: 'Метод этого инструмента',
  noSkill: 'Skill не прикреплён: агент следует только тексту выше.',
  addSkillBack: 'Вернуть skill этого инструмента',
  sentNew: 'Передано агенту · новая сессия',
  sentCurrent: 'Передано агенту · в текущей сессии',
  agentCardTitle: 'То, чего нет ниже, поручите агенту одной фразой',
  agentCardSomeAgent: 'агенте',
  agentCardOutside: 'Откроет сессию этого видео, видео — в контексте →',
  noTranscriptTitle: 'У этого видео пока нет расшифровки',
  noTranscriptBody: 'Все эти инструменты работают от расшифровки: для правки, глав, резюме и заголовков сначала нужна транскрипция.',
  goTranscribe: 'К расшифровке',
  stateRunning: 'Идёт',
  stateReview: 'Ждёт проверки',
  agentCardNew: (agent) => `Новая сессия с этим видео в контексте; работает в ${agent} на этом компьютере и спрашивает перед записью →`,
  stateChapters: (count) => pluralForm('ru', count, { one: `${count} глава`, few: `${count} главы`, many: `${count} глав`, other: `${count} главы` }),

  whyRetranscribe: 'Нужна речевая модель, а расшифровка в Runtime добавляет целую новую расшифровку, а не заменяет участок, поэтому это может только Agent',
  whyCleanup: 'Чтобы найти, что вырезать, нужно взвесить каждое место в контексте, поэтому это может только Agent',
  whyStale: 'В Runtime ещё нет процесса, который переводит заново только устаревшие предложения, поэтому это может только Agent',
  whyCover: 'Для обложки нужно создавать и компоновать изображения, поэтому это может только Agent',
  modelPromptLabel: 'Промпт',
  modelPicker: 'Текстовая модель',
  modelNone: 'Нет текстовой модели',
  modelNoStructured: 'Эта модель не поддерживает структурированный вывод, а он нужен этому инструменту',
  modelPolishNote: 'При прямом вызове модели исправляются только опечатки и пунктуация по словам; на абзацы текст не делится. Для этого передайте задачу Agent.',
  modelGateBody: 'Этот инструмент отправляет промпт и расшифровку текстовой модели.',
  skillsAsSystem: 'Прикреплённые skills уходят модели как системный промпт: только SKILL.md и используемые им файлы references/, больше ничего.',
  contextNone: 'Модели уходит: только промпт выше',
  contextLine: (items) => `Модели уходит: промпт + ${items}`,
  contextTranscript: (count, scope) =>
    `расшифровка${scope ? ` · ${scope}` : ''} ${pluralForm('ru', count, { one: `${count} абзац`, few: `${count} абзаца`, many: `${count} абзацев`, other: `${count} абзаца` })}`,
  contextChapters: (count) => `главы: ${count}`,
  contextAttachments: (count) => `вложения: ${count}`,
  contextSkills: (names) => `Skill ${names}`,
  contextImages: (count) => `; изображения модели не отправляются, будет пропущено изображений: ${count}`,
  modelHint: (model, applies, local) =>
    `${model ? `Вызывает ${model} напрямую` : 'Вызывает модель напрямую'}, без беседы; ${applies ? 'применяется по завершении, отменяется одним шагом' : 'результат — чтобы прочитать и скопировать, в видео ничего не пишется'}. ${local ? 'Локальная модель, данные не покидают компьютер.' : 'Облачные модели тарифицируются по использованию.'}`,
  ctaPolish: 'Отшлифовать',
  ctaChapters: 'Создать главы',
  ctaSummary: 'Написать резюме',
  ctaBlog: 'Написать пост для блога',
  ctaTitle: 'Предложить заголовки',
  ctaDesc: 'Написать описание',
  noTextModel: 'Сначала подключите текстовую модель',
  runSubmitting: 'Запуск…',
  runQueued: 'В очереди',
  runRunning: (model) => `${model} работает`,
  runBatches: (done, total) => `Часть ${done} из ${total}`,
  runNote: 'Работает в фоне; можно уйти с этой страницы и вернуться позже.',
  cancel: 'Отмена',
  cancelled: 'Отменено',
  cancelFailed: (message) => `Не удалось отменить: ${message}`,
  submitFailed: 'Не удалось запустить',
  failed: 'Ошибка',
  interrupted: 'Прервано',
  needsDecision: 'Нужно ваше решение в разделе «Задачи»',
  openTasks: 'Открыть задачи',
  retry: 'Повторить',
  dismiss: 'Закрыть',
  badResult: 'Runtime вернул результат, который эта страница не может прочитать.',
  resultFrom: (model) => `От ${model} · в видео не записано`,
  resultCut: 'Модель упёрлась в лимит вывода, конец может быть обрезан.',
  resultSkipped: (skipped) => `Не отправлено вложений: ${skipped} (изображения и двоичные файлы пропускаются).`,
  copy: 'Копировать',
  copied: 'Скопировано',
  copyFailed: 'Не удалось скопировать',
  done: 'Готово',
  appliedPolish: (count) => `Отшлифовано · изменено слов: ${count}`,
  appliedChapters: (count) => `На шкале времени задано глав: ${count}`,
  appliedNothing: 'Модель не предложила изменений; ничего не записано.',
  undo: 'Отменить',
  undone: 'Отменено',
  undoFailed: 'Не удалось отменить',
  stateResult: 'Есть результат',
  statePercent: (percent) => `${percent}%`,
  statePending: (count) => `Не решено: ${count}`,
  stateStale: (count) => `Устарело: ${count}`,
  stateLast: (when) => `Последний · ${when}`,
};
