import type { AiToolsMessages } from './ai-tools-copy.ts';

export const nl: AiToolsMessages = {
  back: "Terug",

  who: "Kiezen",
  whoAgent: "Overdragen aan de agent",
  whoModel: "Een model rechtstreeks aanroepen",
  whoModelSub: "De Runtime heeft hier nog geen workflow voor, dus alleen de agent kan dit doen",
  scope: "Bereik",
  scopeAll: "Hele video",
  scopeChapter: (index: number, label: string) => `Hoofdstuk ${index} · ${label}`,
  scopeNoChapters: "De tijdlijn heeft nog geen hoofdstukken, dus alleen de hele video is beschikbaar",
  cta: "Overdragen aan de agent",
  queued: "De agent is bezig · het bericht staat in de wachtrij en wordt verzonden wanneer deze beurt eindigt",
  noConversation: "Deze video staat niet in een project of sessie, dus kan niet worden overgedragen aan de agent.",
  createFailed: (message: string) => `Kan geen sessie maken: ${message}`,

  prePolish: "Eerst verbeteren (automatische alinea’s)",
  prePolishOn: "Hoofdstukken worden gegroepeerd op alinea",
  prePolishOff: "Een onbewerkt transcript heeft slechts 1 alinea, dus hoofdstukken worden grof",
  staleEdited: "Zinnen bewerkt in het origineel",
  staleEditedSub: "Je hebt woorden in het transcript gewijzigd, maar de vertaling is nog de oude",
  staleCut: "Zinnen geknipt uit het origineel",
  staleCutSub: "Een knip heeft een deel van een zin verwijderd; vertaal opnieuw vanuit het geknipte origineel",
  staleNone: "Selecteer er minstens één",
  staleOnly: (language: string) => `Alleen de ${language} vertaling`,
  retranscribeModel: "De agent kiest een spraakmodel uit de modellen die op deze computer zijn geïnstalleerd; geef in de instructies hieronder aan als je er een wilt kiezen.",

  retranscribeSpeakers: "Sprekers identificeren na transcriptie",

  platform: "Waar plaatsen",
  platformPlaceholder: "Het platform om op te plaatsen (optioneel); de regels van dat platform worden gevolgd en je wordt herinnerd om te controleren",
  titleCount: "Kandidaten",
  titleCountNote: (min: number, max: number) => `${min}–${max}, elk vanuit een andere invalshoek`,
  coverCount: "Hoeveel",
  coverIdea: "Het ene punt",
  coverIdeaPlaceholder: "Wat mensen op deze video zou laten klikken (optioneel); laat het leeg om de agent dit in het transcript te laten vinden",
  coverRatio: "Beeldverhouding",
  coverRatioProject: "Gelijk aan het videocanvas",
  coverText: "Covertekst",

  soon: "Binnenkort beschikbaar",
  chaptersPolishFirst: "Eerst verbeteren en opdelen in alinea’s en daarna hoofdstukken genereren",

  session: 'Sessie',
  promptLabel: 'Wat je de agent vertelt',
  promptPlaceholder: 'Wat en hoe; gebruik @ om naar hoofdstukken of sprekers te verwijzen',
  restoreDefault: 'Standaard herstellen',
  skillNote: 'Hoe deze tool werkt',
  noSkill: 'Geen skill gekoppeld: de agent volgt alleen de tekst hierboven.',
  addSkillBack: 'Skill van deze tool weer toevoegen',
  sentNew: 'Doorgegeven aan de agent · nieuwe sessie',
  sentCurrent: 'Doorgegeven aan de agent · verder in de huidige sessie',
  agentCardTitle: 'Staat het niet hieronder? Zeg het de agent in één zin',
  agentCardSomeAgent: 'de agent',
  agentCardOutside: 'Opent de sessie van deze video, met de video als context →',
  noTranscriptTitle: 'Deze video heeft nog geen transcript',
  noTranscriptBody: 'Deze tools gaan allemaal uit van het transcript: polijsten, hoofdstukken, samenvattingen en titels vragen eerst een transcriptie.',
  goTranscribe: 'Naar transcript',
  stateRunning: 'Bezig',
  stateReview: 'Te bekijken',
  agentCardNew: (agent) => `Start een nieuwe sessie met deze video als context; draait in ${agent} op deze computer en vraagt eerst voor het schrijven →`,
  stateChapters: (count) => (count === 1 ? '1 hoofdstuk' : `${count} hoofdstukken`),
};
