import { pluralForm } from '@baocut/protocol';
import type { AiToolsMessages } from './ai-tools-copy.ts';

export const pl: AiToolsMessages = {
  back: "Wstecz",

  who: "Wybierz",
  whoAgent: "Przekaż agentowi",
  whoModel: "Wywołaj model bezpośrednio",
  whoModelSub: "Runtime nie ma jeszcze procesu dla tego, więc może wykonać tylko agent",
  scope: "Zakres",
  scopeAll: "Całe wideo",
  scopeChapter: (index: number, label: string) => `Rozdział ${index} · ${label}`,
  scopeNoChapters: "Oś czasu nie ma jeszcze rozdziałów, dostępne tylko całe wideo",
  byAgent: "Wykonuje agent",
  cta: "Przekaż agentowi",
  queued: "Agent zajęty · wiadomość w kolejce, zostanie wysłana po turze",
  noConversation: "Wideo jest poza projektem lub sesją, nie można przekazać agentowi.",
  createFailed: (message: string) => `Nie udało się utworzyć sesji: ${message}`,

  prePolish: "Najpierw popraw (automatyczne akapity)",
  prePolishOn: "Rozdziały są grupowane według akapitów",
  prePolishOff: "Niepoprawiona transkrypcja ma tylko 1 akapit, więc rozdziały będą ogólne",
  staleEdited: "Zdania zmienione w oryginale",
  staleEditedSub: "Zmieniono słowa transkrypcji, ale tłumaczenie nadal stare",
  staleCut: "Zdania wycięte z oryginału",
  staleCutSub: "Cięcie usunęło część zdania; przetłumacz ponownie zmieniony oryginał",
  staleNone: "Zaznacz co najmniej jedno",
  staleOnly: (language: string) => `Tylko ${language} – tłumaczenie`,
  retranscribeModel: "Agent wybiera model mowy spośród zainstalowanych; aby wybrać, podaj w instrukcjach poniżej.",

  retranscribeSpeakers: "Rozpoznaj mówców po transkrypcji",

  platform: "Gdzie publikować",
  platformPlaceholder: "Platforma publikacji (opcjonalnie); przestrzega jej zasad i przypomina o sprawdzeniu",
  titleCount: "Propozycje",
  titleCountNote: (min: number, max: number) => `${min}–${max}, każda z innego punktu widzenia`,
  coverCount: "Ile",
  coverIdea: "Jedna rzecz do przekazania",
  coverIdeaPlaceholder: "Co zachęci do kliknięcia wideo (opcjonalnie); pozostaw puste, agent znajdzie w transkrypcji",
  coverRatio: "Proporcje",
  coverRatioProject: "Tak jak płótno wideo",
  coverText: "Tekst na okładce",

  soon: "Wkrótce",
  chaptersPolishFirst: "Najpierw popraw i podziel na akapity, potem generuj rozdziały",

  session: 'Sesja',
  promptLabel: 'Co przekazać agentowi',
  promptPlaceholder: 'Co i jak zrobić; @ odwołuje się do rozdziału lub mówcy',
  restoreDefault: 'Przywróć domyślne',
  skillNote: 'Sposób działania tego narzędzia',
  noSkill: 'Brak skilla: agent kieruje się tylko tekstem powyżej.',
  addSkillBack: 'Przywróć skill tego narzędzia',
  sentNew: 'Przekazano agentowi · nowa sesja',
  sentCurrent: 'Przekazano agentowi · w bieżącej sesji',
  agentCardTitle: 'Czego nie ma poniżej, powiedz agentowi jednym zdaniem',
  agentCardSomeAgent: 'agencie',
  agentCardOutside: 'Otwiera sesję tego wideo, z wideo jako kontekstem →',
  noTranscriptTitle: 'To wideo nie ma jeszcze transkrypcji',
  noTranscriptBody: 'Wszystkie te narzędzia wychodzą od transkrypcji: poprawki, rozdziały, podsumowania i tytuły wymagają jej najpierw.',
  goTranscribe: 'Przejdź do transkrypcji',
  stateRunning: 'W toku',
  stateReview: 'Do przejrzenia',
  agentCardNew: (agent) => `Nowa sesja z tym wideo jako kontekstem; działa w ${agent} na tym komputerze i pyta przed zapisem →`,
  stateChapters: (count) => pluralForm('pl', count, { one: `${count} rozdział`, few: `${count} rozdziały`, many: `${count} rozdziałów`, other: `${count} rozdziału` }),
};
