import { pluralForm } from '@baocut/protocol';
import type { AiToolsMessages } from './ai-tools-copy.ts';

export const pl: AiToolsMessages = {
  back: "Wstecz",

  who: "Wybierz",
  whoAgent: "Przekaż agentowi",
  whoModel: "Wywołaj model bezpośrednio",
  whoModelSub: "Runtime nie ma jeszcze procesu dla tego, więc może wykonać tylko agent",
  scope: "Zakres",
  scopeAll: "Całe wideo",
  scopeChapter: (index: number, label: string) => `Rozdział ${index} · ${label}`,
  scopeNoChapters: "Oś czasu nie ma jeszcze rozdziałów, dostępne tylko całe wideo",
  cta: "Przekaż agentowi",
  queued: "Agent zajęty · wiadomość w kolejce, zostanie wysłana po turze",
  noConversation: "Wideo jest poza projektem lub sesją, nie można przekazać agentowi.",
  createFailed: (message: string) => `Nie udało się utworzyć sesji: ${message}`,

  prePolish: "Najpierw popraw (automatyczne akapity)",
  prePolishOn: "Rozdziały są grupowane według akapitów",
  prePolishOff: "Niepoprawiona transkrypcja ma tylko 1 akapit, więc rozdziały będą ogólne",
  staleEdited: "Zdania zmienione w oryginale",
  staleEditedSub: "Zmieniono słowa transkrypcji, ale tłumaczenie nadal stare",
  staleCut: "Zdania wycięte z oryginału",
  staleCutSub: "Cięcie usunęło część zdania; przetłumacz ponownie zmieniony oryginał",
  staleNone: "Zaznacz co najmniej jedno",
  staleOnly: (language: string) => `Tylko ${language} – tłumaczenie`,
  retranscribeModel: "Agent wybiera model mowy spośród zainstalowanych; aby wybrać, podaj w instrukcjach poniżej.",

  retranscribeSpeakers: "Rozpoznaj mówców po transkrypcji",

  platform: "Gdzie publikować",
  platformPlaceholder: "Platforma publikacji (opcjonalnie); przestrzega jej zasad i przypomina o sprawdzeniu",
  titleCount: "Propozycje",
  titleCountNote: (min: number, max: number) => `${min}–${max}, każda z innego punktu widzenia`,
  coverCount: "Ile",
  coverIdea: "Jedna rzecz do przekazania",
  coverIdeaPlaceholder: "Co zachęci do kliknięcia wideo (opcjonalnie); pozostaw puste, agent znajdzie w transkrypcji",
  coverRatio: "Proporcje",
  coverRatioProject: "Tak jak płótno wideo",
  coverText: "Tekst na okładce",

  soon: "Wkrótce",
  chaptersPolishFirst: "Najpierw popraw i podziel na akapity, potem generuj rozdziały",

  session: 'Sesja',
  promptLabel: 'Co przekazać agentowi',
  promptPlaceholder: 'Co i jak zrobić; @ odwołuje się do rozdziału lub mówcy',
  restoreDefault: 'Przywróć domyślne',
  skillNote: 'Sposób działania tego narzędzia',
  noSkill: 'Brak skilla: agent kieruje się tylko tekstem powyżej.',
  addSkillBack: 'Przywróć skill tego narzędzia',
  sentNew: 'Przekazano agentowi · nowa sesja',
  sentCurrent: 'Przekazano agentowi · w bieżącej sesji',
  agentCardTitle: 'Czego nie ma poniżej, powiedz agentowi jednym zdaniem',
  agentCardSomeAgent: 'agencie',
  agentCardOutside: 'Otwiera sesję tego wideo, z wideo jako kontekstem →',
  noTranscriptTitle: 'To wideo nie ma jeszcze transkrypcji',
  noTranscriptBody: 'Wszystkie te narzędzia wychodzą od transkrypcji: poprawki, rozdziały, podsumowania i tytuły wymagają jej najpierw.',
  goTranscribe: 'Przejdź do transkrypcji',
  stateRunning: 'W toku',
  stateReview: 'Do przejrzenia',
  agentCardNew: (agent) => `Nowa sesja z tym wideo jako kontekstem; działa w ${agent} na tym komputerze i pyta przed zapisem →`,
  stateChapters: (count) => pluralForm('pl', count, { one: `${count} rozdział`, few: `${count} rozdziały`, many: `${count} rozdziałów`, other: `${count} rozdziału` }),

  whyRetranscribe: 'Wymaga modelu mowy, a transkrypcja w Runtime dodaje całą nową transkrypcję zamiast zastąpić fragment, więc może to zrobić tylko Agent',
  whyCleanup: 'Znalezienie cięć wymaga rozważenia każdego miejsca w kontekście, więc może to zrobić tylko Agent',
  whyStale: 'Runtime nie ma jeszcze procesu, który tłumaczy ponownie tylko nieaktualne zdania, więc może to zrobić tylko Agent',
  whyCover: 'Okładka wymaga generowania i składania obrazów, więc może to zrobić tylko Agent',
  modelPromptLabel: 'Prompt',
  modelPicker: 'Model tekstowy',
  modelNone: 'Brak modelu tekstowego',
  modelNoStructured: 'Ten model nie obsługuje ustrukturyzowanego wyjścia, którego wymaga to narzędzie',
  modelPolishNote: 'Przy bezpośrednim wywołaniu modelu poprawiane są tylko literówki i interpunkcja słowo po słowie; bez podziału na akapity. Do tego przekaż zadanie Agentowi.',
  modelGateBody: 'To narzędzie wysyła prompt i transkrypcję do modelu tekstowego.',
  skillsAsSystem: 'Dołączone skille trafiają do modelu jako prompt systemowy: tylko SKILL.md i używane przez niego pliki references/, nic więcej.',
  contextNone: 'Do modelu trafia: tylko prompt powyżej',
  contextLine: (items) => `Do modelu trafia: prompt + ${items}`,
  contextTranscript: (count, scope) =>
    `transkrypcja${scope ? ` · ${scope}` : ''} ${pluralForm('pl', count, { one: `${count} akapit`, few: `${count} akapity`, many: `${count} akapitów`, other: `${count} akapitu` })}`,
  contextChapters: (count) => `rozdziały: ${count}`,
  contextAttachments: (count) => `załączniki: ${count}`,
  contextSkills: (names) => `Skill ${names}`,
  contextImages: (count) => `; obrazy nie trafiają do modelu, pominięte obrazy: ${count}`,
  modelHint: (model, applies, local) =>
    `${model ? `Wywołuje ${model} bezpośrednio` : 'Wywołuje model bezpośrednio'}, bez rozmowy; ${applies ? 'zmiany są stosowane po zakończeniu, cofniesz je jednym krokiem' : 'wynik jest do przeczytania i skopiowania, nic nie trafia do wideo'}. ${local ? 'Model lokalny, nie opuszcza tego komputera.' : 'Modele w chmurze są rozliczane za użycie.'}`,
  ctaPolish: 'Dopracuj',
  ctaChapters: 'Utwórz rozdziały',
  ctaSummary: 'Napisz podsumowanie',
  ctaBlog: 'Napisz wpis na blog',
  ctaTitle: 'Zaproponuj tytuły',
  ctaDesc: 'Napisz opis',
  noTextModel: 'Najpierw połącz model tekstowy',
  runSubmitting: 'Uruchamianie…',
  runQueued: 'W kolejce',
  runRunning: (model) => `${model} pracuje`,
  runBatches: (done, total) => `Część ${done} z ${total}`,
  runNote: 'Działa w tle; możesz opuścić tę stronę i wrócić później.',
  cancel: 'Anuluj',
  cancelled: 'Anulowano',
  cancelFailed: (message) => `Nie udało się anulować: ${message}`,
  submitFailed: 'Nie udało się uruchomić',
  failed: 'Niepowodzenie',
  interrupted: 'Przerwano',
  needsDecision: 'Wymaga Twojej decyzji w Zadaniach',
  openTasks: 'Otwórz Zadania',
  retry: 'Spróbuj ponownie',
  dismiss: 'Zamknij',
  badResult: 'Runtime zwrócił wynik, którego ta strona nie umie odczytać.',
  resultFrom: (model) => `Od ${model} · nie zapisano w wideo`,
  resultCut: 'Model osiągnął limit wyjścia, więc koniec może być ucięty.',
  resultSkipped: (skipped) => `Niewysłane załączniki: ${skipped} (obrazy i pliki binarne są pomijane).`,
  copy: 'Kopiuj',
  copied: 'Skopiowano',
  copyFailed: 'Nie udało się skopiować',
  done: 'Gotowe',
  appliedPolish: (count) => `Dopracowano · zmienione słowa: ${count}`,
  appliedChapters: (count) => `Ustawione rozdziały na osi czasu: ${count}`,
  appliedNothing: 'Model nie zaproponował zmian; nic nie zapisano.',
  undo: 'Cofnij',
  undone: 'Cofnięto',
  undoFailed: 'Nie udało się cofnąć',
  stateResult: 'Wynik gotowy',
};
