import type { AiToolsMessages } from './ai-tools-copy.ts';

export const tr: AiToolsMessages = {
back: 'Geri',
  // 设置态
  who: 'Kullan', whoAgent: 'Ajana ver', whoAgentSub: 'Bu videonun oturumunda çalışır', whoModel: 'Modeli doğrudan çağır', whoModelSub: 'Runtime içinde henüz iş akışı yok; yalnızca ajan yapabilir', scope: 'Kapsam', scopeAll: 'Tüm video', scopeChapter: (index, label) => `Bölüm ${index} · ${label}`, scopeNoChapters: 'Zaman çizelgesinde henüz bölüm yok; yalnızca tüm video kullanılabilir', byAgent: 'Ajan yapar', preview: 'Ajana gönderilecek içerik', cta: 'Ajana ver', ctaHint: 'Yukarıdaki mesajı bu videonun oturumuna gönderir; ajan hemen başlar. Gerekirse önce yukarıda düzenleyin.', ctaNoVideo: 'Video henüz açık değil; verilecek içerik yok.', sent: 'Ajana verildi · oturumda çalışıyor', queued: 'Ajan meşgul · mesaj sırada, bu tur bitince gönderilir', sendFailed: (message) => `Gönderilemedi: ${message}`, noConversation: 'Bu video proje veya oturumda değil; ajana verilemez.', createFailed: (message) => `Oturum oluşturulamadı: ${message}`,
  // 勾选项与自定义
  prePolish: 'Önce düzelt (otomatik paragraflar)', prePolishOn: 'Bölümler paragrafa göre gruplanır', prePolishOff: 'Düzeltilmemiş dökümde yalnızca 1 paragraf var; bölümler kaba olur', noteTitle: 'Özel yönergeler (isteğe bağlı)', notePlaceholder: 'Konuşma dilini korumak veya marka adlarını değiştirmemek gibi ek gereksinimler…', staleEdited: 'Özgün metinde düzenlenmiş cümleler', staleEditedSub: 'Dökümde sözcükleri değiştirdiniz ancak çeviri hâlâ eski', staleCut: 'Özgün metinden kesilmiş cümleler', staleCutSub: 'Kesim cümlenin bir kısmını kaldırdı; kesilmiş kaynaktan yeniden çevir', staleNone: 'En az birini işaretleyin', staleOnly: (language) => `Yalnızca ${language} çevirisi`, retranscribeModel: 'Ajan bu bilgisayarda yüklü konuşma modellerinden seçer; seçmek için aşağıdaki yönergelerde belirtin.', retranscribeSpeakers: 'Yazıya dökmeden sonra konuşmacıları belirle',
  // 写作与发布
  length: 'Uzunluk', style: 'Stil', styleCustom: 'Nasıl yazılacağını kendi sözlerinizle tarif edin', view: 'Bakış açısı', viewAuto: 'Otomatik: ajan videonun kaynağına göre seçer', language: 'Dil', languageWrite: 'Arayüzle aynı', languagePublish: 'Dökümle aynı', platform: 'Yayın yeri', platformPlaceholder: 'Yayınlanacak platform (isteğe bağlı); platform kurallarını izler ve denetlemenizi hatırlatır', titleCount: 'Adaylar', titleCountNote: (min, max) => `${min}–${max}, her biri farklı açıdan`, coverCount: 'Sayı', coverIdea: 'Söylenecek tek şey', coverIdeaPlaceholder: 'Bu videoya neden tıklasınlar (isteğe bağlı); boş bırakırsanız ajan dökümden bulur', coverRatio: 'En boy oranı', coverRatioProject: 'Video tuvaliyle aynı', coverText: 'Kapak metni', writeNote: 'Başka bir şey (isteğe bağlı)', writeNotePlaceholder: 'Örneğin sonuçla başla veya konuğun adını belirt', titleNote: 'Bir gereksinim (isteğe bağlı)', titleNotePlaceholder: 'Örneğin soru olmasın veya konuğun adını içersin', coverNotePlaceholder: 'Örneğin kırmızı olmasın veya kişi sağda olsun',
  // 还做不了的
  soon: 'Yakında', chaptersPolishFirst: 'Önce düzeltip paragraflara böl, sonra bölümleri oluştur',
};
