import type { AiToolsMessages } from './ai-tools-copy.ts';

export const ptBR: AiToolsMessages = {
  back: "Voltar",

  who: "Usar",
  whoAgent: "Passar para o agente",
  whoModel: "Chamar o modelo",
  whoModelSub: "O Runtime ainda não tem este fluxo; só o agente pode fazer",
  scope: "Escopo",
  scopeAll: "Vídeo inteiro",
  scopeChapter: (index: number, label: string) => `Capítulo ${index} · ${label}`,
  scopeNoChapters: "Sem capítulos na linha do tempo; apenas o vídeo inteiro está disponível",
  cta: "Passar para o agente",
  queued: "O agente está ocupado · mensagem na fila, enviada ao fim deste turno",
  noConversation: "O vídeo não pertence a projeto ou sessão e não pode ser entregue ao agente.",
  createFailed: (message: string) => `Não foi possível criar sessão: ${message}`,

  prePolish: "Revisar primeiro (parágrafos automáticos)",
  prePolishOn: "Capítulos agrupados por parágrafo",
  prePolishOff: "Uma transcrição não revisada só tem 1 parágrafo; os capítulos serão pouco detalhados",
  staleEdited: "Frases editadas no original",
  staleEditedSub: "Você mudou palavras na transcrição; a tradução ainda é a antiga",
  staleCut: "Frases cortadas do original",
  staleCutSub: "O corte tirou parte da frase; retraduzir pelo original cortado",
  staleNone: "Marque ao menos uma opção",
  staleOnly: (language: string) => `Apenas a tradução ${language} tradução`,
  retranscribeModel: "O agente escolhe um modelo de fala instalado neste computador; indique sua escolha nas instruções abaixo.",

  retranscribeSpeakers: "Identificar falantes após transcrever",

  platform: "Publicar em",
  platformPlaceholder: "Onde vai ser publicado (opcional); escrito pelas regras de lá, com lembrete para conferir",
  titleCount: "Opções",
  titleCountNote: (min: number, max: number) => `${min}–${max}, cada um por um ângulo diferente`,
  coverCount: "Quantas",
  coverIdea: "A única coisa a dizer",
  coverIdeaPlaceholder: "O que faria as pessoas clicarem; opcional — deixe vazio para o agente achar na transcrição",
  coverRatio: "Proporção",
  coverRatioProject: "Igual ao canvas do vídeo",
  coverText: "Texto da capa",

  soon: "Em breve",
  chaptersPolishFirst: "Revisar e dividir em parágrafos, depois gerar capítulos",

  session: 'Sessão',
  promptLabel: 'O que dizer ao agente',
  promptPlaceholder: 'O que fazer e como; use @ para citar capítulos ou falantes',
  restoreDefault: 'Restaurar padrão',
  skillNote: 'Como esta ferramenta trabalha',
  noSkill: 'Sem skill: o agente segue só o texto acima.',
  addSkillBack: 'Adicionar de volta o skill desta ferramenta',
  sentNew: 'Enviado ao agente · nova sessão',
  sentCurrent: 'Enviado ao agente · continua na sessão atual',
  agentCardTitle: 'Para o que não está abaixo, diga ao agente numa frase',
  agentCardSomeAgent: 'o agente',
  agentCardOutside: 'Abre a sessão deste vídeo, com o vídeo como contexto →',
  noTranscriptTitle: 'Este vídeo ainda não tem transcrição',
  noTranscriptBody: 'Todas estas ferramentas partem da transcrição: polir, capítulos, resumos e títulos precisam de uma transcrição antes.',
  goTranscribe: 'Ir para a transcrição',
  stateRunning: 'Em andamento',
  stateReview: 'A rever',
  agentCardNew: (agent) => `Abre uma nova sessão com este vídeo como contexto; roda no ${agent} deste computador e pergunta antes de gravar →`,
  stateChapters: (count) => (count === 1 ? '1 capítulo' : `${count} capítulos`),

  whyRetranscribe: 'Precisa de um modelo de voz, e a transcrição do Runtime adiciona uma transcrição nova inteira em vez de substituir um trecho; só o agente pode fazer',
  whyCleanup: 'Encontrar cortes exige pesar cada ponto no contexto; só o agente pode fazer',
  whyStale: 'O Runtime ainda não tem um fluxo para retraduzir só as frases desatualizadas; só o agente pode fazer',
  whyCover: 'Uma capa exige gerar e compor imagens; só o agente pode fazer',
  modelPromptLabel: 'Prompt',
  modelPicker: 'Modelo de texto',
  modelNone: 'Nenhum modelo de texto',
  modelNoStructured: 'Este modelo não suporta saída estruturada, que esta ferramenta exige',
  modelPolishNote: 'Chamando um modelo diretamente, só erros de digitação e pontuação são corrigidos palavra por palavra; não divide em parágrafos. Para isso, envie ao agente.',
  modelGateBody: 'Esta ferramenta envia o prompt e a transcrição para um modelo de texto.',
  skillsAsSystem: 'Os skills anexados vão para o modelo como prompt de sistema: só o SKILL.md e os arquivos de references/ que ele usa, mais nada.',
  contextNone: 'Enviado ao modelo: só o prompt acima',
  contextLine: (items) => `Enviado ao modelo: prompt + ${items}`,
  contextTranscript: (count, scope) => `transcrição${scope ? ` · ${scope}` : ''} ${count === 1 ? '1 parágrafo' : `${count} parágrafos`}`,
  contextChapters: (count) => `capítulos ${count}`,
  contextAttachments: (count) => `anexos ${count}`,
  contextSkills: (names) => `Skill ${names}`,
  contextImages: (count) => `; imagens não vão para o modelo, então ${count === 1 ? '1 imagem será ignorada' : `${count} imagens serão ignoradas`}`,
  modelHint: (model, applies, local) =>
    `${model ? `Chama ${model} diretamente` : 'Chama um modelo diretamente'}, sem conversa; ${applies ? 'aplica ao terminar, com desfazer em um passo' : 'o resultado é para ler e copiar, nada é gravado no vídeo'}. ${local ? 'Modelo local, fica neste computador.' : 'Modelos na nuvem cobram por uso.'}`,
  ctaPolish: 'Polir',
  ctaChapters: 'Criar capítulos',
  ctaSummary: 'Escrever resumo',
  ctaBlog: 'Escrever post de blog',
  ctaTitle: 'Sugerir títulos',
  ctaDesc: 'Escrever descrição',
  noTextModel: 'Conecte um modelo de texto primeiro',
  runSubmitting: 'Iniciando…',
  runQueued: 'Na fila',
  runRunning: (model) => `${model} está trabalhando`,
  runBatches: (done, total) => `Parte ${done} de ${total}`,
  runNote: 'Roda em segundo plano; você pode sair desta página e voltar depois.',
  cancel: 'Cancelar',
  cancelled: 'Cancelado',
  cancelFailed: (message) => `Não foi possível cancelar: ${message}`,
  submitFailed: 'Não foi possível iniciar',
  failed: 'Falhou',
  interrupted: 'Interrompido',
  needsDecision: 'Precisa da sua decisão em Tarefas',
  openTasks: 'Abrir Tarefas',
  retry: 'Tentar de novo',
  dismiss: 'Fechar',
  badResult: 'O Runtime devolveu um resultado que esta página não consegue ler.',
  resultFrom: (model) => `De ${model} · não gravado no vídeo`,
  resultCut: 'O modelo chegou ao limite de saída, então o final pode estar cortado.',
  resultSkipped: (skipped) => (skipped === 1 ? '1 anexo não foi enviado (imagens e arquivos binários são ignorados).' : `${skipped} anexos não foram enviados (imagens e arquivos binários são ignorados).`),
  copy: 'Copiar',
  copied: 'Copiado',
  copyFailed: 'Não foi possível copiar',
  done: 'Concluir',
  appliedPolish: (count) => (count === 1 ? 'Polido · 1 palavra alterada' : `Polido · ${count} palavras alteradas`),
  appliedChapters: (count) => (count === 1 ? '1 capítulo definido na linha do tempo' : `${count} capítulos definidos na linha do tempo`),
  appliedNothing: 'O modelo não sugeriu mudanças; nada foi gravado.',
  undo: 'Desfazer',
  undone: 'Desfeito',
  undoFailed: 'Não foi possível desfazer',
  stateResult: 'Resultado pronto',
  statePercent: (percent) => `${percent}%`,
  statePending: (count) => `${count} pendente${count === 1 ? '' : 's'}`,
  stateStale: (count) => `${count} desatualizada${count === 1 ? '' : 's'}`,
  stateLast: (when) => `Última · ${when}`,
};
