import type { AiToolsMessages } from './ai-tools-copy.ts';

export const fr: AiToolsMessages = {
  back: "Retour",

  who: "Choisir",
  whoAgent: "Confier à l’Agent",
  whoModel: "Appeler directement un modèle",
  whoModelSub: "Le Runtime n’a pas encore de flux pour cela ; seul l’Agent peut le faire",
  scope: "Portée",
  scopeAll: "Toute la vidéo",
  scopeChapter: (index: number, label: string) => `Le chapitre ${index} · ${label}`,
  scopeNoChapters: "La timeline n’a aucun chapitre ; seule la vidéo entière est disponible",
  byAgent: "Effectué par l’Agent",
  cta: "Confier à l’Agent",
  queued: "L’Agent est occupé · message en file, envoyé à la fin du tour",
  noConversation: "Cette vidéo n’appartient à aucun projet ni session ; elle ne peut pas être confiée à l’Agent.",
  createFailed: (message: string) => `Impossible de créer une session : ${message}`,

  prePolish: "Améliorer d’abord (paragraphes automatiques)",
  prePolishOn: "Chapitres regroupés par paragraphe",
  prePolishOff: "Une transcription non améliorée n’a qu’un paragraphe ; les chapitres seront peu détaillés",
  staleEdited: "Phrases modifiées dans l’original",
  staleEditedSub: "Vous avez modifié la transcription mais la traduction est encore l’ancienne",
  staleCut: "Phrases coupées dans l’original",
  staleCutSub: "Une coupe a supprimé une partie de phrase ; retraduisez depuis l’original coupé",
  staleNone: "Cochez au moins une option",
  staleOnly: (language: string) => `Seulement la traduction ${language}`,
  retranscribeModel: "L’Agent choisit un modèle vocal installé sur cet ordinateur ; indiquez votre choix dans les instructions ci-dessous si nécessaire.",

  retranscribeSpeakers: "Identifier les locuteurs après transcription",

  platform: "Où publier",
  platformPlaceholder: "Plateforme de publication (facultatif) ; suit ses règles et vous rappelle de vérifier",
  titleCount: "Candidats",
  titleCountNote: (min: number, max: number) => `${min}–${max}, chacun sous un angle différent`,
  coverCount: "Combien",
  coverIdea: "La seule chose à dire",
  coverIdeaPlaceholder: "Ce qui donnerait envie de cliquer (facultatif) ; laissez vide pour que l’Agent le trouve dans la transcription",
  coverRatio: "Rapport hauteur/largeur",
  coverRatioProject: "Comme le canevas vidéo",
  coverText: "Texte de couverture",

  soon: "Bientôt disponible",
  chaptersPolishFirst: "Améliorer et diviser en paragraphes avant de générer les chapitres",

  session: 'Session',
  promptLabel: 'Ce que vous dites à l’agent',
  promptPlaceholder: 'Quoi faire et comment ; @ pour citer un chapitre ou un intervenant',
  restoreDefault: 'Rétablir par défaut',
  skillNote: 'La méthode de cet outil',
  noSkill: 'Aucun skill : l’agent suit seulement le texte ci-dessus.',
  addSkillBack: 'Remettre le skill de cet outil',
  sentNew: 'Confié à l’agent · nouvelle session',
  sentCurrent: 'Confié à l’agent · suite de la session en cours',
  agentCardTitle: 'Pour tout ce qui n’est pas listé, une phrase à l’agent suffit',
  agentCardSomeAgent: 'l’agent',
  agentCardOutside: 'Ouvre la session de cette vidéo, avec la vidéo en contexte →',
  noTranscriptTitle: 'Cette vidéo n’a pas encore de transcription',
  noTranscriptBody: 'Tous ces outils partent de la transcription : polir, chapitrer, résumer et titrer demandent d’abord une transcription.',
  goTranscribe: 'Aller à la transcription',
  stateRunning: 'En cours',
  stateReview: 'À vérifier',
  agentCardNew: (agent) => `Ouvre une nouvelle session avec cette vidéo en contexte ; s’exécute dans ${agent} sur cet ordinateur et demande avant d’écrire →`,
  stateChapters: (count) => (count <= 1 ? `${count} chapitre` : `${count} chapitres`),
};
