import type { AiToolsMessages } from './ai-tools-copy.ts';

export const fr: AiToolsMessages = {
  back: "Retour",

  who: "Choisir",
  whoAgent: "Confier à l’Agent",
  whoModel: "Appeler directement un modèle",
  whoModelSub: "Le Runtime n’a pas encore de flux pour cela ; seul l’Agent peut le faire",
  scope: "Portée",
  scopeAll: "Toute la vidéo",
  scopeChapter: (index: number, label: string) => `Le chapitre ${index} · ${label}`,
  scopeNoChapters: "La timeline n’a aucun chapitre ; seule la vidéo entière est disponible",
  cta: "Confier à l’Agent",
  queued: "L’Agent est occupé · message en file, envoyé à la fin du tour",
  noConversation: "Cette vidéo n’appartient à aucun projet ni session ; elle ne peut pas être confiée à l’Agent.",
  createFailed: (message: string) => `Impossible de créer une session : ${message}`,

  prePolish: "Améliorer d’abord (paragraphes automatiques)",
  prePolishOn: "Chapitres regroupés par paragraphe",
  prePolishOff: "Une transcription non améliorée n’a qu’un paragraphe ; les chapitres seront peu détaillés",
  framesLabel: 'Ajouter des illustrations d’images clés',
  framesSub: 'Prend des images de la vidéo et les place là où une illustration aide ; désactivé par défaut',
  framesSubModel: 'Un appel direct au modèle ne peut pas récupérer d’images de la vidéo ; confiez-le à l’Agent pour les ajouter',
  staleEdited: "Phrases modifiées dans l’original",
  staleEditedSub: "Vous avez modifié la transcription mais la traduction est encore l’ancienne",
  staleCut: "Phrases coupées dans l’original",
  staleCutSub: "Une coupe a supprimé une partie de phrase ; retraduisez depuis l’original coupé",
  staleNone: "Cochez au moins une option",
  staleOnly: (language: string) => `Seulement la traduction ${language}`,
  retranscribeModel: "L’Agent choisit un modèle vocal installé sur cet ordinateur ; indiquez votre choix dans les instructions ci-dessous si nécessaire.",

  retranscribeSpeakers: "Identifier les locuteurs après transcription",

  platform: "Où publier",
  platformPlaceholder: "Plateforme de publication (facultatif) ; suit ses règles et vous rappelle de vérifier",
  titleCount: "Candidats",
  titleCountNote: (min: number, max: number) => `${min}–${max}, chacun sous un angle différent`,
  coverCount: "Combien",
  coverIdea: "La seule chose à dire",
  coverIdeaPlaceholder: "Ce qui donnerait envie de cliquer (facultatif) ; laissez vide pour que l’Agent le trouve dans la transcription",
  coverRatio: "Rapport hauteur/largeur",
  coverRatioProject: "Comme le canevas vidéo",
  coverText: "Texte de couverture",

  soon: "Bientôt disponible",
  chaptersPolishFirst: "Améliorer et diviser en paragraphes avant de générer les chapitres",

  session: 'Session',
  promptLabel: 'Ce que vous dites à l’agent',
  promptPlaceholder: 'Quoi faire et comment ; @ pour citer un chapitre ou un intervenant',
  restoreDefault: 'Rétablir par défaut',
  skillNote: 'La méthode de cet outil',
  noSkill: 'Aucun skill : l’agent suit seulement le texte ci-dessus.',
  addSkillBack: 'Remettre le skill de cet outil',
  sentNew: 'Confié à l’agent · nouvelle session',
  sentCurrent: 'Confié à l’agent · suite de la session en cours',
  agentChip: 'Agent en cours',
  agentHanded: (agent: string) => `Confié à ${agent} dans une session`,
  agentStarting: 'Ouverture de la session…',
  agentWorking: 'L’agent s’en occupe',
  agentWaiting: 'Votre approbation est requise dans la session',
  agentWaitingBody: 'Rien n’est écrit dans la vidéo avant votre approbation.',
  agentApprove: 'Approuver dans la session',
  agentDone: 'L’agent a terminé',
  agentDoneNote: 'Les résultats sont écrits dans la vidéo comme d’habitude ; la réponse de l’agent est dans la session.',
  agentStopped: 'Arrêté dans la session',
  agentFailed: 'L’agent n’a pas pu terminer',
  openSession: 'Ouvrir la session',
  resetSetup: 'Reconfigurer',
  agentNoteCleanup: 'Vous pouvez continuer à éditer · les coupes suggérées apparaissent barrées dans la transcription et la timeline une fois écrites.',
  agentNoteStale: 'Vous pouvez continuer à éditer · les traductions actualisées mettent les sous-titres à jour directement.',
  agentCardTitle: 'Pour tout ce qui n’est pas listé, une phrase à l’agent suffit',
  agentCardSomeAgent: 'l’agent',
  agentCardOutside: 'Ouvre la session de cette vidéo, avec la vidéo en contexte →',
  noTranscriptTitle: 'Cette vidéo n’a pas encore de transcription',
  noTranscriptBody: 'Tous ces outils partent de la transcription : polir, chapitrer, résumer et titrer demandent d’abord une transcription.',
  goTranscribe: 'Aller à la transcription',
  stateRunning: 'En cours',
  stateReview: 'À vérifier',
  agentCardNew: (agent) => `Ouvre une nouvelle session avec cette vidéo en contexte ; s’exécute dans ${agent} sur cet ordinateur et demande avant d’écrire →`,
  stateChapters: (count) => (count <= 1 ? `${count} chapitre` : `${count} chapitres`),

  whyRetranscribe: "Il faut un modèle vocal, et la transcription du Runtime ajoute une transcription complète au lieu de remplacer un passage ; seul l’Agent peut le faire",
  whyCleanup: "Trouver les coupes demande de peser chaque endroit dans son contexte ; seul l’Agent peut le faire",
  whyStale: "Le Runtime n’a pas encore de flux pour retraduire seulement les phrases périmées ; seul l’Agent peut le faire",
  whyCover: "Une couverture demande de générer et composer des images ; seul l’Agent peut le faire",
  modelPromptLabel: 'Prompt',
  modelPicker: 'Modèle de texte',
  modelNone: 'Aucun modèle de texte',
  modelNoStructured: 'Ce modèle ne prend pas en charge la sortie structurée, nécessaire à cet outil',
  modelPolishNote: 'En appelant un modèle directement, seules les coquilles et la ponctuation sont corrigées mot à mot ; pas de découpage en paragraphes. Pour cela, confiez-le à l’Agent.',
  modelGateBody: 'Cet outil envoie le prompt et la transcription à un modèle de texte.',
  skillsAsSystem: "Les skills joints sont envoyés au modèle comme prompt système : seulement SKILL.md et les fichiers references/ qu’il utilise, rien d’autre.",
  contextNone: 'Envoyé au modèle : seulement le prompt ci-dessus',
  contextLine: (items) => `Envoyé au modèle : prompt + ${items}`,
  contextTranscript: (count, scope) => `transcription${scope ? ` · ${scope}` : ''} ${count <= 1 ? `${count} paragraphe` : `${count} paragraphes`}`,
  contextChapters: (count) => `chapitres ${count}`,
  contextAttachments: (count) => `pièces jointes ${count}`,
  contextSkills: (names) => `Skill ${names}`,
  contextImages: (count) => ` ; les images ne sont pas envoyées au modèle, ${count <= 1 ? `${count} image sera ignorée` : `${count} images seront ignorées`}`,
  modelHint: (model, applies, local) =>
    `${model ? `Appelle ${model} directement` : 'Appelle un modèle directement'}, sans conversation ; ${applies ? 'appliqué à la fin, annulable en une étape' : 'le résultat est à lire et copier, rien n’est écrit dans la vidéo'}. ${local ? 'Modèle local, reste sur cet ordinateur.' : 'Les modèles cloud sont facturés à l’usage.'}`,
  ctaPolish: 'Peaufiner',
  ctaChapters: 'Créer les chapitres',
  ctaSummary: 'Écrire le résumé',
  ctaBlog: 'Écrire l’article',
  ctaTitle: 'Proposer des titres',
  ctaDesc: 'Écrire la description',
  noTextModel: 'Connectez d’abord un modèle de texte',
  runSubmitting: 'Démarrage…',
  runQueued: 'En file d’attente',
  runRunning: (model) => `${model} travaille`,
  runBatches: (done, total) => `Partie ${done} sur ${total}`,
  runNote: 'Ça tourne en arrière-plan ; vous pouvez quitter cette page et revenir.',
  cancel: 'Annuler',
  cancelled: 'Annulé',
  cancelFailed: (message) => `Impossible d’annuler : ${message}`,
  submitFailed: 'Impossible de démarrer',
  failed: 'Échec',
  interrupted: 'Interrompu',
  needsDecision: 'Une décision vous attend dans Tâches',
  openTasks: 'Ouvrir Tâches',
  retry: 'Réessayer',
  dismiss: 'Fermer',
  badResult: 'Le Runtime a renvoyé un résultat que cette page ne sait pas lire.',
  resultFrom: (model) => `De ${model} · non écrit dans la vidéo`,
  resultCut: 'Le modèle a atteint sa limite de sortie ; la fin peut être coupée.',
  resultSkipped: (skipped) => (skipped <= 1 ? `${skipped} pièce jointe non envoyée (images et fichiers binaires ignorés).` : `${skipped} pièces jointes non envoyées (images et fichiers binaires ignorés).`),
  copy: 'Copier',
  copied: 'Copié',
  copyFailed: 'Impossible de copier',
  done: 'Terminé',
  appliedPolish: (count) => (count <= 1 ? `Peaufiné · ${count} mot modifié` : `Peaufiné · ${count} mots modifiés`),
  appliedChapters: (count) => (count <= 1 ? `${count} chapitre placé sur la timeline` : `${count} chapitres placés sur la timeline`),
  appliedNothing: 'Le modèle n’a proposé aucun changement ; rien n’a été écrit.',
  undo: 'Annuler',
  undone: 'Annulé',
  undoFailed: 'Impossible d’annuler',
  stateResult: 'Résultat prêt',
  statePercent: (percent) => `${percent} %`,
  statePending: (count) => `${count} en attente`,
  stateStale: (count) => (count <= 1 ? `${count} obsolète` : `${count} obsolètes`),
  stateLast: (when) => `Dernière · ${when}`,
};
