import type { AiToolsMessages } from './ai-tools-copy.ts';

export const pl: AiToolsMessages = {
  back: "Wstecz",

  who: "Wybierz",
  whoAgent: "Przekaż agentowi",
  whoAgentSub: "Działa w sesji tego wideo",
  whoModel: "Wywołaj model bezpośrednio",
  whoModelSub: "Runtime nie ma jeszcze procesu dla tego, więc może wykonać tylko agent",
  scope: "Zakres",
  scopeAll: "Całe wideo",
  scopeChapter: (index: number, label: string) => `Rozdział ${index} · ${label}`,
  scopeNoChapters: "Oś czasu nie ma jeszcze rozdziałów, dostępne tylko całe wideo",
  byAgent: "Wykonuje agent",
  preview: "Co zostanie wysłane agentowi",
  cta: "Przekaż agentowi",
  ctaHint: "Wysyła powyższą wiadomość do sesji wideo, agent zaczyna od razu. W razie potrzeby najpierw dostosuj wiadomość.",
  ctaNoVideo: "Wideo nie jest jeszcze otwarte, nie ma czego przekazać.",
  sent: "Przekazano agentowi · działa w sesji",
  queued: "Agent zajęty · wiadomość w kolejce, zostanie wysłana po turze",
  sendFailed: (message: string) => `Nie udało się wysłać: ${message}`,
  noConversation: "Wideo jest poza projektem lub sesją, nie można przekazać agentowi.",
  createFailed: (message: string) => `Nie udało się utworzyć sesji: ${message}`,

  prePolish: "Najpierw popraw (automatyczne akapity)",
  prePolishOn: "Rozdziały są grupowane według akapitów",
  prePolishOff: "Niepoprawiona transkrypcja ma tylko 1 akapit, więc rozdziały będą ogólne",
  noteTitle: "Własne instrukcje (opcjonalnie)",
  notePlaceholder: "Dodatkowe wymagania: swobodny ton lub zachowanie nazw marek…",
  staleEdited: "Zdania zmienione w oryginale",
  staleEditedSub: "Zmieniono słowa transkrypcji, ale tłumaczenie nadal stare",
  staleCut: "Zdania wycięte z oryginału",
  staleCutSub: "Cięcie usunęło część zdania; przetłumacz ponownie zmieniony oryginał",
  staleNone: "Zaznacz co najmniej jedno",
  staleOnly: (language: string) => `Tylko ${language} – tłumaczenie`,
  retranscribeModel: "Agent wybiera model mowy spośród zainstalowanych; aby wybrać, podaj w instrukcjach poniżej.",

  retranscribeSpeakers: "Rozpoznaj mówców po transkrypcji",

  length: "Długość",
  style: "Styl",
  styleCustom: "Opisz własnymi słowami, jak napisać",
  view: "Punkt widzenia",
  viewAuto: "Automatyczny: agent decyduje na podstawie źródła wideo",
  language: "Język",
  languageWrite: "Tak jak interfejs",
  languagePublish: "Jak w transkrypcji",
  platform: "Gdzie publikować",
  platformPlaceholder: "Platforma publikacji (opcjonalnie); przestrzega jej zasad i przypomina o sprawdzeniu",
  titleCount: "Propozycje",
  titleCountNote: (min: number, max: number) => `${min}–${max}, każda z innego punktu widzenia`,
  coverCount: "Ile",
  coverIdea: "Jedna rzecz do przekazania",
  coverIdeaPlaceholder: "Co zachęci do kliknięcia wideo (opcjonalnie); pozostaw puste, agent znajdzie w transkrypcji",
  coverRatio: "Proporcje",
  coverRatioProject: "Tak jak płótno wideo",
  coverText: "Tekst na okładce",
  writeNote: "Coś jeszcze (opcjonalnie)",
  writeNotePlaceholder: "Na przykład zacznij od wniosku lub wspomnij imię gościa",
  titleNote: "Jedno wymaganie (opcjonalnie)",
  titleNotePlaceholder: "Na przykład bez pytań lub z imieniem gościa",
  coverNotePlaceholder: "Na przykład bez czerwieni lub osoba po prawej",

  soon: "Wkrótce",
  chaptersPolishFirst: "Najpierw popraw i podziel na akapity, potem generuj rozdziały",
};
