import type { AiToolsMessages } from './ai-tools-copy.ts';

export const ko: AiToolsMessages = {
  back: '뒤로',

  // 设置态
  who: '사용',
  whoAgent: 'Agent에게 맡기기',
  whoAgentSub: '이 영상의 세션에서 실행합니다',
  whoModel: '모델 직접 호출',
  whoModelSub: 'Runtime에 아직 이 작업의 워크플로가 없어 Agent만 할 수 있습니다',
  scope: '범위',
  scopeAll: '영상 전체',
  scopeChapter: (index: number, label: string) => `챕터 ${index} · ${label}`,
  scopeNoChapters: '타임라인에 아직 챕터가 없어 영상 전체만 선택할 수 있습니다',
  byAgent: 'Agent가 처리',
  preview: 'Agent에게 보낼 메시지',
  cta: 'Agent에게 맡기기',
  ctaHint: '위 메시지를 이 영상의 세션으로 보내면 Agent가 바로 시작합니다. 필요하면 먼저 위에서 조정하세요.',
  ctaNoVideo: '영상이 아직 열려 있지 않아 맡길 수 없습니다.',
  sent: 'Agent에게 맡김 · 세션에서 실행 중',
  queued: 'Agent가 작업 중 · 메시지가 대기열에 있으며 이번 턴이 끝나면 보냅니다',
  sendFailed: (message: string) => `보내지 못했습니다: ${message}`,
  noConversation: '이 영상은 어떤 프로젝트나 세션에도 속하지 않아 Agent에게 맡길 수 없습니다.',
  createFailed: (message: string) => `세션을 만들지 못했습니다: ${message}`,

  // 勾选项与自定义
  prePolish: '먼저 다듬기(자동 문단 나누기)',
  prePolishOn: '챕터를 문단 단위로 묶습니다',
  prePolishOff: '다듬지 않은 전사본은 문단이 1개뿐이라 챕터가 거칠게 나뉩니다',
  noteTitle: '사용자 지정 지시(선택 사항)',
  notePlaceholder: '추가 요구 사항(예: 구어체 유지, 브랜드 이름 변경 금지)…',
  staleEdited: '원문이 수정된 문장',
  staleEditedSub: '전사본에서 단어를 바꿨지만 번역은 아직 이전 그대로입니다',
  staleCut: '원문에서 잘린 문장',
  staleCutSub: '컷이 문장 일부를 제거했습니다. 잘린 원문을 기준으로 다시 번역합니다',
  staleNone: '하나 이상 선택하세요',
  staleOnly: (language: string) => `${language} 번역만`,
  retranscribeModel: '음성 모델은 Agent가 이 컴퓨터에 설치된 모델 중에서 고릅니다. 직접 정하려면 아래 지시에 적으세요.',
  retranscribeSpeakers: '전사 후 화자 식별',

  // 写作与发布
  length: '길이',
  style: '스타일',
  styleCustom: '어떻게 쓸지 직접 설명하세요',
  view: '시점',
  viewAuto: '자동: Agent가 영상 출처를 보고 정합니다',
  language: '언어',
  languageWrite: '인터페이스와 같게',
  languagePublish: '전사본과 같게',
  platform: '게시할 곳',
  platformPlaceholder: '게시할 플랫폼(선택 사항). 그 플랫폼의 규칙에 맞춰 쓰고 확인하도록 알려 드립니다',
  titleCount: '후보 수',
  titleCountNote: (min: number, max: number) => `${min}–${max}개, 각각 다른 관점`,
  coverCount: '개수',
  coverIdea: '전하고 싶은 한 가지',
  coverIdeaPlaceholder: '사람들이 이 영상을 클릭하게 만들 한 가지(선택 사항). 비워 두면 Agent가 전사본에서 찾습니다',
  coverRatio: '화면 비율',
  coverRatioProject: '영상 캔버스와 같게',
  coverText: '표지 텍스트',
  writeNote: '그 밖의 요구 사항(선택 사항)',
  writeNotePlaceholder: '예: 결론부터 말하기, 게스트 이름 언급하기',
  titleNote: '요구 사항 한 가지(선택 사항)',
  titleNotePlaceholder: '예: 의문문 쓰지 않기, 게스트 이름 넣기',
  coverNotePlaceholder: '예: 빨간색 쓰지 않기, 인물을 오른쪽에 두기',

  // 还做不了的
  soon: '곧 제공',
  chaptersPolishFirst: '먼저 다듬고 문단을 나눈 뒤 챕터를 생성하세요',
};
