import type { AiToolsMessages } from './ai-tools-copy.ts';

export const ptBR: AiToolsMessages = {
  back: "Voltar",

  who: "Usar",
  whoAgent: "Passar para o agente",
  whoModel: "Chamar o modelo",
  whoModelSub: "O Runtime ainda não tem este fluxo; só o agente pode fazer",
  scope: "Escopo",
  scopeAll: "Vídeo inteiro",
  scopeChapter: (index: number, label: string) => `Capítulo ${index} · ${label}`,
  scopeNoChapters: "Sem capítulos na linha do tempo; apenas o vídeo inteiro está disponível",
  cta: "Passar para o agente",
  queued: "O agente está ocupado · mensagem na fila, enviada ao fim deste turno",
  noConversation: "O vídeo não pertence a projeto ou sessão e não pode ser entregue ao agente.",
  createFailed: (message: string) => `Não foi possível criar sessão: ${message}`,

  prePolish: "Revisar primeiro (parágrafos automáticos)",
  prePolishOn: "Capítulos agrupados por parágrafo",
  prePolishOff: "Uma transcrição não revisada só tem 1 parágrafo; os capítulos serão pouco detalhados",
  staleEdited: "Frases editadas no original",
  staleEditedSub: "Você mudou palavras na transcrição; a tradução ainda é a antiga",
  staleCut: "Frases cortadas do original",
  staleCutSub: "O corte tirou parte da frase; retraduzir pelo original cortado",
  staleNone: "Marque ao menos uma opção",
  staleOnly: (language: string) => `Apenas a tradução ${language} tradução`,
  retranscribeModel: "O agente escolhe um modelo de fala instalado neste computador; indique sua escolha nas instruções abaixo.",

  retranscribeSpeakers: "Identificar falantes após transcrever",

  platform: "Publicar em",
  platformPlaceholder: "Onde vai ser publicado (opcional); escrito pelas regras de lá, com lembrete para conferir",
  titleCount: "Opções",
  titleCountNote: (min: number, max: number) => `${min}–${max}, cada um por um ângulo diferente`,
  coverCount: "Quantas",
  coverIdea: "A única coisa a dizer",
  coverIdeaPlaceholder: "O que faria as pessoas clicarem; opcional — deixe vazio para o agente achar na transcrição",
  coverRatio: "Proporção",
  coverRatioProject: "Igual ao canvas do vídeo",
  coverText: "Texto da capa",

  soon: "Em breve",
  chaptersPolishFirst: "Revisar e dividir em parágrafos, depois gerar capítulos",

  session: 'Sessão',
  promptLabel: 'O que dizer ao agente',
  promptPlaceholder: 'O que fazer e como; use @ para citar capítulos ou falantes',
  restoreDefault: 'Restaurar padrão',
  skillNote: 'Como esta ferramenta trabalha',
  noSkill: 'Sem skill: o agente segue só o texto acima.',
  addSkillBack: 'Adicionar de volta o skill desta ferramenta',
  sentNew: 'Enviado ao agente · nova sessão',
  sentCurrent: 'Enviado ao agente · continua na sessão atual',
  agentCardTitle: 'Para o que não está abaixo, diga ao agente numa frase',
  agentCardSomeAgent: 'o agente',
  agentCardOutside: 'Abre a sessão deste vídeo, com o vídeo como contexto →',
  noTranscriptTitle: 'Este vídeo ainda não tem transcrição',
  noTranscriptBody: 'Todas estas ferramentas partem da transcrição: polir, capítulos, resumos e títulos precisam de uma transcrição antes.',
  goTranscribe: 'Ir para a transcrição',
  stateRunning: 'Em andamento',
  stateReview: 'A rever',
  agentCardNew: (agent) => `Abre uma nova sessão com este vídeo como contexto; roda no ${agent} deste computador e pergunta antes de gravar →`,
  stateChapters: (count) => (count === 1 ? '1 capítulo' : `${count} capítulos`),
};
