import type { BrandMessages } from './brand-copy.ts';

export const ko: BrandMessages = {
  importFilter: '브랜드 키트에 넣을 수 있는 파일',
  videoNotReady: '영상이 아직 준비되지 않아 지금은 변경할 수 없습니다',
  noStylableCaptions: '이 영상에는 스타일을 바꿀 수 있는 자막이 없습니다',
  importTitle: '브랜드 키트로 가져오기',
  import: '가져오기',
  brand: '브랜드',
  imported: (section: string, name: string) => `브랜드 키트 › ${section}(으)로 가져왔습니다: ${name}`,
  notBrandGlossary: (file: string) => `${file}은(는) 브랜드 소재가 아니어서 용어집에 저장했습니다`,
  notBrandVoice: (file: string) => `${file}은(는) 브랜드 소재가 아니어서 목소리에 저장했습니다`,
  importFailed: (file: string, message: string) => `${file}을(를) 가져오지 못했습니다: ${message}`,
  addSection: (section: string) => `${section} 추가`,
  add: '추가',
  addFailed: (file: string, message: string) => `${file}을(를) 추가하지 못했습니다: ${message}`,
  addedCount: (section: string, count: number) => `브랜드 키트 › ${section}에 추가했습니다 · ${count}개`,
  untitled: '제목 없음',
  addedOne: (section: string, name: string) => `브랜드 키트 › ${section}에 추가했습니다: ${name}`,
  actionSaveToBrand: '브랜드 키트에 저장',
  saveProblem: (problem: string) => `브랜드 키트에 저장하지 못했습니다: ${problem}`,
  captionStyle: '자막 스타일',
  captionStyleName: (video: string) => `${video} · 자막 스타일`,
  savedStyle: (name: string) => `브랜드 키트 › 자막 스타일에 저장했습니다: ${name}`,
  actionSaveStyle: '자막 스타일 저장',
  addedColor: (name: string) => `브랜드 색상에 추가했습니다: ${name}`,
  actionAddColor: '브랜드 색상 추가',
  actionRename: '이름 변경',
  removed: (name: string) => `브랜드 키트에서 “${name}” 항목을 삭제했습니다`,
  actionDelete: '삭제',
  copied: (value: string) => `${value} 값을 복사했습니다`,
  copyFailed: (message: string) => `복사하지 못했습니다: ${message}`,
  noFilePicker: '여기서는 파일을 고를 수 없습니다. 컴퓨터의 파일 추가와 가져오기는 데스크톱 앱에서 하세요.',
  loadingLibrary: '브랜드 키트 불러오는 중',
  loadingLibraryEllipsis: '브랜드 키트 불러오는 중…',
  new: '새로 만들기',
  entryCount: (count: number) => `${count}개`,
  styleStillDefault: '자막이 아직 기본 스타일을 사용합니다: 인스펙터에서 자막 스타일을 한 번 바꾼 뒤 돌아와 저장하세요.',
  noCaptionsToSave: '이 영상에는 아직 자막이 없어 저장할 현재 스타일이 없습니다.',
  rename: '이름 변경',
  name: '이름',
  save: '저장',
  deleteTitle: (name: string) => `브랜드 키트에서 “${name}” 항목을 삭제할까요?`,
  delete: '삭제',
  cancel: '취소',
  deleteBody: '삭제하면 다른 영상에서 더 이상 사용할 수 없습니다. 이미 영상에 배치된 사본은 영향을 받지 않습니다.',
  localFiles: '이 컴퓨터의 파일',
  localFilesEllipsis: '이 컴퓨터의 파일…',
  noFilePickerShort: '여기서는 파일을 고를 수 없습니다',
  videoAssets: '이 영상의 소재',
  none: '없음',
  noAssetsOfKind: '이 영상에는 이 종류의 소재가 없습니다',
  saveCurrentStyle: '현재 스타일 저장',
  whichStyle: '저장할 자막 스타일',
  styleUses: (count: number) => `자막 ${count}개에서 사용 중`,
  applyToCaptions: '이 영상의 자막에 적용',
  placeOnCanvas: '캔버스에 배치(재생 헤드 위치)',
  placeOnTimeline: '타임라인에 배치(재생 헤드 위치)',
  copyToAssets: '이 영상의 소재로 복사',
  unreadable: (error: string) => `읽을 수 없습니다: ${error}`,
  loading: '불러오는 중…',
  actionsFor: (name: string) => `“${name}” 작업`,
  copyValue: '색상 값 복사',
  renameEllipsis: '이름 변경…',
  deleteFromLibrary: '브랜드 키트에서 삭제',
  deleteFromLibraryEllipsis: '브랜드 키트에서 삭제…',
  actionPlace: (name: string) => `“${name}” 항목을 영상에 배치`,
  appliedToCaptions: (name: string, count: number) => `“${name}” 스타일을 자막 ${count}개에 적용했습니다`,
  copiedNoCaptions: (name: string) => `“${name}” 스타일을 이 영상에 복사했습니다. 아직 이 스타일을 쓰는 자막은 없습니다`,
  copiedToAssets: (name: string) => `이 영상의 소재로 복사했습니다: ${name}`,
  copiedNotPlaced: (name: string) => `소재로 복사했지만 아직 타임라인에 배치하지 않았습니다: ${name}`,
  elementsTrack: '요소',
  copiedNotPlaceable: (name: string) => `소재로 복사했습니다. 이 종류의 파일은 타임라인에 바로 놓을 수 없습니다: ${name}`,
  addLabel: (name: string) => `${name} 추가`,
  placedAtPlayhead: (name: string) => `타임라인의 재생 헤드 위치에 배치했습니다: ${name}`,
  newBrandColor: '새 브랜드 색상',
  namePlaceholder: '예: 기본 색상',
  color: '색상',
  colorValue: '값',
  colorValueError: '#RRGGBB 형식으로, 불투명도가 있으면 #RRGGBBAA로 입력하세요',
  savedToColors: (value: string) => `브랜드 색상에 저장했습니다: ${value}`,
  actionSaveToColors: '브랜드 색상에 저장',
  brandColors: '브랜드 색상',
  inBrandColors: '이미 브랜드 색상에 있음',
  saveToColors: '브랜드 색상에 저장',
  commonColors: '자주 쓰는 색상',
};
