import type { BrandMessages } from './brand-copy.ts';

export const de: BrandMessages = {
  importFilter: "Dateien, die das Marken-Kit akzeptiert",
  videoNotReady: "Das Video ist noch nicht bereit und kann derzeit nicht geändert werden",
  noStylableCaptions: "Dieses Video hat keine Untertitel mit änderbarem Stil",
  importTitle: "Ins Marken-Kit importieren",
  import: "Importieren",
  brand: "Marke",
  imported: (section: string, name: string) => `Importiert ins Marken-Kit › ${section}: ${name}`,
  notBrandGlossary: (file: string) => `${file} ist kein Markenmaterial; im Glossar gespeichert`,
  notBrandVoice: (file: string) => `${file} ist kein Markenmaterial; unter Stimmen gespeichert`,
  importFailed: (file: string, message: string) => `Importieren fehlgeschlagen: ${file}: ${message}`,
  addSection: (section: string) => `Hinzufügen: ${section}`,
  add: "Hinzufügen",
  addFailed: (file: string, message: string) => `Hinzufügen fehlgeschlagen: ${file}: ${message}`,
  addedCount: (section: string, count: number) => `Zum Marken-Kit hinzugefügt › ${section} · ${count}`,
  untitled: "Unbenannt",
  addedOne: (section: string, name: string) => `Zum Marken-Kit hinzugefügt › ${section}: ${name}`,
  actionSaveToBrand: "im Marken-Kit speichern",
  saveProblem: (problem: string) => `Speichern im Marken-Kit fehlgeschlagen: ${problem}`,
  captionStyle: "Untertitelstil",
  captionStyleName: (video: string) => `${video} · Untertitelstil`,
  savedStyle: (name: string) => `Gespeichert im Marken-Kit › Untertitelstile: ${name}`,
  actionSaveStyle: "Untertitelstil speichern",
  addedColor: (name: string) => `Zu Markenfarben hinzugefügt: ${name}`,
  actionAddColor: "Markenfarbe hinzufügen",
  actionRename: "umbenennen",
  removed: (name: string) => `Gelöscht: „${name}“ aus dem Marken-Kit`,
  actionDelete: "löschen",
  copied: (value: string) => `Kopiert: ${value}`,
  copyFailed: (message: string) => `Kopieren fehlgeschlagen: ${message}`,
  noFilePicker: "Hier können keine Dateien ausgewählt werden; in der Desktop-App vom Computer hinzufügen und importieren.",
  loadingLibrary: "Marken-Kit wird geladen",
  loadingLibraryEllipsis: "Marken-Kit wird geladen…",
  new: "Neu",
  entryCount: (count: number) => `${count}`,
  styleStillDefault: "Untertitel verwenden noch den Standardstil: einmal im Inspektor ändern, dann zum Speichern zurückkehren.",
  noCaptionsToSave: "Dieses Video hat noch keine Untertitel; kein aktueller Stil zum Speichern.",
  rename: "Umbenennen",
  name: "Name",
  save: "Speichern",
  deleteTitle: (name: string) => `Löschen: „${name}“ aus dem Marken-Kit?`,
  delete: "Löschen",
  cancel: "Abbrechen",
  deleteBody: "Nach dem Löschen können andere Videos diesen Eintrag nicht mehr verwenden. Bereits in Videos platzierte Kopien bleiben unverändert.",
  localFiles: "Dateien auf diesem Computer",
  localFilesEllipsis: "Dateien auf diesem Computer…",
  noFilePickerShort: "Hier können keine Dateien ausgewählt werden",
  videoAssets: "Materialien in diesem Video",
  none: "Keine",
  noAssetsOfKind: "Dieses Video hat keine Materialien dieser Art",
  saveCurrentStyle: "Aktuellen Stil speichern",
  whichStyle: "Zu speichernder Untertitelstil",
  styleUses: (count: number) => `Verwendet von ${count} Untertitel`,
  applyToCaptions: "Auf Untertitel dieses Videos anwenden",
  placeOnCanvas: "Auf Arbeitsfläche platzieren (am Abspielkopf)",
  placeOnTimeline: "In Zeitleiste platzieren (am Abspielkopf)",
  copyToAssets: "In Materialien dieses Videos kopieren",
  unreadable: (error: string) => `Lesen fehlgeschlagen: ${error}`,
  loading: "Wird geladen…",
  actionsFor: (name: string) => `Aktionen für „${name}“`,
  copyValue: "Farbwert kopieren",
  renameEllipsis: "Umbenennen…",
  deleteFromLibrary: "Aus Marken-Kit löschen",
  deleteFromLibraryEllipsis: "Aus Marken-Kit löschen…",
  actionPlace: (name: string) => `im Video platzieren: „${name}“`,
  appliedToCaptions: (name: string, count: number) => `Angewendet: „${name}“ auf ${count} Untertitel`,
  copiedNoCaptions: (name: string) => `Kopiert: „${name}“ in dieses Video; noch keine Untertitel verwenden es`,
  copiedToAssets: (name: string) => `In Materialien dieses Videos kopiert: ${name}`,
  copiedNotPlaced: (name: string) => `In Materialien kopiert, noch nicht in der Zeitleiste platziert: ${name}`,
  elementsTrack: "Elemente",
  copiedNotPlaceable: (name: string) => `In Materialien kopiert; dieser Dateityp kann nicht direkt in die Zeitleiste: ${name}`,
  addLabel: (name: string) => `Hinzufügen: ${name}`,
  placedAtPlayhead: (name: string) => `Am Abspielkopf in die Zeitleiste eingefügt: ${name}`,
  newBrandColor: "Neue Markenfarbe",
  namePlaceholder: "z. B. Primär",
  color: "Farbe",
  colorValue: "Wert",
  colorValueError: "#RRGGBB verwenden oder #RRGGBBAA mit Deckkraft",
  savedToColors: (value: string) => `In Markenfarben gespeichert: ${value}`,
  actionSaveToColors: "in Markenfarben speichern",
  brandColors: "Markenfarben",
  inBrandColors: "Bereits in Markenfarben",
  saveToColors: "Zu Markenfarben speichern",
  commonColors: "Häufige Farben",
};
