import type { BrandMessages } from './brand-copy.ts';

export const ptBR: BrandMessages = {
  importFilter: "Arquivos aceitos pelo Kit de marca",
  videoNotReady: "O vídeo ainda não está pronto para alterações",
  noStylableCaptions: "O vídeo não tem legendas com estilo alterável",
  importTitle: "Importar para o Kit de marca",
  import: "Importar",
  brand: "Marca",
  imported: (section: string, name: string) => `Importado para Kit de marca › ${section}: ${name}`,
  notBrandGlossary: (file: string) => `${file} não é mídia de marca; salvo em Glossário`,
  notBrandVoice: (file: string) => `${file} não é mídia de marca; salvo em Vozes`,
  importFailed: (file: string, message: string) => `Não foi possível importar ${file}: ${message}`,
  addSection: (section: string) => `Adicionar ${section}`,
  add: "Adicionar",
  addFailed: (file: string, message: string) => `Não foi possível adicionar ${file}: ${message}`,
  addedCount: (section: string, count: number) => `Adicionado ao Kit de marca › ${section} · ${count}`,
  untitled: "Sem título",
  addedOne: (section: string, name: string) => `Adicionado ao Kit de marca › ${section}: ${name}`,
  actionSaveToBrand: "salvar no Kit de marca",
  saveProblem: (problem: string) => `Não foi possível salvar no Kit de marca: ${problem}`,
  captionStyle: "Estilo de legendas",
  captionStyleName: (video: string) => `${video} · Estilo de legendas`,
  savedStyle: (name: string) => `Salvo em Kit de marca › Estilos de legendas: ${name}`,
  actionSaveStyle: "salvar o estilo de legendas",
  addedColor: (name: string) => `Adicionado às cores de marca: ${name}`,
  actionAddColor: "Adicionar cor da marca",
  actionRename: "Renomear",
  removed: (name: string) => `Excluído “${name}” do Kit de marca`,
  actionDelete: "Excluir",
  copied: (value: string) => `Copiado ${value}`,
  copyFailed: (message: string) => `Não foi possível copiar: ${message}`,
  noFilePicker: "Não é possível escolher arquivos aqui; adicione e importe pelo aplicativo desktop.",
  loadingLibrary: "Carregando Kit de marca",
  loadingLibraryEllipsis: "Carregando o kit de marca…",
  new: "Novo",
  entryCount: (count: number) => `${count}`,
  styleStillDefault: "As legendas ainda usam o estilo padrão: mude uma vez no Inspetor e volte para salvar.",
  noCaptionsToSave: "Este vídeo ainda não tem legendas; não há estilo atual para salvar.",
  rename: "Renomear",
  name: "Nome",
  save: "Salvar",
  deleteTitle: (name: string) => `Excluir “${name}” do Kit de marca?`,
  delete: "Excluir",
  cancel: "Cancelar",
  deleteBody: "Outros vídeos não poderão usar após excluir. Cópias já colocadas nos vídeos não mudam.",
  localFiles: "Arquivo local",
  localFilesEllipsis: "Arquivos deste computador…",
  noFilePickerShort: "Não é possível escolher arquivos aqui",
  videoAssets: "Mídias deste vídeo",
  none: "Nenhum",
  noAssetsOfKind: "Este vídeo não tem mídias deste tipo",
  saveCurrentStyle: "Salvar estilo atual",
  whichStyle: "Estilo de legendas para salvar",
  styleUses: (count: number) => `Usado por ${count} legendas`,
  applyToCaptions: "Aplicar às legendas deste vídeo",
  placeOnCanvas: "Colocar no canvas (no indicador de reprodução)",
  placeOnTimeline: "Colocar na linha do tempo (no indicador de reprodução)",
  copyToAssets: "Copiar para as mídias deste vídeo",
  unreadable: (error: string) => `Não foi possível ler: ${error}`,
  loading: "Lendo…",
  actionsFor: (name: string) => `Ações de “${name}”`,
  copyValue: "Copiar valor da cor",
  renameEllipsis: "Renomear…",
  deleteFromLibrary: "Excluir do Kit de marca",
  deleteFromLibraryEllipsis: "Excluir do Kit de marca…",
  actionPlace: (name: string) => `colocar “${name}” no vídeo`,
  appliedToCaptions: (name: string, count: number) => `Aplicado “${name}” a ${count} legendas`,
  copiedNoCaptions: (name: string) => `Copiado “${name}” para este vídeo; nenhuma legenda usa ainda`,
  copiedToAssets: (name: string) => `Copiado para as mídias do vídeo: ${name}`,
  copiedNotPlaced: (name: string) => `Copiado para mídias, mas ainda fora da linha do tempo: ${name}`,
  elementsTrack: "Elementos",
  copiedNotPlaceable: (name: string) => `Copiado para mídias; este tipo não vai direto à linha do tempo: ${name}`,
  addLabel: (name: string) => `Adicionar ${name}`,
  placedAtPlayhead: (name: string) => `Colocado na linha do tempo no indicador de reprodução: ${name}`,
  newBrandColor: "Nova cor da marca",
  namePlaceholder: "Ex.: principal",
  color: "Cor",
  colorValue: "Valor",
  colorValueError: "Use #RRGGBB, ou #RRGGBBAA com opacidade",
  savedToColors: (value: string) => `Salvo nas cores de marca: ${value}`,
  actionSaveToColors: "Salvar nas cores da marca",
  brandColors: "Cores da marca",
  inBrandColors: "Já está nas cores de marca",
  saveToColors: "Salvar nas cores da marca",
  commonColors: "Cores comuns",
};
