import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const zhHans: CaptionPanelMessages = {
  modes: { none: "无", color: "变色", box: "底块", scale: "放大", lift: "上抬", underline: "下划线", sweep: "扫色" },
  badgeSequence: "动态排版",
  badgeTip: (mode: string) => `当前词：${mode}`,
  modified: "已修改",
  revert: "还原",
  revertLabel: (name: string) => `还原成「${name}」`,
  galleryHint: "套一张卡也会换掉当前词与动效；位置、字号与显示时机不动。",
  active: "当前词",
  activeAria: "当前词的样子",
  color: "颜色",
  boxColor: "底块颜色",
  tintColor: "染色颜色",
  scale: "放大",
  times: "倍",
  transition: "过渡",
  spoken: "念过的词",
  spokenModes: { keep: "不变", tint: "染色", dim: "变淡" },
  unspoken: "没念到的词",
  unspokenModes: { keep: "不变", dim: "变淡", hidden: "不画" },
  sweepUnit: "扫色",
  sweepUnits: { grapheme: "按字", word: "按词" },
  guide: "引导点",
  guideNote: "在扫到的位置上方画一个点",
  nextLine: "预告下一句",
  nextLineNote: "在下面小一号显示下一句",
  noWordTiming: "译文没有逐词时间，这一行的当前词保持不变。",
  motion: "动效",
  stages: { in: "入场", out: "退场", loop: "循环" },
  stageAria: (stage: string) => `${stage}动效`,
  noMotion: "无",
  presets: {
    typewriter: "打字机",
    'fade-up': "淡入上移",
    rise: "升起",
    cascade: "逐词落下",
    pop: "弹出",
    'blur-in': "柔焦",
    'slide-mask': "滑入",
    'wave-in': "波浪入场",
    'drop-in': "落入",
    'float-in-top': "上方浮入",
    'float-in-bottom': "下方浮入",
    'scale-in': "放大入场",
    impact: "冲击",
    flip: "翻页",
    stomp: "跺脚",
    stack: "堆叠",
    'fade-down': "淡出下移",
    sink: "下沉",
    'pop-out': "弹出消失",
    'blur-out': "柔焦消失",
    'typewriter-erase': "逐字擦除",
    pulse: "脉动",
    wave: "波浪",
    shimmer: "闪烁",
    swing: "摇摆",
  },
  unit: "单位",
  units: { cue: "整条", line: "逐行", word: "逐词", grapheme: "逐字" },
  trigger: "触发",
  triggers: { enter: "出现时", spoken: "念到时" },
  duration: "时长",
  intensity: "强弱",
  catalogNote: "这一格跟着念到的词逐词画，触发、单位与时长随它自己。",
  emptyStage: { in: "整句直接出现。", out: "这一句结束时直接消失。", loop: "字幕在画面上时保持静止。" },
  sequencePreset: "预设",
  sequencePresets: { standard: "标准", light: "轻动感" },
  energy: "动感",
  palette: "配色",
  palettes: { classic: "经典", neon: "荧光", paper: "暖纸", ice: "冰蓝", custom: "自定义" },
  primary: "文字",
  accent: "强调",
  secondary: "辅色",
  backgroundColor: "底色",
  shuffle: "换一版",
  seed: (seed: number) => `种子 ${seed}`,
  reveal: "逐词出现",
  revealOn: "一个词一个词冒出来",
  revealOff: "整块一起出现",
  camera: "镜头与排版",
  turn: "旋转",
  turns: { none: "不旋转", turn: "直角转向" },
  lightNote: "轻动感不旋转、停留更久，动感最高 40。",
  cameraMotion: "镜头运动",
  cameraMotions: { smooth: "平滑", stopAndGo: "停走" },
  smoothNote: "镜头在两句之间一直在飞，到达时正好开口。",
  stopNote: "镜头停在当前行上，下一行开口前一小段才挪过去。",
  speed: "镜头速度",
  dwell: "镜头停留",
  anticipation: "镜头提前量",
  fit: "文字占屏",
  density: "文字密度",
  history: "历史文字",
  rows: "行",
  historyOpacity: "历史透明度",
  area: "字幕区域",
  areas: { center: "居中", bottom: "下方", full: "全画面" },
  backdrop: "背景",
  backdrops: { transparent: "透明", solid: "纯色" },
  solidNote: "纯色底只盖住字幕区域里的画面，不删素材、不改声音。",
  ending: "段落结束",
  endings: { hold: "停住", overviewIfRoom: "有空余时拉远" },
  perSegment: "只换某一段、主角词、断段与固定行还没进编辑器。",
};
