import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const es: CaptionPanelMessages = {
  modes: { none: "Ninguno", color: "Color", box: "Recuadro", scale: "Ampliar", lift: "Elevar", underline: "Subrayado", sweep: "Barrido" },
  badgeSequence: "Cinético",
  badgeTip: (mode: string) => `Palabra actual: ${mode}`,
  modified: "Modificado",
  revert: "Restaurar",
  revertLabel: (name: string) => `Restaurar «${name}»`,
  galleryHint: "Una tarjeta también cambia la palabra actual y el movimiento; la posición, el tamaño y el tiempo de visualización no cambian.",
  active: "Palabra actual",
  activeAria: "Aspecto de la palabra actual",
  color: "Color",
  boxColor: "Color del recuadro",
  tintColor: "Color de tinte",
  scale: "Ampliar",
  times: "×",
  transition: "Transición",
  spoken: "Palabras dichas",
  spokenModes: { keep: "Igual", tint: "Teñir", dim: "Atenuar" },
  unspoken: "Palabras siguientes",
  unspokenModes: { keep: "Igual", dim: "Atenuar", hidden: "Ocultar" },
  sweepUnit: "Barrido por",
  sweepUnits: { grapheme: "Carácter", word: "Palabra" },
  guide: "Punto guía",
  guideNote: "Dibuja un punto sobre la posición del barrido",
  nextLine: "Siguiente línea",
  nextLineNote: "Muestra la siguiente línea más pequeña debajo",
  noWordTiming: "Las líneas de traducción no tienen tiempos por palabra, así que la palabra actual no cambia.",
  motion: "Movimiento",
  stages: { in: "Entrada", out: "Salida", loop: "Bucle" },
  stageAria: (stage: string) => `Movimiento de ${stage}`,
  noMotion: "Ninguno",
  presets: {
    typewriter: "Máquina de escribir",
    'fade-up': "Subir con fundido",
    rise: "Ascender",
    cascade: "Cascada",
    pop: "Pop",
    'blur-in': "Enfoque suave",
    'slide-mask': "Deslizar",
    'wave-in': "Entrada en ola",
    'drop-in': "Caída",
    'float-in-top': "Flotar desde arriba",
    'float-in-bottom': "Flotar desde abajo",
    'scale-in': "Ampliar al entrar",
    impact: "Impacto",
    flip: "Volteo",
    stomp: "Pisotón",
    stack: "Apilar",
    'fade-down': "Bajar con fundido",
    sink: "Hundir",
    'pop-out': "Pop de salida",
    'blur-out': "Desenfocar",
    'typewriter-erase': "Borrar",
    pulse: "Pulso",
    wave: "Ola",
    shimmer: "Destello",
    swing: "Balanceo",
  },
  unit: "Unidad",
  units: { cue: "Completo", line: "Línea", word: "Palabra", grapheme: "Carácter" },
  trigger: "Activación",
  triggers: { enter: "Al aparecer", spoken: "Al decirse" },
  duration: "Duración",
  intensity: "Intensidad",
  catalogNote: "Este efecto se dibuja palabra a palabra al decirse; la activación, la unidad y la duración son fijas.",
  emptyStage: { in: "La línea completa aparece de una vez.", out: "La línea desaparece al terminar.", loop: "El subtítulo se queda quieto en pantalla." },
  sequencePreset: "Ajuste",
  sequencePresets: { standard: "Estándar", light: "Suave" },
  energy: "Energía",
  palette: "Colores",
  palettes: { classic: "Clásico", neon: "Neón", paper: "Papel cálido", ice: "Hielo", custom: "Personalizado" },
  primary: "Texto",
  accent: "Acento",
  secondary: "Segundo acento",
  backgroundColor: "Color de fondo",
  shuffle: "Otra versión",
  seed: (seed: number) => `Semilla ${seed}`,
  reveal: "Palabra por palabra",
  revealOn: "Las palabras aparecen de una en una",
  revealOff: "Cada bloque aparece de una vez",
  camera: "Cámara y diseño",
  turn: "Rotación",
  turns: { none: "Ninguna", turn: "Ángulos rectos" },
  lightNote: "Suave mantiene la cámara recta, se detiene más y limita la energía a 40.",
  cameraMotion: "Movimiento de cámara",
  cameraMotions: { smooth: "Fluido", stopAndGo: "Parar y avanzar" },
  smoothNote: "La cámara se desliza entre líneas y llega justo cuando empieza la siguiente.",
  stopNote: "La cámara se detiene en la línea actual y se mueve justo antes de la siguiente.",
  speed: "Velocidad de cámara",
  dwell: "Pausa de cámara",
  anticipation: "Anticipación",
  fit: "Ocupación del texto",
  density: "Densidad del texto",
  history: "Líneas anteriores",
  rows: "líneas",
  historyOpacity: "Opacidad de líneas anteriores",
  area: "Área de subtítulos",
  areas: { center: "Centro", bottom: "Abajo", full: "Pantalla completa" },
  backdrop: "Fondo",
  backdrops: { transparent: "Transparente", solid: "Sólido" },
  solidNote: "Un fondo sólido solo cubre la imagen dentro del área de subtítulos; el metraje y el sonido no cambian.",
  ending: "Fin de segmento",
  endings: { hold: "Mantener", overviewIfRoom: "Alejar si hay espacio" },
  perSegment: "Otra versión por segmento, palabras protagonistas, cortes de segmento y líneas fijas aún no están en el editor.",
};
