import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const pl: CaptionPanelMessages = {
  modes: { none: "Brak", color: "Kolor", box: "Ramka", scale: "Powiększenie", lift: "Uniesienie", underline: "Podkreślenie", sweep: "Wypełnienie" },
  badgeSequence: "Kinetyczne",
  badgeTip: (mode: string) => `Bieżące słowo: ${mode}`,
  modified: "Zmieniono",
  revert: "Przywróć",
  revertLabel: (name: string) => `Przywróć „${name}”`,
  galleryHint: "Karta zmienia też bieżące słowo i ruch; położenie, rozmiar i czas wyświetlania pozostają bez zmian.",
  active: "Bieżące słowo",
  activeAria: "Wygląd bieżącego słowa",
  color: "Kolor",
  boxColor: "Kolor ramki",
  tintColor: "Kolor zabarwienia",
  scale: "Powiększenie",
  times: "×",
  transition: "Przejście",
  spoken: "Wypowiedziane słowa",
  spokenModes: { keep: "Bez zmian", tint: "Zabarw", dim: "Przyciemnij" },
  unspoken: "Kolejne słowa",
  unspokenModes: { keep: "Bez zmian", dim: "Przyciemnij", hidden: "Ukryj" },
  sweepUnit: "Wypełnienie wg",
  sweepUnits: { grapheme: "Znaku", word: "Słowa" },
  guide: "Punkt prowadzący",
  guideNote: "Pokaż punkt nad wypełnianym miejscem",
  nextLine: "Następny wiersz",
  nextLineNote: "Pokaż następny wiersz mniejszy poniżej",
  noWordTiming: "Wiersze tłumaczenia nie mają czasów słów, więc bieżące słowo się nie zmienia.",
  motion: "Ruch",
  stages: { in: "Wejście", out: "Wyjście", loop: "Pętla" },
  stageAria: (stage: string) => `Ruch: ${stage}`,
  noMotion: "Brak",
  presets: {
    typewriter: "Maszyna do pisania",
    'fade-up': "Pojawienie w górę",
    rise: "Wznoszenie",
    cascade: "Kaskada",
    pop: "Wyskok",
    'blur-in': "Miękka ostrość",
    'slide-mask': "Wsunięcie",
    'wave-in': "Fala na wejściu",
    'drop-in': "Wpadnięcie",
    'float-in-top': "Z góry",
    'float-in-bottom': "Z dołu",
    'scale-in': "Powiększenie na wejściu",
    impact: "Uderzenie",
    flip: "Obrót",
    stomp: "Tupnięcie",
    stack: "Stos",
    'fade-down': "Zanikanie w dół",
    sink: "Zapadanie",
    'pop-out': "Zniknięcie",
    'blur-out': "Rozmycie",
    'typewriter-erase': "Wymazanie",
    pulse: "Puls",
    wave: "Fala",
    shimmer: "Migotanie",
    swing: "Kołysanie",
  },
  unit: "Jednostka",
  units: { cue: "Całość", line: "Wiersz", word: "Słowo", grapheme: "Znak" },
  trigger: "Wyzwalacz",
  triggers: { enter: "Przy pojawieniu", spoken: "Przy wypowiedzeniu" },
  duration: "Czas trwania",
  intensity: "Siła",
  catalogNote: "Ten efekt działa słowo po słowie przy wypowiadaniu; wyzwalacz, jednostka i czas są stałe.",
  emptyStage: { in: "Cały wiersz pojawia się od razu.", out: "Wiersz znika na końcu.", loop: "Napis pozostaje nieruchomy na ekranie." },
  sequencePreset: "Ustawienie",
  sequencePresets: { standard: "Standardowe", light: "Lekkie" },
  energy: "Dynamika",
  palette: "Kolory",
  palettes: { classic: "Klasyczne", neon: "Neon", paper: "Ciepły papier", ice: "Lód", custom: "Własne" },
  primary: "Tekst",
  accent: "Akcent",
  secondary: "Drugi akcent",
  backgroundColor: "Kolor tła",
  shuffle: "Inna wersja",
  seed: (seed: number) => `Ziarno ${seed}`,
  reveal: "Słowo po słowie",
  revealOn: "Słowa pojawiają się pojedynczo",
  revealOff: "Każdy blok pojawia się naraz",
  camera: "Kamera i układ",
  turn: "Obrót",
  turns: { none: "Brak", turn: "Kąty proste" },
  lightNote: "Lekkie trzyma kamerę prosto, dłużej się zatrzymuje i ogranicza dynamikę do 40.",
  cameraMotion: "Ruch kamery",
  cameraMotions: { smooth: "Płynny", stopAndGo: "Stop i start" },
  smoothNote: "Kamera płynie między wierszami i dociera dokładnie na początek następnego.",
  stopNote: "Kamera stoi na bieżącym wierszu i przesuwa się tuż przed następnym.",
  speed: "Szybkość kamery",
  dwell: "Postój kamery",
  anticipation: "Wyprzedzenie",
  fit: "Wypełnienie tekstem",
  density: "Gęstość tekstu",
  history: "Wcześniejsze wiersze",
  rows: "wierszy",
  historyOpacity: "Krycie wcześniejszych wierszy",
  area: "Obszar napisów",
  areas: { center: "Środek", bottom: "Dół", full: "Cały kadr" },
  backdrop: "Tło",
  backdrops: { transparent: "Przezroczyste", solid: "Jednolite" },
  solidNote: "Jednolite tło zakrywa tylko obraz w obszarze napisów; materiał i dźwięk pozostają bez zmian.",
  ending: "Koniec segmentu",
  endings: { hold: "Zatrzymaj", overviewIfRoom: "Oddal, jeśli jest miejsce" },
  perSegment: "Inna wersja dla segmentu, słowa główne, podziały segmentów i przypięte wiersze nie są jeszcze w edytorze.",
};
