import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const vi: CaptionPanelMessages = {
  modes: { none: "Không", color: "Màu", box: "Khung", scale: "Phóng to", lift: "Nâng lên", underline: "Gạch chân", sweep: "Quét màu" },
  badgeSequence: "Chuyển động",
  badgeTip: (mode: string) => `Từ hiện tại: ${mode}`,
  modified: "Đã sửa",
  revert: "Khôi phục",
  revertLabel: (name: string) => `Khôi phục “${name}”`,
  galleryHint: "Một thẻ cũng đổi từ hiện tại và chuyển động; vị trí, cỡ chữ và thời điểm hiển thị giữ nguyên.",
  active: "Từ hiện tại",
  activeAria: "Dáng vẻ của từ hiện tại",
  color: "Màu",
  boxColor: "Màu khung",
  tintColor: "Màu nhuộm",
  scale: "Phóng to",
  times: "×",
  transition: "Chuyển tiếp",
  spoken: "Từ đã đọc",
  spokenModes: { keep: "Giữ nguyên", tint: "Nhuộm màu", dim: "Làm mờ" },
  unspoken: "Từ sắp đọc",
  unspokenModes: { keep: "Giữ nguyên", dim: "Làm mờ", hidden: "Ẩn" },
  sweepUnit: "Quét theo",
  sweepUnits: { grapheme: "Ký tự", word: "Từ" },
  guide: "Chấm dẫn",
  guideNote: "Vẽ một chấm phía trên vị trí đang quét",
  nextLine: "Dòng tiếp theo",
  nextLineNote: "Hiện dòng tiếp theo nhỏ hơn ở dưới",
  noWordTiming: "Dòng bản dịch không có thời gian theo từ nên từ hiện tại không đổi.",
  motion: "Chuyển động",
  stages: { in: "Vào", out: "Ra", loop: "Lặp" },
  stageAria: (stage: string) => `Chuyển động ${stage}`,
  noMotion: "Không",
  presets: {
    typewriter: "Máy đánh chữ",
    'fade-up': "Hiện dần lên",
    rise: "Nổi lên",
    cascade: "Rơi lần lượt",
    pop: "Bật",
    'blur-in': "Lấy nét mềm",
    'slide-mask': "Trượt vào",
    'wave-in': "Sóng vào",
    'drop-in': "Rơi vào",
    'float-in-top': "Trôi từ trên",
    'float-in-bottom': "Trôi từ dưới",
    'scale-in': "Phóng to khi vào",
    impact: "Va đập",
    flip: "Lật",
    stomp: "Dậm",
    stack: "Xếp chồng",
    'fade-down': "Mờ dần xuống",
    sink: "Chìm xuống",
    'pop-out': "Bật ra",
    'blur-out': "Mờ đi",
    'typewriter-erase': "Xóa dần",
    pulse: "Nhịp đập",
    wave: "Sóng",
    shimmer: "Lấp lánh",
    swing: "Đung đưa",
  },
  unit: "Đơn vị",
  units: { cue: "Cả câu", line: "Từng dòng", word: "Từng từ", grapheme: "Từng ký tự" },
  trigger: "Kích hoạt",
  triggers: { enter: "Khi xuất hiện", spoken: "Khi được đọc" },
  duration: "Thời lượng",
  intensity: "Độ mạnh",
  catalogNote: "Hiệu ứng này chạy theo từng từ khi được đọc; kích hoạt, đơn vị và thời lượng cố định.",
  emptyStage: { in: "Cả dòng xuất hiện ngay.", out: "Dòng biến mất khi kết thúc.", loop: "Phụ đề đứng yên trên màn hình." },
  sequencePreset: "Mẫu",
  sequencePresets: { standard: "Tiêu chuẩn", light: "Nhẹ" },
  energy: "Độ sôi động",
  palette: "Màu sắc",
  palettes: { classic: "Cổ điển", neon: "Neon", paper: "Giấy ấm", ice: "Băng", custom: "Tùy chỉnh" },
  primary: "Chữ",
  accent: "Nhấn",
  secondary: "Nhấn phụ",
  backgroundColor: "Màu nền",
  shuffle: "Bản khác",
  seed: (seed: number) => `Hạt giống ${seed}`,
  reveal: "Từng từ một",
  revealOn: "Các từ hiện ra lần lượt",
  revealOff: "Mỗi khối hiện ra cùng lúc",
  camera: "Máy quay và bố cục",
  turn: "Xoay",
  turns: { none: "Không", turn: "Góc vuông" },
  lightNote: "Nhẹ giữ máy quay thẳng, dừng lâu hơn và giới hạn độ sôi động ở 40.",
  cameraMotion: "Chuyển động máy quay",
  cameraMotions: { smooth: "Mượt", stopAndGo: "Dừng rồi đi" },
  smoothNote: "Máy quay lướt giữa các dòng và đến đúng lúc dòng tiếp theo bắt đầu.",
  stopNote: "Máy quay dừng ở dòng hiện tại và chỉ di chuyển ngay trước dòng tiếp theo.",
  speed: "Tốc độ máy quay",
  dwell: "Máy quay dừng",
  anticipation: "Đi trước",
  fit: "Độ phủ chữ",
  density: "Mật độ chữ",
  history: "Dòng trước",
  rows: "dòng",
  historyOpacity: "Độ mờ của dòng trước",
  area: "Vùng phụ đề",
  areas: { center: "Giữa", bottom: "Dưới", full: "Toàn khung" },
  backdrop: "Nền",
  backdrops: { transparent: "Trong suốt", solid: "Màu trơn" },
  solidNote: "Nền màu trơn chỉ che hình trong vùng phụ đề; tư liệu và âm thanh không đổi.",
  ending: "Kết thúc đoạn",
  endings: { hold: "Giữ nguyên", overviewIfRoom: "Thu xa nếu còn chỗ" },
  perSegment: "Đổi bản cho từng đoạn, từ chính, ngắt đoạn và cố định dòng chưa có trong trình chỉnh sửa.",
};
