import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const ru: CaptionPanelMessages = {
  modes: { none: "Нет", color: "Цвет", box: "Плашка", scale: "Увеличение", lift: "Подъём", underline: "Подчёркивание", sweep: "Заливка" },
  badgeSequence: "Кинетика",
  badgeTip: (mode: string) => `Текущее слово: ${mode}`,
  modified: "Изменено",
  revert: "Вернуть",
  revertLabel: (name: string) => `Вернуть «${name}»`,
  galleryHint: "Карточка меняет и текущее слово, и движение; положение, размер и время показа остаются прежними.",
  active: "Текущее слово",
  activeAria: "Вид текущего слова",
  color: "Цвет",
  boxColor: "Цвет плашки",
  tintColor: "Цвет окраски",
  scale: "Увеличение",
  times: "×",
  transition: "Переход",
  spoken: "Сказанные слова",
  spokenModes: { keep: "Без изменений", tint: "Окрасить", dim: "Приглушить" },
  unspoken: "Следующие слова",
  unspokenModes: { keep: "Без изменений", dim: "Приглушить", hidden: "Скрыть" },
  sweepUnit: "Заливка по",
  sweepUnits: { grapheme: "Символам", word: "Словам" },
  guide: "Точка-указатель",
  guideNote: "Показывать точку над местом заливки",
  nextLine: "Следующая строка",
  nextLineNote: "Показывать следующую строку мельче снизу",
  noWordTiming: "У строк перевода нет времени по словам, поэтому текущее слово не меняется.",
  motion: "Движение",
  stages: { in: "Появление", out: "Исчезновение", loop: "Цикл" },
  stageAria: (stage: string) => `Движение: ${stage}`,
  noMotion: "Нет",
  presets: {
    typewriter: "Печатная машинка",
    'fade-up': "Появление вверх",
    rise: "Подъём",
    cascade: "Каскад",
    pop: "Всплытие",
    'blur-in': "Мягкий фокус",
    'slide-mask': "Сдвиг",
    'wave-in': "Волна при появлении",
    'drop-in': "Падение",
    'float-in-top': "Сверху",
    'float-in-bottom': "Снизу",
    'scale-in': "Увеличение при появлении",
    impact: "Удар",
    flip: "Переворот",
    stomp: "Топот",
    stack: "Стопка",
    'fade-down': "Исчезновение вниз",
    sink: "Погружение",
    'pop-out': "Схлопывание",
    'blur-out': "Размытие",
    'typewriter-erase': "Стирание",
    pulse: "Пульс",
    wave: "Волна",
    shimmer: "Мерцание",
    swing: "Покачивание",
  },
  unit: "Единица",
  units: { cue: "Целиком", line: "Строка", word: "Слово", grapheme: "Символ" },
  trigger: "Запуск",
  triggers: { enter: "При появлении", spoken: "При произнесении" },
  duration: "Длительность",
  intensity: "Сила",
  catalogNote: "Этот эффект идёт по словам при произнесении; запуск, единица и длительность фиксированы.",
  emptyStage: { in: "Вся строка появляется сразу.", out: "Строка исчезает в конце.", loop: "Субтитр остаётся неподвижным на экране." },
  sequencePreset: "Набор",
  sequencePresets: { standard: "Стандарт", light: "Лёгкий" },
  energy: "Динамика",
  palette: "Цвета",
  palettes: { classic: "Классика", neon: "Неон", paper: "Тёплая бумага", ice: "Лёд", custom: "Свои" },
  primary: "Текст",
  accent: "Акцент",
  secondary: "Второй акцент",
  backgroundColor: "Цвет фона",
  shuffle: "Другой вариант",
  seed: (seed: number) => `Зерно ${seed}`,
  reveal: "По словам",
  revealOn: "Слова появляются по одному",
  revealOff: "Каждый блок появляется целиком",
  camera: "Камера и раскладка",
  turn: "Поворот",
  turns: { none: "Нет", turn: "Прямые углы" },
  lightNote: "Лёгкий не поворачивает камеру, дольше задерживается и ограничивает динамику до 40.",
  cameraMotion: "Движение камеры",
  cameraMotions: { smooth: "Плавно", stopAndGo: "С остановками" },
  smoothNote: "Камера плывёт между строками и приходит ровно к началу следующей.",
  stopNote: "Камера стоит на текущей строке и сдвигается прямо перед следующей.",
  speed: "Скорость камеры",
  dwell: "Задержка камеры",
  anticipation: "Упреждение",
  fit: "Заполнение текстом",
  density: "Плотность текста",
  history: "Прежние строки",
  rows: "строк",
  historyOpacity: "Непрозрачность прежних строк",
  area: "Область субтитров",
  areas: { center: "По центру", bottom: "Снизу", full: "Весь кадр" },
  backdrop: "Фон",
  backdrops: { transparent: "Прозрачный", solid: "Сплошной" },
  solidNote: "Сплошной фон закрывает только изображение в области субтитров; материал и звук не меняются.",
  ending: "Конец сегмента",
  endings: { hold: "Остановить", overviewIfRoom: "Отдалить, если есть место" },
  perSegment: "Другой вариант для одного сегмента, главные слова, разрывы сегментов и закреплённые строки пока не в редакторе.",
};
