import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const ptBR: CaptionPanelMessages = {
  modes: { none: "Nenhum", color: "Cor", box: "Caixa", scale: "Ampliar", lift: "Elevar", underline: "Sublinhado", sweep: "Varredura" },
  badgeSequence: "Cinético",
  badgeTip: (mode: string) => `Palavra atual: ${mode}`,
  modified: "Modificado",
  revert: "Restaurar",
  revertLabel: (name: string) => `Restaurar “${name}”`,
  galleryHint: "Um cartão também muda a palavra atual e o movimento; posição, tamanho e tempo de exibição não mudam.",
  active: "Palavra atual",
  activeAria: "Aparência da palavra atual",
  color: "Cor",
  boxColor: "Cor da caixa",
  tintColor: "Cor do tingimento",
  scale: "Ampliar",
  times: "×",
  transition: "Transição",
  spoken: "Palavras ditas",
  spokenModes: { keep: "Igual", tint: "Tingir", dim: "Esmaecer" },
  unspoken: "Próximas palavras",
  unspokenModes: { keep: "Igual", dim: "Esmaecer", hidden: "Ocultar" },
  sweepUnit: "Varredura por",
  sweepUnits: { grapheme: "Caractere", word: "Palavra" },
  guide: "Ponto guia",
  guideNote: "Mostra um ponto acima da posição da varredura",
  nextLine: "Próxima linha",
  nextLineNote: "Mostra a próxima linha menor abaixo",
  noWordTiming: "Linhas de tradução não têm tempo por palavra, então a palavra atual não muda.",
  motion: "Movimento",
  stages: { in: "Entrada", out: "Saída", loop: "Loop" },
  stageAria: (stage: string) => `Movimento de ${stage}`,
  noMotion: "Nenhum",
  presets: {
    typewriter: "Máquina de escrever",
    'fade-up': "Subir com fade",
    rise: "Erguer",
    cascade: "Cascata",
    pop: "Pop",
    'blur-in': "Foco suave",
    'slide-mask': "Deslizar",
    'wave-in': "Entrada em onda",
    'drop-in': "Cair",
    'float-in-top': "Flutuar de cima",
    'float-in-bottom': "Flutuar de baixo",
    'scale-in': "Ampliar ao entrar",
    impact: "Impacto",
    flip: "Virar",
    stomp: "Pisada",
    stack: "Empilhar",
    'fade-down': "Descer com fade",
    sink: "Afundar",
    'pop-out': "Pop de saída",
    'blur-out': "Desfocar",
    'typewriter-erase': "Apagar",
    pulse: "Pulsar",
    wave: "Onda",
    shimmer: "Cintilar",
    swing: "Balançar",
  },
  unit: "Unidade",
  units: { cue: "Inteiro", line: "Linha", word: "Palavra", grapheme: "Caractere" },
  trigger: "Disparo",
  triggers: { enter: "Ao aparecer", spoken: "Ao ser dita" },
  duration: "Duração",
  intensity: "Intensidade",
  catalogNote: "Este efeito é desenhado palavra por palavra ao ser dito; disparo, unidade e duração são fixos.",
  emptyStage: { in: "A linha inteira aparece de uma vez.", out: "A linha some quando termina.", loop: "A legenda fica parada na tela." },
  sequencePreset: "Predefinição",
  sequencePresets: { standard: "Padrão", light: "Leve" },
  energy: "Energia",
  palette: "Cores",
  palettes: { classic: "Clássico", neon: "Neon", paper: "Papel quente", ice: "Gelo", custom: "Personalizado" },
  primary: "Texto",
  accent: "Destaque",
  secondary: "Segundo destaque",
  backgroundColor: "Cor de fundo",
  shuffle: "Outra versão",
  seed: (seed: number) => `Semente ${seed}`,
  reveal: "Palavra por palavra",
  revealOn: "As palavras surgem uma a uma",
  revealOff: "Cada bloco aparece de uma vez",
  camera: "Câmera e layout",
  turn: "Rotação",
  turns: { none: "Nenhuma", turn: "Ângulos retos" },
  lightNote: "Leve mantém a câmera reta, demora mais e limita a energia a 40.",
  cameraMotion: "Movimento da câmera",
  cameraMotions: { smooth: "Suave", stopAndGo: "Para e anda" },
  smoothNote: "A câmera desliza entre as linhas e chega bem quando a próxima começa.",
  stopNote: "A câmera fica na linha atual e se move logo antes da próxima.",
  speed: "Velocidade da câmera",
  dwell: "Pausa da câmera",
  anticipation: "Antecipação",
  fit: "Preenchimento do texto",
  density: "Densidade do texto",
  history: "Linhas anteriores",
  rows: "linhas",
  historyOpacity: "Opacidade das linhas anteriores",
  area: "Área da legenda",
  areas: { center: "Centro", bottom: "Embaixo", full: "Tela inteira" },
  backdrop: "Fundo",
  backdrops: { transparent: "Transparente", solid: "Sólido" },
  solidNote: "Um fundo sólido cobre só a imagem dentro da área da legenda; mídia e som não mudam.",
  ending: "Fim do segmento",
  endings: { hold: "Manter", overviewIfRoom: "Afastar se houver espaço" },
  perSegment: "Outra versão por segmento, palavras de destaque, quebras de segmento e linhas fixadas ainda não estão no editor.",
};
