import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const tr: CaptionPanelMessages = {
  modes: { none: "Yok", color: "Renk", box: "Kutu", scale: "Büyüt", lift: "Kaldır", underline: "Alt çizgi", sweep: "Süpürme" },
  badgeSequence: "Kinetik",
  badgeTip: (mode: string) => `Geçerli sözcük: ${mode}`,
  modified: "Değiştirildi",
  revert: "Geri al",
  revertLabel: (name: string) => `“${name}” stiline geri dön`,
  galleryHint: "Bir kart geçerli sözcüğü ve hareketi de değiştirir; konum, boyut ve gösterim zamanı aynı kalır.",
  active: "Geçerli sözcük",
  activeAria: "Geçerli sözcüğün görünümü",
  color: "Renk",
  boxColor: "Kutu rengi",
  tintColor: "Boyama rengi",
  scale: "Büyüt",
  times: "×",
  transition: "Geçiş",
  spoken: "Söylenen sözcükler",
  spokenModes: { keep: "Aynı", tint: "Boya", dim: "Soldur" },
  unspoken: "Sıradaki sözcükler",
  unspokenModes: { keep: "Aynı", dim: "Soldur", hidden: "Gizle" },
  sweepUnit: "Süpürme",
  sweepUnits: { grapheme: "Karakter", word: "Sözcük" },
  guide: "Kılavuz nokta",
  guideNote: "Süpürülen konumun üstünde bir nokta göster",
  nextLine: "Sonraki satır",
  nextLineNote: "Sonraki satırı altta daha küçük göster",
  noWordTiming: "Çeviri satırlarında sözcük zamanlaması yoktur, bu yüzden geçerli sözcük değişmez.",
  motion: "Hareket",
  stages: { in: "Giriş", out: "Çıkış", loop: "Döngü" },
  stageAria: (stage: string) => `${stage} hareketi`,
  noMotion: "Yok",
  presets: {
    typewriter: "Daktilo",
    'fade-up': "Yukarı belirme",
    rise: "Yükselme",
    cascade: "Şelale",
    pop: "Pop",
    'blur-in': "Yumuşak odak",
    'slide-mask': "Kaydırma",
    'wave-in': "Dalga girişi",
    'drop-in': "Düşme",
    'float-in-top': "Yukarıdan süzülme",
    'float-in-bottom': "Aşağıdan süzülme",
    'scale-in': "Büyüyerek giriş",
    impact: "Darbe",
    flip: "Çevirme",
    stomp: "Tepinme",
    stack: "Yığma",
    'fade-down': "Aşağı solma",
    sink: "Batma",
    'pop-out': "Pop çıkış",
    'blur-out': "Bulanık çıkış",
    'typewriter-erase': "Silme",
    pulse: "Nabız",
    wave: "Dalga",
    shimmer: "Parıltı",
    swing: "Sallanma",
  },
  unit: "Birim",
  units: { cue: "Tümü", line: "Satır", word: "Sözcük", grapheme: "Karakter" },
  trigger: "Tetikleyici",
  triggers: { enter: "Görününce", spoken: "Söylenince" },
  duration: "Süre",
  intensity: "Güç",
  catalogNote: "Bu efekt söylenen her sözcükte çizilir; tetikleyici, birim ve süre sabittir.",
  emptyStage: { in: "Satırın tamamı bir anda görünür.", out: "Satır bitince kaybolur.", loop: "Altyazı ekranda hareketsiz kalır." },
  sequencePreset: "Ön ayar",
  sequencePresets: { standard: "Standart", light: "Hafif" },
  energy: "Enerji",
  palette: "Renkler",
  palettes: { classic: "Klasik", neon: "Neon", paper: "Sıcak kâğıt", ice: "Buz", custom: "Özel" },
  primary: "Metin",
  accent: "Vurgu",
  secondary: "İkinci vurgu",
  backgroundColor: "Arka plan rengi",
  shuffle: "Başka sürüm",
  seed: (seed: number) => `Tohum ${seed}`,
  reveal: "Sözcük sözcük",
  revealOn: "Sözcükler tek tek belirir",
  revealOff: "Her blok bir anda görünür",
  camera: "Kamera ve düzen",
  turn: "Döndürme",
  turns: { none: "Yok", turn: "Dik açılar" },
  lightNote: "Hafif, kamerayı düz tutar, daha uzun bekler ve enerjiyi 40 ile sınırlar.",
  cameraMotion: "Kamera hareketi",
  cameraMotions: { smooth: "Akıcı", stopAndGo: "Dur ve git" },
  smoothNote: "Kamera satırlar arasında süzülür ve sonraki satır başlarken varır.",
  stopNote: "Kamera geçerli satırda durur ve sonrakinden hemen önce kayar.",
  speed: "Kamera hızı",
  dwell: "Kamera bekleme",
  anticipation: "Öncelik",
  fit: "Metin doluluğu",
  density: "Metin yoğunluğu",
  history: "Önceki satırlar",
  rows: "satır",
  historyOpacity: "Önceki satır opaklığı",
  area: "Altyazı alanı",
  areas: { center: "Orta", bottom: "Alt", full: "Tam kare" },
  backdrop: "Arka plan",
  backdrops: { transparent: "Saydam", solid: "Düz renk" },
  solidNote: "Düz renk arka plan yalnızca altyazı alanındaki görüntüyü örter; malzeme ve ses değişmez.",
  ending: "Bölüm sonu",
  endings: { hold: "Beklet", overviewIfRoom: "Yer varsa uzaklaş" },
  perSegment: "Bölüm başına başka sürüm, ana sözcükler, bölüm araları ve sabitlenmiş satırlar henüz düzenleyicide yok.",
};
