import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const zhHant: CaptionPanelMessages = {
  modes: { none: "無", color: "變色", box: "底塊", scale: "放大", lift: "上抬", underline: "底線", sweep: "掃色" },
  badgeSequence: "動態排版",
  badgeTip: (mode: string) => `目前詞：${mode}`,
  modified: "已修改",
  revert: "還原",
  revertLabel: (name: string) => `還原成「${name}」`,
  galleryHint: "套用一張卡片也會換掉目前詞與動效；位置、字級與顯示時機不變。",
  active: "目前詞",
  activeAria: "目前詞的樣子",
  color: "顏色",
  boxColor: "底塊顏色",
  tintColor: "染色顏色",
  scale: "放大",
  times: "倍",
  transition: "過渡",
  spoken: "唸過的詞",
  spokenModes: { keep: "不變", tint: "染色", dim: "變淡" },
  unspoken: "還沒唸到的詞",
  unspokenModes: { keep: "不變", dim: "變淡", hidden: "不顯示" },
  sweepUnit: "掃色",
  sweepUnits: { grapheme: "按字", word: "按詞" },
  guide: "引導點",
  guideNote: "在掃到的位置上方畫一個點",
  nextLine: "預告下一句",
  nextLineNote: "在下方以小一號顯示下一句",
  noWordTiming: "譯文沒有逐詞時間，這一行的目前詞維持不變。",
  motion: "動效",
  stages: { in: "進場", out: "退場", loop: "循環" },
  stageAria: (stage: string) => `${stage}動效`,
  noMotion: "無",
  presets: {
    typewriter: "打字機",
    'fade-up': "淡入上移",
    rise: "升起",
    cascade: "逐詞落下",
    pop: "彈出",
    'blur-in': "柔焦",
    'slide-mask': "滑入",
    'wave-in': "波浪進場",
    'drop-in': "落入",
    'float-in-top': "上方浮入",
    'float-in-bottom': "下方浮入",
    'scale-in': "放大進場",
    impact: "衝擊",
    flip: "翻頁",
    stomp: "跺腳",
    stack: "堆疊",
    'fade-down': "淡出下移",
    sink: "下沉",
    'pop-out': "彈出消失",
    'blur-out': "柔焦消失",
    'typewriter-erase': "逐字擦除",
    pulse: "脈動",
    wave: "波浪",
    shimmer: "閃爍",
    swing: "搖擺",
  },
  unit: "單位",
  units: { cue: "整條", line: "逐行", word: "逐詞", grapheme: "逐字" },
  trigger: "觸發",
  triggers: { enter: "出現時", spoken: "唸到時" },
  duration: "時長",
  intensity: "強弱",
  catalogNote: "這一格跟著唸到的詞逐詞呈現，觸發、單位與時長隨它本身。",
  emptyStage: { in: "整句直接出現。", out: "這一句結束時直接消失。", loop: "字幕在畫面上時保持靜止。" },
  sequencePreset: "預設",
  sequencePresets: { standard: "標準", light: "輕動感" },
  energy: "動感",
  palette: "配色",
  palettes: { classic: "經典", neon: "螢光", paper: "暖紙", ice: "冰藍", custom: "自訂" },
  primary: "文字",
  accent: "強調",
  secondary: "輔色",
  backgroundColor: "底色",
  shuffle: "換一版",
  seed: (seed: number) => `種子 ${seed}`,
  reveal: "逐詞出現",
  revealOn: "一個詞一個詞冒出來",
  revealOff: "整塊一起出現",
  camera: "鏡頭與排版",
  turn: "旋轉",
  turns: { none: "不旋轉", turn: "直角轉向" },
  lightNote: "輕動感不旋轉、停留更久，動感最高 40。",
  cameraMotion: "鏡頭運動",
  cameraMotions: { smooth: "平滑", stopAndGo: "停走" },
  smoothNote: "鏡頭在兩句之間一直移動，抵達時正好開口。",
  stopNote: "鏡頭停在目前這一行，下一行開口前才移過去。",
  speed: "鏡頭速度",
  dwell: "鏡頭停留",
  anticipation: "鏡頭提前量",
  fit: "文字佔畫面",
  density: "文字密度",
  history: "歷史文字",
  rows: "行",
  historyOpacity: "歷史透明度",
  area: "字幕區域",
  areas: { center: "置中", bottom: "下方", full: "全畫面" },
  backdrop: "背景",
  backdrops: { transparent: "透明", solid: "純色" },
  solidNote: "純色底只蓋住字幕區域內的畫面，不刪素材、不改聲音。",
  ending: "段落結束",
  endings: { hold: "停住", overviewIfRoom: "有空間時拉遠" },
  perSegment: "只換某一段、主角詞、斷段與固定行尚未進入編輯器。",
};
