import type { CaptionPanelMessages } from './caption-panel-copy.ts';

export const fr: CaptionPanelMessages = {
  modes: { none: "Aucun", color: "Couleur", box: "Encadré", scale: "Agrandir", lift: "Soulever", underline: "Souligné", sweep: "Balayage" },
  badgeSequence: "Cinétique",
  badgeTip: (mode: string) => `Mot actif : ${mode}`,
  modified: "Modifié",
  revert: "Rétablir",
  revertLabel: (name: string) => `Rétablir « ${name} »`,
  galleryHint: "Une carte change aussi le mot actif et l’animation ; la position, la taille et le moment d’affichage restent inchangés.",
  active: "Mot actif",
  activeAria: "Apparence du mot actif",
  color: "Couleur",
  boxColor: "Couleur de l’encadré",
  tintColor: "Couleur de teinte",
  scale: "Agrandir",
  times: "×",
  transition: "Transition",
  spoken: "Mots prononcés",
  spokenModes: { keep: "Inchangé", tint: "Teinter", dim: "Atténuer" },
  unspoken: "Mots à venir",
  unspokenModes: { keep: "Inchangé", dim: "Atténuer", hidden: "Masquer" },
  sweepUnit: "Balayage par",
  sweepUnits: { grapheme: "Caractère", word: "Mot" },
  guide: "Point guide",
  guideNote: "Affiche un point au-dessus de la position balayée",
  nextLine: "Ligne suivante",
  nextLineNote: "Affiche la ligne suivante en plus petit dessous",
  noWordTiming: "Les lignes de traduction n’ont pas de minutage par mot ; le mot actif ne change donc pas.",
  motion: "Animation",
  stages: { in: "Entrée", out: "Sortie", loop: "Boucle" },
  stageAria: (stage: string) => `Animation : ${stage}`,
  noMotion: "Aucune",
  presets: {
    typewriter: "Machine à écrire",
    'fade-up': "Fondu montant",
    rise: "Montée",
    cascade: "Cascade",
    pop: "Pop",
    'blur-in': "Flou doux",
    'slide-mask': "Glissement",
    'wave-in': "Vague d’entrée",
    'drop-in': "Chute",
    'float-in-top': "Flotter du haut",
    'float-in-bottom': "Flotter du bas",
    'scale-in': "Agrandir à l’entrée",
    impact: "Impact",
    flip: "Retournement",
    stomp: "Frappe",
    stack: "Empiler",
    'fade-down': "Fondu descendant",
    sink: "Enfoncer",
    'pop-out': "Pop de sortie",
    'blur-out': "Flou de sortie",
    'typewriter-erase': "Effacer",
    pulse: "Pulsation",
    wave: "Vague",
    shimmer: "Scintillement",
    swing: "Balancement",
  },
  unit: "Unité",
  units: { cue: "Entier", line: "Ligne", word: "Mot", grapheme: "Caractère" },
  trigger: "Déclenchement",
  triggers: { enter: "À l’apparition", spoken: "À la prononciation" },
  duration: "Durée",
  intensity: "Intensité",
  catalogNote: "Cet effet s’applique mot par mot à la prononciation ; déclenchement, unité et durée sont fixes.",
  emptyStage: { in: "La ligne entière apparaît d’un coup.", out: "La ligne disparaît à la fin.", loop: "Le sous-titre reste immobile à l’écran." },
  sequencePreset: "Préréglage",
  sequencePresets: { standard: "Standard", light: "Léger" },
  energy: "Énergie",
  palette: "Couleurs",
  palettes: { classic: "Classique", neon: "Néon", paper: "Papier chaud", ice: "Glace", custom: "Personnalisé" },
  primary: "Texte",
  accent: "Accent",
  secondary: "Second accent",
  backgroundColor: "Couleur de fond",
  shuffle: "Autre version",
  seed: (seed: number) => `Graine ${seed}`,
  reveal: "Mot par mot",
  revealOn: "Les mots apparaissent un à un",
  revealOff: "Chaque bloc apparaît d’un coup",
  camera: "Caméra et mise en page",
  turn: "Rotation",
  turns: { none: "Aucune", turn: "Angles droits" },
  lightNote: "Léger garde la caméra droite, s’attarde plus et limite l’énergie à 40.",
  cameraMotion: "Mouvement de caméra",
  cameraMotions: { smooth: "Fluide", stopAndGo: "Arrêt et reprise" },
  smoothNote: "La caméra glisse entre les lignes et arrive pile au début de la suivante.",
  stopNote: "La caméra reste sur la ligne en cours et se déplace juste avant la suivante.",
  speed: "Vitesse de caméra",
  dwell: "Pause de caméra",
  anticipation: "Anticipation",
  fit: "Remplissage du texte",
  density: "Densité du texte",
  history: "Lignes précédentes",
  rows: "lignes",
  historyOpacity: "Opacité des lignes précédentes",
  area: "Zone des sous-titres",
  areas: { center: "Centre", bottom: "Bas", full: "Plein cadre" },
  backdrop: "Fond",
  backdrops: { transparent: "Transparent", solid: "Uni" },
  solidNote: "Un fond uni ne couvre que l’image dans la zone des sous-titres ; les médias et le son restent intacts.",
  ending: "Fin de segment",
  endings: { hold: "Figer", overviewIfRoom: "Dézoomer si possible" },
  perSegment: "Une autre version par segment, les mots vedettes, les coupures de segment et les lignes épinglées ne sont pas encore dans l’éditeur.",
};
