import type { ChapterMessages } from './chapter-copy.ts';

export const ko: ChapterMessages = {
  band: '챕터',
  prev: '이전 챕터',
  next: '다음 챕터',
  noChapters: '아직 챕터가 없습니다',
  gap: '챕터 없음',
  beforeFirst: '첫 챕터 이전',
  add: '재생 헤드 위치에 챕터 추가',
  rename: '이름 변경…',
  remove: '이 챕터 삭제',
  menuLabel: (title: string) => `챕터 “${title}”`,
  gapMenuLabel: '챕터 막대',
  segmentLabel: (title: string, range: string) => `${title}, ${range}, 클릭하면 시작 지점으로 이동`,
  dragHint: '드래그해 이 챕터의 시작 지점 이동',
  addTitle: '챕터 추가',
  renameTitle: '챕터 이름 변경',
  titleLabel: '제목',
  addAt: (time: string) => `${time}에서 시작해 다음 챕터까지 이어집니다`,
  confirmAdd: '추가',
  confirmRename: '이름 변경',
  cancel: '취소',
  refusal: {
    exists: '재생 헤드 위치에 이미 챕터가 있습니다',
    beyond: '재생 헤드가 끝에 있어 여기에는 챕터를 추가할 수 없습니다',
    blank: '제목은 비워 둘 수 없습니다',
  },
  labels: { add: '챕터 추가', rename: '챕터 이름 변경', remove: '챕터 삭제', move: '챕터 시작 지점 이동' },
  added: (title: string) => `챕터 “${title}”을(를) 추가했습니다`,
  renamed: (title: string) => `“${title}”(으)로 이름을 변경했습니다`,
  removed: (title: string) => `챕터 “${title}”을(를) 삭제했습니다`,
  undo: '실행 취소',
  clickRename: '클릭해 이름 변경',
  jump: '이 챕터의 시작 지점으로 이동',
  paragraphs: (n: number) => `문단 ${n}개`,
  empty: '이 챕터에는 아직 문단이 없습니다',
};
