import { pluralForm } from '@baocut/protocol';
import type { EditorMessages } from './editor-copy.ts';

export const de: EditorMessages = {
  withNote: (label: string, note: string) => `${label} (${note})`,
  labeled: (label: string, value: string) => `${label}: ${value}`,
  thenNext: (message: string, next: string) => `${message}. ${next}`,
  gap: " ",
  undo: "Rückgängig machen",
  redo: "Wiederholen",
  cancel: "Abbrechen",
  retry: "Erneut versuchen",
  addClip: "Clip hinzufügen",
  editor: "Editor",
  notEditableNow: "Das Video kann derzeit nicht bearbeitet werden",
  timeline: "Zeitleiste",
  moveClips: "Clips verschieben",
  moveTrack: 'Spur verschieben',
  importAndAdd: "Material importieren und hinzufügen",
  seconds2: (seconds: number) => `${seconds.toFixed(2)}s`,
  emptyTimeline: "Material hierher ziehen oder rechts im Bereich hinzufügen",
  hideTrack: (label: string) => `Ausblenden: ${label}: nicht in der Vorschau angezeigt`,
  showTrack: (label: string) => `Einblenden: ${label}`,
  hideTrackLabel: "Spur ausblenden",
  showTrackLabel: "Spur einblenden",
  unmuteTrack: (label: string) => `Stummschaltung aufheben: ${label}`,
  muteTrack: (label: string) => `Stummschalten: ${label}`,
  unmuteTrackLabel: "Stummschaltung aufheben",
  muteTrackLabel: "Spur stummschalten",
  unlockTrack: (label: string) => `Entsperren: ${label}`,
  lockTrack: (label: string) => `Sperren: ${label}: Clips können darauf nicht verschoben, getrimmt oder gelöscht werden`,
  unlockTrackLabel: "Spur entsperren",
  lockTrackLabel: "Spur sperren",
  playTip: { play: "Abspielen · Space", pause: "Pause · Space", replay: "Erneut abspielen" },
  playLabel: { play: "Abspielen", pause: "Pause", replay: "Erneut abspielen" },
  undoTip: (label: string, keys: string) => `Rückgängig machen: „${label}“ ${keys}`,
  redoTip: (label: string, keys: string) => `Wiederholen: „${label}“ ${keys}`,
  nothingToUndo: "Nichts zum Rückgängigmachen",
  nothingToRedo: "Nichts zum Wiederholen",
  splitTip: "Am Abspielkopf teilen · S",
  split: "Teilen",
  splitClips: "Clip teilen",
  deleteTip: "Auswahl löschen · Delete",
  deleteSelected: "Auswahl löschen",
  playhead: "Abspielkopfposition",
  totalLength: (duration: string) => `Gesamtlänge ${duration}`,
  editFailed: (message: string) => `Änderung konnte nicht vorgenommen werden: ${message}`,
  cantOpen: "Dieses Video kann nicht geöffnet werden",
  openingAria: "Video wird geöffnet",
  opening: "Video wird geöffnet…",
  resizeTimeline: "Zeitleistengröße ändern",
  workingDraft: "Arbeitsentwurf",
  previewCanvas: "Vorschau",
  previewFailed: "Die Vorschau kann nicht gezeichnet werden",
  emptyDrag: "Materialien in die Zeitleiste ziehen",
  emptyOr: "oder rechts im Medienbereich hinzufügen",
  problemsCount: (n: number) => `${n} ${pluralForm('de', n, { one: "Eintrag", other: "Einträge" })} kann nicht gezeichnet werden`,
  problemsTitle: "Einige Inhalte dieses Frames können nicht gezeichnet werden",
  rendererFailed: (message: string) => `Der Vorschau-Renderer wurde nicht geladen: ${message}`,
  spectrumTooLarge: (itemId: string, assetId: string, mb: number) =>
    `Wellenform ${itemId}: Material ${assetId} ist größer als ${mb} MB; die Vorschau analysiert daher keinen Ton. Export bleibt unverändert`,
  stall: {
    loading: 'Vorschau wird geladen',
    title: 'Die Vorschau hängt',
    engine: 'Die Vorschau-Engine wird noch geladen',
    video: 'Dieses Video wird noch vorbereitet',
    media: (name: string) => `Warten auf Medien: ${name}`,
    mediaUnnamed: 'Warten auf Medien',
    preparing: 'Vorschau wird vorbereitet',
    converting: (name: string) => `Wird zum Abspielen konvertiert: ${name}`,
    convertingUnnamed: 'Medien werden zum Abspielen konvertiert',
    once: 'Das passiert nur beim ersten Öffnen. Deine Originaldatei bleibt unverändert.',
    prepare: (name: string) => `Medienkonvertierung kommt nicht voran: ${name}`,
    prepareUnnamed: 'Medienkonvertierung kommt nicht voran',
    captions: (name: string) => `Warten auf Untertitel: ${name}`,
    captionsUnnamed: 'Warten auf Untertitel',
    fonts: (name: string) => `Warten auf Schriften: ${name}`,
    paint: 'Das Bild wird nicht mehr aktualisiert',
    body: (seconds: number) => `${seconds} s gewartet. Erneut versuchen lädt nur die Vorschau neu; dein Video bleibt unverändert.`,
  },
};
