import type { EditorMessages } from './editor-copy.ts';

export const zhHans: EditorMessages = {
  withNote: (label: string, note: string) => `${label}（${note}）`,
  labeled: (label: string, value: string) => `${label}：${value}`,
  thenNext: (message: string, next: string) => `${message}。${next}`,
  gap: '　',
  undo: '撤销',
  redo: '重做',
  cancel: '取消',
  retry: '重试',
  addClip: '添加片段',
  editor: '编辑器',
  notEditableNow: '视频暂时不能修改',
  timeline: '时间线',
  moveClips: '移动片段',
  moveTrack: '移动轨道',
  importAndAdd: '导入并添加素材',
  seconds2: (seconds: number) => `${seconds.toFixed(2)} 秒`,
  emptyTimeline: '把素材拖进来，或从右侧面板添加',
  hideTrack: (label: string) => `隐藏 ${label}：预览里不显示`,
  showTrack: (label: string) => `显示 ${label}`,
  hideTrackLabel: '隐藏轨道',
  showTrackLabel: '显示轨道',
  unmuteTrack: (label: string) => `取消静音 ${label}`,
  muteTrack: (label: string) => `静音 ${label}`,
  unmuteTrackLabel: '取消静音',
  muteTrackLabel: '静音轨道',
  unlockTrack: (label: string) => `解锁 ${label}`,
  lockTrack: (label: string) => `锁定 ${label}：不能移动、裁切或删除其中的片段`,
  unlockTrackLabel: '解锁轨道',
  lockTrackLabel: '锁定轨道',
  playTip: { play: '播放 · 空格', pause: '暂停 · 空格', replay: '重播' },
  playLabel: { play: '播放', pause: '暂停', replay: '重播' },
  undoTip: (label: string, keys: string) => `撤销「${label}」 ${keys}`,
  redoTip: (label: string, keys: string) => `重做「${label}」 ${keys}`,
  nothingToUndo: '没有可撤销的操作',
  nothingToRedo: '没有可重做的操作',
  splitTip: '在播放头处拆分 · S',
  split: '拆分',
  splitClips: '拆分片段',
  deleteTip: '删除选中 · Delete',
  deleteSelected: '删除选中',
  playhead: '播放头位置',
  totalLength: (duration: string) => `总长 ${duration}`,
  editFailed: (message: string) => `没能修改：${message}`,
  cantOpen: '打不开这个视频',
  openingAria: '正在打开视频',
  opening: '正在打开视频…',
  resizeTimeline: '调整时间线高度',
  previewCanvas: '预览画面',
  previewFailed: '预览画不出来',
  emptyDrag: '把素材拖到时间线上',
  emptyOr: '或从右侧的素材面板添加',
  problemsCount: (n: number) => `${n} 处画不出来`,
  problemsTitle: '这一帧有画不出来的内容',
  rendererFailed: (message: string) => `预览渲染模块没有载入：${message}`,
  spectrumTooLarge: (itemId: string, assetId: string, mb: number) =>
    `声波 ${itemId} 听的素材 ${assetId} 超过 ${mb} MB，预览不分析它的声音；导出照常`,
  stall: {
    loading: '正在载入预览',
    title: '预览卡住了',
    engine: '预览引擎还在载入',
    video: '还在准备这部视频',
    media: (name: string) => `在等媒体：${name}`,
    mediaUnnamed: '在等媒体',
    preparing: '正在准备预览',
    converting: (name: string) => `要先转换才能播放：${name}`,
    convertingUnnamed: '要先转换媒体才能播放',
    once: '只在第一次打开时转换，之后直接播放；原文件不会改动。',
    prepare: (name: string) => `转换媒体没有进展：${name}`,
    prepareUnnamed: '转换媒体没有进展',
    captions: (name: string) => `在等字幕：${name}`,
    captionsUnnamed: '在等字幕',
    fonts: (name: string) => `在等字体：${name}`,
    paint: '画面一直没有更新',
    body: (seconds: number) => `已经等了 ${seconds} 秒。重试只重新载入预览，不会改动视频。`,
  },
};
