import type { ElementsMessages } from './elements-copy.ts';

export const zhHant: ElementsMessages = {
  all: '全部',
  sticker: '貼紙',
  shape: '形狀',
  visualizer: '視覺化',
  progress: '進度',
  wave: '波形',
  myStickers: '我的貼紙',
  builtin: '內建',
  confetti: '彩紙',
  elementsTrack: '元素',
  searchElements: '搜尋元素',
  backToCatalog: '返回元素',
  elements: '元素',
  searchPlaceholder: '搜尋貼紙、形狀、視覺化',
  elementCategories: '元素類別',
  stickerCategories: '貼紙類別',
  visualizerCategories: '視覺化類別',
  dynamicCategories: '動態貼紙類別',
  notFound: (query: string) => `找不到「${query}」`,
  clickHint: '按一下即可在播放頭處建立元素並選取它，然後在畫布上將它拖曳到定位。',
  viewAll: '檢視全部',
  progressBars: '進度列',
  builtinCount: (count: number) => `${count} 種樣式`,
  confettiNote: '10 種演算法粒子樣式 · 長度不限',
  dynamicHint: '品牌庫中的 Lottie 在畫布上會跟隨播放頭；縮圖停在一個影格，滑鼠移上去時才播放。彩紙不是動畫圖片：十種配方逐格運算而成，長度跟隨時間軸上的片段；相同的種子會產生相同的畫面。',
  stickerCount: (count: number) => `${count}`,
  fromBrand: '來自品牌庫',
  uploadToBrand: '在品牌庫中上傳',
  noMine: (query: string) => `「我的貼紙」中沒有「${query}」`,
  readingBrand: '正在載入品牌庫…',
  noOwnDynamic: '你還沒有自己的動態貼紙',
  noOwnStatic: '你還沒有自己的貼紙',
  dynamicAccepts: '品牌庫接受 Lottie 動畫（.json）；圖片貼紙請放在「貼紙」頁面。',
  staticAccepts: '品牌庫接受圖片（PNG、WebP、GIF、JPG）；Lottie 動畫（.json）請放在「動態貼紙」頁面。',
  signpost: '貼紙存放在品牌庫中，任何影片都能使用；放入時會複製一份，之後在品牌庫中的變更不會影響這部影片。',
  addNamed: (name: string) => `新增${name}`,
  text: '文字',
  addTextFailed: (message: string) => `無法新增文字：${message}`,
  textBox: '文字方塊',
  textPresetLabel: (name: string) => `文字 · ${name}`,
  textCategories: '文字預設集類別',
  addTextBox: '新增文字方塊',
  presetCount: (count: number) => `${count}`,
  addPreset: (name: string) => `新增文字預設集「${name}」`,
  layers: (count: number) => `${count} 個圖層`,
  layersInTurn: (name: string, count: number) => `${name} · ${count} 個圖層，依序出現`,
  tabTranscript: '逐字稿',
  tabSubtitle: '字幕',
  tabAiTools: 'AI 工具',
  tabImage: '圖片',
  tabVideo: '影片',
  tabAudio: '音訊',
  tabBrand: '品牌',
  tabProps: '屬性',
  currentTool: '目前的編輯工具',
  videoTools: '影片編輯工具',
  resizePanel: '調整面板大小',
  added: (label: string, start: string, end: string) => `已新增${label} · ${start} → ${end}`,
  undo: '還原',
  lottieFetchFailed: (status: number) => `無法載入 Lottie 檔案（${status}）`,
};
