import type { ElementsMessages } from './elements-copy.ts';

export const zhHans: ElementsMessages = {
  all: '全部',
  sticker: '贴纸',
  shape: '形状',
  visualizer: '可视化',
  progress: '进度',
  wave: '声波',
  myStickers: '我的贴纸',
  builtin: '内置',
  confetti: '彩纸',
  elementsTrack: '元素',
  searchElements: '搜索元素',
  backToCatalog: '返回元素目录',
  elements: '元素',
  searchPlaceholder: '搜索贴纸、形状、可视化',
  elementCategories: '元素分类',
  stickerCategories: '贴纸分类',
  visualizerCategories: '可视化分类',
  dynamicCategories: '动态贴纸分类',
  notFound: (query: string) => `没有找到「${query}」`,
  clickHint: '点一下就在播放头处新建一条元素并选中；落好之后在画布上拖到想要的位置。',
  viewAll: '查看全部',
  progressBars: '进度条',
  builtinCount: (count: number) => `${count} 款`,
  confettiNote: '10 款算法粒子 · 时长任意',
  dynamicHint: '品牌库的 Lottie 落到画面上跟着播放头走，格子停在一帧、鼠标移上去才播。彩纸不是动图：十款配方逐帧算出来，时长随时间线上那一条走；同一枚种子同一幅画面。',
  stickerCount: (count: number) => `${count} 份`,
  fromBrand: '来自品牌库',
  uploadToBrand: '去品牌库上传',
  noMine: (query: string) => `我的贴纸里没有「${query}」`,
  readingBrand: '正在读品牌库…',
  noOwnDynamic: '还没有你自己的动态贴纸',
  noOwnStatic: '还没有你自己的贴纸',
  dynamicAccepts: '品牌库收 Lottie 动画（.json）；图片贴纸归「贴纸」那一页。',
  staticAccepts: '品牌库收图片（PNG、WebP、GIF、JPG）；Lottie 动画（.json）归「动态贴纸」那一页。',
  signpost: '贴纸存在品牌库里，换个视频也能用；放进来是拷一份，之后库里再改不影响这个视频。',
  addNamed: (name: string) => `添加${name}`,
  text: '文字',
  addTextFailed: (message: string) => `没能添加文字：${message}`,
  textBox: '文本框',
  textPresetLabel: (name: string) => `文字 · ${name}`,
  textCategories: '文字预设分类',
  addTextBox: '添加文本框',
  presetCount: (count: number) => `${count} 条`,
  addPreset: (name: string) => `添加文字预设「${name}」`,
  layers: (count: number) => `${count} 层`,
  layersInTurn: (name: string, count: number) => `${name} · ${count} 层，依次出现`,
  tabTranscript: '文稿',
  tabSubtitle: '字幕',
  tabImage: '图片',
  tabVideo: '视频',
  tabAudio: '音频',
  tabBrand: '品牌',
  tabProps: '属性',
  currentTool: '当前编辑工具',
  videoTools: '视频编辑工具',
  resizePanel: '调整面板宽度',
  added: (label: string, start: string, end: string) => `已添加${label} · ${start} → ${end}`,
  undo: '撤销',
  lottieFetchFailed: (status: number) => `读不到 Lottie 文件（${status}）`,
};
