import type { ElementsMessages } from './elements-copy.ts';

export const ja: ElementsMessages = {
  all: 'すべて',
  sticker: 'ステッカー',
  shape: '図形',
  visualizer: 'ビジュアライザ',
  progress: '進行状況',
  wave: '波形',
  myStickers: 'マイステッカー',
  builtin: '組み込み',
  confetti: '紙吹雪',
  elementsTrack: '要素',
  searchElements: '要素を検索',
  backToCatalog: '要素の一覧に戻る',
  elements: '要素',
  searchPlaceholder: 'ステッカー、図形、ビジュアライザを検索',
  elementCategories: '要素のカテゴリ',
  stickerCategories: 'ステッカーのカテゴリ',
  visualizerCategories: 'ビジュアライザのカテゴリ',
  dynamicCategories: 'アニメーションステッカーのカテゴリ',
  notFound: (query: string) => `「${query}」は見つかりませんでした`,
  clickHint: 'クリックすると再生ヘッドの位置に要素を作成して選択します。その後、キャンバス上で目的の位置までドラッグしてください。',
  viewAll: 'すべて表示',
  progressBars: 'プログレスバー',
  builtinCount: (count: number) => `${count} 種類`,
  confettiNote: 'アルゴリズムによるパーティクル 10 種類 · 長さは自由',
  dynamicHint: 'ブランドキットの Lottie はキャンバス上で再生ヘッドに合わせて再生されます。タイルは 1 フレームで止まっていて、マウスを重ねると再生されます。紙吹雪はアニメーション画像ではありません。10 種類のレシピをフレームごとに計算し、長さはタイムライン上のクリップに従います。同じシードなら同じ画面になります。',
  stickerCount: (count: number) => `${count} 個`,
  fromBrand: 'ブランドキットから',
  uploadToBrand: 'ブランドキットでアップロード',
  noMine: (query: string) => `マイステッカーに「${query}」はありません`,
  readingBrand: 'ブランドキットを読み込み中…',
  noOwnDynamic: '自分のアニメーションステッカーはまだありません',
  noOwnStatic: '自分のステッカーはまだありません',
  dynamicAccepts: 'ブランドキットには Lottie アニメーション（.json）を追加できます。画像のステッカーは「ステッカー」ページに入ります。',
  staticAccepts: 'ブランドキットには画像（PNG、WebP、GIF、JPG）を追加できます。Lottie アニメーション（.json）は「アニメーションステッカー」ページに入ります。',
  signpost: 'ステッカーはブランドキットに保存されるため、どの動画でも使えます。配置するとコピーされ、その後キット側で変更してもこの動画には影響しません。',
  addNamed: (name: string) => `${name} を追加`,
  text: 'テキスト',
  addTextFailed: (message: string) => `テキストを追加できませんでした：${message}`,
  textBox: 'テキストボックス',
  textPresetLabel: (name: string) => `テキスト · ${name}`,
  textCategories: 'テキストプリセットのカテゴリ',
  addTextBox: 'テキストボックスを追加',
  presetCount: (count: number) => `${count} 件`,
  addPreset: (name: string) => `テキストプリセット「${name}」を追加`,
  layers: (count: number) => `${count} レイヤー`,
  layersInTurn: (name: string, count: number) => `${name} · ${count} レイヤーが順に表示`,
  tabTranscript: '文字起こし',
  tabSubtitle: '字幕',
  tabImage: '画像',
  tabVideo: '動画',
  tabAudio: '音声',
  tabBrand: 'ブランド',
  tabProps: 'プロパティ',
  currentTool: '現在の編集ツール',
  videoTools: '動画編集ツール',
  resizePanel: 'パネルの幅を調整',
  added: (label: string, start: string, end: string) => `${label} を追加しました · ${start} → ${end}`,
  undo: '取り消す',
  lottieFetchFailed: (status: number) => `Lottie ファイルを読み込めませんでした（${status}）`,
};
