import type { ElementsMessages } from './elements-copy.ts';

export const ko: ElementsMessages = {
  all: '전체',
  sticker: '스티커',
  shape: '도형',
  visualizer: '비주얼라이저',
  progress: '진행률',
  wave: '파형',
  myStickers: '내 스티커',
  builtin: '기본 제공',
  confetti: '색종이',
  elementsTrack: '요소',
  searchElements: '요소 검색',
  backToCatalog: '요소로 돌아가기',
  elements: '요소',
  searchPlaceholder: '스티커, 도형, 비주얼라이저 검색',
  elementCategories: '요소 카테고리',
  stickerCategories: '스티커 카테고리',
  visualizerCategories: '비주얼라이저 카테고리',
  dynamicCategories: '애니메이션 스티커 카테고리',
  notFound: (query: string) => `“${query}”에 대한 결과가 없습니다`,
  clickHint: '클릭하면 재생 헤드 위치에 요소를 만들고 선택합니다. 그런 다음 캔버스에서 원하는 위치로 드래그하세요.',
  viewAll: '모두 보기',
  progressBars: '진행 표시줄',
  builtinCount: (count: number) => `스타일 ${count}개`,
  confettiNote: '알고리즘 파티클 스타일 10개 · 길이 제한 없음',
  dynamicHint: '브랜드 키트의 Lottie는 캔버스에서 재생 헤드를 따라 재생되며, 타일에서는 한 프레임에 멈춰 있다가 마우스를 올리면 재생됩니다. 색종이는 애니메이션 이미지가 아닙니다: 레시피 10개가 프레임마다 계산되고 길이는 타임라인의 클립을 따르며, 같은 시드는 같은 화면을 만듭니다.',
  stickerCount: (count: number) => `${count}개`,
  fromBrand: '브랜드 키트에서',
  uploadToBrand: '브랜드 키트에서 업로드',
  noMine: (query: string) => `내 스티커에 “${query}” 항목이 없습니다`,
  readingBrand: '브랜드 키트 불러오는 중…',
  noOwnDynamic: '아직 직접 추가한 애니메이션 스티커가 없습니다',
  noOwnStatic: '아직 직접 추가한 스티커가 없습니다',
  dynamicAccepts: '브랜드 키트는 Lottie 애니메이션(.json)을 받습니다. 이미지 스티커는 “스티커” 페이지에 들어갑니다.',
  staticAccepts: '브랜드 키트는 이미지(PNG, WebP, GIF, JPG)를 받습니다. Lottie 애니메이션(.json)은 “애니메이션 스티커” 페이지에 들어갑니다.',
  signpost: '스티커는 브랜드 키트에 저장되므로 어떤 영상에서든 쓸 수 있습니다. 배치하면 사본이 만들어지며, 이후 키트에서 바꿔도 이 영상에는 영향이 없습니다.',
  addNamed: (name: string) => `${name} 추가`,
  text: '텍스트',
  addTextFailed: (message: string) => `텍스트를 추가하지 못했습니다: ${message}`,
  textBox: '텍스트 상자',
  textPresetLabel: (name: string) => `텍스트 · ${name}`,
  textCategories: '텍스트 프리셋 카테고리',
  addTextBox: '텍스트 상자 추가',
  presetCount: (count: number) => `${count}개`,
  addPreset: (name: string) => `텍스트 프리셋 “${name}” 추가`,
  layers: (count: number) => `레이어 ${count}개`,
  layersInTurn: (name: string, count: number) => `${name} · 레이어 ${count}개, 차례로 나타남`,
  tabTranscript: '전사본',
  tabSubtitle: '자막',
  tabAiTools: 'AI 도구',
  tabImage: '이미지',
  tabVideo: '영상',
  tabAudio: '오디오',
  tabBrand: '브랜드',
  tabProps: '속성',
  currentTool: '현재 편집 도구',
  videoTools: '영상 편집 도구',
  resizePanel: '패널 크기 조정',
  added: (label: string, start: string, end: string) => `${label} 추가함 · ${start} → ${end}`,
  undo: '실행 취소',
  lottieFetchFailed: (status: number) => `Lottie 파일을 불러오지 못했습니다(${status})`,
};
