import type { ElementsMessages } from './elements-copy.ts';

export const de: ElementsMessages = {
  all: "Alle",
  sticker: "Sticker",
  shape: "Formen",
  visualizer: "Visualisierungen",
  progress: "Fortschritt",
  wave: "Wellenformen",
  myStickers: "Meine Sticker",
  builtin: "Eingebaut",
  confetti: "Konfetti",
  elementsTrack: "Elemente",
  searchElements: "Elemente suchen",
  backToCatalog: "Zurück zu Elementen",
  elements: "Elemente",
  searchPlaceholder: "Sticker, Formen, Visualisierungen suchen",
  elementCategories: "Elementkategorien",
  stickerCategories: "Stickerkategorien",
  visualizerCategories: "Visualisierungskategorien",
  dynamicCategories: "Kategorien animierter Sticker",
  notFound: (query: string) => `Keine Treffer für „${query}“`,
  clickHint: "Klicken, um am Abspielkopf ein Element zu erstellen und auszuwählen; anschließend auf der Arbeitsfläche an die gewünschte Position ziehen.",
  viewAll: "Alle anzeigen",
  progressBars: "Fortschrittsbalken",
  builtinCount: (count: number) => `${count} Stile`,
  confettiNote: "10 algorithmische Partikelstile · beliebige Länge",
  dynamicHint: "Lottie aus dem Marken-Kit folgt dem Abspielkopf auf der Arbeitsfläche; Kacheln halten einen Frame und spielen beim Darüberfahren ab. Konfetti ist kein animiertes Bild: Die zehn Varianten werden Frame für Frame berechnet, und ihre Länge folgt dem Clip in der Zeitleiste; derselbe Seed liefert dasselbe Bild.",
  stickerCount: (count: number) => `${count}`,
  fromBrand: "Aus dem Marken-Kit",
  uploadToBrand: "Im Marken-Kit hochladen",
  noMine: (query: string) => `Kein „${query}“ unter Meine Sticker`,
  readingBrand: "Marken-Kit wird geladen…",
  noOwnDynamic: "Noch keine eigenen animierten Sticker",
  noOwnStatic: "Noch keine eigenen Sticker",
  dynamicAccepts: "Das Marken-Kit akzeptiert Lottie-Animationen (.json); Bildsticker gehören auf die Seite „Sticker“.",
  staticAccepts: "Das Marken-Kit akzeptiert Bilder (PNG, WebP, GIF, JPG); Lottie-Animationen (.json) gehören auf die Seite „Animierte Sticker“.",
  signpost: "Sticker liegen im Marken-Kit, damit jedes Video sie verwenden kann. Beim Platzieren wird eine Kopie erstellt; spätere Änderungen im Kit beeinflussen dieses Video nicht.",
  addNamed: (name: string) => `Hinzufügen: ${name}`,
  text: "Text",
  addTextFailed: (message: string) => `Text konnte nicht hinzugefügt werden: ${message}`,
  textBox: "Textfeld",
  textPresetLabel: (name: string) => `Text · ${name}`,
  textCategories: "Textvoreinstellungskategorien",
  addTextBox: "Textfeld hinzufügen",
  presetCount: (count: number) => `${count}`,
  addPreset: (name: string) => `Textvoreinstellung hinzufügen: „${name}“`,
  layers: (count: number) => `${count} Ebenen`,
  layersInTurn: (name: string, count: number) => `${name} · ${count} Ebenen, nacheinander erscheinend`,
  tabTranscript: "Transkript",
  tabSubtitle: "Untertitel",
  tabImage: "Bilder",
  tabVideo: "Video",
  tabAudio: "Audio",
  tabBrand: "Marke",
  tabProps: "Eigenschaften",
  currentTool: "Aktuelles Bearbeitungswerkzeug",
  videoTools: "Videobearbeitungswerkzeuge",
  resizePanel: "Bereichsgröße ändern",
  added: (label: string, start: string, end: string) => `Hinzugefügt: ${label} · ${start} → ${end}`,
  undo: "Rückgängig machen",
  lottieFetchFailed: (status: number) => `Lottie-Datei konnte nicht geladen werden (${status})`,
};
