import type { FontMessages } from './font-copy.ts';

export const pl: FontMessages = {
  cancelDownload: "Anuluj pobieranie",
  searchFonts: "Szukaj czcionek",
  searchFontsPlaceholder: "Szukaj czcionek…",
  category: "Kategoria",
  allCategories: "Wszystkie kategorie",
  script: "Pismo",
  allScripts: "Wszystkie pisma",
  listFailed: "Nie udało się uzyskać listy czcionek",
  listLoading: "Pobieranie listy czcionek…",
  noMatch: "Brak pasujących czcionek",
  downloadable: (count: string) => ` · ${count} dostępnych do pobrania`,
  use: (family: string) => `Użyj ${family}`,
  download: "Pobierz",
  downloadFamily: (family: string) => `Najpierw pobierz ${family}`,
  cancelDownloadFamily: (family: string) => `Anuluj pobieranie ${family}`,
  retryTip: (message: string) => `Spróbuj ponownie · ${message}`,
  retryFamily: (family: string) => `Spróbuj pobrać ${family} ponownie`,
  detailsTip: "Szczegóły czcionki i licencja",
  detailsFamily: (family: string) => `${family} – szczegóły i licencja`,
  skipThis: "Pomiń tę",
  cancelAllTip: "Anuluj wszystko · użyj na razie czcionek zastępczych",
  cancelAll: "Anuluj wszystko",
  collapse: "Ukryj",
  view: "Pokaż",
  gotIt: "Rozumiem",
  settings: "Ustawienia",
  progress: "Postęp pobierania czcionki",
  retry: "Spróbuj ponownie",
  systemFont: "Czcionka systemowa",
  pingFang: "PingFang SC",
  songti: "Songti SC",
  kaiti: "Kaiti SC",
  font: "Czcionka",
  fontValue: (label: string, font: string) => `${label}: ${font}`,
  backToList: "Wróć do listy czcionek",
  deleteDownloaded: "Usuń pobrane pliki",
  useThis: "Użyj tej czcionki",
};
