import type { FontMessages } from './font-copy.ts';

export const ko: FontMessages = {
  cancelDownload: '다운로드 취소',
  searchFonts: '글꼴 검색',
  searchFontsPlaceholder: '글꼴 검색…',
  category: '카테고리',
  allCategories: '모든 카테고리',
  script: '문자 체계',
  allScripts: '모든 문자 체계',
  listFailed: '글꼴 목록을 가져오지 못했습니다',
  listLoading: '글꼴 목록 가져오는 중…',
  noMatch: '일치하는 글꼴이 없습니다',
  downloadable: (count: string) => ` · 다운로드 가능 ${count}개`,
  use: (family: string) => `${family} 사용`,
  download: '다운로드',
  downloadFamily: (family: string) => `${family} 다운로드`,
  cancelDownloadFamily: (family: string) => `${family} 다운로드 취소`,
  retryTip: (message: string) => `다시 시도 · ${message}`,
  retryFamily: (family: string) => `${family} 다운로드 다시 시도`,
  detailsTip: '글꼴 세부 정보와 라이선스',
  detailsFamily: (family: string) => `${family} 세부 정보와 라이선스`,
  skipThis: '이 글꼴 건너뛰기',
  cancelAllTip: '모두 취소 · 우선 대체 글꼴 사용',
  cancelAll: '모두 취소',
  collapse: '숨기기',
  view: '보기',
  gotIt: '확인',
  settings: '설정',
  progress: '글꼴 다운로드 진행률',
  retry: '다시 시도',
  systemFont: '시스템 글꼴',
  pingFang: 'PingFang SC',
  songti: 'Songti SC',
  kaiti: 'Kaiti SC',
  font: '글꼴',
  fontValue: (label: string, font: string) => `${label}: ${font}`,
  backToList: '글꼴 목록으로 돌아가기',
  deleteDownloaded: '다운로드한 파일 삭제',
  useThis: '이 글꼴 사용',
};
