import type { FontMessages } from './font-copy.ts';

export const ja: FontMessages = {
  cancelDownload: 'ダウンロードをキャンセル',
  searchFonts: 'フォントを検索',
  searchFontsPlaceholder: 'フォントを検索…',
  category: 'カテゴリ',
  allCategories: 'すべてのカテゴリ',
  script: '文字体系',
  allScripts: 'すべての文字体系',
  listFailed: 'フォントの一覧を取得できませんでした',
  listLoading: 'フォントの一覧を取得中…',
  noMatch: '一致するフォントはありません',
  downloadable: (count: string) => ` · ${count} 個ダウンロード可能`,
  use: (family: string) => `${family} を使用`,
  download: 'ダウンロード',
  downloadFamily: (family: string) => `${family} をダウンロード`,
  cancelDownloadFamily: (family: string) => `${family} のダウンロードをキャンセル`,
  retryTip: (message: string) => `再試行 · ${message}`,
  retryFamily: (family: string) => `${family} のダウンロードを再試行`,
  detailsTip: 'フォントの詳細とライセンス',
  detailsFamily: (family: string) => `${family} の詳細とライセンス`,
  skipThis: 'これをスキップ',
  cancelAllTip: 'すべてキャンセル · ひとまず代替フォントで表示',
  cancelAll: 'すべてキャンセル',
  collapse: '閉じる',
  view: '表示',
  gotIt: 'OK',
  settings: '設定',
  progress: 'フォントのダウンロードの進行状況',
  retry: '再試行',
  systemFont: 'システムフォント',
  pingFang: 'PingFang SC',
  songti: 'Songti SC',
  kaiti: 'Kaiti SC',
  font: 'フォント',
  fontValue: (label: string, font: string) => `${label}：${font}`,
  backToList: 'フォントの一覧に戻る',
  deleteDownloaded: 'ダウンロードしたファイルを削除',
  useThis: 'このフォントを使用',
};
