import type { FontMessages } from './font-copy.ts';

export const fr: FontMessages = {
  cancelDownload: "Annuler le téléchargement",
  searchFonts: "Rechercher des polices",
  searchFontsPlaceholder: "Rechercher des polices…",
  category: "Catégorie",
  allCategories: "Toutes les catégories",
  script: "Écriture",
  allScripts: "Toutes les écritures",
  listFailed: "Impossible de récupérer la liste des polices",
  listLoading: "Récupération de la liste des polices…",
  noMatch: "Aucune police correspondante",
  downloadable: (count: string) => ` · ${count} téléchargeables`,
  use: (family: string) => `Utiliser ${family}`,
  download: "Télécharger",
  downloadFamily: (family: string) => `Télécharger ${family}`,
  cancelDownloadFamily: (family: string) => `Annuler le téléchargement de ${family}`,
  retryTip: (message: string) => `Réessayer · ${message}`,
  retryFamily: (family: string) => `Réessayer le téléchargement de ${family}`,
  detailsTip: "Détails et licence de la police",
  detailsFamily: (family: string) => `${family} : détails et licence`,
  skipThis: "Ignorer celle-ci",
  cancelAllTip: "Tout annuler · utiliser les polices de remplacement",
  cancelAll: "Tout annuler",
  collapse: "Masquer",
  view: "Voir",
  gotIt: "Je l'ai compris",
  settings: "Réglages",
  progress: "Progression du téléchargement des polices",
  retry: "Réessayer",
  systemFont: "Police système",
  pingFang: "PingFang SC",
  songti: "Songti SC",
  kaiti: "Kaiti SC",
  font: "Police",
  fontValue: (label: string, font: string) => `${label} : ${font}`,
  backToList: "Retour à la liste des polices",
  deleteDownloaded: "Supprimer les fichiers téléchargés",
  useThis: "Utiliser cette police",
};
