import type { FontMessages } from './font-copy.ts';

export const de: FontMessages = {
  cancelDownload: "Download abbrechen",
  searchFonts: "Schriftarten durchsuchen",
  searchFontsPlaceholder: "Schriften suchen…",
  category: "Kategorie",
  allCategories: "Alle Kategorien",
  script: "Schriftsystem",
  allScripts: "Alle Schriftsysteme",
  listFailed: "Schriftliste konnte nicht abgerufen werden",
  listLoading: "Schriftliste wird abgerufen…",
  noMatch: "Keine passenden Schriften",
  downloadable: (count: string) => ` · ${count} herunterladbar`,
  use: (family: string) => `Verwenden: ${family}`,
  download: "Herunterladen",
  downloadFamily: (family: string) => `Herunterladen: ${family}`,
  cancelDownloadFamily: (family: string) => `Download abbrechen: ${family}`,
  retryTip: (message: string) => `Erneut versuchen · ${message}`,
  retryFamily: (family: string) => `Erneut herunterladen: ${family}`,
  detailsTip: "Schriftdetails und Lizenz",
  detailsFamily: (family: string) => `${family}: Details und Lizenz`,
  skipThis: "Diese überspringen",
  cancelAllTip: "Alle abbrechen · vorerst Ersatzschriften verwenden",
  cancelAll: "Alle abbrechen",
  collapse: "Verstecken",
  view: "Ansehen",
  gotIt: "Verstanden",
  settings: "Einstellungen",
  progress: "Schriftdownload-Fortschritt",
  retry: "Erneut versuchen",
  systemFont: "Systemschrift",
  pingFang: "PingFang SC",
  songti: "Songti SC",
  kaiti: "Kaiti SC",
  font: "Schrift",
  fontValue: (label: string, font: string) => `${label}: ${font}`,
  backToList: "Zurück zur Schriftliste",
  deleteDownloaded: "Heruntergeladene Dateien löschen",
  useThis: "Diese Schrift verwenden",
};
