import type { FontMessages } from './font-copy.ts';

export const zhHans: FontMessages = {
  cancelDownload: '取消下载',
  searchFonts: '搜索字体',
  searchFontsPlaceholder: '搜索字体…',
  category: '分类',
  allCategories: '全部分类',
  script: '文字',
  allScripts: '全部文字',
  listFailed: '字体列表没有取到',
  listLoading: '正在取字体列表…',
  noMatch: '没有匹配的字体',
  downloadable: (count: string) => ` · 可下载 ${count} 个`,
  use: (family: string) => `用 ${family}`,
  download: '下载',
  downloadFamily: (family: string) => `下载 ${family}`,
  cancelDownloadFamily: (family: string) => `取消下载 ${family}`,
  retryTip: (message: string) => `重试 · ${message}`,
  retryFamily: (family: string) => `重试下载 ${family}`,
  detailsTip: '字体详情与许可',
  detailsFamily: (family: string) => `${family} 的详情与许可`,
  skipThis: '跳过这个',
  cancelAllTip: '全部取消 · 先用回退字体显示',
  cancelAll: '全部取消',
  collapse: '收起',
  view: '查看',
  gotIt: '知道了',
  settings: '设置',
  progress: '字体下载进度',
  retry: '重试',
  systemFont: '系统字体',
  pingFang: '苹方',
  songti: '宋体',
  kaiti: '楷体',
  font: '字体',
  fontValue: (label: string, font: string) => `${label}：${font}`,
  backToList: '回到字体列表',
  deleteDownloaded: '删除下载的文件',
  useThis: '用这个字体',
};
