import type { InspectorMessages } from './inspector-copy.ts';

export const ptBR: InspectorMessages = {
  text: "Texto",
  style: "Estilo",
  textSchema: (schema: string) => `O estilo deste texto é ${schema}; ainda não pode ser editado aqui.`,
  shape: "Formas",
  fill: "Preenchimento",
  color: "Cor",
  fillColor: "Cor de preenchimento",
  opacity: "Opacidade",
  stroke: "Contorno",
  strokeColor: "Cor do contorno",
  strokeWidth: "Largura",
  corner: "Raio do canto",
  titleAnimatedSticker: "Adesivo animado",
  titleSticker: "Adesivo",
  titleCounter: "Contador",
  titleText: "Editar texto",
  titleProgress: "Barra de progresso",
  titleVisualizer: "Forma de onda",
  titleConfetti: "Confete",
  titleDraw: "Desenho",
  titlePlaceholder: "Espaço reservado",
  titleWhiteboard: "Quadro branco",
  titleComposition: "Composição",
  appearance: "Aparência",
  params: "Parâmetros",
  paramsReadOnly: (title: string) => `${title}: parâmetros ainda não editáveis aqui.`,
  compositionReadOnly: "Parâmetros de composição por código têm validação própria e ainda não podem ser editados aqui.",
  restoreColors: "Restaurar cores originais",
  replaceColor: (source: string) => `Substituir ${source}`,
  stickerUnknown: (id: string) => `O template de adesivo ${id || "(sem templateId)"} não é reconhecido.`,
  loopLoop: "Repetição",
  loopOnce: "Reproduzir uma vez",
  loopHold: "Manter",
  playback: "Reproduzir",
  playMode: "Modo de reprodução",
  countdown: "Contagem regressiva",
  countup: "Contagem crescente",
  formatS: "Segundos",
  formatMmss: "Min:Sec",
  formatHmmss: "Hr:Min:Sec",
  timing: "Tempo",
  timingMode: "Modo de tempo",
  clockFace: "Formato do relógio",
  cfStyle: "Estilo",
  cfStyleTile: (name: string) => `Estilo: ${name}, clique para mudar`,
  cfBurst: "Rajada",
  cfContinuous: "Contínuo",
  cfMoreShapes: (n: number) => ` e ${n - 1} a mais`,
  cfChangeStyle: "Mudar estilo",
  cfStyles: "Estilos de confete",
  cfReset: "Voltar à receita",
  cfColorN: (n: number) => `Cor ${n}`,
  cfRemoveColorN: (n: number) => `Remover cor ${n}`,
  cfConfettiColorN: (n: number) => `Cor do confete ${n}`,
  cfAddColor: "Adicionar uma cor",
  cfColorsNote: "As partículas alternam entre estas cores pela semente; com uma só cor o confete fica monocromático.",
  cfShapes: "Formas do confete",
  cfMotionAside: "1× usa a receita original",
  cfMotion: "Movimento das partículas",
  cfCount: "Por rajada",
  cfUnit: "unid.",
  cfDensity: "Densidade",
  cfRateUnit: "unid./s",
  cfSize: "Tamanho",
  cfSpeed: "Velocidade",
  cfGravity: "Gravidade",
  cfWind: "Vento",
  cfDrift: "Deriva",
  cfSpin: "Girar",
  cfOpacity: "Opacidade das partículas",
  cfEmitAsideBurst: "A rajada b sai em b × intervalo",
  cfEmitAsideContinuous: "Nascimentos por segundo = densidade",
  cfEmit: "Emissão",
  cfMode: "Modo",
  cfEmitMode: "Modo de emissão",
  cfInterval: "Intervalo",
  cfIntervalZero: "Intervalo 0 = uma única rajada; o quadro fica vazio quando as partículas somem.",
  cfSettle: "Assentar antes do fim",
  cfSettleOn: "Para de emitir uma vida antes do fim",
  cfSettleOff: "Continua até o fim",
  cfOrigin: "Origem",
  cfOriginCustom: "Personalizado",
  cfOriginRecipeMulti: (n: number) => `Da receita · ${n} emissores`,
  cfOriginRecipe: "Segue a receita",
  cfOriginX: "Origem X",
  cfOriginY: "Origem Y",
  cfAngle: "Direção",
  cfSpread: "Abertura",
  cfAngleNote: "−90° aponta para cima, 0° à direita; a origem pode ficar fora da tela (−20% … 120%).",
  cfRandomAside: "Mesma seed, mesma imagem",
  cfRandom: "Aleatoriedade",
  cfSeed: "Semente",
  cfReseed: "Outra",
  current: (name: string) => `${name} (atual)`,
  cfCatalogNote: "Trocar estilo restaura sua receita (cores, formas, movimento e emissão); só a seed permanece, mantendo as mesmas partículas ao trocar.",
  alignLeft: "Esquerda",
  alignCenter: "Médio",
  alignRight: "Certo",
  fontSize: "Tamanho",
  textColor: "Cor do texto",
  bold: "Negrito",
  italic: "Itálico",
  underline: "Sublinhado",
  align: "Alinhar",
  lineHeight: "Entrelinha",
  letterSpacing: "Espaçamento entre letras",
  background: "faixa de fundo",
  backgroundPlate: "Forma de fundo",
  backgroundColor: "Cor de fundo",
  padding: "Preenchimento",
  glow: "Brilho",
  glowColor: "Cor do brilho",
  intensity: "Intensidade",
  range: "Escopo",
  glowShadowNote: "Brilho e sombra compartilham efeito; com ambos ativados, só o brilho é desenhado.",
  shadow: "Sombra",
  shadowColor: "Cor da sombra",
  distance: "Distância",
  blur: "Desfoque",
  angle: "Ângulo",
  clipLocked: "Clipe bloqueado; desbloqueie para mudar.",
  trackLocked: "Faixa bloqueada; desbloqueie na linha do tempo para mudar.",
  unlock: "Desbloquear",
  custom: "Personalizado",
  speedAside: "Duração recalculada com a nova velocidade",
  speedChange: "Velocidade",
  speedRate: "Velocidade",
  speedNote: "Se o clipe ampliado cobrir os seguintes, não os empurra; a alteração é rejeitada.",
  sound: "Voz",
  mute: "Silenciar",
  volume: "Volume",
  fadeIn: "Surgir",
  fadeOut: "Desvanecer",
  seconds: "Segundos",
  timeAside: "Alinha ao quadro mais próximo",
  time: "Horário",
  start: "Início",
  startAtPlayhead: "Definir início no indicador de reprodução",
  end: "Fim",
  endAtPlayhead: "Definir fim no indicador de reprodução",
  duration: "Duração",
  timecode: "Código de tempo",
  sourceIn: "Início da origem",
  track: "Faixa",
  editFps: (fps: string) => `Taxa de quadros da edição ${fps}`,
  asset: "Mídia",
  revision: (revision: number | string) => `Revisão ${revision}`,
  secondsInputError: "Informe segundos (ex.: 10.5) ou “min:sec”",
  secondsField: (label: string) => `${label} (s)`,
  deleteClip: "Excluir clipe",
  trPrevious: "Unir ao clipe anterior",
  trNext: "Unir ao próximo clipe",
  trHintJoinedIn: "Transição do anterior a este; ambos precisam de mídia extra além do corte.",
  trHintJoinedOut: "Transição deste ao próximo; ambos precisam de mídia extra além do corte.",
  trHintIn: "Transição das camadas inferiores a este clipe.",
  trHintOut: "Transição deste clipe às camadas inferiores.",
  transition: "Transição",
  trSlot: "Posição da transição",
  trEffects: "Efeitos de transição",
  trUnknown: (kind: string) => `A transição desta borda é ${kind}, não reconhecida; prévia em corte seco. Escolher outra substitui.`,
  direction: "Direção",
  overlayColor: "Cor de sobreposição",
  easing: "Suavização",
  trJoin: "Unir",
  trCrossfade: "Crossfade de áudio",
  trApplyNote: (hint: string) => `${hint} Escolhas imediatas e desfazíveis.`,
  pageVideo: "Editar vídeo",
  pageImage: "Editar imagem",
  pageAudio: "Editar áudio",
  pageCaption: "Propriedades da legenda",
  selectedClips: (n: number) => `${n} clipes selecionados`,
  videoProperties: "Propriedades do vídeo",
  backToVideo: "Voltar às propriedades do vídeo",
  created: (n: number) => `Criado ${n}`,
  updated: (n: number) => `Atualizado ${n}`,
  deleted: (n: number) => `Excluídas ${n}`,
  lastChange: "Última alteração",
  lastChangeLabel: (label: string) => `Última alteração · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `Revisão ${from} → ${to}`,
  changedObjects: (parts: string[]) => `Objetos: ${parts.join(" · ")}`,
  durationChange: (from: string, to: string) => `Duração do vídeo ${from} → ${to}`,
  undoAvailable: "Desfazível (⌘Z ou esta etapa no Histórico)",
  undoUnavailable: (reason: string) => `Não pode ser desfeito: ${reason}`,
  unknownReason: "motivo desconhecido",
  requestedSeconds: (value: number | string) => `${value} s`,
  requestedFrame: (value: number | string) => `quadro ${value}`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `Solicitado ${requested} → real ${actual} (quadro ${frame}, ${fps})`,
  shiftMs: (ms: string) => `, diferença de ${ms} ms`,
  geometry: "Geometria",
  anchor: "Âncora",
  measureFrom: (name: string) => `Medir de ${name}`,
  width: "Largura",
  height: "Alto",
  lockRatio: "Travar proporção",
  snapToPin: "Alinhar à âncora",
  fullWidth: "Largura total",
  fullHeight: "Altura total",
  fitCanvas: "Ajustar à tela",
  fillCanvas: "Preencher a tela",
  rotation: "Girar",
  flip: "Virar",
  horizontal: "Horizontal",
  vertical: "Verticais",
  percentField: (label: string) => `${label} (%)`,
  rangeAside: "Intervalo invertido = barra regressiva",
  progressRange: "Alcance",
  rangeStart: "Origem",
  rangeEnd: "Fim",
  controls: "Controle",
  minimum: "Mínimo",
  maximum: "Máximo",
  smoothing: "Suavização",
  noColorControls: (label: string) => `“${label}” não tem controles de cor; suas cores vêm do estilo.`,
  styleTile: (label: string, count: number) => `Estilo: ${label}, ${count} estilos, clique para escolher`,
  styleCount: (count: number) => `${count} estilos · clique para escolher`,
  waveStyles: "Estilos de onda sonora",
  progressStyles: "Estilos de barra de progresso",
  waveNote: "Controles conforme o estilo: Osciloscópio e Onda circular sem dB; Área espectral / Matriz de pontos / Anel pulsante / Fita usam duas cores.",
  progressNote: "Controles conforme o estilo: bordas arco-íris sem cores; os dois arco-íris móveis só têm cor de “Fundo”.",
  silentTrack: "(faixa sem áudio)",
  ducking: "Reduzir áudio original",
  duckUnder: "Sob",
  duckUnderTrack: "Faixa que dispara a redução",
  duckSeveral: "Várias faixas ou clipes",
  duckSpeech: "Esta regra segue trechos de fala; escolher uma faixa faz seguir apenas ela.",
  duckItems: "Esta regra segue várias faixas ou clipes; escolher uma faz seguir apenas ela.",
  duckDepth: "Abaixar em",
  advanced: "Avançado",
  attack: "Descida",
  release: "Retorno",
  usingDefaults: "Usando padrões",
  usingYours: "Usando seus valores",
  restoreDefaults: "Restaurar padrões",
  duckShared: "A regra também reduz outros clipes; mudanças se aplicam a todos, desativar desativa a regra inteira.",
  duckNothing: "Sem outra faixa com áudio; coloque música, dublagem ou narração em outra faixa primeiro.",
  black: "Preto",
  aspect: "Proporção",
  aspectNote: "O lado menor permanece; posições em percentuais fazem os clipes seguirem a tela, e o que preenchia continua preenchendo.",
  canvasBackground: "Fundo",
  backdrop: "Fundo",
  canvasColor: "Cor da tela",
  specs: "Especificações",
  size: "Tamanho",
  frameRate: "Taxa de quadros",
  contents: "Conteúdo",
  contentsCount: (tracks: number, clips: number, assets: number) => `${tracks} faixas · ${clips} clipes · ${assets} mídias`,
  videoNote: "Selecione clipes para ver propriedades. Segure ⇧ ou ⌘ ao clicar para seleção múltipla.",
  colorAdjust: "Correção de cor",
  dropShadow: "Sombra projetada",
  resetAll: "Redefinir tudo",
  effects: "Efeitos",
  radius: "Raio",
  offsetX: "Deslocamento horizontal",
  offsetY: "Deslocamento vertical",
  dropShadowColor: "Cor da sombra",
  widthLabel: "Largura",
  effectsNote: "Sombra e contorno seguem bordas transparentes; em vídeo opaco, o retângulo. Comprimentos em pixels com lado menor 540.",
  unknownEffects: (kinds: string[]) => `Estes efeitos não têm controles aqui: ${kinds.join(", ")}. Mantidos como estão; prévia ignora, verificação antes da exportação lista.`,
  overMax: (current: string, max: string) => `Atual ${current} · máximo do controle ${max}`,
  exactInput: (label: string) => `Informar valor exato de ${label}`,
  withUnit: (label: string, unit: string) => `${label} (${unit})`,
  colorValue: (label: string, value: string) => `${label}: ${value}`,
  saturationBrightness: (label: string) => `${label} saturação e brilho`,
  commonColors: "Cores comuns",
  fitContain: "Conter",
  fitCover: "Capa",
  picture: "Visual",
  fit: "Ajustar",
  plateNote: "O clipe tem fundo ou cantos arredondados que a prévia ainda não mostra.",
  orderTranslationFirst: "Topo da tradução",
  orderOriginalFirst: "Topo original",
  editCaptionStyle: "Editar estilo de legendas",
  loadingCaptionStyle: "Carregando estilo de legendas…",
  captionSchema: (schema: string) => `Este estilo de legendas é ${schema}; ainda não pode ser editado aqui.`,
  noSchema: "(sem schema)",
  defaultStyle: "Estilo padrão",
  textStyle: "Estilo de texto",
  position: "Posição",
  horizontalPos: "Horizontal",
  bilingual: "Bilíngue",
  order: "Ordem",
  bilingualOrder: "Ordem bilíngue",
  lineGap: "Espaçamento entre linhas",
  displayAside: "Relativo ao início e fim da frase",
  display: "Exibição",
  lead: "Mais cedo",
  lag: "Mais tarde",
  punctuation: "Pontuação",
  punctToSpace: "Substituir vírgulas e pontos por espaços",
};
