import type { InspectorMessages } from './inspector-copy.ts';

export const fr: InspectorMessages = {
  text: "Texte",
  style: "Style",
  textSchema: (schema: string) => `Le style de ce texte est ${schema} ; il ne peut pas encore être modifié ici.`,
  shape: "Forme",
  fill: "Remplissage",
  color: "Couleur",
  fillColor: "Couleur de remplissage",
  opacity: "Opacité",
  stroke: "Contour",
  strokeColor: "Couleur du contour",
  strokeWidth: "Largeur",
  corner: "Rayon d'angle",
  titleAnimatedSticker: "Sticker animé",
  titleSticker: "Autocollant",
  titleCounter: "Compteur",
  titleText: "Modifier le texte",
  titleProgress: "Barre de progression",
  titleVisualizer: "Forme d'onde",
  titleConfetti: "Confettis",
  titleDraw: "En cours",
  titlePlaceholder: "Emplacement réservé",
  titleWhiteboard: "Tableau blanc",
  titleComposition: "Composition",
  appearance: "Apparence",
  params: "Réglages",
  paramsReadOnly: (title: string) => `${title} : paramètres non modifiables ici pour l’instant.`,
  compositionReadOnly: "Les paramètres de composition par code ont leurs propres règles de validation et ne sont pas encore modifiables ici.",
  restoreColors: "Restaurer les couleurs originales",
  replaceColor: (source: string) => `Remplacer ${source}`,
  stickerUnknown: (id: string) => `Le modèle de sticker ${id || "(aucun templateId)"} n’est pas reconnu.`,
  loopLoop: "Boucle",
  loopOnce: "Lire une fois",
  loopHold: "Maintien",
  playback: "Lecture",
  playMode: "Mode de lecture",
  countdown: "Compte à rebours",
  countup: "Compter",
  formatS: "Secondes",
  formatMmss: "Min:Sec",
  formatHmmss: "Hr:Min:Sec",
  timing: "Calendrier",
  timingMode: "Mode temporel",
  clockFace: "Format d’horloge",
  cfStyle: "Style",
  cfStyleTile: (name: string) => `Style : ${name}, cliquez pour changer`,
  cfBurst: "Salve",
  cfContinuous: "Continu",
  cfMoreShapes: (n: number) => ` et ${n - 1} de plus`,
  cfChangeStyle: "Changer le style",
  cfStyles: "Styles de confettis",
  cfReset: "Rétablir la recette",
  cfColorN: (n: number) => `Couleur ${n}`,
  cfRemoveColorN: (n: number) => `Retirer la couleur ${n}`,
  cfConfettiColorN: (n: number) => `Couleur de confettis ${n}`,
  cfAddColor: "Ajouter une couleur",
  cfColorsNote: "Les particules prennent ces couleurs selon la graine ; gardez une seule couleur pour des confettis unis.",
  cfShapes: "Formes des confettis",
  cfMotionAside: "1× utilise la recette telle quelle",
  cfMotion: "Mouvement des particules",
  cfCount: "Par salve",
  cfUnit: "unités",
  cfDensity: "Densité",
  cfRateUnit: "unités/s",
  cfSize: "Taille",
  cfSpeed: "Vitesse",
  cfGravity: "Gravité",
  cfWind: "Vent",
  cfDrift: "Dérive",
  cfSpin: "Rotation",
  cfOpacity: "Opacité des particules",
  cfEmitAsideBurst: "Explosion b à b × intervalle",
  cfEmitAsideContinuous: "Naissances par seconde = densité",
  cfEmit: "Émission",
  cfMode: "Mode",
  cfEmitMode: "Mode d’émission",
  cfInterval: "Intervalle",
  cfIntervalZero: "Intervalle 0 = une seule émission ; écran vide après la durée de vie des particules.",
  cfSettle: "Vider avant la fin",
  cfSettleOn: "Aucune nouvelle particule pendant la dernière durée de vie avant la fin",
  cfSettleOff: "Continuer jusqu’à la fin",
  cfOrigin: "Origine",
  cfOriginCustom: "Personnalisé",
  cfOriginRecipeMulti: (n: number) => `Depuis la recette · ${n} émetteurs`,
  cfOriginRecipe: "Depuis la recette",
  cfOriginX: "Origine X",
  cfOriginY: "Origine Y",
  cfAngle: "Direction",
  cfSpread: "Ouverture",
  cfAngleNote: "−90° pointe vers le haut et 0° vers la droite ; origine possible hors écran (−20 % … 120 %).",
  cfRandomAside: "Même graine, même image",
  cfRandom: "Aléatoire",
  cfSeed: "Graine",
  cfReseed: "Autre",
  current: (name: string) => `${name} (actuel)`,
  cfCatalogNote: "Changer de style rétablit sa recette (couleurs, formes, mouvement et émission changent) ; seule la graine reste, pour conserver les mêmes particules à l’écran.",
  alignLeft: "Gauche",
  alignCenter: "Centre",
  alignRight: "À droite",
  fontSize: "Taille",
  textColor: "Couleur du texte",
  bold: "Gras",
  italic: "Italique",
  underline: "Souligné",
  align: "Alignement",
  lineHeight: "Hauteur de ligne",
  letterSpacing: "Espacement des lettres",
  background: "Fond",
  backgroundPlate: "Forme de fond",
  backgroundColor: "Couleur de fond",
  padding: "Rembourrage",
  glow: "Lueur",
  glowColor: "Couleur de lueur",
  intensity: "Intensité",
  range: "Gamme",
  glowShadowNote: "Lueur et ombre partagent un effet ; si les deux sont activées, seule la lueur est dessinée.",
  shadow: "Ombre",
  shadowColor: "Couleur d’ombre",
  distance: "Distance",
  blur: "Flou",
  angle: "Angle",
  clipLocked: "Ce clip est verrouillé ; déverrouillez-le pour modifier.",
  trackLocked: "Sa piste est verrouillée ; déverrouillez-la sur la timeline pour modifier.",
  unlock: "Déverrouiller",
  custom: "Personnalisé",
  speedAside: "Durée recalculée à la nouvelle vitesse",
  speedChange: "Vitesse",
  speedRate: "Vitesse",
  speedNote: "Si le clip allongé recouvre les suivants, il ne les repousse pas ; la modification est refusée.",
  sound: "Audio",
  mute: "Couper le son",
  volume: "Volume",
  fadeIn: "Fondu entrant",
  fadeOut: "Fondu sortant",
  seconds: "s",
  timeAside: "S’aligne sur l’image la plus proche",
  time: "Date",
  start: "Début",
  startAtPlayhead: "Définir le début à la tête de lecture",
  end: "Fin",
  endAtPlayhead: "Définir la fin à la tête de lecture",
  duration: "Durée",
  timecode: "Code temporel",
  sourceIn: "Début source",
  track: "Piste",
  editFps: (fps: string) => `Fréquence d’images de montage ${fps}`,
  asset: "Média",
  revision: (revision: number | string) => `Révision ${revision}`,
  secondsInputError: "Saisissez des secondes (ex. 10.5) ou « min:sec »",
  secondsField: (label: string) => `${label} (s)`,
  deleteClip: "Supprimer le clip",
  trPrevious: "Fusionner avec le clip précédent",
  trNext: "Fusionner avec le clip suivant",
  trHintJoinedIn: "Transition du clip précédent vers celui-ci ; les deux doivent avoir du média disponible au-delà de la coupe.",
  trHintJoinedOut: "Transition de ce clip vers le suivant ; les deux doivent avoir du média disponible au-delà de la coupe.",
  trHintIn: "Transition des calques inférieures vers ce clip.",
  trHintOut: "Transition de ce clip vers les calques inférieures.",
  transition: "Transition",
  trSlot: "Position de transition",
  trEffects: "Effets de transition",
  trUnknown: (kind: string) => `La transition sur ce bord est ${kind}, non reconnue par cette version ; aperçu en coupe franche. En choisir une la remplace.`,
  direction: "Direction",
  overlayColor: "Couleur de superposition",
  easing: "Courbe d’accélération",
  trJoin: "Fusionner",
  trCrossfade: "Fondu croisé audio",
  trApplyNote: (hint: string) => `${hint} Choix appliqués immédiatement et annulables.`,
  pageVideo: "Modifier la vidéo",
  pageImage: "Modifier l’image",
  pageAudio: "Modifier l’audio",
  pageCaption: "Propriétés des sous-titres",
  selectedClips: (n: number) => `${n} clips sélectionnés`,
  videoProperties: "Propriétés de la vidéo",
  backToVideo: "Retour aux propriétés de la vidéo",
  created: (n: number) => `Créé ${n}`,
  updated: (n: number) => `Mis à jour : ${n}`,
  deleted: (n: number) => `Supprimé : ${n}`,
  lastChange: "Dernière modification",
  lastChangeLabel: (label: string) => `Dernière modification · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `Révision ${from} → ${to}`,
  changedObjects: (parts: string[]) => `Objets : ${parts.join(" · ")}`,
  durationChange: (from: string, to: string) => `Durée vidéo ${from} → ${to}`,
  undoAvailable: "Annulable (⌘Z ou annuler cette étape dans Historique)",
  undoUnavailable: (reason: string) => `Non annulable : ${reason}`,
  unknownReason: "motif inconnu",
  requestedSeconds: (value: number | string) => `${value} s`,
  requestedFrame: (value: number | string) => `image ${value}`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `Demandé ${requested} → réel ${actual} (image ${frame}, ${fps})`,
  shiftMs: (ms: string) => `, écart de ${ms} ms`,
  geometry: "Géométrie",
  anchor: "Ancre",
  measureFrom: (name: string) => `Mesurer depuis ${name}`,
  width: "L",
  height: "H",
  lockRatio: "Verrouiller le format",
  snapToPin: "Aligner sur l’ancre",
  fullWidth: "Pleine largeur",
  fullHeight: "Pleine hauteur",
  fitCanvas: "Adapter au canevas",
  fillCanvas: "Remplir le canevas",
  rotation: "Rotation",
  flip: "Retourner",
  horizontal: "Horizontal",
  vertical: "Verticale",
  percentField: (label: string) => `${label} (%)`,
  rangeAside: "Plage inversée = barre de compte à rebours",
  progressRange: "Gamme",
  rangeStart: "Début",
  rangeEnd: "Fin",
  controls: "Contrôles",
  minimum: "Minimum",
  maximum: "Maximum",
  smoothing: "Lissage",
  noColorControls: (label: string) => `« ${label} » n’a aucun contrôle de couleur ; ses couleurs proviennent du style.`,
  styleTile: (label: string, count: number) => `Style : ${label}, ${count} styles, cliquez pour choisir`,
  styleCount: (count: number) => `${count} styles · cliquez pour choisir`,
  waveStyles: "Styles de forme d’onde",
  progressStyles: "Styles de progression",
  waveNote: "Contrôles selon le style : Oscilloscope et Onde circulaire n’ont pas de réglage dB ; Zone spectrale / Matrice de points / Anneau pulsé / Ruban utilisent deux couleurs.",
  progressNote: "Contrôles selon le style : les deux bordures arc-en-ciel n’ont aucun réglage de couleur ; les deux arcs-en-ciel mobiles ont seulement une couleur « Fond ».",
  silentTrack: "(piste sans audio)",
  ducking: "Atténuer l’audio original",
  duckUnder: "Atténuer sous",
  duckUnderTrack: "Piste à suivre pour l’atténuation",
  duckSeveral: "Plusieurs pistes ou clips",
  duckSpeech: "Cette règle suit les passages parlés ; choisir une piste la fait suivre cette piste uniquement.",
  duckItems: "Cette règle suit plusieurs pistes ou clips ; choisir une piste la fait suivre cette piste uniquement.",
  duckDepth: "Réduire de",
  advanced: "Avancé",
  attack: "Attaque",
  release: "Relâchement",
  usingDefaults: "Valeurs par défaut",
  usingYours: "Vos valeurs",
  restoreDefaults: "Rétablir les valeurs par défaut",
  duckShared: "Cette règle atténue aussi d’autres clips ; les changements s’y appliquent. La désactiver désactive toute la règle.",
  duckNothing: "Aucune autre piste n’a d’audio ; rien à suivre pour l’atténuation. Placez musique, doublage ou narration sur une autre piste.",
  black: "Noir",
  aspect: "Rapport hauteur/largeur",
  aspectNote: "Le petit côté reste identique ; positions stockées en pourcentages : les clips suivent le canevas, les contenus plein canevas le restent.",
  canvasBackground: "Arrière-plan",
  backdrop: "Arrière-plan",
  canvasColor: "Couleur du canevas",
  specs: "Caractéristiques",
  size: "Taille",
  frameRate: "Fréquence d’images",
  contents: "Contenu",
  contentsCount: (tracks: number, clips: number, assets: number) => `${tracks} pistes · ${clips} clips · ${assets} médias`,
  videoNote: "Sélectionnez des clips sur la timeline pour voir leurs propriétés. Maintenez ⇧ ou ⌘ et cliquez pour une sélection multiple.",
  colorAdjust: "Correction des couleurs",
  dropShadow: "Ombre portée",
  resetAll: "Tout réinitialiser",
  effects: "Effets",
  radius: "Rayon",
  offsetX: "Décalage horizontal",
  offsetY: "Décalage vertical",
  dropShadowColor: "Couleur d’ombre",
  widthLabel: "Largeur",
  effectsNote: "Ombre et contour suivent les bords transparents de l’image ; le rectangle pour la vidéo opaque. Longueurs en pixels sur un petit côté de 540.",
  unknownEffects: (kinds: string[]) => `Ces effets n’ont aucun contrôle ici : ${kinds.join(", ")}. Ils sont conservés ; l’aperçu les ignore, la vérification avant export les liste.`,
  overMax: (current: string, max: string) => `Actuel ${current} · maximum du curseur ${max}`,
  exactInput: (label: string) => `Saisir précisément ${label}`,
  withUnit: (label: string, unit: string) => `${label} (${unit})`,
  colorValue: (label: string, value: string) => `${label} : ${value}`,
  saturationBrightness: (label: string) => `${label} la saturation et la luminosité`,
  commonColors: "Couleurs courantes",
  fitContain: "Contenir",
  fitCover: "Couverture",
  picture: "Image",
  fit: "Ajustement",
  plateNote: "Ce clip a un fond ou des coins arrondis que l’aperçu n’affiche pas encore.",
  orderTranslationFirst: "Traduction en haut",
  orderOriginalFirst: "Original en haut",
  editCaptionStyle: "Modifier le style de sous-titres",
  loadingCaptionStyle: "Chargement du style de sous-titres…",
  captionSchema: (schema: string) => `Ce style de sous-titres est ${schema} ; il ne peut pas encore être modifié ici.`,
  noSchema: "(aucun schema)",
  defaultStyle: "Style par défaut",
  textStyle: "Style de texte",
  position: "Position",
  horizontalPos: "Horizontal",
  bilingual: "Bilingue",
  order: "Commande",
  bilingualOrder: "Ordre bilingue",
  lineGap: "Espacement des lignes",
  displayAside: "Par rapport au début et à la fin de la phrase",
  display: "Affichage",
  lead: "Plus tôt",
  lag: "Plus tard",
  punctuation: "Ponctuation",
  punctToSpace: "Remplacer virgules et points par des espaces",
};
