import { pluralForm } from '@baocut/protocol';
const quantityForms = {"clip": ["klip", "klipy", "klipów", "klipu"], "track": ["ścieżka", "ścieżki", "ścieżek", "ścieżki"], "asset": ["materiał", "materiały", "materiałów", "materiału"], "style": ["styl", "style", "stylów", "stylu"], "emitter": ["emiter", "emitery", "emiterów", "emitera"]} as const;
const quantity = (n: number, kind: keyof typeof quantityForms) => { const f = quantityForms[kind]; return pluralForm('pl', n, { one: `${n} ${f[0]}`, few: `${n} ${f[1]}`, many: `${n} ${f[2]}`, other: `${n} ${f[3]}` }); };
import type { InspectorMessages } from './inspector-copy.ts';

export const pl: InspectorMessages = {
  text: "Tekst",
  style: "Styl",
  textSchema: (schema: string) => `Styl tego tekstu to ${schema}; nie można go jeszcze edytować tutaj.`,
  shape: "Kształt",
  fill: "Wypełnienie",
  color: "Kolor",
  fillColor: "Kolor wypełnienia",
  opacity: "Nieprzezroczystość",
  stroke: "Obrys",
  strokeColor: "Kolor obrysu",
  strokeWidth: "Szerokość",
  corner: "Zaokrąglenie rogów",
  titleAnimatedSticker: "Animowana naklejka",
  titleSticker: "Naklejka",
  titleCounter: "Licznik",
  titleText: "Edytuj tekst",
  titleProgress: "Pasek postępu",
  titleVisualizer: "Przebieg fali",
  titleConfetti: "Konfetti",
  titleDraw: "Rysunek",
  titlePlaceholder: "Symbol zastępczy",
  titleWhiteboard: "Tablica",
  titleComposition: "Kompozycja",
  appearance: "Wygląd",
  params: "Parametry",
  paramsReadOnly: (title: string) => `${title}: parametrów nie można jeszcze edytować tutaj.`,
  compositionReadOnly: "Parametry kompozycji kodowej mają własne reguły walidacji i nie można ich jeszcze edytować tutaj.",
  restoreColors: "Przywróć oryginalne kolory",
  replaceColor: (source: string) => `Zastąp ${source}`,
  stickerUnknown: (id: string) => `Szablon naklejki ${id || '(no templateId)'} nie został rozpoznany.`,
  loopLoop: "Pętla",
  loopOnce: "Odtwórz raz",
  loopHold: "Zatrzymaj na końcu",
  playback: "Odtwarzanie",
  playMode: "Tryb odtwarzania",
  countdown: "Odliczaj w dół",
  countup: "Odliczanie w przód",
  formatS: "Sekundy",
  formatMmss: "Min:Sek",
  formatHmmss: "Godz:Min:Sek",
  timing: "Czas",
  timingMode: "Tryb pomiaru czasu",
  clockFace: "Format zegara",
  cfStyle: "Styl",
  cfStyleTile: (name: string) => `Styl: ${name}, kliknij, aby zmienić`,
  cfBurst: "Salwa",
  cfContinuous: "Ciągły",
  cfMoreShapes: (n: number) => `i jeszcze ${n - 1}`,
  cfChangeStyle: "Zmień styl",
  cfStyles: "Style konfetti",
  cfReset: "Przywróć ustawienia wzorca",
  cfColorN: (n: number) => `Kolor ${n}`,
  cfRemoveColorN: (n: number) => `Usuń kolor ${n}`,
  cfConfettiColorN: (n: number) => `Kolor konfetti ${n}`,
  cfAddColor: "Dodaj kolor",
  cfColorsNote: "Cząstki otrzymują te kolory kolejno według ziarna; zostaw jeden kolor, aby konfetti było jednokolorowe.",
  cfShapes: "Kształty konfetti",
  cfMotionAside: "1× to niezmieniony wzorzec",
  cfMotion: "Ruch cząstek",
  cfCount: "Na salwę",
  cfUnit: "szt.",
  cfDensity: "Gęstość",
  cfRateUnit: "szt./s",
  cfSize: "Rozmiar",
  cfSpeed: "Prędkość",
  cfGravity: "Grawitacja",
  cfWind: "Wiatr",
  cfDrift: "Dryf",
  cfSpin: "Obrót",
  cfOpacity: "Krycie cząstek",
  cfEmitAsideBurst: "Wybuch b w chwili b × interwał",
  cfEmitAsideContinuous: "Narodziny na sekundę = gęstość",
  cfEmit: "Emisja",
  cfMode: "Tryb",
  cfEmitMode: "Tryb emisji",
  cfInterval: "Odstęp",
  cfIntervalZero: "Interwał 0 oznacza jeden wybuch; po upływie czasu życia cząstek ekran jest pusty.",
  cfSettle: "Wyczyść przed końcem",
  cfSettleOn: "Nowe cząstki nie powstają przez ostatni okres życia przed końcem",
  cfSettleOff: "Kontynuuj do końca",
  cfOrigin: "Początek",
  cfOriginCustom: "Niestandardowe",
  cfOriginRecipeMulti: (n: number) => `Ze wzorca · ${quantity(n, "emitter")}`,
  cfOriginRecipe: "Ze wzorca",
  cfOriginX: "Początek X",
  cfOriginY: "Początek Y",
  cfAngle: "Kierunek",
  cfSpread: "Rozrzut",
  cfAngleNote: "Kierunek −90° wskazuje w górę, a 0° w prawo; źródło może być poza ekranem (−20% … 120%).",
  cfRandomAside: "To samo ziarno, ten sam obraz",
  cfRandom: "Losowość",
  cfSeed: "Ziarno",
  cfReseed: "Inne",
  current: (name: string) => `${name} (bieżący)`,
  cfCatalogNote: "Zmiana stylu przywraca jego ustawienia wzorca (kolory, kształty, ruch cząstek i emisję); zachowane jest tylko ziarno, więc cząstki na ekranie pozostają tą samą grupą.",
  alignLeft: "Do lewej",
  alignCenter: "Wyśrodkuj",
  alignRight: "Do prawej",
  fontSize: "Rozmiar",
  textColor: "Kolor tekstu",
  bold: "Pogrubienie",
  italic: "Kursywa",
  underline: "Podkreślenie",
  align: "Wyrównanie",
  lineHeight: "Wysokość wiersza",
  letterSpacing: "Odstęp między literami",
  background: "Tło",
  backgroundPlate: "Kształt tła",
  backgroundColor: "Kolor tła",
  padding: "Odstępy",
  glow: "Blask",
  glowColor: "Kolor poświaty",
  intensity: "Intensywność",
  range: "Zasięg",
  glowShadowNote: "Poświata i cień zajmują jedno miejsce efektu; gdy oba są włączone, rysowana jest tylko poświata.",
  shadow: "Cień",
  shadowColor: "Kolor cienia",
  distance: "Odległość",
  blur: "Rozmycie",
  angle: "Kąt",
  clipLocked: "Ten klip jest zablokowany; odblokuj go, aby wprowadzić zmiany.",
  trackLocked: "Ścieżka jest zablokowana; odblokuj ją na osi czasu, aby wprowadzić zmiany.",
  unlock: "Odblokuj",
  custom: "Niestandardowe",
  speedAside: "Długość jest przeliczana przy nowej prędkości",
  speedChange: "Prędkość",
  speedRate: "Prędkość",
  speedNote: "Jeśli dłuższy klip przykryłby kolejne klipy, nie przesunie ich; zmiana zostanie odrzucona.",
  sound: "Dźwięk",
  mute: "Wycisz",
  volume: "Głośność",
  fadeIn: "Pojawienie",
  fadeOut: "Zanikanie",
  seconds: "s",
  timeAside: "Przyciąga do najbliższej klatki",
  time: "Czas",
  start: "Początek",
  startAtPlayhead: "Ustaw początek na głowicy",
  end: "Koniec",
  endAtPlayhead: "Ustaw koniec na głowicy",
  duration: "Czas trwania",
  timecode: "Kod czasu",
  sourceIn: "Początek w źródle",
  track: "Ścieżka",
  editFps: (fps: string) => `Zmień liczbę klatek na sekundę ${fps}`,
  asset: "Materiał",
  revision: (revision: number | string) => `Wersja ${revision}`,
  secondsInputError: "Wpisz sekundy (np. 10.5) lub „min:sec”",
  secondsField: (label: string) => `${label} (s)`,
  deleteClip: "Usuń klip",
  trPrevious: "Połącz z poprzednim klipem",
  trNext: "Połącz z następnym klipem",
  trHintJoinedIn: "Przejście z poprzedniego klipu do tego; oba potrzebują zapasu materiału poza cięciem.",
  trHintJoinedOut: "Przejście z tego klipu do następnego; oba potrzebują zapasu materiału poza cięciem.",
  trHintIn: "Przejście z warstw poniżej do tego klipu.",
  trHintOut: "Przejście z tego klipu do warstw poniżej.",
  transition: "Przejście",
  trSlot: "Pozycja przejścia",
  trEffects: "Efekty przejścia",
  trUnknown: (kind: string) => `Przejście na tej krawędzi to ${kind}; ta wersja go nie rozpoznaje, więc podgląd pokazuje twarde cięcie. Wybór innego zastąpi go.`,
  direction: "Kierunek",
  overlayColor: "Kolor nakładki",
  easing: "Krzywa ruchu",
  trJoin: "Połącz",
  trCrossfade: "Przenikanie audio",
  trApplyNote: (hint: string) => `${hint} Wybór działa od razu i można go cofnąć.`,
  pageVideo: "Edytuj wideo",
  pageImage: "Edytuj obraz",
  pageAudio: "Edytuj audio",
  pageCaption: "Właściwości napisów",
  selectedClips: (n: number) => `Wybrano: ${quantity(n, "clip")}`,
  videoProperties: "Właściwości wideo",
  backToVideo: "Wróć do właściwości wideo",
  created: (n: number) => `Utworzono: ${n}`,
  updated: (n: number) => `Zaktualizowano: ${n}`,
  deleted: (n: number) => `Usunięto: ${n}`,
  lastChange: "Ostatnia zmiana",
  lastChangeLabel: (label: string) => `Ostatnia zmiana · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `Wersja ${from} → ${to}`,
  changedObjects: (parts: string[]) => `Obiekty: ${parts.join(" · ")}`,
  durationChange: (from: string, to: string) => `Długość wideo ${from} → ${to}`,
  undoAvailable: "Można cofnąć (⌘Z lub ten krok w Historii)",
  undoUnavailable: (reason: string) => `Nie można cofnąć: ${reason}`,
  unknownReason: "nieznana przyczyna",
  requestedSeconds: (value: number | string) => `${value} s`,
  requestedFrame: (value: number | string) => `klatka ${value}`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `Żądano ${requested} → faktycznie ${actual} (klatka ${frame}, ${fps})`,
  shiftMs: (ms: string) => `, różnica ${ms} ms`,
  geometry: "Geometria",
  anchor: "Punkt zakotwiczenia",
  measureFrom: (name: string) => `Mierz od ${name}`,
  width: "S",
  height: "W",
  lockRatio: "Zablokuj proporcje",
  snapToPin: "Przyciągnij do punktu zakotwiczenia",
  fullWidth: "Pełna szerokość",
  fullHeight: "Pełna wysokość",
  fitCanvas: "Dopasuj do płótna",
  fillCanvas: "Wypełnij obszar",
  rotation: "Obrót",
  flip: "Odwróć",
  horizontal: "Poziomo",
  vertical: "W pionie",
  percentField: (label: string) => `${label} (%)`,
  rangeAside: "Odwrócony zakres = pasek odliczania",
  progressRange: "Zasięg",
  rangeStart: "Początek",
  rangeEnd: "Koniec",
  controls: "Elementy sterujące",
  minimum: "Minimum",
  maximum: "Maksimum",
  smoothing: "Wygładzanie",
  noColorControls: (label: string) => `„${label}” nie ma ustawień koloru – kolory pochodzą z samego stylu.`,
  styleTile: (label: string, count: number) => `Styl: ${label}, ${quantity(count, "style")}, kliknij, aby wybrać`,
  styleCount: (count: number) => `${quantity(count, "style")} · kliknij, aby wybrać`,
  waveStyles: "Style fali dźwiękowej",
  progressStyles: "Style postępu",
  waveNote: "Ustawienia zależą od stylu: Oscyloskop i Fala pierścieniowa nie mają ustawień dB; Obszar widma, Matryca punktowa, Pulsujący pierścień i Wstęga używają dwóch kolorów.",
  progressNote: "Ustawienia zależą od stylu: dwie tęczowe ramki nie mają ustawień koloru, a dwie wędrujące tęcze mają tylko kolor „Tła”.",
  silentTrack: "(ścieżka bez audio)",
  ducking: "Przyciszaj oryginalne audio",
  duckUnder: "Przyciszaj pod",
  duckUnderTrack: "Ścieżka wywołująca przyciszenie",
  duckSeveral: "Kilka ścieżek lub klipów",
  duckSpeech: "Ta reguła śledzi fragmenty, w których ktoś mówi; wybór ścieżki ograniczy ją do tej ścieżki.",
  duckItems: "Ta reguła śledzi kilka ścieżek lub klipów; wybór ścieżki ograniczy ją do tej ścieżki.",
  duckDepth: "Zmniejsz o",
  advanced: "Zaawansowane",
  attack: "Atak",
  release: "Powrót",
  usingDefaults: "Używane wartości domyślne",
  usingYours: "Używane własne wartości",
  restoreDefaults: "Przywróć domyślne",
  duckShared: "Ta reguła przycisza też inne klipy, więc zmiany dotyczą również ich; wyłączenie wyłącza całą regułę.",
  duckNothing: "Żadna inna ścieżka nie ma jeszcze audio, więc nie ma pod co przyciszać: najpierw dodaj muzykę, dubbing lub narrację na innej ścieżce.",
  black: "Czarny",
  aspect: "Proporcje",
  aspectNote: "Krótszy bok pozostaje taki sam; pozycje są zapisane jako procenty kadru, więc klipy podążają za płótnem, a wypełniające je nadal je wypełniają.",
  canvasBackground: "Tło",
  backdrop: "Podkład",
  canvasColor: "Kolor płótna",
  specs: "Parametry",
  size: "Rozmiar",
  frameRate: "Liczba klatek",
  contents: "Zawartość",
  contentsCount: (tracks: number, clips: number, assets: number) => `${quantity(tracks, "track")} · ${quantity(clips, "clip")} · ${quantity(assets, "asset")}`,
  videoNote: "Zaznacz klipy na osi czasu, aby zobaczyć ich właściwości. Przytrzymaj ⇧ lub ⌘ i klikaj, aby wybrać kilka.",
  colorAdjust: "Korekcja koloru",
  dropShadow: "Rzucany cień",
  resetAll: "Resetuj wszystko",
  effects: "Efekty",
  radius: "Promień",
  offsetX: "Przesunięcie poziome",
  offsetY: "Przesunięcie pionowe",
  dropShadowColor: "Kolor cienia",
  widthLabel: "Szerokość",
  effectsNote: "Cień i obrys podążają za przezroczystymi krawędziami obrazu; dla nieprzezroczystego wideo za prostokątem. Długości to piksele przy krótszym boku 540.",
  unknownEffects: (kinds: string[]) => `Te efekty nie mają ustawień na tej stronie: ${kinds.join(", ")}. Zachowane są bez zmian; podgląd je pomija, a kontrola przed eksportem je wymienia.`,
  overMax: (current: string, max: string) => `Bieżąca wartość ${current} · maksimum suwaka ${max}`,
  exactInput: (label: string) => `Wpisz dokładną wartość ${label}`,
  withUnit: (label: string, unit: string) => `${label} (${unit})`,
  colorValue: (label: string, value: string) => `${label}: ${value}`,
  saturationBrightness: (label: string) => `${label} nasycenia i jasności`,
  commonColors: "Popularne kolory",
  fitContain: "Zmieść",
  fitCover: "Wypełnij",
  picture: "Obraz",
  fit: "Dopasowanie",
  plateNote: "Ten klip ma podkład lub zaokrąglone rogi, których podgląd jeszcze nie pokazuje.",
  orderTranslationFirst: "Tłumaczenie na górze",
  orderOriginalFirst: "Oryginał na górze",
  editCaptionStyle: "Edytuj styl napisów",
  loadingCaptionStyle: "Wczytywanie stylu napisów…",
  captionSchema: (schema: string) => `Styl napisów to ${schema}; nie można go jeszcze edytować tutaj.`,
  noSchema: "(brak schema)",
  defaultStyle: "Styl domyślny",
  textStyle: "Styl tekstu",
  position: "Pozycja",
  horizontalPos: "Poziomo",
  bilingual: "Dwujęzyczny",
  order: "Kolejność",
  bilingualOrder: "Kolejność dwóch języków",
  lineGap: "Odstęp między wierszami",
  displayAside: "Względem początku i końca zdania",
  display: "Wyświetlanie",
  lead: "Wcześniej",
  lag: "Później",
  punctuation: "Interpunkcja",
  punctToSpace: "Zastępuj przecinki i kropki spacjami",
};
