import { defineMessages } from '@baocut/protocol';
import { zhHans } from './inspector-copy.zh-Hans.ts';
import { zhHant } from './inspector-copy.zh-Hant.ts';
import { ja } from './inspector-copy.ja.ts';
import { ko } from './inspector-copy.ko.ts';
import { es } from './inspector-copy.es.ts';
import { fr } from './inspector-copy.fr.ts';
import { de } from './inspector-copy.de.ts';
import { nl } from './inspector-copy.nl.ts';
import { ptBR } from './inspector-copy.pt-BR.ts';
import { it } from './inspector-copy.it.ts';
import { ru } from './inspector-copy.ru.ts';
import { pl } from './inspector-copy.pl.ts';
import { tr } from './inspector-copy.tr.ts';
import { vi } from './inspector-copy.vi.ts';

/** 属性页（检查器）的文案：元素页、彩纸、文字样式、片段页公共几节、转场与控件。译文在 `inspector-copy.zh-Hans.ts`。 */
const en = {
  text: 'Text',
  style: 'Style',
  textSchema: (schema: string) => `This text’s style is ${schema}; it can’t be edited here yet.`,
  shape: 'Shape',
  fill: 'Fill',
  color: 'Color',
  fillColor: 'Fill color',
  opacity: 'Opacity',
  stroke: 'Stroke',
  strokeColor: 'Stroke color',
  strokeWidth: 'Width',
  corner: 'Corner radius',
  titleAnimatedSticker: 'Animated sticker',
  titleSticker: 'Sticker',
  titleCounter: 'Counter',
  titleText: 'Edit text',
  titleProgress: 'Progress bar',
  titleVisualizer: 'Waveform',
  titleConfetti: 'Confetti',
  titleDraw: 'Drawing',
  titlePlaceholder: 'Placeholder',
  titleWhiteboard: 'Whiteboard',
  titleComposition: 'Composition',
  appearance: 'Appearance',
  params: 'Parameters',
  paramsReadOnly: (title: string) => `${title} parameters can’t be edited here yet.`,
  compositionReadOnly: 'Code composition parameters follow their own validation rules and can’t be edited here yet.',
  restoreColors: 'Restore original colors',
  replaceColor: (source: string) => `Replace ${source}`,
  stickerUnknown: (id: string) => `Sticker template ${id || '(no templateId)'} isn’t recognized.`,
  loopLoop: 'Loop',
  loopOnce: 'Play once',
  loopHold: 'Hold',
  playback: 'Playback',
  playMode: 'Playback mode',
  countdown: 'Count down',
  countup: 'Count up',
  formatS: 'Seconds',
  formatMmss: 'Min:Sec',
  formatHmmss: 'Hr:Min:Sec',
  timing: 'Timing',
  timingMode: 'Timing mode',
  clockFace: 'Clock format',
  cfStyle: 'Style',
  cfStyleTile: (name: string) => `Style: ${name}, click to change`,
  cfBurst: 'Burst',
  cfContinuous: 'Continuous',
  cfMoreShapes: (n: number) => ` and ${n - 1} more`,
  cfChangeStyle: 'Change style',
  cfStyles: 'Confetti styles',
  cfReset: 'Reset to recipe',
  cfColorN: (n: number) => `Color ${n}`,
  cfRemoveColorN: (n: number) => `Remove color ${n}`,
  cfConfettiColorN: (n: number) => `Confetti color ${n}`,
  cfAddColor: 'Add color',
  cfColorsNote: 'Particles take these colors in turn by seed; delete down to one for single-color confetti.',
  cfShapes: 'Confetti shapes',
  cfMotionAside: '1× is the recipe as is',
  cfMotion: 'Particle motion',
  cfCount: 'Per burst',
  cfUnit: 'pcs',
  cfDensity: 'Density',
  cfRateUnit: 'pcs/s',
  cfSize: 'Size',
  cfSpeed: 'Speed',
  cfGravity: 'Gravity',
  cfWind: 'Wind',
  cfDrift: 'Drift',
  cfSpin: 'Spin',
  cfOpacity: 'Particle opacity',
  cfEmitAsideBurst: 'Burst b at b × interval',
  cfEmitAsideContinuous: 'Births per second = density',
  cfEmit: 'Emission',
  cfMode: 'Mode',
  cfEmitMode: 'Emission mode',
  cfInterval: 'Interval',
  cfIntervalZero: 'Interval 0 = fire once; the screen is empty once the particles’ lifetime passes.',
  cfSettle: 'Clear before the end',
  cfSettleOn: 'No new particles in the last lifetime before the end',
  cfSettleOff: 'Keep going to the end',
  cfOrigin: 'Origin',
  cfOriginCustom: 'Custom',
  cfOriginRecipeMulti: (n: number) => `From recipe · ${n} emitters`,
  cfOriginRecipe: 'From recipe',
  cfOriginX: 'Origin X',
  cfOriginY: 'Origin Y',
  cfAngle: 'Direction',
  cfSpread: 'Spread',
  cfAngleNote: 'Direction −90° points straight up and 0° points right; the origin can be off screen (−20% … 120%).',
  cfRandomAside: 'Same seed, same picture',
  cfRandom: 'Randomness',
  cfSeed: 'Seed',
  cfReseed: 'Shuffle',
  current: (name: string) => `${name} (current)`,
  cfCatalogNote: 'Switching styles resets to that style’s recipe defaults (colors, shapes, particle motion, and emission all change); only the seed stays—so as you switch, the particles on screen remain the same bunch.',
  alignLeft: 'Left',
  alignCenter: 'Center',
  alignRight: 'Right',
  fontSize: 'Size',
  textColor: 'Text color',
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  align: 'Alignment',
  lineHeight: 'Line height',
  letterSpacing: 'Letter spacing',
  background: 'Background',
  backgroundPlate: 'Background shape',
  backgroundColor: 'Background color',
  padding: 'Padding',
  glow: 'Glow',
  glowColor: 'Glow color',
  intensity: 'Intensity',
  range: 'Range',
  glowShadowNote: 'Glow and shadow share one effect slot; with both on, only the glow is drawn.',
  shadow: 'Shadow',
  shadowColor: 'Shadow color',
  distance: 'Distance',
  blur: 'Blur',
  angle: 'Angle',
  clipLocked: 'This clip is locked; unlock it to make changes.',
  trackLocked: 'Its track is locked; unlock the track on the timeline to make changes.',
  unlock: 'Unlock',
  custom: 'Custom',
  speedAside: 'Length is recalculated at the new rate',
  speedChange: 'Speed',
  speedRate: 'Rate',
  speedNote: 'If the longer clip would cover the clips after it, it won’t push them aside; the change is rejected.',
  sound: 'Audio',
  mute: 'Mute',
  volume: 'Volume',
  fadeIn: 'Fade in',
  fadeOut: 'Fade out',
  seconds: 's',
  timeAside: 'Snaps to the nearest frame',
  time: 'Time',
  start: 'Start',
  startAtPlayhead: 'Set start to playhead',
  end: 'End',
  endAtPlayhead: 'Set end to playhead',
  duration: 'Duration',
  timecode: 'Timecode',
  sourceIn: 'Source in',
  track: 'Track',
  editFps: (fps: string) => `Edit frame rate ${fps}`,
  asset: 'Asset',
  revision: (revision: number | string) => `Revision ${revision}`,
  secondsInputError: 'Enter seconds (e.g. 10.5) or “min:sec”',
  secondsField: (label: string) => `${label} (s)`,
  deleteClip: 'Delete clip',
  trPrevious: 'Join with the previous clip',
  trNext: 'Join with the next clip',
  trHintJoinedIn: 'Transitions from the previous clip into this one; both clips need spare media beyond the cut.',
  trHintJoinedOut: 'Transitions from this clip into the next one; both clips need spare media beyond the cut.',
  trHintIn: 'Transitions from the layers below into this clip.',
  trHintOut: 'Transitions from this clip into the layers below.',
  transition: 'Transition',
  trSlot: 'Transition position',
  trEffects: 'Transition effects',
  trUnknown: (kind: string) => `The transition on this edge is ${kind}, which this version doesn’t recognize; the preview draws a hard cut. Choosing one replaces it.`,
  direction: 'Direction',
  overlayColor: 'Overlay color',
  easing: 'Easing',
  trJoin: 'Join',
  trCrossfade: 'Crossfade audio',
  trApplyNote: (hint: string) => `${hint} Choices apply immediately and can be undone.`,
  pageVideo: 'Edit video',
  pageImage: 'Edit image',
  pageAudio: 'Edit audio',
  pageCaption: 'Subtitle properties',
  selectedClips: (n: number) => `${n} clips selected`,
  videoProperties: 'Video properties',
  backToVideo: 'Back to video properties',
  created: (n: number) => `Created ${n}`,
  updated: (n: number) => `Updated ${n}`,
  deleted: (n: number) => `Deleted ${n}`,
  lastChange: 'Last change',
  lastChangeLabel: (label: string) => `Last change · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `Revision ${from} → ${to}`,
  changedObjects: (parts: string[]) => `Objects: ${parts.join(' · ')}`,
  durationChange: (from: string, to: string) => `Video length ${from} → ${to}`,
  undoAvailable: 'Can be undone (⌘Z, or undo this step in History)',
  undoUnavailable: (reason: string) => `Can’t be undone: ${reason}`,
  unknownReason: 'unknown reason',
  requestedSeconds: (value: number | string) => `${value} s`,
  requestedFrame: (value: number | string) => `frame ${value}`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `Requested ${requested} → actual ${actual} (frame ${frame}, ${fps})`,
  shiftMs: (ms: string) => `, off by ${ms} ms`,
  geometry: 'Geometry',
  anchor: 'Anchor',
  measureFrom: (name: string) => `Measure from ${name}`,
  width: 'W',
  height: 'H',
  lockRatio: 'Lock aspect ratio',
  snapToPin: 'Snap to anchor',
  fullWidth: 'Full width',
  fullHeight: 'Full height',
  fitCanvas: 'Fit canvas',
  fillCanvas: 'Fill canvas',
  rotation: 'Rotation',
  flip: 'Flip',
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  percentField: (label: string) => `${label} (%)`,
  rangeAside: 'Reversed range = countdown bar',
  progressRange: 'Range',
  rangeStart: 'Start',
  rangeEnd: 'End',
  controls: 'Controls',
  minimum: 'Minimum',
  maximum: 'Maximum',
  smoothing: 'Smoothing',
  noColorControls: (label: string) => `“${label}” has no color controls—its colors come from the style itself.`,
  styleTile: (label: string, count: number) => `Style: ${label}, ${count} styles, click to choose`,
  styleCount: (count: number) => `${count} styles · click to choose`,
  waveStyles: 'Waveform styles',
  progressStyles: 'Progress styles',
  waveNote: 'Controls follow the style: Oscilloscope and Ring Wave have no dB controls; Spectrum Area / Dot Matrix / Pulse Ring / Ribbon use two colors.',
  progressNote: 'Controls follow the style: the two rainbow borders have no color controls, and the two roaming rainbows have only a “Background” color.',
  silentTrack: '(track with no audio)',
  ducking: 'Duck original audio',
  duckUnder: 'Duck under',
  duckUnderTrack: 'Track to duck under',
  duckSeveral: 'Several tracks or clips',
  duckSpeech: 'This rule follows the stretches where someone is speaking; choosing a track makes it follow only that track.',
  duckItems: 'This rule follows several tracks or clips; choosing a track makes it follow only that track.',
  duckDepth: 'Reduce by',
  advanced: 'Advanced',
  attack: 'Attack',
  release: 'Release',
  usingDefaults: 'Using defaults',
  usingYours: 'Using your values',
  restoreDefaults: 'Restore defaults',
  duckShared: 'This rule also ducks other clips, so changes here apply to them too; turning it off disables the whole rule.',
  duckNothing: 'No other track has audio yet, so there’s nothing to duck under: put music, a dub, or narration on another track first.',
  black: 'Black',
  aspect: 'Aspect ratio',
  aspectNote: 'The short side stays the same; positions are stored as percentages of the frame, so clips follow the canvas and anything filling the canvas still fills it.',
  canvasBackground: 'Canvas background',
  backdrop: 'Backdrop',
  canvasColor: 'Canvas color',
  specs: 'Specs',
  size: 'Size',
  frameRate: 'Frame rate',
  contents: 'Contents',
  contentsCount: (tracks: number, clips: number, assets: number) => `${tracks} tracks · ${clips} clips · ${assets} assets`,
  videoNote: 'Select clips on the timeline to see their properties here. Hold ⇧ or ⌘ and click to select several.',
  colorAdjust: 'Color correction',
  dropShadow: 'Drop shadow',
  resetAll: 'Reset all',
  effects: 'Effects',
  radius: 'Radius',
  offsetX: 'Horizontal offset',
  offsetY: 'Vertical offset',
  dropShadowColor: 'Shadow color',
  widthLabel: 'Width',
  effectsNote: 'Drop shadow and stroke follow the picture’s transparent edges; for opaque video they follow the rectangle. Lengths are pixels on a 540 short side.',
  unknownEffects: (kinds: string[]) => `These effects have no controls on this page: ${kinds.join(', ')}. They’re kept as is; the preview skips them, and the pre-export check lists them.`,
  overMax: (current: string, max: string) => `Current ${current} · slider max ${max}`,
  exactInput: (label: string) => `Enter exact ${label}`,
  withUnit: (label: string, unit: string) => `${label} (${unit})`,
  colorValue: (label: string, value: string) => `${label}: ${value}`,
  saturationBrightness: (label: string) => `${label} saturation and brightness`,
  commonColors: 'Common colors',
  fitContain: 'Contain',
  fitCover: 'Cover',
  picture: 'Picture',
  fit: 'Fit',
  plateNote: 'This clip has a backing or rounded corners, which the preview doesn’t show yet.',
  orderTranslationFirst: 'Translation on top',
  orderOriginalFirst: 'Original on top',
  editCaptionStyle: 'Edit subtitle style',
  loadingCaptionStyle: 'Loading subtitle style…',
  captionSchema: (schema: string) => `This subtitle style is ${schema}; it can’t be edited here yet.`,
  noSchema: '(no schema)',
  defaultStyle: 'Default style',
  textStyle: 'Text style',
  position: 'Position',
  horizontalPos: 'Horizontal',
  bilingual: 'Bilingual',
  order: 'Order',
  bilingualOrder: 'Bilingual order',
  lineGap: 'Line spacing',
  displayAside: 'Relative to the sentence’s start and end',
  display: 'Display',
  lead: 'Earlier',
  lag: 'Later',
  punctuation: 'Punctuation',
  punctToSpace: 'Replace commas and periods with spaces',
};

export type InspectorMessages = typeof en;
export const INSPECTOR_COPY = defineMessages(en, { 'zh-Hans': zhHans, 'zh-Hant': zhHant, ja, ko, es, fr, de, nl, 'pt-BR': ptBR, it, ru, pl, tr, vi });
