import type { InspectorMessages } from './inspector-copy.ts';

export const ja: InspectorMessages = {
  text: 'テキスト',
  style: 'スタイル',
  textSchema: (schema: string) => `このテキストのスタイルは ${schema} のため、まだここでは編集できません。`,
  shape: '図形',
  fill: '塗り',
  color: '色',
  fillColor: '塗りの色',
  opacity: '不透明度',
  stroke: '線',
  strokeColor: '線の色',
  strokeWidth: '太さ',
  corner: '角の丸み',
  titleAnimatedSticker: 'アニメーションステッカー',
  titleSticker: 'ステッカー',
  titleCounter: 'カウンタ',
  titleText: 'テキストを編集',
  titleProgress: 'プログレスバー',
  titleVisualizer: '波形',
  titleConfetti: '紙吹雪',
  titleDraw: '手描き',
  titlePlaceholder: 'プレースホルダ',
  titleWhiteboard: 'ホワイトボード',
  titleComposition: 'コンポジション',
  appearance: '外観',
  params: 'パラメータ',
  paramsReadOnly: (title: string) => `${title}のパラメータは、まだここでは編集できません。`,
  compositionReadOnly: 'コードによるコンポジションのパラメータは独自のルールで検証されるため、まだここでは編集できません。',
  restoreColors: '元の色に戻す',
  replaceColor: (source: string) => `${source} を置き換え`,
  stickerUnknown: (id: string) => `ステッカーテンプレート ${id || '（templateId なし）'} を認識できません。`,
  loopLoop: 'ループ',
  loopOnce: '1 回再生',
  loopHold: '静止',
  playback: '再生',
  playMode: '再生方法',
  countdown: 'カウントダウン',
  countup: 'カウントアップ',
  formatS: '秒',
  formatMmss: '分:秒',
  formatHmmss: '時:分:秒',
  timing: '計時',
  timingMode: '計時の方法',
  clockFace: '時計の表示形式',
  cfStyle: 'スタイル',
  cfStyleTile: (name: string) => `スタイル：${name}、クリックして変更`,
  cfBurst: 'バースト',
  cfContinuous: '連続',
  cfMoreShapes: (n: number) => ` ほか ${n - 1} 種類`,
  cfChangeStyle: 'スタイルを変更',
  cfStyles: '紙吹雪のスタイル',
  cfReset: 'レシピに戻す',
  cfColorN: (n: number) => `色 ${n}`,
  cfRemoveColorN: (n: number) => `色 ${n} を削除`,
  cfConfettiColorN: (n: number) => `紙吹雪の色 ${n}`,
  cfAddColor: '色を追加',
  cfColorsNote: 'パーティクルはシードに従ってこれらの色を順番に使います。1 色だけ残すと単色の紙吹雪になります。',
  cfShapes: '紙吹雪の形',
  cfMotionAside: '1× はレシピのまま',
  cfMotion: 'パーティクルの動き',
  cfCount: '1 回あたりの数',
  cfUnit: '個',
  cfDensity: '密度',
  cfRateUnit: '個/秒',
  cfSize: 'サイズ',
  cfSpeed: '速度',
  cfGravity: '重力',
  cfWind: '風',
  cfDrift: '揺れ',
  cfSpin: '回転',
  cfOpacity: 'パーティクルの不透明度',
  cfEmitAsideBurst: 'b 回目は b × 間隔の時点',
  cfEmitAsideContinuous: '1 秒あたりの発生数 = 密度',
  cfEmit: '放出',
  cfMode: 'モード',
  cfEmitMode: '放出モード',
  cfInterval: '間隔',
  cfIntervalZero: '間隔 0 = 1 回だけ放出します。パーティクルの寿命が過ぎると画面は空になります。',
  cfSettle: '終了前に出し切る',
  cfSettleOn: '終了前の 1 寿命分は新しいパーティクルを出さない',
  cfSettleOff: '終了まで出し続ける',
  cfOrigin: '起点',
  cfOriginCustom: 'カスタム',
  cfOriginRecipeMulti: (n: number) => `レシピに従う · エミッタ ${n} 個`,
  cfOriginRecipe: 'レシピに従う',
  cfOriginX: '起点 X',
  cfOriginY: '起点 Y',
  cfAngle: '方向',
  cfSpread: '広がり',
  cfAngleNote: '方向 −90° は真上、0° は真右です。起点は画面の外にも置けます（−20% … 120%）。',
  cfRandomAside: '同じシードなら同じ画面',
  cfRandom: 'ランダム',
  cfSeed: 'シード',
  cfReseed: 'シャッフル',
  current: (name: string) => `${name}（現在）`,
  cfCatalogNote: 'スタイルを変えると、そのスタイルのレシピの既定値に戻ります（色、形、パーティクルの動き、放出がすべて変わります）。シードだけは残るため、切り替えても画面上のパーティクルは同じひとまとまりのままです。',
  alignLeft: '左',
  alignCenter: '中央',
  alignRight: '右',
  fontSize: 'サイズ',
  textColor: 'テキストの色',
  bold: '太字',
  italic: '斜体',
  underline: '下線',
  align: '揃え',
  lineHeight: '行の高さ',
  letterSpacing: '文字間隔',
  background: '背景',
  backgroundPlate: '背景の形',
  backgroundColor: '背景色',
  padding: '余白',
  glow: 'グロー',
  glowColor: 'グローの色',
  intensity: '強度',
  range: '範囲',
  glowShadowNote: 'グローとシャドウは 1 つのエフェクト枠を共有します。両方オンの場合はグローだけが描画されます。',
  shadow: 'シャドウ',
  shadowColor: 'シャドウの色',
  distance: '距離',
  blur: 'ぼかし',
  angle: '角度',
  clipLocked: 'このクリップはロックされています。変更するにはロックを解除してください。',
  trackLocked: 'このクリップのトラックはロックされています。変更するにはタイムラインでトラックのロックを解除してください。',
  unlock: 'ロックを解除',
  custom: 'カスタム',
  speedAside: '長さは新しい速度で再計算されます',
  speedChange: '速度',
  speedRate: '倍速',
  speedNote: '長くなったクリップが後ろのクリップに重なる場合、後ろのクリップは押し出されず、この変更は拒否されます。',
  sound: '音声',
  mute: 'ミュート',
  volume: '音量',
  fadeIn: 'フェードイン',
  fadeOut: 'フェードアウト',
  seconds: '秒',
  timeAside: '最も近いフレームに揃えます',
  time: '時間',
  start: '開始',
  startAtPlayhead: '開始を再生ヘッドの位置に設定',
  end: '終了',
  endAtPlayhead: '終了を再生ヘッドの位置に設定',
  duration: '長さ',
  timecode: 'タイムコード',
  sourceIn: 'ソースのイン点',
  track: 'トラック',
  editFps: (fps: string) => `編集フレームレート ${fps}`,
  asset: '素材',
  revision: (revision: number | string) => `リビジョン ${revision}`,
  secondsInputError: '秒数（例：10.5）または「分:秒」の形式で入力してください',
  secondsField: (label: string) => `${label}（秒）`,
  deleteClip: 'クリップを削除',
  trPrevious: '前のクリップとのつなぎ',
  trNext: '次のクリップとのつなぎ',
  trHintJoinedIn: '前のクリップからこのクリップへ切り替わります。両方のクリップとも、カット点の外側に素材の余白が必要です。',
  trHintJoinedOut: 'このクリップから次のクリップへ切り替わります。両方のクリップとも、カット点の外側に素材の余白が必要です。',
  trHintIn: '下のレイヤーからこのクリップへ切り替わります。',
  trHintOut: 'このクリップから下のレイヤーへ切り替わります。',
  transition: 'トランジション',
  trSlot: 'トランジションの位置',
  trEffects: 'トランジションのエフェクト',
  trUnknown: (kind: string) => `この境界のトランジションは ${kind} ですが、このバージョンでは認識できないため、プレビューではカットとして描画します。いずれかを選ぶと置き換わります。`,
  direction: '方向',
  overlayColor: 'オーバーレイの色',
  easing: 'イージング',
  trJoin: 'つなぎ',
  trCrossfade: '音声をクロスフェード',
  trApplyNote: (hint: string) => `${hint}選択するとすぐに適用され、取り消せます。`,
  pageVideo: '動画を編集',
  pageImage: '画像を編集',
  pageAudio: '音声を編集',
  pageCaption: '字幕のプロパティ',
  selectedClips: (n: number) => `${n} 個のクリップを選択中`,
  videoProperties: '動画のプロパティ',
  backToVideo: '動画のプロパティに戻る',
  created: (n: number) => `追加 ${n}`,
  updated: (n: number) => `更新 ${n}`,
  deleted: (n: number) => `削除 ${n}`,
  lastChange: '直前の変更',
  lastChangeLabel: (label: string) => `直前の変更 · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `リビジョン ${from} → ${to}`,
  changedObjects: (parts: string[]) => `オブジェクト：${parts.join(' · ')}`,
  durationChange: (from: string, to: string) => `動画の長さ ${from} → ${to}`,
  undoAvailable: '取り消せます（⌘Z、または履歴でこのステップを取り消す）',
  undoUnavailable: (reason: string) => `取り消せません：${reason}`,
  unknownReason: '原因不明',
  requestedSeconds: (value: number | string) => `${value} 秒`,
  requestedFrame: (value: number | string) => `${value} フレーム目`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `指定 ${requested} → 実際 ${actual}（${frame} フレーム目、${fps}）`,
  shiftMs: (ms: string) => `、ずれ ${ms} ミリ秒`,
  geometry: 'ジオメトリ',
  anchor: 'アンカー',
  measureFrom: (name: string) => `${name}から測る`,
  width: '幅',
  height: '高さ',
  lockRatio: '縦横比を固定',
  snapToPin: 'アンカーにスナップ',
  fullWidth: '横いっぱい',
  fullHeight: '縦いっぱい',
  fitCanvas: 'キャンバスに合わせる',
  fillCanvas: 'キャンバスいっぱい',
  rotation: '回転',
  flip: '反転',
  horizontal: '左右',
  vertical: '上下',
  percentField: (label: string) => `${label}（%）`,
  rangeAside: '逆向きの区間 = カウントダウンバー',
  progressRange: '区間',
  rangeStart: '開始',
  rangeEnd: '終了',
  controls: 'コントロール',
  minimum: '最小',
  maximum: '最大',
  smoothing: 'スムージング',
  noColorControls: (label: string) => `「${label}」には色のコントロールがありません。配色はスタイル自体で決まります。`,
  styleTile: (label: string, count: number) => `スタイル：${label}、${count} 種類、クリックして選択`,
  styleCount: (count: number) => `${count} 種類 · クリックして選択`,
  waveStyles: '波形のスタイル',
  progressStyles: 'プログレスのスタイル',
  waveNote: 'コントロールはスタイルによって変わります。オシロスコープとリング波形には dB のコントロールがなく、スペクトラムエリア / ドットマトリクス / パルスリング / リボンは 2 色です。',
  progressNote: 'コントロールはスタイルによって変わります。2 種類のレインボー枠には色のコントロールがなく、2 種類の流れるレインボーには「背景」色しかありません。',
  silentTrack: '（音声のないトラック）',
  ducking: '元の音声を下げる',
  duckUnder: '下げる基準',
  duckUnderTrack: 'どのトラックの下で下げるか',
  duckSeveral: '複数のトラックまたはクリップ',
  duckSpeech: 'このルールは誰かが話している区間に従います。トラックを選ぶと、そのトラックだけに従うようになります。',
  duckItems: 'このルールは複数のトラックまたはクリップに従います。トラックを選ぶと、そのトラックだけに従うようになります。',
  duckDepth: '下げる量',
  advanced: '詳細',
  attack: 'アタック',
  release: 'リリース',
  usingDefaults: '既定値を使用中',
  usingYours: '入力した値を使用中',
  restoreDefaults: '既定値に戻す',
  duckShared: 'このルールはほかのクリップも下げているため、ここでの変更はそれらにも適用されます。オフにするとルール全体が無効になります。',
  duckNothing: 'ほかのトラックにまだ音声がないため、下げる基準がありません。先に別のトラックに音楽、吹き替え、ナレーションを置いてください。',
  black: '黒',
  aspect: 'アスペクト比',
  aspectNote: '短辺は変わりません。位置はフレームに対するパーセントで保存されるため、画面上のクリップはキャンバスに追従し、キャンバスいっぱいのものはそのまま全体を覆います。',
  canvasBackground: 'キャンバスの背景',
  backdrop: '下地',
  canvasColor: 'キャンバスの色',
  specs: '仕様',
  size: 'サイズ',
  frameRate: 'フレームレート',
  contents: '内容',
  contentsCount: (tracks: number, clips: number, assets: number) => `トラック ${tracks} 本 · クリップ ${clips} 個 · 素材 ${assets} 個`,
  videoNote: 'タイムラインでクリップを選択すると、ここにクリップのプロパティが表示されます。⇧ または ⌘ を押しながらクリックすると複数選択できます。',
  colorAdjust: '色補正',
  dropShadow: 'ドロップシャドウ',
  resetAll: 'すべてリセット',
  effects: 'エフェクト',
  radius: '半径',
  offsetX: '横方向のオフセット',
  offsetY: '縦方向のオフセット',
  dropShadowColor: 'シャドウの色',
  widthLabel: '幅',
  effectsNote: 'ドロップシャドウと線は画像の透明な縁に沿います。不透明な動画では長方形の縁に沿います。長さは短辺 540 換算のピクセルです。',
  unknownEffects: (kinds: string[]) => `このページにコントロールがないエフェクトがあります：${kinds.join('、')}。そのまま保持され、プレビューではスキップされ、書き出し前のチェックで一覧表示されます。`,
  overMax: (current: string, max: string) => `現在 ${current} · スライダーの上限 ${max}`,
  exactInput: (label: string) => `${label}を正確に入力`,
  withUnit: (label: string, unit: string) => `${label}（${unit}）`,
  colorValue: (label: string, value: string) => `${label}：${value}`,
  saturationBrightness: (label: string) => `${label}の彩度と明度`,
  commonColors: 'よく使う色',
  fitContain: '全体表示',
  fitCover: '全面表示',
  picture: '画面',
  fit: 'フィット',
  plateNote: 'このクリップには背景プレートか角の丸みがありますが、プレビューにはまだ反映されません。',
  orderTranslationFirst: '翻訳を上に',
  orderOriginalFirst: '原文を上に',
  editCaptionStyle: '字幕スタイルを編集',
  loadingCaptionStyle: '字幕スタイルを読み込み中…',
  captionSchema: (schema: string) => `この字幕スタイルは ${schema} のため、まだここでは編集できません。`,
  noSchema: '（schema なし）',
  defaultStyle: '既定のスタイル',
  textStyle: 'テキストスタイル',
  position: '位置',
  horizontalPos: '横位置',
  bilingual: '二言語',
  order: '順序',
  bilingualOrder: '二言語の順序',
  lineGap: '行間',
  displayAside: '文の開始と終了に対して',
  display: '表示',
  lead: '早める',
  lag: '遅らせる',
  punctuation: '句読点',
  punctToSpace: '読点と句点をスペースに置き換える',
};
