import { pluralForm } from '@baocut/protocol';
const quantityForms = {"clip": ["клип", "клипа", "клипов", "клипа"], "track": ["дорожка", "дорожки", "дорожек", "дорожки"], "asset": ["материал", "материала", "материалов", "материала"], "style": ["стиль", "стиля", "стилей", "стиля"], "emitter": ["источник", "источника", "источников", "источника"]} as const;
const quantity = (n: number, kind: keyof typeof quantityForms) => { const f = quantityForms[kind]; return pluralForm('ru', n, { one: `${n} ${f[0]}`, few: `${n} ${f[1]}`, many: `${n} ${f[2]}`, other: `${n} ${f[3]}` }); };
import type { InspectorMessages } from './inspector-copy.ts';

export const ru: InspectorMessages = {
  text: "Текст",
  style: "Стиль",
  textSchema: (schema: string) => `Стиль этого текста — ${schema}; его пока нельзя редактировать здесь.`,
  shape: "Форма",
  fill: "Заливка",
  color: "Цвет",
  fillColor: "Цвет заливки",
  opacity: "Непрозрачность",
  stroke: "Обводка",
  strokeColor: "Цвет обводки",
  strokeWidth: "Ширина",
  corner: "Скругление углов",
  titleAnimatedSticker: "Анимированная наклейка",
  titleSticker: "наклейка",
  titleCounter: "Счётчик",
  titleText: "Редактировать текст",
  titleProgress: "Индикатор выполнения",
  titleVisualizer: "Звуковая волна",
  titleConfetti: "Конфетти",
  titleDraw: "Рисунок",
  titlePlaceholder: "Заполнитель",
  titleWhiteboard: "Доска",
  titleComposition: "Композиция",
  appearance: "Внешний вид",
  params: "Параметры",
  paramsReadOnly: (title: string) => `${title}: параметры пока нельзя редактировать здесь.`,
  compositionReadOnly: "Параметры кодовой композиции имеют собственные правила проверки и пока не редактируются здесь.",
  restoreColors: "Восстановить исходные цвета",
  replaceColor: (source: string) => `Заменить ${source}`,
  stickerUnknown: (id: string) => `Шаблон наклейки ${id || '(no templateId)'} не распознан.`,
  loopLoop: "Цикл",
  loopOnce: "Воспроизвести один раз",
  loopHold: "Удерживать",
  playback: "Воспроизведение",
  playMode: "Режим воспроизведения",
  countdown: "Обратный отсчёт",
  countup: "Прямой отсчёт",
  formatS: "Секунды",
  formatMmss: "Мин:Сек",
  formatHmmss: "Ч:Мин:Сек",
  timing: "Тайминг",
  timingMode: "Режим отсчёта",
  clockFace: "Формат часов",
  cfStyle: "Стиль",
  cfStyleTile: (name: string) => `Стиль: ${name}, нажмите для изменения`,
  cfBurst: "Залп",
  cfContinuous: "Непрерывно",
  cfMoreShapes: (n: number) => `и ещё ${n - 1}`,
  cfChangeStyle: "Изменить стиль",
  cfStyles: "Стили конфетти",
  cfReset: "Сбросить к настройкам шаблона",
  cfColorN: (n: number) => `Цвет ${n}`,
  cfRemoveColorN: (n: number) => `Удалить цвет ${n}`,
  cfConfettiColorN: (n: number) => `Цвет конфетти ${n}`,
  cfAddColor: "Добавить цвет",
  cfColorsNote: "Частицы получают эти цвета по очереди в зависимости от seed; оставьте один цвет для одноцветного конфетти.",
  cfShapes: "Формы конфетти",
  cfMotionAside: "1× — шаблон без изменений",
  cfMotion: "Движение частиц",
  cfCount: "За залп",
  cfUnit: "шт.",
  cfDensity: "Плотность",
  cfRateUnit: "шт./с",
  cfSize: "Размер",
  cfSpeed: "Скорость",
  cfGravity: "Гравитация",
  cfWind: "Ветер",
  cfDrift: "Дрейф",
  cfSpin: "Вращение",
  cfOpacity: "Непрозрачность частиц",
  cfEmitAsideBurst: "Вспышка b в момент b × интервал",
  cfEmitAsideContinuous: "Частиц в секунду = плотность",
  cfEmit: "Выброс",
  cfMode: "Режим",
  cfEmitMode: "Режим испускания",
  cfInterval: "Интервал",
  cfIntervalZero: "Интервал 0 — одна вспышка; после истечения времени жизни частиц экран пуст.",
  cfSettle: "Очистить перед концом",
  cfSettleOn: "В последний период жизни частиц перед концом новые частицы не появляются",
  cfSettleOff: "Продолжать до конца",
  cfOrigin: "Начало",
  cfOriginCustom: "Пользовательский",
  cfOriginRecipeMulti: (n: number) => `Из шаблона · ${quantity(n, "emitter")}`,
  cfOriginRecipe: "Из шаблона",
  cfOriginX: "Начало X",
  cfOriginY: "Начало Y",
  cfAngle: "Направление",
  cfSpread: "Разброс",
  cfAngleNote: "Направление −90° — вверх, 0° — вправо; источник может находиться за экраном (−20% … 120%).",
  cfRandomAside: "Одинаковый seed — одинаковая картинка",
  cfRandom: "Случайность",
  cfSeed: "Сид",
  cfReseed: "Другое",
  current: (name: string) => `${name} (текущий)`,
  cfCatalogNote: "Смена стиля восстанавливает его настройки шаблона (цвета, формы, движение частиц и испускание); сохраняется только seed, поэтому частицы остаются той же группой.",
  alignLeft: "Слева",
  alignCenter: "По центру",
  alignRight: "Справа",
  fontSize: "Размер",
  textColor: "Цвет текста",
  bold: "Полужирный",
  italic: "Курсив",
  underline: "Подчёркнутый",
  align: "Выравнивание",
  lineHeight: "Высота строки",
  letterSpacing: "Межбуквенный интервал",
  background: "Фон",
  backgroundPlate: "Форма фона",
  backgroundColor: "Цвет фона",
  padding: "Отступы",
  glow: "Свечение",
  glowColor: "Цвет свечения",
  intensity: "Интенсивность",
  range: "Диапазон",
  glowShadowNote: "Свечение и тень используют один слот эффекта; если включены оба, отображается только свечение.",
  shadow: "Тень",
  shadowColor: "Цвет тени",
  distance: "Расстояние",
  blur: "Размытие",
  angle: "Угол",
  clipLocked: "Клип заблокирован; разблокируйте его для изменения.",
  trackLocked: "Дорожка заблокирована; разблокируйте её на монтажной шкале.",
  unlock: "Разблокировать",
  custom: "Пользовательский",
  speedAside: "Длительность пересчитывается для новой скорости",
  speedChange: "Скорость",
  speedRate: "Скорость",
  speedNote: "Если удлинённый клип перекроет следующие, они не будут сдвинуты; изменение отклоняется.",
  sound: "Аудио",
  mute: "Без звука",
  volume: "Громкость",
  fadeIn: "Появление",
  fadeOut: "Исчезание",
  seconds: "с",
  timeAside: "Привязка к ближайшему кадру",
  time: "Время",
  start: "Начало",
  startAtPlayhead: "Установить начало на курсор воспроизведения",
  end: "Конец",
  endAtPlayhead: "Установить конец на курсор воспроизведения",
  duration: "Длительность",
  timecode: "Таймкод",
  sourceIn: "Начало в источнике",
  track: "Дорожка",
  editFps: (fps: string) => `Изменить частоту кадров ${fps}`,
  asset: "Материал",
  revision: (revision: number | string) => `Версия ${revision}`,
  secondsInputError: "Введите секунды (например, 10.5) или «min:sec»",
  secondsField: (label: string) => `${label} (с)`,
  deleteClip: "Удалить клип",
  trPrevious: "Объединить с предыдущим клипом",
  trNext: "Объединить со следующим клипом",
  trHintJoinedIn: "Переход от предыдущего клипа к этому; обоим нужен запас материала за границей склейки.",
  trHintJoinedOut: "Переход от этого клипа к следующему; обоим нужен запас материала за границей склейки.",
  trHintIn: "Переход от нижних слоёв к этому клипу.",
  trHintOut: "Переход от этого клипа к нижним слоям.",
  transition: "Переход",
  trSlot: "Положение перехода",
  trEffects: "Эффекты перехода",
  trUnknown: (kind: string) => `Переход на этой границе — ${kind}; эта версия его не распознаёт, поэтому в предпросмотре резкая склейка. Выбор другого заменит его.`,
  direction: "Направление",
  overlayColor: "Цвет наложения",
  easing: "Сглаживание движения",
  trJoin: "Объединить",
  trCrossfade: "Перекрёстное затухание аудио",
  trApplyNote: (hint: string) => `${hint} Выбор применяется сразу и может быть отменён.`,
  pageVideo: "Редактировать видео",
  pageImage: "Редактировать изображение",
  pageAudio: "Редактировать аудио",
  pageCaption: "Свойства субтитров",
  selectedClips: (n: number) => `Выбрано: ${quantity(n, "clip")}`,
  videoProperties: "Свойства видео",
  backToVideo: "Назад к свойствам видео",
  created: (n: number) => `Создано: ${n}`,
  updated: (n: number) => `Обновлено: ${n}`,
  deleted: (n: number) => `Удалено: ${n}`,
  lastChange: "Последнее изменение",
  lastChangeLabel: (label: string) => `Последнее изменение · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `Версия ${from} → ${to}`,
  changedObjects: (parts: string[]) => `Объекты: ${parts.join(" · ")}`,
  durationChange: (from: string, to: string) => `Длительность видео ${from} → ${to}`,
  undoAvailable: "Можно отменить (⌘Z или этот шаг в истории)",
  undoUnavailable: (reason: string) => `Нельзя отменить: ${reason}`,
  unknownReason: "неизвестная причина",
  requestedSeconds: (value: number | string) => `${value} с`,
  requestedFrame: (value: number | string) => `кадр ${value}`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `Запрошено ${requested} → фактически ${actual} (кадр ${frame}, ${fps})`,
  shiftMs: (ms: string) => `, отклонение ${ms} мс`,
  geometry: "Геометрия",
  anchor: "Опорная точка",
  measureFrom: (name: string) => `Измерять от ${name}`,
  width: "Ш",
  height: "В",
  lockRatio: "Сохранять пропорции",
  snapToPin: "Привязать к опорной точке",
  fullWidth: "Во всю ширину",
  fullHeight: "Во всю высоту",
  fitCanvas: "Подогнать под холст",
  fillCanvas: "Заполнить холст",
  rotation: "Поворот",
  flip: "Перевернуть",
  horizontal: "По горизонтали",
  vertical: "По вертикали",
  percentField: (label: string) => `${label} (%)`,
  rangeAside: "Обратный диапазон — полоса обратного отсчёта",
  progressRange: "Диапазон",
  rangeStart: "Начало",
  rangeEnd: "Конец",
  controls: "Элементы управления",
  minimum: "Минимум",
  maximum: "Максимум",
  smoothing: "Сглаживание",
  noColorControls: (label: string) => `«${label}» не имеет настроек цвета — цвета определяются самим стилем.`,
  styleTile: (label: string, count: number) => `Стиль: ${label}, ${quantity(count, "style")}, нажмите для выбора`,
  styleCount: (count: number) => `${quantity(count, "style")} · нажмите для выбора`,
  waveStyles: "Стили звуковой волны",
  progressStyles: "Стили прогресса",
  waveNote: "Настройки зависят от стиля: у «Осциллографа» и «Кольцевой волны» нет настроек dB; «Область спектра», «Точечная матрица», «Пульсирующее кольцо» и «Лента» используют два цвета.",
  progressNote: "Настройки зависят от стиля: две радужные рамки не имеют настроек цвета, а две движущиеся радуги имеют только цвет «Фона».",
  silentTrack: "(дорожка без аудио)",
  ducking: "Приглушать исходное аудио",
  duckUnder: "Приглушать под",
  duckUnderTrack: "Дорожка, под которую приглушать",
  duckSeveral: "Несколько дорожек или клипов",
  duckSpeech: "Это правило следует за участками речи; при выборе дорожки оно будет следовать только за ней.",
  duckItems: "Это правило следует за несколькими дорожками или клипами; при выборе дорожки оно будет следовать только за ней.",
  duckDepth: "Уменьшить на",
  advanced: "Дополнительно",
  attack: "Атака",
  release: "Восстановление",
  usingDefaults: "По умолчанию",
  usingYours: "Ваши значения",
  restoreDefaults: "Вернуть по умолчанию",
  duckShared: "Это правило приглушает и другие клипы; изменения относятся и к ним, а отключение выключает всё правило.",
  duckNothing: "На других дорожках пока нет аудио, поэтому приглушать не под что: сначала добавьте музыку, дубляж или речь на другую дорожку.",
  black: "Чёрный",
  aspect: "Соотношение сторон",
  aspectNote: "Короткая сторона сохраняется; положения записаны в процентах кадра, поэтому клипы следуют за холстом, а заполняющие его продолжают заполнять.",
  canvasBackground: "Фон",
  backdrop: "Подложка",
  canvasColor: "Цвет холста",
  specs: "Характеристики",
  size: "Размер",
  frameRate: "Частота кадров",
  contents: "Содержимое",
  contentsCount: (tracks: number, clips: number, assets: number) => `${quantity(tracks, "track")} · ${quantity(clips, "clip")} · ${quantity(assets, "asset")}`,
  videoNote: "Выберите клипы на монтажной шкале, чтобы увидеть их свойства. Удерживайте ⇧ или ⌘ и нажимайте для выбора нескольких.",
  colorAdjust: "Цветокоррекция",
  dropShadow: "Падающая тень",
  resetAll: "Сбросить всё",
  effects: "Эффекты",
  radius: "Радиус",
  offsetX: "Горизонтальное смещение",
  offsetY: "Вертикальное смещение",
  dropShadowColor: "Цвет тени",
  widthLabel: "Ширина",
  effectsNote: "Тень и обводка следуют прозрачным краям изображения; у непрозрачного видео — прямоугольнику. Размеры в пикселях при короткой стороне 540.",
  unknownEffects: (kinds: string[]) => `У этих эффектов нет настроек на этой странице: ${kinds.join(", ")}. Они сохраняются без изменений; предпросмотр пропускает их, а проверка перед экспортом перечисляет.`,
  overMax: (current: string, max: string) => `Текущее значение ${current} · максимум ползунка ${max}`,
  exactInput: (label: string) => `Ввести точное значение ${label}`,
  withUnit: (label: string, unit: string) => `${label} (${unit})`,
  colorValue: (label: string, value: string) => `${label}: ${value}`,
  saturationBrightness: (label: string) => `${label} насыщенности и яркости`,
  commonColors: "Общие цвета",
  fitContain: "Вписать",
  fitCover: "Заполнить",
  picture: "Изображение",
  fit: "Масштабирование",
  plateNote: "У этого клипа есть подложка или скруглённые углы, которые пока не отображаются в предпросмотре.",
  orderTranslationFirst: "Перевод сверху",
  orderOriginalFirst: "Оригинал сверху",
  editCaptionStyle: "Изменить стиль субтитров",
  loadingCaptionStyle: "Загрузка стиля субтитров…",
  captionSchema: (schema: string) => `Этот стиль субтитров — ${schema}; его пока нельзя редактировать здесь.`,
  noSchema: "(нет schema)",
  defaultStyle: "Стиль по умолчанию",
  textStyle: "Стиль текста",
  position: "Позиция",
  horizontalPos: "По горизонтали",
  bilingual: "Двуязычный",
  order: "Порядок",
  bilingualOrder: "Порядок двух языков",
  lineGap: "Межстрочный интервал",
  displayAside: "Относительно начала и конца предложения",
  display: "Отображение",
  lead: "Раньше",
  lag: "Позже",
  punctuation: "Пунктуация",
  punctToSpace: "Заменять запятые и точки пробелами",
};
