import type { InspectorMessages } from './inspector-copy.ts';

export const ko: InspectorMessages = {
  text: '텍스트',
  style: '스타일',
  textSchema: (schema: string) => `이 텍스트의 스타일 형식은 ${schema}입니다. 아직 여기서 편집할 수 없습니다.`,
  shape: '도형',
  fill: '채우기',
  color: '색상',
  fillColor: '채우기 색상',
  opacity: '불투명도',
  stroke: '윤곽선',
  strokeColor: '윤곽선 색상',
  strokeWidth: '두께',
  corner: '모서리 반경',
  titleAnimatedSticker: '애니메이션 스티커',
  titleSticker: '스티커',
  titleCounter: '카운터',
  titleText: '텍스트 편집',
  titleProgress: '진행 표시줄',
  titleVisualizer: '파형',
  titleConfetti: '색종이',
  titleDraw: '드로잉',
  titlePlaceholder: '자리 표시자',
  titleWhiteboard: '화이트보드',
  titleComposition: '합성',
  appearance: '모양',
  params: '매개변수',
  paramsReadOnly: (title: string) => `${title} 매개변수는 아직 여기서 편집할 수 없습니다.`,
  compositionReadOnly: '코드 합성의 매개변수는 자체 검증 규칙을 따르므로 아직 여기서 편집할 수 없습니다.',
  restoreColors: '원래 색상 복원',
  replaceColor: (source: string) => `${source} 바꾸기`,
  stickerUnknown: (id: string) => `스티커 템플릿 ${id || '(templateId 없음)'}을(를) 인식할 수 없습니다.`,
  loopLoop: '반복',
  loopOnce: '한 번 재생',
  loopHold: '정지 화면',
  playback: '재생',
  playMode: '재생 방식',
  countdown: '카운트다운',
  countup: '카운트업',
  formatS: '초',
  formatMmss: '분:초',
  formatHmmss: '시:분:초',
  timing: '타이밍',
  timingMode: '타이밍 방식',
  clockFace: '시계 형식',
  cfStyle: '스타일',
  cfStyleTile: (name: string) => `스타일: ${name}, 클릭해 변경`,
  cfBurst: '버스트',
  cfContinuous: '연속',
  cfMoreShapes: (n: number) => ` 외 ${n - 1}개`,
  cfChangeStyle: '스타일 변경',
  cfStyles: '색종이 스타일',
  cfReset: '레시피로 재설정',
  cfColorN: (n: number) => `색상 ${n}`,
  cfRemoveColorN: (n: number) => `색상 ${n} 제거`,
  cfConfettiColorN: (n: number) => `색종이 색상 ${n}`,
  cfAddColor: '색상 추가',
  cfColorsNote: '입자는 시드에 따라 이 색상들을 번갈아 사용합니다. 하나만 남기면 단색 색종이가 됩니다.',
  cfShapes: '색종이 모양',
  cfMotionAside: '1×는 레시피 그대로',
  cfMotion: '입자 움직임',
  cfCount: '버스트당 개수',
  cfUnit: '개',
  cfDensity: '밀도',
  cfRateUnit: '개/초',
  cfSize: '크기',
  cfSpeed: '속도',
  cfGravity: '중력',
  cfWind: '바람',
  cfDrift: '흔들림',
  cfSpin: '회전',
  cfOpacity: '입자 불투명도',
  cfEmitAsideBurst: 'b번째 버스트는 b × 간격 시점',
  cfEmitAsideContinuous: '초당 생성 수 = 밀도',
  cfEmit: '방출',
  cfMode: '모드',
  cfEmitMode: '방출 모드',
  cfInterval: '간격',
  cfIntervalZero: '간격 0 = 한 번만 방출합니다. 입자의 수명이 지나면 화면이 비어 있습니다.',
  cfSettle: '끝나기 전에 비우기',
  cfSettleOn: '끝나기 전 마지막 수명 구간에는 새 입자를 만들지 않음',
  cfSettleOff: '끝까지 계속',
  cfOrigin: '시작점',
  cfOriginCustom: '사용자 지정',
  cfOriginRecipeMulti: (n: number) => `레시피 따름 · 방출기 ${n}개`,
  cfOriginRecipe: '레시피 따름',
  cfOriginX: '시작점 X',
  cfOriginY: '시작점 Y',
  cfAngle: '방향',
  cfSpread: '퍼짐',
  cfAngleNote: '방향 −90°는 바로 위, 0°는 오른쪽입니다. 시작점은 화면 밖에 둘 수도 있습니다(−20% … 120%).',
  cfRandomAside: '같은 시드, 같은 화면',
  cfRandom: '무작위성',
  cfSeed: '시드',
  cfReseed: '다시 섞기',
  current: (name: string) => `${name}(현재)`,
  cfCatalogNote: '스타일을 바꾸면 그 스타일의 레시피 기본값으로 재설정되며(색상, 모양, 입자 움직임, 방출이 모두 바뀜) 시드만 유지됩니다. 그래서 스타일을 바꿔도 화면의 입자 무리는 같습니다.',
  alignLeft: '왼쪽',
  alignCenter: '가운데',
  alignRight: '오른쪽',
  fontSize: '크기',
  textColor: '텍스트 색상',
  bold: '굵게',
  italic: '기울임꼴',
  underline: '밑줄',
  align: '정렬',
  lineHeight: '줄 높이',
  letterSpacing: '자간',
  background: '배경',
  backgroundPlate: '배경 모양',
  backgroundColor: '배경 색상',
  padding: '여백',
  glow: '광채',
  glowColor: '광채 색상',
  intensity: '강도',
  range: '범위',
  glowShadowNote: '광채와 그림자는 효과 슬롯 하나를 함께 씁니다. 둘 다 켜면 광채만 그립니다.',
  shadow: '그림자',
  shadowColor: '그림자 색상',
  distance: '거리',
  blur: '흐림',
  angle: '각도',
  clipLocked: '이 클립은 잠겨 있습니다. 변경하려면 잠금을 해제하세요.',
  trackLocked: '이 클립의 트랙이 잠겨 있습니다. 변경하려면 타임라인에서 트랙 잠금을 해제하세요.',
  unlock: '잠금 해제',
  custom: '사용자 지정',
  speedAside: '길이는 새 속도로 다시 계산됩니다',
  speedChange: '속도',
  speedRate: '배속',
  speedNote: '길어진 클립이 뒤 클립을 덮게 되면 뒤 클립을 밀어내지 않고 변경이 거부됩니다.',
  sound: '오디오',
  mute: '음소거',
  volume: '볼륨',
  fadeIn: '페이드 인',
  fadeOut: '페이드 아웃',
  seconds: '초',
  timeAside: '가장 가까운 프레임에 맞춤',
  time: '시간',
  start: '시작',
  startAtPlayhead: '시작을 재생 헤드로 설정',
  end: '끝',
  endAtPlayhead: '끝을 재생 헤드로 설정',
  duration: '길이',
  timecode: '타임코드',
  sourceIn: '소스 시작점',
  track: '트랙',
  editFps: (fps: string) => `편집 프레임 레이트 ${fps}`,
  asset: '소재',
  revision: (revision: number | string) => `버전 ${revision}`,
  secondsInputError: '초(예: 10.5) 또는 “분:초”로 입력하세요',
  secondsField: (label: string) => `${label}(초)`,
  deleteClip: '클립 삭제',
  trPrevious: '이전 클립과 연결',
  trNext: '다음 클립과 연결',
  trHintJoinedIn: '이전 클립에서 이 클립으로 전환합니다. 두 클립 모두 컷 지점 너머에 여분의 미디어가 있어야 합니다.',
  trHintJoinedOut: '이 클립에서 다음 클립으로 전환합니다. 두 클립 모두 컷 지점 너머에 여분의 미디어가 있어야 합니다.',
  trHintIn: '아래 레이어에서 이 클립으로 전환합니다.',
  trHintOut: '이 클립에서 아래 레이어로 전환합니다.',
  transition: '전환',
  trSlot: '전환 위치',
  trEffects: '전환 효과',
  trUnknown: (kind: string) => `이 가장자리의 전환(${kind})은 이 버전에서 인식할 수 없어 미리보기에서는 하드 컷으로 그립니다. 하나를 선택하면 대체됩니다.`,
  direction: '방향',
  overlayColor: '오버레이 색상',
  easing: '이징',
  trJoin: '연결',
  trCrossfade: '오디오 크로스페이드',
  trApplyNote: (hint: string) => `${hint} 선택하면 바로 적용되며 실행 취소할 수 있습니다.`,
  pageVideo: '영상 편집',
  pageImage: '이미지 편집',
  pageAudio: '오디오 편집',
  pageCaption: '자막 속성',
  selectedClips: (n: number) => `클립 ${n}개 선택됨`,
  videoProperties: '영상 속성',
  backToVideo: '영상 속성으로 돌아가기',
  created: (n: number) => `생성 ${n}`,
  updated: (n: number) => `수정 ${n}`,
  deleted: (n: number) => `삭제 ${n}`,
  lastChange: '마지막 변경',
  lastChangeLabel: (label: string) => `마지막 변경 · ${label}`,
  revisionChange: (from: number | string, to: number | string) => `버전 ${from} → ${to}`,
  changedObjects: (parts: string[]) => `객체: ${parts.join(' · ')}`,
  durationChange: (from: string, to: string) => `영상 길이 ${from} → ${to}`,
  undoAvailable: '실행 취소할 수 있습니다(⌘Z 또는 기록에서 이 단계 실행 취소)',
  undoUnavailable: (reason: string) => `실행 취소할 수 없습니다: ${reason}`,
  unknownReason: '알 수 없는 이유',
  requestedSeconds: (value: number | string) => `${value}초`,
  requestedFrame: (value: number | string) => `프레임 ${value}`,
  resolution: (requested: string, actual: string, frame: number, fps: string) => `요청 ${requested} → 실제 ${actual}(프레임 ${frame}, ${fps})`,
  shiftMs: (ms: string) => `, ${ms} ms 어긋남`,
  geometry: '지오메트리',
  anchor: '고정점',
  measureFrom: (name: string) => `${name} 기준으로 측정`,
  width: '너비',
  height: '높이',
  lockRatio: '종횡비 고정',
  snapToPin: '고정점에 맞추기',
  fullWidth: '전체 너비',
  fullHeight: '전체 높이',
  fitCanvas: '캔버스에 맞추기',
  fillCanvas: '캔버스 채우기',
  rotation: '회전',
  flip: '뒤집기',
  horizontal: '가로',
  vertical: '세로',
  percentField: (label: string) => `${label}(%)`,
  rangeAside: '범위를 뒤집으면 카운트다운 막대',
  progressRange: '범위',
  rangeStart: '시작',
  rangeEnd: '끝',
  controls: '컨트롤',
  minimum: '최소',
  maximum: '최대',
  smoothing: '부드럽게',
  noColorControls: (label: string) => `“${label}”에는 색상 컨트롤이 없습니다. 색상은 스타일 자체에서 정해집니다.`,
  styleTile: (label: string, count: number) => `스타일: ${label}, 총 ${count}개, 클릭해 선택`,
  styleCount: (count: number) => `스타일 ${count}개 · 클릭해 선택`,
  waveStyles: '파형 스타일',
  progressStyles: '진행률 스타일',
  waveNote: '컨트롤은 스타일에 따라 달라집니다: 오실로스코프와 원형 파동에는 dB 컨트롤이 없고, 스펙트럼 영역 / 도트 매트릭스 / 펄스 링 / 리본은 두 가지 색상을 사용합니다.',
  progressNote: '컨트롤은 스타일에 따라 달라집니다: 무지개 테두리 두 가지에는 색상 컨트롤이 없고, 무지개 스네이크 두 가지에는 “배경” 색상만 있습니다.',
  silentTrack: '(오디오가 없는 트랙)',
  ducking: '원본 오디오 낮추기',
  duckUnder: '기준 트랙',
  duckUnderTrack: '낮출 때 기준이 되는 트랙',
  duckSeveral: '여러 트랙 또는 클립',
  duckSpeech: '이 규칙은 누군가 말하는 구간을 따릅니다. 트랙을 선택하면 그 트랙만 따르도록 바뀝니다.',
  duckItems: '이 규칙은 여러 트랙이나 클립을 따릅니다. 트랙을 선택하면 그 트랙만 따르도록 바뀝니다.',
  duckDepth: '낮출 양',
  advanced: '고급',
  attack: '어택',
  release: '릴리스',
  usingDefaults: '기본값 사용 중',
  usingYours: '입력한 값 사용 중',
  restoreDefaults: '기본값 복원',
  duckShared: '이 규칙은 다른 클립도 낮추므로 여기서 바꾸면 그 클립에도 적용됩니다. 끄면 규칙 전체가 비활성화됩니다.',
  duckNothing: '다른 트랙에 아직 오디오가 없어 낮출 기준이 없습니다. 먼저 다른 트랙에 음악, 더빙 또는 내레이션을 넣으세요.',
  black: '검정',
  aspect: '화면 비율',
  aspectNote: '짧은 변은 그대로 유지됩니다. 위치는 프레임 대비 백분율로 저장되므로 클립은 캔버스를 따라가고, 캔버스를 채우던 것은 계속 채웁니다.',
  canvasBackground: '캔버스 배경',
  backdrop: '배경색',
  canvasColor: '캔버스 색상',
  specs: '사양',
  size: '크기',
  frameRate: '프레임 레이트',
  contents: '내용',
  contentsCount: (tracks: number, clips: number, assets: number) => `트랙 ${tracks}개 · 클립 ${clips}개 · 소재 ${assets}개`,
  videoNote: '타임라인에서 클립을 선택하면 여기에 속성이 표시됩니다. ⇧ 또는 ⌘를 누른 채 클릭하면 여러 개를 선택할 수 있습니다.',
  colorAdjust: '색상 보정',
  dropShadow: '드롭 섀도',
  resetAll: '모두 재설정',
  effects: '효과',
  radius: '반경',
  offsetX: '가로 오프셋',
  offsetY: '세로 오프셋',
  dropShadowColor: '그림자 색상',
  widthLabel: '너비',
  effectsNote: '드롭 섀도와 윤곽선은 화면의 투명한 가장자리를 따릅니다. 불투명한 영상은 사각형 가장자리를 따릅니다. 길이는 짧은 변 540 기준 픽셀입니다.',
  unknownEffects: (kinds: string[]) => `이 페이지에 컨트롤이 없는 효과가 있습니다: ${kinds.join(', ')}. 그대로 유지되며, 미리보기에서는 건너뛰고 내보내기 전 검사에서 표시됩니다.`,
  overMax: (current: string, max: string) => `현재 ${current} · 슬라이더 최대 ${max}`,
  exactInput: (label: string) => `${label} 정확히 입력`,
  withUnit: (label: string, unit: string) => `${label}(${unit})`,
  colorValue: (label: string, value: string) => `${label}: ${value}`,
  saturationBrightness: (label: string) => `${label} 채도와 밝기`,
  commonColors: '자주 쓰는 색상',
  fitContain: '맞추기',
  fitCover: '채우기',
  picture: '화면',
  fit: '맞춤 방식',
  plateNote: '이 클립에는 배경판이나 둥근 모서리가 있지만 미리보기에는 아직 표시되지 않습니다.',
  orderTranslationFirst: '번역을 위에',
  orderOriginalFirst: '원문을 위에',
  editCaptionStyle: '자막 스타일 편집',
  loadingCaptionStyle: '자막 스타일 불러오는 중…',
  captionSchema: (schema: string) => `이 자막 스타일의 형식은 ${schema}입니다. 아직 여기서 편집할 수 없습니다.`,
  noSchema: '(schema 없음)',
  defaultStyle: '기본 스타일',
  textStyle: '텍스트 스타일',
  position: '위치',
  horizontalPos: '가로',
  bilingual: '이중 언어',
  order: '순서',
  bilingualOrder: '이중 언어 순서',
  lineGap: '줄 간격',
  displayAside: '문장의 시작과 끝 기준',
  display: '표시',
  lead: '앞당기기',
  lag: '늦추기',
  punctuation: '문장 부호',
  punctToSpace: '쉼표와 마침표를 공백으로 바꾸기',
};
