import type { AudioGenMessages, GeneratedMarkMessages, ImageGenMessages } from './media-gen-copy.ts';
import { pluralForm } from '@baocut/protocol';
export const esAudioGen: AudioGenMessages = {
 generate: 'Generar voz', clone: 'Clonar voz', generateTip: 'Leer texto en voz alta con un modelo en la nube y añadirlo a la biblioteca de materiales', cloneTip: 'Leer texto con una voz clonada de Mis voces', back: 'Volver a Audio', running: 'En curso en segundo plano', textPlaceholder: 'Texto que sintetizar; se divide en segmentos por puntos o saltos de línea…', clonePlaceholder: 'Qué debe decir esta voz…', cta: 'Generar', cloneCta: 'Generar con esta voz', hint: (provider) => `Se envía en línea a ${provider} para síntesis y se factura según sus reglas. El progreso aparece en la barra superior y Tareas en segundo plano; al terminar se añade a la biblioteca de materiales. Colocarlo en la línea de tiempo es otro paso. Dejar de esperar no retira una solicitud ya enviada.`, readOnly: 'Este vídeo es de solo lectura ahora, por lo que no se pueden generar materiales en él', noVoicesTitle: 'Aún no hay voces en Mis voces', noVoicesBody: 'Para clonar una voz, primero graba una o impórtala de un archivo en Modelos › Síntesis de voz › Mis voces; después súbela a un proveedor que clone voces (ElevenLabs). Vuelve y elígela entre las voces de abajo.', goVoices: 'Abrir Mis voces', runTitle: (title) => `${title}…`, runNote: 'Puedes seguir editando · la síntesis se ejecuta en segundo plano y se añade a la biblioteca de materiales al terminar.', cancel: 'Cancelar', cancelled: 'Cancelado', done: (meta) => `Generado · ${meta}`, inLibrary: (name) => `Añadido a la biblioteca de materiales · ${name}`, importing: 'Añadiendo a la biblioteca de materiales…', add: 'Añadir a la línea de tiempo', addTip: 'Colocar en el cabezal de reproducción', again: 'Generar otro', backToAudio: 'Volver a Audio', doneNote: 'El material está en la biblioteca Audio, marcado como «Generado». Arrástralo a la línea de tiempo o haz clic en «+» para colocarlo; puedes usarlo tantas veces como quieras.', failed: (message) => `No se pudo generar · ${message}`, edit: 'Editar y generar de nuevo', retried: 'Enviado de nuevo',
};
export const esImageGen: ImageGenMessages = {
 title: 'Imágenes', segments: 'Origen de la imagen', project: 'Materiales del vídeo', gen: 'Generado por IA', noModelTitle: 'Aún no hay un modelo de imágenes', noModelBody: 'Conecta un proveedor en la nube (Modelos › Generación de imágenes › Modelos en la nube) o descarga Qwen-Image-2.1 (Modelos › Generación de imágenes › Modelos locales); cualquiera sirve.', connect: 'Conectar un proveedor en la nube', downloadLocal: 'Descargar modelo local', fit: 'Igual que el lienzo del vídeo', recent: 'Reciente', all: (n) => `Los ${n} ${pluralForm('es', n, { one: 'lote', other: 'lotes' })}`, fewer: 'Solo los últimos 3 lotes', empty: 'Aún no se han generado imágenes para este vídeo. Las imágenes generadas van directamente a la biblioteca de materiales (marcadas como «Generado»); colocarlas en el lienzo es otro paso.', place: 'Colocar en el lienzo', placeTip: 'Colocar en el cabezal de reproducción', inLibrary: 'En la biblioteca de materiales', importing: 'Añadiendo a la biblioteca de materiales…', useAsRef: 'Usar como referencia', foot: 'Las imágenes generadas van directamente a la biblioteca de materiales de este vídeo, con su origen (modelo, parámetros, tarea) registrado en el material; el prompt permanece solo en el registro de la tarea. Colocarlas en el lienzo es otro paso.', readOnly: 'Este vídeo es de solo lectura ahora, por lo que no se pueden generar materiales en él', charCount: (chars, max) => `${chars} / ${max} caracteres`, charCountPlain: (chars) => `${chars} ${pluralForm('es', chars, { one: 'carácter', other: 'caracteres' })}`,
};
export const esMark: GeneratedMarkMessages = { generated: 'Generado' };
