import type { AudioGenMessages, GeneratedMarkMessages, ImageGenMessages } from './media-gen-copy.ts';

export const trMark: GeneratedMarkMessages = { generated: 'Oluşturuldu' };

export const trAudioGen: AudioGenMessages = {
generate: 'Konuşma oluştur', clone: 'Ses klonla', generateTip: 'Bulut modeliyle metni sesli oku ve medya kitaplığına ekle', cloneTip: 'Seslerim içinde klonlanmış sesle metni oku', back: 'Ses kısmına dön', running: 'Arka planda çalışıyor', textPlaceholder: 'Sentezlenecek metin; nokta veya satır sonunda parçalara bölünür…', clonePlaceholder: 'Bu ses ne söylesin…', cta: 'Oluştur', cloneCta: 'Bu sesle oluştur', hint: (provider) => `Sentez için ${provider} sağlayıcısına çevrimiçi gönderilir, kendi kurallarıyla ücretlendirilir. İlerleme üst çubukta ve Arka plan görevleri kısmında görünür; bitince medya kitaplığına eklenir. Zaman çizelgesine yerleştirmek ayrı adımdır. Beklemeyi durdurmak gönderilmiş isteği geri çağırmaz.`, readOnly: 'Video şu anda salt okunur; içine medya oluşturulamaz', noVoicesTitle: 'Seslerim içinde henüz ses yok', noVoicesBody: 'Ses klonlamak için önce Modeller › Konuşma sentezi › Seslerim içinde kayıt yapın veya dosyadan içe aktarın, sonra klonlama sunan sağlayıcıya (ElevenLabs) yükleyin. Geri dönüp aşağıdaki seslerden seçin.', goVoices: 'Seslerim aç', runTitle: (title) => `${title}…`, runNote: 'Düzenlemeye devam edebilirsiniz · sentez arka planda çalışır, bitince medya kitaplığına eklenir.', cancel: 'İptal', cancelled: 'İptal edildi', done: (meta) => `Oluşturuldu · ${meta}`, inLibrary: (name) => `Medya kitaplığına eklendi · ${name}`, importing: 'Medya kitaplığına ekleniyor…', add: 'Zaman çizelgesine ekle', addTip: 'Oynatma kafasına yerleştir', again: 'Başka oluştur', backToAudio: 'Ses kısmına dön', doneNote: 'Medya Ses kitaplığında “Oluşturuldu” işaretlidir. Zaman çizelgesine sürükleyin veya “+” ile yerleştirin; istediğiniz kadar kullanabilirsiniz.', failed: (message) => `Oluşturulamadı · ${message}`, edit: 'Düzenle ve yeniden oluştur', retried: 'Yeniden gönderildi',
};

export const trImageGen: ImageGenMessages = {
title: 'Görseller', segments: 'Görsel kaynağı', project: 'Video medyası', gen: 'AI oluşturdu', noModelTitle: 'Henüz görsel modeli yok', noModelBody: 'Bulut sağlayıcısı bağlayın (Modeller › Görsel oluşturma › Bulut modelleri) veya Qwen-Image-2.1 indirin (Modeller › Görsel oluşturma › Yerel modeller); ikisi de çalışır.', connect: 'Bulut sağlayıcısı bağla', downloadLocal: 'Yerel model indir', fit: 'Video tuvaliyle aynı', recent: 'Son', all: (n) => `${n} grubun tümü`, fewer: 'Yalnızca son 3 grup', empty: 'Bu video için henüz görsel oluşturulmadı. Oluşturulan görseller doğrudan medya kitaplığına gider (“Oluşturuldu” işaretli); tuvale yerleştirmek ayrı adımdır.', place: 'Tuvale yerleştir', placeTip: 'Oynatma kafasına yerleştir', inLibrary: 'Medya kitaplığında', importing: 'Medya kitaplığına ekleniyor…', useAsRef: 'Referans olarak kullan', foot: 'Oluşturulan görseller video medya kitaplığına doğrudan eklenir; kaynağı (model, parametreler, görev) medya ile kaydedilir, istem yalnızca görev kaydında kalır. Tuvale yerleştirmek ayrı adımdır.', readOnly: 'Video şu anda salt okunur; içine medya oluşturulamaz', charCount: (chars, max) => `${chars} / ${max} karakter`, charCountPlain: (chars) => `${chars} karakter`,
};
