import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';

const noun: Record<PlaceableKind, string> = { video: '영상', image: '이미지', audio: '오디오' };

export const ko: MediaMessages = {
  kindName: (kind: PlaceableKind): string => noun[kind],
  panelTitle: (kind: PlaceableKind): string => noun[kind],
  undo: '실행 취소',
  readOnly: '영상이 읽기 전용입니다',
  revealManaged: '영상 폴더로 모아 BaoCut이 관리하므로 별도의 파일 위치가 없습니다',
  revealUnknown: '이 파일에 기록된 위치를 찾을 수 없습니다',
  uses: '사용 위치',
  usesNone: '아직 타임라인에서 사용하지 않았습니다',
  replace: '교체…',
  replaceNone: '타임라인에서 사용하지 않아 교체할 것이 없습니다',
  collect: '영상 폴더로 모으기',
  collectNote: '원본 파일을 영상 폴더로 복사하고 원래 위치의 파일은 그대로 둡니다. 나중에 원본을 옮겨도 영향이 없습니다',
  remove: '영상에서 제거',
  removeNote: '아직 영상에서 소재를 제거할 수 없습니다: Runtime에 해당 작업이 없습니다',
  copied: (name: string) => `${name} 복사됨`,
  copyFailed: '복사하지 못했습니다. 다시 시도하세요.',
  collected: (name: string) => `“${name}”을(를) 영상 폴더로 모았습니다`,
  moreActions: (name: string) => `“${name}” 추가 작업`,
  preview: '미리 보기',
  copyName: '파일 이름 복사',
  usesCount: (n: number) => `타임라인에서 ${n}곳에 사용됨`,
  usesOf: (name: string) => `“${name}” 사용 위치`,
  replaceOne: (kind: PlaceableKind) => `타임라인의 이 ${noun[kind]} 교체`,
  replaceMany: (n: number) => `${n}개 모두 함께 교체`,
  previewFailed: (error: string) => `이 소재를 읽을 수 없습니다: ${error}`,
  previewLoading: '소재를 가져오는 중…',
  retry: '다시 시도',
  close: '닫기',
  importLabel: '소재 가져오기',
  imported: '소재 라이브러리로 가져옴 · 아직 타임라인에 없음',
  addClip: '클립 추가',
  addKind: (kind: PlaceableKind) => `${noun[kind]} 추가`,
  dropOrPick: (kind: PlaceableKind) => `파일을 여기에 놓거나 로컬 ${noun[kind]} 파일을 선택하세요`,
  import: '가져오기',
  existing: (kind: PlaceableKind) => `기존 ${noun[kind]}`,
  dubAnother: '다른 언어로 더빙',
  dubbedGroups: (n: number) => `${n}개 언어 더빙됨`,
  dubHintBefore: '영상이 다른 언어로 말하게 하려면 ',
  dubHintLink: '번역 더빙',
  dubHintAfter: '을 여세요. 더빙한 언어마다 여기에 그룹이 하나씩 생깁니다.',
  emptyLibrary: '소재 라이브러리에 아직 이 유형의 파일이 없습니다',
  emptyHint: '위의 상자로 파일을 끌어 오거나 “가져오기”를 클릭해 파일을 선택하세요.',
  foot: '가져오기는 파일을 소재 라이브러리에 추가할 뿐이며 파일은 원래 위치에 그대로 둡니다(링크). 영상 폴더로 복사하려면 소재의 ⋯ 메뉴에서 “영상 폴더로 모으기”를 사용하세요. 타임라인에 배치하는 것은 별도의 단계입니다. “+”를 클릭해 재생 헤드 위치에 놓거나 타임라인으로 끌어 놓으세요. 같은 소재를 여러 번 사용할 수 있습니다.',
  linked: '링크',
  pauseAuditionOf: (name: string) => `“${name}” 일시 정지`,
  auditionOf: (name: string) => `“${name}” 재생`,
  pauseAudition: '일시 정지',
  auditionTip: '이 오디오 재생',
  usedTimes: (n: number) => `타임라인에 있음 · ${n}곳`,
  unused: '미사용',
  addToTimelineOf: (name: string) => `“${name}”을(를) 타임라인에 추가`,
  addToTimelineTip: '타임라인에 추가(재생 헤드 위치)',
  auditionFailed: (name: string, error: string) => `“${name}”을(를) 재생하지 못했습니다: ${error}`,
  auditionFailedPlain: (name: string) => `“${name}”을(를) 재생하지 못했습니다`,
  replaceKind: (kind: PlaceableKind) => `${noun[kind]} 교체`,
  replacedOne: (kind: PlaceableKind) => `타임라인의 ${noun[kind]} 교체됨`,
  replacedMany: (kind: PlaceableKind, n: number) => `타임라인의 ${noun[kind]} 교체됨 · 클립 ${n}개`,
  replacingThis: '이 소재를 교체하는 중',
  replaceRule: '타임라인에서 이 소재를 사용하는 클립이 함께 교체됩니다. 위치, 자르기, 스타일, 볼륨은 유지되고 새 소재는 처음부터 재생됩니다. 새 소재가 더 짧으면 클립이 짧아지고 같은 트랙의 뒤쪽 클립이 앞으로 당겨집니다.',
  replaceCancelNote: '창을 닫으면 취소됩니다. 확인한 뒤에도 실행 취소할 수 있습니다.',
  pickNew: (kind: PlaceableKind) => `새 ${noun[kind]} 선택`,
  sourceTabs: '새 소재의 출처',
  localFile: '로컬 파일',
  searchExisting: (kind: PlaceableKind) => `기존 ${noun[kind]} 검색`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `기존 ${noun[kind]} 검색…`,
  noNameMatch: '이름이 일치하는 소재가 없습니다.',
  noOthers: (kind: PlaceableKind) => `이 영상에는 아직 다른 ${noun[kind]} 소재가 없습니다. 먼저 하나를 가져오거나 “로컬 파일”로 전환하세요.`,
  chooseLocal: (kind: PlaceableKind) => `로컬 ${noun[kind]} 파일 선택`,
  localNote: '파일이 영상 소재에 추가되고, 타임라인의 이 클립들을 교체하는 데 사용됩니다.',
  chooseAgain: '다른 파일 선택',
  chooseKindFile: (kind: PlaceableKind) => `${noun[kind]} 파일 선택`,
  alignNote: '원래 소재의 시간에 맞춤(같은 내용의 다른 버전)',
  replaceWith: (name: string) => `새 소재: ${name}`,
  noneChosen: '아직 새 소재를 선택하지 않았습니다',
  pickToReplace: '대신 넣을 소재를 선택하세요.',
  usingClips: '이 소재를 사용하는 클립',
  locked: '잠김',
  proxy: '합성의 사전 렌더링 대체본',
  keepAsIs: '변경 없음',
  cancel: '취소',
  confirmReplace: '교체',
};
