import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';

/** 句中用的素材类名。 */
const noun: Record<PlaceableKind, string> = { video: '视频', image: '图片', audio: '音频' };

export const zhHans: MediaMessages = {
  kindName: (kind: PlaceableKind): string => noun[kind],
  panelTitle: (kind: PlaceableKind): string => noun[kind],
  undo: '撤销',
  readOnly: '视频是只读的',
  revealManaged: '已收进视频目录，由 BaoCut 管理，没有单独的文件位置',
  revealUnknown: '找不到这个文件登记的位置',
  uses: '用在哪',
  usesNone: '时间线上还没用到',
  replace: '替换…',
  replaceNone: '时间线上没有用到它，不用替换',
  collect: '收进视频目录',
  collectNote: '把原文件复制进视频目录，原处的文件不动；之后移走原文件也不影响',
  remove: '从视频移除',
  removeNote: '还不能从视频里移除素材：Runtime 没有对应的操作',
  copied: (name: string) => `已复制 ${name}`,
  copyFailed: '复制失败，请重试',
  collected: (name: string) => `已把「${name}」收进视频目录`,
  moreActions: (name: string) => `「${name}」的更多操作`,
  preview: '预览',
  copyName: '复制文件名',
  usesCount: (n: number) => `时间线上 ${n} 处`,
  usesOf: (name: string) => `「${name}」用在哪`,
  replaceOne: (kind: PlaceableKind) => `换掉时间线上这段${noun[kind]}`,
  replaceMany: (n: number) => `${n} 段一起换`,
  previewFailed: (error: string) => `读不到这个素材：${error}`,
  previewLoading: '正在取素材…',
  retry: '重试',
  close: '关闭',
  importLabel: '导入素材',
  imported: '已导入素材库 · 还没放到时间线上',
  addClip: '添加片段',
  addKind: (kind: PlaceableKind) => `添加${noun[kind]}`,
  dropOrPick: (kind: PlaceableKind) => `拖入文件，或选择本地${noun[kind]}`,
  import: '导入',
  existing: (kind: PlaceableKind) => `已有${noun[kind]}`,
  dubAnother: '再配一种语言',
  dubbedGroups: (n: number) => `已配 ${n} 组`,
  dubHintBefore: '要让视频用另一种语言开口，打开',
  dubHintLink: '翻译配音',
  dubHintAfter: '；配好的每种语言在这里各成一组。',
  emptyLibrary: '素材库里还没有这一类文件',
  emptyHint: '拖进上面的框，或者点「导入」选文件。',
  foot: '导入只把文件收进素材库，文件留在原处（链接）；要复制进视频目录，用素材 ⋯ 里的「收进视频目录」。放到时间线是另一步：点「＋」放在播放头处，或拖到时间线上，同一个素材可以用很多次。',
  linked: '链接',
  pauseAuditionOf: (name: string) => `暂停试听「${name}」`,
  auditionOf: (name: string) => `试听「${name}」`,
  pauseAudition: '暂停试听',
  auditionTip: '试听这段音频',
  usedTimes: (n: number) => `已在时间线 · ${n} 处`,
  unused: '未使用',
  addToTimelineOf: (name: string) => `把「${name}」添加到时间线`,
  addToTimelineTip: '添加到时间线（播放头处）',
  auditionFailed: (name: string, error: string) => `没能试听「${name}」：${error}`,
  auditionFailedPlain: (name: string) => `没能试听「${name}」`,
  replaceKind: (kind: PlaceableKind) => `替换${noun[kind]}`,
  replacedOne: (kind: PlaceableKind) => `已替换时间线上的${noun[kind]}`,
  replacedMany: (kind: PlaceableKind, n: number) => `已替换时间线上的${noun[kind]} · ${n} 段`,
  replacingThis: '正在替换这个素材',
  replaceRule: '时间线上用到它的片段一起换：位置、裁剪、样式与音量保留，新素材从头用起；新素材不够长时片段变短，同一条轨道上后面的片段跟着往前挪。',
  replaceCancelNote: '关闭窗口可取消。确认后可撤销。',
  pickNew: (kind: PlaceableKind) => `选新的${noun[kind]}`,
  sourceTabs: '新素材从哪来',
  localFile: '本地文件',
  searchExisting: (kind: PlaceableKind) => `搜索已有${noun[kind]}`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `搜索已有${noun[kind]}…`,
  noNameMatch: '没有名字对得上的素材。',
  noOthers: (kind: PlaceableKind) => `视频里还没有别的${noun[kind]}。先导入一份，或者切到「本地文件」。`,
  chooseLocal: (kind: PlaceableKind) => `选择本地${noun[kind]}`,
  localNote: '文件会加入视频素材，用于替换时间线上的这些片段。',
  chooseAgain: '重新选择文件',
  chooseKindFile: (kind: PlaceableKind) => `选择${noun[kind]}文件`,
  alignNote: '按原素材时间对齐（同一段内容的另一个版本）',
  replaceWith: (name: string) => `替换为：${name}`,
  noneChosen: '尚未选择新素材',
  pickToReplace: '选一份素材，选了就能换。',
  usingClips: '用到它的片段',
  locked: '已锁定',
  proxy: '合成的预渲染替身',
  keepAsIs: '保持原样',
  cancel: '取消',
  confirmReplace: '确认替换',
};
