import { pluralForm } from '@baocut/protocol';
import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';

const noun: Record<PlaceableKind, string> = { video: 'vidéo', image: 'image', audio: 'audio' };

export const fr: MediaMessages = {
  kindName: (kind: PlaceableKind): string => ({ video: "Vidéo", image: "Images", audio: "Audio" })[kind],
  panelTitle: (kind: PlaceableKind): string => ({ video: "Vidéo", image: "Images", audio: "Audio" })[kind],
  undo: "Annuler",
  readOnly: "La vidéo est en lecture seule",
  revealManaged: "Rassemblé dans le dossier vidéo et géré par BaoCut ; aucun emplacement de fichier séparé",
  revealUnknown: "Emplacement enregistré pour ce fichier introuvable",
  uses: "Où il est utilisé",
  usesNone: "Pas encore utilisé sur la timeline",
  replace: "Remplacer…",
  replaceNone: "Absent de la timeline ; rien à remplacer",
  collect: "Rassembler dans le dossier vidéo",
  collectNote: "Copie le fichier original dans le dossier vidéo sans le déplacer ; déplacer l’original ensuite n’a aucun effet",
  remove: "Retirer de la vidéo",
  removeNote: "Les médias ne peuvent pas encore être retirés : aucune opération du Runtime pour cela",
  copied: (name: string) => `Copié : ${name}`,
  copyFailed: "Impossible de copier. Réessayez.",
  collected: (name: string) => `« ${name} » rassemblé dans le dossier vidéo`,
  moreActions: (name: string) => `Autres actions pour « ${name} »`,
  preview: "Aperçu",
  copyName: "Copier le nom du fichier",
  usesCount: (n: number) => `Utilisé à ${n} ${pluralForm('fr', n, { one: "emplacement", other: "emplacements" })} sur la timeline`,
  usesOf: (name: string) => `Où « ${name} » est utilisé`,
  replaceOne: (kind: PlaceableKind) => `Remplacer ce ${noun[kind]} sur la timeline`,
  replaceMany: (n: number) => `Remplacer tous les ${n} ensemble`,
  previewFailed: (error: string) => `Impossible de lire ce média : ${error}`,
  previewLoading: "Récupération du média…",
  retry: "Réessayer",
  close: "Fermer",
  importLabel: "Importer des médias",
  imported: "Importé dans la bibliothèque de médias · pas encore sur la timeline",
  addClip: "Ajouter un clip",
  addKind: (kind: PlaceableKind) => `Ajouter ${noun[kind]}`,
  dropOrPick: (kind: PlaceableKind) => `Déposez des fichiers ici ou choisissez un fichier local ${noun[kind]} fichier`,
  import: "Importer",
  existing: (kind: PlaceableKind): string => ({ video: "Vidéos existantes", image: "Images existantes", audio: "Audio existant" })[kind],
  dubAnother: "Doublage dans une autre langue",
  dubbedGroups: (n: number) => `${n} ${pluralForm('fr', n, { one: "langue", other: "langues" })} doublées`,
  dubHintBefore: "Pour faire parler la vidéo dans une autre langue, ouvrez ",
  dubHintLink: "Doublage traduit",
  dubHintAfter: " ; chaque langue doublée a son propre groupe ici.",
  emptyLibrary: "Aucun fichier de ce type dans la bibliothèque de médias",
  emptyHint: "Glissez des fichiers ci-dessus ou cliquez sur « Importer » pour les choisir.",
  foot: "Importer ajoute seulement les fichiers à la bibliothèque et les laisse à leur emplacement (liés) ; utilisez « Rassembler dans le dossier vidéo » dans le menu ⋯ pour les copier. Placement sur la timeline séparé : cliquez « + » à la tête de lecture ou glissez sur la timeline. Un média peut être réutilisé plusieurs fois.",
  linked: "Lié",
  pauseAuditionOf: (name: string) => `Mettre en pause « ${name} »`,
  auditionOf: (name: string) => `Lire « ${name} »`,
  pauseAudition: "Pause",
  auditionTip: "Lire cet audio",
  usedTimes: (n: number) => `Sur la timeline · ${n} ${pluralForm('fr', n, { one: "emplacement", other: "emplacements" })}`,
  unused: "Non utilisé",
  addToTimelineOf: (name: string) => `Ajouter « ${name} » à la timeline`,
  addToTimelineTip: "Ajouter à la timeline (à la tête de lecture)",
  auditionFailed: (name: string, error: string) => `Impossible de lire « ${name} » : ${error}`,
  auditionFailedPlain: (name: string) => `Impossible de lire « ${name} »`,
  replaceKind: (kind: PlaceableKind) => `Remplacer ${noun[kind]}`,
  replacedOne: (kind: PlaceableKind) => `Remplacé : ${noun[kind]} sur la timeline`,
  replacedMany: (kind: PlaceableKind, n: number) => `Remplacé : ${noun[kind]} sur la timeline · ${n} clips`,
  replacingThis: "Remplacement de ce média",
  replaceRule: "Tous les clips utilisant ce média sont remplacés : position, recadrage, style et volume conservés, nouveau média lu depuis son début. S’il est plus court, les clips raccourcissent et les suivants de la même piste avancent.",
  replacingClip: 'Remplacement de ce clip',
  replaceClipRule: 'Seul ce clip est remplacé ; les autres clips utilisant ce média ne changent pas. Position, recadrage, style et volume sont conservés, et le nouveau média est lu depuis son début. S’il est plus court, le clip raccourcit et les suivants de la même piste avancent.',
  replaceCancelNote: "Fermez la fenêtre pour annuler. Annulable après confirmation.",
  pickNew: (kind: PlaceableKind) => `Choisir le nouveau ${noun[kind]}`,
  sourceTabs: "Origine du nouveau média",
  localFile: "Fichier local",
  searchExisting: (kind: PlaceableKind) => `Rechercher parmi les ${noun[kind]}`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `Rechercher parmi les ${noun[kind]}…`,
  noNameMatch: "Aucun média ne porte ce nom.",
  noOthers: (kind: PlaceableKind) => `Aucun autre ${noun[kind]} dans cette vidéo. Importez-en un ou passez à « Fichier local ».`,
  chooseLocal: (kind: PlaceableKind) => `Choisir un fichier local ${noun[kind]} fichier`,
  localNote: "Le fichier est ajouté aux médias et remplace ces clips sur la timeline.",
  chooseAgain: "Choisir un autre fichier",
  chooseKindFile: (kind: PlaceableKind) => `Choisir ${noun[kind]} fichier`,
  alignNote: "Aligner sur les horaires du média original (autre version du même contenu)",
  replaceWith: (name: string) => `Remplacer par : ${name}`,
  noneChosen: "Aucun nouveau média choisi",
  pickToReplace: "Choisissez un média de remplacement.",
  usingClips: "Clips qui l’utilisent",
  locked: "Verrouillé",
  proxy: "Substitut prérendu d’une composition",
  keepAsIs: "Inchangé",
  cancel: "Annuler",
  confirmReplace: "Remplacer",
};
