import { pluralForm } from '@baocut/protocol';
import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';


const noun: Record<PlaceableKind, string> = { video: 'wideo', image: 'obraz', audio: 'audio' };

export const pl: MediaMessages = {
  kindName: (kind: PlaceableKind) => ({ video: "Wideo", image: "Obraz", audio: "Dźwięk" })[kind],
  panelTitle: (kind: PlaceableKind) => ({ video: "Wideo", image: "Obrazy", audio: "Dźwięk" })[kind],
  undo: "Cofnij",
  readOnly: "Wideo jest tylko do odczytu",
  revealManaged: "Zebrany w folderze wideo i zarządzany przez BaoCut; brak osobnej lokalizacji pliku",
  revealUnknown: "Nie można znaleźć zapisanej lokalizacji pliku",
  uses: "Gdzie używane",
  usesNone: "Jeszcze nie używane na osi czasu",
  replace: "Zastąp…",
  replaceNone: "Nie używane na osi czasu, nie ma czego zastąpić",
  collect: "Zbierz w folderze wideo",
  collectNote: "Kopiuje plik oryginalny do folderu wideo i zostawia na miejscu; późniejsze przeniesienie oryginału bez wpływu",
  remove: "Usuń z wideo",
  removeNote: "Nie można jeszcze usuwać materiałów z wideo: Runtime nie ma operacji",
  copied: (name: string) => `Skopiowano: ${name}`,
  copyFailed: "Nie udało się skopiować. Spróbuj ponownie.",
  collected: (name: string) => `Zebrano „${name}” w folderze wideo`,
  moreActions: (name: string) => `Więcej działań dla „${name}”`,
  preview: "Podgląd",
  copyName: "Kopiuj nazwę pliku",
  usesCount: (n: number) => `Używane w ${n} ${pluralForm('pl', n, { one: "miejsce", few: "miejsca", many: "miejsc", other: "miejsca" })} na osi czasu`,
  usesOf: (name: string) => `Gdzie używane „${name}”`,
  replaceOne: (kind: PlaceableKind) => `Zastąp: ${noun[kind]} na osi czasu`,
  replaceMany: (n: number) => `Zastąp wszystkie: ${n} razem`,
  previewFailed: (error: string) => `Nie można odczytać materiału: ${error}`,
  previewLoading: "Odczytywanie materiału…",
  retry: "Spróbuj ponownie",
  close: "Zamknij",
  importLabel: "Importuj materiały",
  imported: "Zaimportowano do biblioteki materiałów · jeszcze poza osią czasu",
  addClip: "Dodaj klip",
  addKind: (kind: PlaceableKind) => `Dodaj ${noun[kind]}`,
  dropOrPick: (kind: PlaceableKind) => `Przeciągnij pliki tutaj lub wybierz lokalny ${noun[kind]} plik`,
  import: "Importuj",
  existing: (kind: PlaceableKind) => ({ video: "Istniejące wideo", image: "Istniejące obrazy", audio: "Istniejące audio" })[kind],
  dubAnother: "Dubbing w innym języku",
  dubbedGroups: (n: number) => `${n} ${pluralForm('pl', n, { one: "język", few: "języki", many: "języków", other: "języka" })} z dubbingiem`,
  dubHintBefore: "Aby wideo mówiło w innym języku, otwórz ",
  dubHintLink: "Tłumaczony dubbing",
  dubHintAfter: "; każdy język dubbingu otrzymuje tutaj własną grupę.",
  emptyLibrary: "Biblioteka materiałów nie ma jeszcze takich plików",
  emptyHint: "Przeciągnij pliki powyżej lub kliknij „Importuj”, aby wybrać.",
  foot: "Import dodaje pliki do biblioteki materiałów i zostawia na miejscu (powiązane); aby skopiować do folderu wideo, użyj „Zbierz w folderze wideo” w menu ⋯. Umieszczenie na osi czasu osobno: kliknij „+” przy głowicy lub przeciągnij na oś czasu. Materiał można używać wielokrotnie.",
  linked: "Powiązane",
  pauseAuditionOf: (name: string) => `Wstrzymaj „${name}”`,
  auditionOf: (name: string) => `Odtwórz „${name}”`,
  pauseAudition: "Wstrzymaj",
  auditionTip: "Odtwórz audio",
  usedTimes: (n: number) => `Na osi czasu · ${n} ${pluralForm('pl', n, { one: "miejsce", few: "miejsca", many: "miejsc", other: "miejsca" })}`,
  unused: "Nieużywany",
  addToTimelineOf: (name: string) => `Dodaj „${name}” na oś czasu`,
  addToTimelineTip: "Dodaj na oś czasu (przy głowicy odtwarzania)",
  auditionFailed: (name: string, error: string) => `Nie udało się odtworzyć „${name}”: ${error}`,
  auditionFailedPlain: (name: string) => `Nie udało się odtworzyć „${name}”`,
  replaceKind: (kind: PlaceableKind) => `Zastąp ${noun[kind]}`,
  replacedOne: (kind: PlaceableKind) => `Zastąpiono materiał ${noun[kind]} na osi czasu`,
  replacedMany: (kind: PlaceableKind, n: number) => pluralForm('pl', n, { one: `Materiał ${noun[kind]} zastąpiono na osi czasu · ${n} klip`, few: `Materiał ${noun[kind]} zastąpiono na osi czasu · ${n} klipy`, many: `Materiał ${noun[kind]} zastąpiono na osi czasu · ${n} klipów`, other: `Materiał ${noun[kind]} zastąpiono na osi czasu · ${n} klipu` }),
  replacingThis: "Zastępowanie materiału",
  replaceRule: "Klipy tego materiału są zastępowane razem: pozycja, przycięcie, styl i głośność zachowane, nowy materiał od początku. Jeśli krótszy, klipy skracają się, późniejsze na tej samej ścieżce przesuwają wcześniej.",
  replaceCancelNote: "Zamknij okno, aby anulować. Po potwierdzeniu można cofnąć.",
  pickNew: (kind: PlaceableKind) => `Wybierz nowy materiał: ${noun[kind]}`,
  sourceTabs: "Źródło nowego materiału",
  localFile: "Plik lokalny",
  searchExisting: (kind: PlaceableKind) => `Szukaj istniejących: ${noun[kind]}`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `Szukaj istniejących: ${noun[kind]}…`,
  noNameMatch: "Brak materiałów o tej nazwie.",
  noOthers: (kind: PlaceableKind) => `W wideo nie ma jeszcze innego materiału typu ${noun[kind]}. Najpierw importuj lub wybierz „Plik lokalny”.`,
  chooseLocal: (kind: PlaceableKind) => `Wybierz lokalny materiał: ${noun[kind]} plik`,
  localNote: "Plik trafia do materiałów wideo i zastępuje klipy osi czasu.",
  chooseAgain: "Wybierz inny plik",
  chooseKindFile: (kind: PlaceableKind) => `Wybierz ${noun[kind]} plik`,
  alignNote: "Dopasuj do czasu oryginalnego materiału (inna wersja tej samej treści)",
  replaceWith: (name: string) => `Zastąp przez: ${name}`,
  noneChosen: "Nie wybrano jeszcze nowego materiału",
  pickToReplace: "Wybierz materiał do zastąpienia.",
  usingClips: "Używające klipy",
  locked: "Zablokowane",
  proxy: "Wyrenderowany zastępnik kompozycji",
  keepAsIs: "Bez zmian",
  cancel: "Anuluj",
  confirmReplace: "Wymień",
};
