import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';

const noun: Record<PlaceableKind, string> = { video: '影片', image: '圖片', audio: '音訊' };

export const zhHant: MediaMessages = {
  kindName: (kind: PlaceableKind): string => noun[kind],
  panelTitle: (kind: PlaceableKind): string => noun[kind],
  undo: '還原',
  readOnly: '影片為唯讀',
  revealManaged: '已收集到影片資料夾並由 BaoCut 管理，沒有單獨的檔案位置',
  revealUnknown: '找不到這個檔案記錄的位置',
  uses: '使用位置',
  usesNone: '尚未在時間軸上使用',
  replace: '替換…',
  replaceNone: '未在時間軸上使用，因此沒有可替換的內容',
  collect: '收集到影片資料夾',
  collectNote: '將原始檔案複製到影片資料夾，原始檔案保留在原處；之後移動原始檔案也不受影響',
  remove: '從影片移除',
  removeNote: '目前還無法從影片移除素材：Runtime 沒有對應的操作',
  copied: (name: string) => `已複製 ${name}`,
  copyFailed: '無法複製，請重試。',
  collected: (name: string) => `已將「${name}」收集到影片資料夾`,
  moreActions: (name: string) => `「${name}」的更多操作`,
  preview: '預覽',
  copyName: '複製檔案名稱',
  usesCount: (n: number) => `在時間軸上使用了 ${n} 處`,
  usesOf: (name: string) => `「${name}」的使用位置`,
  replaceOne: (kind: PlaceableKind) => `替換時間軸上的這個${noun[kind]}`,
  replaceMany: (n: number) => `一起替換全部 ${n} 個`,
  previewFailed: (error: string) => `無法讀取這個素材：${error}`,
  previewLoading: '正在取得素材…',
  retry: '重試',
  close: '關閉',
  importLabel: '匯入素材',
  imported: '已匯入媒體庫 · 尚未放到時間軸上',
  addClip: '新增片段',
  addKind: (kind: PlaceableKind) => `新增${noun[kind]}`,
  dropOrPick: (kind: PlaceableKind) => `將檔案拖放到這裡，或選擇本機${noun[kind]}檔案`,
  import: '匯入',
  existing: (kind: PlaceableKind) => `現有${noun[kind]}`,
  dubAnother: '用其他語言配音',
  dubbedGroups: (n: number) => `已配音 ${n} 種語言`,
  dubHintBefore: '要讓影片說另一種語言，請開啟',
  dubHintLink: '翻譯配音',
  dubHintAfter: '；每種配好的語言都會在這裡成為一組。',
  emptyLibrary: '媒體庫中還沒有這類檔案',
  emptyHint: '將檔案拖曳到上方的方框，或按一下「匯入」選擇檔案。',
  foot: '匯入只會將檔案加入媒體庫，並保留在原處（連結）；要將檔案複製到影片資料夾，請使用素材 ⋯ 選單中的「收集到影片資料夾」。放到時間軸上是另一個步驟：按一下「+」放到播放頭處，或拖曳到時間軸上。同一個素材可以使用多次。',
  linked: '已連結',
  pauseAuditionOf: (name: string) => `暫停「${name}」`,
  auditionOf: (name: string) => `播放「${name}」`,
  pauseAudition: '暫停',
  auditionTip: '播放這段音訊',
  usedTimes: (n: number) => `在時間軸上 · ${n} 處`,
  unused: '未使用',
  addToTimelineOf: (name: string) => `將「${name}」新增到時間軸`,
  addToTimelineTip: '新增到時間軸（播放頭處）',
  auditionFailed: (name: string, error: string) => `無法播放「${name}」：${error}`,
  auditionFailedPlain: (name: string) => `無法播放「${name}」`,
  replaceKind: (kind: PlaceableKind) => `替換${noun[kind]}`,
  replacedOne: (kind: PlaceableKind) => `已替換時間軸上的${noun[kind]}`,
  replacedMany: (kind: PlaceableKind, n: number) => `已替換時間軸上的${noun[kind]} · ${n} 個片段`,
  replacingThis: '正在替換這個素材',
  replaceRule: '時間軸上使用它的片段會一起替換：保留位置、裁切、樣式與音量，新素材從開頭播放。如果新素材較短，片段會變短，同一軌道上後面的片段會往前移。',
  replaceCancelNote: '關閉視窗即可取消。確認後可以還原。',
  pickNew: (kind: PlaceableKind) => `選擇新的${noun[kind]}`,
  sourceTabs: '新素材的來源',
  localFile: '本機檔案',
  searchExisting: (kind: PlaceableKind) => `搜尋現有${noun[kind]}`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `搜尋現有${noun[kind]}…`,
  noNameMatch: '沒有名稱相符的素材。',
  noOthers: (kind: PlaceableKind) => `這部影片中還沒有其他${noun[kind]}。請先匯入，或切換到「本機檔案」。`,
  chooseLocal: (kind: PlaceableKind) => `選擇本機${noun[kind]}檔案`,
  localNote: '檔案會加入影片的素材，並用來替換時間軸上的這些片段。',
  chooseAgain: '選擇其他檔案',
  chooseKindFile: (kind: PlaceableKind) => `選擇${noun[kind]}檔案`,
  alignNote: '對齊原始素材的時間（同一內容的另一個版本）',
  replaceWith: (name: string) => `替換為：${name}`,
  noneChosen: '尚未選擇新素材',
  pickToReplace: '請選擇要用來替換的素材。',
  usingClips: '使用它的片段',
  locked: '已鎖定',
  proxy: '合成的預先渲染替代版本',
  keepAsIs: '不變',
  cancel: '取消',
  confirmReplace: '替換',
};
