import { pluralForm } from '@baocut/protocol';
import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';

const noun: Record<PlaceableKind, string> = { video: 'vídeo', image: 'imagem', audio: 'áudio' };

export const ptBR: MediaMessages = {
  kindName: (kind: PlaceableKind): string => ({ video: "Vídeo", image: "Imagem", audio: "Áudio" })[kind],
  panelTitle: (kind: PlaceableKind): string => ({ video: "Vídeo", image: "Imagens", audio: "Áudio" })[kind],
  undo: "Desfazer",
  readOnly: "Vídeo em leitura apenas",
  revealManaged: "Coletado na pasta do vídeo e gerenciado pelo BaoCut; sem local separado",
  revealUnknown: "Local registrado do arquivo não encontrado",
  uses: "Onde é usado",
  usesNone: "Ainda não usado na linha do tempo",
  replace: "Substituir…",
  replaceNone: "Não usado na linha do tempo; nada para substituir",
  collect: "Coletar na pasta do vídeo",
  collectNote: "Copia o original para a pasta do vídeo sem movê-lo; mover o original depois não afeta",
  remove: "Remover do vídeo",
  removeNote: "Mídias ainda não podem ser removidas; o Runtime não tem operação para isso",
  copied: (name: string) => `Copiado ${name}`,
  copyFailed: "Não foi possível copiar. Tente novamente.",
  collected: (name: string) => `Coletado “${name}” na pasta do vídeo`,
  moreActions: (name: string) => `Mais ações de “${name}”`,
  preview: "Visualização",
  copyName: "Copiar nome do arquivo",
  usesCount: (n: number) => `Usado em ${n} ${pluralForm('pt-BR', n, { one: "local", other: "locais" })} na linha do tempo`,
  usesOf: (name: string) => `Onde “${name}” é usado`,
  replaceOne: (kind: PlaceableKind) => `Substituir este ${noun[kind]} na linha do tempo`,
  replaceMany: (n: number) => `Substituir todos os ${n} juntos`,
  previewFailed: (error: string) => `Não foi possível ler esta mídia: ${error}`,
  previewLoading: "Obtendo a mídia…",
  retry: "Tentar novamente",
  close: "Fechar",
  importLabel: "Importar mídias",
  imported: "Importado à biblioteca · ainda fora da linha do tempo",
  addClip: "Adicionar clipe",
  addKind: (kind: PlaceableKind) => `Adicionar ${noun[kind]}`,
  dropOrPick: (kind: PlaceableKind) => `Solte arquivos aqui ou escolha um arquivo local de ${noun[kind]} arquivo`,
  import: "Importar",
  existing: (kind: PlaceableKind): string => ({ video: "Vídeos existentes", image: "Imagens existentes", audio: "Áudio existente" })[kind],
  dubAnother: "Dublagem em outro idioma",
  dubbedGroups: (n: number) => `${n} ${pluralForm('pt-BR', n, { one: "idioma", other: "idiomas" })} dublados`,
  dubHintBefore: "Para o vídeo falar outro idioma, abra ",
  dubHintLink: "Dublagem traduzida",
  dubHintAfter: "; cada idioma dublado ganha um grupo aqui.",
  emptyLibrary: "Sem arquivos deste tipo na biblioteca",
  emptyHint: "Arraste acima ou clique “Importar” para escolher.",
  foot: "Importar adiciona à biblioteca e deixa arquivos no local (vinculados); para copiar à pasta do vídeo, use “Coletar na pasta do vídeo” no menu ⋯. Colocar na linha do tempo é separado: “+” no indicador de reprodução ou arraste. A mídia pode ser usada várias vezes.",
  linked: "Vinculado",
  pauseAuditionOf: (name: string) => `Pausar “${name}”`,
  auditionOf: (name: string) => `Reproduzir “${name}”`,
  pauseAudition: "Pausar",
  auditionTip: "Reproduzir este áudio",
  usedTimes: (n: number) => `Na linha do tempo · ${n} ${pluralForm('pt-BR', n, { one: "local", other: "locais" })}`,
  unused: "Não usado",
  addToTimelineOf: (name: string) => `Adicionar “${name}” à linha do tempo`,
  addToTimelineTip: "Adicionar à linha do tempo (no indicador de reprodução)",
  auditionFailed: (name: string, error: string) => `Não foi possível reproduzir “${name}”: ${error}`,
  auditionFailedPlain: (name: string) => `Não foi possível reproduzir “${name}”`,
  replaceKind: (kind: PlaceableKind) => `Substituir ${noun[kind]}`,
  replacedOne: (kind: PlaceableKind) => `Substituído ${noun[kind]} na linha do tempo`,
  replacedMany: (kind: PlaceableKind, n: number) => `Substituído ${noun[kind]} na linha do tempo · ${n} clipes`,
  replacingThis: "Substituindo esta mídia",
  replaceRule: "Todos os clipes que usam a mídia são substituídos: posição, recorte, estilo e volume mantidos; nova mídia começa do início. Se menor, clipes encurtam e os seguintes avançam.",
  replaceCancelNote: "Feche para cancelar. Você pode desfazer após confirmar.",
  pickNew: (kind: PlaceableKind) => `Escolher nova mídia de ${noun[kind]}`,
  sourceTabs: "Origem da nova mídia",
  localFile: "Arquivo local",
  searchExisting: (kind: PlaceableKind) => `Buscar existentes de ${noun[kind]}`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `Buscar existentes de ${noun[kind]}…`,
  noNameMatch: "Nenhuma mídia corresponde ao nome.",
  noOthers: (kind: PlaceableKind) => `Ainda não há outro arquivo de ${noun[kind]} neste vídeo. Importe ou use “Arquivo local”.`,
  chooseLocal: (kind: PlaceableKind) => `Escolher arquivo local de ${noun[kind]} arquivo`,
  localNote: "O arquivo é adicionado às mídias e substitui estes clipes na linha do tempo.",
  chooseAgain: "Escolher outro arquivo",
  chooseKindFile: (kind: PlaceableKind) => `Escolher ${noun[kind]} arquivo`,
  alignNote: "Alinhar ao tempo original (outra versão do mesmo conteúdo)",
  replaceWith: (name: string) => `Substituir por: ${name}`,
  noneChosen: "Nenhuma nova mídia escolhida",
  pickToReplace: "Escolha uma mídia para substituir.",
  usingClips: "Clipes que usam esta mídia",
  locked: "Travado",
  proxy: "Substituto pré-renderizado de composição",
  keepAsIs: "mantido",
  cancel: "Cancelar",
  confirmReplace: "Substituir",
};
