import type { PlaceableKind } from '../../model/editor-ops.ts';
import type { MediaMessages } from './media-copy.ts';

const noun: Record<PlaceableKind, string> = { video: '動画', image: '画像', audio: '音声' };

export const ja: MediaMessages = {
  kindName: (kind: PlaceableKind): string => noun[kind],
  panelTitle: (kind: PlaceableKind): string => noun[kind],
  undo: '取り消す',
  readOnly: '動画は読み取り専用です',
  revealManaged: '動画フォルダに取り込まれ BaoCut が管理しているため、個別のファイルの場所はありません',
  revealUnknown: 'このファイルに記録された場所が見つかりません',
  uses: '使用箇所',
  usesNone: 'タイムラインではまだ使われていません',
  replace: '置き換え…',
  replaceNone: 'タイムラインで使われていないため、置き換える必要はありません',
  collect: '動画フォルダに取り込む',
  collectNote: '元のファイルを動画フォルダにコピーし、元の場所のファイルはそのまま残します。後で元のファイルを移動しても影響しません',
  remove: '動画から削除',
  removeNote: 'まだ動画から素材を削除できません：Runtime に対応する操作がありません',
  copied: (name: string) => `${name} をコピーしました`,
  copyFailed: 'コピーできませんでした。再試行してください。',
  collected: (name: string) => `「${name}」を動画フォルダに取り込みました`,
  moreActions: (name: string) => `「${name}」のその他の操作`,
  preview: 'プレビュー',
  copyName: 'ファイル名をコピー',
  usesCount: (n: number) => `タイムライン上の ${n} か所で使用`,
  usesOf: (name: string) => `「${name}」の使用箇所`,
  replaceOne: (kind: PlaceableKind) => `タイムライン上のこの${noun[kind]}を置き換え`,
  replaceMany: (n: number) => `${n} 個をまとめて置き換え`,
  previewFailed: (error: string) => `この素材を読み取れません：${error}`,
  previewLoading: '素材を取得中…',
  retry: '再試行',
  close: '閉じる',
  importLabel: '素材を読み込む',
  imported: '素材ライブラリに読み込みました · まだタイムラインには配置していません',
  addClip: 'クリップを追加',
  addKind: (kind: PlaceableKind) => `${noun[kind]}を追加`,
  dropOrPick: (kind: PlaceableKind) => `ファイルをドロップするか、ローカルの${noun[kind]}ファイルを選択`,
  import: '読み込む',
  existing: (kind: PlaceableKind) => `既存の${noun[kind]}`,
  dubAnother: '別の言語で吹き替え',
  dubbedGroups: (n: number) => `${n} 言語を吹き替え済み`,
  dubHintBefore: '動画を別の言語で話させるには、',
  dubHintLink: '翻訳吹き替え',
  dubHintAfter: 'を開いてください。吹き替えた言語ごとに、ここにグループが作られます。',
  emptyLibrary: '素材ライブラリにはまだこの種類のファイルがありません',
  emptyHint: '上の枠にファイルをドラッグするか、「読み込む」をクリックしてファイルを選択してください。',
  foot: '読み込みではファイルを素材ライブラリに追加するだけで、ファイルは元の場所に残ります（リンク）。動画フォルダにコピーするには、素材の ⋯ メニューの「動画フォルダに取り込む」を使います。タイムラインへの配置は別の手順です：「＋」をクリックして再生ヘッドの位置に配置するか、タイムラインにドラッグします。同じ素材を何度でも使えます。',
  linked: 'リンク',
  pauseAuditionOf: (name: string) => `「${name}」を一時停止`,
  auditionOf: (name: string) => `「${name}」を再生`,
  pauseAudition: '一時停止',
  auditionTip: 'この音声を再生',
  usedTimes: (n: number) => `タイムライン上 · ${n} か所`,
  unused: '未使用',
  addToTimelineOf: (name: string) => `「${name}」をタイムラインに追加`,
  addToTimelineTip: 'タイムラインに追加（再生ヘッドの位置）',
  auditionFailed: (name: string, error: string) => `「${name}」を再生できませんでした：${error}`,
  auditionFailedPlain: (name: string) => `「${name}」を再生できませんでした`,
  replaceKind: (kind: PlaceableKind) => `${noun[kind]}を置き換え`,
  replacedOne: (kind: PlaceableKind) => `タイムライン上の${noun[kind]}を置き換えました`,
  replacedMany: (kind: PlaceableKind, n: number) => `タイムライン上の${noun[kind]}を置き換えました · ${n} 個のクリップ`,
  replacingThis: 'この素材を置き換えています',
  replaceRule: 'タイムライン上でこの素材を使っているクリップをまとめて置き換えます。位置、クロップ、スタイル、音量は保持され、新しい素材は先頭から使われます。新しい素材のほうが短い場合はクリップが短くなり、同じトラックの後ろのクリップが前に詰められます。',
  replaceCancelNote: 'ウインドウを閉じるとキャンセルできます。確定後も取り消せます。',
  pickNew: (kind: PlaceableKind) => `新しい${noun[kind]}を選択`,
  sourceTabs: '新しい素材の取得元',
  localFile: 'ローカルファイル',
  searchExisting: (kind: PlaceableKind) => `既存の${noun[kind]}を検索`,
  searchExistingPlaceholder: (kind: PlaceableKind) => `既存の${noun[kind]}を検索…`,
  noNameMatch: '名前が一致する素材はありません。',
  noOthers: (kind: PlaceableKind) => `この動画にはまだほかの${noun[kind]}がありません。先に読み込むか、「ローカルファイル」に切り替えてください。`,
  chooseLocal: (kind: PlaceableKind) => `ローカルの${noun[kind]}ファイルを選択`,
  localNote: 'ファイルは動画の素材に追加され、タイムライン上のこれらのクリップの置き換えに使われます。',
  chooseAgain: '別のファイルを選択',
  chooseKindFile: (kind: PlaceableKind) => `${noun[kind]}ファイルを選択`,
  alignNote: '元の素材のタイミングに合わせる（同じ内容の別バージョン）',
  replaceWith: (name: string) => `置き換え先：${name}`,
  noneChosen: '新しい素材はまだ選択されていません',
  pickToReplace: '置き換える素材を選択してください。',
  usingClips: 'この素材を使っているクリップ',
  locked: 'ロック中',
  proxy: 'コンポジションのプリレンダリング代替',
  keepAsIs: '変更なし',
  cancel: 'キャンセル',
  confirmReplace: '置き換える',
};
