import type { AudioGenMessages, GeneratedMarkMessages, ImageGenMessages } from './media-gen-copy.ts';

export const viMark: GeneratedMarkMessages = { generated: 'Đã tạo' };

export const viAudioGen: AudioGenMessages = {
generate: 'Tạo giọng nói', clone: 'Nhân bản giọng', generateTip: 'Đọc văn bản bằng mô hình đám mây và thêm vào thư viện tư liệu', cloneTip: 'Đọc bằng giọng đã nhân bản trong Giọng của tôi', back: 'Trở về Âm thanh', running: 'Đang chạy nền', textPlaceholder: 'Văn bản cần tổng hợp; tách đoạn tại dấu chấm hoặc xuống dòng…', clonePlaceholder: 'Giọng này nên nói gì…', cta: 'Tạo', cloneCta: 'Tạo bằng giọng này', hint: (provider) => `Gửi trực tuyến đến ${provider} để tổng hợp và tính phí theo quy tắc của họ. Tiến độ hiện trên thanh đầu và Tác vụ nền; khi xong thêm vào thư viện tư liệu, đặt trên dòng thời gian là bước riêng. Dừng chờ không thu hồi yêu cầu đã gửi.`, readOnly: 'Video hiện chỉ đọc nên không tạo tư liệu vào được', noVoicesTitle: 'Giọng của tôi chưa có giọng', noVoicesBody: 'Để nhân bản, ghi âm hoặc nhập tệp trong Mô hình › Tổng hợp giọng nói › Giọng của tôi trước rồi tải lên nhà cung cấp có thể nhân bản (ElevenLabs). Trở lại và chọn giọng bên dưới.', goVoices: 'Mở Giọng của tôi', runTitle: (title) => `${title}…`, runNote: 'Có thể tiếp tục chỉnh sửa · tổng hợp chạy nền, khi xong thêm vào thư viện tư liệu.', cancel: 'Hủy', cancelled: 'Đã hủy', done: (meta) => `Đã tạo · ${meta}`, inLibrary: (name) => `Đã thêm vào thư viện tư liệu · ${name}`, importing: 'Đang thêm vào thư viện tư liệu…', add: 'Thêm lên dòng thời gian', addTip: 'Đặt tại đầu phát', again: 'Tạo thêm', backToAudio: 'Trở về Âm thanh', doneNote: 'Tư liệu trong thư viện Âm thanh, đánh dấu “Đã tạo”. Kéo lên dòng thời gian hoặc nhấp “+”; dùng bao nhiêu lần cũng được.', failed: (message) => `Không tạo được · ${message}`, edit: 'Chỉnh sửa và tạo lại', retried: 'Đã gửi lại',
};

export const viImageGen: ImageGenMessages = {
title: 'Hình ảnh', segments: 'Nguồn hình ảnh', project: 'Tư liệu video', gen: 'AI tạo', noModelTitle: 'Chưa có mô hình hình ảnh', noModelBody: 'Kết nối nhà cung cấp đám mây (Mô hình › Tạo hình ảnh › Mô hình đám mây) hoặc tải Qwen-Image-2.1 (Mô hình › Tạo hình ảnh › Mô hình cục bộ); cách nào cũng dùng được.', connect: 'Kết nối nhà cung cấp đám mây', downloadLocal: 'Tải mô hình cục bộ', fit: 'Giống khung vẽ video', recent: 'Gần đây', all: (n) => `Tất cả ${n} nhóm`, fewer: 'Chỉ 3 nhóm cuối', empty: 'Chưa tạo hình ảnh cho video này. Hình tạo vào thẳng thư viện tư liệu (đánh dấu “Đã tạo”); đặt trên khung vẽ là bước riêng.', place: 'Đặt trên khung vẽ', placeTip: 'Đặt tại đầu phát', inLibrary: 'Trong thư viện tư liệu', importing: 'Đang thêm vào thư viện tư liệu…', useAsRef: 'Dùng làm tham chiếu', foot: 'Hình tạo vào thẳng thư viện tư liệu video, ghi nguồn (mô hình, tham số, tác vụ) cùng tư liệu; lời nhắc chỉ trong bản ghi tác vụ. Đặt trên khung vẽ là bước riêng.', readOnly: 'Video hiện chỉ đọc nên không tạo tư liệu vào được', charCount: (chars, max) => `${chars} / ${max} ký tự`, charCountPlain: (chars) => `${chars} ký tự`,
};
