import type { AudioGenMessages, GeneratedMarkMessages, ImageGenMessages } from './media-gen-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const itMark: GeneratedMarkMessages = { generated: 'Generato' };

export const itAudioGen: AudioGenMessages = {
  generate: 'Genera voce', clone: 'Clona voce', generateTip: 'Leggi testo ad alta voce con un modello cloud e aggiungilo alla libreria dei materiali', cloneTip: 'Leggi testo con una voce clonata in «Le mie voci»', back: 'Torna ad Audio', running: 'In esecuzione in background', textPlaceholder: 'Testo da sintetizzare; diviso in segmenti ai punti o alle interruzioni di riga…', clonePlaceholder: 'Cosa deve dire questa voce…', cta: 'Genera', cloneCta: 'Genera con questa voce',
  hint: (provider: string) => `Inviato online a ${provider} per la sintesi, con addebito secondo le sue regole. L’avanzamento appare nella barra superiore e in «Attività in background»; al termine viene aggiunto alla libreria dei materiali, mentre l’inserimento nella timeline è un passaggio separato. Smettere di attendere non ritira una richiesta già inviata.`,
  readOnly: 'Questo video è attualmente di sola lettura, quindi non puoi generarvi materiali', noVoicesTitle: 'Nessuna voce ancora in «Le mie voci»', noVoicesBody: 'Per clonare una voce, registra o importa prima da un file in Modelli › Sintesi vocale › Le mie voci, poi caricala su un provider capace di clonare (ElevenLabs). Torna qui e sceglila dalle voci sotto.', goVoices: 'Apri Le mie voci', runTitle: (title: string) => `${title}…`, runNote: 'Puoi continuare a modificare · la sintesi viene eseguita in background e aggiunta alla libreria dei materiali al termine.', cancel: 'Annulla', cancelled: 'Annullato', done: (meta: string) => `Generato · ${meta}`, inLibrary: (name: string) => `Aggiunto alla libreria dei materiali · ${name}`, importing: 'Aggiunta alla libreria dei materiali…', add: 'Aggiungi alla timeline', addTip: 'Inserisci alla testina di riproduzione', again: 'Genera un altro', backToAudio: 'Torna ad Audio', doneNote: 'Il materiale è nella libreria Audio, indicato come «Generato». Trascinalo nella timeline o fai clic su «+» per inserirlo; puoi usarlo tutte le volte che vuoi.', failed: (message: string) => `Impossibile generare · ${message}`, edit: 'Modifica e genera di nuovo', retried: 'Inviato di nuovo',
};

export const itImageGen: ImageGenMessages = {
  title: 'Immagini', segments: 'Origine dell’immagine', project: 'Materiali del video', gen: 'Generata con IA', noModelTitle: 'Nessun modello di immagini ancora presente', noModelBody: 'Connetti un provider cloud (Modelli › Generazione di immagini › Modelli cloud) o scarica Qwen-Image-2.1 (Modelli › Generazione di immagini › Modelli locali); va bene uno qualsiasi.', connect: 'Connetti un provider cloud', downloadLocal: 'Scarica modello locale', fit: 'Come l’area di lavoro del video', recent: 'Recenti', all: (n: number) => pluralForm('it', n, { one: `Tutto il gruppo (${n})`, other: `Tutti i ${n} gruppi` }), fewer: 'Solo gli ultimi 3 gruppi', empty: 'Nessuna immagine ancora generata per questo video. Le immagini generate vanno direttamente nella libreria dei materiali (indicate come «Generato»); l’inserimento nell’area di lavoro è un passaggio separato.', place: 'Inserisci nell’area di lavoro', placeTip: 'Inserisci alla testina di riproduzione', inLibrary: 'Nella libreria dei materiali', importing: 'Aggiunta alla libreria dei materiali…', useAsRef: 'Usa come riferimento', foot: 'Le immagini generate vanno direttamente nella libreria dei materiali di questo video, con origine (modello, parametri, attività) registrata col materiale; il prompt rimane solo nel registro dell’attività. L’inserimento nell’area di lavoro è un passaggio separato.', readOnly: 'Questo video è attualmente di sola lettura, quindi non puoi generarvi materiali', charCount: (chars: number, max: number) => `${chars} / ${max} caratteri`, charCountPlain: (chars: number) => pluralForm('it', chars, { one: `${chars} carattere`, other: `${chars} caratteri` }),
};
