import type { SpeakersMessages } from './speakers-copy.ts';

export const tr: SpeakersMessages = {
title: 'Konuşmacıları belirle', back: 'Geri', background: 'Arka planda çalışıyor',
  // 设置
  cardTitle: 'Kimin konuştuğunu belirle', cardBody: 'Konuşmacıları ses iziyle yeniden belirler, altyazı ve dökümü adlarla etiketler. Önce sonucu gözden geçirirsiniz; uygulayana kadar değişiklik olmaz.', who: 'Kullan', local: 'Cihazdaki ses izi modeli', localSub: 'Bu bilgisayarda kalır', agent: 'Ajana ver', agentSub: 'Bu videonun oturumunda çalışır', scope: 'Kapsam', scopeAll: 'Tüm video', scopeLocal: (scope) => `Cihazdaki tanıma tüm videoyu kapsar; yalnızca “${scope}” için ajana verin.`, packHint: (size) => `Cihazdaki ses izi modeli${size ? ` (yaklaşık ${size})` : ''} ilk çalıştırmada indirilir, sonrasında çevrimdışı çalışır.`, packDownloading: (pct) => `Cihazdaki ses izi modeli indiriliyor${pct === null ? '…' : ` · %${pct}`}; bitince tanıma başlar.`, packUnlisted: 'Bu bilgisayarda ses izi modeli yok; yalnızca ajan yapabilir.', noSpeech: 'Bu video henüz yazıya dökülmedi. Önce Altyazı panelinde yazıya döküp konuşmacıları belirleyin.', manySpeech: 'Videoda birden fazla döküm var; ilki kullanılır', start: 'Başlat', startHint: 'Bitince gözden geçirme sayfası açılır; uygulama öncesi onayladığınız tek araç budur.', readOnly: 'Video salt okunur; konuşmacılar belirlenemez.', web: 'Tarayıcıda konuşmacılar belirlenemez', webBody: 'Konuşmacı belirleme bu bilgisayardaki ses izi modelini kullanır. BaoCut masaüstü uygulamasını kullanın.',
  // 运行
  submitting: 'Gönderiliyor…', queued: 'Sırada…', running: 'Konuşmacılar belirleniyor…', activity: (stage) => `Cihazdaki ses izi modeli · ${stage}`, runNote: 'Düzenlemeye devam edebilirsiniz · tanıma arka planda çalışır, bitince gözden geçirme sayfası açar; dökümü doğrudan değiştirmez.', cancel: 'İptal', cancelled: 'Konuşmacı belirleme iptal edildi', cancelFailed: (message) => `İptal edilemedi: ${message}`,
  // 确认
  found: (n) => `${n} konuşmacı bulundu. Örnekleri dinleyip kim olduklarını onaylayın, ada tıklayıp yeniden adlandırın, sonra uygulayın.`, same: 'Konuşmacı sınırları mevcut etiketlerle eşleşiyor; uygulamak yalnızca adları değiştirir.', newSpeaker: 'Yeni', rename: 'Yeniden adlandır', renameLabel: (name) => `Yeniden adlandır: “${name}”`, sentences: (n) => `${n} cümle`, clipOff: 'Bu cümle kesildi ve zaman çizelgesinde yok', splitTitle: (n) => `${n} çeviri yeniden bölünür; yeniden çeviri gerekmez`, splitBody: 'Konuşmacı sınırı değiştirmek yalnızca altyazı satırlarının bölünmesini etkiler; çevrilmiş metin aynı kalır.', skipped: (n) => `Eski biçimdeki ${n} çeviri yeniden bölünmez; uygulamadan sonra cümleleri hizalanmaz, güncel değil işaretlenir.`, apply: 'Uygula', applyHint: 'Uygulamadan sonra her zaman geri alabilirsiniz.', discard: 'Bu sonuçtan vazgeç',
  // 收据
  engine: 'Cihazdaki ses izi modeli', undoneReceipt: 'Geri alındı · konuşmacı etiketleri geri yüklendi', undo: 'Geri al', redo: 'Yinele', again: 'Yeniden çalıştır', done: 'Bitti', splitDone: (n) => `${n} çeviri yeni konuşmacı sınırlarında yeniden bölündü; yeniden çeviri yapılmadı.`, undoneTitle: 'Geri alındı', undoneBody: '“Yeniden çalıştır” baştan başlar; tanıma ayarlarınız korunur.', captionsStale: (n) => `${n} altyazı izi eski dökümden yapıldı ve güncellenmedi.`, gotoCaptions: 'Altyazıları aç', noUndo: 'Geri alınacak bir şey yok; sonuç mevcut etiketlerle eşleşiyor.', undoFailed: 'Geri alınamadı', redoFailed: 'Yinelenemedi',
  // 问题
  failed: 'Konuşmacı belirleme başarısız', interrupted: 'Konuşmacı belirleme kesildi', submitFailed: 'Konuşmacı belirleme başlatılamadı', applyFailed: 'Sonuç uygulanamadı', applyStale: 'Tanımadan sonra döküm veya çeviriler değişti. Yeniden çalıştırıp uygulayın.', badResult: 'Sonuç okunamadı. Yeniden çalıştırın.', retry: 'Yeniden dene', decide: 'Arka plan görevleri kısmında çöz', dismiss: 'Tamam', chapterScope: (n, label) => `Bölüm ${n} · ${label}`, manySpeechNamed: (name) => `Videoda birden fazla döküm var; ilk “${name}” kullanılıyor`,
};
