import { pluralForm } from '@baocut/protocol';
import type { SpeakersMessages } from './speakers-copy.ts';

export const de: SpeakersMessages = {
  title: "Sprecher erkennen",
  back: "Zurück",
  background: "Läuft im Hintergrund",

  cardTitle: "Sprecher zuordnen",
  cardBody: "Erkennt Sprecher erneut anhand des Stimmabdrucks und beschriftet Untertitel und Transkript mit Namen. Ergebnis zuerst prüfen; vor dem Anwenden wird nichts geändert.",
  who: "Verwenden",
  local: "Lokales Stimmabdruckmodell",
  localSub: "Bleibt auf diesem Computer",
  agent: "An den Agenten übergeben",
  agentSub: "Läuft in der Sitzung dieses Videos",
  scope: "Bereich",
  scopeAll: "Ganzes Video",
  scopeLocal: (scope: string) => `Lokale Erkennung umfasst das ganze Video; für die Erkennung nur in „${scope}“ an den Agenten übergeben.`,
  packHint: (size: string | null) =>
    `Das lokale Stimmabdruckmodell${size ? ` (etwa ${size})` : ""} wird beim ersten Ausführen heruntergeladen und funktioniert danach offline.`,
  packDownloading: (pct: number | null) =>
    `Lokales Stimmabdruckmodell wird heruntergeladen${pct === null ? "…" : ` · ${pct}%`}; die Erkennung beginnt nach Abschluss.`,
  packUnlisted: "Auf diesem Computer ist kein lokales Stimmabdruckmodell verfügbar; nur der Agent kann dies ausführen.",
  noSpeech: "Dieses Video wurde noch nicht transkribiert. Zuerst im Untertitel-Bereich transkribieren, dann Sprecher erkennen.",
  manySpeech: "Das Video hat mehrere Transkripte; das erste wird verwendet",
  start: "Starten",
  startHint: "Nach Abschluss öffnet sich eine Prüfseite – dies ist das einzige Werkzeug, bei dem vor dem Anwenden bestätigt wird.",
  agentHint: "Sendet diese Anfrage an die Sitzung des Videos; der Agent beginnt sofort.",
  readOnly: "Das Video ist schreibgeschützt; Sprecher können nicht erkannt werden.",
  web: "Sprecher können im Browser nicht erkannt werden",
  webBody: "Sprechererkennung verwendet das lokale Stimmabdruckmodell auf diesem Computer. Die BaoCut-Desktop-App verwenden.",

  submitting: "Wird eingereicht…",
  queued: "In Warteschlange…",
  running: "Sprecher werden erkannt…",
  activity: (stage: string) => `Lokales Stimmabdruckmodell · ${stage}`,
  runNote: "Weiterbearbeiten möglich · Erkennung läuft im Hintergrund und öffnet nach Abschluss eine Prüfseite; das Transkript wird nicht direkt geändert.",
  cancel: "Abbrechen",
  cancelled: "Sprechererkennung abgebrochen",
  cancelFailed: (message: string) => `Abbrechen fehlgeschlagen: ${message}`,

  found: (n: number) =>
    `Gefunden: ${pluralForm('de', n, { one: "Sprecher", other: "Sprecher" })}. Zur Zuordnung die Hörproben anhören, zum Umbenennen auf einen Namen klicken und dann anwenden.`,
  same: "Sprechergrenzen entsprechen den aktuellen Beschriftungen; Anwenden ändert nur Namen.",
  newSpeaker: "Neu",
  rename: "Umbenennen",
  renameLabel: (name: string) => `Umbenennen: „${name}“`,
  sentences: (n: number) => pluralForm('de', n, { one: "Satz", other: "Sätze" }),
  clipOff: "Dieser Satz wurde herausgeschnitten und ist nicht in der Zeitleiste",
  splitTitle: (n: number) => `${pluralForm('de', n, { one: "Übersetzung", other: "Übersetzungen" })} werden neu aufgeteilt; keine erneute Übersetzung nötig`,
  splitBody: "Geänderte Sprechergrenzen beeinflussen nur die Untertitel-Zeilenaufteilung; der übersetzte Text bleibt unverändert.",
  skipped: (n: number) =>
    `${pluralForm('de', n, { one: "Übersetzung", other: "Übersetzungen" })} im älteren Format werden nicht neu aufgeteilt; nach dem Anwenden sind ihre Sätze nicht mehr ausgerichtet und werden als veraltet markiert.`,
  apply: "Anwenden",
  applyHint: "Nach dem Anwenden jederzeit rückgängig zu machen.",
  discard: "Dieses Ergebnis verwerfen",

  engine: "Lokales Stimmabdruckmodell",
  undoneReceipt: "Rückgängig gemacht · Sprecherbeschriftungen wiederhergestellt",
  undo: "Rückgängig machen",
  redo: "Wiederholen",
  again: "Erneut ausführen",
  done: "Fertig",
  splitDone: (n: number) => `${pluralForm('de', n, { one: "Übersetzung wurde", other: "Übersetzungen wurden" })} an den neuen Sprechergrenzen neu aufgeteilt – keine erneute Übersetzung.`,
  undoneTitle: "Rückgängig gemacht",
  undoneBody: "„Erneut ausführen“ beginnt neu – Ihre Erkennungseinstellungen bleiben erhalten.",
  captionsStale: (n: number) =>
    pluralForm('de', n, { one: "1 Untertitelspur wurde aus einem älteren Transkript erstellt und nicht aktualisiert.", other: `${n} Untertitelspuren wurden aus einem älteren Transkript erstellt und nicht aktualisiert.` }),
  gotoCaptions: "Untertitel öffnen",
  noUndo: "Nichts zum Rückgängigmachen: Ergebnis entspricht den aktuellen Beschriftungen.",
  undoFailed: "Rückgängigmachen fehlgeschlagen",
  redoFailed: "Wiederholen fehlgeschlagen",

  failed: "Sprechererkennung fehlgeschlagen",
  interrupted: "Sprechererkennung unterbrochen",
  submitFailed: "Sprechererkennung konnte nicht gestartet werden",
  applyFailed: "Ergebnis konnte nicht angewendet werden",
  applyStale: "Transkript oder Übersetzungen wurden nach der Erkennung geändert. Erneut ausführen und dann anwenden.",
  badResult: "Das Ergebnis konnte nicht gelesen werden. Erneut ausführen.",
  retry: "Erneut versuchen",
  decide: "Unter Hintergrundaufgaben lösen",
  dismiss: "OK",
  chapterScope: (n: number, label: string) => `Kapitel ${n} · ${label}`,
  manySpeechNamed: (name: string) => `Das Video hat mehrere Transkripte; das erste wird verwendet: „${name}“`,
};
