import type { SpeakersMessages } from './speakers-copy.ts';

export const vi: SpeakersMessages = {
title: 'Nhận dạng người nói', back: 'Trở lại', background: 'Đang chạy nền',
  // 设置
  cardTitle: 'Xác định ai nói', cardBody: 'Nhận dạng lại người nói bằng dấu giọng, gắn tên vào phụ đề và bản chép lời. Xem kết quả trước; chưa thay đổi đến khi áp dụng.', who: 'Dùng', local: 'Mô hình dấu giọng trên thiết bị', localSub: 'Giữ trên máy tính này', agent: 'Giao cho Agent', agentSub: 'Chạy trong phiên video này', scope: 'Phạm vi', scopeAll: 'Toàn bộ video', scopeLocal: (scope) => `Nhận dạng trên thiết bị bao gồm toàn video; chỉ nhận dạng “${scope}” thì giao Agent.`, packHint: (size) => `Mô hình dấu giọng trên thiết bị${size ? ` (khoảng ${size})` : ''} tải khi chạy lần đầu rồi hoạt động ngoại tuyến.`, packDownloading: (pct) => `Đang tải mô hình dấu giọng${pct === null ? '…' : ` · ${pct}%`}; nhận dạng bắt đầu khi xong.`, packUnlisted: 'Máy tính này không có mô hình dấu giọng; chỉ Agent thực hiện được.', noSpeech: 'Video chưa chép lời. Chép trong bảng Phụ đề trước rồi nhận dạng người nói.', manySpeech: 'Video có nhiều bản chép lời; dùng bản đầu', start: 'Bắt đầu', startHint: 'Khi xong mở trang xem lại; đây là công cụ duy nhất xác nhận trước áp dụng.', readOnly: 'Video chỉ đọc nên không nhận dạng người nói được.', web: 'Không nhận dạng người nói trong trình duyệt được', webBody: 'Nhận dạng người nói dùng mô hình dấu giọng trên máy tính này. Dùng ứng dụng BaoCut máy tính.',
  // 运行
  submitting: 'Đang gửi…', queued: 'Đang chờ…', running: 'Đang nhận dạng người nói…', activity: (stage) => `Mô hình dấu giọng trên thiết bị · ${stage}`, runNote: 'Có thể tiếp tục chỉnh sửa · nhận dạng chạy nền, mở trang xem lại khi xong; không đổi trực tiếp bản chép lời.', cancel: 'Hủy', cancelled: 'Đã hủy nhận dạng người nói', cancelFailed: (message) => `Không hủy được: ${message}`,
  // 确认
  found: (n) => `Tìm thấy ${n} người nói. Nghe mẫu để xác định ai, nhấp tên để đổi rồi áp dụng.`, same: 'Ranh giới người nói khớp nhãn hiện tại; áp dụng chỉ đổi tên.', newSpeaker: 'Mới', rename: 'Đổi tên', renameLabel: (name) => `Đổi tên “${name}”`, sentences: (n) => `${n} câu`, clipOff: 'Câu này đã cắt, không trên dòng thời gian', splitTitle: (n) => `${n} bản dịch được tách lại; không cần dịch lại`, splitBody: 'Đổi ranh giới người nói chỉ ảnh hưởng tách dòng phụ đề; văn bản dịch giữ nguyên.', skipped: (n) => `${n} bản dịch định dạng cũ không tách lại; sau áp dụng câu không thẳng hàng và đánh dấu lỗi thời.`, apply: 'Áp dụng', applyHint: 'Có thể hoàn tác bất cứ lúc nào sau áp dụng.', discard: 'Loại bỏ kết quả',
  // 收据
  engine: 'Mô hình dấu giọng trên thiết bị', undoneReceipt: 'Đã hoàn tác · khôi phục nhãn người nói', undo: 'Hoàn tác', redo: 'Làm lại', again: 'Chạy lại', done: 'Xong', splitDone: (n) => `${n} bản dịch tách lại ở ranh giới mới; không dịch lại.`, undoneTitle: 'Đã hoàn tác', undoneBody: '“Chạy lại” bắt đầu từ đầu; giữ cài đặt nhận dạng.', captionsStale: (n) => `${n} rãnh phụ đề tạo từ bản chép lời cũ chưa cập nhật.`, gotoCaptions: 'Mở Phụ đề', noUndo: 'Không có gì hoàn tác: kết quả khớp nhãn hiện tại.', undoFailed: 'Không hoàn tác được', redoFailed: 'Không làm lại được',
  // 问题
  failed: 'Nhận dạng người nói thất bại', interrupted: 'Nhận dạng người nói gián đoạn', submitFailed: 'Không bắt đầu nhận dạng người nói được', applyFailed: 'Không áp dụng kết quả được', applyStale: 'Bản chép lời hoặc bản dịch đổi sau nhận dạng. Chạy lại rồi áp dụng.', badResult: 'Không đọc được kết quả. Chạy lại.', retry: 'Thử lại', decide: 'Xử lý trong Tác vụ nền', dismiss: 'OK', chapterScope: (n, label) => `Chương ${n} · ${label}`, manySpeechNamed: (name) => `Video có nhiều bản chép lời; dùng bản đầu “${name}”`,
};
