import type { SpeakersMessages } from './speakers-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const it: SpeakersMessages = {
  title: 'Identifica parlanti', back: 'Indietro', background: 'In esecuzione in background', cardTitle: 'Riconosci chi parla', cardBody: 'Identifica di nuovo i parlanti dall’impronta vocale e aggiunge i nomi ai sottotitoli e alla trascrizione. Rivedi prima il risultato; nulla cambia finché non lo applichi.', who: 'Usa', local: 'Modello locale di impronta vocale', localSub: 'Rimane su questo computer', agent: 'Passa all’agente', agentSub: 'Esegue nella sessione di questo video', scope: 'Ambito', scopeAll: 'Video intero',
  scopeLocal: (scope: string) => `L’identificazione locale copre il video intero; per identificare solo «${scope}», passa all’agente.`, packHint: (size: string | null) => `Il modello locale di impronta vocale${size ? ` (circa ${size})` : ''} viene scaricato alla prima esecuzione e poi funziona offline.`, packDownloading: (pct: number | null) => `Download del modello locale di impronta vocale${pct === null ? '…' : ` · ${pct}%`}; l’identificazione inizia al termine.`, packUnlisted: 'Nessun modello locale di impronta vocale disponibile su questo computer; può farlo solo l’agente.',
  noSpeech: 'Questo video non è ancora stato trascritto. Trascrivilo prima nel pannello Sottotitoli, poi identifica i parlanti.', manySpeech: 'Il video ha diverse trascrizioni; viene usata la prima', start: 'Avvia', startHint: 'Al termine si apre una pagina di revisione: è l’unico strumento da confermare prima dell’applicazione.', readOnly: 'Il video è di sola lettura, quindi i parlanti non possono essere identificati.', web: 'Non è possibile identificare i parlanti nel browser', webBody: 'L’identificazione dei parlanti usa il modello locale di impronta vocale su questo computer. Usa l’app desktop BaoCut.',
  submitting: 'Invio in corso…', queued: 'In coda…', running: 'Identificazione dei parlanti…', activity: (stage: string) => `Modello locale di impronta vocale · ${stage}`, runNote: 'Puoi continuare a modificare · l’identificazione viene eseguita in background e apre una pagina di revisione al termine; non cambia direttamente la trascrizione.', cancel: 'Annulla', cancelled: 'Identificazione dei parlanti annullata', cancelFailed: (message: string) => `Impossibile annullare: ${message}`,
  found: (n: number) => `${pluralForm('it', n, { one: `${n} parlante trovato`, other: `${n} parlanti trovati` })}. Ascolta i campioni per confermare chi è chi, fai clic su un nome per rinominarlo, poi applica.`, same: 'I confini dei parlanti corrispondono alle etichette attuali; l’applicazione cambia solo i nomi.', newSpeaker: 'Nuovo', rename: 'Rinomina', renameLabel: (name: string) => `Rinomina «${name}»`, sentences: (n: number) => pluralForm('it', n, { one: `${n} frase`, other: `${n} frasi` }), clipOff: 'Questa frase è stata tagliata e non è nella timeline',
  splitTitle: (n: number) => pluralForm('it', n, { one: `${n} traduzione verrà suddivisa di nuovo; non serve ritradurre`, other: `${n} traduzioni verranno suddivise di nuovo; non serve ritradurre` }), splitBody: 'Cambiare i confini dei parlanti modifica solo la suddivisione delle righe dei sottotitoli; il testo tradotto rimane invariato.', skipped: (n: number) => pluralForm('it', n, { one: `${n} traduzione in un formato precedente non verrà suddivisa di nuovo; dopo l’applicazione le sue frasi non saranno allineate e verrà segnata come non aggiornata.`, other: `${n} traduzioni in un formato precedente non verranno suddivise di nuovo; dopo l’applicazione le loro frasi non saranno allineate e verranno segnate come non aggiornate.` }),
  apply: 'Applica', applyHint: 'Puoi annullare in qualsiasi momento dopo l’applicazione.', discard: 'Scarta questo risultato', engine: 'Modello locale di impronta vocale', undoneReceipt: 'Annullato · etichette dei parlanti ripristinate', undo: 'Annulla', redo: 'Ripeti', again: 'Esegui di nuovo', done: 'Fatto',
  splitDone: (n: number) => pluralForm('it', n, { one: `${n} traduzione è stata suddivisa di nuovo ai nuovi confini dei parlanti, senza ritraduzione.`, other: `${n} traduzioni sono state suddivise di nuovo ai nuovi confini dei parlanti, senza ritraduzione.` }), undoneTitle: 'Annullato', undoneBody: '«Esegui di nuovo» ricomincia; le impostazioni di identificazione vengono conservate.', captionsStale: (n: number) => pluralForm('it', n, { one: `${n} traccia di sottotitoli deriva da una trascrizione precedente e non è stata aggiornata.`, other: `${n} tracce di sottotitoli derivano da una trascrizione precedente e non sono state aggiornate.` }), gotoCaptions: 'Apri Sottotitoli', noUndo: 'Nulla da annullare: il risultato corrisponde alle etichette attuali.', undoFailed: 'Impossibile annullare', redoFailed: 'Impossibile ripetere',
  failed: 'Identificazione dei parlanti non riuscita', interrupted: 'Identificazione dei parlanti interrotta', submitFailed: 'Impossibile avviare l’identificazione dei parlanti', applyFailed: 'Impossibile applicare il risultato', applyStale: 'La trascrizione o le traduzioni sono cambiate dopo l’identificazione. Eseguila di nuovo, poi applica.', badResult: 'Impossibile leggere il risultato. Esegui di nuovo.', retry: 'Riprova', decide: 'Risolvi in «Attività in background»', dismiss: 'OK', chapterScope: (n: number, label: string) => `Capitolo ${n} · ${label}`, manySpeechNamed: (name: string) => `Il video ha diverse trascrizioni; viene usata la prima, «${name}»`,
};
