import { pluralForm } from '@baocut/protocol';
const subtitles = (n: number) => pluralForm('pl', n, { one: `${n} napis`, few: `${n} napisy`, many: `${n} napisów`, other: `${n} napisu` });
const sentenceCount = (n: number) => pluralForm('pl', n, { one: `${n} zdanie`, few: `${n} zdania`, many: `${n} zdań`, other: `${n} zdania` });
import type { CaptionStyleMessages, NotConfiguredMessages, SubtitleMessages } from './subtitle-copy.ts';

export const plSubtitle: SubtitleMessages = {
  emptyTitle: "Brak napisów",
  emptyReady: "Transkrybuj multimedia, potem sprawdzaj napisy tutaj.",
  emptyNoMedia: "Najpierw dodaj wideo lub audio, potem generuj napisy.",

  emptyNotPlaced: "Wideo lub audio jeszcze poza osią czasu. Umieść przed generowaniem napisów.",
  emptyReuse: (name: string) => `„${name}” już transkrybowane; napisy używają gotowej transkrypcji bez ponownego rozpoznawania.`,
  generate: "Utwórz napisy",
  addMedia: "Dodaj multimedia",
  importFile: "Importuj plik napisów",
  pickAsset: "Materiał do napisów",
  pickTranscribe: "Transkrybuj, potem generuj",
  pickReuse: "Generuj z gotowej transkrypcji · bez ponownego rozpoznawania",

  liveTitle: "Transkrypcja",
  submitting: "Przesyłanie transkrypcji",
  writing: "Generowanie napisów",
  transcribed: (done: string, total: string | null) => (total ? `Transkrybowano: ${done} / ${total}` : `Transkrybowano: ${done}`),
  segments: (done: number, total: number | null) => total ? `Rozpoznano: ${done} / ${total} segmentów` : `Rozpoznano: ${pluralForm('pl', done, { one: `${done} segment`, few: `${done} segmenty`, many: `${done} segmentów`, other: `${done} segmentu` })}`,
  stages: ["Dekodowanie dźwięku", "Rozpoznawanie", "Dopasuj słowa", "Zapisz"],
  cancel: "Anuluj transkrypcję",

  liveNote: "Rozpoznane fragmenty pojawiają się po kolei. Po transkrypcji powstają napisy, które sprawdzisz tutaj wiersz po wierszu.",
  foreignNote: "Transkrypcja rozpoczęta poza panelem „Napisy”. Po ukończeniu kliknij „Generuj napisy”.",
  liveTip: (pct: number | null, at: string, remain: string | null) =>
    [pct === null ? "Transkrypcja" : `Transkrypcja ${pct}%`, `przepisano do ${at}`, ...(remain ? [`pozostało ${remain}`] : [])].join(' · '),
  pendingLeft: (remain: string) => `Transkrypcja · pozostało ${remain}`,
  cancelled: "Transkrypcja anulowana",
  cancelFailed: (message: string) => `Nie udało się anulować transkrypcji: ${message}`,

  generated: (count: number, from: string, to: string) => `Wygenerowano: ${subtitles(count)} · ${from} → ${to}`,
  created: (count: number) => `Wygenerowano: ${subtitles(count)}`,

  createdShelved: (count: number) => `Wygenerowano: ${subtitles(count)} · oryginał już na ekranie, nowa warstwa niewidoczna; kliknij na pasku, aby umieścić`,
  notConfigured: (reason: string) => `Jeszcze nie można transkrybować · ${reason}`,
  submitFailed: "Nie udało się rozpocząć transkrypcji",
  failed: "Transkrypcja nie powiodła się",
  interrupted: "Transkrypcja przerwana",
  noSpeechTitle: "Mowa nierozpoznana",
  noSpeech: "W materiale nie słychać mowy.",
  noAudioTitle: "Materiał nie ma ścieżki audio",
  noAudio: "Ponów z wideo lub audio z dźwiękiem.",
  offTimelineTitle: "Rozpoznanej mowy nie ma na osi czasu",
  offTimeline: "Część materiału na osi czasu bez mowy lub materiał usunięty z osi czasu.",
  badSpeech: "Format transkrypcji nierozpoznany, nie można podzielić na napisy.",
  pendingTitle: "Transkrypcja ukończona, napisy jeszcze niewygenerowane",
  pending: "Transkrypcja zapisana w wideo; kliknij „Generuj napisy” bez ponownej transkrypcji.",
  writeFailedTitle: "Napisy niezapisane w wideo",
  otherVideo: (name: string) => `„${name}” transkrybowane · wróć do wideo i kliknij „Generuj napisy”`,
  retry: "Spróbuj ponownie",
  dismiss: "OK",
  unsettledTitle: "Wynik transkrypcji nieznany",
  unsettled:
    "Runtime zrestartowany przed odpowiedzią rozpoznawania. Opłata mogła być naliczona, bez automatycznego ponowienia. Zdecyduj w zadaniach w tle, ponowić lub porzucić; po zapisie transkrypcji „Generuj napisy” używa jej bezpośrednio.",
  unappliedTitle: "Transkrypcja niezapisana w wideo",
  unapplied: (message: string) => `${message ? `${message}. ` : ""}Wynik rozpoznawania dostępny; zapisz w wideo z zadań w tle. Potem „Generuj napisy” używa go bezpośrednio.`,
  decide: "Rozwiąż w zadaniach w tle",

  onScreen: "Na ekranie",
  defaultStyle: "Styl domyślny",
  styleEntry: (n: number) => n ? `Edytuj styl · ${pluralForm('pl', n, { one: `${n} ścieżka napisów`, few: `${n} ścieżki napisów`, many: `${n} ścieżek napisów`, other: `${n} ścieżki napisów` })} na ekranie` : "Edytuj styl",
  styleEntryLabel: "Edytuj styl napisów",
  chipPick: "Sprawdź poniżej",
  chipOff: "Wyłączone · włącz w nagłówku ścieżki",
  chipLocked: "Zablokowane · odblokuj w nagłówku ścieżki",
  drop: (name: string) => `Zdejmij „${name}” z ekranu`,
  dropTip: "Zdejmij z ekranu · dane zostają",
  dropLast: "To jedyna ścieżka napisów na ekranie – zdjęcie zostawi bez napisów",
  dropped: (name: string) => `Zdjęto „${name}” z ekranu · przywróć z nagłówka ścieżki`,
  putBackTip: (name: string, stacked: boolean) => `Przywróć „${name}” na ekran${stacked ? " · trzecia wymaga potwierdzenia" : ""}`,
  putBack: (name: string) => `Przywróć „${name}” na ekran`,
  stacked: (name: string, n: number) => `Nałożono „${name}” · ${n} teraz na ekranie`,
  stackTitle: (n: number) => `${n} ścieżek napisów będzie na ekranie`,
  stackBody: (name: string, n: number) => `Przywrócenie „${name}” pokaże ${n} razem – w pionowym wideo trzy zajmują znaczną część ekranu.`,
  stackConfirm: "Nałóż kolejną",
  cancelLabel: "Anuluj",
  translate: "Przetłumacz na…",
  translateOff: "Tłumaczenie jeszcze niepodłączone: model tekstowy i proces w przygotowaniu",
  translateTip: "Wybierz język i model tekstowy; tłumaczenie na ekranie nową ścieżką napisów",
  translatingLabel: (language: string) => `Tłumaczenie na ${language}`,
  flip: "Odwróć ⇅",
  flipTip: "Zamień dwa wiersze – górny jest główny, z większym tekstem",
  flipOff: "Można zamienić oryginał i tłumaczenie ze wspólnym stylem na ekranie; brak takiej pary",
  flipped: (translationFirst: boolean) => `Zamieniono · ${translationFirst ? "tłumaczenie u góry, oryginał poniżej" : "oryginał u góry, tłumaczenie poniżej"}`,

  stats: (cues: number, sentences: number) => `${subtitles(cues)} · ${sentenceCount(sentences)}`,
  seam: "Merge up",
  seamSpeaker: "Różni mówcy · nie można połączyć",
  undo: "Cofnij",
  panelTitle: "Napisy",
  importFileTip: "Importuj plik napisów (SRT, WebVTT, ASS)",
  importUnsupported: "Obsługiwane tylko SRT, WebVTT i ASS",
  importEmpty: (file: string) => `Nie znaleziono napisów w „${file}”`,
  importLabel: "Importuj napisy",
  imported: (count: number, end: string) => `Zaimportowano: ${count} napisów · 0:00 → ${end}`,
  readingCues: "Wczytywanie napisów…",
  unsupportedDoc: "Formatu napisów nie można jeszcze tutaj edytować.",
  rewriteLabel: "Edytuj napis",
  rewritten: "Napis zmieniony",
  splitLabel: "Podziel napis",
  splitDone: "Podzielono na dwa · czas według liczby znaków",
  mergeSpeaker: "Różni mówcy · nie można połączyć",
  firstCue: "Już pierwszy",
  lastCue: "Już ostatni",
  mergeLabel: "Połącz napisy",
  mergedUp: "Połączono z poprzednim · czas połączony",
  mergedDown: "Połączono z następnym · czas połączony",
  noChanges: "Brak dopasowań do zmiany",
  replaceLabel: "Zastąp tekst napisów",
  replaced: (count: number) => `Zastąpiono: ${count}`,
  tooFast: (count: number) => `${count} przekracza tempo czytania`,
  keysHint: "Enter dzieli · ⌫ na początku łączy w górę · ⌦ na końcu w dół",
  findReplace: "Znajdź i zastąp",
  findReplaceTip: "Znajdź i zastąp · ⌘F",
  noSentences: "Dokument napisów nie ma jeszcze zdań.",
  badRegex: "Nieprawidłowe wyrażenie regularne",
  noResults: "Brak wyników",
  find: "Znajdź",
  findPlaceholder: "Znajdź w napisach",
  previous: "Poprzedni",
  next: "Dalej",
  closeFind: "Zamknij wyszukiwanie",
  replaceWith: "Zamień na",
  matchCase: "Uwzględnij wielkość liter",
  wholeWordShort: "Słowo",
  wholeWord: "Dopasuj całe słowo",
  regex: "Wyrażenie regularne · tekst zastępczy wstawiany dosłownie",
  replace: "Wymień",
  replaceAll: "Zastąp wszystko",
  regexError: (error: string) => `Błąd wyrażenia regularnego: ${error}`,
  cutAway: "Materiał wideo zdania wycięto",
  seekHere: "Przesuń głowicę do zdania",
  readingSpeed: "Tempo czytania: znaki na sekundę",
  editCue: (n: number) => `Edytuj napis ${n}`,
  cueText: "Tekst napisu",
  dropLabel: "Zdejmij napisy z płótna",
  landLabel: "Przywróć napisy na płótno",
  flipLabel: "Zamień kolejność napisów",
  applyStyleLabel: "Styl napisów",
  listSeparator: ", ",
  noSchema: "(brak schema)",
  editPreset: (name: string) => `Edytuj styl: ${name}`,
  trackName: "Napisy",
};

export const plNotConfigured: NotConfiguredMessages = {
  'no-default': "Nie wybrano jeszcze modelu transkrypcji",
  'missing-credential': "Usługa transkrypcji nie ma jeszcze klucza",
  'not-installed': "Lokalny model transkrypcji jeszcze niezainstalowany",
  'signed-out': "Agent jeszcze niezalogowany",
  outdated: "Wersja agenta zbyt stara",
  'not-paired': "Węzeł zdalny jeszcze niesparowany",
  'not-connected': "Węzeł zdalny niepołączony",
  unsupported: "Usługa nie obsługuje transkrypcji",
  disabled: "Usługa transkrypcji wyłączona",
};

export const plCaptionStyle: CaptionStyleMessages = {

  title: "Style napisów",
  back: "Wróć do napisów",
  open: "Zmień styl",
  openTip: "Otwórz galerię stylów napisów: każda karta to inny wygląd",
  scope: "Zastosuj do",
  scopeAll: "Wszystko",
  hint: "Karty pokazują obecne napisy. Zastosowanie zmienia tylko wygląd, nie dodaje ani nie usuwa wierszy. Użyj paska powyżej lub nagłówka ścieżki dla dodawania i zdejmowania.",
  hintScope: "Gdy „Zastosuj do” wskazuje wiersz, zmienia tylko jego, reszta bez ruchu.",
  hintMotion: "Karty Social z chińskimi nazwami zwykle animują słowa lub znaki; tutaj tylko wygląd statyczny.",
  edit: "Edytuj ten styl",
  applied: (name: string, lines: string) => `Zastosowano „${name}” · zmieniono styl: ${lines}`,
  appliedOne: (line: string, name: string, others: string) => `Zastosowano „${name}” do ${line}${others ? ` · ${others} bez zmian` : ""}`,
  loading: "Wczytywanie stylów napisów…",
  foreign: (schema: string) => `Styl napisów to ${schema}; galeria nie stosuje do niego.`,
  readOnly: "Wideo nie można teraz zmienić; karty tylko do podglądu.",

  lineSwitch: "Wiersz do edycji",
  original: "Oryginał",
  translation: "Tłumaczenie",
  lineOwn: (line: string, n: number) => `${line}: ${pluralForm('pl', n, { one: `${n} ustawienie`, few: `${n} ustawienia`, many: `${n} ustawień`, other: `${n} ustawienia` })} osobno; reszta według wspólnego stylu obu wierszy.`,
  lineShared: (line: string) => `Zmiany tutaj tylko dla ${line}; reszta według wspólnego stylu wierszy.`,
  followShared: "Według wspólnego stylu",
  ratio: (root: string, bi: string, orig: string, source: string, size: string, k: string) => `Rozmiar bazowy ${root} × skala dwujęzyczna ${bi} ≈ ${orig} (rzeczywisty rozmiar „${source}”); ten wiersz ${size} = oryginał × ${k}.`,
  ratioOwn: (size: string) => `Rozmiar wiersza ustawiony na ${size} osobno, bez proporcji oryginału.`,
  originalOwn: (size: string) => `Rozmiar oryginału ustawiony na ${size} osobno; tłumaczenie nie podąża za nim.`,
  followRatio: "Znów według proporcji",
  originalChain: "Zmień rozmiar oryginału, tłumaczenie proporcjonalnie.",
  place: "Pozycja na ekranie",
  places: [
    { key: 'top', label: "Góra", y: 10, valign: 'top' },
    { key: 'middle', label: "Środek", y: 50, valign: 'center' },
    { key: 'bottom', label: "Dół", y: 90, valign: 'bottom' },
  ],
  remembered: 'Zmienione opcje są zapamiętywane dla nowych napisów.',
  fromTop: "Od góry",
  anchor: "Linia zakotwiczenia",
  anchors: [
    { key: 'top', label: "Górna krawędź" },
    { key: 'center', label: "Linia środkowa" },
    { key: 'bottom', label: "Dolna krawędź" },
  ],
  anchorHint: {
    top: "Górna krawędź do linii kotwicy → wiersze rosną w dół.",
    center: "Linia środkowa do kotwicy → wiersze rosną równo w górę i dół.",
    bottom: "Dolna krawędź do kotwicy → wiersze rosną w górę (zwykle dla napisów).",
  },
  casing: "Wielkość liter",
  cases: [
    { key: 'none', label: "Bez zmian" },
    { key: 'uppercase', label: "WERSALIKI" },
    { key: 'title', label: "Jak tytuł" },
    { key: 'lowercase', label: "małe litery" },
  ],
  plate: "Kształt",
  plates: [
    { key: 'wrap', label: "Wiersz po wierszu", note: "Osobne pole na wiersz o jego szerokości" },
    { key: 'block', label: "Jedno pole", note: "Jeden prostokąt na napis o szerokości najdłuższego wiersza" },
  ],
};
