import type { CaptionStyleMessages, NotConfiguredMessages, SubtitleMessages } from './subtitle-copy.ts';

export const zhSubtitle: SubtitleMessages = {
  emptyTitle: '还没有字幕',
  emptyReady: '转录媒体后，即可在这里校对字幕。',
  emptyNoMedia: '先添加视频或音频，再生成字幕。',
  /** 素材在库里、还没放上时间线：字幕跟着时间线走，转录了也落不到画面上。 */
  emptyNotPlaced: '视频或音频还没放上时间线。放上去之后才能生成字幕。',
  emptyReuse: (name: string) => `「${name}」已经转写过，生成字幕会直接用这份转写，不再重新识别。`,
  generate: '生成字幕',
  addMedia: '添加媒体',
  importFile: '导入字幕文件',
  pickAsset: '为哪段素材生成字幕',
  pickTranscribe: '转录后生成',
  pickReuse: '用已有转写生成 · 不再识别',

  // 转录中（LiveHead）
  liveTitle: '转录中',
  submitting: '正在提交转录',
  writing: '正在生成字幕',
  transcribed: (done: string, total: string | null) => (total ? `已转录 ${done} / ${total}` : `已转录 ${done}`),
  segments: (done: number, total: number | null) => (total ? `已识别 ${done} / ${total} 段` : `已识别 ${done} 段`),
  stages: ['解码音频', '识别', '词级对齐', '落盘'],
  cancel: '取消转录',
  /** 设计稿这里写「识别出来的部分会一段一段出现」；协议没有部分结果，如实说。 */
  liveNote: '识别出来的部分会一段一段出现；转录完成后生成字幕，再在这里逐句校对。',
  foreignNote: '这次转录不是从字幕面板开始的：完成后点「生成字幕」用它的结果。',
  liveTip: (pct: number | null, at: string, remain: string | null) =>
    [pct === null ? '转录中' : `转录中 ${pct}%`, `已转录到 ${at}`, ...(remain ? [`还剩 ${remain}`] : [])].join(' · '),
  pendingLeft: (remain: string) => `转录中 · 还剩 ${remain}`,
  cancelled: '已取消转录',
  cancelFailed: (message: string) => `没能取消转录：${message}`,

  // 结果与问题
  generated: (count: number, from: string, to: string) => `已生成 ${count} 条字幕 · ${from} → ${to}`,
  created: (count: number) => `已生成 ${count} 条字幕`,
  /** 这个素材已经有原文字幕显示着：新的一层停用着放上去（轨条上的虚线 chip）。 */
  createdShelved: (count: number) => `已生成 ${count} 条字幕 · 画面上已有原文字幕，新的一层先没放上画面，在轨条上点它放回`,
  notConfigured: (reason: string) => `还不能转录 · ${reason}`,
  submitFailed: '没能开始转录',
  failed: '转录失败',
  interrupted: '转录中断了',
  noSpeechTitle: '没有识别出语音',
  noSpeech: '这段素材里没有听到说话声。',
  noAudioTitle: '这段素材没有音轨',
  noAudio: '换一段带声音的视频或音频再试。',
  offTimelineTitle: '识别出的话都不在时间线上',
  offTimeline: '这段素材在时间线上用到的部分里没有说话声，或者它已经从时间线上拿掉了。',
  badSpeech: '转写文档的格式认不出来，没法切成字幕。',
  pendingTitle: '转写已完成，字幕还没生成',
  pending: '转写已经存进视频；再点「生成字幕」会直接用它，不用重新转录。',
  writeFailedTitle: '字幕没有写进视频',
  otherVideo: (name: string) => `「${name}」转写完成 · 回到那个视频点「生成字幕」`,
  retry: '重试',
  dismiss: '知道了',
  unsettledTitle: '转录结果不明',
  unsettled:
    'Runtime 重启时这次识别还没有回音，可能已经计费，不会自动重发。去后台任务里决定再试还是放弃；转写写进视频之后，点「生成字幕」会直接用它。',
  unappliedTitle: '转写没有写进视频',
  unapplied: (message: string) =>
    `${message ? `${message}。` : ''}识别结果还在，可以在后台任务里重新写入视频；写入之后点「生成字幕」会直接用它。`,
  decide: '去后台任务处理',

  // 轨条与样式入口卡
  onScreen: '画面上',
  defaultStyle: '缺省样式',
  styleEntry: (n: number) => (n ? `编辑样式 · 画面上 ${n} 条字幕轨` : '编辑样式'),
  styleEntryLabel: '编辑字幕样式',
  chipPick: '在下面校对这一条',
  chipOff: '已停用 · 时间轴行头能启用',
  chipLocked: '已锁定 · 时间轴行头能解锁',
  drop: (name: string) => `把「${name}」从画面上拿下`,
  dropTip: '从画面上拿下 · 不删数据',
  dropLast: '画面上只剩这一条字幕了——再拿下来就没有字幕了',
  dropped: (name: string) => `已把「${name}」从画面上拿下来 · 时间轴行头能放回来`,
  putBackTip: (name: string, stacked: boolean) => `把「${name}」放回画面${stacked ? ' · 第三条会问一次' : ''}`,
  putBack: (name: string) => `已把「${name}」放回画面`,
  stacked: (name: string, n: number) => `已把「${name}」叠上去 · 现在 ${n} 条`,
  stackTitle: (n: number) => `画面上会有 ${n} 条字幕`,
  stackBody: (name: string, n: number) => `放回「${name}」就是 ${n} 条一起显示——竖屏里三条会占掉小半屏。`,
  stackConfirm: '再叠一条',
  cancelLabel: '取消',
  translate: '翻译成…',
  translateOff: '翻译还没接上：文本模型与翻译流程正在做',
  translateTip: '选目标语言与文本模型，翻好的译文作为一条新的字幕轨放到画面上',
  translatingLabel: (language: string) => `正在翻译成${language}`,
  flip: '倒转 ⇅',
  flipTip: '倒转两行的上下——在上那行是主行，字更大',
  flipOff: '原文与译文用的是同一份样式、都在画面上时才能倒转；现在还没有可以倒转的一组',
  flipped: (translationFirst: boolean) => `已倒转 · 现在${translationFirst ? '译文在上、原文在下' : '原文在上、译文在下'}`,

  // 列表
  stats: (cues: number, sentences: number) => `${cues} 条 · ${sentences} 句`,
  seam: '并入上一条',
  seamSpeaker: '说话人不同 · 不能并入',
  undo: '撤销',
  panelTitle: '字幕',
  importFileTip: '导入字幕文件（SRT、WebVTT、ASS）',
  importUnsupported: '只认 SRT、WebVTT 与 ASS 字幕文件',
  importEmpty: (file: string) => `「${file}」里没有读到字幕`,
  importLabel: '导入字幕',
  imported: (count: number, end: string) => `已导入 ${count} 条字幕 · 0:00 → ${end}`,
  readingCues: '正在读取字幕…',
  unsupportedDoc: '这份字幕文档的格式还不能在这里编辑。',
  rewriteLabel: '改写字幕',
  rewritten: '已改写这一条字幕',
  splitLabel: '拆分字幕',
  splitDone: '已拆成两条 · 时间按字数分',
  mergeSpeaker: '说话人不同 · 不能合并',
  firstCue: '已经是第一条',
  lastCue: '已经是最后一条',
  mergeLabel: '合并字幕',
  mergedUp: '已并入上一条 · 时间接上',
  mergedDown: '已并入下一条 · 时间接上',
  noChanges: '没有需要改动的匹配',
  replaceLabel: '替换字幕文字',
  replaced: (count: number) => `已替换 ${count} 处`,
  tooFast: (count: number) => `${count} 条超出阅读速度`,
  keysHint: 'Enter 拆 · 行首 ⌫ 并上 · 行尾 ⌦ 并下',
  findReplace: '查找和替换',
  findReplaceTip: '查找和替换 · ⌘F',
  noSentences: '这份字幕还没有句子。',
  badRegex: '正则无效',
  noResults: '无结果',
  find: '查找',
  findPlaceholder: '在字幕里查找',
  previous: '上一个',
  next: '下一个',
  closeFind: '关闭查找',
  replaceWith: '替换为',
  matchCase: '区分大小写',
  wholeWordShort: '全词',
  wholeWord: '全词匹配',
  regex: '正则表达式 · 替换文字按字面插入',
  replace: '替换',
  replaceAll: '全部替换',
  regexError: (error: string) => `正则写错了：${error}`,
  cutAway: '这一句所在的画面已经剪掉了',
  seekHere: '播放头跳到这一句',
  readingSpeed: '阅读速度：每秒字数',
  editCue: (n: number) => `改写第 ${n} 条字幕`,
  cueText: '字幕文字',
  dropLabel: '从画面上拿下字幕',
  landLabel: '把字幕放回画面',
  flipLabel: '倒转字幕上下',
  applyStyleLabel: '套用字幕样式',
  listSeparator: '、',
  noSchema: '（没有 schema）',
  editPreset: (name: string) => `编辑这份样式：${name}`,
  trackName: '字幕',
  transcriptRow: '文稿',
  transcriptRowTip: '文稿 · 只读 · 这条视频还没有字幕轨，在字幕 Tab 生成',
};

export const zhNotConfigured: NotConfiguredMessages = {
  'no-default': '还没有选转录用的模型',
  'missing-credential': '转录服务还没有填密钥',
  'not-installed': '本地转录模型还没有安装',
  'signed-out': '智能体还没有登录',
  outdated: '智能体的版本太旧',
  'not-paired': '远端节点还没有配对',
  'not-connected': '远端节点没有连上',
  unsupported: '选的服务不支持转录',
  disabled: '转录服务已停用',
};

export const zhCaptionStyle: CaptionStyleMessages = {
  // 画廊
  title: '字幕样式',
  back: '返回字幕',
  open: '更换样式',
  openTip: '打开字幕样式画廊：一张卡换一套涂装',
  scope: '套到',
  scopeAll: '全部',
  hint: '每张卡画的都是你画面上现在这几条字幕。套一张只换涂装，不会多一条、也不会少一条——想加一条或拿下一条，用上面的轨条或时间轴的字幕行头。',
  hintScope: '「套到」指到一条时只换那一条，别的一根线都不动。',
  hintMotion: '社交里那几张中文名的卡原本带逐词或逐字动效，这里只换得上它们的静态涂装。',
  edit: '编辑这份样式',
  applied: (name: string, lines: string) => `已套用「${name}」· 已给 ${lines} 换上这份样式`,
  appliedOne: (line: string, name: string, others: string) => `已给 ${line} 换上「${name}」${others ? `· ${others}没动` : ''}`,
  loading: '正在读取字幕样式…',
  foreign: (schema: string) => `这份字幕样式是 ${schema}，画廊套不上。`,
  readOnly: '这个视频现在不能改，样式卡只能看。',

  // 属性页
  lineSwitch: '改哪一行',
  original: '原文',
  translation: '译文',
  lineOwn: (line: string, n: number) => `${line}有 ${n} 项单独设置，其余跟随两行共用的样式。`,
  lineShared: (line: string) => `这里改的只是${line}；没改过的项跟随两行共用的样式。`,
  followShared: '全部跟随',
  ratio: (root: string, bi: string, orig: string, source: string, size: string, k: string) =>
    `根字号 ${root} × 双语压缩 ${bi} ≈ ${orig}（「${source}」的有效字号）；这一条 ${size} = 原文 × ${k}。`,
  ratioOwn: (size: string) => `这一条的字号单独设成了 ${size}，不跟原文的比例走。`,
  originalOwn: (size: string) => `原文的字号单独设成了 ${size}，译文不再跟着它变。`,
  followRatio: '改回跟比例',
  originalChain: '改原文的字号，译文按比例跟着变。',
  place: '放在画面',
  places: [
    { key: 'top', label: '顶部', y: 10, valign: 'top' },
    { key: 'middle', label: '居中', y: 50, valign: 'center' },
    { key: 'bottom', label: '底部', y: 90, valign: 'bottom' },
  ],
  remembered: '修改的选项会记住，下次新建字幕继续使用。',
  fromTop: '距顶部',
  anchor: '锚线位置',
  anchors: [
    { key: 'top', label: '顶边' },
    { key: 'center', label: '中线' },
    { key: 'bottom', label: '底边' },
  ],
  anchorHint: {
    top: '顶边钉在锚线上 → 折行向下长。',
    center: '中线钉在锚线上 → 折行向上下均分。',
    bottom: '底边钉在锚线上 → 折行向上长（字幕的常态）。',
  },
  casing: '大小写',
  cases: [
    { key: 'none', label: '原样' },
    { key: 'uppercase', label: '全大写' },
    { key: 'title', label: '首字母大写' },
    { key: 'lowercase', label: '全小写' },
  ],
  plate: '形态',
  plates: [
    { key: 'wrap', label: '逐行', note: '每一行各自贴一块，宽度跟着那一行走' },
    { key: 'block', label: '整块', note: '整条一块矩形，按最宽那一行' },
  ],
};
