const subtitles = (n: number) => `${n} ${pluralForm('de', n, { one: 'Untertitel', other: 'Untertitel' })}`;
type Choice<K extends string> = { readonly key: K; readonly label: string };
type Place = Choice<'top' | 'middle' | 'bottom'> & { readonly y: number; readonly valign: 'top' | 'center' | 'bottom' };
type Plate = Choice<'wrap' | 'block'> & { readonly note: string };
import { pluralForm } from '@baocut/protocol';
import type { CaptionStyleMessages, NotConfiguredMessages, SubtitleMessages } from './subtitle-copy.ts';

export const deSubtitle: SubtitleMessages = {
  emptyTitle: "Noch keine Untertitel",
  emptyReady: "Medien transkribieren, dann hier die Untertitel Korrektur lesen.",
  emptyNoMedia: "Zuerst eine Video- oder Audiodatei hinzufügen, dann Untertitel erzeugen.",

  emptyNotPlaced: "Video oder Audio liegt noch nicht in der Zeitleiste. Vor dem Erzeugen der Untertitel dort platzieren.",
  emptyReuse: (name: string) => `„${name}“ ist bereits transkribiert; Untertitel werden aus diesem Transkript ohne erneute Erkennung erzeugt.`,
  generate: "Untertitel erzeugen",
  addMedia: "Medien hinzufügen",
  importFile: "Untertiteldatei importieren",
  pickAsset: "Material zum Erzeugen der Untertitel",
  pickTranscribe: "Transkribieren, dann erzeugen",
  pickReuse: "Aus vorhandenem Transkript erzeugen · keine erneute Erkennung",

  liveTitle: "Wird transkribiert",
  submitting: "Transkription wird eingereicht",
  writing: "Untertitel werden erzeugt",
  transcribed: (done: string, total: string | null) => (total ? `Transkribiert: ${done} / ${total}` : `Transkribiert: ${done}`),
  segments: (done: number, total: number | null) => (total ? `Erkannt: ${done} / ${total} Abschnitte` : `Erkannt: ${done} ${pluralForm('de', done, { one: "Abschnitt", other: "Abschnitte" })}`),
  stages: ["Audio dekodieren", "Erkennen", "Wörter ausrichten", "Speichern"],
  cancel: "Transkription abbrechen",

  liveNote: "Erkannte Teile erscheinen nacheinander. Nach Abschluss der Transkription werden Untertitel erzeugt, die Sie hier Zeile für Zeile Korrektur lesen können.",
  foreignNote: "Diese Transkription wurde nicht im Untertitel-Bereich gestartet. Nach Abschluss auf „Untertitel erzeugen“ klicken, um ihr Ergebnis zu verwenden.",
  liveTip: (pct: number | null, at: string, remain: string | null) =>
    [pct === null ? "Wird transkribiert" : `Wird transkribiert ${pct} %`, `transkribiert bis ${at}`, ...(remain ? [`noch ${remain}`] : [])].join(' · '),
  pendingLeft: (remain: string) => `Wird transkribiert · noch ${remain}`,
  cancelled: "Transkription abgebrochen",
  cancelFailed: (message: string) => `Transkription konnte nicht abgebrochen werden: ${message}`,

  generated: (count: number, from: string, to: string) => `Erzeugt: ${subtitles(count)} · ${from} → ${to}`,
  created: (count: number) => `Erzeugt: ${subtitles(count)}`,

  createdShelved: (count: number) =>
    `Erzeugt: ${subtitles(count)} · Originaluntertitel sind bereits sichtbar; die neue Ebene wird noch nicht angezeigt. Zum Anzeigen auf den Streifen klicken`,
  notConfigured: (reason: string) => `Transkription noch nicht möglich · ${reason}`,
  submitFailed: "Transkription konnte nicht gestartet werden",
  failed: "Die Transkription ist fehlgeschlagen",
  interrupted: "Transkription unterbrochen",
  noSpeechTitle: "Keine Sprache erkannt",
  noSpeech: "In diesem Material ist niemand beim Sprechen zu hören.",
  noAudioTitle: "Dieses Material hat keine Audiospur",
  noAudio: "Mit einer Video- oder Audiodatei mit Ton erneut versuchen.",
  offTimelineTitle: "Keine erkannte Sprache liegt in der Zeitleiste",
  offTimeline: "Der in der Zeitleiste verwendete Materialbereich enthält keine Sprache, oder das Material wurde aus der Zeitleiste entfernt.",
  badSpeech: "Das Transkriptformat wird nicht erkannt und kann nicht in Untertitel aufgeteilt werden.",
  pendingTitle: "Transkription abgeschlossen, Untertitel noch nicht erzeugt",
  pending: "Das Transkript ist im Video gespeichert; erneut auf „Untertitel erzeugen“ klicken, um es ohne erneute Transkription zu verwenden.",
  writeFailedTitle: "Die Untertitel wurden nicht ins Video geschrieben",
  otherVideo: (name: string) => `„${name}“ transkribiert · zu diesem Video zurückkehren und auf „Untertitel erzeugen“ klicken`,
  retry: "Erneut versuchen",
  dismiss: "OK",
  unsettledTitle: "Transkriptionsergebnis unbekannt",
  unsettled:
    "Die Runtime wurde vor der Antwort auf diese Erkennung neu gestartet. Möglicherweise wurden bereits Kosten berechnet; die Anfrage wird nicht automatisch erneut gesendet. Unter Hintergrundaufgaben erneut versuchen oder verwerfen; sobald das Transkript ins Video geschrieben ist, verwendet „Untertitel erzeugen“ es direkt.",
  unappliedTitle: "Das Transkript wurde nicht ins Video geschrieben",
  unapplied: (message: string) =>
    `${message ? `${message}. ` : ""}Das Erkennungsergebnis ist noch verfügbar; unter Hintergrundaufgaben erneut ins Video schreiben. Danach verwendet „Untertitel erzeugen“ es direkt.`,
  decide: "Unter Hintergrundaufgaben lösen",

  onScreen: "Im Bild",
  defaultStyle: "Standardstil",
  styleEntry: (n: number) => (n ? `Stil bearbeiten · ${n} ${pluralForm('de', n, { one: "Untertitelspur", other: "Untertitelspuren" })} sichtbar` : "Stil bearbeiten"),
  styleEntryLabel: "Untertitelstil bearbeiten",
  chipPick: "Diese unten Korrektur lesen",
  chipOff: "Ausgeschaltet · am Spurkopf einschalten",
  chipLocked: "Gesperrt · am Spurkopf entsperren",
  drop: (name: string) => `Ausblenden: „${name}“`,
  dropTip: "Aus dem Bild nehmen · Daten bleiben",
  dropLast: "Dies ist die einzige noch sichtbare Untertitelspur – Ausblenden entfernt alle Untertitel aus dem Bild",
  dropped: (name: string) => `Ausgeblendet: „${name}“ · am Spurkopf wieder einblenden`,
  putBackTip: (name: string, stacked: boolean) => `Wieder einblenden: „${name}“${stacked ? " · eine dritte benötigt vorher eine Bestätigung" : ""}`,
  putBack: (name: string) => `Wieder einblenden: „${name}“`,
  stacked: (name: string, n: number) => `Gestapelt: „${name}“ · ${n} jetzt sichtbar`,
  stackTitle: (n: number) => `${n} Untertitelspuren werden sichtbar`,
  stackBody: (name: string, n: number) => `Wieder einblenden: „${name}“ zeigt ${n} gemeinsam – in einem Hochkantvideo nehmen drei einen großen Bildbereich ein.`,
  stackConfirm: "Weitere stapeln",
  cancelLabel: "Abbrechen",
  translate: "Übersetzen in…",
  translateOff: "Übersetzung ist noch nicht angebunden: Textmodell und Übersetzungsworkflow werden entwickelt",
  translateTip: "Zielsprache und Textmodell auswählen; die Übersetzung erscheint als neue Untertitelspur",
  translatingLabel: (language: string) => `Übersetzung nach ${language}`,
  flip: "Umkehren ⇅",
  flipTip: "Die zwei Zeilen tauschen – die obere ist die Hauptzeile mit größerem Text",
  flipOff: "Tauschen ist nur möglich, wenn Original und Übersetzung einen Stil teilen und beide sichtbar sind; es gibt noch kein solches Paar",
  flipped: (translationFirst: boolean) =>
    `Getauscht · ${translationFirst ? "Übersetzung oben, Original unten" : "Original oben, Übersetzung unten"}`,

  stats: (cues: number, sentences: number) => `${subtitles(cues)} · ${sentences} ${pluralForm('de', sentences, { one: "Satz", other: "Sätze" })}`,
  seam: "Merge up",
  seamSpeaker: "Unterschiedliche Sprecher · Zusammenführen nicht möglich",
  undo: "Rückgängig machen",
  panelTitle: "Untertitel",
  importFileTip: "Untertiteldatei importieren (SRT, WebVTT, ASS)",
  importUnsupported: "Nur SRT-, WebVTT- und ASS-Untertiteldateien werden unterstützt",
  importEmpty: (file: string) => `Keine Untertitel gefunden in „${file}“`,
  importLabel: "Untertitel importieren",
  imported: (count: number, end: string) => `Importiert: ${count} Untertitel · 0:00 → ${end}`,
  readingCues: "Untertitel werden geladen…",
  unsupportedDoc: "Das Format dieses Untertiteldokuments kann hier noch nicht bearbeitet werden.",
  rewriteLabel: "Untertitel bearbeiten",
  rewritten: "Untertitel bearbeitet",
  splitLabel: "Untertitel teilen",
  splitDone: "In zwei geteilt · Timing nach Zeichenanzahl aufgeteilt",
  mergeSpeaker: "Unterschiedliche Sprecher · Zusammenführen nicht möglich",
  firstCue: "Bereits der erste Eintrag",
  lastCue: "Bereits der letzte Eintrag",
  mergeLabel: "Untertitel zusammenführen",
  mergedUp: "Mit vorherigem zusammengeführt · Timing verbunden",
  mergedDown: "Mit nächstem zusammengeführt · Timing verbunden",
  noChanges: "Keine Treffer müssen geändert werden",
  replaceLabel: "Untertiteltext ersetzen",
  replaced: (count: number) => `Ersetzt: ${count}`,
  tooFast: (count: number) => `${count} über Lesegeschwindigkeit`,
  keysHint: "Enter teilt · ⌫ am Anfang verbindet nach oben · ⌦ am Ende verbindet nach unten",
  findReplace: "Suchen und ersetzen",
  findReplaceTip: "Suchen und ersetzen · ⌘F",
  noSentences: "Dieses Untertiteldokument hat noch keine Sätze.",
  badRegex: "Ungültiger regulärer Ausdruck",
  noResults: "Keine Ergebnisse",
  find: "Finden",
  findPlaceholder: "In Untertiteln suchen",
  previous: "Zurück",
  next: "Als Nächstes",
  closeFind: "Suche schließen",
  replaceWith: "Ersetzen durch",
  matchCase: "Groß-/Kleinschreibung beachten",
  wholeWordShort: "Wort",
  wholeWord: "Nur ganze Wörter",
  regex: "Regulärer Ausdruck · Ersatztext wird unverändert eingefügt",
  replace: "Ersetzen",
  replaceAll: "Alle ersetzen",
  regexError: (error: string) => `Fehler im regulären Ausdruck: ${error}`,
  cutAway: "Das Filmmaterial dieses Satzes wurde herausgeschnitten",
  seekHere: "Abspielkopf zu diesem Satz bewegen",
  readingSpeed: "Lesegeschwindigkeit: Zeichen pro Sekunde",
  editCue: (n: number) => `Untertitel bearbeiten: ${n}`,
  cueText: "Untertiteltext",
  dropLabel: "Untertitel von der Arbeitsfläche entfernen",
  landLabel: "Untertitel wieder auf der Arbeitsfläche anzeigen",
  flipLabel: "Untertitelreihenfolge tauschen",
  applyStyleLabel: "Untertitelstil anwenden",
  listSeparator: ", ",
  noSchema: "(kein schema)",
  editPreset: (name: string) => `Diesen Stil bearbeiten: ${name}`,
  trackName: "Untertitel",
  transcriptRow: "Transkript",
  transcriptRowTip: "Transkript · schreibgeschützt · Dieses Video hat noch keine Untertitelspur. Im Tab „Untertitel“ erzeugen.",
};

export const deNotConfigured: NotConfiguredMessages = {
  'no-default': "Noch kein Modell für Transkription ausgewählt",
  'missing-credential': "Der Transkriptionsdienst hat noch keinen Schlüssel",
  'not-installed': "Das lokale Transkriptionsmodell ist noch nicht installiert",
  'signed-out': "Der Agent ist noch nicht angemeldet",
  outdated: "Die Agentenversion ist zu alt",
  'not-paired': "Der Remote-Knoten ist noch nicht gekoppelt",
  'not-connected': "Der Remote-Knoten ist nicht verbunden",
  unsupported: "Der gewählte Dienst unterstützt keine Transkription",
  disabled: "Der Transkriptionsdienst ist ausgeschaltet",
};

export const deCaptionStyle: CaptionStyleMessages = {

  title: "Untertitelstile",
  back: "Zurück zu Untertiteln",
  open: "Stil ändern",
  openTip: "Untertitelstil-Galerie öffnen: jede Karte zeigt eine andere Darstellung",
  scope: "Anwenden auf",
  scopeAll: "Alle",
  hint: "Jede Karte zeigt Ihre derzeit sichtbaren Untertitel. Anwenden ändert nur die Darstellung; niemals wird eine Zeile hinzugefügt oder entfernt. Zum Hinzufügen oder Ausblenden den Streifen oben oder den Untertitelspur-Kopf in der Zeitleiste verwenden.",
  hintScope: "Wenn „Anwenden auf“ auf eine Zeile zeigt, ändert sich nur diese Zeile; alles andere bleibt gleich.",
  hintMotion: "Social-Karten mit chinesischen Namen animieren normalerweise Wort für Wort oder Zeichen für Zeichen; hier kann nur ihr statisches Aussehen angewendet werden.",
  edit: "Diesen Stil bearbeiten",
  applied: (name: string, lines: string) => `Angewendet: „${name}“ · neu gestaltet: ${lines}`,
  appliedOne: (line: string, name: string, others: string) => `Angewendet: „${name}“ auf ${line}${others ? ` · ${others} unverändert` : ""}`,
  loading: "Untertitelstile werden geladen…",
  foreign: (schema: string) => `Dieser Untertitelstil ist ${schema}; die Galerie kann darauf nicht angewendet werden.`,
  readOnly: "Dieses Video kann derzeit nicht geändert werden; Stilkarten sind nur zur Ansicht.",

  lineSwitch: "Zu bearbeitende Zeile",
  original: "Original",
  translation: "Übersetzung",
  lineOwn: (line: string, n: number) => `${line}: ${n} eigene ${pluralForm('de', n, { one: "Einstellung", other: "Einstellungen" })} für sich; der Rest folgt dem gemeinsamen Stil beider Zeilen.`,
  lineShared: (line: string) => `Änderungen hier gelten nur für ${line}; unveränderte Werte folgen dem gemeinsamen Stil beider Zeilen.`,
  followShared: "Gemeinsamem Stil folgen",
  ratio: (root: string, bi: string, orig: string, source: string, size: string, k: string) =>
    `Grundgröße ${root} × zweisprachiger Skalierung ${bi} ≈ ${orig} (effektive Größe von „${source}“); diese Zeile ${size} = Original × ${k}.`,
  ratioOwn: (size: string) => `Die Größe dieser Zeile ist unabhängig festgelegt auf ${size} und folgt nicht dem Verhältnis zum Original.`,
  originalOwn: (size: string) => `Die Größe des Originals ist unabhängig festgelegt auf ${size}; die Übersetzung folgt ihm nicht mehr.`,
  followRatio: "Wieder dem Verhältnis folgen",
  originalChain: "Größe des Originals ändern; die Übersetzung folgt proportional.",
  place: "Position im Bild",
  places: [
    { key: 'top', label: "Oben", y: 10, valign: 'top' },
    { key: 'middle', label: "Mitte", y: 50, valign: 'center' },
    { key: 'bottom', label: "Unten", y: 90, valign: 'bottom' },
  ] as readonly Place[],
  remembered: 'Geänderte Optionen werden für neue Untertitel gespeichert.',
  fromTop: "Von oben",
  anchor: "Ankerlinie",
  anchors: [
    { key: 'top', label: "Oberkante" },
    { key: 'center', label: "Mittellinie" },
    { key: 'bottom', label: "Unterkante" },
  ] as readonly Choice<'top' | 'center' | 'bottom'>[],
  anchorHint: {
    top: "Oberkante an Ankerlinie fixiert → umgebrochene Zeilen wachsen nach unten.",
    center: "Mittellinie an Ankerlinie fixiert → umgebrochene Zeilen wachsen gleichmäßig nach oben und unten.",
    bottom: "Unterkante an Ankerlinie fixiert → umgebrochene Zeilen wachsen nach oben (üblich für Untertitel).",
  },
  casing: "Groß-/Kleinschreibung",
  cases: [
    { key: 'none', label: "Unverändert" },
    { key: 'uppercase', label: "GROSSBUCHSTABEN" },
    { key: 'title', label: "Titelschreibung" },
    { key: 'lowercase', label: "Kleinbuchstaben" },
  ] as readonly Choice<'none' | 'uppercase' | 'title' | 'lowercase'>[],
  plate: "Form",
  plates: [
    { key: 'wrap', label: "Pro Zeile", note: "Jede Zeile erhält einen eigenen Kasten in ihrer Breite" },
    { key: 'block', label: "Block", note: "Ein Rechteck für den gesamten Untertitel in der Breite der längsten Zeile" },
  ] as readonly Plate[],
};
