import type { CaptionStyleMessages, NotConfiguredMessages, SubtitleMessages } from './subtitle-copy.ts';

export const jaSubtitle: SubtitleMessages = {
  emptyTitle: '字幕はまだありません',
  emptyReady: 'メディアを文字起こしすると、ここで字幕を校正できます。',
  emptyNoMedia: '先に動画または音声ファイルを追加してから、字幕を生成してください。',
  emptyNotPlaced: '動画または音声がまだタイムラインにありません。タイムラインに配置してから字幕を生成してください。',
  emptyReuse: (name: string) => `「${name}」は文字起こし済みです。字幕の生成にはその文字起こしを使い、再認識はしません。`,
  generate: '字幕を生成',
  addMedia: 'メディアを追加',
  importFile: '字幕ファイルを読み込む',
  pickAsset: '字幕を生成する素材',
  pickTranscribe: '文字起こししてから生成',
  pickReuse: '既存の文字起こしから生成 · 再認識なし',

  // 转录中（LiveHead）
  liveTitle: '文字起こし中',
  submitting: '文字起こしを送信中',
  writing: '字幕を生成中',
  transcribed: (done: string, total: string | null) => (total ? `文字起こし済み ${done} / ${total}` : `文字起こし済み ${done}`),
  segments: (done: number, total: number | null) => (total ? `${done} / ${total} 個のセグメントを認識` : `${done} 個のセグメントを認識`),
  stages: ['音声をデコード', '認識', '単語の位置合わせ', '保存'],
  cancel: '文字起こしをキャンセル',
  liveNote: '認識された部分から順に表示されます。文字起こしが完了すると字幕が生成され、ここで 1 行ずつ校正できます。',
  foreignNote: 'この文字起こしは字幕パネルから開始されたものではありません。完了したら「字幕を生成」をクリックして結果を使ってください。',
  liveTip: (pct: number | null, at: string, remain: string | null) =>
    [pct === null ? '文字起こし中' : `文字起こし中 ${pct}%`, `${at} まで完了`, ...(remain ? [`残り ${remain}`] : [])].join(' · '),
  pendingLeft: (remain: string) => `文字起こし中 · 残り ${remain}`,
  cancelled: '文字起こしをキャンセルしました',
  cancelFailed: (message: string) => `文字起こしをキャンセルできませんでした：${message}`,

  // 结果与问题
  generated: (count: number, from: string, to: string) => `字幕を ${count} 件生成しました · ${from} → ${to}`,
  created: (count: number) => `字幕を ${count} 件生成しました`,
  createdShelved: (count: number) =>
    `字幕を ${count} 件生成しました · 原文の字幕がすでに画面にあるため、新しいレイヤーはまだ表示していません。トラックバーでクリックすると画面に表示されます`,
  notConfigured: (reason: string) => `まだ文字起こしできません · ${reason}`,
  submitFailed: '文字起こしを開始できませんでした',
  failed: '文字起こしに失敗しました',
  interrupted: '文字起こしが中断されました',
  noSpeechTitle: '音声が認識されませんでした',
  noSpeech: 'この素材には話し声が含まれていません。',
  noAudioTitle: 'この素材には音声トラックがありません',
  noAudio: '音声のある動画または音声ファイルで再試行してください。',
  offTimelineTitle: '認識された発話はどれもタイムライン上にありません',
  offTimeline: 'この素材のうちタイムラインで使われている部分に発話がないか、素材がタイムラインから外されています。',
  badSpeech: '文字起こしの形式を認識できないため、字幕に分割できません。',
  pendingTitle: '文字起こしは完了しましたが、字幕はまだ生成されていません',
  pending: '文字起こしは動画に保存されています。もう一度「字幕を生成」をクリックすると、文字起こしをやり直さずにそれを使います。',
  writeFailedTitle: '字幕を動画に書き込めませんでした',
  otherVideo: (name: string) => `「${name}」の文字起こしが完了 · その動画に戻って「字幕を生成」をクリックしてください`,
  retry: '再試行',
  dismiss: 'OK',
  unsettledTitle: '文字起こしの結果が不明です',
  unsettled:
    'この認識の応答が返る前に Runtime が再起動しました。すでに課金されている可能性があるため、自動では再送信しません。再試行するか中止するかをバックグラウンドタスクで決めてください。文字起こしが動画に書き込まれると、「字幕を生成」はそれをそのまま使います。',
  unappliedTitle: '文字起こしを動画に書き込めませんでした',
  unapplied: (message: string) =>
    `${message ? `${message}。` : ''}認識結果は残っており、バックグラウンドタスクから動画に再度書き込めます。書き込んだ後は「字幕を生成」がそれをそのまま使います。`,
  decide: 'バックグラウンドタスクで対応',

  // 轨条与样式入口卡
  onScreen: '画面に表示中',
  defaultStyle: '既定のスタイル',
  styleEntry: (n: number) => (n ? `スタイルを編集 · 画面上の字幕トラック ${n} 本` : 'スタイルを編集'),
  styleEntryLabel: '字幕スタイルを編集',
  chipPick: 'この字幕を下で校正',
  chipOff: 'オフ · トラックヘッダーからオンにできます',
  chipLocked: 'ロック中 · トラックヘッダーからロックを解除できます',
  drop: (name: string) => `「${name}」を画面から外す`,
  dropTip: '画面から外す · データは残ります',
  dropLast: '画面に残っている字幕トラックはこれだけです。外すと字幕がなくなります',
  dropped: (name: string) => `「${name}」を画面から外しました · トラックヘッダーから戻せます`,
  putBackTip: (name: string, stacked: boolean) => `「${name}」を画面に戻す${stacked ? ' · 3 本目は先に確認します' : ''}`,
  putBack: (name: string) => `「${name}」を画面に戻しました`,
  stacked: (name: string, n: number) => `「${name}」を重ねました · 現在画面に ${n} 本`,
  stackTitle: (n: number) => `画面に ${n} 本の字幕トラックが表示されます`,
  stackBody: (name: string, n: number) => `「${name}」を戻すと ${n} 本が同時に表示されます。縦長の動画では 3 本で画面のかなりの部分を占めます。`,
  stackConfirm: 'もう 1 本重ねる',
  cancelLabel: 'キャンセル',
  translate: '翻訳先…',
  translateOff: '翻訳はまだ接続されていません。テキストモデルと翻訳ワークフローは開発中です',
  translateTip: '翻訳先の言語とテキストモデルを選びます。訳文は新しい字幕トラックとして画面に表示されます',
  translatingLabel: (language: string) => `${language} に翻訳中`,
  flip: '上下反転 ⇅',
  flipTip: '2 行の上下を入れ替えます。上の行がメインで、文字が大きくなります',
  flipOff: '原文と訳文が同じスタイルを共有し、両方とも画面にあるときだけ反転できます。まだそのような組はありません',
  flipped: (translationFirst: boolean) =>
    `反転しました · ${translationFirst ? '訳文が上、原文が下' : '原文が上、訳文が下'}`,

  // 列表
  stats: (cues: number, sentences: number) => `字幕 ${cues} 件 · ${sentences} 文`,
  seam: '前の字幕に結合',
  seamSpeaker: '話者が異なる · 結合できません',
  undo: '取り消す',
  panelTitle: '字幕',
  importFileTip: '字幕ファイルを読み込む（SRT、WebVTT、ASS）',
  importUnsupported: 'SRT、WebVTT、ASS の字幕ファイルのみ対応しています',
  importEmpty: (file: string) => `「${file}」に字幕が見つかりません`,
  importLabel: '字幕を読み込む',
  imported: (count: number, end: string) => `字幕を ${count} 件読み込みました · 0:00 → ${end}`,
  readingCues: '字幕を読み込み中…',
  unsupportedDoc: 'この字幕ドキュメントの形式は、ここではまだ編集できません。',
  rewriteLabel: '字幕を編集',
  rewritten: '字幕を編集しました',
  splitLabel: '字幕を分割',
  splitDone: '2 つに分割しました · 時間は文字数で配分',
  mergeSpeaker: '話者が異なる · 結合できません',
  firstCue: 'すでに最初の字幕です',
  lastCue: 'すでに最後の字幕です',
  mergeLabel: '字幕を結合',
  mergedUp: '前の字幕に結合しました · 時間をつなげました',
  mergedDown: '次の字幕に結合しました · 時間をつなげました',
  noChanges: '変更が必要な一致はありません',
  replaceLabel: '字幕テキストを置換',
  replaced: (count: number) => `${count} 件を置換しました`,
  tooFast: (count: number) => `${count} 件が読む速さの上限を超えています`,
  keysHint: 'Enter で分割 · 行頭で ⌫ を押すと前と結合 · 行末で ⌦ を押すと次と結合',
  findReplace: '検索と置換',
  findReplaceTip: '検索と置換 · ⌘F',
  noSentences: 'この字幕ドキュメントにはまだ文がありません。',
  badRegex: '無効な正規表現',
  noResults: '結果なし',
  find: '検索',
  findPlaceholder: '字幕内を検索',
  previous: '前へ',
  next: '次へ',
  closeFind: '検索を閉じる',
  replaceWith: '置換後',
  matchCase: '大文字と小文字を区別',
  wholeWordShort: '単語',
  wholeWord: '単語単位で一致',
  regex: '正規表現 · 置換テキストはそのまま挿入されます',
  replace: '置換',
  replaceAll: 'すべて置換',
  regexError: (error: string) => `正規表現のエラー：${error}`,
  cutAway: 'この文の映像はカットされています',
  seekHere: '再生ヘッドをこの文に移動',
  readingSpeed: '読む速さ：1 秒あたりの文字数',
  editCue: (n: number) => `字幕 ${n} を編集`,
  cueText: '字幕テキスト',
  dropLabel: '字幕をキャンバスから外す',
  landLabel: '字幕をキャンバスに戻す',
  flipLabel: '字幕の上下を入れ替え',
  applyStyleLabel: '字幕スタイルを適用',
  listSeparator: '、',
  noSchema: '（schema なし）',
  editPreset: (name: string) => `このスタイルを編集：${name}`,
  trackName: '字幕',
};

export const jaNotConfigured: NotConfiguredMessages = {
  'no-default': '文字起こしに使うモデルがまだ選ばれていません',
  'missing-credential': '文字起こしサービスのキーがまだ設定されていません',
  'not-installed': 'ローカルの文字起こしモデルがまだインストールされていません',
  'signed-out': 'Agent はまだサインインしていません',
  outdated: 'Agent のバージョンが古すぎます',
  'not-paired': 'リモートノードがまだペアリングされていません',
  'not-connected': 'リモートノードに接続されていません',
  unsupported: '選択したサービスは文字起こしに対応していません',
  disabled: '文字起こしサービスはオフになっています',
};

export const jaCaptionStyle: CaptionStyleMessages = {
  // 画廊
  title: '字幕スタイル',
  back: '字幕に戻る',
  open: 'スタイルを変更',
  openTip: '字幕スタイルのギャラリーを開きます。カードごとに見た目が異なります',
  scope: '適用先',
  scopeAll: 'すべて',
  hint: '各カードには、いま画面にある字幕がそのまま表示されています。適用しても見た目が変わるだけで、行が増えたり減ったりはしません。行を追加したり外したりするには、上のトラックバーかタイムラインの字幕トラックヘッダーを使ってください。',
  hintScope: '「適用先」で 1 行を指定すると、その行だけが変わり、ほかは何も変わりません。',
  hintMotion: 'ソーシャルにある中国語名のカードは本来、単語単位または文字単位のアニメーションが付いています。ここで適用できるのは静止した見た目だけです。',
  edit: 'このスタイルを編集',
  applied: (name: string, lines: string) => `「${name}」を適用しました · ${lines} のスタイルを変更`,
  appliedOne: (line: string, name: string, others: string) => `${line} に「${name}」を適用しました${others ? ` · ${others} は変更なし` : ''}`,
  loading: '字幕スタイルを読み込み中…',
  foreign: (schema: string) => `この字幕スタイルは ${schema} のため、ギャラリーから適用できません。`,
  readOnly: 'この動画は現在変更できないため、スタイルカードは表示のみです。',

  // 属性页
  lineSwitch: '編集する行',
  original: '原文',
  translation: '訳文',
  lineOwn: (line: string, n: number) => `${line} には独自の設定が ${n} 項目あります。それ以外は 2 行共通のスタイルに従います。`,
  lineShared: (line: string) => `ここでの変更は ${line} にのみ適用されます。変更していない項目は 2 行共通のスタイルに従います。`,
  followShared: '共通スタイルに従う',
  ratio: (root: string, bi: string, orig: string, source: string, size: string, k: string) =>
    `基本サイズ ${root} × 二言語倍率 ${bi} ≈ ${orig}（「${source}」の実効サイズ）。この行の ${size} = 原文 × ${k}。`,
  ratioOwn: (size: string) => `この行のサイズは個別に ${size} に設定されており、原文の比率には従いません。`,
  originalOwn: (size: string) => `原文のサイズは個別に ${size} に設定されています。訳文はもう連動しません。`,
  followRatio: '比率に戻す',
  originalChain: '原文のサイズを変えると、訳文も比率に応じて変わります。',
  place: '画面上の位置',
  places: [
    { key: 'top', label: '上部', y: 10, valign: 'top' },
    { key: 'middle', label: '中央', y: 50, valign: 'center' },
    { key: 'bottom', label: '下部', y: 90, valign: 'bottom' },
  ],
  remembered: '変更した設定は保存され、新しい字幕にも使われます。',
  fromTop: '上端から',
  anchor: '基準線',
  anchors: [
    { key: 'top', label: '上端' },
    { key: 'center', label: '中心線' },
    { key: 'bottom', label: '下端' },
  ],
  anchorHint: {
    top: '上端を基準線に固定 → 折り返した行は下に伸びます。',
    center: '中心線を基準線に固定 → 折り返した行は上下に均等に伸びます。',
    bottom: '下端を基準線に固定 → 折り返した行は上に伸びます（字幕では一般的）。',
  },
  casing: '大文字と小文字',
  cases: [
    { key: 'none', label: 'そのまま' },
    { key: 'uppercase', label: 'すべて大文字' },
    { key: 'title', label: 'タイトルケース' },
    { key: 'lowercase', label: 'すべて小文字' },
  ],
  plate: '形状',
  plates: [
    { key: 'wrap', label: '行ごと', note: '行ごとに、その行の幅に合わせたボックスを付けます' },
    { key: 'block', label: 'ブロック', note: '字幕全体を 1 つの長方形で囲み、最も長い行の幅に合わせます' },
  ],
};
