import type { CaptionStyleMessages, NotConfiguredMessages, SubtitleMessages } from './subtitle-copy.ts';

import { pluralForm } from '@baocut/protocol';
const subtitles = (n: number) => `${n} ${pluralForm('pt-BR', n, { one: 'legenda', other: 'legendas' })}`;
type Choice<K extends string> = { readonly key: K; readonly label: string };
type Place = Choice<'top' | 'middle' | 'bottom'> & { readonly y: number; readonly valign: 'top' | 'center' | 'bottom' };
type Plate = Choice<'wrap' | 'block'> & { readonly note: string };

export const ptBRSubtitle: SubtitleMessages = {
  emptyTitle: "Ainda não há legendas",
  emptyReady: "Transcreva sua mídia para editar as legendas aqui.",
  emptyNoMedia: "Adicione vídeo ou áudio primeiro e depois crie as legendas.",

  emptyNotPlaced: "Vídeo ou áudio ainda fora da linha do tempo. Coloque antes de gerar legendas.",
  emptyReuse: (name: string) => `“${name}” já está transcrito; usa a transcrição sem reconhecer novamente.`,
  generate: "Gerar legendas",
  addMedia: "Adicionar mídia",
  importFile: "Importar arquivo de legendas",
  pickAsset: "Mídia para gerar legendas",
  pickTranscribe: "Transcrever, depois gerar",
  pickReuse: "Gerar da transcrição · sem novo reconhecimento",

  liveTitle: "Transcrevendo",
  submitting: "Enviando transcrição",
  writing: "Gerar legendas",
  transcribed: (done: string, total: string | null) => (total ? `Transcritos ${done} / ${total}` : `Transcritos ${done}`),
  segments: (done, total) => `Reconhecimento: ${done}${total ? ` / ${total}` : ''} ${pluralForm('pt-BR', total ?? done, { one: 'segmento', other: 'segmentos' })}`,
  stages: ["Decodificar áudio", "Reconhecer", "Alinhar palavras", "Salvar"],
  cancel: "Cancelar transcrição",

  liveNote: "As partes reconhecidas aparecem uma a uma. Ao fim da transcrição, as legendas são geradas e você pode revisá-las aqui linha a linha.",
  foreignNote: "Esta transcrição não começou no painel Legendas. Ao concluir, clique “Gerar legendas” para usar o resultado.",
  liveTip: (pct: number | null, at: string, remain: string | null) =>
    [pct === null ? "Transcrevendo" : `Transcrevendo ${pct}%`, `transcrito até ${at}`, ...(remain ? [`faltam ${remain}`] : [])].join(' · '),
  pendingLeft: (remain: string) => `Transcrevendo · faltam ${remain}`,
  cancelled: "Transcrição cancelada",
  cancelFailed: (message: string) => `Não foi possível cancelar transcrição: ${message}`,

  generated: (count: number, from: string, to: string) => `Geradas ${subtitles(count)} · ${from} → ${to}`,
  created: (count: number) => `Geradas ${subtitles(count)}`,

  createdShelved: (count: number) =>
    `Geradas ${subtitles(count)} · original já na tela; nova camada oculta. Clique nela na faixa de opções para exibir`,
  notConfigured: (reason: string) => `Ainda não pode transcrever · ${reason}`,
  submitFailed: "Não foi possível iniciar transcrição",
  failed: "Falha na transcrição",
  interrupted: "Transcrição interrompida",
  noSpeechTitle: "Nenhuma fala reconhecida",
  noSpeech: "Não há fala audível nesta mídia.",
  noAudioTitle: "Esta mídia não tem faixa de áudio",
  noAudio: "Tente com vídeo ou áudio que tenha som.",
  offTimelineTitle: "Nenhuma fala reconhecida está na linha do tempo",
  offTimeline: "A parte desta mídia na linha do tempo não tem fala, ou a mídia foi removida.",
  badSpeech: "Formato de transcrição não reconhecido; não pode dividir em legendas.",
  pendingTitle: "Transcrição concluída, legendas ainda não geradas",
  pending: "Transcrição salva no vídeo; clique “Gerar legendas” sem transcrever novamente.",
  writeFailedTitle: "As legendas não foram gravadas no vídeo",
  otherVideo: (name: string) => `“${name}” transcrito · volte ao vídeo e clique “Gerar legendas”`,
  retry: "Tentar novamente",
  dismiss: "Entendi",
  unsettledTitle: "Resultado de transcrição desconhecido",
  unsettled:
    "Runtime reiniciou antes da resposta. Cobrança possível; não reenvia automaticamente. Decida em Tarefas em segundo plano se repete ou descarta. Após gravar, “Gerar legendas” usa direto.",
  unappliedTitle: "A transcrição não foi gravada no vídeo",
  unapplied: (message: string) =>
    `${message ? `${message}. ` : ""}Resultado ainda disponível; grave pelo painel Tarefas em segundo plano. Depois “Gerar legendas” usa direto.`,
  decide: "Resolver em Tarefas em segundo plano",

  onScreen: "Na tela",
  defaultStyle: "Estilo padrão",
  styleEntry: (n: number) => (n ? `Editar estilo · ${n} faixa de legendas${pluralForm('pt-BR', n, { one: "", other: "s" })} na tela` : "Editar estilo"),
  styleEntryLabel: "Editar estilo de legendas",
  chipPick: "Revisar esta abaixo",
  chipOff: "Desativada · ative no cabeçalho da linha do tempo",
  chipLocked: "Bloqueada · desbloqueie pelo cabeçalho",
  drop: (name: string) => `Retirar “${name}” da tela`,
  dropTip: "Tirar da tela · mantém os dados",
  dropLast: "Única faixa de legendas na tela; retirar deixa sem legendas",
  dropped: (name: string) => `Retirado “${name}” da tela · restaure pelo cabeçalho`,
  putBackTip: (name: string, stacked: boolean) => `Restaurar “${name}” na tela${stacked ? " · uma terceira pede confirmação" : ""}`,
  putBack: (name: string) => `Restaurar “${name}” na tela`,
  stacked: (name: string, n: number) => `Sobreposto “${name}” · ${n} na tela agora`,
  stackTitle: (n: number) => `${n} faixas de legendas ficarão na tela`,
  stackBody: (name: string, n: number) => `Restaurar “${name}” exibe ${n} juntas; em vídeo vertical, três ocupam boa parte da tela.`,
  stackConfirm: "Sobrepor outra",
  cancelLabel: "Cancelar",
  translate: "Traduzir para…",
  translateOff: "Tradução ainda não conectada; modelo de texto e fluxo em desenvolvimento",
  translateTip: "Escolha idioma e modelo; a tradução aparece como nova faixa de legendas",
  translatingLabel: (language: string) => `Traduzindo para ${language}`,
  flip: "Inverter ⇅",
  flipTip: "Inverte as duas linhas; a de cima é a principal e maior",
  flipOff: "Só pode inverter com original e tradução no mesmo estilo e visíveis; ainda não há par",
  flipped: (translationFirst: boolean) =>
    `Invertido · ${translationFirst ? "tradução acima, original abaixo" : "original acima, tradução abaixo"}`,

  stats: (cues: number, sentences: number) => `${subtitles(cues)} · ${sentences} frase${pluralForm('pt-BR', sentences, { one: "", other: "s" })}`,
  seam: "Merge up",
  seamSpeaker: "Only adjacent cues from the same speaker can be merged",
  undo: "Desfazer",
  panelTitle: "Legendas",
  importFileTip: "Importar legendas (SRT, WebVTT, ASS)",
  importUnsupported: "Só arquivos SRT, WebVTT e ASS são aceitos",
  importEmpty: (file: string) => `Nenhuma legenda em “${file}”`,
  importLabel: "Importar legendas",
  imported: (count: number, end: string) => `Importadas ${count} legendas · 0:00 → ${end}`,
  readingCues: "Carregando legendas…",
  unsupportedDoc: "Formato deste documento ainda não pode ser editado aqui.",
  rewriteLabel: "Editar legenda",
  rewritten: "Legenda editada",
  splitLabel: "Dividir legenda",
  splitDone: "Dividida em duas · tempo distribuído por caracteres",
  mergeSpeaker: "Only adjacent cues from the same speaker can be merged",
  firstCue: "Já é a primeira",
  lastCue: "Já é a última",
  mergeLabel: "Mesclar legendas",
  mergedUp: "Mesclada à anterior · tempos unidos",
  mergedDown: "Mesclada à próxima · tempos unidos",
  noChanges: "Sem correspondências para alterar",
  replaceLabel: "Substituir texto das legendas",
  replaced: (count: number) => `Substituídos ${count}`,
  tooFast: (count: number) => `${count} acima da velocidade de leitura`,
  keysHint: "Enter divide · ⌫ no início mescla acima · ⌦ no fim mescla abaixo",
  findReplace: "Localizar e substituir",
  findReplaceTip: "Localizar e substituir · ⌘F",
  noSentences: "Este documento ainda não tem frases.",
  badRegex: "Padrão inválido",
  noResults: "Sem resultados",
  find: "Encontrar",
  findPlaceholder: "Localizar nas legendas",
  previous: "Anterior",
  next: "Próximos passos",
  closeFind: "Fechar busca",
  replaceWith: "Substitua por",
  matchCase: "Diferenciar maiúsculas",
  wholeWordShort: "Palavra",
  wholeWord: "Palavra inteira",
  regex: "Expressão regular · substituição inserida literalmente",
  replace: "Substituir",
  replaceAll: "Substituir tudo",
  regexError: (error: string) => `Erro na expressão regular: ${error}`,
  cutAway: "As imagens desta frase foram cortadas",
  seekHere: "Mover indicador de reprodução para esta frase",
  readingSpeed: "Velocidade de leitura: caracteres por segundo",
  editCue: (n: number) => `Editar legenda ${n}`,
  cueText: "Texto da legenda",
  dropLabel: "Retirar legendas da tela",
  landLabel: "Restaurar legendas na tela",
  flipLabel: "Inverter ordem das legendas",
  applyStyleLabel: "Aplicar estilo das legendas",
  listSeparator: ", ",
  noSchema: "(sem schema)",
  editPreset: (name: string) => `Editar este estilo: ${name}`,
  trackName: "Legendas",
  transcriptRow: "Transcrição",
  transcriptRowTip: "Transcrição · somente leitura · Este vídeo ainda não tem faixa de legendas. Gere uma na aba Legendas.",
};

export const ptBRNotConfigured: NotConfiguredMessages = {
  'no-default': "Sem modelo de transcrição escolhido",
  'missing-credential': "Serviço de transcrição sem chave",
  'not-installed': "Modelo local de transcrição não instalado",
  'signed-out': "Agente ainda não conectado",
  outdated: "Versão do agente antiga demais",
  'not-paired': "Nó remoto ainda não pareado",
  'not-connected': "Nó remoto não conectado",
  unsupported: "Serviço escolhido não transcreve",
  disabled: "Serviço de transcrição desativado",
};

export const ptBRCaptionStyle: CaptionStyleMessages = {

  title: "Estilo de legendas",
  back: "Voltar às Legendas",
  open: "Mudar estilo",
  openTip: "Abrir galeria de estilos; cada cartão tem visual diferente",
  scope: "Aplicar a",
  scopeAll: "Todos",
  hint: "Cada cartão é pintado com as legendas que estão na sua tela agora. Aplicar um só muda o visual — nunca adiciona nem remove uma faixa; para isso use a faixa de trilhas acima ou os cabeçalhos de legenda na linha do tempo.",
  hintScope: "Aponte “Aplicar a” para uma faixa e só ela muda; a outra fica como está.",
  edit: "Editar este estilo",
  applied: (name: string, lines: string) => `Aplicado “${name}” · estilo alterado em ${lines}`,
  appliedOne: (line: string, name: string, others: string) => `Aplicado “${name}” a ${line}${others ? ` · ${others} inalteradas` : ""}`,
  loading: "Carregando estilos de legendas…",
  foreign: (schema: string) => `Este estilo de legendas é ${schema}; a galeria não pode aplicar.`,
  readOnly: "Vídeo não editável agora; cartões só para visualizar.",

  lineSwitch: "Linha para editar",
  original: "Original",
  translation: "Tradução",
  lineOwn: (line, n) => `${line} tem ${n} ${pluralForm('pt-BR', n, { one: 'configuração própria', other: 'configurações próprias' })}; o restante segue o estilo compartilhado das linhas.`,
  lineShared: (line: string) => `Mudanças aqui afetam só ${line}; o que não mudar segue o estilo compartilhado.`,
  followShared: "Seguir estilo compartilhado",
  ratio: (root: string, bi: string, orig: string, source: string, size: string, k: string) =>
    `Tamanho base ${root} × escala bilíngue ${bi} ≈ ${orig} (tamanho efetivo de “${source}”); esta linha ${size} = original × ${k}.`,
  ratioOwn: (size: string) => `Tamanho desta linha definido para ${size} independentemente, sem seguir a proporção original.`,
  originalOwn: (size: string) => `Tamanho do original definido para ${size} independentemente; a tradução não segue mais.`,
  followRatio: "Seguir proporção novamente",
  originalChain: "Mude o tamanho do original; a tradução segue proporcionalmente.",
  place: "Posição na tela",
  places: [
    { key: 'top', label: "Superior", y: 10, valign: 'top' },
    { key: 'middle', label: "Meio", y: 50, valign: 'center' },
    { key: 'bottom', label: "Inferior", y: 90, valign: 'bottom' },
  ] as readonly Place[],
  remembered: 'As opções alteradas são salvas para novas legendas.',
  fromTop: "Do topo",
  anchor: "Linha de âncora",
  anchors: [
    { key: 'top', label: "Borda superior" },
    { key: 'center', label: "Linha central" },
    { key: 'bottom', label: "Borda inferior" },
  ] as readonly Choice<'top' | 'center' | 'bottom'>[],
  anchorHint: {
    top: "A borda superior fica presa à linha de âncora, então as linhas quebradas crescem para baixo.",
    center: "O meio fica preso à linha de âncora, então as linhas quebradas crescem igualmente para cima e para baixo.",
    bottom: "A borda inferior fica presa à linha de âncora, então as linhas quebradas crescem para cima — o padrão das legendas.",
  },
  casing: "Maiúsculas",
  cases: [
    { key: 'none', label: "Como está" },
    { key: 'uppercase', label: "MAIÚSCULAS" },
    { key: 'title', label: "Iniciais maiúsculas" },
    { key: 'lowercase', label: "minúsculas" },
  ] as readonly Choice<'none' | 'uppercase' | 'title' | 'lowercase'>[],
  plate: "Forma",
  plates: [
    { key: 'wrap', label: "Por linha", note: "Uma caixa por linha, na largura dela" },
    { key: 'block', label: "Bloco", note: "Um retângulo para a legenda inteira, com largura da maior linha" },
  ] as readonly Plate[],
};
