import type { TextNotConfiguredMessages, TranslateMessages } from './translate-copy.ts';

export const trTranslate: TranslateMessages = {
  // 设置页（TranslateFlow）
  title: "Yeni dile çevir",
  back: "Altyazı kısmına dön",
  target: "Hedef dil",
  targetPicker: "Çevrilecek dil",
  source: "Özgün",
  sourcePicker: "Çevrilecek döküm",
  sourceLine: (language, sentences) => sentences === null ? language : `${language} · ${sentences} cümle`,
  model: "Metin modeli",
  modelPicker: "Çeviri için metin modeli",
  manage: "Metin modellerini yönet…",
  modelsLoading: "Metin modelleri yükleniyor…",
  noStructured: "Yapılandırılmış çıktı yok · çeviride kullanılamaz",
  notConfiguredTitle: "Henüz kullanılabilir metin modeli yok",
  notConfiguredBody: "Çeviri metin modelini gruplar halinde çağırır. Ayarlar › Modeller › Metin oluşturma kısmında sağlayıcı bağlayın (anahtarını girin), yapılandırılmış çıktı destekleyen model seçip başlamak için dönün.",
  goModels: "Ayarlar › Modeller › Metin oluşturma aç",
  style: "Stil ipucu",
  stylePlaceholder: "Örneğin konuşma dili, kısa; adları özgün halde koru",
  styleHint: "İsteğe bağlı; en fazla 500 karakter.",
  glossary: "Sözlük",
  glossaryNote: "İşaretli = bu videoda etkin (geri alınabilir düzenleme). Yönü eşleşen etkin sözlükler kullanılır; çok öğe varsa her grupta yalnızca kaynakta görünenler gönderilir.",
  glossaryManage: "Sözlükleri yönet…",
  glossaryEmpty: (target) => `Sözlük kitaplığında henüz ${target} diline çeviri sözlüğü yok.`,
  glossaryLoading: "Sözlükler yükleniyor…",
  glossaryCount: (terms, hits) => `${terms} öğe · videoda ${hits} bulundu`,
  glossaryFailed: (message) => `Bu videoda etkin sözlükler okunamadı: ${message}`,
  glossaryReadOnly: "Video salt okunur; etkin sözlükleri değiştirilemez.",
  glossaryLimit: (max) => `Tek adımda en fazla ${max} sözlük etkin olabilir`,
  glossaryOn: (name) => `Bu video için “${name}” etkinleştirildi`,
  glossaryOff: (name) => `“${name}” kapatıldı`,
  glossaryWriteFailed: (message) => `Etkin sözlükler değiştirilemedi: ${message}`,
  bilingual: "İki dili göster",
  bilingualHint: "Bitince kaynak ve çeviri birlikte görünür. Kapalıysa yalnızca çeviri görünür; kaynak ekrandan alınır, silinmez.",
  cta: (language) => `${language} diline çevir`,
  ctaHint: "Bitince otomatik görüntüye yerleştirilir; her zaman geri alınabilir. Çevrimiçi modeller token başına ücretlendirilir.",
  noSpeechTitle: "Henüz çevrilecek döküm yok",
  noSpeech: "Çeviri dökümden cümle cümle çalışır. Önce Altyazı panelinde “Altyazı oluştur” ile medyayı yazıya dökün; içe aktarılan altyazılarda sözcük zamanları yoktur, doğrudan çevrilemez.",
  busy: "Bu video zaten çevriliyor; başka dile başlamadan önce bitmesini bekleyin.",
  readOnly: "Video salt okunur; çevrilemez.",
  allTaken: "Tüm yaygın dillerin çevirisi var.",

  // 运行态
  submitting: "Çeviri gönderiliyor",
  queued: "Sırada",
  running: (from, to) => `Çevriliyor · ${from} → ${to}`,
  stepUnits: (done, total) => total ? `${done} / ${total} cümle çevrildi` : `${done} cümle çevrildi`,
  cancel: "Çeviriyi iptal et",
  cancelled: "Çeviri iptal edildi",
  cancelFailed: (message) => `Çeviri iptal edilemedi: ${message}`,
  liveNote: "Bitince otomatik görüntüye yerleştirilir; her zaman geri alınabilir. Bu sayfadan ayrılabilirsiniz.",
  foreign: "Bu çeviri buradan başlatılmadı. Bitince karşılaştırma listesinde “Ekrana yerleştir” kullanın.",
  agentNote: "Agent cümle cümle çevirir ve bitince çeviriyi videoya yazar",
  agentSession: "Bir Agent oturumu çeviriyor. Durdurmak için oturumu durdurun.",
  chipTip: (step) => `Çevriliyor · ${step}`,

  // 问题
  notConfigured: (reason) => `Henüz çevrilemiyor · ${reason}`,
  submitFailed: "Çeviri başlatılamadı",
  failed: "Çeviri başarısız",
  interrupted: "Çeviri kesildi",
  retry: "Yeniden dene",
  retrying: "Yeniden deneniyor",
  retryFailed: (message) => `Yeniden denenemedi: ${message}`,
  retryCharges: "Yeniden deneme durduğu adımdan devam eder. “Çevir” adımında durduysa model yeniden çağrılır, yeniden ücretlendirilebilir.",
  retryFree: "Yeniden deneme durduğu adımdan devam eder; tamamlanmış çeviriler modeli yeniden çağırmaz.",
  dismiss: "Tamam",
  decide: "Arka plan görevleri kısmında çöz",
  emptyTitle: "Çeviride görüntüye yerleştirilecek cümle yok",
  empty: "Çevirinin tüm cümleleri güncel değil veya boş.",
  pendingTitle: "Çeviri bitti ancak henüz görüntüde değil",
  pending: "Çeviri videoda kaydedildi. Karşılaştırma listesinde “Ekrana yerleştir” tıklayın.",
  offTimeline: "Zaman çizelgesinde bu medyayı kullanan klip yok; altyazılar ekrana konamaz. Çeviri videoda kaydedildi; karşılaştırma listesinde “Ekrana yerleştir” tıklayın.",
  badDocument: "Çeviri veya döküm biçimi tanınmıyor; altyazılara bölünemez.",

  // 回执
  applied: (language, count) => `Uygulandı · ${language} diline çevrildi · ${count} altyazı`,
  appliedNote: (bilingual) => bilingual ? 'Özgün metin ve çeviri birlikte görünür.' : 'Yalnızca çeviri görünür; özgün metin ekrandan alındı (silinmedi, şeritten geri koyabilirsiniz).',
  undo: "Geri al",
  done: "Tamamlandı",
  undone: (language) => `Geri alındı · ${language} altyazıları ekrandan kaldırıldı`,
  undoneNote: "Özgün metne dokunulmadı; çeviri videoda kalır. Karşılaştırma listesinden tekrar “Ekrana yerleştir” kullanabilirsiniz.",
  undoFailed: "Geri alınamadı: bu adımdan sonra video değişti. Düzenleyicide geri alın.",

  // 放到画面上
  place: "Ekrandaki konum",
  placing: "Ekrana yerleştiriliyor",
  unnamed: "Çeviri",
  placed: (language, count) => `${language} çevirisi ekrana yerleştirildi · ${count} altyazı`,
  notPlaced: "Bu çeviri henüz görüntüde değil.",

  // 对照条与列表
  list: "Liste",
  modes: { src: "Yalnızca orijinal", bi: "Orijinal + çeviri", trans: "Yalnızca çeviri" },
  compareLanguage: "Karşılaştırılacak çeviri",
  noTranslation: "Henüz çeviri yok · önce şeritte “… diline çevir” kullanın",
  original: (language) => `Özgün metin · ${language}`,
  translation: (language) => `Çeviri · ${language}`,
  reading: "Çeviri yükleniyor…",
  unreadable: "Bu çevirinin biçimi henüz burada gösterilemiyor.",
  speechMissing: "Bu çevirinin dökümü artık videoda yok.",
  stats: (count) => `${count} cümle`,
  untranslated: (n) => `${n} cümle çevrilmedi`,
  stale: (n) => `${n} çevrilmiş cümle güncel değil`,
  gone: (n) => `${n} özgün cümle silindi`,
  allFresh: "Tüm çeviriler güncel ✓",
  refreshHint: "Doğrudan düzenlemek için çeviriye tıklayın; düzenlenenler güncel sayılır. Yalnızca bu cümleleri yeniden çevirmek için ajana verin:",
  refreshOpen: "Eski çevirileri güncelle",
  refreshHintWeb: "Doğrudan düzenlemek için çeviriye tıklayın; düzenlenenler güncel sayılır.",
  chipStale: "Güncel değil",
  chipUntranslated: "Çevrilmedi",
  chipGone: "Özgün metin silindi",
  goneTip: "Cümle artık dökümde yok; çevirisi görüntüye gelmez ve düzenlenemez.",
  emptyPlaceholder: "(Henüz çeviri yok · doldurmak için tıklayın)",
  editLabel: (n) => `${n} cümlesinin çevirisini düzenle`,
  editing: "Çeviri",
  editHint: "Yeniden yazmak için çevrilmiş cümleye tıklayın: dışarı tıklayınca kaydedilir, Esc iptal eder. Görüntüdeki altyazılar güncellenir.",
  editTail: "Düzenlemek için çeviriye tıklayın",
  noRows: "Bu çeviride henüz cümle yok.",
  edited: "Bu çevrilmiş cümle yeniden yazıldı",
  editFailed: (message) => `Yeniden yazılamadı: ${message}`,
  seekTip: "Oynatma kafasını bu cümleye taşı",
  cutTip: "Bu cümlenin görüntüsü kesildi",
  translateTo: (language) => `${language} diline çevir`,
  rewriteTranslation: "Çeviriyi düzenle",
  unknownLanguage: "Bilinmeyen dil",
  targetLanguage: "hedef dil",
};

export const trTextNotConfigured: TextNotConfiguredMessages = {
  'no-default': "Metin oluşturma için henüz model seçilmedi",
  'missing-credential': "Metin modelinin sağlayıcısında henüz anahtar yok",
  'not-installed': "Metin modeli henüz yüklü değil",
  'signed-out': "Ajan henüz giriş yapmadı",
  outdated: "Ajan sürümü çok eski",
  'not-paired': "Uzak düğüm henüz eşleştirilmedi",
  'not-connected': "Uzak düğüm bağlı değil",
  unsupported: "Seçilen hizmet metin oluşturmayı desteklemiyor",
  disabled: "Metin oluşturma hizmeti kapalı",
};
