const sentences = (n: number) => pluralForm('pl', n, { one: `${n} zdanie`, few: `${n} zdania`, many: `${n} zdań`, other: `${n} zdania` });
const subtitles = (n: number) => pluralForm('pl', n, { one: `${n} napis`, few: `${n} napisy`, many: `${n} napisów`, other: `${n} napisu` });
import { pluralForm } from '@baocut/protocol';
import type { TextNotConfiguredMessages, TranslateMessages } from './translate-copy.ts';

export const plTranslate: TranslateMessages = {

  title: "Przetłumacz na nowy język",
  back: "Wróć do napisów",
  target: "Język docelowy",
  targetPicker: "Język tłumaczenia",
  source: "Oryginał",
  sourcePicker: "Transkrypcja do tłumaczenia",
  sourceLine: (language: string, count: number | null) => (count === null ? language : `${language} · ${sentences(count)}`),
  model: "Model tekstowy",
  modelPicker: "Model tekstowy tłumaczenia",
  manage: "Zarządzaj modelami tekstowymi…",
  modelsLoading: "Wczytywanie modeli tekstowych…",
  noStructured: "Bez wyniku strukturalnego · tłumaczenie niemożliwe",
  notConfiguredTitle: "Nie ma jeszcze dostępnego modelu tekstowego",
  notConfiguredBody: "Tłumaczenie wywołuje model partiami. W Ustawienia › Modele › Generowanie tekstu połącz dostawcę (klucz) i wybierz model z wynikiem strukturalnym, potem wróć.",
  goModels: "Otwórz Ustawienia › Modele › Generowanie tekstu",
  style: "Wskazówka stylu",
  stylePlaceholder: "Np. swobodnie, zwięźle; zachowaj oryginalne imiona",
  styleHint: "Opcjonalnie; do 500 znaków.",
  glossary: "Słownik",
  glossaryNote: "Zaznaczone = włączone dla wideo (można cofnąć). Tłumaczenie używa włączonych słowników właściwego kierunku; każda partia zawiera tylko wpisy z oryginału.",
  glossaryManage: "Zarządzaj słownikami…",
  glossaryEmpty: (target: string) => `Biblioteka nie ma słowników tłumaczenia na ${target} jeszcze.`,
  glossaryLoading: "Wczytywanie słowników…",
  glossaryCount: (terms: number, hits: number) => `${terms} ${pluralForm('pl', terms, { one: "wpis", few: "wpisy", many: "wpisów", other: "wpisu" })} · ${hits} znaleziono w wideo`,
  glossaryFailed: (message: string) => `Nie można odczytać włączonych słowników wideo: ${message}`,
  glossaryReadOnly: "Wideo tylko do odczytu, nie można zmienić włączonych słowników.",
  glossaryLimit: (max: number) => `Najwyżej ${max} słowników można włączyć w kroku`,
  glossaryOn: (name: string) => `Włączono słownik „${name}” dla tego wideo`,
  glossaryOff: (name: string) => `Wyłączono słownik „${name}” dla tego wideo`,
  glossaryWriteFailed: (message: string) => `Nie udało się zmienić włączonych słowników: ${message}`,
  bilingual: "Pokaż oba języki",
  bilingualHint: "Po tłumaczeniu oryginał i tłumaczenie razem na ekranie. Po wyłączeniu tylko tłumaczenie, oryginał zdjęty (nieusunięty).",
  cta: (language: string) => `Przetłumacz na ${language}`,
  ctaHint: "Po ukończeniu automatycznie na ekranie, można cofnąć. Modele online rozliczane za tokeny.",
  noSpeechTitle: "Brak transkrypcji do tłumaczenia",
  noSpeech: "Tłumaczenie działa zdanie po zdaniu z transkrypcji. Najpierw transkrybuj przez „Generuj napisy” w panelu „Napisy”; importowane pliki bez czasu słów nie są tłumaczone bezpośrednio.",
  busy: "Wideo jest już tłumaczone; poczekaj przed innym językiem.",
  readOnly: "Wideo tylko do odczytu, tłumaczenie niemożliwe.",
  allTaken: "Wszystkie popularne języki już przetłumaczone.",

  submitting: "Przesyłanie tłumaczenia",
  queued: "W kolejce",
  running: (from: string, to: string) => `Tłumaczenie · ${from} → ${to}`,
  stepUnits: (done: number, total: number | null) => (total ? `Przetłumaczono: ${done} / ${total}` : `Przetłumaczono: ${sentences(done)}`),
  cancel: "Anuluj tłumaczenie",
  cancelled: "Tłumaczenie anulowano",
  cancelFailed: (message: string) => `Nie udało się anulować tłumaczenia: ${message}`,
  liveNote: "Po ukończeniu automatycznie na ekranie, można cofnąć. Możesz opuścić stronę.",
  foreign: "Tłumaczenie zaczęto gdzie indziej. Po ukończeniu użyj „Umieść na ekranie” w porównaniu.",
  agentNote: "Agent tłumaczy zdanie po zdaniu i na końcu zapisuje tłumaczenie w wideo",
  agentSession: "Sesja Agenta tłumaczy. Aby zatrzymać, zatrzymaj sesję.",
  chipTip: (step: string) => `Tłumaczenie · ${step}`,

  notConfigured: (reason: string) => `Jeszcze nie można tłumaczyć · ${reason}`,
  submitFailed: "Nie udało się rozpocząć tłumaczenia",
  failed: "Tłumaczenie nie powiodło się",
  interrupted: "Tłumaczenie przerwano",
  retry: "Spróbuj ponownie",
  retrying: "Ponawianie",
  retryFailed: (message: string) => `Nie udało się ponowić: ${message}`,
  retryCharges: "Ponowienie od zatrzymanego kroku. Jeśli krok „Przetłumacz”, model wywołany ponownie, możliwa kolejna opłata.",
  retryFree: "Ponowienie od zatrzymanego kroku; gotowe tłumaczenia bez ponownego wywołania modelu.",
  dismiss: "OK",
  decide: "Rozwiąż w zadaniach w tle",
  emptyTitle: "Tłumaczenie nie ma zdań do umieszczenia na ekranie",
  empty: "Wszystkie zdania tłumaczenia nieaktualne lub puste.",
  pendingTitle: "Tłumaczenie ukończone, jeszcze poza ekranem",
  pending: "Tłumaczenie zapisane w wideo. Kliknij „Umieść na ekranie” w porównaniu.",
  offTimeline: "Żaden klip nie używa materiału, napisy nie mogą trafić na ekran. Tłumaczenie zapisane; kliknij „Umieść na ekranie” w porównaniu.",
  badDocument: "Format tłumaczenia lub transkrypcji nierozpoznany, nie można podzielić na napisy.",

  applied: (language: string, count: number) => `Zastosowano · tłumaczenie na ${language} · ${subtitles(count)}`,
  appliedNote: (bilingual: boolean) => bilingual
      ? "Oryginał i tłumaczenie razem na ekranie."
      : "Na ekranie tylko tłumaczenie; oryginał zdjęty (nieusunięty – można przywrócić z paska).",
  undo: "Cofnij",
  done: "Gotowe",
  undone: (language: string) => `Cofnięto · ${language} napisów zdjęto z ekranu`,
  undoneNote: "Oryginał bez zmian, tłumaczenie zostaje w wideo, możesz znów „Umieść na ekranie” z porównania.",
  undoFailed: "Nie można cofnąć: wideo zmieniło się po kroku. Cofnij w edytorze.",

  place: "Położenie na ekranie",
  placing: "Umieszczanie na ekranie",
  unnamed: "Tłumaczenie",
  placed: (language: string, count: number) => `Umieszczono ${language} tłumaczenie na ekranie · ${subtitles(count)}`,
  notPlaced: "Tłumaczenie jeszcze poza ekranem.",

  list: "Lista",
  modes: { src: "Tylko oryginał", bi: "Oryginał + tłumaczenie", trans: "Tylko tłumaczenie" },
  compareLanguage: "Tłumaczenie do porównania",
  noTranslation: "Brak tłumaczeń · najpierw użyj „Przetłumacz na…” na pasku",
  original: (language: string) => `Oryginał · ${language}`,
  translation: (language: string) => `Tłumaczenie · ${language}`,
  reading: "Wczytywanie tłumaczenia…",
  unreadable: "Formatu tłumaczenia nie można jeszcze tutaj wyświetlić.",
  speechMissing: "Transkrypcji tego tłumaczenia nie ma już w wideo.",
  stats: (count: number) => sentences(count),
  untranslated: (n: number) => `${sentences(n)} nieprzetłumaczone`,
  stale: (n: number) => pluralForm('pl', n, { one: `${n} przetłumaczone zdanie nieaktualne`, few: `${n} przetłumaczone zdania nieaktualne`, many: `${n} przetłumaczonych zdań nieaktualnych`, other: `${n} przetłumaczonego zdania nieaktualnego` }),
  gone: (n: number) => `${n} oryginalnych ${pluralForm('pl', n, { one: "zdanie", few: "zdania", many: "zdań", other: "zdania" })} usunięte`,
  allFresh: "Wszystkie tłumaczenia aktualne ✓",
  refreshHint: "Kliknij tłumaczenie, aby edytować; zmienione nie są nieaktualne. Aby tłumaczyć ponownie tylko te zdania, przekaż agentowi:",
  refreshOpen: "Odśwież nieaktualne tłumaczenia",
  refreshHintWeb: "Kliknij tłumaczenie, aby edytować; zmienione nie są nieaktualne.",
  chipStale: "Nieaktualne",
  chipUntranslated: "Nieprzetłumaczone",
  chipGone: "Oryginał usunięty",
  goneTip: "Zdania nie ma już w transkrypcji: tłumaczenie nie pojawi się na ekranie i nie może być edytowane.",
  emptyPlaceholder: "(Brak tłumaczenia · kliknij, aby wypełnić)",
  editLabel: (n: number) => `Edytuj tłumaczenie zdania ${n}`,
  editing: "Tłumaczenie",
  editHint: "Kliknij przetłumaczone zdanie, aby edytować: kliknięcie poza zapisuje, Esc odrzuca. Napisy aktualizują się.",
  editTail: "Kliknij tłumaczenie, aby edytować",
  noRows: "Tłumaczenie nie ma jeszcze zdań.",
  edited: "Zmieniono przetłumaczone zdanie",
  editFailed: (message: string) => `Nie udało się zmienić: ${message}`,
  seekTip: "Przesuń głowicę do zdania",
  cutTip: "Materiał wideo zdania wycięto",
  translateTo: (language: string) => `Przetłumacz na ${language}`,
  rewriteTranslation: "Edytuj tłumaczenie",
  unknownLanguage: "Nieznany język",
  targetLanguage: "język docelowy",
};

export const plTextNotConfigured: TextNotConfiguredMessages = {
  'no-default': "Nie wybrano jeszcze modelu generowania tekstu",
  'missing-credential': "Dostawca modelu tekstowego nie ma jeszcze klucza",
  'not-installed': "Model tekstowy jeszcze niezainstalowany",
  'signed-out': "Agent jeszcze niezalogowany",
  outdated: "Wersja agenta zbyt stara",
  'not-paired': "Węzeł zdalny jeszcze niesparowany",
  'not-connected': "Węzeł zdalny niepołączony",
  unsupported: "Wybrana usługa nie obsługuje generowania tekstu",
  disabled: "Usługa generowania tekstu wyłączona",
};
