import type { TextNotConfiguredMessages, TranslateMessages } from './translate-copy.ts';

import { pluralForm } from '@baocut/protocol';
const sentences = (n: number) => `${n} ${pluralForm('fr', n, { one: 'phrase', other: 'phrases' })}`;
const subtitles = (n: number) => `${n} ${pluralForm('fr', n, { one: 'sous-titre', other: 'sous-titres' })}`;

export const frTranslate: TranslateMessages = {

  title: "Traduire dans une nouvelle langue",
  back: "Retour aux sous-titres",
  target: "Langue cible",
  targetPicker: "Langue cible",
  source: "Originale",
  sourcePicker: "Transcription à traduire",
  sourceLine: (language: string, count: number | null) => (count === null ? language : `${language} · ${sentences(count)}`),
  model: "Modèle de texte",
  modelPicker: "Modèle de texte pour la traduction",
  manage: "Gérer les modèles de texte…",
  modelsLoading: "Chargement des modèles de texte…",
  noStructured: "Aucune sortie structurée · traduction impossible",
  notConfiguredTitle: "Aucun modèle de texte disponible",
  notConfiguredBody:
    "La traduction appelle un modèle de texte par lots. Dans Réglages › Modèles › Génération de texte, connectez un fournisseur (clé) et choisissez un modèle avec sortie structurée, puis revenez démarrer.",
  goModels: "Ouvrir Réglages › Modèles › Génération de texte",
  style: "Indication de style",
  stylePlaceholder: "Par exemple : oral, concis ; conserver les noms originaux",
  styleHint: "Facultatif ; 500 caractères maximum.",
  glossary: "Glossaire",
  glossaryNote:
    "Coché = activé pour cette vidéo (annulable). Les glossaires correspondant au sens de traduction sont utilisés ; chaque lot inclut seulement les termes présents dans l’original.",
  glossaryManage: "Gérer les glossaires…",
  glossaryEmpty: (target: string) => `La bibliothèque n’a aucun glossaire de traduction vers ${target} pour l’instant.`,
  glossaryLoading: "Chargement des glossaires…",
  glossaryCount: (terms: number, hits: number) => `${terms} ${pluralForm('fr', terms, { one: "entrée", other: "entrées" })} · ${hits} trouvées dans cette vidéo`,
  glossaryFailed: (message: string) => `Impossible de lire les glossaires activés de cette vidéo : ${message}`,
  glossaryReadOnly: "La vidéo est en lecture seule ; glossaires activés non modifiables.",
  glossaryLimit: (max: number) => `Au plus ${max} glossaires peuvent être activés en une étape`,
  glossaryOn: (name: string) => `« ${name} » activé pour cette vidéo`,
  glossaryOff: (name: string) => `« ${name} » activé pour cette vidéo`,
  glossaryWriteFailed: (message: string) => `Impossible de changer les glossaires activés : ${message}`,
  bilingual: "Afficher les deux langues",
  bilingualHint:
    "À la fin, original et traduction apparaissent ensemble. Sinon, seule la traduction apparaît ; original retiré de l’écran, pas supprimé.",
  cta: (language: string) => `Traduire en ${language}`,
  ctaHint: "Placement automatique à l’écran à la fin, annulable. Modèles en ligne facturés au token.",
  noSpeechTitle: "Aucune transcription à traduire",
  noSpeech:
    "La traduction suit chaque phrase d’une transcription. Transcrivez d’abord un média avec « Générer des sous-titres » dans Sous-titres ; les fichiers importés n’ont pas d’horaires de mots et ne peuvent pas être traduits directement.",
  busy: "Cette vidéo est déjà en traduction ; attendez avant une autre langue.",
  readOnly: "La vidéo est en lecture seule ; traduction impossible.",
  allTaken: "Toutes les langues courantes ont déjà une traduction.",

  submitting: "Soumission de la traduction",
  queued: "En file",
  running: (from: string, to: string) => `Traduction · ${from} → ${to}`,
  stepUnits: (done: number, total: number | null) => (total ? `Traduit : ${done} / ${total} phrases` : `Traduit : ${sentences(done)}`),
  cancel: "Annuler la traduction",
  cancelled: "Traduction annulée",
  cancelFailed: (message: string) => `Impossible d’annuler la traduction : ${message}`,
  liveNote: "Placement automatique à l’écran à la fin, annulable. Vous pouvez quitter cette page.",
  foreign: "Cette traduction n’a pas été démarrée ici. À la fin, utilisez « Placer à l’écran » dans la comparaison.",
  agentNote: "L’Agent traduit phrase par phrase et l’écrit dans la vidéo à la fin",
  agentSession: "Une session de l’Agent traduit. Pour l’arrêter, arrêtez la session.",
  chipTip: (step: string) => `Traduction · ${step}`,

  notConfigured: (reason: string) => `Traduction indisponible · ${reason}`,
  submitFailed: "Impossible de démarrer la traduction",
  failed: "Échec de traduction",
  interrupted: "Traduction interrompue",
  retry: "Réessayer",
  retrying: "Nouvelle tentative",
  retryFailed: (message: string) => `Impossible de réessayer : ${message}`,
  retryCharges: "Réessayer reprend à l’étape d’arrêt. Si c’était « Traduire », le modèle est rappelé et peut facturer à nouveau.",
  retryFree: "Réessayer reprend à l’étape d’arrêt ; les traductions terminées ne rappellent pas le modèle.",
  dismiss: "OK",
  decide: "Résoudre dans Tâches en arrière-plan",
  emptyTitle: "La traduction n’a aucune phrase à placer à l’écran",
  empty: "Toutes les phrases sont obsolètes ou vides.",
  pendingTitle: "Traduction terminée mais pas encore à l’écran",
  pending: "La traduction est enregistrée dans la vidéo. Cliquez « Placer à l’écran » dans la comparaison.",
  offTimeline:
    "Aucun clip n’utilise ce média ; sous-titres non plaçables à l’écran. Traduction enregistrée ; cliquez « Placer à l’écran » dans la comparaison.",
  badDocument: "Format de traduction ou transcription non reconnu ; découpage en sous-titres impossible.",

  applied: (language: string, count: number) => `Appliqué · traduit en ${language} · ${subtitles(count)}`,
  appliedNote: (bilingual: boolean): string =>
    bilingual
      ? "Original et traduction apparaissent ensemble à l’écran."
      : "Seule la traduction est affichée ; original retiré, pas supprimé (réaffichable depuis la bande).",
  undo: "Annuler",
  done: "Terminé",
  undone: (language: string) => `Annulé · ${language} sous-titres retirés de l’écran`,
  undoneNote: "Original inchangé, traduction conservée ; « Placer à l’écran » est réutilisable depuis la comparaison.",
  undoFailed: "Impossible d’annuler : vidéo modifiée depuis cette étape. Annulez dans l’éditeur.",

  place: "Position à l’écran",
  placing: "Placement à l’écran",
  unnamed: "Traduction",
  placed: (language: string, count: number) => `Traduction ${language} placée à l’écran · ${subtitles(count)}`,
  notPlaced: "Cette traduction n’est pas encore à l’écran.",

  list: "Liste",
  modes: { src: "Original seulement", bi: "Original + traduction", trans: "Traduction seule" },
  compareLanguage: "Traduction à comparer",
  noTranslation: "Aucune traduction · utilisez d’abord « Traduire en… » sur la bande",
  original: (language: string) => `Original · ${language}`,
  translation: (language: string) => `Traduction · ${language}`,
  reading: "Chargement de la traduction…",
  unreadable: "Le format de cette traduction n’est pas encore consultable ici.",
  speechMissing: "La transcription de cette traduction n’est plus dans la vidéo.",
  stats: (count: number) => sentences(count),
  untranslated: (n: number) => `${sentences(n)} non traduites`,
  stale: (n: number) => `${n} traduites ${pluralForm('fr', n, { one: "phrase est", other: "phrases sont" })} obsolètes`,
  gone: (n: number) => `${n} originales ${pluralForm('fr', n, { one: "phrase", other: "phrases" })} supprimées`,
  allFresh: "Toutes les traductions à jour ✓",
  refreshHint: "Cliquez une traduction pour la modifier ; les phrases modifiées ne sont plus obsolètes. Pour retraduire seulement celles-ci, confiez-les à l’Agent :",
  refreshOpen: "Actualiser les traductions obsolètes",
  refreshHintWeb: "Cliquez une traduction pour la modifier ; les phrases modifiées ne sont plus obsolètes.",
  chipStale: "Obsolète",
  chipUntranslated: "Non traduit",
  chipGone: "Original supprimé",
  goneTip: "Cette phrase n’est plus dans la transcription ; sa traduction ne sera ni affichée ni modifiable.",
  emptyPlaceholder: "(Aucune traduction · cliquez pour compléter)",
  editLabel: (n: number) => `Modifier la traduction de la phrase ${n}`,
  editing: "Traduction",
  editHint: "Cliquez une phrase traduite pour la réécrire : enregistrement en quittant le champ, Esc abandonne. Les sous-titres affichés suivent.",
  editTail: "Cliquer une traduction pour modifier",
  noRows: "Cette traduction n’a aucune phrase.",
  edited: "Phrase traduite réécrite",
  editFailed: (message: string) => `Impossible de réécrire : ${message}`,
  seekTip: "Déplacer la tête de lecture à cette phrase",
  cutTip: "Les images de cette phrase ont été coupées",
  translateTo: (language: string) => `Traduire en ${language}`,
  rewriteTranslation: "Modifier la traduction",
  unknownLanguage: "Langue inconnue",
  targetLanguage: "la langue cible",
};

export const frTextNotConfigured: TextNotConfiguredMessages = {
  'no-default': "Aucun modèle de génération de texte choisi",
  'missing-credential': "Le fournisseur du modèle de texte n’a pas encore de clé",
  'not-installed': "Le modèle de texte n’est pas installé",
  'signed-out': "L’Agent n’est pas encore connecté",
  outdated: "La version de l’Agent est trop ancienne",
  'not-paired': "Le nœud distant n’est pas jumelé",
  'not-connected': "Le nœud distant n’est pas connecté",
  unsupported: "Le service choisi ne prend pas en charge la génération de texte",
  disabled: "Le service de génération de texte est désactivé",
};
