import type { TranscriptMessages, TranscriptToolsMessages } from './transcript-copy.ts';
import { pluralForm } from '@baocut/protocol';

function secondsLabel(seconds: number): string {
  return seconds < 10 ? `${(Math.round(seconds * 10) / 10).toFixed(1).replace('.', ',')} s` : `${Math.round(seconds)} s`;
}
export const itSeconds = secondsLabel;
const words = (n: number): string => pluralForm('it', n, { one: `${n} parola`, other: `${n} parole` });
export const itTranscript: TranscriptMessages = {
  title: 'Trascrizione', modes: 'Modalità di modifica della trascrizione', modeEdit: 'Modifica testo', modeCut: 'Taglia media',
  hintEdit: 'Modifica solo il testo trascritto; video e audio restano invariati. Fai doppio clic su una parola per modificarla; ⌫ elimina solo il testo.',
  hintCut: 'Seleziona del testo e premi ⌫ per tagliarlo insieme da video, audio e sottotitoli. Le parole tagliate restano barrate e possono essere ripristinate.',
  emptyTitle: 'Nessuna trascrizione', emptyNoMedia: 'Aggiungi prima un file video o audio. Dopo la trascrizione, le parole pronunciate appaiono qui.', emptyNotPlaced: 'Il video o l’audio non è ancora sulla timeline. Posizionalo e trascrivilo: la trascrizione apparirà qui.', emptyNotTranscribed: 'I materiali sulla timeline non sono stati trascritti. Trascrivili nel pannello Sottotitoli e la trascrizione apparirà qui.', gotoSubtitle: 'Trascrivi in Sottotitoli', addMedia: 'Aggiungi media', loading: 'Caricamento della trascrizione…', noWords: 'Questa trascrizione non ha parole da mostrare.', notSpeech: 'Il formato di questa trascrizione non è riconosciuto.',
  stats: (count: number, cut: number) => cut ? `${words(count)} · ${pluralForm('it', cut, { one: `${cut} tagliata`, other: `${cut} tagliate` })}` : words(count), jump: 'Vai qui', cutWordTitle: 'Tagliata dalla timeline', partialWordTitle: 'Un taglio cade all’interno di questa parola; solo una parte resta sulla timeline',
  selected: (count: number, seconds: number | null) => `${pluralForm('it', count, { one: `${count} parola selezionata`, other: `${count} parole selezionate` })}${seconds === null ? '' : ` · ${secondsLabel(seconds)}`}`,
  cut: 'Taglia', restore: 'Ripristina', editWord: 'Modifica parola', deleteText: 'Elimina testo', clear: 'Cancella selezione · Esc', aiFind: 'Trova tagli', aiFindHint: 'Oppure lascia che l’IA trovi prima intercalari e pause',
  cutDone: (seconds: number, ranges: number) => ranges > 1 ? `Tagliati ${secondsLabel(seconds)} · ${ranges} intervalli` : `Tagliati ${secondsLabel(seconds)}`, cutNothing: 'Le parole selezionate non sono più sulla timeline; non c’è nulla da tagliare.', cutTooShort: 'La selezione è più breve di un fotogramma e non può essere tagliata.', restoreDone: (seconds: number) => `Ripristinati ${secondsLabel(seconds)}`, restoreNotRelaid: 'Alcuni tagli non hanno una giunzione corrispondente sulla timeline. Sono stati rimossi dall’elenco dei tagli, ma il contenuto non è stato riposizionato.',
  restoreRefused: { untracked: 'Questo intervallo non è stato rimosso con un taglio (ad esempio, è stato rifilato trascinando il bordo di una clip), quindi non c’è un taglio da ripristinare. Trascina il bordo della clip sulla timeline per ripristinarlo.', partial: 'Solo una parte di questo intervallo è stata rimossa con un taglio, quindi non puoi cambiarne l’intervallo. Fai clic sulla fascia del taglio per ripristinare prima quella parte.' },
  textSaved: 'Testo aggiornato · video e audio invariati', textDeleted: (count: number) => `Testo di ${words(count)} eliminato · video e audio invariati`, stale: (count: number) => pluralForm('it', count, { one: `${count} traccia di sottotitoli è stata creata da una trascrizione precedente e non è stata aggiornata.`, other: `${count} tracce di sottotitoli sono state create da una trascrizione precedente e non sono state aggiornate.` }), gotoCaptions: 'Apri Sottotitoli', undo: 'Annulla', seamLabel: (seconds: number) => `Tagliati ${secondsLabel(seconds)} · fai clic per ripristinare`, cutLabel: 'Taglia nella trascrizione', restoreLabel: 'Ripristina contenuto tagliato',
  liveCopy: 'Copia quanto trascritto finora',
  liveCopied: 'Copiato quanto trascritto finora · la trascrizione è ancora in corso',
  liveSpeaker: 'Riconoscimento',
  liveWaiting: 'Il testo riconosciuto compare qui man mano che arriva. Alcuni servizi lo restituiscono tutto alla fine.',
  liveNote: 'Il testo riconosciuto compare paragrafo per paragrafo. Potrai modificarlo al termine della trascrizione.',
  liveJump: 'Vai al più recente',
  liveSaving: 'Salvataggio della trascrizione',
};
export const itTranscriptTools: TranscriptToolsMessages = {
  toolsMenu: 'Sistema trascrizione', toolsTidy: 'Sistema tutta la trascrizione', toolsFrom: 'Parti dalla trascrizione', findTip: 'Trova e sostituisci · ⌘F', findLabel: 'Trova e sostituisci', findPlaceholder: 'Trova nella trascrizione', lockTranslation: 'Qui puoi cercare nelle traduzioni, ma non modificarle: il pannello Trascrizione modifica solo l’originale', lockLoading: 'Una versione più recente di questa trascrizione è ancora in caricamento; sostituisci quando termina', replaceLabel: 'Sostituisci testo della trascrizione', replaceDone: (count: number) => `${pluralForm('it', count, { one: `${count} corrispondenza sostituita`, other: `${count} corrispondenze sostituite` })} · video e audio invariati`, replaceNothing: 'Nessuna corrispondenza da cambiare',
  copyMenu: 'Copia trascrizione', copyAllHead: (lang: string) => `Copia tutto · ${lang}`, copyText: 'Copia testo', copySpeaker: 'Con parlanti', copyTimed: 'Con codici temporali e parlanti', copyScopeHead: (scope: string) => `Copia ${scope}`, copied: (scope: string, receipt: string) => `Copiato: ${scope} · ${receipt}`, copyFailed: 'Copia non riuscita · il browser ha negato l’accesso agli appunti', copyEmpty: 'Nulla da copiare', scopeAll: 'tutto', scopePara: 'questo paragrafo', scopeChapter: (title: string) => `«${title}»`, scopeSelection: 'testo selezionato', copySelection: 'Copia', copySelectionTip: 'Copia testo selezionato · ⌘C',
  langLabel: 'Lingua della trascrizione', langSource: 'Originale', langTranslation: 'Traduzione', langBoth: (source: string, translation: string) => `${source} + ${translation}`, showBoth: 'Mostra anche l’originale', showBothNeedsTranslation: 'Scegli prima una traduzione', showBothHint: 'Affiancati', noTranslation: 'Nessuna traduzione', noTranslationHint: 'Traduci dal pannello Sottotitoli con «+ Traduci in…»', translationNote: 'Le traduzioni seguono la riproduzione solo per paragrafo: i tempi delle parole esistono solo nell’originale, quindi l’evidenziazione parola per parola sarebbe inventata.', translationOnly: 'Non puoi modificare o tagliare mentre visualizzi solo una traduzione; torna all’originale o alla vista affiancata per modificare.', noParagraphTranslation: 'Questo paragrafo non ha una traduzione',
  paraMenu: 'Questo paragrafo…', moveUp: 'Sposta al capitolo precedente', moveDown: 'Sposta al capitolo successivo', play: 'Riproduci paragrafo', moveHead: 'Sposta al capitolo', moveTo: (title: string) => `Sposta in «${title}»`, moveWith: (count: number) => count > 1 ? `Si sposta insieme ai paragrafi vicini su quel lato, ${count} paragrafi in tutto` : 'Sposta solo questo paragrafo', noPrev: 'Non ci sono capitoli prima di questo paragrafo', noNext: 'Non ci sono capitoli dopo questo paragrafo', moveBlocked: 'Lo spostamento lascerebbe vuoto questo capitolo o supererebbe l’inizio del capitolo vicino', moveLabel: 'Sposta paragrafo nel capitolo vicino', moved: (title: string, count: number) => count > 1 ? `${count} paragrafi spostati in «${title}»` : `Spostato in «${title}»`, cutPara: 'Taglia questo paragrafo', cutParaHint: 'Taglia insieme video, audio e sottotitoli; puoi ripristinarli',
  chapterMenu: 'Questo capitolo…', renameChapter: 'Rinomina…', cutChapter: 'Taglia questo capitolo', cutChapterHint: 'Taglia insieme video, audio e sottotitoli; i capitoli successivi si spostano indietro', cutChapterLabel: 'Taglia capitolo', cutChapterRefused: { empty: 'Questo capitolo non ha durata', whole: 'Questo capitolo è l’intero video; tagliandolo non resterebbe nulla', 'no-tracks': 'Nessuna traccia sulla timeline usa i materiali trascritti, quindi non c’è nulla da tagliare' }, cutChapterDone: (title: string, seconds: number) => `«${title}» tagliato · ${secondsLabel(seconds)}`, removeMarker: 'Elimina marcatore del capitolo', removeMarkerHint: 'Elimina solo il marcatore; il contenuto resta', find: 'Trova', badRegex: 'Regex non valida', noResults: 'Nessun risultato', previous: 'Precedente', next: 'Successivo', closeFind: 'Chiudi ricerca', replaceWith: 'Sostituisci con', matchCase: 'Distingui maiuscole e minuscole', wholeWordShort: 'Parola', wholeWord: 'Corrispondenza parola intera', regex: 'Espressione regolare · il testo sostitutivo viene inserito letteralmente', replace: 'Sostituisci', replaceAll: 'Sostituisci tutto', regexError: (error: string) => `Errore nella regex: ${error}`,
};
