import type { VideoBarMessages } from './video-bar-copy.ts';

export const it: VideoBarMessages = {
  closeToSpace: "Chiudi video · torna nello Space",
  closeToHome: "Chiudi video · torna nella Home",
  untitled: "Video",
  rename: "Rinomina video",
  details: "Dettagli del video",
  actions: "Azioni sul video",
  showInSpace: "Mostra nello Space",
  revealVideoFolder: "Mostra cartella del video",
  close: "Chiudi video",
  nameLabel: "Nome",
  save: "Salva",
  openFailed: "Impossibile aprire",
  stale: "Non aggiornato · impossibile modificare al momento",
  openingAria: "Apertura in corso",
  opening: "Apertura in corso…",
  savingAria: "Salvataggio in corso",
  saving: "Salvataggio in corso…",
  agentChanged: (label: string) => `L’agente ha modificato il video: ${label}`,
  savedByAgent: (label: string) => `Salvato · Agente: ${label}`,
  saved: "Salvato",
  versionHistory: (revision: string) => `Versione ${revision}, visualizza cronologia`,
  version: (revision: string) => `Versione ${revision}`,
  historyFailed: (message: string) => `Impossibile caricare la cronologia: ${message}`,
  history: "Cronologia",
  historyLoading: "Caricamento della cronologia",
  noChanges: "Nessuna modifica ancora.",
  undoneMark: " (annullato)",
  historyMeta: (revision: string, actor: string, ago: string) => `Versione ${revision} · ${actor} · ${ago}`,
  undo: "Annulla",
  actorAgent: "Agente",
  actorSystem: "Sistema",
  actorYou: "Tu",
};
