import type { VideoBarMessages } from './video-bar-copy.ts';

export const ru: VideoBarMessages = {
  closeToSpace: "Закрыть видео · вернуться в Space",
  closeToHome: "Закрыть видео · вернуться в Home",
  untitled: "Видео",
  rename: "Переименовать видео",
  details: "Сведения о видео",
  actions: "Действия с видео",
  showInSpace: "Показать в Space",
  revealVideoFolder: "Показать папку видео",
  close: "Закрыть видео",
  nameLabel: "Название",
  save: "Сохранить",
  openFailed: "Не удалось открыть",
  stale: "Не синхронизировано · пока нельзя редактировать",
  openingAria: "Открытие",
  opening: "Открытие…",
  savingAria: "Сохранение",
  saving: "Сохранение…",
  agentChanged: (label: string) => `Агент изменил видео: ${label}`,
  savedByAgent: (label: string) => `Сохранено · агент: ${label}`,
  saved: "Сохранено",
  versionHistory: (revision: string) => `Версия ${revision}, посмотреть историю`,
  version: (revision: string) => `Версия ${revision}`,
  historyFailed: (message: string) => `Не удалось загрузить историю: ${message}`,
  history: "История",
  historyLoading: "Загрузка истории",
  noChanges: "Изменений пока нет.",
  undoneMark: " (отменено)",
  historyMeta: (revision: string, actor: string, ago: string) => `Версия ${revision} · ${actor} · ${ago}`,
  undo: "Отменить",
  actorAgent: "Агент",
  actorSystem: "Система",
  actorYou: "Вы",
};
