import type { VideoBarMessages } from './video-bar-copy.ts';

export const zhHant: VideoBarMessages = {
  closeToSpace: '關閉影片 · 回到 Space',
  closeToHome: '關閉影片 · 回到 Home',
  untitled: '影片',
  rename: '重新命名影片',
  details: '影片詳細資訊',
  actions: '影片操作',
  showInSpace: '在 Space 中顯示',
  revealVideoFolder: '顯示影片資料夾',
  close: '關閉影片',
  nameLabel: '名稱',
  save: '儲存',
  openFailed: '無法開啟',
  stale: '尚未同步 · 暫時無法修改',
  openingAria: '正在開啟',
  opening: '正在開啟…',
  savingAria: '正在儲存',
  saving: '儲存中…',
  agentChanged: (label: string) => `Agent 修改了影片：${label}`,
  savedByAgent: (label: string) => `已儲存 · Agent：${label}`,
  saved: '已儲存',
  versionHistory: (revision: string) => `版本 ${revision}，檢視歷史記錄`,
  version: (revision: string) => `版本 ${revision}`,
  historyFailed: (message: string) => `無法載入歷史記錄：${message}`,
  history: '歷史記錄',
  historyLoading: '正在載入歷史記錄',
  noChanges: '還沒有任何修改。',
  undoneMark: '（已還原）',
  historyMeta: (revision: string, actor: string, ago: string) => `版本 ${revision} · ${actor} · ${ago}`,
  undo: '還原',
  actorAgent: 'Agent',
  actorSystem: '系統',
  actorYou: '你',
};
