import type { ImagePreviewMessages } from './image-preview-copy.ts';
export const it: ImagePreviewMessages = {
  retry: "Riprova",
  openAttachment: "Apri allegato",
  copy: "Copia immagine",
  image: "Immagine",
  canvasView: "Tela",
  markup: "Annota",
  erase: "Cancella",
  removeBg: "Rimuovi sfondo",
  select: "Seleziona immagini",
  all: "Seleziona tutto",
  clear: "Cancella selezione",
  undo: "Annulla",
  redo: "Ripeti",
  brush: "Pennello",
  rectangle: "Rettangolo",
  arrow: "Freccia",
  text: "Testo",
  stroke: "Spessore tratto",
  color: "Colore",
  original: "Originale",
  frames: "Fotogrammi",
  frame: "Fotogramma",
  retime: "Scarica GIF a velocità modificata",
  sheet: "Griglia fotogrammi",
  panorama: "Panorama a 360°",
  reset: "Ripristina",
  editPrompt: "Descrivi come modificare questa immagine…",
  unavailable: "Anteprima non disponibile. Puoi scaricare l’originale.",
  pip: "Picture-in-picture",
  more: "Altre opzioni",
  copyPath: "Copia percorso",
  saveCopy: "Salva una copia…",
  fullPreview: "Espandi anteprima",
  queueSelected: "Aggiungi immagini selezionate alla bozza",

  "previous": "Immagine precedente",
  "next": "Immagine successiva",
  "zoomOut": "Riduci",
  "zoomIn": "Ingrandisci",
  "fit": "Adatta alla finestra",
  "annotations": "Annotazioni",
  "ratio": "Modifica proporzioni",
  "download": "Scarica",
  "add": "Aggiungi annotazione",
  "edit": "Modifica annotazione",
  "save": "Salva annotazione",
  "cancel": "Annulla",
  "remove": "Elimina",
  "queue": "Aggiungi alla bozza",
  "hint": "Fai clic o trascina per segnare un’area. Le annotazioni restano associate a ogni immagine.",
  "canvas": "Trascina per spostare. In modalità annotazione, premi Invio per segnare il centro.",
  "gallery": "Immagini",
  "openTab": "Apri in scheda",
  "queued": "Immagine e richiesta aggiunte alla bozza. Invia quando vuoi.",
  "changeRequest": "Modifica l’immagine seguendo queste annotazioni. Crea un nuovo file e conserva l’originale.",
  "ratioRequest": "Adatta l’immagine a queste proporzioni mantenendo soggetto e stile. Crea un nuovo file e conserva l’originale."
};
