import type { ImagePreviewMessages } from './image-preview-copy.ts';
export const zhHant: ImagePreviewMessages = {
  retry: "重試",
  openAttachment: "開啟附件",
  copy: "複製圖片",
  image: "圖片",
  canvasView: "畫布",
  markup: "標記",
  erase: "塗抹移除",
  removeBg: "移除背景",
  select: "多選圖片",
  all: "全選",
  clear: "清除選取",
  undo: "復原",
  redo: "重做",
  brush: "畫筆",
  rectangle: "矩形",
  arrow: "箭頭",
  text: "文字",
  stroke: "筆畫寬度",
  color: "顏色",
  original: "原圖",
  frames: "分幀",
  frame: "幀",
  retime: "下載變速 GIF",
  sheet: "分幀網格",
  panorama: "360° 全景",
  reset: "重設",
  editPrompt: "描述你想如何修改這張圖片…",
  unavailable: "暫時無法預覽，仍可下載原始檔案。",
  pip: "子母畫面",
  more: "更多選項",
  copyPath: "複製路徑",
  saveCopy: "另存副本…",
  fullPreview: "展開預覽",
  queueSelected: "所選圖片加入草稿",

  "previous": "上一張圖片",
  "next": "下一張圖片",
  "zoomOut": "縮小圖片",
  "zoomIn": "放大圖片",
  "fit": "符合視窗",
  "annotations": "註解",
  "ratio": "調整比例",
  "download": "下載",
  "add": "新增註解",
  "edit": "編輯註解",
  "save": "儲存註解",
  "cancel": "取消",
  "remove": "刪除",
  "queue": "加入對話草稿",
  "hint": "點選圖片標記位置，或拖曳選取區域。註解隨圖片保留。",
  "canvas": "圖片，可拖曳查看；註解模式下按 Enter 在中央新增註解。",
  "gallery": "圖片清單",
  "openTab": "在分頁開啟",
  "queued": "圖片與請求已加入草稿，傳送後再處理。",
  "changeRequest": "請依照以下註解修改圖片，建立新檔案並保留原圖。",
  "ratioRequest": "請將圖片調整為以下比例，保留主體和原有風格；建立新檔案並保留原圖。"
};
