import type { ImagePreviewMessages } from './image-preview-copy.ts';
export const de: ImagePreviewMessages = {
  retry: "Erneut versuchen",
  openAttachment: "Anhang öffnen",
  copy: "Bild kopieren",
  image: "Bild",
  canvasView: "Leinwand",
  markup: "Markieren",
  erase: "Radieren",
  removeBg: "Hintergrund entfernen",
  select: "Bilder auswählen",
  all: "Alle auswählen",
  clear: "Auswahl aufheben",
  undo: "Rückgängig",
  redo: "Wiederholen",
  brush: "Pinsel",
  rectangle: "Rechteck",
  arrow: "Pfeil",
  text: "Text",
  stroke: "Strichstärke",
  color: "Farbe",
  original: "Original",
  frames: "Einzelbilder",
  frame: "Einzelbild",
  retime: "GIF mit neuer Geschwindigkeit herunterladen",
  sheet: "Einzelbildraster",
  panorama: "360°-Panorama",
  reset: "Zurücksetzen",
  editPrompt: "Beschreibe die Bildbearbeitung…",
  unavailable: "Vorschau nicht verfügbar. Das Original kann heruntergeladen werden.",
  pip: "Bild im Bild",
  more: "Weitere Optionen",
  copyPath: "Pfad kopieren",
  saveCopy: "Kopie speichern…",
  fullPreview: "Vorschau vergrößern",
  queueSelected: "Ausgewählte Bilder zum Entwurf hinzufügen",

  "previous": "Vorheriges Bild",
  "next": "Nächstes Bild",
  "zoomOut": "Verkleinern",
  "zoomIn": "Vergrößern",
  "fit": "An Fenster anpassen",
  "annotations": "Anmerkungen",
  "ratio": "Seitenverhältnis ändern",
  "download": "Herunterladen",
  "add": "Anmerkung hinzufügen",
  "edit": "Anmerkung bearbeiten",
  "save": "Anmerkung speichern",
  "cancel": "Abbrechen",
  "remove": "Löschen",
  "queue": "Zum Entwurf hinzufügen",
  "hint": "Klicken oder ziehen Sie, um einen Bereich zu markieren. Anmerkungen bleiben beim jeweiligen Bild.",
  "canvas": "Ziehen zum Verschieben. Im Anmerkungsmodus markiert Enter die Mitte.",
  "gallery": "Bilder",
  "openTab": "In Tab öffnen",
  "queued": "Bild und Anfrage zum Entwurf hinzugefügt. Senden Sie, wenn Sie bereit sind.",
  "changeRequest": "Bearbeite das Bild anhand dieser Anmerkungen. Erstelle eine neue Datei und behalte das Original.",
  "ratioRequest": "Passe das Bild an dieses Seitenverhältnis an und behalte Motiv und Stil. Erstelle eine neue Datei und behalte das Original."
};
