import type { ImagePreviewMessages } from './image-preview-copy.ts';
export const pl: ImagePreviewMessages = {
  retry: "Spróbuj ponownie",
  openAttachment: "Otwórz załącznik",
  copy: "Kopiuj obraz",
  image: "Obraz",
  canvasView: "Płótno",
  markup: "Oznacz",
  erase: "Wymaż",
  removeBg: "Usuń tło",
  select: "Wybierz obrazy",
  all: "Zaznacz wszystko",
  clear: "Wyczyść zaznaczenie",
  undo: "Cofnij",
  redo: "Ponów",
  brush: "Pędzel",
  rectangle: "Prostokąt",
  arrow: "Strzałka",
  text: "Tekst",
  stroke: "Grubość linii",
  color: "Kolor",
  original: "Oryginał",
  frames: "Klatki",
  frame: "Klatka",
  retime: "Pobierz GIF ze zmienioną szybkością",
  sheet: "Siatka klatek",
  panorama: "Panorama 360°",
  reset: "Resetuj",
  editPrompt: "Opisz zmiany obrazu…",
  unavailable: "Podgląd niedostępny. Możesz pobrać oryginał.",
  pip: "Obraz w obrazie",
  more: "Więcej opcji",
  copyPath: "Kopiuj ścieżkę",
  saveCopy: "Zapisz kopię…",
  fullPreview: "Powiększ podgląd",
  queueSelected: "Dodaj wybrane obrazy do wersji roboczej",

  "previous": "Poprzedni obraz",
  "next": "Następny obraz",
  "zoomOut": "Pomniejsz",
  "zoomIn": "Powiększ",
  "fit": "Dopasuj do okna",
  "annotations": "Adnotacje",
  "ratio": "Zmień proporcje",
  "download": "Pobierz",
  "add": "Dodaj adnotację",
  "edit": "Edytuj adnotację",
  "save": "Zapisz adnotację",
  "cancel": "Anuluj",
  "remove": "Usuń",
  "queue": "Dodaj do szkicu",
  "hint": "Kliknij lub przeciągnij, aby zaznaczyć obszar. Adnotacje są zachowywane dla każdego obrazu.",
  "canvas": "Przeciągnij, aby przesunąć. W trybie adnotacji Enter zaznacza środek.",
  "gallery": "Obrazy",
  "openTab": "Otwórz w karcie",
  "queued": "Obraz i prośbę dodano do szkicu. Wyślij, gdy będziesz gotowy.",
  "changeRequest": "Edytuj obraz według tych adnotacji. Utwórz nowy plik i zachowaj oryginał.",
  "ratioRequest": "Dostosuj obraz do tych proporcji, zachowując temat i styl. Utwórz nowy plik i zachowaj oryginał."
};
