import type { ImagePreviewMessages } from './image-preview-copy.ts';
export const tr: ImagePreviewMessages = {
  retry: "Yeniden dene",
  openAttachment: "Eki aç",
  copy: "Görüntüyü kopyala",
  image: "Görüntü",
  canvasView: "Tuval",
  markup: "İşaretle",
  erase: "Sil",
  removeBg: "Arka planı kaldır",
  select: "Görüntüleri seç",
  all: "Tümünü seç",
  clear: "Seçimi temizle",
  undo: "Geri al",
  redo: "Yinele",
  brush: "Fırça",
  rectangle: "Dikdörtgen",
  arrow: "Ok",
  text: "Metin",
  stroke: "Çizgi kalınlığı",
  color: "Renk",
  original: "Orijinal",
  frames: "Kareler",
  frame: "Kare",
  retime: "Hızı değiştirilmiş GIF’i indir",
  sheet: "Kare ızgarası",
  panorama: "360° panorama",
  reset: "Sıfırla",
  editPrompt: "Görüntünün nasıl düzenleneceğini açıklayın…",
  unavailable: "Önizleme kullanılamıyor. Orijinali indirebilirsiniz.",
  pip: "Resim içinde resim",
  more: "Diğer seçenekler",
  copyPath: "Yolu kopyala",
  saveCopy: "Bir kopya kaydet…",
  fullPreview: "Önizlemeyi genişlet",
  queueSelected: "Seçili görüntüleri taslağa ekle",

  "previous": "Önceki resim",
  "next": "Sonraki resim",
  "zoomOut": "Uzaklaştır",
  "zoomIn": "Yakınlaştır",
  "fit": "Pencereye sığdır",
  "annotations": "Notlar",
  "ratio": "En boy oranını değiştir",
  "download": "İndir",
  "add": "Not ekle",
  "edit": "Notu düzenle",
  "save": "Notu kaydet",
  "cancel": "İptal",
  "remove": "Sil",
  "queue": "Taslağa ekle",
  "hint": "Bölgeyi işaretlemek için tıklayın veya sürükleyin. Notlar her resim için saklanır.",
  "canvas": "Kaydırmak için sürükleyin. Not modunda Enter ile merkezi işaretleyin.",
  "gallery": "Resimler",
  "openTab": "Sekmede aç",
  "queued": "Resim ve istek taslağa eklendi. Hazır olduğunuzda gönderin.",
  "changeRequest": "Resmi bu notlara göre düzenle. Yeni bir dosya oluştur ve orijinali koru.",
  "ratioRequest": "Konuyu ve stili koruyarak resmi bu orana ayarla. Yeni bir dosya oluştur ve orijinali koru."
};
