import type { ImagePreviewMessages } from './image-preview-copy.ts';
export const ja: ImagePreviewMessages = {
  retry: "再試行",
  openAttachment: "添付ファイルを開く",
  copy: "画像をコピー",
  image: "画像",
  canvasView: "キャンバス",
  markup: "マークアップ",
  erase: "消去",
  removeBg: "背景を削除",
  select: "画像を選択",
  all: "すべて選択",
  clear: "選択を解除",
  undo: "元に戻す",
  redo: "やり直す",
  brush: "ブラシ",
  rectangle: "長方形",
  arrow: "矢印",
  text: "テキスト",
  stroke: "線の太さ",
  color: "色",
  original: "元の画像",
  frames: "フレーム",
  frame: "フレーム",
  retime: "速度変更した GIF をダウンロード",
  sheet: "フレーム一覧",
  panorama: "360° パノラマ",
  reset: "リセット",
  editPrompt: "画像の編集内容を入力…",
  unavailable: "プレビューできません。元のファイルはダウンロードできます。",
  pip: "ピクチャーインピクチャー",
  more: "その他のオプション",
  copyPath: "パスをコピー",
  saveCopy: "コピーを保存…",
  fullPreview: "プレビューを拡大",
  queueSelected: "選択した画像を下書きに追加",

  "previous": "前の画像",
  "next": "次の画像",
  "zoomOut": "縮小",
  "zoomIn": "拡大",
  "fit": "ウィンドウに合わせる",
  "annotations": "注釈",
  "ratio": "縦横比を変更",
  "download": "ダウンロード",
  "add": "注釈を追加",
  "edit": "注釈を編集",
  "save": "注釈を保存",
  "cancel": "キャンセル",
  "remove": "削除",
  "queue": "会話の下書きに追加",
  "hint": "クリックまたはドラッグで範囲を指定します。注釈は画像ごとに保持されます。",
  "canvas": "ドラッグで画像を移動。注釈モードでは Enter で中央を指定。",
  "gallery": "画像一覧",
  "openTab": "タブで開く",
  "queued": "画像と依頼を下書きに追加しました。準備ができたら送信してください。",
  "changeRequest": "以下の注釈に従って画像を編集し、元の画像を残して新しいファイルを作成してください。",
  "ratioRequest": "被写体とスタイルを維持して次の縦横比に変更し、元の画像を残して新しいファイルを作成してください。"
};
