import type { PanelMessages } from './panel-copy.ts';
export const de: PanelMessages = {
  preview: "Vorschau",
  source: "Quelltext",
  table: "Tabelle",
  formatted: "Formatiert",
  openDefault: "In Standard-App öffnen",
  previousPage: "Vorherige Seite",
  nextPage: "Nächste Seite",
  fitWidth: "An Breite anpassen",
  zoom: "Zoom",
  csvInvalid: "CSV-Anführungszeichen nicht geschlossen. Quelltext ansehen.",
  jsonInvalid: "Ungültiges JSON. Original wird angezeigt.",
  column: (index: number) => `Spalte ${index}`,
  find: "Auf Seite suchen",
  previousMatch: "Vorheriger Treffer",
  nextMatch: "Nächster Treffer",
  closeFind: "Suche schließen",
  device: "Gerätevorschau",
  phone: "Telefon",
  tablet: "Tablet",
  laptop: "Laptop",
  custom: "Benutzerdefiniert",
  width: "Breite",
  height: "Höhe",
  rotate: "Drehen",
  closeDevice: "Gerätevorschau schließen",
  forceReload: "Ohne Cache neu laden",
  duplicate: "In neuem Tab öffnen",
  popupBlocked: "Popup blockiert.",
  downloadExternal: "Download im Browser geöffnet.",
  permissionBlocked: "Website-Berechtigung verweigert.",
  dismiss: "Schließen",
};
