import type { PanelMessages } from './panel-copy.ts';
export const tr: PanelMessages = {
  preview: "Önizleme",
  source: "Kaynak",
  table: "Tablo",
  formatted: "Biçimlendirilmiş",
  openDefault: "Varsayılan uygulamada aç",
  previousPage: "Önceki sayfa",
  nextPage: "Sonraki sayfa",
  fitWidth: "Genişliğe sığdır",
  zoom: "Yakınlaştırma",
  csvInvalid: "CSV tırnak işareti kapanmamış. Kaynağı görüntüleyin.",
  jsonInvalid: "Geçersiz JSON. Kaynak gösteriliyor.",
  column: (index: number) => `Sütun ${index}`,
  find: "Sayfada bul",
  previousMatch: "Önceki eşleşme",
  nextMatch: "Sonraki eşleşme",
  closeFind: "Aramayı kapat",
  device: "Cihaz önizlemesi",
  phone: "Telefon",
  tablet: "Tablet",
  laptop: "Dizüstü",
  custom: "Özel",
  width: "Genişlik",
  height: "Yükseklik",
  rotate: "Döndür",
  closeDevice: "Cihaz önizlemesini kapat",
  forceReload: "Önbelleksiz yeniden yükle",
  duplicate: "Yeni sekmede aç",
  popupBlocked: "Açılır pencere engellendi.",
  downloadExternal: "İndirme tarayıcıda açıldı.",
  permissionBlocked: "Site izni reddedildi.",
  dismiss: "Kapat",
};
