import type { PanelMessages } from './panel-copy.ts';
export const ru: PanelMessages = {
  preview: "Предпросмотр",
  source: "Исходный текст",
  table: "Таблица",
  formatted: "Форматирование",
  openDefault: "Открыть приложением по умолчанию",
  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  fitWidth: "По ширине",
  zoom: "Масштаб",
  csvInvalid: "Кавычка CSV не закрыта. Откройте исходный текст.",
  jsonInvalid: "Некорректный JSON. Показан исходный текст.",
  column: (index: number) => `Столбец ${index}`,
  find: "Найти на странице",
  previousMatch: "Предыдущее совпадение",
  nextMatch: "Следующее совпадение",
  closeFind: "Закрыть поиск",
  device: "Предпросмотр устройства",
  phone: "Телефон",
  tablet: "Планшет",
  laptop: "Ноутбук",
  custom: "Свой размер",
  width: "Ширина",
  height: "Высота",
  rotate: "Повернуть",
  closeDevice: "Закрыть предпросмотр устройства",
  forceReload: "Перезагрузить без кеша",
  duplicate: "Открыть в новой вкладке",
  popupBlocked: "Всплывающее окно заблокировано.",
  downloadExternal: "Загрузка открыта в браузере.",
  permissionBlocked: "В разрешении сайта отказано.",
  dismiss: "Закрыть",
};
