import type { PanelMessages } from './panel-copy.ts';
export const fr: PanelMessages = {
  preview: "Aperçu",
  source: "Source",
  table: "Tableau",
  formatted: "Mis en forme",
  openDefault: "Ouvrir dans l’application par défaut",
  previousPage: "Page précédente",
  nextPage: "Page suivante",
  fitWidth: "Ajuster à la largeur",
  zoom: "Zoom",
  csvInvalid: "Guillemet CSV non fermé. Consultez la source.",
  jsonInvalid: "JSON non valide. Affichage du texte original.",
  column: (index: number) => `Colonne ${index}`,
  find: "Rechercher dans la page",
  previousMatch: "Résultat précédent",
  nextMatch: "Résultat suivant",
  closeFind: "Fermer la recherche",
  device: "Aperçu de l’appareil",
  phone: "Téléphone",
  tablet: "Tablette",
  laptop: "Portable",
  custom: "Personnalisé",
  width: "Largeur",
  height: "Hauteur",
  rotate: "Pivoter",
  closeDevice: "Fermer l’aperçu de l’appareil",
  forceReload: "Recharger sans cache",
  duplicate: "Ouvrir dans un nouvel onglet",
  popupBlocked: "Fenêtre contextuelle bloquée.",
  downloadExternal: "Téléchargement ouvert dans le navigateur.",
  permissionBlocked: "Autorisation du site refusée.",
  dismiss: "Fermer",
};
