import type { PanelMessages } from './panel-copy.ts';
export const zhHans: PanelMessages = {
  preview: "预览",
  source: "源码",
  table: "表格",
  formatted: "格式化",
  openDefault: "用默认应用打开",
  previousPage: "上一页",
  nextPage: "下一页",
  fitWidth: "适合宽度",
  zoom: "缩放",
  csvInvalid: "CSV 引号没有闭合，请查看源码。",
  jsonInvalid: "JSON 格式有误，已显示原文。",
  column: (index: number) => `列 ${index}`,
  find: "在网页中查找",
  previousMatch: "上一个匹配",
  nextMatch: "下一个匹配",
  closeFind: "关闭查找",
  device: "设备预览",
  phone: "手机",
  tablet: "平板",
  laptop: "笔记本",
  custom: "自定义",
  width: "宽度",
  height: "高度",
  rotate: "旋转",
  closeDevice: "关闭设备预览",
  forceReload: "忽略缓存重新加载",
  duplicate: "在新标签页打开",
  popupBlocked: "已拦截弹窗。",
  downloadExternal: "下载已交给系统浏览器。",
  permissionBlocked: "已拒绝网站权限请求。",
  dismiss: "关闭提示",
};
