import type { PanelMessages } from './panel-copy.ts';
export const ko: PanelMessages = {
  preview: "미리 보기",
  source: "소스",
  table: "표",
  formatted: "서식 적용",
  openDefault: "기본 앱으로 열기",
  previousPage: "이전 페이지",
  nextPage: "다음 페이지",
  fitWidth: "너비에 맞춤",
  zoom: "확대/축소",
  csvInvalid: "CSV 따옴표가 닫히지 않았습니다. 소스를 확인하세요.",
  jsonInvalid: "잘못된 JSON입니다. 원문을 표시합니다.",
  column: (index: number) => `열 ${index}`,
  find: "페이지에서 찾기",
  previousMatch: "이전 일치",
  nextMatch: "다음 일치",
  closeFind: "찾기 닫기",
  device: "기기 미리 보기",
  phone: "휴대폰",
  tablet: "태블릿",
  laptop: "노트북",
  custom: "사용자 지정",
  width: "너비",
  height: "높이",
  rotate: "회전",
  closeDevice: "기기 미리 보기 닫기",
  forceReload: "캐시 없이 새로고침",
  duplicate: "새 탭에서 열기",
  popupBlocked: "팝업을 차단했습니다.",
  downloadExternal: "브라우저에서 다운로드를 열었습니다.",
  permissionBlocked: "사이트 권한 요청을 거부했습니다.",
  dismiss: "닫기",
};
