import type { PanelMessages } from './panel-copy.ts';
export const it: PanelMessages = {
  preview: "Anteprima",
  source: "Sorgente",
  table: "Tabella",
  formatted: "Formattato",
  openDefault: "Apri nell’app predefinita",
  previousPage: "Pagina precedente",
  nextPage: "Pagina successiva",
  fitWidth: "Adatta alla larghezza",
  zoom: "Zoom",
  csvInvalid: "Virgolette CSV non chiuse. Visualizza il sorgente.",
  jsonInvalid: "JSON non valido. Viene mostrato l’originale.",
  column: (index: number) => `Colonna ${index}`,
  find: "Trova nella pagina",
  previousMatch: "Corrispondenza precedente",
  nextMatch: "Corrispondenza successiva",
  closeFind: "Chiudi ricerca",
  device: "Anteprima dispositivo",
  phone: "Telefono",
  tablet: "Tablet",
  laptop: "Portatile",
  custom: "Personalizzato",
  width: "Larghezza",
  height: "Altezza",
  rotate: "Ruota",
  closeDevice: "Chiudi anteprima dispositivo",
  forceReload: "Ricarica senza cache",
  duplicate: "Apri in nuova scheda",
  popupBlocked: "Popup bloccato.",
  downloadExternal: "Download aperto nel browser.",
  permissionBlocked: "Autorizzazione del sito negata.",
  dismiss: "Chiudi",
};
