import type { PanelMessages } from './panel-copy.ts';
export const vi: PanelMessages = {
  preview: "Xem trước",
  source: "Mã nguồn",
  table: "Bảng",
  formatted: "Định dạng",
  openDefault: "Mở bằng ứng dụng mặc định",
  previousPage: "Trang trước",
  nextPage: "Trang sau",
  fitWidth: "Vừa chiều rộng",
  zoom: "Thu phóng",
  csvInvalid: "Dấu ngoặc kép CSV chưa đóng. Hãy xem mã nguồn.",
  jsonInvalid: "JSON không hợp lệ. Đang hiển thị bản gốc.",
  column: (index: number) => `Cột ${index}`,
  find: "Tìm trên trang",
  previousMatch: "Kết quả trước",
  nextMatch: "Kết quả tiếp theo",
  closeFind: "Đóng tìm kiếm",
  device: "Xem trước thiết bị",
  phone: "Điện thoại",
  tablet: "Máy tính bảng",
  laptop: "Máy tính xách tay",
  custom: "Tùy chỉnh",
  width: "Chiều rộng",
  height: "Chiều cao",
  rotate: "Xoay",
  closeDevice: "Đóng xem trước thiết bị",
  forceReload: "Tải lại không dùng bộ nhớ đệm",
  duplicate: "Mở trong thẻ mới",
  popupBlocked: "Đã chặn cửa sổ bật lên.",
  downloadExternal: "Đã mở tải xuống trong trình duyệt.",
  permissionBlocked: "Đã từ chối quyền của trang.",
  dismiss: "Đóng",
};
