import { pluralForm } from '@baocut/protocol';
import type { ConversationPlace, ShellMessages } from './shell-copy.ts';

const where = (place: ConversationPlace) => (place === 'project' ? 'w projekcie' : 'w folderze roboczym');

export const pl: ShellMessages = {
  list: (items) => items.join(", "),
  separator: ", ",
  common: {
    cancel: "Anuluj",
    save: "Zapisz",
    rename: "Zmień nazwę",
    renameEllipsis: "Zmień nazwę…",
    name: "Nazwa",
    pin: "Kotwica",
    unpin: "Odepnij",
    newSession: "Nowa sesja",
    newSessionInProject: "Nowa sesja w tym projekcie",
    working: "Przetwarzanie",
    loading: "Wczytywanie",
    loadingEllipsis: "Wczytywanie…",
    tools: "Narzędzia",
    services: "Usługi",
    tasks: "Zadania w tle",
    settings: "Ustawienia",
    back: "Wstecz",
    forward: "Naprzód",
  },
  conversationHeader: {
    running: "Przetwarzanie",
    waiting: "Oczekiwanie na zatwierdzenie",
    actions: "Działania sesji",
    viewInSpace: (name) => `Zobacz „${name}” w Space`,
    revealProject: "Pokaż folder projektu",
    revealWorkdir: "Pokaż folder roboczy",
    deleteSession: "Usuń sesję",
    deleteSessionEllipsis: "Usuń sesję…",
    deleteTitle: "Usunąć tę sesję?",
    deleteConfirm: "Usuń",
    deleteBody: "Historia sesji zostanie usunięta z BaoCut, trwające zadanie najpierw zatrzymane. Pliki projektu bez zmian.",
    deleteFailed: (message) => `Nie udało się usunąć: ${message}`,
    renameTitle: "Zmień nazwę sesji",
    videosIn: (place) => (place === 'project' ? "Wideo projektu" : "Wideo folderu roboczego"),
    noVideosIn: (place) => (place === 'project' ? "Projekt nie ma jeszcze wideo" : "Folder roboczy nie ma jeszcze wideo"),
    mediaIn: (place) => place === 'project' ? "Wideo i audio projektu" : "Wideo i audio folderu roboczego",
    noMediaIn: (place) => place === 'project' ? "Projekt nie ma jeszcze wideo ani audio" : "Folder roboczy nie ma jeszcze wideo ani audio",
    scanning: "Skanowanie…",
    none: "Żadne",
    newVideoFailed: (message) => `Nie udało się utworzyć wideo: ${message}`,
    openVideo: "Otwórz wideo",
    newVideo: "Nowe wideo",
    playMedia: "Odtwórz wideo lub audio",
  },
  sidebar: {
    openFolderFailed: (message) => `Nie udało się otworzyć folderu: ${message}`,
    archived: (title) => `Zarchiwizowano „${title}”`,
    undo: "Cofnij",
    sessions: "Sesje",
    projectsAndSessions: "Projekty i sesje",
    pinned: "Przypięte",
    projects: "Projekty",
    recent: "Najnowsze",
    newOrOpenProject: "Utwórz lub otwórz projekt",
    newProjectEllipsis: "Nowy projekt…",
    openFolderEllipsis: "Otwórz istniejący folder…",
    noSessions: "Nie ma jeszcze sesji.",
    noProjects: "Nie ma jeszcze projektów. Utwórz lub otwórz folder; agent pracuje w nim.",
    newProjectTitle: "Nowy projekt",
    projectName: "Nazwa projektu",
    untitledProject: "Projekt bez tytułu",
    newProjectHint: (dir) => `Folder o tej samej nazwie powstanie w ${dir}.`,
    create: "Utwórz",
    projectCreated: (name) => `Utworzono projekt „${name}”`,
    renameProjectTitle: "Zmień nazwę projektu",
    renameProjectHint: "Zmienia tylko nazwę w BaoCut, nazwa folderu bez zmian.",
    toggleSection: (collapsed, label) => `${collapsed ? "Rozwiń" : "Zwiń"} ${label}`,
    organizeLabel: "Organizuj projekty i sesje",
    sidebarSettings: "Ustawienia paska bocznego",
    organize: "Organizuj pasek boczny",
    byProject: "Grupuj według projektu",
    flat: "Na jednej liście",
    sortSessions: "Sortuj sesje",
    byRecent: "Ostatnia aktywność",
    byName: "Nazwa",
  },
  sidebarRows: {
    noProject: "Poza projektem",
    rowActions: (title) => `Działania dla „${title}”`,
    togglePin: (pinned, title) => `${pinned ? "Odepnij" : "Kotwica"} „${title}”`,
    archiveNamed: (title) => `Archiwizuj „${title}”`,
    archive: "Archiwizuj sesję",
    projectActions: (name) => `Działania projektu „${name}”`,
    showInSpace: "Pokaż w Space",
    newHere: "Nowa sesja tutaj",
  },
  settingsPage: {
    general: "Ogólne",
    models: "Modele",
    nav: "Nawigacja ustawień",
    sections: "Sekcje ustawień",
    shortcutNewSession: "Nowa sesja",
    shortcutTasks: "Zadania w tle",
    shortcutSettings: "Ustawienia",
    shortcutSidebar: "Pokaż lub ukryj pasek boczny",
    shortcutBack: "Wstecz",
    shortcutForward: "Naprzód",
    app: "Aplikacja",
    privacyTitle: "Dane pozostają na komputerze",
    privacyHint: "Sesje, lista projektów i oznaczenia Space w folderze danych; pliki projektów w swoich folderach, BaoCut nie wysyła ich. Dostęp online agenta zależy od silnika.",
    dataDir: "Folder danych",
    projectsDir: "Nowe projekty trafiają do",
    logsDir: "Folder dzienników",
    webCleared: "Dane internetowe wyczyszczone",
    webClearFailed: (message) => `Nie udało się wyczyścić danych internetowych: ${message}`,
    webData: "Dane internetowe",
    webDataHint: "Cookie, logowania i pamięć podręczna stron obszaru pracy. Po wyczyszczeniu trzeba zalogować ponownie.",
    webDataNone: "Środowisko nie ma kart internetowych.",
    clear: "Wyczyść",
    runtimeHint: "Przy błędach pliki dzienników pomogą znaleźć przyczynę.",
    version: "Wersja",
    appVersion: (version, build) => `Aplikacja ${version}${build > 0 ? ` (Build ${build})` : ""}`,
    uiVersion: (version, protocol) => `Interfejs ${version} (protokół ${protocol})`,
    runtimeVersion: (version, protocol) => `${version} (protokół ${protocol})`,
    versionNote: "Przy niezgodnych wersjach protokołu interfejsu i Runtime pojawi się prośba aktualizacji.",
  },
  conversationView: {
    missing: "Sesja nie istnieje lub usunięta.",
    loadingSession: "Wczytywanie sesji",
    switchFailed: (message) => `Nie udało się przełączyć: ${message}`,
    accessModeFailed: (message) => `Nie udało się zmienić trybu dostępu: ${message}`,
    placeholder: "Kontynuuj lub spróbuj innego kierunku",
    removeFailed: (message) => `Nie udało się usunąć: ${message}`,
    stopFailed: (message) => `Nie udało się zatrzymać: ${message}`,
  },
  composer: {
    disconnected: "Brak połączenia z Runtime",
    driverUnavailable: (name, detail) => `${name} niedostępny: ${detail}`,
    stopping: "Zatrzymywanie",
    stop: "Zatrzymaj",
    send: "Wyślij",
    dropEditorState: "Nie dołączaj stanu edytora do wiadomości",
    spaceEntries: "Elementy Space w wiadomości",
    dropSpaceEntries: "Nie dołączaj tych elementów Space do wiadomości",
    message: "Wiadomość do agenta",
  },
  rail: {
    running: (label, count) => `${label}, ${count} w trakcie lub w kolejce`,
    nav: "Główna nawigacja",
    primary: "Główne sekcje",
    secondary: "Usługi i zadania w tle",
  },
  utilitySidebar: {
    overviewTasks: "Wszystkie zadania",
    overviewTools: "Wszystkie narzędzia",
    overviewServices: "Przegląd usług",
    noteTasks: "Zadania działają w tle; przełączaj strony w dowolnej chwili.",
    noteTools: "Używaj narzędzi osobno; przenoś wyniki do wideo lub sesji.",
    noteServices: "Zarządzaj połączeniami komputera dla innych aplikacji i urządzeń.",
    nav: (title) => `${title} – nawigacja`,
    localServices: "Usługi lokalne",
  },
  titleBar: {
    backTip: "Wstecz ⌘[",
    forwardTip: "Dalej ⌘]",
    openTab: 'Nowa karta',
    enterSplit: 'Widok podzielony',
    hideTabs: 'Ukryj karty',
    showTabs: 'Pokaż karty',
    openTabsCount: (n: number) => `${n} ${pluralForm('pl', n, { one: 'otwarta karta', few: 'otwarte karty', many: 'otwartych kart', other: 'otwartej karty' })}`,
    openTabs: 'Otwarte karty',
    openInFull: (name: string) => `Otwórz „${name}” w pełnym widoku`,
    enterFull: 'Pełny widok',
    exitFull: 'Zamknij pełny widok',
    summary: 'Podsumowanie',
    summaryOutputs: (n: number) => `Wyniki · ${n}`,
    summaryEmpty: 'Ta sesja nie ma jeszcze wyników.',
  },
  connectionBanner: {
    incompatible: (reason) => `Protokoły interfejsu i Runtime niezgodne: ${reason}`,
    closed: "Połączenie zamknięte",
    lost: (reason, retrying) => `${reason}.${retrying ? " Łączenie ponowne…" : ""}`,
    reconnectingEllipsis: "Łączenie ponowne…",
    title: "Brak połączenia z Runtime BaoCut",
    reconnecting: "Łączenie ponowne",
  },
  videoInfo: {
    title: "Szczegóły wideo",
    name: "Nazwa",
    summary: "Podsumowanie",
    notes: "Notatki",
    notSaved: "Nie można jeszcze zapisać",
    copyAll: "Kopiuj całość",
    done: "Gotowe",
    copied: "Szczegóły wideo skopiowane",
    copyFailed: "Nie udało się skopiować. Zaznacz tekst i skopiuj ręcznie.",
    renameInEditor: "Otwórz wideo, aby zmienić nazwę",
    renameFailed: (message) => `Nie udało się zmienić nazwy: ${message}`,
  },
  filePreview: {
    tooLarge: "Plik zbyt duży do pełnego wyświetlenia",
    loading: "Wczytywanie podglądu",
    unsupported: "BaoCut nie pokazuje jeszcze tego typu pliku. Pokaż w folderze i otwórz inną aplikacją.",
    failed: (message) => `Nie udało się wczytać podglądu: ${message}`,
  },
  accessPicker: {
    current: (label) => `Tryb dostępu: ${label}`,
    label: "Tryb dostępu",
  },
  agentPicker: {
    current: (label) => `Agent kodujący i model: ${label}`,
    label: "Agent kodujący i model",
    models: (name) => `${name} modeli`,
  },
  nameDialog: {
    failed: (action, message) => `Nie udało się ${action.toLowerCase()}: ${message}`,
  },
  editorReference: {
    label: (videoName, selected) => `„${videoName}”${selected ? ` · ${selected} ${pluralForm('pl', selected, { one: "klip", few: "klipy", many: "klipów", other: "klipu" })} wybrano` : ""}`,
    description: "Wysyła obecną wersję wideo, wybrane klipy i pozycję głowicy z wiadomością",
  },
  voicePicker: { placeholder: "Wybierz głos" },
  pageSidebar: { resize: "Zmień rozmiar paska bocznego", pin: 'Przypnij pasek boczny' },
  filePane: { label: (name) => `Plik: ${name}` },
};
