import type { ConversationPlace, ShellMessages } from './shell-copy.ts';

const where = (place: ConversationPlace) => (place === 'project' ? 'プロジェクト内' : '作業フォルダ内');

export const ja: ShellMessages = {
  list: (items) => items.join('、'),
  separator: '、',
  common: {
    cancel: 'キャンセル',
    save: '保存',
    rename: '名前を変更',
    renameEllipsis: '名前を変更…',
    name: '名前',
    pin: 'ピン留め',
    unpin: 'ピン留めを外す',
    newSession: '新しいセッション',
    newSessionInProject: 'このプロジェクトで新しいセッション',
    working: '処理中',
    loading: '読み込み中',
    loadingEllipsis: '読み込み中…',
    tools: 'ツール',
    services: 'サービス',
    tasks: 'バックグラウンドタスク',
    settings: '設定',
    back: '戻る',
    forward: '進む',
  },
  conversationHeader: {
    running: '処理中',
    waiting: '承認待ち',
    actions: 'セッションの操作',
    viewInSpace: (name) => `「${name}」を Space で表示`,
    revealProject: 'プロジェクトフォルダを表示',
    revealWorkdir: '作業フォルダを表示',
    deleteSession: 'セッションを削除',
    deleteSessionEllipsis: 'セッションを削除…',
    deleteTitle: 'このセッションを削除しますか？',
    deleteConfirm: '削除',
    deleteBody: 'セッションの履歴は BaoCut から削除され、実行中のタスクは先に停止されます。プロジェクトフォルダ内のファイルには影響しません。',
    deleteFailed: (message) => `削除できませんでした：${message}`,
    renameTitle: 'セッションの名前を変更',
    videosIn: (place) => `${where(place)}の動画`,
    noVideosIn: (place) => `${where(place)}にはまだ動画がありません`,
    mediaIn: (place) => `${where(place)}の動画と音声`,
    noMediaIn: (place) => `${where(place)}にはまだ動画も音声もありません`,
    scanning: 'スキャン中…',
    none: 'なし',
    newVideoFailed: (message) => `動画を作成できませんでした：${message}`,
    openVideo: '動画を開く',
    newVideo: '新しい動画',
    playMedia: '動画または音声を再生',
  },
  sidebar: {
    openFolderFailed: (message) => `フォルダを開けませんでした：${message}`,
    archived: (title) => `「${title}」をアーカイブしました`,
    undo: '取り消す',
    sessions: 'セッション',
    projectsAndSessions: 'プロジェクトとセッション',
    pinned: 'ピン留め',
    projects: 'プロジェクト',
    recent: '最近',
    newOrOpenProject: 'プロジェクトを作成または開く',
    newProjectEllipsis: '新規プロジェクト…',
    openFolderEllipsis: '既存のフォルダを開く…',
    noSessions: 'セッションはまだありません。',
    noProjects: 'プロジェクトはまだありません。新しく作成するか、既存のフォルダを開いてください。Agent はそこで作業します。',
    newProjectTitle: '新規プロジェクト',
    projectName: 'プロジェクト名',
    untitledProject: '無題のプロジェクト',
    newProjectHint: (dir) => `${dir} に同じ名前のフォルダが作成されます。`,
    create: '作成',
    projectCreated: (name) => `プロジェクト「${name}」を作成しました`,
    renameProjectTitle: 'プロジェクトの名前を変更',
    renameProjectHint: 'BaoCut に表示される名前だけが変わり、フォルダ名はそのままです。',
    toggleSection: (collapsed, label) => `${label} を${collapsed ? '展開する' : '折りたたむ'}`,
    organizeLabel: 'プロジェクトとセッションを整理',
    sidebarSettings: 'サイドバーの設定',
    organize: 'サイドバーを整理',
    byProject: 'プロジェクトごとにグループ化',
    flat: '1 つのリストで表示',
    sortSessions: 'セッションの並べ替え',
    byRecent: '最近のアクティビティ',
    byName: '名前',
  },
  sidebarRows: {
    noProject: 'プロジェクトに属していません',
    rowActions: (title) => `「${title}」の操作`,
    togglePin: (pinned, title) => (pinned ? `「${title}」のピン留めを外す` : `「${title}」をピン留め`),
    archiveNamed: (title) => `「${title}」をアーカイブ`,
    archive: 'セッションをアーカイブ',
    projectActions: (name) => `プロジェクト「${name}」の操作`,
    showInSpace: 'Space で表示',
    newHere: 'ここで新しいセッション',
  },
  settingsPage: {
    general: '一般',
    models: 'モデル',
    nav: '設定のナビゲーション',
    sections: '設定のセクション',
    shortcutNewSession: '新しいセッション',
    shortcutTasks: 'バックグラウンドタスク',
    shortcutSettings: '設定',
    shortcutSidebar: 'サイドバーの表示/非表示',
    shortcutBack: '戻る',
    shortcutForward: '進む',
    app: 'アプリ',
    privacyTitle: 'データはこのコンピュータに保存されます',
    privacyHint:
      'セッション、プロジェクト一覧、Space のマークはデータフォルダに保存されます。プロジェクトのファイルはそれぞれのフォルダにあり、BaoCut がアップロードすることはありません。Agent エンジンがオンラインに接続するかどうかはエンジン次第です。',
    dataDir: 'データフォルダ',
    projectsDir: '新規プロジェクトの保存先',
    logsDir: 'ログフォルダ',
    webCleared: 'Web データを消去しました',
    webClearFailed: (message) => `Web データを消去できませんでした：${message}`,
    webData: 'Web データ',
    webDataHint: 'ワークスペースで開いた Web ページが残した Cookie、サインイン情報、キャッシュです。消去すると、それらのサイトに再度サインインする必要があります。',
    webDataNone: 'この環境には Web タブがありません。',
    clear: '消去',
    runtimeHint: '問題が起きたときは、ログフォルダ内のファイルが原因の特定に役立ちます。',
    version: 'バージョン',
    appVersion: (version, build) => `アプリ ${version}${build > 0 ? `（ビルド ${build}）` : ''}`,
    uiVersion: (version, protocol) => `インターフェイス ${version}（プロトコル ${protocol}）`,
    runtimeVersion: (version, protocol) => `${version}（プロトコル ${protocol}）`,
    versionNote: 'インターフェイスと Runtime のプロトコルバージョンが一致しない場合は、更新を促すメッセージが表示されます。',
  },
  conversationView: {
    missing: 'このセッションは存在しないか、削除されています。',
    loadingSession: 'セッションを読み込み中',
    switchFailed: (message) => `切り替えられませんでした：${message}`,
    accessModeFailed: (message) => `アクセスモードを変更できませんでした：${message}`,
    placeholder: '続けて指示するか、別の方向を試してください',
    removeFailed: (message) => `削除できませんでした：${message}`,
    stopFailed: (message) => `停止できませんでした：${message}`,
  },
  composer: {
    disconnected: 'Runtime に接続されていません',
    driverUnavailable: (name, detail) => `${name} は利用できません：${detail}`,
    stopping: '停止中',
    stop: '停止',
    send: '送信',
    dropEditorState: 'このメッセージにエディタの状態を含めない',
    spaceEntries: 'このメッセージと一緒に送る Space の項目',
    dropSpaceEntries: 'このメッセージにこれらの Space の項目を含めない',
    message: 'Agent へのメッセージ',
  },
  rail: {
    running: (label, count) => `${label}、${count} 件が実行中または待機中`,
    nav: 'メインナビゲーション',
    primary: 'メインセクション',
    secondary: 'サービスとバックグラウンドタスク',
  },
  utilitySidebar: {
    overviewTasks: 'すべてのタスク',
    overviewTools: 'すべてのツール',
    overviewServices: 'サービスの概要',
    noteTasks: 'タスクはバックグラウンドで実行され続けます。いつでもページを切り替えられます。',
    noteTools: 'ツールを単独で使い、結果を動画やセッションに持ち帰れます。',
    noteServices: 'このコンピュータがほかのアプリやデバイスに提供する接続を管理します。',
    nav: (title) => `${title} のナビゲーション`,
    localServices: 'ローカルサービス',
  },
  titleBar: {
    backTip: '戻る ⌘[',
    forwardTip: '進む ⌘]',
    openTab: '新しいタブを開く',
    enterSplit: '分割表示にする',
    hideTabs: 'タブを隠す',
    showTabs: 'タブを表示',
    openTabsCount: (n: number) => `開いているタブ ${n} 個`,
    openTabs: '開いているタブ',
    openInFull: (name: string) => `「${name}」をフル表示で開く`,
    enterFull: 'フル表示にする',
    exitFull: 'フル表示を終了',
    summary: 'セッションの概要',
    summaryOutputs: (n: number) => `生成物 · ${n}`,
    summaryEmpty: 'このセッションにはまだ生成物がありません。',
  },
  connectionBanner: {
    incompatible: (reason) => `インターフェイスと Runtime のプロトコルバージョンに互換性がありません：${reason}`,
    closed: '接続が閉じられました',
    lost: (reason, retrying) => `${reason}。${retrying ? '再接続中…' : ''}`,
    reconnectingEllipsis: '再接続中…',
    title: 'BaoCut Runtime に接続されていません',
    reconnecting: '再接続中',
  },
  videoInfo: {
    title: '動画の詳細',
    name: '名前',
    summary: '概要',
    notes: 'メモ',
    notSaved: 'まだ保存できません',
    copyAll: 'すべてコピー',
    done: '完了',
    copied: '動画の詳細をコピーしました',
    copyFailed: 'コピーできませんでした。テキストを選択して手動でコピーしてください。',
    renameInEditor: '名前を変更するには動画を開いてください',
    renameFailed: (message) => `名前を変更できませんでした：${message}`,
  },
  filePreview: {
    tooLarge: 'ファイルが大きすぎるため、ここではすべてを表示できません',
    loading: 'プレビューを読み込み中',
    unsupported: 'この種類のファイルは BaoCut ではまだプレビューできません。フォルダで表示して、ほかのアプリで開いてください。',
    failed: (message) => `プレビューを読み込めませんでした：${message}`,
  },
  accessPicker: {
    current: (label) => `アクセスモード：${label}`,
    label: 'アクセスモード',
  },
  agentPicker: {
    current: (label) => `コーディング Agent とモデル：${label}`,
    label: 'コーディング Agent とモデル',
    models: (name) => `${name} のモデル`,
  },
  nameDialog: {
    failed: (action, message) => `${action}できませんでした：${message}`,
  },
  editorReference: {
    label: (videoName, selected) => `「${videoName}」${selected ? ` · ${selected} 個のクリップを選択中` : ''}`,
    description: 'この動画の現在のバージョン、選択中のクリップ、再生ヘッドの位置をメッセージと一緒に送ります',
  },
  voicePicker: { placeholder: '声を選択' },
  pageSidebar: { resize: 'サイドバーの幅を調整', pin: 'サイドバーを固定' },
  filePane: { label: (name) => `ファイル：${name}` },
};
