import type { ConversationPlace, ShellMessages } from './shell-copy.ts';

const where = (place: ConversationPlace) => (place === 'project' ? '프로젝트' : '작업 폴더');

export const ko: ShellMessages = {
  list: (items) => items.join(', '),
  separator: ', ',
  common: {
    cancel: '취소',
    save: '저장',
    rename: '이름 변경',
    renameEllipsis: '이름 변경…',
    name: '이름',
    pin: '고정',
    unpin: '고정 해제',
    newSession: '새 세션',
    newSessionInProject: '이 프로젝트에서 새 세션',
    working: '진행 중',
    loading: '불러오는 중',
    loadingEllipsis: '불러오는 중…',
    tools: '도구',
    services: '서비스',
    tasks: '백그라운드 작업',
    settings: '설정',
    back: '뒤로',
    forward: '앞으로',
  },
  conversationHeader: {
    running: '진행 중',
    waiting: '승인 대기 중',
    actions: '세션 메뉴',
    viewInSpace: (name) => `Space에서 “${name}” 보기`,
    revealProject: '프로젝트 폴더 보기',
    revealWorkdir: '작업 폴더 보기',
    deleteSession: '세션 삭제',
    deleteSessionEllipsis: '세션 삭제…',
    deleteTitle: '이 세션을 삭제할까요?',
    deleteConfirm: '삭제',
    deleteBody: '세션 기록이 BaoCut에서 삭제되며, 실행 중인 작업은 먼저 중지됩니다. 프로젝트 폴더의 파일은 영향을 받지 않습니다.',
    deleteFailed: (message) => `삭제하지 못했습니다: ${message}`,
    renameTitle: '세션 이름 변경',
    videosIn: (place) => `${where(place)}의 영상`,
    noVideosIn: (place) => `${where(place)}에 아직 영상이 없습니다`,
    mediaIn: (place) => `${where(place)}의 영상 및 오디오`,
    noMediaIn: (place) => `${where(place)}에 아직 영상이나 오디오가 없습니다`,
    scanning: '스캔 중…',
    none: '없음',
    newVideoFailed: (message) => `영상을 만들지 못했습니다: ${message}`,
    openVideo: '영상 열기',
    newVideo: '새 영상',
    playMedia: '영상 또는 오디오 재생',
  },
  sidebar: {
    openFolderFailed: (message) => `폴더를 열지 못했습니다: ${message}`,
    archived: (title) => `“${title}” 세션을 보관했습니다`,
    undo: '실행 취소',
    sessions: '세션',
    projectsAndSessions: '프로젝트 및 세션',
    pinned: '고정됨',
    projects: '프로젝트',
    recent: '최근',
    newOrOpenProject: '프로젝트 만들기 또는 열기',
    newProjectEllipsis: '새 프로젝트…',
    openFolderEllipsis: '기존 폴더 열기…',
    noSessions: '아직 세션이 없습니다.',
    noProjects: '아직 프로젝트가 없습니다. 새로 만들거나 기존 폴더를 여세요. Agent가 그 폴더에서 작업합니다.',
    newProjectTitle: '새 프로젝트',
    projectName: '프로젝트 이름',
    untitledProject: '이름 없는 프로젝트',
    newProjectHint: (dir) => `${dir}에 같은 이름의 폴더가 만들어집니다.`,
    create: '만들기',
    projectCreated: (name) => `“${name}” 프로젝트를 만들었습니다`,
    renameProjectTitle: '프로젝트 이름 변경',
    renameProjectHint: 'BaoCut에 표시되는 이름만 바뀌며 폴더 이름은 그대로입니다.',
    toggleSection: (collapsed, label) => `${label} ${collapsed ? '펼치기' : '접기'}`,
    organizeLabel: '프로젝트 및 세션 정리',
    sidebarSettings: '사이드바 설정',
    organize: '사이드바 정리',
    byProject: '프로젝트별로 묶기',
    flat: '한 목록으로 보기',
    sortSessions: '세션 정렬',
    byRecent: '최근 활동',
    byName: '이름',
  },
  sidebarRows: {
    noProject: '프로젝트에 속하지 않음',
    rowActions: (title) => `“${title}” 메뉴`,
    togglePin: (pinned, title) => `“${title}” ${pinned ? '고정 해제' : '고정'}`,
    archiveNamed: (title) => `“${title}” 보관`,
    archive: '세션 보관',
    projectActions: (name) => `“${name}” 프로젝트 메뉴`,
    showInSpace: 'Space에서 보기',
    newHere: '여기에서 새 세션',
  },
  settingsPage: {
    general: '일반',
    models: '모델',
    nav: '설정 탐색',
    sections: '설정 섹션',
    shortcutNewSession: '새 세션',
    shortcutTasks: '백그라운드 작업',
    shortcutSettings: '설정',
    shortcutSidebar: '사이드바 보기 또는 숨기기',
    shortcutBack: '뒤로',
    shortcutForward: '앞으로',
    app: '앱',
    privacyTitle: '데이터는 이 컴퓨터에 보관됩니다',
    privacyHint:
      '세션, 프로젝트 목록, Space 표시는 데이터 폴더에 저장되고, 프로젝트 파일은 각자의 폴더에 있으며 BaoCut은 이를 업로드하지 않습니다. Agent 엔진의 온라인 연결 여부는 엔진이 정합니다.',
    dataDir: '데이터 폴더',
    projectsDir: '새 프로젝트 위치',
    logsDir: '로그 폴더',
    webCleared: '웹 데이터를 지웠습니다',
    webClearFailed: (message) => `웹 데이터를 지우지 못했습니다: ${message}`,
    webData: '웹 데이터',
    webDataHint: '작업 공간에서 연 웹 페이지가 남긴 쿠키, 로그인 상태, 캐시입니다. 지우면 해당 사이트에 다시 로그인해야 합니다.',
    webDataNone: '이 환경에는 웹 탭이 없습니다.',
    clear: '지우기',
    runtimeHint: '문제가 생기면 로그 폴더의 파일이 원인을 찾는 데 도움이 됩니다.',
    version: '버전',
    appVersion: (version, build) => `앱 ${version}${build > 0 ? `(빌드 ${build})` : ''}`,
    uiVersion: (version, protocol) => `인터페이스 ${version}(프로토콜 ${protocol})`,
    runtimeVersion: (version, protocol) => `${version}(프로토콜 ${protocol})`,
    versionNote: '인터페이스와 Runtime의 프로토콜 버전이 맞지 않으면 업데이트하라는 안내가 표시됩니다.',
  },
  conversationView: {
    missing: '이 세션이 없거나 삭제되었습니다.',
    loadingSession: '세션 불러오는 중',
    switchFailed: (message) => `전환하지 못했습니다: ${message}`,
    accessModeFailed: (message) => `접근 모드를 변경하지 못했습니다: ${message}`,
    placeholder: '이어서 말하거나 다른 방향을 시도해 보세요',
    removeFailed: (message) => `제거하지 못했습니다: ${message}`,
    stopFailed: (message) => `중지하지 못했습니다: ${message}`,
  },
  composer: {
    disconnected: 'Runtime에 연결되지 않음',
    driverUnavailable: (name, detail) => `${name} 사용 불가: ${detail}`,
    stopping: '중지 중',
    stop: '중지',
    send: '보내기',
    dropEditorState: '이 메시지에 편집기 상태를 포함하지 않음',
    spaceEntries: '이 메시지와 함께 보내는 Space 항목',
    dropSpaceEntries: '이 메시지에 이 Space 항목을 포함하지 않음',
    message: 'Agent에게 보낼 메시지',
  },
  rail: {
    running: (label, count) => `${label}, ${count}개 실행 중 또는 대기 중`,
    nav: '기본 탐색',
    primary: '주요 섹션',
    secondary: '서비스 및 백그라운드 작업',
  },
  utilitySidebar: {
    overviewTasks: '모든 작업',
    overviewTools: '모든 도구',
    overviewServices: '서비스 개요',
    noteTasks: '작업은 백그라운드에서 계속 실행되므로 언제든 페이지를 전환할 수 있습니다.',
    noteTools: '도구를 단독으로 사용하고 결과를 영상이나 세션으로 가져올 수 있습니다.',
    noteServices: '이 컴퓨터가 다른 앱과 기기에 제공하는 연결을 관리합니다.',
    nav: (title) => `${title} 탐색`,
    localServices: '로컬 서비스',
  },
  titleBar: {
    backTip: '뒤로 ⌘[',
    forwardTip: '앞으로 ⌘]',
    openTab: '새 탭 열기',
    enterSplit: '분할 보기로 전환',
    hideTabs: '탭 숨기기',
    showTabs: '탭 보기',
    openTabsCount: (n: number) => `열린 탭 ${n}개`,
    openTabs: '열린 탭',
    openInFull: (name: string) => `‘${name}’ 전체 보기로 열기`,
    enterFull: '전체 보기로 전환',
    exitFull: '전체 보기 종료',
    summary: '세션 요약',
    summaryOutputs: (n: number) => `결과물 · ${n}`,
    summaryEmpty: '이 세션에는 아직 결과물이 없습니다.',
  },
  connectionBanner: {
    incompatible: (reason) => `인터페이스와 Runtime의 프로토콜 버전이 호환되지 않습니다: ${reason}`,
    closed: '연결이 닫혔습니다',
    lost: (reason, retrying) => `${reason}.${retrying ? ' 다시 연결하는 중…' : ''}`,
    reconnectingEllipsis: '다시 연결하는 중…',
    title: 'BaoCut Runtime에 연결되지 않음',
    reconnecting: '다시 연결하는 중',
  },
  videoInfo: {
    title: '영상 세부 정보',
    name: '이름',
    summary: '요약',
    notes: '메모',
    notSaved: '아직 저장할 수 없음',
    copyAll: '모두 복사',
    done: '완료',
    copied: '영상 세부 정보를 복사했습니다',
    copyFailed: '복사하지 못했습니다. 텍스트를 선택해 직접 복사하세요.',
    renameInEditor: '영상을 열어야 이름을 변경할 수 있습니다',
    renameFailed: (message) => `이름을 변경하지 못했습니다: ${message}`,
  },
  filePreview: {
    tooLarge: '파일이 너무 커서 여기에 전체를 표시할 수 없습니다',
    loading: '미리 보기 불러오는 중',
    unsupported: 'BaoCut에서는 아직 이 형식의 파일을 미리 볼 수 없습니다. 폴더에서 보기로 연 뒤 다른 앱으로 여세요.',
    failed: (message) => `미리 보기를 불러오지 못했습니다: ${message}`,
  },
  accessPicker: {
    current: (label) => `접근 모드: ${label}`,
    label: '접근 모드',
  },
  agentPicker: {
    current: (label) => `코딩 Agent 및 모델: ${label}`,
    label: '코딩 Agent 및 모델',
    models: (name) => `${name} 모델`,
  },
  nameDialog: {
    failed: (action, message) => `${action}에 실패했습니다: ${message}`,
  },
  editorReference: {
    label: (videoName, selected) => `“${videoName}”${selected ? ` · 클립 ${selected}개 선택됨` : ''}`,
    description: '이 영상의 현재 버전, 선택한 클립, 재생 헤드 위치를 메시지와 함께 보냅니다',
  },
  voicePicker: { placeholder: '목소리 선택' },
  pageSidebar: { resize: '사이드바 크기 조정', pin: '사이드바 고정' },
  filePane: { label: (name) => `파일: ${name}` },
};
