import { pluralForm } from '@baocut/protocol';
import type { ConversationPlace, ShellMessages } from './shell-copy.ts';

const where = (place: ConversationPlace) => (place === 'project' ? 'в проекте' : 'в рабочей папке');

export const ru: ShellMessages = {
  list: (items) => items.join(", "),
  separator: ", ",
  common: {
    cancel: "Отмена",
    save: "Сохранить",
    rename: "Переименовать",
    renameEllipsis: "Переименовать…",
    name: "Название",
    pin: "Привязка",
    unpin: "Открепить",
    newSession: "Новая сессия",
    newSessionInProject: "Новая сессия в этом проекте",
    working: "Выполняется",
    loading: "Загрузка",
    loadingEllipsis: "Загрузка…",
    tools: "Инструменты",
    services: "Сервисы",
    tasks: "Фоновые задачи",
    settings: "Настройки",
    back: "Назад",
    forward: "Вперед",
  },
  conversationHeader: {
    running: "Выполняется",
    waiting: "Ожидание одобрения",
    actions: "Действия с сессией",
    viewInSpace: (name) => `Показать «${name}» в Space`,
    revealProject: "Показать папку проекта",
    revealWorkdir: "Показать рабочую папку",
    deleteSession: "Удалить сессию",
    deleteSessionEllipsis: "Удалить сессию…",
    deleteTitle: "Удалить эту сессию?",
    deleteConfirm: "Удалить",
    deleteBody: "История сессии удалится из BaoCut, выполняющаяся задача сначала остановится. Файлы проекта не затронуты.",
    deleteFailed: (message) => `Не удалось удалить: ${message}`,
    renameTitle: "Переименовать сессию",
    videosIn: (place) => (place === 'project' ? "Видео проекта" : "Видео рабочей папки"),
    noVideosIn: (place) => (place === 'project' ? "В проекте ещё нет видео" : "В рабочей папке ещё нет видео"),
    mediaIn: (place) => place === 'project' ? "Видео и аудио проекта" : "Видео и аудио рабочей папки",
    noMediaIn: (place) => place === 'project' ? "В проекте ещё нет видео и аудио" : "В рабочей папке ещё нет видео и аудио",
    scanning: "Сканирование…",
    none: "Нет",
    newVideoFailed: (message) => `Не удалось создать видео: ${message}`,
    openVideo: "Открыть видео",
    newVideo: "Новое видео",
    playMedia: "Воспроизвести видео или аудио",
  },
  sidebar: {
    openFolderFailed: (message) => `Не удалось открыть папку: ${message}`,
    archived: (title) => `Архивировано «${title}»`,
    undo: "Отменить",
    sessions: "Сессии",
    projectsAndSessions: "Проекты и сессии",
    pinned: "Закреплённые",
    projects: "Проекты",
    recent: "Недавние",
    newOrOpenProject: "Создать или открыть проект",
    newProjectEllipsis: "Новый проект…",
    openFolderEllipsis: "Открыть существующую папку…",
    noSessions: "Сессий ещё нет.",
    noProjects: "Проектов ещё нет. Создайте или откройте папку; агент работает в ней.",
    newProjectTitle: "Новый проект",
    projectName: "Имя проекта",
    untitledProject: "Проект без названия",
    newProjectHint: (dir) => `Одноимённая папка создастся в ${dir}.`,
    create: "Создать",
    projectCreated: (name) => `Создан проект «${name}»`,
    renameProjectTitle: "Переименовать проект",
    renameProjectHint: "Меняет только имя в BaoCut, имя папки сохраняется.",
    toggleSection: (collapsed, label) => `${collapsed ? "Развернуть" : "Свернуть"} ${label}`,
    organizeLabel: "Организовать проекты и сессии",
    sidebarSettings: "Настройки боковой панели",
    organize: "Организовать боковую панель",
    byProject: "Группировать по проектам",
    flat: "Одним списком",
    sortSessions: "Сортировать сессии",
    byRecent: "Недавняя активность",
    byName: "Название",
  },
  sidebarRows: {
    noProject: "Вне проекта",
    rowActions: (title) => `Действия для «${title}»`,
    togglePin: (pinned, title) => `${pinned ? "Открепить" : "Привязка"} «${title}»`,
    archiveNamed: (title) => `Архивировать «${title}»`,
    archive: "Архивировать сессию",
    projectActions: (name) => `Действия с проектом «${name}»`,
    showInSpace: "Показать в Space",
    newHere: "Новая сессия здесь",
  },
  settingsPage: {
    general: "Общие",
    models: "Модели",
    nav: "Навигация настроек",
    sections: "Разделы настроек",
    shortcutNewSession: "Новая сессия",
    shortcutTasks: "Фоновые задачи",
    shortcutSettings: "Настройки",
    shortcutSidebar: "Показать или скрыть боковую панель",
    shortcutBack: "Назад",
    shortcutForward: "Вперед",
    app: "Приложение",
    privacyTitle: "Ваши данные остаются на компьютере",
    privacyHint: "Сессии, список проектов и отметки Space в папке данных; файлы проектов в своих папках, BaoCut не отправляет их. Сетевой доступ агента определяется движком.",
    dataDir: "Папка данных",
    projectsDir: "Новые проекты сохраняются в",
    logsDir: "Папка журналов",
    webCleared: "Веб-данные очищены",
    webClearFailed: (message) => `Не удалось очистить веб-данные: ${message}`,
    webData: "Веб-данные",
    webDataHint: "Cookie, входы и кеш страниц рабочей области. После очистки нужно войти на сайтах снова.",
    webDataNone: "В этой среде нет веб-вкладок.",
    clear: "Очистить",
    runtimeHint: "При ошибках файлы журналов помогут найти причину.",
    version: "Версия",
    appVersion: (version, build) => `Приложение ${version}${build > 0 ? ` (Build ${build})` : ""}`,
    uiVersion: (version, protocol) => `Интерфейс ${version} (протокол ${protocol})`,
    runtimeVersion: (version, protocol) => `${version} (протокол ${protocol})`,
    versionNote: "При несовпадении версий протокола интерфейса и Runtime появится запрос обновления.",
  },
  conversationView: {
    missing: "Сессия не существует или удалена.",
    loadingSession: "Загрузка сессии",
    switchFailed: (message) => `Не удалось переключить: ${message}`,
    accessModeFailed: (message) => `Не удалось изменить режим доступа: ${message}`,
    placeholder: "Продолжить или попробовать другое направление",
    removeFailed: (message) => `Не удалось удалить: ${message}`,
    stopFailed: (message) => `Не удалось остановить: ${message}`,
  },
  composer: {
    disconnected: "Нет подключения к Runtime",
    driverUnavailable: (name, detail) => `${name} недоступен: ${detail}`,
    stopping: "Остановка",
    stop: "Остановить",
    send: "Отправить",
    dropEditorState: "Не добавлять состояние редактора к сообщению",
    spaceEntries: "Элементы Space в сообщении",
    dropSpaceEntries: "Не добавлять эти элементы Space к сообщению",
    message: "Сообщение агенту",
  },
  rail: {
    running: (label, count) => `${label}, ${count} выполняется или в очереди`,
    nav: "Главная навигация",
    primary: "Главные разделы",
    secondary: "Сервисы и фоновые задачи",
  },
  utilitySidebar: {
    overviewTasks: "Все задачи",
    overviewTools: "Все инструменты",
    overviewServices: "Обзор сервисов",
    noteTasks: "Задачи продолжаются в фоне; переключайте страницы в любой момент.",
    noteTools: "Используйте инструменты отдельно; возвращайте результаты в видео или сессию.",
    noteServices: "Управляйте подключениями компьютера для других приложений и устройств.",
    nav: (title) => `${title} — навигация`,
    localServices: "Локальные сервисы",
  },
  titleBar: {
    backTip: "Назад ⌘[",
    forwardTip: "Вперёд ⌘]",
    openTab: 'Новая вкладка',
    enterSplit: 'Разделённый вид',
    hideTabs: 'Скрыть вкладки',
    showTabs: 'Показать вкладки',
    openTabsCount: (n: number) => `${n} ${pluralForm('ru', n, { one: 'открытая вкладка', few: 'открытые вкладки', many: 'открытых вкладок', other: 'открытой вкладки' })}`,
    openTabs: 'Открытые вкладки',
    openInFull: (name: string) => `Открыть «${name}» в полном виде`,
    enterFull: 'Полный вид',
    exitFull: 'Выйти из полного вида',
    summary: 'Сводка',
    summaryOutputs: (n: number) => `Результаты · ${n}`,
    summaryEmpty: 'В этой сессии пока нет результатов.',
  },
  connectionBanner: {
    incompatible: (reason) => `Протоколы интерфейса и Runtime несовместимы: ${reason}`,
    closed: "Соединение закрыто",
    lost: (reason, retrying) => `${reason}.${retrying ? " Переподключение…" : ""}`,
    reconnectingEllipsis: "Переподключение…",
    title: "Нет подключения к Runtime BaoCut",
    reconnecting: "Переподключение",
  },
  videoInfo: {
    title: "Сведения о видео",
    name: "Название",
    summary: "Сводка",
    notes: "Примечания",
    notSaved: "Пока нельзя сохранить",
    copyAll: "Копировать всё",
    done: "Готово",
    copied: "Сведения о видео скопированы",
    copyFailed: "Не удалось скопировать. Выделите текст и скопируйте вручную.",
    renameInEditor: "Откройте видео для переименования",
    renameFailed: (message) => `Не удалось переименовать: ${message}`,
  },
  filePreview: {
    tooLarge: "Файл слишком большой для полного отображения",
    loading: "Загрузка предпросмотра",
    unsupported: "BaoCut пока не показывает этот вид файла. Покажите в папке и откройте другим приложением.",
    failed: (message) => `Не удалось загрузить предпросмотр: ${message}`,
  },
  accessPicker: {
    current: (label) => `Режим доступа: ${label}`,
    label: "Режим доступа",
  },
  agentPicker: {
    current: (label) => `Агент для программирования и модель: ${label}`,
    label: "Агент для программирования и модель",
    models: (name) => `${name} моделей`,
  },
  nameDialog: {
    failed: (action, message) => `Не удалось ${action.toLowerCase()}: ${message}`,
  },
  editorReference: {
    label: (videoName, selected) => `«${videoName}»${selected ? ` · ${selected} ${pluralForm('ru', selected, { one: "клип", few: "клипа", many: "клипов", other: "клипа" })} выделено` : ""}`,
    description: "Отправляет текущую версию видео, выбранные клипы и позицию курсора воспроизведения с сообщением",
  },
  voicePicker: { placeholder: "Выбрать голос" },
  pageSidebar: { resize: "Изменить размер боковой панели", pin: 'Закрепить боковую панель' },
  filePane: { label: (name) => `Файл: ${name}` },
};
