import type { ConversationPlace, ShellMessages } from './shell-copy.ts';

const where = (place: ConversationPlace) => (place === 'project' ? '项目里' : '工作目录里');

export const zhHans: ShellMessages = {
  list: (items) => items.join('、'),
  separator: '、',
  common: {
    cancel: '取消',
    save: '保存',
    rename: '重命名',
    renameEllipsis: '重命名…',
    name: '名称',
    pin: '置顶',
    unpin: '取消置顶',
    newSession: '新建会话',
    newSessionInProject: '在这个项目里新建会话',
    working: '进行中',
    loading: '正在加载',
    loadingEllipsis: '正在加载…',
    tools: '工具',
    services: '服务',
    tasks: '后台任务',
    settings: '设置',
    back: '后退',
    forward: '前进',
  },
  conversationHeader: {
    running: '进行中',
    waiting: '等待批准',
    actions: '会话操作',
    viewInSpace: (name) => `在 Space 中查看「${name}」`,
    revealProject: '在文件夹中显示项目',
    revealWorkdir: '在文件夹中显示工作目录',
    deleteSession: '删除会话',
    deleteSessionEllipsis: '删除会话…',
    deleteTitle: '删除这个会话？',
    deleteConfirm: '删除',
    deleteBody: '会话记录会从 BaoCut 里删除，正在运行的任务会先停下。项目目录里的文件不受影响。',
    deleteFailed: (message) => `没能删除：${message}`,
    renameTitle: '重命名会话',
    videosIn: (place) => `${where(place)}的视频`,
    noVideosIn: (place) => `${where(place)}还没有视频`,
    mediaIn: (place) => `${where(place)}的视频与音频`,
    noMediaIn: (place) => `${where(place)}还没有视频或音频`,
    scanning: '正在扫描…',
    none: '没有',
    newVideoFailed: (message) => `没能新建视频：${message}`,
    openVideo: '打开视频',
    newVideo: '新建视频',
    playMedia: '播放视频或音频',
  },
  sidebar: {
    openFolderFailed: (message) => `没能打开目录：${message}`,
    archived: (title) => `已归档「${title}」`,
    undo: '撤销',
    sessions: '会话',
    projectsAndSessions: '项目与会话',
    pinned: '置顶',
    projects: '项目',
    recent: '最近',
    newOrOpenProject: '新建或打开项目',
    newProjectEllipsis: '新建项目…',
    openFolderEllipsis: '打开已有目录…',
    noSessions: '还没有会话。',
    noProjects: '还没有项目。新建一个，或打开已有目录；智能体就在那里工作。',
    newProjectTitle: '新建项目',
    projectName: '项目名称',
    untitledProject: '未命名项目',
    newProjectHint: (dir) => `会在 ${dir} 里新建同名目录。`,
    create: '新建',
    projectCreated: (name) => `已新建项目「${name}」`,
    renameProjectTitle: '重命名项目',
    renameProjectHint: '只改在 BaoCut 里显示的名字，目录名不变。',
    toggleSection: (collapsed, label) => `${collapsed ? '展开' : '折叠'}${label}`,
    organizeLabel: '整理项目与会话',
    sidebarSettings: '侧栏设置',
    organize: '整理侧栏',
    byProject: '按项目分组',
    flat: '在一个列表中',
    sortSessions: '会话排序',
    byRecent: '最近活动',
    byName: '名称',
  },
  sidebarRows: {
    noProject: '不属于任何项目',
    rowActions: (title) => `「${title}」的操作`,
    togglePin: (pinned, title) => `${pinned ? '取消置顶' : '置顶'}「${title}」`,
    archiveNamed: (title) => `归档「${title}」`,
    archive: '归档会话',
    projectActions: (name) => `项目「${name}」的操作`,
    showInSpace: '在 Space 中显示',
    newHere: '在这里新建会话',
  },
  settingsPage: {
    general: '通用',
    models: '模型',
    nav: '设置导航',
    sections: '设置分节',
    shortcutNewSession: '新建会话',
    shortcutTasks: '后台任务',
    shortcutSettings: '设置',
    shortcutSidebar: '显示或隐藏侧栏',
    shortcutBack: '后退',
    shortcutForward: '前进',
    app: '应用',
    privacyTitle: '数据都在这台电脑上',
    privacyHint: '会话、项目登记与 Space 的标记都存在数据目录里；项目文件在各自的目录里，BaoCut 不上传。智能体引擎联网与否由引擎自己决定。',
    dataDir: '数据目录',
    projectsDir: '新建项目放在',
    logsDir: '日志目录',
    webCleared: '已清除网页数据',
    webClearFailed: (message) => `没能清除网页数据：${message}`,
    webData: '网页数据',
    webDataHint: '功能区里打开过的网页留下的 Cookie、登录状态与缓存。清除后这些网站需要重新登录。',
    webDataNone: '这个环境没有网页标签。',
    clear: '清除',
    runtimeHint: '遇到问题时，日志目录里的文件能帮助定位。',
    version: '版本',
    appVersion: (version, build) => `应用 ${version}${build > 0 ? `（Build ${build}）` : ''}`,
    uiVersion: (version, protocol) => `界面 ${version}（协议 ${protocol}）`,
    runtimeVersion: (version, protocol) => `${version}（协议 ${protocol}）`,
    versionNote: '界面与 Runtime 的协议版本不一致时会提示更新。',
  },
  conversationView: {
    missing: '这个会话不存在或已经删除。',
    loadingSession: '正在加载会话',
    switchFailed: (message) => `没能切换：${message}`,
    accessModeFailed: (message) => `没能切换访问模式：${message}`,
    placeholder: '接着说，或者换个方向',
    removeFailed: (message) => `没能去掉：${message}`,
    stopFailed: (message) => `没能停止：${message}`,
  },
  composer: {
    disconnected: '没有连上 Runtime',
    driverUnavailable: (name, detail) => `${name} 不可用：${detail}`,
    stopping: '正在停止',
    stop: '停止',
    send: '发送',
    dropEditorState: '这条消息不附带编辑器状态',
    spaceEntries: '随这条消息带上的 Space 条目',
    dropSpaceEntries: '这条消息不带这些 Space 条目',
    message: '给智能体的消息',
  },
  rail: {
    running: (label, count) => `${label}，${count} 个在跑或排队`,
    nav: '主导航',
    primary: '主要入口',
    secondary: '服务与后台任务',
  },
  utilitySidebar: {
    overviewTasks: '全部任务',
    overviewTools: '全部工具',
    overviewServices: '服务总览',
    noteTasks: '任务在后台继续运行，可随时切换页面。',
    noteTools: '独立使用工具，结果可带回视频或会话。',
    noteServices: '管理本机提供给其他应用和设备的连接。',
    nav: (title) => `${title}导航`,
    localServices: '本机服务',
  },
  titleBar: {
    backTip: '后退 ⌘[',
    forwardTip: '前进 ⌘]',
    openTab: '打开新标签页',
    enterSplit: '进入分屏视图',
    hideTabs: '隐藏标签页',
    showTabs: '显示标签页',
    openTabsCount: (n: number) => `${n} 个已打开的标签页`,
    openTabs: '已打开的标签页',
    openInFull: (name: string) => `在完整视图中打开「${name}」`,
    enterFull: '进入完整视图',
    exitFull: '退出完整视图',
    summary: '会话摘要',
    summaryOutputs: (n: number) => `产物 · ${n}`,
    summaryEmpty: '这条会话还没有产物。',
  },
  connectionBanner: {
    incompatible: (reason) => `界面与 Runtime 的协议版本不兼容：${reason}`,
    closed: '连接已关闭',
    lost: (reason, retrying) => `${reason}。${retrying ? '正在重新连接…' : ''}`,
    reconnectingEllipsis: '正在重新连接…',
    title: '没有连上 BaoCut Runtime',
    reconnecting: '正在重新连接',
  },
  videoInfo: {
    title: '视频详情',
    name: '名称',
    summary: '简介',
    notes: '备注',
    notSaved: '还不能保存',
    copyAll: '复制全部',
    done: '完成',
    copied: '已复制视频详情',
    copyFailed: '没能复制，请手动选中文字复制',
    renameInEditor: '打开视频后才能改名',
    renameFailed: (message) => `没能重命名：${message}`,
  },
  filePreview: {
    tooLarge: '文件太大，这里不显示全文',
    loading: '正在加载预览',
    unsupported: '这种文件在 BaoCut 里还不能预览。可以在文件夹中显示后用别的应用打开。',
    failed: (message) => `没能加载预览：${message}`,
  },
  accessPicker: {
    current: (label) => `访问模式：${label}`,
    label: '访问模式',
  },
  agentPicker: {
    current: (label) => `编码 Agent 与模型：${label}`,
    label: '编码 Agent 与模型',
    models: (name) => `${name} 的模型`,
  },
  nameDialog: {
    failed: (action, message) => `没能${action}：${message}`,
  },
  editorReference: {
    label: (videoName, selected) => `「${videoName}」${selected ? ` · 选中 ${selected} 个片段` : ''}`,
    description: '随消息附带这个视频的当前版本、选中的片段和播放头位置',
  },
  voicePicker: { placeholder: '选一个音色' },
  pageSidebar: { resize: '调整侧栏宽度', pin: '固定侧边栏' },
  filePane: { label: (name) => `文件：${name}` },
};
