import { pluralForm } from '@baocut/protocol';
import type { ConversationPlace, ShellMessages } from './shell-copy.ts';

export const de: ShellMessages = {

  list: (items: readonly string[]): string => items.join(", "),
  separator: ", ",
  common: {
    cancel: "Abbrechen",
    save: "Speichern",
    rename: "Umbenennen",
    renameEllipsis: "Umbenennen…",
    name: "Name",
    pin: "Anker",
    unpin: "Lösen",
    newSession: "Neue Sitzung",
    newSessionInProject: "Neue Sitzung in diesem Projekt",
    working: "Verarbeitung",
    loading: "Wird geladen",
    loadingEllipsis: "Wird geladen…",
    tools: "Werkzeuge",
    services: "Dienste",
    tasks: "Hintergrundaufgaben",
    settings: "Einstellungen",
    back: "Zurück",
    forward: "Vorwärts",
  },
  conversationHeader: {
    running: "Verarbeitung",
    waiting: "Wartet auf Genehmigung",
    actions: "Sitzungsaktionen",
    viewInSpace: (name: string) => `In Space anzeigen: „${name}“`,
    revealProject: "Projektordner anzeigen",
    revealWorkdir: "Arbeitsordner anzeigen",
    deleteSession: "Sitzung löschen",
    deleteSessionEllipsis: "Sitzung löschen…",
    deleteTitle: "Diese Sitzung löschen?",
    deleteConfirm: "Löschen",
    deleteBody:
      "Der Sitzungsverlauf wird aus BaoCut entfernt; laufende Aufgaben werden zuerst gestoppt. Dateien im Projektordner bleiben unverändert.",
    deleteFailed: (message: string) => `Löschen fehlgeschlagen: ${message}`,
    renameTitle: "Sitzung umbenennen",
    videosIn: (place: ConversationPlace): string => (place === 'project' ? "Videos im Projekt" : "Videos im Arbeitsordner"),
    noVideosIn: (place: ConversationPlace): string => (place === 'project' ? "Noch keine Videos im Projekt" : "Noch keine Videos im Arbeitsordner"),
    mediaIn: (place: ConversationPlace): string =>
      place === 'project' ? "Videos und Audio im Projekt" : "Videos und Audio im Arbeitsordner",
    noMediaIn: (place: ConversationPlace): string =>
      place === 'project' ? "Noch keine Videos oder Audiodateien im Projekt" : "Noch keine Videos oder Audiodateien im Arbeitsordner",
    scanning: "Wird gescannt…",
    none: "Keine",
    newVideoFailed: (message: string) => `Video konnte nicht erstellt werden: ${message}`,
    openVideo: "Video öffnen",
    newVideo: "Neues Video",
    playMedia: "Video oder Audio abspielen",
  },
  sidebar: {
    openFolderFailed: (message: string) => `Ordner konnte nicht geöffnet werden: ${message}`,
    archived: (title: string) => `Archiviert: „${title}“`,
    undo: "Rückgängig machen",
    sessions: "Sitzungen",
    projectsAndSessions: "Projekte und Sitzungen",
    pinned: "Angeheftet",
    projects: "Projekte",
    recent: "Zuletzt",
    newOrOpenProject: "Projekt erstellen oder öffnen",
    newProjectEllipsis: "Neues Projekt…",
    openFolderEllipsis: "Vorhandenen Ordner öffnen…",
    noSessions: "Noch keine Sitzungen.",
    noProjects: "Noch keine Projekte. Ein Projekt erstellen oder vorhandenen Ordner öffnen; der Agent arbeitet dort.",
    newProjectTitle: "Neues Projekt",
    projectName: "Projektname",
    untitledProject: "Unbenanntes Projekt",
    newProjectHint: (dir: string) => `Ein gleichnamiger Ordner wird erstellt in ${dir}.`,
    create: "Erstellen",
    projectCreated: (name: string) => `Projekt erstellt: „${name}“`,
    renameProjectTitle: "Projekt umbenennen",
    renameProjectHint: "Ändert nur den Namen in BaoCut; der Ordnername bleibt unverändert.",
    toggleSection: (collapsed: boolean, label: string) => `${collapsed ? "Erweitern" : "Einklappen"} ${label}`,
    organizeLabel: "Projekte und Sitzungen organisieren",
    sidebarSettings: "Seitenleisteneinstellungen",
    organize: "Seitenleiste organisieren",
    byProject: "Nach Projekt gruppieren",
    flat: "In einer Liste",
    sortSessions: "Sitzungen sortieren",
    byRecent: "Letzte Aktivität",
    byName: "Name",
  },
  sidebarRows: {
    noProject: "Nicht in einem Projekt",
    rowActions: (title: string) => `Aktionen für „${title}“`,
    togglePin: (pinned: boolean, title: string) => `${pinned ? "Lösen" : "Anker"} „${title}“`,
    archiveNamed: (title: string) => `Archivieren: „${title}“`,
    archive: "Sitzung archivieren",
    projectActions: (name: string) => `Aktionen für Projekt „${name}“`,
    showInSpace: "In Space anzeigen",
    newHere: "Hier neue Sitzung",
  },
  settingsPage: {
    general: "Allgemein",
    models: "Modelle",
    nav: "Einstellungsnavigation",
    sections: "Einstellungsbereiche",
    shortcutNewSession: "Neue Sitzung",
    shortcutTasks: "Hintergrundaufgaben",
    shortcutSettings: "Einstellungen",
    shortcutSidebar: "Seitenleiste ein- oder ausblenden",
    shortcutBack: "Zurück",
    shortcutForward: "Vorwärts",
    app: "App",
    privacyTitle: "Ihre Daten bleiben auf diesem Computer",
    privacyHint:
      "Sitzungen, Projektliste und Space-Markierungen liegen im Datenordner. Projektdateien bleiben in ihren eigenen Ordnern und werden von BaoCut nicht hochgeladen. Internetverbindung des Agenten bestimmt dessen Engine.",
    dataDir: "Datenordner",
    projectsDir: "Neue Projekte liegen in",
    logsDir: "Protokollordner",
    webCleared: "Webdaten gelöscht",
    webClearFailed: (message: string) => `Webdaten konnten nicht gelöscht werden: ${message}`,
    webData: "Webdaten",
    webDataHint: "Cookies, Anmeldungen und Cache der im Arbeitsbereich geöffneten Webseiten. Nach Löschen ist erneute Anmeldung auf diesen Websites nötig.",
    webDataNone: "Diese Umgebung hat keine Web-Tabs.",
    clear: "Löschen",
    runtimeHint: "Bei Fehlern helfen Dateien im Protokollordner bei der Diagnose.",
    version: "Version",
    appVersion: (version: string, build: number) => `App ${version}${build > 0 ? ` (Build ${build})` : ""}`,
    uiVersion: (version: string, protocol: number | string) => `Oberfläche ${version} (Protokoll ${protocol})`,
    runtimeVersion: (version: string, protocol: number | string) => `${version} (Protokoll ${protocol})`,
    versionNote: "Bei abweichenden Oberflächen- und Runtime-Protokollversionen wird zur Aktualisierung aufgefordert.",
  },
  conversationView: {
    missing: "Diese Sitzung ist nicht vorhanden oder wurde gelöscht.",
    loadingSession: "Sitzung wird geladen",
    switchFailed: (message: string) => `Wechsel fehlgeschlagen: ${message}`,
    accessModeFailed: (message: string) => `Zugriffsmodus konnte nicht geändert werden: ${message}`,
    placeholder: "Fortfahren oder eine andere Richtung versuchen",
    removeFailed: (message: string) => `Entfernen fehlgeschlagen: ${message}`,
    stopFailed: (message: string) => `Stoppen fehlgeschlagen: ${message}`,
  },
  composer: {
    disconnected: "Nicht mit Runtime verbunden",
    driverUnavailable: (name: string, detail: string) => `${name} nicht verfügbar: ${detail}`,
    stopping: "Wird gestoppt",
    stop: "Stopp",
    send: "Senden",
    dropEditorState: "Editorzustand dieser Nachricht nicht beifügen",
    spaceEntries: "Mit dieser Nachricht gesendete Space-Einträge",
    dropSpaceEntries: "Diese Space-Einträge dieser Nachricht nicht beifügen",
    message: "Nachricht an den Agenten",
  },
  rail: {
    running: (label: string, count: number) => `${label}, ${count} laufend oder eingereiht`,
    nav: "Hauptnavigation",
    primary: "Hauptbereiche",
    secondary: "Dienste und Hintergrundaufgaben",
  },
  utilitySidebar: {
    overviewTasks: "Alle Aufgaben",
    overviewTools: "Alle Werkzeuge",
    overviewServices: "Dienstübersicht",
    noteTasks: "Aufgaben laufen im Hintergrund weiter; Seitenwechsel jederzeit möglich.",
    noteTools: "Werkzeuge einzeln verwenden und Ergebnisse in ein Video oder eine Sitzung übernehmen.",
    noteServices: "Verbindungen dieses Computers zu anderen Apps und Geräten verwalten.",
    nav: (title: string) => `${title}: Navigation`,
    localServices: "Lokale Dienste",
  },
  titleBar: {
    backTip: "Zurück ⌘[",
    forwardTip: "Vorwärts ⌘]",
    openTab: 'Neuer Tab',
    enterSplit: 'Geteilte Ansicht',
    hideTabs: 'Tabs ausblenden',
    showTabs: 'Tabs einblenden',
    openTabsCount: (n: number) => (n === 1 ? '1 geöffneter Tab' : `${n} geöffnete Tabs`),
    openTabs: 'Geöffnete Tabs',
    openInFull: (name: string) => `„${name}“ in der Vollansicht öffnen`,
    enterFull: 'Vollansicht',
    exitFull: 'Vollansicht verlassen',
    summary: 'Zusammenfassung',
    summaryOutputs: (n: number) => `Ergebnisse · ${n}`,
    summaryEmpty: 'Diese Sitzung hat noch keine Ergebnisse.',
  },
  connectionBanner: {
    incompatible: (reason: string) => `Oberflächen- und Runtime-Protokollversionen sind inkompatibel: ${reason}`,
    closed: "Verbindung geschlossen",
    lost: (reason: string, retrying: boolean) => `${reason}.${retrying ? " Wird neu verbunden…" : ""}`,
    reconnectingEllipsis: "Wird neu verbunden…",
    title: "Nicht mit BaoCut Runtime verbunden",
    reconnecting: "Wird neu verbunden",
  },
  videoInfo: {
    title: "Videodetails",
    name: "Name",
    summary: "Zusammenfassung",
    notes: "Notizen",
    notSaved: "Noch nicht speicherbar",
    copyAll: "Alles kopieren",
    done: "Fertig",
    copied: "Videodetails kopiert",
    copyFailed: "Kopieren fehlgeschlagen. Text auswählen und manuell kopieren.",
    renameInEditor: "Video zum Umbenennen öffnen",
    renameFailed: (message: string) => `Umbenennen fehlgeschlagen: ${message}`,
  },
  filePreview: {
    tooLarge: "Die Datei ist zu groß für eine vollständige Anzeige",
    loading: "Vorschau wird geladen",
    unsupported: "BaoCut kann diesen Dateityp noch nicht als Vorschau anzeigen. Im Ordner anzeigen und mit einer anderen App öffnen.",
    failed: (message: string) => `Vorschau konnte nicht geladen werden: ${message}`,
  },
  accessPicker: {
    current: (label: string) => `Zugriffsmodus: ${label}`,
    label: "Zugriffsmodus",
  },
  agentPicker: {
    current: (label: string) => `Coding-Agent und Modell: ${label}`,
    label: "Coding-Agent und Modell",
    models: (name: string) => `${name} Modelle`,
  },
  nameDialog: {
    failed: (action: string, message: string) => `Fehlgeschlagen: ${action.toLowerCase()}: ${message}`,
  },
  editorReference: {
    label: (videoName: string, selected: number) =>
      `„${videoName}“${selected ? ` · ${selected} ${pluralForm('de', selected, { one: "Clip", other: "Clips" })} ausgewählt` : ""}`,
    description: "Sendet aktuelle Videoversion, ausgewählte Clips und Abspielkopfposition mit der Nachricht",
  },
  voicePicker: { placeholder: "Stimme auswählen" },
  pageSidebar: { resize: "Seitenleistengröße ändern", pin: 'Seitenleiste anheften' },
  filePane: { label: (name: string) => `Datei: ${name}` },
};
