import type { ProvidersHttpMessages } from './providers-http.ts';
export const es: ProvidersHttpMessages = {
 aborted: 'Solicitud cancelada', rejected: (p) => `${p.label} rechazó la solicitud (HTTP ${p.status})`, unreachable: (p) => `No se puede acceder a ${p.label}`, httpStatus: (p) => `${p.label} devolvió HTTP ${p.status}`, failedAfterAttempts: (p) => `${p.what}, sigue fallando después de ${p.attempts} intentos`, withMessage: (p) => `${p.text}: ${p.message}`, errorCode: (p) => `${p.message} (${p.code})`,
 noResponse: (p) => `${p.label} no respondió en ${p.seconds} segundos`, tooManyRedirects: (p) => `${p.label} redirigió demasiadas veces`, badRedirect: (p) => `${p.label} devolvió una dirección de redirección que no se puede reconocer`, redirectProtocol: (p) => `${p.label} redirigió a un protocolo no compatible`, redirectOrigin: (p) => `${p.label} redirigió la solicitud a otra dirección. No se siguió, para evitar enviar materiales a otro lugar`, responseTooLarge: 'La respuesta del proveedor es demasiado grande',
 invalidJson: (p) => `La respuesta de ${p.label} no es JSON válido`, notObject: (p) => `La respuesta de ${p.label} no es un objeto`, missingField: (p) => `La respuesta de ${p.label} no tiene ${p.field}`, missingText: (p) => `Falta texto en la respuesta de ${p.label}`, missingTranscript: (p) => `La respuesta de ${p.label} no tiene resultado de transcripción`, cloneNoVoiceId: (p) => `La respuesta de clonación de ${p.label} no tiene voice_id`, noB64: (p) => `La respuesta de ${p.label} no tiene b64_json (no se admiten endpoints que solo devuelven URL de imágenes)`,
 listShape: (p) => `La lista de modelos de ${p.label} no es ${p.shape}`, listNotArray: (p) => `La lista de modelos de ${p.label} no es un array`, voicesShape: (p) => `La lista de voces de ${p.label} no es { voices: [...] }`, unexpectedFinish: (p) => `${p.label} devolvió un motivo de finalización inesperado: ${p.reason}`, jsonNotAudio: (p) => `${p.label} devolvió JSON en lugar de audio`, emptyAudio: (p) => `${p.label} devolvió audio vacío`, formatUnsupported: (p) => `${p.label} no produce ${p.format}`,
 imageCount: (p) => `${p.label} devolvió ${p.got} imágenes, pero se solicitaron ${p.want}`, transcribeIncomplete: (p) => `${p.label} no terminó esta transcripción (${p.status})`, generateIncomplete: (p) => `${p.label} no terminó esta generación (${p.status})`, noImageSize: (p) => `El modelo ${p.model} de ${p.label} no tiene el tamaño ${p.size}`, noImageReturned: (p) => `${p.label} no devolvió ninguna imagen`, noImageReturnedSaid: (p) => `${p.label} no devolvió ninguna imagen: ${p.said}`, wrongMime: (p) => `${p.label} devolvió ${p.got}, pero se solicitó ${p.want}`,
 emptyOutput: 'El proveedor devolvió un resultado vacío', requestIncomplete: 'La solicitud no terminó', audioUnreadable: 'No se puede leer el audio del material (falló la decodificación de ffmpeg)', chunkEncodeFailed: 'Falló la codificación de un segmento de audio (ffmpeg)', notWav: 'El audio decodificado no es WAV', wavMissingChunks: 'Al WAV decodificado le falta el bloque fmt o data', ffmpegMissing: 'ffmpeg no encontrado. La transcripción en línea lo necesita para preparar el audio. Instálalo y reinicia BaoCut', ffmpegRunFailed: (p) => `No se pudo ejecutar ffmpeg: ${p.error}`, ffmpegTimeout: 'ffmpeg agotó el tiempo al procesar audio',
 rangeClamped: (p) => `El intervalo solicitado supera el final del audio: se procesaron ${p.decoded} s y se solicitaron ${p.requested} s`, segmentDropped: (p) => `Un segmento de texto tenía tiempos no válidos y se descartó: ${p.text}`,
};
