import type { ProvidersHttpMessages } from './providers-http.ts';

export const fr: ProvidersHttpMessages = {
  aborted: 'Requête annulée', rejected: (p) => `${p.label} a refusé la requête (HTTP ${p.status})`, unreachable: (p) => `Impossible de joindre ${p.label}`, httpStatus: (p) => `${p.label} a renvoyé HTTP ${p.status}`,
  failedAfterAttempts: (p) => `${p.what}, toujours en échec après ${p.attempts} tentatives`, withMessage: (p) => `${p.text} : ${p.message}`, errorCode: (p) => `${p.message} (${p.code})`, noResponse: (p) => `${p.label} n’a pas répondu en ${p.seconds} secondes`,
  tooManyRedirects: (p) => `${p.label} a redirigé trop de fois`, badRedirect: (p) => `${p.label} a renvoyé une adresse de redirection non reconnue`, redirectProtocol: (p) => `${p.label} a redirigé vers un protocole non pris en charge`,
  redirectOrigin: (p) => `${p.label} a redirigé la requête vers une autre adresse. La redirection n’a pas été suivie afin de ne pas envoyer les médias ailleurs`, responseTooLarge: 'La réponse du fournisseur est trop volumineuse', invalidJson: (p) => `La réponse de ${p.label} n’est pas un JSON valide`,
  notObject: (p) => `La réponse de ${p.label} n’est pas un objet`, missingField: (p) => `La réponse de ${p.label} ne contient pas ${p.field}`, missingText: (p) => `La réponse de ${p.label} ne contient pas de texte`, missingTranscript: (p) => `La réponse de ${p.label} ne contient pas de résultat de transcription`,
  cloneNoVoiceId: (p) => `La réponse de clonage de ${p.label} ne contient pas de voice_id`, noB64: (p) => `La réponse de ${p.label} ne contient pas de b64_json (les points de terminaison qui renvoient uniquement des URL d’image ne sont pas pris en charge)`, listShape: (p) => `La liste de modèles de ${p.label} n’est pas ${p.shape}`,
  listNotArray: (p) => `La liste de modèles de ${p.label} n’est pas un tableau`, voicesShape: (p) => `La liste de voix de ${p.label} n’est pas { voices: [...] }`, unexpectedFinish: (p) => `${p.label} a renvoyé une raison de fin inattendue : ${p.reason}`,
  jsonNotAudio: (p) => `${p.label} a renvoyé du JSON au lieu d’audio`, emptyAudio: (p) => `${p.label} a renvoyé un audio vide`, formatUnsupported: (p) => `${p.label} ne produit pas ${p.format}`, imageCount: (p) => `${p.label} a renvoyé ${p.got} images, mais ${p.want} étaient demandées`,
  transcribeIncomplete: (p) => `${p.label} n’a pas terminé cette transcription (${p.status})`, generateIncomplete: (p) => `${p.label} n’a pas terminé cette génération (${p.status})`, noImageSize: (p) => `Le modèle ${p.model} de ${p.label} ne propose pas la taille ${p.size}`,
  noImageReturned: (p) => `${p.label} n’a renvoyé aucune image`, noImageReturnedSaid: (p) => `${p.label} n’a renvoyé aucune image : ${p.said}`, wrongMime: (p) => `${p.label} a renvoyé ${p.got}, mais ${p.want} était demandé`, emptyOutput: 'Le fournisseur a renvoyé une sortie vide', requestIncomplete: 'La requête n’a pas abouti',
  audioUnreadable: 'Impossible de lire l’audio du média (échec du décodage ffmpeg)', chunkEncodeFailed: 'L’encodage d’un segment audio a échoué (ffmpeg)', notWav: 'L’audio décodé n’est pas WAV', wavMissingChunks: 'Le WAV décodé n’a pas de bloc fmt ou data',
  ffmpegMissing: 'ffmpeg est introuvable. La transcription en ligne en a besoin pour préparer l’audio. Installez-le, puis redémarrez BaoCut', ffmpegRunFailed: (p) => `Impossible d’exécuter ffmpeg : ${p.error}`, ffmpegTimeout: 'ffmpeg a expiré pendant le traitement de l’audio',
  rangeClamped: (p) => `La plage demandée dépasse la fin de l’audio : ${p.decoded} s traitées, ${p.requested} s demandées`, segmentDropped: (p) => `Un segment de texte avait un minutage invalide et a été supprimé : ${p.text}`,
};
