import { pluralForm } from '@baocut/protocol';
import { MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_PER_MESSAGE } from '@baocut/protocol';
import type { CopyMessages } from './copy.ts';




export const ru: CopyMessages = {
  /** 打开系统的文件管理器并选中目标。所有平台同一个说法，不写某个平台专有的文件管理器名字（docs/glossary.md）。 */
  reveal: "Показать в папке",
  untitled: "Новая сессия",
  /** 用户消息上方已发送的图片（原型 agent-thread.jsx `UserMsg`）。 */
  sentAttachments: "Отправленные файлы",
  /** 任务在跑时切换访问模式的提示（原型 model-agent.js `modeToast` 的运行中分支）。 */
  accessModeToast: (label: string) => `Следующий ход будет выполнен в режиме «${label}». Текущий ход сохранит прежний режим доступа.`,
  /** composer 脚注（原型 model-agent.js `composerFoot`）：在哪儿跑、用谁的订阅（空串表示没有账号名）、这一档会不会问你、快捷键。 */
  composerFoot: (name: string, account: string, foot: string) =>
    `Работает через ${name} на этом компьютере, ${account ? `с вашей подпиской ${account}` : "с вашей подпиской"}. ${foot} Enter — отправить, Shift+Enter — новая строка, @ — ссылка, / — команды.`,

  /**
   * 访问模式（架构设计 §3.12，原型 data.js `agent.modes`）。原型只画四档；「先给方案」是协议里独立的一档，
   * 输入框下拉只在会话已经处在这一档时列出它（例如经 CLI 切过去的）。
   */
  accessModeLabel: {
    plan: "Сначала план",
    ask: "Под надзором",
    autoAcceptEdits: "Автоприём правок",
    auto: "Авто",
    fullAccess: "Полный доступ",
  },
  accessModeHint: {
    plan: "Только чтение. Сначала предлагает план и не меняет файлы или видео",
    ask: "Спрашивает перед командами или изменением файлов",
    autoAcceptEdits: "Автоматически одобряет изменения файлов и спрашивает перед остальным",
    auto: "Автоматически одобряет обычные действия; перед рискованными спрашивает",
    fullAccess: "Выполняет команды и меняет файлы без вопросов",
  },
  taskStatusLabel: {
    running: "Выполняется",
    stopping: "Остановка",
    completed: "Готово",
    stopped: "Остановлено",
    failed: "Ошибка",
  },
  /** composer 脚注的中段：这一档到底会不会问你（原型 model-agent.js `modeFoot`）。 */
  accessModeFoot: {
    plan: "Только планирует и не меняет видео.",
    ask: "Спрашивает перед каждой записью в видео.",
    autoAcceptEdits: "Изменения файлов видео разрешены автоматически; остальные команды требуют вопроса.",
    auto: "Обычные действия разрешены автоматически; рискованные требуют вопроса.",
    fullAccess: "Записывает в видео без вопроса каждый раз.",
  },
  /** 模型定位（原型 model-agent-setup.js `TIERS`）。 */
  modelTierLabel: { balanced: "Рекомендуется", max: "Самая мощная", fast: "Самая быстрая" },
  /**
   * 推理强度（原型 data.js `agent.efforts`）：原生 id → 名字与代价。原型的 `mid` 在 Claude 与 Codex 里叫 `medium`。
   * 原型给「中」的副文案是「默认」：这里改成标在模型自己的默认强度那一行（见 agent-choice.ts `effortRows`）。
   */
  effort: {
    low: { label: "Низкий", sub: "Быстро, подходит для небольших правок" },
    medium: { label: "Средний", sub: null },
    high: { label: "Высокий", sub: "Медленнее, дольше обдумывает" },
  },
  agentPicker: {
    group: "Агент для программирования",
    models: "Модели",
    effort: (label: string) => `Уровень рассуждений · ${label}`,
    agentDefault: "Модель агента по умолчанию",
    agentDefaultSub: "Определяется настройками CLI",
    configModelGate: (model: string) => `${model} требует более новой CLI`,
    notListed: "Этой модели нет в текущем списке",
    defaultMark: "По умолчанию",
    localAccount: "Этот компьютер",
    settings: "Настройки › Агенты…",
    settingsSub: "Агент для программирования · Подписка · Политика одобрений",
    /** 会话有任务后 Agent 固定（架构设计 §3.11：原生会话不能跨 Agent 续）。 */
    locked: "Эта сессия уже началась, поэтому сменить агента нельзя. Для смены начните новую сессию.",
    detecting: "Обнаружение агентов…",
  },
  /** Agent 用不了时第一级那一行的副文案（原型 model-agent.js `providerRows`，状态词取 model-agent-setup.js `badge`）。 */
  driverStateReason: {
    disabled: "Отключён в настройках",
    'not-installed': "Не установлен",
    'signed-out': "Нужен вход · Проверьте настройки",
    outdated: "Устаревшая версия · Проверьте настройки",
    error: "Не запускается · Проверьте настройки",
  },
  /** 斜杠命令的名字与说明，键是去掉 `/` 的命令名（`SLASH_COMMANDS`）。 */
  slash: {
    polish: { label: "Отредактировать расшифровку", sub: "Исправить опечатки, добавить пунктуацию, разбить на абзацы" },
    chapters: { label: "Создать главы", sub: "Разделить по темам и добавить заголовки" },
    speakers: { label: "Определить говорящих", sub: "Добавить имена в субтитры и расшифровку" },
    retranscribe: { label: "Расшифровать заново", sub: "Обработать аудио другой речевой моделью" },
    clean: { label: "Найти вырезаемые фрагменты", sub: "Слова-паразиты, длинные паузы, неудачные дубли" },
    translate: { label: "Перевести субтитры", sub: "Перевести на один язык и выровнять таймкоды" },
    refresh: { label: "Обновить устаревшие переводы", sub: "Перевести заново только строки с изменённым оригиналом" },
    dub: { label: "Перевести озвучку", sub: "Озвучить видео на другом языке" },
    summary: { label: "Написать краткое содержание", sub: "Краткое содержание и ключевые моменты с таймкодами" },
    blog: { label: "Написать пост для блога", sub: "Переписать как статью" },
    title: { label: "Предложить заголовки", sub: "Несколько вариантов с разных сторон" },
    desc: { label: "Написать описание", sub: "С таймкодами глав и тегами" },
    cover: { label: "Создать обложку", sub: "Несколько вариантов на основе ключевых кадров" },
    export: { label: "Экспортировать", sub: "SRT / MP4 со встроенными субтитрами" },
  },
  composerMenu: {
    insert: "Вставить",
    filesAndFolders: 'Файлы и папки',
    files: 'Файлы', folders: 'Папки',
    filesMessage: (paths) => `Файлы и папки:\n${paths.map(path => JSON.stringify(path)).join('\n')}`,
    pickFailed: (message) => `Не удалось выбрать файлы: ${message}`,
    webFilesUnsupported: 'Добавляйте локальные файлы и папки в BaoCut для компьютера. Загрузка в Web-клиенте пока недоступна.',
    /** 原型是「引用章节或文件」；章节、说话人这类数据 Runtime 还没有，只列视频与文件。 */
    mention: "Сослаться на видео или файл",
    slash: "Использовать инструмент",
    /** 「+」菜单的两组：附件类在上，引用与命令在下（原型 composer-insert-menu.jsx）。 */
    attachSection: 'Добавить',
    referSection: "Ссылки и команды",
    imagesUnsupported: (driverName: string) => `${driverName} не принимает изображения`,
    noMentionCandidates: "Здесь пока нет видео или файлов для ссылки",
  },
  /** 输入框「+ › 使用 Skill」、输入框上的 skill 标记与会话消息上的标记（产品设计 §3.2.3、§6.9；原型 composer-insert-menu.jsx）。 */
  skill: {
    use: "Использовать Skill",
    manage: "Управлять Skills…",
    loading: "Загрузка Skills…",
    none: "Skills пока нет. Добавьте из локальной папки в настройках или импортируйте из GitHub",
    loadFailed: "Не удалось загрузить Skills",
    token: (name: string) => `Skill: ${name}`,
    remove: (name: string) => `Убрать Skill: ${name}`,
  },
  /** 附图（原型 agent-thread.jsx `composerImageFiles` 与 `addImages`）。 */
  attachment: {
    tooLarge: `Выберите изображения размером не более ${MAX_ATTACHMENT_BYTES / 1024 / 1024} MiB`,
    tooMany: `Можно прикрепить до ${MAX_ATTACHMENTS_PER_MESSAGE} ${pluralForm('ru', MAX_ATTACHMENTS_PER_MESSAGE, { one: 'изображения', few: 'изображений', many: 'изображений', other: 'изображения' })}`,
    /** 原型只收 image/*；协议只收这四种（limits.ts），多出来的一句。 */
    badType: "Можно прикрепить только PNG, JPEG, GIF или WebP",
    uploadFailed: (message: string) => `Не удалось загрузить изображение: ${message}`,
    httpFailed: (status: number) => `Ошибка загрузки (HTTP ${status})`,
    networkFailed: "Ошибка загрузки: Runtime недоступен",
    uploading: "Загрузка изображений…",
  },
  /** 忙时排队（会话有任务在跑时发的话）。 */
  queue: {
    title: (count: number) => `В очереди на отправку · ${count}`,
    images: (count: number) => `${count} ${pluralForm('ru', count, {one: "изображение", few: "изображения", many: "изображений", other: "изображения"})}`,
    edit: "Редактировать",
    save: "Сохранить",
    cancel: "Отмена",
    remove: "Удалить",
    sendNow: "Отправить сейчас",
    editLabel: "Редактировать сообщение в очереди",
    steerUnsupported: "Этот агент не принимает сообщения во время задачи. Сообщение будет отправлено после её завершения",
    skillWaits: "Сообщения со Skill не могут присоединиться к текущему ходу. Они будут отправлены после его завершения",
    failed: (message: string) => `Не удалось отправить сообщение из очереди: ${message}`,
    busyPlaceholder: "Агент работает. Новые сообщения помещаются в очередь до завершения текущего хода",
  },
  /** 任务失败后的恢复区（原型 agent-thread.jsx `ErrorMsg`）。 */
  recovery: {
    authTitle: (name: string) => `${name} требует входа заново`,
    authBody: (name: string) =>
      `Вход выполняется в окне агента ${name}; BaoCut не обрабатывает ваш аккаунт или пароль. После входа вернитесь и отправьте снова.`,
    openLogin: "Войти через терминал",
    loginOpened: (command: string) => `Выполнение ${command} в терминале · После входа вернитесь и отправьте снова`,
    loginCopied: "Не удалось открыть терминал. Команда входа скопирована; вставьте её в терминал для выполнения",
    loginManual: (command: string) => `Не удалось открыть терминал. Выполните ${command} в терминале`,
    modelTitle: (model: string | null) => `${model ?? "Эта модель"} сейчас недоступна`,
    modelBody: "Выберите другую модель и отправьте снова. BaoCut не переключает модели самостоятельно.",
    pickModel: "Отправить снова с другой моделью",
    resend: "Отправить снова",
    retry: "Повторить попытку",
    agentSettings: "Настройки агента",
    nothingToResend: "Не удалось найти сообщение этого хода для повторной отправки",
    resendFailed: (message: string) => `Не удалось отправить снова: ${message}`,
  },
  /** 审批卡（原型 agent-thread.jsx `PermissionMsg`，自动允许的那一行取 model-agent.js `autoAllowLabel`）。 */
  approval: {
    title: {
      command: "Агент хочет выполнить команду",
      'file-change': "Агент хочет изменить файлы",
      tool: "Агент хочет использовать инструмент",
      highRisk: "Агент хочет выполнить рискованное действие",
    },
    kind: { command: "Выполнить команду", 'file-change': "Изменить файлы", tool: "Использовать инструмент" },
    projectFiles: "Файлы проекта",
    inDir: (dir: string) => `В ${dir}`,
    allow: "Разрешить",
    allowAlways: (rule: string) => `Всегда разрешать ${rule}`,
    decline: "Отклонить",
    accepted: "Разрешено",
    acceptedAlways: (rule: string) => `Разрешено · Больше не спрашивать о ${rule} снова`,
    declined: "Отклонено",
    cancelled: "Остановлено",
    autoRule: (rule: string | null) => (rule ? `Разрешено автоматически · Правило ${rule}` : "Разрешено автоматически · Правило"),
    autoMode: "Разрешено автоматически · Режим доступа",
    input: "Краткое описание входных данных",
    copyInput: "Скопировать описание входных данных",
    failed: (message: string) => `Не удалось отправить: ${message}`,
  },
  /** 变更卡的撤销与恢复（原型 agent-thread.jsx `ReceiptMsg`）。 */
  change: {
    undone: "Отменено · Изменения убраны",
    undo: "Отменить",
    restore: "Восстановить",
    openVideo: "Открыть видео",
    confirmTitle: "Отменить этот шаг?",
    /**
     * 「恢复」只在这一笔还是你最近一次撤销、之后你没再改这个视频时才有（见 change-card.tsx），不说「随时」。
     */
    confirmBody: "Изменения, внесённые этим шагом в видео, будут удалены. Пока вы снова не отредактируете видео, их можно вернуть через «Восстановить».",
    cancel: "Отмена",
    undoneToast: "Отменено",
    restoredToast: "Восстановлено",
    alreadyUndone: "Этот шаг уже отменён",
    undoFailed: (message: string) => `Не удалось отменить: ${message}`,
    restoreFailed: (message: string) => `Не удалось восстановить: ${message}`,
  },
  /**
   * 空会话（原型 agent-thread.jsx `AgentThread` 的空态，建议取 data.js `agent.chips`）。
   * 原型说明句里的「@ 可以引用章节、说话人、译文」「写入之前一定先问你」「把视频拖进来」这里还做不到
   * （@ 只列视频与文件；问不问看访问模式；会话里不能拖入视频），只留做得到的部分。
   */
  threadEmpty: {
    greetVideo: (name: string) => `Что сделать с видео «${name}»?`,
    greet: "Что агент может сделать для вас?",
    subVideo: "Он сначала прочитает это видео и предложит план. Используйте @ для ссылок на другие видео или файлы.",
    sub: "Начните с описания желаемого результата. Работа выполняется агентом для программирования на вашем компьютере с вашей подпиской.",
    suggestions: "Попробуйте попросить",
    chipsVideo: [
      "Убери слова-паразиты из этой главы",
      "Дай каждой главе более короткий заголовок",
      "Найди повторяющиеся части, которые можно вырезать",
      "Приведи термины в соответствие с глоссарием",
    ],
    chips: [
      "Добавь субтитры к этому видео и переведи их на английский",
      "Найди слова-паразиты и длинные паузы, перечисли перед вырезанием",
      "Раздели этот выпуск на главы с заголовками",
      "Экспортируй двуязычный SRT и MP4 со встроенными субтитрами",
    ],
  },
  /** 产物卡（原型 home-session.jsx `SessionArtifactCard`、`SessionMoviePreview`、`SessionMessageArtifacts`）。 */
  output: {
    playVideo: (name: string) => `Воспроизвести видео «${name}»`,
    noThumbnail: "Нет миниатюры",
    sourceMissing: "Исходный файл не найден",
    openEditor: "Открыть редактор",
    openVideo: (name: string) => `Открыть видео «${name}»`,
    playHere: "Воспроизвести справа",
    previewHere: "Предпросмотр справа",
    reveal: "Показать в папке",
    messageOutputs: "Результаты сообщения",
  },
  /**
   * 线程里的视频卡与下载卡（产品设计 §3.2.2、§6.5；原型 home-session.jsx `SessionArtifactCard`、agent-cards.jsx `JobRow` / `DownloadCard`）。
   * 状态词与 Space 的视频状态同一套说法。
   */
  videoCard: {
    agentTranslating: 'Агент переводит по предложениям',
    sentenceTotal: (n: number) => pluralForm('ru', n, { one: `Всего ${n} предложение`, few: `Всего ${n} предложения`, many: `Всего ${n} предложений`, other: `Всего ${n} предложения` }),
    status: { translating: 'Идёт перевод', transcribing: "Расшифровка", queued: "В очереди", transcribed: "Расшифровано", failed: "Ошибка" },
    rows: "Работать с этим видео",
    retranscribe: "Расшифровать заново",
    translate: "Перевести",
    linkImport: "Импорт по ссылке",
    tail: { queued: "В очереди", done: "Готово", failed: "Ошибка", cancelled: "Отменено", interrupted: "Прервано", unknown: "Результат неизвестен" },
    elapsed: (clock: string) => `${clock} прошло`,
    recognized: (done: string, total: string | null) => (total ? `Распознано: ${done} / ${total}` : `Распознано: ${done}`),
    segments: (done: number, total: number | null) => total != null ? `Распознано: ${done} / ${total} ${pluralForm('ru', total, {one: "сегмент", few: "сегмента", many: "сегментов", other: "сегмента"})}` : `Распознано: ${done} ${pluralForm('ru', done, {one: "сегмент", few: "сегмента", many: "сегментов", other: "сегмента"})}`,
    translated: (done: number, total: number | null) => total != null ? `Переведено: ${done} / ${total} ${pluralForm('ru', total, {one: "строка", few: "строки", many: "строк", other: "строки"})}` : `Переведено: ${done} ${pluralForm('ru', done, {one: "строка", few: "строки", many: "строк", other: "строки"})}`,
    downloaded: (text: string) => `Скачано: ${text}`,
    documentWritten: "Расшифровка записана в видео",
    notFinished: "Этот шаг не завершён",
    retrying: "Автоматический повтор после ошибки",
    play: "Воспроизвести",
    reveal: "Показать в папке",
    cancel: "Отмена",
    retry: "Повторить попытку",
    warning: {
      'no-speech': "Речь не обнаружена",
      'no-audio-track': "У видео нет аудиодорожки",
      'diarization-unavailable': "Эта модель не различает говорящих",
    } as Record<string, string>,
    download: {
      queued: "Ожидание скачивания",
      running: "Скачивание видео",
      done: "Скачивание завершено",
      failed: "Скачивание не завершено",
      cancelled: "Скачивание отменено",
      interrupted: "Скачивание прервано",
      fallbackName: "Видео",
    },
    openFailed: (message: string) => `Не удалось открыть: ${message}`,
    retryFailed: (message: string) => `Не удалось повторить: ${message}`,
  },
  /** Home 起始页（产品设计 §3.2.1；原型 page-new.jsx Home、new-agent.jsx）。 */
  home: {
    title: "Какое видео вы хотите создать?",
    templates: "Шаблоны",
    quickStart: "Быстрый старт",
    blankVideo: "Новое пустое видео",
    blankVideoTip: "Без расшифровки и очереди — сразу в редактор",
    blankVideoCreated: "Пустое видео создано",
    blankVideoFailed: (message: string) => `Не удалось создать пустое видео: ${message}`,
    /** 没选项目时新建空白视频，先建一个这样命名的项目。 */
    blankVideoProject: "Пустое видео",
    removeTemplate: "Убрать шаблон",
    templateToken: (title: string) => `Шаблон: ${title}`,
    allTemplates: "Все шаблоны",
    searchTemplates: "Найти шаблоны",
    templateKind: "Тип",
    templateSource: "Источник",
    templateCategories: "Категории",
    viewTemplate: (title: string) => `Посмотреть шаблон: ${title}`,
    useExampleLabel: (title: string) => `Использовать запрос: ${title}`,
    useTemplateLabel: (title: string) => `Использовать шаблон: ${title}`,
    templatePicked: "Выбрано",
    exampleBadge: "Пример",
    templatePage: (page: number, pages: number, total: number) => `Страница ${page} из ${pages} · ${total} всего`,
    prevPage: "Предыдущая страница",
    nextPage: "Следующая страница",
    noTemplates: "Нет подходящих шаблонов. Попробуйте другое слово или категорию.",
    templatesEmpty: "В папке шаблонов пока нет шаблонов.",
    templatesLoading: "Загрузка шаблонов…",
    templatesFailed: (message: string) => `Не удалось прочитать папку шаблонов: ${message}`,
    retryTemplates: "Повторить попытку",
    templatesNote: "Встроенные шаблоны поставляются с приложением; добавленные вами в папку шаблонов отображаются как «Мои».",
    templatesSkipped: (count: number) => `Не удалось загрузить ${count} ${pluralForm('ru', count, {one: "шаблон", few: "шаблона", many: "шаблонов", other: "шаблона"})}`,
    showSkipped: "Показать причину",
    hideSkipped: "Скрыть",
    pickTemplateHint: "Выберите шаблон слева, чтобы увидеть здесь предпросмотр и запрос.",
    templatePrompt: "Запрос",
    templatePromptLoading: "Загрузка запроса…",
    templatePromptFailed: (message: string) => `Не удалось прочитать запрос: ${message}`,
    templateSay: "Попробуйте написать",
    templateFields: 'Нужно заполнить',
    templateSkills: (list: string) => `Подход: ${list}`,
    slotsLeft: (count: number, labels: string) =>
      `${pluralForm('ru', count, { one: `Осталось заполнить ${count} поле`, few: `Осталось заполнить ${count} поля`, many: `Осталось заполнить ${count} полей`, other: `Осталось заполнить ${count} поля` })}: ${labels} · Можно отправить и так — агент сначала спросит вас`,
    fillNextSlot: 'Заполнить следующее',
    templateBriefNote: "После выбора агент сначала уточнит тему, цель, аудиторию и материалы, затем начнёт создание.",
    templateAssets: "Материалы",
    templatePromptOnly: "Только запрос, без материалов",
    useTemplate: "Использовать этот шаблон",
    keepTemplate: "Продолжить с этим шаблоном",
    useExample: "Использовать этот запрос",
    promptPlaced: "Запрос заполнен",
    undo: "Отменить",
    playPreview: "Воспроизвести предпросмотр",
    pausePreview: "Приостановить предпросмотр",
    placeholder: "Опишите желаемое видео или перетащите материалы сюда…",
    templatePlaceholder: "О чём видео? Добавьте тему, аудиторию или требования…",
    localFiles: "Локальные файлы",
    addMedia: "Видео или аудио",
    addDocument: "PDF или документ",
    addImage: "Изображение",
    recentVideos: "Недавние видео",
    /** 选了最近的视频，原先挂着的视频或音频素材让出位置（一句话只对一条视频说）。 */
    recentReplaced: (title: string, removed: string) => `Теперь работаем с видео «${title}»; убрано видео «${removed}»`,
    removeMaterial: (name: string) => `Убрать материал: ${name}`,
    materialsFull: (max: number, rejected: number) => `За один раз можно добавить до ${max} ${pluralForm('ru', max, { one: 'материала', few: 'материалов', many: 'материалов', other: 'материала' })}; ${rejected} не добавлено`,
    notLocalFile: "Этого файла нет на компьютере, поэтому его нельзя передать агенту",
    thisComputer: "Этот компьютер",
    pickProject: "Выбрать проект",
    pickProjectLabel: (name: string | null) => `Выбрать проект: ${name ?? "Нет"}`,
    currentProject: "Текущий проект",
    newProject: "Новый проект",
    noProject: "Без проекта агент работает во временной папке",
    enableFailed: (message: string) => `Не удалось включить: ${message}`,
  },
  /**
   * 起始页「快捷开始」的四条（原型 model-newproject.js `STARTERS`）：处理已有视频或音频的常见事，点一下把这句话放进输入框。
   * 措辞不带「动画」「讲解」「图表」这类词，免得被当成某一类制作。`needs` 是提示里「再把什么拖进输入框」。
   */
  homeStarter: {
    sub: { title: "Добавить субтитры", needs: "видеоматериал", prompt: "Добавьте субтитры к этому видео." },
    trans: { title: "Расшифровать и перевести", needs: "видеоматериал", prompt: "Расшифруй это видео и переведи на китайский в виде двуязычных субтитров." },
    clean: {
      title: "Обрезать видео с говорящим",
      needs: "видеоматериал",
      prompt: "Расшифруй это видео и найди слова-паразиты, длинные паузы и повторные дубли. Покажи мне перед вырезанием.",
    },
    a2v: { title: "Видео из аудио", needs: "аудиофайл", prompt: "Преврати это аудио в видео с фоном, волной и субтитрами." },
    tip: (needs: string) => `Заполняет запрос. Затем перетащите ${needs} в поле сообщения`,
  },
  /** 模板分类的显示名（模板包规范 §3.2；键是协议的一部分）。认不出的键由 model/home-templates.ts 兜底按键名显示。 */
  templateCategory: {
    all: "Все",
    marketing: "Маркетинг",
    'product-launch': "Запуск продукта",
    explainer: "Объяснение",
    'news-data': "Новости и данные",
    editing: "Монтаж",
    'creative-short': "Творческое короткое видео",
    'motion-design': "Моушн-дизайн",
  },
  /** 两类模板（规范 §1.2）。 */
  templateKind: { all: "Все", scene: "Шаблоны сцен", example: "Примеры" },
  templateSource: { all: "Все источники", builtin: "Встроенные", user: "Мои", community: "Сообщество" },
  /** 模板自带素材的种类（规范 §3.4）。 */
  templateAsset: { image: "Изображение", svg: "SVG", audio: "Аудио", video: "Видео" },
  /** 模板的画幅与时长文案（原型 model-home-templates.js `spec`、`specLine`）。 */
  templateSpec: {
    allAuto: "Соотношение сторон и длительность автоматически",
    ratioAuto: "Соотношение сторон автоматически",
    lengthAuto: "Длительность автоматически",
    sceneDefault: (spec: string) => `${spec} по умолчанию; чтобы изменить, напишите об этом в сообщении`,
    exampleAuto: "Соотношение сторон и длительность автоматически; агент определит по содержимому",
  },
  /** 起始页的创建项目对话框（原型 new-agent.jsx `CreateProjectDialog`）。 */
  createProject: {
    title: "Создать проект",
    close: "Закрыть создание проекта",
    name: "Имя проекта",
    placeholder: "Назовите проект",
    location: "Сохранить в папке",
    preview: (path: string) => `Проект будет сохранён в ${path}`,
    cancel: "Отмена",
    create: "Создать",
    created: (name: string) => `Создан проект «${name}»`,
    failed: (message: string) => `Не удалось создать проект: ${message}`,
  },
  /** 任务种类的名字（原型 page-tasks.jsx `KIND`）。Agent 会话里的任务原型没有单列，叫「Agent 任务」。 */
  taskKind: {
    agent: "Задача агента",
    transcribe: "Расшифровать",
    synthesizeSpeech: "Синтезировать речь",
    generateImage: "Создать изображение",
    generateText: "Сгенерировать текст",
    export: "Экспортировать",
    pipeline: "Пайплайн",
    'pipeline-step': "Шаг конвейера",
    modelInstall: "Установить модель",
    modelTest: "Проверить модель",
    modelsMove: "Переместить папку моделей",
    toolInstall: "Установить инструмент",
    toolUpdate: "Обновить инструмент",
    fontDownload: "Скачать шрифт",
    voiceClone: "Клонировать голос",
    agentTranslate: "Перевести",
    legacyImport: "Импортировать прежние проекты",
  },
  /** Job 的阶段（`JobPhase`）：列表与胶囊念「识别中 · 45%」。 */
  jobPhase: {
    queued: "В очереди",
    starting: "Запуск",
    loading: "Загрузка модели",
    decoding: "Декодирование аудио",
    vad: "Обнаружение речи",
    transcribing: "Распознавание",
    aligning: "Выравнивание времени",
    diarizing: "Определение говорящих",
    finalizing: "Завершение",
    probing: "Чтение медиа",
    encoding: "Кодирование",
    downloading: "Скачивание",
    moving: "Перемещение",
    generating: "Генерация",
    validating: "Проверка",
    publishing: "Сохранение результатов",
    applying: "Запись в видео",
    done: "Готово",
  },
  /** 后台任务页、详情与侧栏。 */
  taskView: {
    queued: "В очереди",
    running: "Выполняется",
    awaitingApproval: "Нужно ваше одобрение",
    cancelled: "Отменено",
    failed: "Ошибка",
    completed: "Готово",
    interrupted: "Прервано",
    needsReconciliation: "Результат неизвестен",
    retrying: "Автоматический повтор после ошибки",
    costCharged: "Результат получен; оплата один раз",
    costCancelUnsupported: "Поставщик не поддерживает отмену; запрос может завершиться удалённо и быть оплачен",
    costUnknown: "Неизвестно, отправлен ли запрос; оплата могла быть списана",
    costPossible: "Возможно, оплата списана",
    chipAgent: "Агент",
    chipCli: "CLI",
    byAgent: "Сессия агента",
    byCli: "CLI",
    byApp: "Приложение",
    byNode: "Удалённый узел",
    local: "Этот компьютер",
    cloud: "Облако",
    node: "Удалённый узел",
    noProject: "Вне проекта",
    pageTitle: "Все задачи",
    activeSection: "Выполняется",
    historySection: "Готово",
    historyGroup: "История",
    emptyActive: "Нет выполняемых задач",
    emptyActiveBody: "Здесь появляются расшифровка, перевод и экспорт.",
    emptyHistory: "Завершённых задач пока нет",
    openConversation: "Открыть сессию",
    details: "Подробнее",
    cancel: "Отмена",
    stop: "Остановить",
    back: "Фоновые задачи",
    notFound: "Задача не найдена",
    notFoundBody: "Этой задачи больше нет в списке",
    cancelTask: "Отменить задачу",
    cancelExport: "Отменить экспорт",
    stopTask: "Остановить задачу",
    cancelExportHint: "Незавершённый файл удаляется; само видео не затрагивается. После начала сохранения остановить нельзя; сохранение завершится.",
    stopHint: "Агент остановится на текущем шаге; уже записанные файлы проекта не затрагиваются.",
    conversationHint: "Этот запуск одобрен в сессии агента; переписка и одобрения находятся в той сессии.",
    agentTaskHint: "Эта задача принадлежит сессии агента; переписка и одобрения находятся в той сессии.",
    cancelledBody: "Само видео не затрагивается.",
    interruptedBody: "Runtime остановился или перезапустился до завершения запуска. Он не возобновится; запустите заново при необходимости.",
    needsReconciliationBody: "Runtime перезапустился до ответа облачного запроса. Оплата могла быть списана; автоматически запрос не повторяется.",
    configHint: "Это проблема настройки; повторение того же действия не поможет. Добавьте недостающий компонент и запустите снова.",
    sourceSection: "Источник",
    imagesSection: "Изображения",
    outputsSection: "Результаты",
    factsSection: "Подробнее",
    reveal: "Показать в папке",
    open: "Открыть",
    copyPrompt: "Скопировать запрос",
    promptCopied: "Запрос скопирован",
    copyFailed: "Не удалось скопировать. Выделите текст и скопируйте вручную",
    documentWritten: "Расшифровка записана в видео",
    importedToVideo: "Импортировано в видео",
    imageName: (n: number) => `Изображение ${n}`,
    audioName: (n: number) => `Аудио ${n}`,
    videoName: (n: number) => `Экспорт ${n}`,
    fileName: (n: number) => `Файл ${n}`,
    entries: (n: number) => `${n} ${pluralForm('ru', n, {one: "запись", few: "записи", many: "записей", other: "записи"})}`,
    packageFiles: (n: number) => `Переносимый пакет · ${n} ${pluralForm('ru', n, {one: "файл", few: "файла", many: "файлов", other: "файла"})}`,
    projectClips: (n: number) => `Проект · ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    documentName: "Расшифровка",
    stopFailed: (message: string) => `Не удалось остановить: ${message}`,
    cancelFailed: (message: string) => `Не удалось отменить: ${message}`,
    /** 对账（`jobs.reconcile`）：重启后结果不明、中断或没有写进视频的任务，由用户决定。 */
    reconcileRetry: "Повторить попытку",
    reconcileDiscard: "Отбросить результат",
    reconcileApply: "Записать в видео снова",
    reconcileRetryHint: (charges: boolean): string =>
      charges ? "Повторно вызывает поставщика; возможна повторная оплата." : "Снова ставит ту же задачу в очередь и выполняет с начала.",
    reconcileDiscardHint: "Отмечено как отменённое; уже списанная оплата не возвращается.",
    reconcileApplyHint: "Результат сохранён: он будет проверен снова и записан в видео. Сначала откройте это видео.",
    reconcileFailed: (message: string) => `Не удалось обработать: ${message}`,
    openFailed: (message: string) => `Не удалось открыть: ${message}`,
    remedyInstall: "Установить компоненты",
    remedyCloud: "Настроить облачные модели",
    remedyDefault: "Выбрать модели по умолчанию",
    remedyNode: "Посмотреть удалённые узлы",
    remedyAgent: "Открыть настройки агента",
  },
  /** 任务胶囊与悬停卡（原型 task-pill.jsx、model-task-pill.js）。 */
  taskPill: {
    count: (n: number) => `${n} ${pluralForm('ru', n, {one: "фоновая задача", few: "фоновые задачи", many: "фоновых задач", other: "фоновой задачи"})}`,
    all: "Все задачи",
    more: (n: number) => `Ещё ${n} ${pluralForm('ru', n, {one: "задача", few: "задачи", many: "задач", other: "задачи"})} · Все задачи в фоновых задачах`,
    mine: "Это видео",
    justStarted: "Только что началось",
    startedAt: (ago: string) => `Началось ${ago}`,
  },
  /**
   * 功能区的「项目文件」标签（原型 home-workspace.jsx `WorkspaceFiles` 的 `__browse__` 分支）。
   * 原型没有的状态（读取中、读不了、目录为空、只列出一部分）按同样口吻补上。
   */
  projectFiles: {
    region: "Файлы проекта",
    /** 不属于项目的会话：根目录是它自己的工作目录。 */
    scratchRoot: "Папка сессии",
    searchLabel: "Найти файлы проекта",
    searchPlaceholder: "Найти файлы или видео",
    listLabel: (where: string) => `Файлы в папке «${where}»`,
    resultsLabel: "Результаты поиска",
    breadcrumbs: "Путь к папке",
    loading: "Загрузка файлов…",
    emptyFolder: "Папка пуста",
    noMatch: "Нет подходящих файлов",
    noMatchHint: "Поиск по именам файлов; скрытые файлы и папки зависимостей пропускаются.",
    failed: "Не удалось прочитать список файлов",
    retry: "Повторить попытку",
    truncatedList: (count: number) => `Слишком много файлов; показаны только первые ${count}.`,
    truncatedSearch: "Слишком много совпадений; показана часть. Уточните поисковое слово.",
    inRoot: "Корень проекта",
  },
  /**
   * 功能区的网页标签（原型 home-browser.jsx `WorkspaceBrowser`）。原型用 iframe；这里是宿主的独立网页视图（架构设计 §12.10），
   * 所以底部那句改成说明隔离；被拒绝的地址（本机地址、非 http/https）、网页进程退出与「这个环境不能内嵌网页」是原型没有的状态。
   */
  webTab: {
    back: "Назад",
    forward: "Вперёд",
    stop: "Остановить загрузку",
    reload: "Обновить страницу",
    address: "Веб-адрес",
    placeholder: "Найти или ввести URL",
    go: "Перейти",
    menu: "Параметры страницы",
    copy: "Скопировать адрес страницы",
    copied: "Адрес страницы скопирован",
    copyFailed: "Не удалось скопировать адрес страницы",
    external: "Открыть во внешнем браузере",
    zoomIn: "Увеличить масштаб",
    zoomOut: "Уменьшить масштаб",
    zoomReset: "Сбросить масштаб до 100 %",
    invalid: "Введите URL http / https или поисковый запрос. URL не может содержать имя пользователя или пароль.",
    loading: "Загрузка страницы…",
    slow: "Страница загружается медленно. Повторите попытку или откройте во внешнем браузере.",
    startTitle: "Найти или открыть веб-страницу",
    startBody: "Введите URL или запрос для поиска здесь, не прерывая разговор.",
    enterUrl: "Ввести URL",
    stoppedTitle: "Загрузка остановлена",
    failedTitle: "Не удалось загрузить страницу",
    failedDetail: (description: string, code: number) => `${description} (${code})`,
    crashedTitle: "Страница неожиданно завершила работу",
    crashedBody: "Попробуйте обновить её.",
    retry: "Перезагрузить",
    blockedTitle: {
      loopback: "Локальные адреса здесь не открываются",
      scheme: "Можно открыть только URL http / https",
      'app-origin': "Страницы самого BaoCut нельзя открыть в веб-вкладке",
      invalid: "Некорректный URL",
    },
    blockedBody: {
      loopback: "Из соображений безопасности встроенные страницы не обращаются к локальным сервисам (localhost, 127.0.0.1 и другим). При необходимости откройте в браузере.",
      scheme: "Другие схемы (файлы, ссылки приложений и другие) не открываются во встроенных страницах.",
      'app-origin': "Страницы самого приложения не открываются в веб-вкладке.",
      invalid: "Проверьте написание URL.",
    },
    backToPage: "Вернуться на страницу",
    footer: "Страницы открываются в отдельной среде без доступа к BaoCut и локальным сервисам; входы отделены от системного браузера.",
    externalShort: "Открыть снаружи",
    unsupportedTitle: "Веб-страницы нельзя встроить здесь",
    unsupportedBody: "Настольное приложение BaoCut умеет открывать веб напрямую; пока откройте в браузере.",
    openInBrowser: "Открыть в браузере",
    toolsTitle: 'Инструменты',
    newPageTitle: 'Новая веб-страница',
    newPageBody: 'Создать HTML-файл в проекте и открыть предпросмотр',
    browseFilesTitle: 'Файлы проекта',
    browseFilesBody: 'Показать папку проекта в этой вкладке',
    newPageFileName: 'Новая страница',
    newPageHint: 'Напишите страницу здесь или попросите агента её изменить.',
    newPageFailed: 'Не удалось создать веб-страницу',
  },
  /** 时间线的剪贴板、右键菜单与带撤销的提示（原型 editor-keys.jsx、timeline-menu.jsx；原型说「元素」，这里是「片段」）。 */
  timelineEdit: {
    undo: "Отменить",
    /** `verb` 是本目录里的动作名（`copy`、`cutItem`、`remove`、`duplicate`）。 */
    pick: (verb: string) => `Выберите клипы для действия: ${verb.toLowerCase()}`,
    copied: (n: number) => `Скопировано ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    cut: (n: number) => `Вырезано ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    pasted: (n: number) => `Вставлено ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    duplicated: (n: number) => `Созданы копии: ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    deleted: (n: number) => `Удалено ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    clipboardEmpty: (mod: string) => `Буфер обмена пуст · Сначала нажмите ${mod}C, чтобы скопировать клип`,
    otherVideo: "Клипы в буфере взяты из другого видео · Их можно вставить только в то видео",
    selectedAtPlayhead: (n: number) => `Выбрано ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    nothingAtPlayhead: "У курсора воспроизведения нет клипов",
    labelCut: "Вырезать клипы",
    labelPaste: "Вставить клипы",
    labelDuplicate: "Создать копии клипов",
    labelDelete: "Удалить клипы",
    labelSplit: "Разделить клип",
    labelNudge: "Сдвинуть время клипа",
    labelDisable: "Отключить клип",
    labelEnable: "Включить клип",
    menuLabel: (name: string) => `Клип «${name}»`,
    split: "Разделить у курсора воспроизведения",
    splitUnavailable: "Курсор воспроизведения вне этого клипа",
    copy: "Скопировать",
    cutItem: "Вырезать",
    paste: "Вставить",
    duplicate: "Создать копию",
    disable: "Отключить этот клип",
    enable: "Включить этот клип",
    disableHint: "Остаётся на таймлайне · Пропускается в кадре и экспорте",
    enableHint: "Снова в кадре и экспорте",
    remove: "Удалить",
  },
  /** 走带的缩放菜单（原型 data.js `zoomMenu` 与 timeline.jsx 的 Transport）。 */
  timelineZoom: {
    menu: "Масштабирование",
    tip: "Параметры масштаба",
    in: "Увеличить масштаб",
    out: "Уменьшить масштаб",
    '100': "100%",
    fit: "Вместить в окно",
    fitClip: "Вместить текущий клип",
    playhead: "Масштаб к курсору воспроизведения",
    fitSelection: "Вместить выбранное",
    noClip: "Переместите курсор воспроизведения внутрь клипа",
    noSelection: "Сначала выберите клипы на таймлайне",
  },
  /**
   * 编辑器快捷键清单（原型 editor-keys.jsx 的 SHEET）：只列这里真有的键。
   * 键里的 ⌘ 在 Windows 与 Linux 上换成 Ctrl+（见 shortcut-sheet）。
   */
  shortcutSheet: {
    title: "Сочетания клавиш",
    done: "Понятно",
    hint: "Когда курсор в текстовом поле, эти клавиши действуют в нём.",
    rows: [
      ["Удалить выбранное (промежутки, пустые на всех дорожках, закрываются)", "Удалить"],
      ["Удалить выбранный отрезок со всех дорожек (всё, что дальше, сдвигается вперёд)", "⇧Удалить"],
      ["Снять выбор / закрыть всплывающее окно", "Esc"],
      ["Воспроизведение / пауза", "Space / K"],
      ["Отмена / повтор", "⌘Z / ⇧⌘Z"],
      ["Копирование / вырезание / вставка", "⌘C / ⌘X / ⌘V"],
      ["Создать копию", "⌘D"],
      ["Выбрать все клипы у курсора воспроизведения", "⌘A"],
      ["Курсор назад / вперёд на кадр (при воспроизведении: 5 секунд)", "← / →"],
      ["Курсор назад / вперёд на секунду", "⇧← / ⇧→"],
      ["Назад / вперёд на 10 секунд", "J / L"],
      ["При воспроизведении: громкость +10 / −10 (увеличение включает звук)", "↑ / ↓"],
      ["Выключить / включить звук", "M"],
      ["Сдвинуть выбранный элемент на холсте (сначала нажмите холст)", "Стрелки (⇧ сдвигает на 5 %, ⌥↑ / ⌥↓ на 0,1 %)"],
      ["Сдвинуть время выбранного клипа (⇧ по одной секунде)", "⌥← / ⌥→"],
      ["Масштаб таймлайна увеличить / уменьшить / 100 %", "⌘= / ⌘− / ⌘0"],
      ["Таймлайн: вместить окно / текущий клип / курсор / выбор", "⌥⌘1 / ⌥⌘2 / ⌥⌘3 / ⌥⌘4"],
      ["Разделить у курсора воспроизведения", "S / ⌘B"],
      ["Полноэкранное воспроизведение / выйти из полного экрана (когда на холсте ничего не выбрано)", "F"],
      ["Выбранный клип на передний / задний план", "F / B"],
      ["Выбранный клип на уровень вперёд / назад", "⌘↑ / ⌘↓"],
      ["Перейти в начало / конец", "Home / End"],
      ["Открыть список сочетаний редактора", "?"],
    ] as [string, string][],
  },
  /** Home 功能区：标签条、加号菜单、视图控件、会话列与单文件标签（原型 home-workspace.jsx、shell.jsx）。 */
  workspace: {
    tablist: "Вкладки рабочего пространства",
    tablistHint: "Перетащите вкладки для изменения порядка или нажмите Alt + Shift + Left/Right Arrow.",
    close: (name: string) => `Закрыть вкладку «${name}»`,
    add: "Открыть новую вкладку",
    dragging: (name: string) => `Перетаскивание «${name}». Отпустите для размещения, Esc — отмена`,
    moved: (name: string) => `Перемещено «${name}»`,
    dragCancelled: "Перетаскивание отменено",
    viewGroup: "Вид рабочего пространства",
    resize: "Изменить ширину колонки сессии",
    conversation: "Сессия",
    /** 窄窗口里会话标签的提示与读屏名称（产品设计 §3.3）：`status` 是进行中 / 等待批准，没有时省掉。 */
    conversationTabTip: (title: string, status: string | null) =>
      `Сессия «${title}»${status ? ` · ${status}` : ""} · Закреплена первой; нельзя переместить или закрыть`,
    conversationTabLabel: (title: string, status: string | null) => `Сессия «${title}»${status ? `, ${status}` : ""}, закреплена первой`,
    opening: "Открытие видео…",
    showInSpace: "Показать в Space",
    reveal: "Показать в папке",
    fileMissing: "Файл перемещён или удалён",
    filesNoConversation: "После создания сессии здесь появятся файлы её папки.",
  },
  /** 舞台上的对象：选中框、把手、旋转钮、多选统一框与就地改字（原型 stage-objects.jsx、stage-marquee.jsx）。 */
  stage: {
    label: "Объекты на холсте",
    textEditor: "Редактировать текст",
    move: "Переместить",
    resize: "Изменить размер",
    scale: "Масштабировать",
    rotate: "Повернуть",
    rotateReset: "Сбросить поворот",
    groupMove: "Переместить вместе",
    groupScale: "Масштабировать вместе",
    nudge: "Сдвинуть положение",
    edgeHeightTip: "Перетащите для изменения высоты · ⌥ от центра",
    edgeWidthTip: "Перетащите для изменения ширины · ⌥ от центра",
    cornerFreeTip: "Перетащите для изменения размера · ⇧ свободные пропорции, ⌥ от центра",
    cornerScaleTip: "Масштабировать пропорционально · ⌥ от центра",
    rotateTip: "Перетащите для поворота · Шаг 15°, ⇧ свободный поворот · Двойное нажатие сбрасывает",
    groupCornerTip: "Масштабировать всё пропорционально",
    picked: (n: number) => `${n} выделено`,
    degrees: (n: number) => `${n}°`,
  },
  /**
   * 四项服务的目录与起停用词（原型 model-services.js `SERVICES`）；远端算力沿用「共享」。顺序就是侧栏与总览的顺序。
   * 模型接口服务在原型里是 Web 服务页里的一节（page-services-api.jsx `ApiSection`）；Runtime 把它做成独立的服务（自己的端口、
   * 令牌与开关，架构设计 §4.8），这里排在 Web 服务后面。
   */
  service: {
    mcp: {
      name: "Сервис MCP",
      scope: "Только этот компьютер",
      desc: "Позволяет другим ИИ-приложениям читать видео и вызывать инструменты BaoCut",
      start: "Запустить сервис",
      stop: "Остановить сервис",
      starting: "Запуск…",
      stopping: "Остановка…",
    },
    remote: {
      name: "Удалённые вычисления",
      scope: "Локальная сеть",
      desc: "Предоставляет вычисления этого Mac другим компьютерам в локальной сети",
      start: "Начать общий доступ",
      stop: "Остановить общий доступ",
      starting: "Запуск…",
      stopping: "Остановка…",
    },
    web: {
      name: "Веб-сервис",
      scope: "Только этот компьютер",
      desc: "Откройте BaoCut Web в браузере для редактирования тех же видео",
      start: "Запустить сервис",
      stop: "Остановить сервис",
      starting: "Запуск…",
      stopping: "Остановка…",
    },
    'model-api': {
      name: "API моделей",
      scope: "Только этот компьютер",
      desc: "Позволяет инструментам с OpenAI API использовать модели BaoCut для расшифровки, озвучки, создания изображений и текста",
      start: "Запустить сервис",
      stop: "Остановить сервис",
      starting: "Запуск…",
      stopping: "Остановка…",
    },
  },
  /** 服务的状态词（原型 model-services.js `stateLabel`）；`unavailable` 是这个版本的 Runtime 没有提供的服务。 */
  serviceState: {
    share: { starting: "Запуск общего доступа…", stopping: "Остановка общего доступа…", error: "Общий доступ неожиданно остановлен", on: "Общий доступ включён", off: "Общий доступ выключен" },
    service: { starting: "Запуск…", stopping: "Остановка…", error: "Не удалось запустить", on: "Работает", off: "Не начато" },
    unavailable: "Пока недоступно",
  },
  servicesPage: {
    title: "Сервисы",
    overview: "Обзор сервисов",
    lede: "Сервисы BaoCut на этом Mac для подключения других приложений и устройств. По умолчанию все выключены и останавливаются при выходе из BaoCut.",
    allOff: "Нет работающих сервисов",
    errors: (n: number) => `${n} ${pluralForm('ru', n, {one: "ошибка", few: "ошибки", many: "ошибок", other: "ошибки"})}`,
    running: (n: number) => `${n} выполняется`,
    open: (name: string) => `Открыть ${name}`,
    /** `verb` 是服务自己的启动词（`service.*.start`）。 */
    restart: (verb: string) => `Повторить: ${verb}`,
    railAlert: (text: string) => `Сервисы, ${text}`,
    railApprovals: (n: number) => `Сервисы, ${n} ${pluralForm('ru', n, {one: "запрос", few: "запроса", many: "запросов", other: "запроса"})} — ожидается ваше одобрение`,
    loading: "Загрузка статуса…",
    disconnected: "Нет подключения к BaoCut Runtime",
    failed: (message: string) => `Не получилось: ${message}`,
    /** Runtime 列出了、但这个版本没有提供的服务（`available: false`）：总览行与详情页说清楚为什么不能起停。 */
    unavailableDetail: "Эта версия BaoCut Runtime пока не предоставляет этот сервис",
    unavailableTitle: (name: string) => `${name} пока недоступен`,
    notRunning: "Сервис не работает. Сначала запустите его",
    mcpRelated: "Хотите научить Claude Code или Codex в терминале работать с BaoCut? Установите для них Skill BaoCut — сервис не нужен. См.",
    mcpRelatedLink: "Настройки › Skills",
  },
  /** BaoCut Runtime 卡（原服务页的一张卡，现在给设置 › 诊断复用）。 */
  runtimeCard: {
    name: "BaoCut Runtime",
    version: "Версия",
    versionValue: (runtime: string, protocol: number | string) => `${runtime} (протокол ${protocol})`,
    pid: "Процесс",
    startedAt: "Начало",
    home: "Папка данных",
  },
  /** 远端算力页（原型 page-shell.jsx RemotePage）。这个版本只能共享转录，其他几类任务画成禁用并说明原因。 */
  remote: {
    title: "Удалённые вычисления",
    tabsLabel: "Разделы удалённых вычислений",
    tabShare: "Общий доступ к этому Mac",
    tabNodes: "Использовать другие компьютеры",
    ledeShare: {
      before: "Предоставьте расшифровку этого Mac другим компьютерам в локальной сети. ",
      strong: "Файлы остаются в локальной сети",
      after: "; возвращаются только результаты — без серверов.",
    },
    ledeNodes: {
      before: "Передайте расшифровку более быстрому компьютеру в локальной сети. ",
      strong: "Файлы остаются в локальной сети",
      after: "; обратно приходят только результаты — без серверов.",
    },

    cardOn: "Общий доступ к этому Mac включён",
    cardOff: "Общий доступ выключен",
    subOff: "Другие устройства не видят этот Mac.",
    subErrorFallback: "Сервис узла не принимает подключения.",
    errorFix: "Закройте программу, занимающую порт, и снова включите общий доступ — либо остановите его, если он больше не нужен.",
    foot: "Пока общий доступ включён, BaoCut возобновляет его при следующем открытии.",
    footRight: "Общий доступ останавливается при выходе из BaoCut.",
    privacy: "Входные данные задачи передаются только по локальной сети, обратно приходят лишь результаты; после задачи на этом Mac ничего не остаётся.",
    offHint: "После запуска общего доступа появится шестизначный код сопряжения; введите на другом устройстве для подключения.",
    started: "Общий доступ к этому Mac запущен",
    stopped: "Общий доступ остановлен",

    nodeName: "Имя узла",
    address: "Адрес",
    noAddress: "Адрес локальной сети недоступен",
    pairingTitle: "Код сопряжения",
    pairingHint: (left: string) => `Введите код на другом устройстве. Истекает через ${left}.`,
    pairingLocked: (until: string) => `Слишком много неверных попыток; сопряжение заблокировано до ${until}. Создайте новый код для немедленной разблокировки.`,
    pairingNone:
      "Сейчас кода сопряжения нет. После однократного использования, истечения срока или повторного открытия BaoCut нужен новый код. Сопряжённые устройства не затрагиваются.",
    regenerate: "Создать заново",
    generate: "Создать код сопряжения",
    regenerated: "Новый код сопряжения создан",

    tasksTitle: "Задачи для других компьютеров",
    taskSummary: (on: number, total: number) => `Предоставляется ${on} / ${total} ${pluralForm('ru', total, {one: "тип задач", few: "типа задач", many: "типов задач", other: "типа задач"})}`,
    taskUnsupported: "Эта версия пока не предоставляет такой тип задач",
    taskNoModel: (noun: string) => `На этом Mac нет доступной модели: ${noun}; такие задачи с других компьютеров завершатся ошибкой`,
    taskSwitch: (name: string) => `Предлагать ${name.toLowerCase()}`,
    taskOn: (name: string) => `Теперь предоставляется ${name.toLowerCase()}`,
    taskOff: (name: string) => `Больше не предоставляется ${name.toLowerCase()} · Принятые задачи завершатся`,

    status: "Статус",
    idle: "Свободен",
    jobs: (running: number, queued: number) =>
      [running ? `${running} выполняется` : "", queued ? `${queued} в очереди` : ""].filter(Boolean).join(" · "),

    clientsTitle: "Сопряжённые устройства",
    clientsEmpty: "С этим Mac пока нет сопряжённых устройств.",
    clientMeta: (paired: string, seen: string | null) => (seen ? `Сопряжено ${paired} · Последнее подключение ${seen}` : `Сопряжено ${paired} · Ещё не подключалось`),
    revoke: "Отозвать",
    revokeLabel: (name: string) => `Отозвать разрешение «${name}»`,
    revokeTitle: (name: string) => `Отозвать разрешение «${name}»?`,
    revokeBody: "Токен сразу перестанет работать, а задачи, отправленные на этот Mac, будут отменены. Для повторного использования нужно снова ввести код сопряжения.",
    revoked: (name: string) => `Отозвано устройство «${name}»`,

    paired: "Сопряжено",
    pairedEmptyTitle: "Сопряжённых узлов пока нет",
    pairedEmptyBody: "Включите «Общий доступ к этому Mac» на другом компьютере, затем выполните сопряжение здесь.",
    nearby: "Рядом",
    nearbyIdle: "Нажмите «Найти компьютеры рядом», чтобы увидеть компьютеры с общим доступом в локальной сети.",
    nearbyNone:
      "Компьютеры с общим доступом не найдены. Убедитесь, что там включён «Общий доступ к этому Mac» и оба компьютера в одной локальной сети, либо добавьте по адресу.",
    search: "Найти компьютеры рядом",
    searching: "Поиск…",
    addByAddress: "Добавить по адресу…",
    pair: "Выполнить сопряжение",
    pairLabel: (name: string) => `Выполнить сопряжение с устройством «${name}»`,
    online: "В сети",
    offline: "Не в сети",
    versionMismatch: "Несовместимая версия",
    unpaired: "Сопряжение больше недействительно",
    checking: "Проверка…",
    more: (name: string) => `Другие действия для «${name}»`,
    copyAddress: "Копировать адрес",
    copied: (address: string) => `Скопировано: ${address}`,
    copyFailed: "Не удалось скопировать. Выделите текст и скопируйте",
    unpair: "Удалить сопряжение",
    unpairTitle: (name: string) => `Удалить сопряжение с устройством «${name}»?`,
    unpairBody: "Этот компьютер больше не появится в списке моделей расшифровки. Сопряжение можно повторить в любой момент.",
    unpairDone: "Сопряжение удалено",
    /** 节点卡上「为什么用不了」：按 `PairedNode.problem` 拼（没有诊断方法，不叫「诊断」）。 */
    problem: {
      unreachable: "Компьютер недоступен. Убедитесь, что на нём открыт BaoCut с «Общим доступом к этому Mac» и оба компьютера в одной локальной сети.",
      version: "Версии BaoCut на компьютерах несовместимы. Обновите обе до последней версии.",
      unpaired: "Сопряжение больше недействительно: другая сторона отозвала этот компьютер либо адрес использует другой компьютер. Удалите сопряжение и выполните снова.",
    },
    transcribeOff: "Расшифровка не предоставляется",
    transcribeModels: (n: number) => n ? `Расшифровка · ${n} ${pluralForm('ru', n, {one: "модель", few: "модели", many: "моделей", other: "модели"})}` : 'Расшифровка',

    pairTitle: (name: string) => `Выполнить сопряжение с устройством «${name}»`,
    addTitle: "Добавить по адресу",
    pairBody: "Найдите шестизначный код в «Общем доступе к этому Mac» на том компьютере и введите здесь.",
    addressLabel: "Адрес",
    addressPlaceholder: "192.168.1.31:47610",
    addressHint: (port: number) => `Имя хоста или IP, при необходимости с портом; если порт не указан, используется ${port}.`,
    codeLabel: "Код сопряжения",
    codePlaceholder: "481 924",
    cancel: "Отмена",
    pairing: "Сопряжение…",
    pairedToast: "Сопряжено · Теперь есть в списке моделей расшифровки",
    addressEmpty: "Введите адрес того компьютера",
    addressInvalid: "Неверный формат адреса: используйте 192.168.1.31 или 192.168.1.31:47610",
    portInvalid: "Порт должен быть числом от 1 до 65535",
    codeInvalid: "Код сопряжения состоит из 6 цифр",
    pairErrors: {
      'pairing-code-invalid': "Код сопряжения неверен или истёк. Попросите создать новый и повторите попытку.",
      'pairing-locked': "Слишком много неверных попыток; тот компьютер временно заблокировал сопряжение. Попросите нажать «Создать заново» для разблокировки.",
      version: "Версии BaoCut на компьютерах несовместимы. Сначала обновите обе до последней версии.",
      'source-not-allowed': "Тот компьютер не принимает подключения с адреса этого компьютера.",
      lost: "Компьютер недоступен. Проверьте адрес и порт и убедитесь, что там включён «Общий доступ к этому Mac».",
    },
    pairFailed: (message: string) => `Сопряжение не удалось: ${message}`,
  },
  /** 「提供给其他电脑的任务」的名字（键见 `REMOTE_TASK_COPY`）。`noun` 是缺模型提示里的那类模型。 */
  remoteTask: {
    asr: { name: "Расшифровка", noun: "модель расшифровки" },
    tts: { name: "Озвучка", noun: "модель озвучки" },
    image: { name: "Генерация изображений", noun: "модель изображений" },
    separate: { name: "Разделение вокала", noun: "модель разделения" },
    download: { name: "Скачивание видео", noun: null },
    export: { name: "Экспорт видео", noun: null },
  },
  /** 帮助中心（原型 help-center.jsx）：外框、分类、搜索、快速上手、快捷键页与入口。 */
  help: {
    title: "Центр справки",
    subtitle: "Находите ответы в любой момент и приступайте к работе",
    close: "Закрыть справку",
    navLabel: "Категории справки",
    navTitle: "Работа с BaoCut",
    navNote: ["Читайте только нужное.", "Закройте справку и вернитесь к работе."] as [string, string],
    sections: { start: "Быстрый старт", guide: "Руководства", keys: "Сочетания клавиш", faq: "Частые вопросы" },
    searchLabel: "Найти в справке",
    searchPlaceholder: "Найдите нужное действие, например стиль субтитров",
    results: "Результаты поиска",
    found: (n: number) => `Найдено: ${n} ${pluralForm('ru', n, {one: "руководство", few: "руководства", many: "руководств", other: "руководства"})}`,
    emptyTitle: "Нет подходящих руководств",
    emptyBody: "Попробуйте «субтитры», «материалы», «агент» или «соотношение сторон» либо начните с быстрого старта.",
    emptyAction: "Посмотреть быстрый старт",
    welcomeEyebrow: "Впервые здесь? Начните отсюда",
    welcomeTitle: "Создать первое видео с субтитрами",
    welcomeBody: (steps: number) => `От клипа до экспорта с субтитрами за ${steps} ${pluralForm('ru', steps, {one: "шаг", few: "шага", many: "шагов", other: "шага"})}.`,
    welcomeAction: "Начать руководство для первого запуска",
    welcomeDuration: (steps: number, minutes: number) => `${steps} ${pluralForm('ru', steps, {one: "шаг", few: "шага", many: "шагов", other: "шага"})} · Около ${minutes} мин чтения`,
    pathLabel: (steps: number) => `Первый запуск за ${steps} ${pluralForm('ru', steps, {one: "шаг", few: "шага", many: "шагов", other: "шага"})}`,
    pathMinutes: (minutes: number) => `${minutes} мин чтения`,
    moreTitle: "Также может пригодиться",
    allGuides: "Все руководства",
    keysHintLead: "Не можете найти действие?",
    keysHintLink: "Посмотреть сочетания клавиш",
    keysHintNote: "Открывает список в редакторе",
    keysTitle: "Меньше нажатий, немного быстрее",
    keysIntro: "Эти сочетания работают в редакторе. При вводе текста клавиши сначала действуют в текстовом поле.",
    keysPlatform: "Стиль сочетаний",
    mac: "macOS",
    other: "Windows / Linux",
    guideTitle: "Найдите нужное действие здесь",
    guideIntro: "Каждое руководство посвящено одному действию — можно сразу вернуться к видео и попробовать.",
    faqTitle: "Есть проблема? Начните здесь",
    faqIntro: "Начните с частых причин и проверяйте по шагам.",
    minutes: (minutes: number) => `${minutes} мин`,
    readTime: (minutes: number) => `Около ${minutes} мин чтения`,
    backToResults: "Вернуться к результатам поиска",
    backTo: (section: string) => `Вернуться к ${section}`,
    pickVideo: "Выбрать видео",
    pickVideoNote: "Сначала откройте видео, затем следуйте руководству.",
    ctaNote: "Открывает функцию; дальше действуйте самостоятельно.",
    backToVideo: "Вернуться к видео",
    backNote: "Закройте справку и попробуйте в своём видео.",
    next: (title: string) => `Читать дальше: ${title}`,
    footer: "Встроенные руководства · Доступны офлайн",
    entry: "Центр справки · F1",
    entryLabel: "Центр справки",
    settingsEntry: "Справка",
  },
  /** 编辑器预览的监听音量与全屏（快捷键 ↑/↓、M、F；原型 editor-keys.jsx 借全屏播放器的键）。只是这个窗口听到、看到的，不进视频。 */
  previewKeys: {
    volume: (volume: number) => `Громкость предпросмотра ${volume}`,
    muted: "Звук предпросмотра выключен",
    unmuted: (volume: number) => `Звук предпросмотра включён · Громкость ${volume}`,
    fullscreenFailed: "Не удалось открыть полноэкранный предпросмотр",
  },
  /** 画布浮动工具条与多选页（原型 stage-toolbar.jsx、stage-toolbar-menu.jsx、panel-elements.jsx MultiSelectPanel）。 */
  stageToolbar: {
    label: "Панель клипа",
    more: "Ещё",
    back: "Назад",
    unavailable: "Пока недоступно",
    textColor: "Цвет текста",
    fillColor: "Цвет заливки",
    strokeColor: "Цвет обводки",
    strokeWidth: "Насыщенность",
    muted: "Без звука",
    firstGeometry: (name: string) => `Геометрия доступна только для чтения и показывает первый клип «${name}»; выберите только его для изменения значений.`,
    align: "Выровнять",
    alignTo: "Относительно",
    toSelection: "Выбранное",
    toCanvas: "Холст",
    alignLeft: "Выровнять по левому краю",
    alignHCenter: "По центру горизонтально",
    alignRight: "Выровнять по правому краю",
    alignTop: "По верхнему краю",
    alignVCenter: "По центру вертикально",
    alignBottom: "По нижнему краю",
    distribute: "Распределить",
    distributeX: "Распределить горизонтально",
    distributeY: "Распределить вертикально",
    alignNeed: "Для выравнивания нужно минимум два перемещаемых клипа или один при выравнивании по холсту.",
    distributeNeed: "Для равномерного распределения нужно минимум три перемещаемых клипа.",
    labelAlign: "Выровнять клипы",
    labelDistribute: "Распределить клипы",
    aligned: (n: number) => `Выровнено: ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    distributed: (n: number) => `Распределено: ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    inPlace: "Уже на месте; перемещать нечего",
    duplicate: "Создать копию",
    copy: "Скопировать",
    removeAll: (n: number) => n === 1 ? 'Удалить этот клип' : `Удалить ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}`,
    skipped: (n: number) => `Не участвуют в выравнивании и распределении: ${n} ${pluralForm('ru', n, {one: "клип", few: "клипа", many: "клипов", other: "клипа"})}. Основное видео, аудио и субтитры не размещаются отдельно на холсте, а заблокированные клипы не перемещаются.`,
    dragNote: "Перетащите один из них на холсте для перемещения вместе. Выберите один клип для изменения его свойств.",
    hint: "Выравнивание, распределение, копирование и удаление каждое считаются одним шагом отмены.",
    labelFlip: "Отразить",
    labelFit: "Подогнать под холст",
    labelFill: "Заполнить холст",
  },
  /** @ 补全分组（设计稿 model-agent.js `mentionItems` 的本视频一组）：打开的视频里的章节与说话人在前。 */
  mentionGroups: {
    video: "Это видео",
    files: "Видео и файлы",
  },
};
