import { pluralForm } from '@baocut/protocol';
import { MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_PER_MESSAGE } from '@baocut/protocol';
import type { CopyMessages } from './copy.ts';




export const pl: CopyMessages = {
  /** 打开系统的文件管理器并选中目标。所有平台同一个说法，不写某个平台专有的文件管理器名字（docs/glossary.md）。 */
  reveal: "Pokaż w folderze",
  untitled: "Nowa sesja",
  /** 用户消息上方已发送的图片（原型 agent-thread.jsx `UserMsg`）。 */
  sentAttachments: "Wysłane pliki",
  /** 任务在跑时切换访问模式的提示（原型 model-agent.js `modeToast` 的运行中分支）。 */
  accessModeToast: (label: string) => `Następna tura użyje trybu „${label}”. Bieżąca tura zachowa obecny tryb dostępu.`,
  /** composer 脚注（原型 model-agent.js `composerFoot`）：在哪儿跑、用谁的订阅（空串表示没有账号名）、这一档会不会问你、快捷键。 */
  composerFoot: (name: string, account: string, foot: string) =>
    `Działa przez ${name} na tym komputerze, ${account ? `z Twoją subskrypcją ${account}` : "z Twoją subskrypcją"}. ${foot} Enter wysyła, Shift+Enter dodaje wiersz, @ tworzy odwołanie, / otwiera polecenia.`,

  /**
   * 访问模式（架构设计 §3.12，原型 data.js `agent.modes`）。原型只画四档；「先给方案」是协议里独立的一档，
   * 输入框下拉只在会话已经处在这一档时列出它（例如经 CLI 切过去的）。
   */
  accessModeLabel: {
    plan: "Najpierw plan",
    ask: "Nadzorowany",
    autoAcceptEdits: "Automatyczna akceptacja zmian",
    auto: "Automatyczny",
    fullAccess: "Pełny dostęp",
  },
  accessModeHint: {
    plan: "Tylko odczyt. Najpierw proponuje plan i nie zmienia plików ani wideo",
    ask: "Pyta przed uruchomieniem poleceń lub zmianą plików",
    autoAcceptEdits: "Automatycznie zatwierdza zmiany plików, a przed resztą pyta",
    auto: "Automatycznie zatwierdza zwykłe działania; przed ryzykownymi nadal pyta",
    fullAccess: "Uruchamia polecenia i zmienia pliki bez pytania",
  },
  taskStatusLabel: {
    running: "Przetwarzanie",
    stopping: "Zatrzymywanie",
    completed: "Gotowe",
    stopped: "Zatrzymano",
    failed: "Niepowodzenie",
  },
  /** composer 脚注的中段：这一档到底会不会问你（原型 model-agent.js `modeFoot`）。 */
  accessModeFoot: {
    plan: "Tylko planuje i nie zmienia wideo.",
    ask: "Pyta przed każdym zapisem do wideo.",
    autoAcceptEdits: "Zmiany plików wideo są dozwolone automatycznie; inne polecenia nadal wymagają pytania.",
    auto: "Zwykłe działania są dozwolone automatycznie; ryzykowne nadal wymagają pytania.",
    fullAccess: "Zapisuje do wideo bez pytania za każdym razem.",
  },
  /** 模型定位（原型 model-agent-setup.js `TIERS`）。 */
  modelTierLabel: { balanced: "Zalecany", max: "Najmocniejszy", fast: "Najszybszy" },
  /**
   * 推理强度（原型 data.js `agent.efforts`）：原生 id → 名字与代价。原型的 `mid` 在 Claude 与 Codex 里叫 `medium`。
   * 原型给「中」的副文案是「默认」：这里改成标在模型自己的默认强度那一行（见 agent-choice.ts `effortRows`）。
   */
  effort: {
    low: { label: "Niski", sub: "Szybko, dobrze do małych zmian" },
    medium: { label: "Średni", sub: null },
    high: { label: "Wysoki", sub: "Wolniej, dłużej rozważa" },
  },
  agentPicker: {
    group: "Agent kodujący",
    models: "Modele",
    effort: (label: string) => `Intensywność rozumowania · ${label}`,
    agentDefault: "Domyślny model agenta",
    agentDefaultSub: "Wybrany przez konfigurację CLI",
    configModelGate: (model: string) => `${model} wymaga nowszego CLI`,
    notListed: "Tego modelu nie ma na bieżącej liście",
    defaultMark: "Domyślny",
    localAccount: "Ten komputer",
    settings: "Ustawienia › Agenci…",
    settingsSub: "Agent kodujący · Subskrypcja · Zasady zatwierdzania",
    /** 会话有任务后 Agent 固定（架构设计 §3.11：原生会话不能跨 Agent 续）。 */
    locked: "Ta sesja już się rozpoczęła, więc nie można zmienić agenta. Aby go zmienić, rozpocznij nową sesję.",
    detecting: "Wykrywanie agentów…",
  },
  /** Agent 用不了时第一级那一行的副文案（原型 model-agent.js `providerRows`，状态词取 model-agent-setup.js `badge`）。 */
  driverStateReason: {
    disabled: "Wyłączony w ustawieniach",
    'not-installed': "Niezainstalowany",
    'signed-out': "Wymaga logowania · Sprawdź ustawienia",
    outdated: "Zbyt stara wersja · Sprawdź ustawienia",
    error: "Nie można uruchomić · Sprawdź ustawienia",
  },
  /** 斜杠命令的名字与说明，键是去掉 `/` 的命令名（`SLASH_COMMANDS`）。 */
  slash: {
    polish: { label: "Popraw transkrypcję", sub: "Popraw literówki, dodaj interpunkcję, podziel na akapity" },
    chapters: { label: "Wygeneruj rozdziały", sub: "Podziel według tematów i dodaj tytuły" },
    speakers: { label: "Rozpoznaj mówców", sub: "Dodaj imiona do napisów i transkrypcji" },
    retranscribe: { label: "Transkrybuj ponownie", sub: "Przetwórz audio ponownie innym modelem mowy" },
    clean: { label: "Znajdź fragmenty do wycięcia", sub: "Wypełniacze, długie pauzy, nieudane ujęcia" },
    translate: { label: "Przetłumacz napisy", sub: "Przetłumacz na jeden język i dopasuj kody czasu" },
    refresh: { label: "Odśwież nieaktualne tłumaczenia", sub: "Przetłumacz ponownie tylko wiersze ze zmienionym oryginałem" },
    dub: { label: "Przetłumacz dubbing", sub: "Nadaj wideo mowę w innym języku" },
    summary: { label: "Napisz podsumowanie", sub: "Podsumowanie i kluczowe punkty z czasem" },
    blog: { label: "Napisz wpis na blog", sub: "Przeredaguj na artykuł" },
    title: { label: "Zaproponuj tytuły", sub: "Kilka propozycji z różnych perspektyw" },
    desc: { label: "Napisz opis", sub: "Z czasami rozdziałów i tagami" },
    cover: { label: "Utwórz okładkę", sub: "Kilka propozycji na podstawie kluczowych kadrów" },
    export: { label: "Eksportuj", sub: "SRT / MP4 z wtopionymi napisami" },
  },
  composerMenu: {
    insert: "Wstaw",
    filesAndFolders: 'Pliki i foldery',
    files: 'Pliki', folders: 'Foldery',
    filesMessage: (paths) => `Pliki i foldery:\n${paths.map(path => JSON.stringify(path)).join('\n')}`,
    pickFailed: (message) => `Nie udało się wybrać plików: ${message}`,
    webFilesUnsupported: 'Dodaj lokalne pliki i foldery w aplikacji komputerowej BaoCut. Klient Web nie obsługuje jeszcze przesyłania plików.',
    /** 原型是「引用章节或文件」；章节、说话人这类数据 Runtime 还没有，只列视频与文件。 */
    mention: "Odwołaj się do wideo lub pliku",
    slash: "Użyj narzędzia",
    /** 「+」菜单的两组：附件类在上，引用与命令在下（原型 composer-insert-menu.jsx）。 */
    attachSection: 'Dodaj',
    referSection: "Odwołania i polecenia",
    imagesUnsupported: (driverName: string) => `${driverName} nie przyjmuje obrazów`,
    noMentionCandidates: "Nie ma tu jeszcze wideo ani plików do odwołania",
  },
  /** 输入框「+ › 使用 Skill」、输入框上的 skill 标记与会话消息上的标记（产品设计 §3.2.3、§6.9；原型 composer-insert-menu.jsx）。 */
  skill: {
    use: "Użyj Skill",
    manage: "Zarządzaj Skills…",
    loading: "Wczytywanie Skills…",
    none: "Brak Skills. Dodaj z folderu lokalnego w ustawieniach lub zaimportuj z GitHub",
    loadFailed: "Nie udało się wczytać Skills",
    token: (name: string) => `Skill: ${name}`,
    remove: (name: string) => `Usuń Skill: ${name}`,
  },
  /** 附图（原型 agent-thread.jsx `composerImageFiles` 与 `addImages`）。 */
  attachment: {
    tooLarge: `Wybierz obrazy nie większe niż ${MAX_ATTACHMENT_BYTES / 1024 / 1024} MiB`,
    tooMany: `Możesz dołączyć do ${MAX_ATTACHMENTS_PER_MESSAGE} ${pluralForm('pl', MAX_ATTACHMENTS_PER_MESSAGE, { one: 'obrazu', few: 'obrazów', many: 'obrazów', other: 'obrazu' })}`,
    /** 原型只收 image/*；协议只收这四种（limits.ts），多出来的一句。 */
    badType: "Można dołączać tylko obrazy PNG, JPEG, GIF lub WebP",
    uploadFailed: (message: string) => `Nie udało się przesłać obrazu: ${message}`,
    httpFailed: (status: number) => `Przesyłanie nie powiodło się (HTTP ${status})`,
    networkFailed: "Przesyłanie nie powiodło się: brak połączenia z Runtime",
    uploading: "Przesyłanie obrazów…",
  },
  /** 忙时排队（会话有任务在跑时发的话）。 */
  queue: {
    title: (count: number) => `W kolejce do wysłania · ${count}`,
    images: (count: number) => `${count} ${pluralForm('pl', count, {one: "obraz", few: "obrazy", many: "obrazów", other: "obrazu"})}`,
    edit: "Edytuj",
    save: "Zapisz",
    cancel: "Anuluj",
    remove: "Usuń",
    sendNow: "Wyślij teraz",
    editLabel: "Edytuj wiadomość w kolejce",
    steerUnsupported: "Ten agent nie przyjmuje wiadomości w trakcie zadania. Wiadomość zostanie wysłana po jego zakończeniu",
    skillWaits: "Wiadomość ze Skill nie może dołączyć do bieżącej tury. Zostanie wysłana po zakończeniu tury",
    failed: (message: string) => `Nie udało się wysłać wiadomości z kolejki: ${message}`,
    busyPlaceholder: "Agent pracuje. Nowe wiadomości czekają w kolejce do końca tej tury",
  },
  /** 任务失败后的恢复区（原型 agent-thread.jsx `ErrorMsg`）。 */
  recovery: {
    authTitle: (name: string) => `${name} wymaga ponownego logowania`,
    authBody: (name: string) =>
      `Logowanie odbywa się w oknie agenta ${name}; BaoCut nie przetwarza Twojego konta ani hasła. Po zalogowaniu wróć i wyślij ponownie.`,
    openLogin: "Zaloguj się z terminala",
    loginOpened: (command: string) => `Uruchamianie ${command} w terminalu · Po zalogowaniu wróć i wyślij ponownie`,
    loginCopied: "Nie udało się otworzyć terminala. Skopiowano polecenie logowania; wklej je w terminalu, aby uruchomić",
    loginManual: (command: string) => `Nie udało się otworzyć terminala. Uruchom ${command} w terminalu`,
    modelTitle: (model: string | null) => `${model ?? "Ten model"} jest teraz niedostępny`,
    modelBody: "Wybierz inny model i wyślij ponownie. BaoCut nie zmienia modeli samodzielnie.",
    pickModel: "Wyślij ponownie z innym modelem",
    resend: "Wyślij ponownie",
    retry: "Spróbuj ponownie",
    agentSettings: "Ustawienia agenta",
    nothingToResend: "Nie można znaleźć wiadomości tej tury do ponownego wysłania",
    resendFailed: (message: string) => `Nie udało się wysłać ponownie: ${message}`,
  },
  /** 审批卡（原型 agent-thread.jsx `PermissionMsg`，自动允许的那一行取 model-agent.js `autoAllowLabel`）。 */
  approval: {
    title: {
      command: "Agent chce uruchomić polecenie",
      'file-change': "Agent chce zmienić pliki",
      tool: "Agent chce użyć narzędzia",
      highRisk: "Agent chce zrobić coś ryzykownego",
    },
    kind: { command: "Uruchom polecenie", 'file-change': "Zmień pliki", tool: "Użyj narzędzia" },
    projectFiles: "Pliki w projekcie",
    inDir: (dir: string) => `W ${dir}`,
    allow: "Zezwól",
    allowAlways: (rule: string) => `Zawsze zezwalaj na ${rule}`,
    decline: "Odmów",
    accepted: "Zezwolono",
    acceptedAlways: (rule: string) => `Zezwolono · Bez kolejnych pytań o ${rule} ponownie`,
    declined: "Odmówiono",
    cancelled: "Zatrzymano",
    autoRule: (rule: string | null) => (rule ? `Zezwolono automatycznie · Reguła ${rule}` : "Zezwolono automatycznie · Reguła"),
    autoMode: "Zezwolono automatycznie · Tryb dostępu",
    input: "Podsumowanie danych wejściowych",
    copyInput: "Skopiuj podsumowanie danych wejściowych",
    failed: (message: string) => `Nie udało się przesłać: ${message}`,
  },
  /** 变更卡的撤销与恢复（原型 agent-thread.jsx `ReceiptMsg`）。 */
  change: {
    undone: "Cofnięto · Zmiany wycofane",
    undo: "Cofnij",
    restore: "Przywróć",
    openVideo: "Otwórz wideo",
    confirmTitle: "Cofnąć ten krok?",
    /**
     * 「恢复」只在这一笔还是你最近一次撤销、之后你没再改这个视频时才有（见 change-card.tsx），不说「随时」。
     */
    confirmBody: "Zmiany zapisane w wideo przez ten krok zostaną usunięte. Dopóki nie zmienisz ponownie wideo, możesz je przywrócić przyciskiem Przywróć.",
    cancel: "Anuluj",
    undoneToast: "Cofnięto",
    restoredToast: "Przywrócono",
    alreadyUndone: "Ten krok już cofnięto",
    undoFailed: (message: string) => `Nie udało się cofnąć: ${message}`,
    restoreFailed: (message: string) => `Nie udało się przywrócić: ${message}`,
  },
  /**
   * 空会话（原型 agent-thread.jsx `AgentThread` 的空态，建议取 data.js `agent.chips`）。
   * 原型说明句里的「@ 可以引用章节、说话人、译文」「写入之前一定先问你」「把视频拖进来」这里还做不到
   * （@ 只列视频与文件；问不问看访问模式；会话里不能拖入视频），只留做得到的部分。
   */
  threadEmpty: {
    greetVideo: (name: string) => `Co zrobić z wideo „${name}”?`,
    greet: "Co agent może dla Ciebie zrobić?",
    subVideo: "Najpierw przeczyta to wideo i poda plan. Użyj @, aby odwołać się do innych wideo lub plików.",
    sub: "Zacznij od opisu, co ma zostać zrobione. Działa w agencie kodującym na Twoim komputerze, z Twoją subskrypcją.",
    suggestions: "Spróbuj poprosić",
    chipsVideo: [
      "Usuń wypełniacze z tego rozdziału",
      "Nadaj każdemu rozdziałowi krótszy tytuł",
      "Znajdź powtarzające się części do wycięcia",
      "Dopasuj terminy do słownika",
    ],
    chips: [
      "Dodaj napisy do tego wideo i przetłumacz je na angielski",
      "Znajdź wypełniacze i długie pauzy, wypisz przed wycinaniem",
      "Podziel odcinek na rozdziały z tytułami",
      "Wyeksportuj dwujęzyczny SRT i MP4 z wtopionymi napisami",
    ],
  },
  /** 产物卡（原型 home-session.jsx `SessionArtifactCard`、`SessionMoviePreview`、`SessionMessageArtifacts`）。 */
  output: {
    playVideo: (name: string) => `Odtwórz wideo „${name}”`,
    noThumbnail: "Brak miniatury",
    sourceMissing: "Nie znaleziono pliku źródłowego",
    openEditor: "Otwórz edytor",
    openVideo: (name: string) => `Otwórz wideo „${name}”`,
    playHere: "Odtwórz po prawej",
    previewHere: "Podgląd po prawej",
    reveal: "Pokaż w folderze",
    messageOutputs: "Wyniki wiadomości",
  },
  /**
   * 线程里的视频卡与下载卡（产品设计 §3.2.2、§6.5；原型 home-session.jsx `SessionArtifactCard`、agent-cards.jsx `JobRow` / `DownloadCard`）。
   * 状态词与 Space 的视频状态同一套说法。
   */
  videoCard: {
    agentTranslating: 'Agent tłumaczy zdanie po zdaniu',
    sentenceTotal: (n: number) => pluralForm('pl', n, { one: `${n} zdanie łącznie`, few: `${n} zdania łącznie`, many: `${n} zdań łącznie`, other: `${n} zdania łącznie` }),
    status: { translating: 'Tłumaczenie', transcribing: "Transkrypcja", queued: "W kolejce", transcribed: "Transkrybowano", failed: "Niepowodzenie" },
    rows: "Pracuj nad tym wideo",
    retranscribe: "Transkrybuj ponownie",
    translate: "Przetłumacz",
    linkImport: "Import z linku",
    tail: { queued: "W kolejce", done: "Gotowe", failed: "Niepowodzenie", cancelled: "Anulowano", interrupted: "Przerwano", unknown: "Wynik nieznany" },
    elapsed: (clock: string) => `${clock} upłynęło`,
    recognized: (done: string, total: string | null) => (total ? `Rozpoznano: ${done} / ${total}` : `Rozpoznano: ${done}`),
    segments: (done: number, total: number | null) => total != null ? `Rozpoznano ${done} / ${total} ${pluralForm('pl', total, {one: "segment", few: "segmenty", many: "segmentów", other: "segmentu"})}` : `Rozpoznano ${done} ${pluralForm('pl', done, {one: "segment", few: "segmenty", many: "segmentów", other: "segmentu"})}`,
    translated: (done: number, total: number | null) => total != null ? `Przetłumaczono ${done} / ${total} ${pluralForm('pl', total, {one: "wiersz", few: "wiersze", many: "wierszy", other: "wiersza"})}` : `Przetłumaczono ${done} ${pluralForm('pl', done, {one: "wiersz", few: "wiersze", many: "wierszy", other: "wiersza"})}`,
    downloaded: (text: string) => `Pobrano: ${text}`,
    documentWritten: "Transkrypcja zapisana w wideo",
    notFinished: "Ten krok nie został ukończony",
    retrying: "Automatyczne ponawianie po błędzie",
    play: "Odtwórz",
    reveal: "Pokaż w folderze",
    cancel: "Anuluj",
    retry: "Spróbuj ponownie",
    warning: {
      'no-speech': "Nie wykryto mowy",
      'no-audio-track': "Wideo nie ma ścieżki audio",
      'diarization-unavailable': "Ten model nie rozróżnia mówców",
    } as Record<string, string>,
    download: {
      queued: "Oczekiwanie na pobieranie",
      running: "Pobieranie wideo",
      done: "Pobieranie ukończone",
      failed: "Pobieranie nie zakończyło się",
      cancelled: "Pobieranie anulowano",
      interrupted: "Pobieranie przerwane",
      fallbackName: "Wideo",
    },
    openFailed: (message: string) => `Nie udało się otworzyć: ${message}`,
    retryFailed: (message: string) => `Nie udało się ponowić: ${message}`,
  },
  /** Home 起始页（产品设计 §3.2.1；原型 page-new.jsx Home、new-agent.jsx）。 */
  home: {
    title: "Jakie wideo chcesz stworzyć?",
    templates: "Szablony",
    quickStart: "Szybki start",
    blankVideo: "Nowe puste wideo",
    blankVideoTip: "Bez transkrypcji, bez kolejki – prosto do edytora",
    blankVideoCreated: "Utworzono puste wideo",
    blankVideoFailed: (message: string) => `Nie udało się utworzyć pustego wideo: ${message}`,
    /** 没选项目时新建空白视频，先建一个这样命名的项目。 */
    blankVideoProject: "Puste wideo",
    removeTemplate: "Usuń szablon",
    templateToken: (title: string) => `Szablon: ${title}`,
    allTemplates: "Wszystkie szablony",
    searchTemplates: "Szukaj szablonów",
    templateKind: "Typ",
    templateSource: "Źródło",
    templateCategories: "Kategorie",
    viewTemplate: (title: string) => `Zobacz szablon: ${title}`,
    useExampleLabel: (title: string) => `Użyj polecenia: ${title}`,
    useTemplateLabel: (title: string) => `Użyj szablonu: ${title}`,
    templatePicked: "Wybrano",
    exampleBadge: "Przykład",
    templatePage: (page: number, pages: number, total: number) => `Strona ${page} z ${pages} · ${total} łącznie`,
    prevPage: "Poprzednia strona",
    nextPage: "Następna strona",
    noTemplates: "Brak pasujących szablonów. Spróbuj innego słowa lub kategorii.",
    templatesEmpty: "Folder szablonów nie ma jeszcze szablonów.",
    templatesLoading: "Wczytywanie szablonów…",
    templatesFailed: (message: string) => `Nie udało się odczytać folderu szablonów: ${message}`,
    retryTemplates: "Spróbuj ponownie",
    templatesNote: "Wbudowane szablony są częścią aplikacji; szablony włożone do folderu szablonów pojawiają się jako „Moje”.",
    templatesSkipped: (count: number) => `Nie udało się wczytać ${count} ${pluralForm('pl', count, {one: "szablonu", few: "szablonów", many: "szablonów", other: "szablonu"})}`,
    showSkipped: "Pokaż przyczynę",
    hideSkipped: "Ukryj",
    pickTemplateHint: "Wybierz szablon po lewej, aby zobaczyć tu podgląd i polecenie.",
    templatePrompt: "Polecenie",
    templatePromptLoading: "Wczytywanie polecenia…",
    templatePromptFailed: (message: string) => `Nie udało się odczytać polecenia: ${message}`,
    templateSay: "Spróbuj napisać",
    templateFields: 'Do uzupełnienia',
    templateSkills: (list: string) => `Sposób pracy: ${list}`,
    slotsLeft: (count: number, labels: string) =>
      `${pluralForm('pl', count, { one: `Zostało ${count} pole do uzupełnienia`, few: `Zostały ${count} pola do uzupełnienia`, many: `Zostało ${count} pól do uzupełnienia`, other: `Zostało ${count} pola do uzupełnienia` })}: ${labels} · Możesz wysłać mimo to — agent najpierw zapyta`,
    fillNextSlot: 'Uzupełnij następne',
    templateBriefNote: "Po wybraniu agent najpierw potwierdzi z Tobą temat, cel, odbiorców i materiały, a potem zacznie tworzyć.",
    templateAssets: "Materiały",
    templatePromptOnly: "Tylko polecenie, bez materiałów",
    useTemplate: "Użyj tego szablonu",
    keepTemplate: "Kontynuuj z tym szablonem",
    useExample: "Użyj tego polecenia",
    promptPlaced: "Wypełniono polecenie",
    undo: "Cofnij",
    playPreview: "Odtwórz podgląd",
    pausePreview: "Wstrzymaj podgląd",
    placeholder: "Opisz wideo, które chcesz stworzyć, lub przeciągnij tu materiały…",
    templatePlaceholder: "O czym ma być? Dodaj temat, odbiorców lub wymagania…",
    localFiles: "Pliki lokalne",
    addMedia: "Wideo lub audio",
    addDocument: "PDF lub dokument",
    addImage: "Obraz",
    recentVideos: "Ostatnie wideo",
    /** 选了最近的视频，原先挂着的视频或音频素材让出位置（一句话只对一条视频说）。 */
    recentReplaced: (title: string, removed: string) => `Teraz praca nad wideo „${title}”; usunięto wideo „${removed}”`,
    removeMaterial: (name: string) => `Usuń materiał: ${name}`,
    materialsFull: (max: number, rejected: number) => `Możesz dodać do ${max} ${pluralForm('pl', max, { one: 'materiału', few: 'materiałów', many: 'materiałów', other: 'materiału' })} naraz; ${rejected} nie dodano`,
    notLocalFile: "Tego pliku nie ma na tym komputerze, więc nie można go przekazać agentowi",
    thisComputer: "Ten komputer",
    pickProject: "Wybierz projekt",
    pickProjectLabel: (name: string | null) => `Wybierz projekt: ${name ?? "Brak"}`,
    currentProject: "Bieżący projekt",
    newProject: "Nowy projekt",
    noProject: "Bez projektu agent pracuje w folderze tymczasowym",
    enableFailed: (message: string) => `Nie udało się włączyć: ${message}`,
  },
  /**
   * 起始页「快捷开始」的四条（原型 model-newproject.js `STARTERS`）：处理已有视频或音频的常见事，点一下把这句话放进输入框。
   * 措辞不带「动画」「讲解」「图表」这类词，免得被当成某一类制作。`needs` 是提示里「再把什么拖进输入框」。
   */
  homeStarter: {
    sub: { title: "Dodaj napisy", needs: "materiał wideo", prompt: "Dodaj napisy do tego wideo." },
    trans: { title: "Transkrybuj i przetłumacz", needs: "materiał wideo", prompt: "Transkrybuj to wideo i przetłumacz na chiński jako dwujęzyczne napisy." },
    clean: {
      title: "Przytnij wideo z mówiącą osobą",
      needs: "materiał wideo",
      prompt: "Transkrybuj to wideo i znajdź wypełniacze, długie pauzy i powtórzone ujęcia. Pokaż przed wycinaniem.",
    },
    a2v: { title: "Audio do wideo", needs: "plik audio", prompt: "Zamień to audio w wideo z tłem, przebiegiem fali i napisami." },
    tip: (needs: string) => `Wypełnia polecenie. Następnie przeciągnij ${needs} do pola wiadomości`,
  },
  /** 模板分类的显示名（模板包规范 §3.2；键是协议的一部分）。认不出的键由 model/home-templates.ts 兜底按键名显示。 */
  templateCategory: {
    all: "Wszystkie",
    marketing: "Marketing",
    'product-launch': "Premiera produktu",
    explainer: "Objaśnienie",
    'news-data': "Wiadomości i dane",
    editing: "Montaż",
    'creative-short': "Krótki film kreatywny",
    'motion-design': "Projektowanie animacji",
  },
  /** 两类模板（规范 §1.2）。 */
  templateKind: { all: "Wszystkie", scene: "Szablony scen", example: "Przykłady" },
  templateSource: { all: "Wszystkie źródła", builtin: "Wbudowane", user: "Moje", community: "Społeczność" },
  /** 模板自带素材的种类（规范 §3.4）。 */
  templateAsset: { image: "Obraz", svg: "SVG", audio: "Audio", video: "Wideo" },
  /** 模板的画幅与时长文案（原型 model-home-templates.js `spec`、`specLine`）。 */
  templateSpec: {
    allAuto: "Proporcje i czas automatycznie",
    ratioAuto: "Proporcje automatycznie",
    lengthAuto: "Czas automatycznie",
    sceneDefault: (spec: string) => `${spec} domyślnie; aby zmienić, napisz to w wiadomości`,
    exampleAuto: "Proporcje i czas automatycznie, agent ustala je z treści",
  },
  /** 起始页的创建项目对话框（原型 new-agent.jsx `CreateProjectDialog`）。 */
  createProject: {
    title: "Utwórz projekt",
    close: "Zamknij tworzenie projektu",
    name: "Nazwa projektu",
    placeholder: "Nazwij projekt",
    location: "Zapisz w folderze",
    preview: (path: string) => `Projekt zostanie zapisany w ${path}`,
    cancel: "Anuluj",
    create: "Utwórz",
    created: (name: string) => `Utworzono projekt „${name}”`,
    failed: (message: string) => `Nie udało się utworzyć projektu: ${message}`,
  },
  /** 任务种类的名字（原型 page-tasks.jsx `KIND`）。Agent 会话里的任务原型没有单列，叫「Agent 任务」。 */
  taskKind: {
    agent: "Zadanie agenta",
    transcribe: "Transkrybuj",
    synthesizeSpeech: "Wygeneruj mowę",
    generateImage: "Wygeneruj obraz",
    generateText: "Generuj tekst",
    export: "Eksport",
    pipeline: "Potok",
    'pipeline-step': "Krok potoku",
    modelInstall: "Zainstaluj model",
    modelTest: "Sprawdź model",
    modelsMove: "Przenieś folder modeli",
    toolInstall: "Zainstaluj narzędzie",
    toolUpdate: "Zaktualizuj narzędzie",
    fontDownload: "Pobierz czcionkę",
    voiceClone: "Sklonuj głos",
    agentTranslate: "Przetłumacz",
    legacyImport: "Zaimportuj wcześniejsze projekty",
  },
  /** Job 的阶段（`JobPhase`）：列表与胶囊念「识别中 · 45%」。 */
  jobPhase: {
    queued: "W kolejce",
    starting: "Uruchamianie",
    loading: "Wczytywanie modelu",
    decoding: "Dekodowanie audio",
    vad: "Wykrywanie mowy",
    transcribing: "Rozpoznawanie",
    aligning: "Dopasowywanie czasu",
    diarizing: "Rozpoznawanie mówców",
    finalizing: "Finalizowanie",
    probing: "Odczyt mediów",
    encoding: "Kodowanie",
    downloading: "Pobieranie",
    moving: "Przenoszenie",
    generating: "Generowanie",
    validating: "Sprawdzanie",
    publishing: "Zapisywanie wyników",
    applying: "Zapisywanie do wideo",
    done: "Gotowe",
  },
  /** 后台任务页、详情与侧栏。 */
  taskView: {
    queued: "W kolejce",
    running: "W toku",
    awaitingApproval: "Wymaga Twojego zatwierdzenia",
    cancelled: "Anulowano",
    failed: "Niepowodzenie",
    completed: "Gotowe",
    interrupted: "Przerwano",
    needsReconciliation: "Wynik nieznany",
    retrying: "Automatyczne ponawianie po błędzie",
    costCharged: "Wynik otrzymany; opłata raz",
    costCancelUnsupported: "Dostawca nie obsługuje anulowania; prośba może dokończyć się zdalnie i zostać rozliczona",
    costUnknown: "Nie wiadomo, czy prośba została wysłana; mogła zostać rozliczona",
    costPossible: "Mogło zostać rozliczone",
    chipAgent: "Agent",
    chipCli: "CLI",
    byAgent: "Sesja agenta",
    byCli: "CLI",
    byApp: "Aplikacja",
    byNode: "Zdalny węzeł",
    local: "Ten komputer",
    cloud: "Chmura",
    node: "Zdalny węzeł",
    noProject: "Poza projektem",
    pageTitle: "Wszystkie zadania",
    activeSection: "W toku",
    historySection: "Gotowe",
    historyGroup: "Historia",
    emptyActive: "Brak uruchomionych zadań",
    emptyActiveBody: "Tutaj pojawiają się transkrypcje, tłumaczenia i eksporty.",
    emptyHistory: "Brak zakończonych zadań",
    openConversation: "Otwórz sesję",
    details: "Szczegóły",
    cancel: "Anuluj",
    stop: "Zatrzymaj",
    back: "Zadania w tle",
    notFound: "Nie znaleziono zadania",
    notFoundBody: "Tego zadania nie ma już na liście",
    cancelTask: "Anuluj zadanie",
    cancelExport: "Anuluj eksport",
    stopTask: "Zatrzymaj zadanie",
    cancelExportHint: "Nieukończony plik zostanie usunięty; wideo pozostaje bez zmian. Po rozpoczęciu zapisywania nie można go zatrzymać i zakończy zapis.",
    stopHint: "Agent zatrzyma się na bieżącym kroku; pliki już zapisane w projekcie pozostają bez zmian.",
    conversationHint: "To uruchomienie zatwierdzono w sesji agenta; rozmowa i zatwierdzenia są w tej sesji.",
    agentTaskHint: "To zadanie należy do sesji agenta; rozmowa i zatwierdzenia są w tej sesji.",
    cancelledBody: "Samo wideo pozostaje bez zmian.",
    interruptedBody: "Runtime zatrzymał się lub uruchomił ponownie przed końcem tego uruchomienia. Nie wznowi się; w razie potrzeby uruchom ponownie.",
    needsReconciliationBody: "Runtime uruchomił się ponownie przed odpowiedzią z chmury. Prośba mogła zostać rozliczona i nie zostanie wysłana ponownie automatycznie.",
    configHint: "To problem konfiguracji; ponowienie tej samej ścieżki nie pomoże. Dodaj brakujący komponent, a potem uruchom ponownie.",
    sourceSection: "Źródło",
    imagesSection: "Obrazy",
    outputsSection: "Wyniki",
    factsSection: "Szczegóły",
    reveal: "Pokaż w folderze",
    open: "Otwórz",
    copyPrompt: "Skopiuj polecenie",
    promptCopied: "Polecenie skopiowane",
    copyFailed: "Nie udało się skopiować. Zaznacz tekst i skopiuj ręcznie",
    documentWritten: "Transkrypcja zapisana w wideo",
    importedToVideo: "Zaimportowano do wideo",
    imageName: (n: number) => `Obraz ${n}`,
    audioName: (n: number) => `Audio ${n}`,
    videoName: (n: number) => `Eksport ${n}`,
    fileName: (n: number) => `Plik ${n}`,
    entries: (n: number) => `${n} ${pluralForm('pl', n, {one: "wpis", few: "wpisy", many: "wpisów", other: "wpisu"})}`,
    packageFiles: (n: number) => `Pakiet przenośny · ${n} ${pluralForm('pl', n, {one: "plik", few: "pliki", many: "plików", other: "pliku"})}`,
    projectClips: (n: number) => `Projekt · ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    documentName: "Transkrypcja",
    stopFailed: (message: string) => `Nie udało się zatrzymać: ${message}`,
    cancelFailed: (message: string) => `Nie udało się anulować: ${message}`,
    /** 对账（`jobs.reconcile`）：重启后结果不明、中断或没有写进视频的任务，由用户决定。 */
    reconcileRetry: "Spróbuj ponownie",
    reconcileDiscard: "Odrzuć wynik",
    reconcileApply: "Zapisz ponownie do wideo",
    reconcileRetryHint: (charges: boolean): string =>
      charges ? "Ponownie wywołuje dostawcę i może naliczyć opłatę ponownie." : "Ponownie kolejkuje to samo zadanie i uruchamia je od początku.",
    reconcileDiscardHint: "Oznaczono jako anulowane; poniesione opłaty nie są zwracane.",
    reconcileApplyHint: "Wynik nadal istnieje: zostanie ponownie sprawdzony i zapisany do wideo. Najpierw otwórz to wideo.",
    reconcileFailed: (message: string) => `Nie udało się obsłużyć: ${message}`,
    openFailed: (message: string) => `Nie udało się otworzyć: ${message}`,
    remedyInstall: "Zainstaluj komponenty",
    remedyCloud: "Skonfiguruj modele w chmurze",
    remedyDefault: "Wybierz modele domyślne",
    remedyNode: "Zobacz zdalne węzły",
    remedyAgent: "Otwórz ustawienia agenta",
  },
  /** 任务胶囊与悬停卡（原型 task-pill.jsx、model-task-pill.js）。 */
  taskPill: {
    count: (n: number) => `${n} ${pluralForm('pl', n, {one: "zadanie w tle", few: "zadania w tle", many: "zadań w tle", other: "zadania w tle"})}`,
    all: "Wszystkie zadania",
    more: (n: number) => `Jeszcze ${n} ${pluralForm('pl', n, {one: "zadanie", few: "zadania", many: "zadań", other: "zadania"})} · Zobacz wszystko w zadaniach w tle`,
    mine: "To wideo",
    justStarted: "Właśnie rozpoczęto",
    startedAt: (ago: string) => `Rozpoczęto ${ago}`,
  },
  /**
   * 功能区的「项目文件」标签（原型 home-workspace.jsx `WorkspaceFiles` 的 `__browse__` 分支）。
   * 原型没有的状态（读取中、读不了、目录为空、只列出一部分）按同样口吻补上。
   */
  projectFiles: {
    region: "Pliki projektu",
    /** 不属于项目的会话：根目录是它自己的工作目录。 */
    scratchRoot: "Folder sesji",
    searchLabel: "Znajdź pliki projektu",
    searchPlaceholder: "Znajdź pliki lub wideo",
    listLabel: (where: string) => `Pliki w folderze „${where}”`,
    resultsLabel: "Wyniki wyszukiwania",
    breadcrumbs: "Ścieżka folderu",
    loading: "Wczytywanie plików…",
    emptyFolder: "Ten folder jest pusty",
    noMatch: "Brak pasujących plików",
    noMatchHint: "Wyszukiwanie dopasowuje nazwy plików i pomija ukryte pliki oraz foldery zależności.",
    failed: "Nie udało się odczytać listy plików",
    retry: "Spróbuj ponownie",
    truncatedList: (count: number) => `Za dużo plików; pokazano tylko pierwsze ${count}.`,
    truncatedSearch: "Za dużo wyników; pokazano część. Spróbuj dokładniejszego słowa.",
    inRoot: "Główny folder projektu",
  },
  /**
   * 功能区的网页标签（原型 home-browser.jsx `WorkspaceBrowser`）。原型用 iframe；这里是宿主的独立网页视图（架构设计 §12.10），
   * 所以底部那句改成说明隔离；被拒绝的地址（本机地址、非 http/https）、网页进程退出与「这个环境不能内嵌网页」是原型没有的状态。
   */
  webTab: {
    back: "Wstecz",
    forward: "Dalej",
    stop: "Zatrzymaj wczytywanie",
    reload: "Odśwież stronę",
    address: "Adres internetowy",
    placeholder: "Szukaj lub wpisz URL",
    go: "Przejdź",
    menu: "Opcje strony",
    copy: "Skopiuj adres strony",
    copied: "Skopiowano adres strony",
    copyFailed: "Nie udało się skopiować adresu strony",
    external: "Otwórz w zewnętrznej przeglądarce",
    zoomIn: "Powiększ",
    zoomOut: "Pomniejsz",
    zoomReset: "Przywróć powiększenie 100%",
    invalid: "Wpisz URL http / https lub zapytanie. URL nie może zawierać nazwy użytkownika ani hasła.",
    loading: "Wczytywanie strony…",
    slow: "Strona wczytuje się wolno. Spróbuj ponownie lub otwórz ją w zewnętrznej przeglądarce.",
    startTitle: "Wyszukaj lub otwórz stronę internetową",
    startBody: "Wpisz URL lub zapytanie, aby szukać tutaj i kontynuować rozmowę.",
    enterUrl: "Wpisz URL",
    stoppedTitle: "Wczytywanie zatrzymane",
    failedTitle: "Nie udało się wczytać strony",
    failedDetail: (description: string, code: number) => `${description} (${code})`,
    crashedTitle: "Strona nieoczekiwanie zakończyła działanie",
    crashedBody: "Spróbuj ją odświeżyć.",
    retry: "Przeładuj",
    blockedTitle: {
      loopback: "Lokalne adresy nie otwierają się tutaj",
      scheme: "Można otworzyć tylko URL http / https",
      'app-origin': "Stron BaoCut nie można otwierać w karcie internetowej",
      invalid: "Ten URL jest nieprawidłowy",
    },
    blockedBody: {
      loopback: "Dla bezpieczeństwa osadzone strony nie łączą się z lokalnymi usługami (localhost, 127.0.0.1 itd.). W razie potrzeby otwórz w przeglądarce.",
      scheme: "Inne schematy (pliki, linki aplikacji itd.) nie otwierają się w osadzonych stronach.",
      'app-origin': "Własne strony aplikacji nie otwierają się w karcie internetowej.",
      invalid: "Sprawdź zapis URL.",
    },
    backToPage: "Wróć do strony",
    footer: "Strony otwierają się w oddzielnym środowisku bez dostępu do BaoCut i lokalnych usług; logowania są oddzielone od przeglądarki systemowej.",
    externalShort: "Otwórz zewnętrznie",
    unsupportedTitle: "Nie można tu osadzać stron internetowych",
    unsupportedBody: "Aplikacja BaoCut na komputerze może bezpośrednio przeglądać sieć; na razie otwórz w przeglądarce.",
    openInBrowser: "Otwórz w przeglądarce",
    toolsTitle: 'Narzędzia',
    newPageTitle: 'Nowa strona internetowa',
    newPageBody: 'Utwórz plik HTML w projekcie i wyświetl podgląd',
    browseFilesTitle: 'Przeglądaj pliki projektu',
    browseFilesBody: 'Pokaż folder projektu w tej karcie',
    newPageFileName: 'Nowa strona',
    newPageHint: 'Napisz tu treść strony albo poproś agenta o zmiany.',
    newPageFailed: 'Nie udało się utworzyć strony internetowej',
  },
  /** 时间线的剪贴板、右键菜单与带撤销的提示（原型 editor-keys.jsx、timeline-menu.jsx；原型说「元素」，这里是「片段」）。 */
  timelineEdit: {
    undo: "Cofnij",
    /** `verb` 是本目录里的动作名（`copy`、`cutItem`、`remove`、`duplicate`）。 */
    pick: (verb: string) => `Zaznacz klipy do działania: ${verb.toLowerCase()}`,
    copied: (n: number) => `Skopiowano ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    cut: (n: number) => `Wycięto ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    pasted: (n: number) => `Wklejono ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    duplicated: (n: number) => `Zduplikowano ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    deleted: (n: number) => `Usunięto ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    clipboardEmpty: (mod: string) => `Schowek jest pusty · Najpierw naciśnij ${mod}C, aby skopiować klip`,
    otherVideo: "Klipy w schowku pochodzą z innego wideo · Można je wkleić tylko z powrotem do tamtego wideo",
    selectedAtPlayhead: (n: number) => `Zaznaczono ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    nothingAtPlayhead: "Brak klipów przy głowicy",
    labelCut: "Wytnij klipy",
    labelPaste: "Wklej klipy",
    labelDuplicate: "Duplikuj klipy",
    labelDelete: "Usuń klipy",
    labelSplit: "Podziel klip",
    labelNudge: "Przesuń czas klipu",
    labelDisable: "Wyłącz klip",
    labelEnable: "Włącz klip",
    menuLabel: (name: string) => `Klip „${name}”`,
    split: "Podziel przy głowicy",
    splitUnavailable: "Głowica nie jest wewnątrz tego klipu",
    copy: "Kopiuj",
    cutItem: "Wytnij",
    paste: "Wklej",
    duplicate: "Duplikuj",
    disable: "Wyłącz ten klip",
    enable: "Włącz ten klip",
    disableHint: "Pozostaje na osi czasu · Pomijany w obrazie i eksportach",
    enableHint: "Znów w obrazie i eksportach",
    remove: "Usuń",
  },
  /** 走带的缩放菜单（原型 data.js `zoomMenu` 与 timeline.jsx 的 Transport）。 */
  timelineZoom: {
    menu: "Zoom",
    tip: "Opcje powiększenia",
    in: "Powiększ",
    out: "Pomniejsz",
    '100': "100%",
    fit: "Dopasuj do okna",
    fitClip: "Dopasuj bieżący klip",
    playhead: "Powiększ do głowicy",
    fitSelection: "Dopasuj zaznaczenie",
    noClip: "Przenieś głowicę do wnętrza klipu",
    noSelection: "Najpierw zaznacz klipy na osi czasu",
  },
  /**
   * 编辑器快捷键清单（原型 editor-keys.jsx 的 SHEET）：只列这里真有的键。
   * 键里的 ⌘ 在 Windows 与 Linux 上换成 Ctrl+（见 shortcut-sheet）。
   */
  shortcutSheet: {
    title: "Skróty klawiaturowe",
    done: "Rozumiem",
    hint: "Gdy kursor jest w polu tekstowym, te klawisze działają w tym polu.",
    rows: [
      ["Usuń zaznaczenie", "Usuń"],
      ["Odznacz / zamknij okno podręczne", "Esc"],
      ["Odtwarzanie / pauza", "Space / K"],
      ["Cofnij / ponów", "⌘Z / ⇧⌘Z"],
      ["Kopiuj / wytnij / wklej", "⌘C / ⌘X / ⌘V"],
      ["Duplikuj", "⌘D"],
      ["Zaznacz wszystkie klipy pod głowicą", "⌘A"],
      ["Głowica wstecz / dalej o klatkę (podczas odtwarzania: 5 sekund)", "← / →"],
      ["Głowica wstecz / dalej o sekundę", "⇧← / ⇧→"],
      ["Wstecz / dalej o 10 sekund", "J / L"],
      ["Podczas odtwarzania: głośność +10 / −10 (zwiększenie włącza dźwięk)", "↑ / ↓"],
      ["Wycisz / włącz dźwięk", "M"],
      ["Przesuń zaznaczony element na płótnie (najpierw kliknij płótno)", "Strzałki (⇧ przesuwa o 5%, ⌥↑ / ⌥↓ o 0,1%)"],
      ["Przesuń czas zaznaczonego klipu (⇧ po jednej sekundzie)", "⌥← / ⌥→"],
      ["Oś czasu: powiększ / pomniejsz / 100%", "⌘= / ⌘− / ⌘0"],
      ["Oś czasu: dopasuj okno / bieżący klip / głowicę / zaznaczenie", "⌥⌘1 / ⌥⌘2 / ⌥⌘3 / ⌥⌘4"],
      ["Podziel przy głowicy", "S / ⌘B"],
      ["Odtwarzanie pełnoekranowe / wyjdź z pełnego ekranu", "F"],
      ["Przejdź do początku / końca", "Home / End"],
      ["Otwórz listę skrótów edytora", "?"],
    ] as [string, string][],
  },
  /** Home 功能区：标签条、加号菜单、视图控件、会话列与单文件标签（原型 home-workspace.jsx、shell.jsx）。 */
  workspace: {
    tablist: "Karty obszaru roboczego",
    tablistHint: "Przeciągnij karty, aby zmienić kolejność, lub naciśnij Alt + Shift + Left/Right Arrow.",
    close: (name: string) => `Zamknij kartę „${name}”`,
    add: "Otwórz nową kartę",
    dragging: (name: string) => `Przeciąganie „${name}”. Puść, aby upuścić, Esc anuluje`,
    moved: (name: string) => `Przeniesiono „${name}”`,
    dragCancelled: "Przeciąganie anulowane",
    viewGroup: "Widok obszaru roboczego",
    resize: "Zmień szerokość kolumny sesji",
    conversation: "Sesja",
    /** 窄窗口里会话标签的提示与读屏名称（产品设计 §3.3）：`status` 是进行中 / 等待批准，没有时省掉。 */
    conversationTabTip: (title: string, status: string | null) =>
      `Sesja „${title}”${status ? ` · ${status}` : ""} · Przypięta jako pierwsza; nie można przenieść ani zamknąć`,
    conversationTabLabel: (title: string, status: string | null) => `Sesja „${title}”${status ? `, ${status}` : ""}, przypięta jako pierwsza`,
    opening: "Otwieranie wideo…",
    showInSpace: "Pokaż w Space",
    reveal: "Pokaż w folderze",
    fileMissing: "Plik przeniesiono lub usunięto",
    filesNoConversation: "Po utworzeniu sesji pojawią się tu pliki z jej folderu.",
  },
  /** 舞台上的对象：选中框、把手、旋转钮、多选统一框与就地改字（原型 stage-objects.jsx、stage-marquee.jsx）。 */
  stage: {
    label: "Obiekty na płótnie",
    textEditor: "Edytuj tekst",
    move: "Przesuń",
    resize: "Zmień rozmiar",
    scale: "Skaluj",
    rotate: "Obróć",
    rotateReset: "Resetuj obrót",
    groupMove: "Przesuń razem",
    groupScale: "Skaluj razem",
    nudge: "Przesuń pozycję",
    edgeHeightTip: "Przeciągnij, aby zmienić wysokość · ⌥ od środka",
    edgeWidthTip: "Przeciągnij, aby zmienić szerokość · ⌥ od środka",
    cornerFreeTip: "Przeciągnij, aby zmienić rozmiar · ⇧ odblokowuje proporcje, ⌥ od środka",
    cornerScaleTip: "Skaluj proporcjonalnie · ⌥ od środka",
    rotateTip: "Przeciągnij, aby obrócić · Skok 15°, ⇧ obrót swobodny · Podwójne kliknięcie resetuje",
    groupCornerTip: "Skaluj wszystko proporcjonalnie",
    picked: (n: number) => `${n} wybrano`,
    degrees: (n: number) => `${n}°`,
  },
  /**
   * 四项服务的目录与起停用词（原型 model-services.js `SERVICES`）；远端算力沿用「共享」。顺序就是侧栏与总览的顺序。
   * 模型接口服务在原型里是 Web 服务页里的一节（page-services-api.jsx `ApiSection`）；Runtime 把它做成独立的服务（自己的端口、
   * 令牌与开关，架构设计 §4.8），这里排在 Web 服务后面。
   */
  service: {
    mcp: {
      name: "Usługa MCP",
      scope: "Tylko ten komputer",
      desc: "Pozwala innym aplikacjom AI czytać wideo i wywoływać narzędzia BaoCut",
      start: "Uruchom usługę",
      stop: "Zatrzymaj usługę",
      starting: "Uruchamianie…",
      stopping: "Zatrzymywanie…",
    },
    remote: {
      name: "Obliczenia zdalne",
      scope: "Sieć lokalna",
      desc: "Udostępnia obliczenia tego Maca innym komputerom w Twojej sieci lokalnej",
      start: "Rozpocznij udostępnianie",
      stop: "Zatrzymaj udostępnianie",
      starting: "Uruchamianie…",
      stopping: "Zatrzymywanie…",
    },
    web: {
      name: "Usługa internetowa",
      scope: "Tylko ten komputer",
      desc: "Otwórz BaoCut Web w przeglądarce, aby edytować te same wideo",
      start: "Uruchom usługę",
      stop: "Zatrzymaj usługę",
      starting: "Uruchamianie…",
      stopping: "Zatrzymywanie…",
    },
    'model-api': {
      name: "API modeli",
      scope: "Tylko ten komputer",
      desc: "Pozwala narzędziom używającym OpenAI API korzystać z modeli BaoCut do transkrypcji, mowy, obrazów i tekstu",
      start: "Uruchom usługę",
      stop: "Zatrzymaj usługę",
      starting: "Uruchamianie…",
      stopping: "Zatrzymywanie…",
    },
  },
  /** 服务的状态词（原型 model-services.js `stateLabel`）；`unavailable` 是这个版本的 Runtime 没有提供的服务。 */
  serviceState: {
    share: { starting: "Rozpoczynanie udostępniania…", stopping: "Zatrzymywanie udostępniania…", error: "Udostępnianie nieoczekiwanie zatrzymane", on: "Udostępnianie", off: "Brak udostępniania" },
    service: { starting: "Uruchamianie…", stopping: "Zatrzymywanie…", error: "Nie udało się uruchomić", on: "Działa", off: "Nierozpoczęte" },
    unavailable: "Jeszcze niedostępne",
  },
  servicesPage: {
    title: "Usługi",
    overview: "Przegląd usług",
    lede: "Usługi BaoCut na tym Macu, z którymi mogą łączyć się inne aplikacje i urządzenia. Wszystkie są domyślnie wyłączone i zatrzymują się przy zamknięciu BaoCut.",
    allOff: "Żadna nie działa",
    errors: (n: number) => `${n} ${pluralForm('pl', n, {one: "błąd", few: "błędy", many: "błędów", other: "błędu"})}`,
    running: (n: number) => `${n} w trakcie`,
    open: (name: string) => `Otwórz ${name}`,
    /** `verb` 是服务自己的启动词（`service.*.start`）。 */
    restart: (verb: string) => `Powtórz: ${verb}`,
    railAlert: (text: string) => `Usługi, ${text}`,
    railApprovals: (n: number) => `Usługi, ${n} ${pluralForm('pl', n, {one: "prośba", few: "prośby", many: "próśb", other: "prośby"})} – oczekiwanie na Twoje zatwierdzenie`,
    loading: "Wczytywanie stanu…",
    disconnected: "Brak połączenia z BaoCut Runtime",
    failed: (message: string) => `Nie powiodło się: ${message}`,
    /** Runtime 列出了、但这个版本没有提供的服务（`available: false`）：总览行与详情页说清楚为什么不能起停。 */
    unavailableDetail: "Ta wersja BaoCut Runtime nie oferuje jeszcze tej usługi",
    unavailableTitle: (name: string) => `${name} jest jeszcze niedostępne`,
    notRunning: "Usługa nie działa. Najpierw ją uruchom",
    mcpRelated: "Chcesz nauczyć Claude Code lub Codex w terminalu sposobów pracy BaoCut? Zainstaluj dla nich Skill BaoCut – usługa nie jest potrzebna. Zobacz",
    mcpRelatedLink: "Ustawienia › Skills",
  },
  /** BaoCut Runtime 卡（原服务页的一张卡，现在给设置 › 诊断复用）。 */
  runtimeCard: {
    name: "BaoCut Runtime",
    version: "Wersja",
    versionValue: (runtime: string, protocol: number | string) => `${runtime} (protokół ${protocol})`,
    pid: "Proces",
    startedAt: "Rozpoczęto",
    home: "Folder danych",
  },
  /** 远端算力页（原型 page-shell.jsx RemotePage）。这个版本只能共享转录，其他几类任务画成禁用并说明原因。 */
  remote: {
    title: "Obliczenia zdalne",
    tabsLabel: "Widoki obliczeń zdalnych",
    tabShare: "Udostępnianie tego Maca",
    tabNodes: "Użyj innych komputerów",
    ledeShare: {
      before: "Udostępnij transkrypcję tego Maca innym komputerom w Twojej sieci lokalnej. ",
      strong: "Pliki pozostają w sieci lokalnej",
      after: "; wracają tylko wyniki – bez serwerów.",
    },
    ledeNodes: {
      before: "Przekaż transkrypcję szybszemu komputerowi w Twojej sieci lokalnej. ",
      strong: "Pliki pozostają w sieci lokalnej",
      after: "; wracają tylko wyniki – bez serwerów.",
    },

    cardOn: "Udostępnianie tego Maca",
    cardOff: "Udostępnianie wyłączone",
    subOff: "Inne urządzenia nie widzą tego Maca.",
    subErrorFallback: "Usługa węzła nie nasłuchuje.",
    errorFix: "Zamknij program używający tego portu, a potem włącz udostępnianie ponownie – lub zatrzymaj, jeśli już go nie potrzebujesz.",
    foot: "Gdy udostępnianie jest włączone, BaoCut wznawia je przy następnym otwarciu.",
    footRight: "Udostępnianie zatrzymuje się przy zamknięciu BaoCut.",
    privacy: "Dane wejściowe zadania przesyłane są tylko w sieci lokalnej i wracają tylko wyniki; po zakończeniu zadania nic nie zostaje na tym Macu.",
    offHint: "Po rozpoczęciu udostępniania pojawi się 6-cyfrowy kod parowania; wpisz go na drugim urządzeniu, aby połączyć.",
    started: "Rozpoczęto udostępnianie tego Maca",
    stopped: "Zatrzymano udostępnianie",

    nodeName: "Nazwa węzła",
    address: "Adres",
    noAddress: "Brak adresu sieci lokalnej",
    pairingTitle: "Kod parowania",
    pairingHint: (left: string) => `Wpisz ten kod na drugim urządzeniu. Wygaśnie za ${left}.`,
    pairingLocked: (until: string) => `Za dużo błędnych prób; parowanie zablokowane do ${until}. Wygeneruj nowy kod, aby odblokować teraz.`,
    pairingNone:
      "Obecnie brak kodu parowania. Trzeba wygenerować nowy po użyciu, wygaśnięciu lub ponownym otwarciu BaoCut. Sparowane urządzenia pozostają bez zmian.",
    regenerate: "Wygeneruj ponownie",
    generate: "Wygeneruj kod parowania",
    regenerated: "Wygenerowano nowy kod parowania",

    tasksTitle: "Zadania udostępniane innym komputerom",
    taskSummary: (on: number, total: number) => `Udostępnianie ${on} / ${total} ${pluralForm('pl', total, {one: "typ zadania", few: "typy zadań", many: "typów zadań", other: "typu zadania"})}`,
    taskUnsupported: "Ta wersja nie może jeszcze udostępniać tego rodzaju zadania",
    taskNoModel: (noun: string) => `Ten Mac nie ma użytecznego modelu: ${noun}; takie zadania z innych komputerów nie powiodą się`,
    taskSwitch: (name: string) => `Udostępnij ${name.toLowerCase()}`,
    taskOn: (name: string) => `Teraz udostępnianie: ${name.toLowerCase()}`,
    taskOff: (name: string) => `Zatrzymano udostępnianie: ${name.toLowerCase()} · Przyjęte zadania zakończą się`,

    status: "Stan",
    idle: "Bezczynny",
    jobs: (running: number, queued: number) =>
      [running ? `${running} w trakcie` : "", queued ? `${queued} w kolejce` : ""].filter(Boolean).join(" · "),

    clientsTitle: "Sparowane urządzenia",
    clientsEmpty: "Żadne urządzenie nie jest jeszcze sparowane z tym Makiem.",
    clientMeta: (paired: string, seen: string | null) => (seen ? `Sparowano ${paired} · Ostatnio widziano ${seen}` : `Sparowano ${paired} · Nigdy nie połączono`),
    revoke: "Cofnij uprawnienie",
    revokeLabel: (name: string) => `Cofnij uprawnienie „${name}”`,
    revokeTitle: (name: string) => `Cofnąć uprawnienie „${name}”?`,
    revokeBody: "Token od razu przestaje działać, a zadania wysłane na tego Maca są anulowane. Aby użyć ponownie, trzeba znów wpisać kod parowania.",
    revoked: (name: string) => `Cofnięto uprawnienie urządzenia „${name}”`,

    paired: "Sparowano",
    pairedEmptyTitle: "Brak sparowanych węzłów",
    pairedEmptyBody: "Włącz „Udostępnianie tego Maca” na drugim komputerze, a następnie sparuj tutaj.",
    nearby: "W pobliżu",
    nearbyIdle: "Kliknij „Znajdź komputery w pobliżu”, aby zobaczyć komputery udostępniające w Twojej sieci lokalnej.",
    nearbyNone:
      "Nie znaleziono udostępniających komputerów. Upewnij się, że tam włączono „Udostępnianie tego Maca” i oba są w tej samej sieci lokalnej – lub dodaj przez adres.",
    search: "Znajdź komputery w pobliżu",
    searching: "Wyszukiwanie…",
    addByAddress: "Dodaj przez adres…",
    pair: "Sparuj",
    pairLabel: (name: string) => `Sparuj z urządzeniem „${name}”`,
    online: "Online",
    offline: "Offline",
    versionMismatch: "Niezgodna wersja",
    unpaired: "Parowanie jest już nieważne",
    checking: "Sprawdzanie…",
    more: (name: string) => `Więcej działań dla „${name}”`,
    copyAddress: "Skopiuj adres",
    copied: (address: string) => `Skopiowano: ${address}`,
    copyFailed: "Nie udało się skopiować. Zaznacz tekst i skopiuj",
    unpair: "Usuń parowanie",
    unpairTitle: (name: string) => `Usuń parowanie z urządzeniem „${name}”?`,
    unpairBody: "Ten komputer zniknie z listy modeli transkrypcji. Możesz ponownie sparować w każdej chwili.",
    unpairDone: "Usunięto parowanie",
    /** 节点卡上「为什么用不了」：按 `PairedNode.problem` 拼（没有诊断方法，不叫「诊断」）。 */
    problem: {
      unreachable: "Nie można połączyć z tym komputerem. Upewnij się, że ma otwarty BaoCut z „Udostępnianiem tego Maca”, a oba komputery są w tej samej sieci lokalnej.",
      version: "Komputery mają niezgodne wersje BaoCut. Zaktualizuj oba do najnowszej wersji.",
      unpaired: "Parowanie jest nieważne: druga strona cofnęła uprawnienie tego komputera lub inny komputer używa tego adresu. Usuń parowanie i sparuj ponownie.",
    },
    transcribeOff: "Transkrypcja nie jest udostępniana",
    transcribeModels: (n: number) => n ? `Transkrypcja · ${n} ${pluralForm('pl', n, {one: "model", few: "modele", many: "modeli", other: "modelu"})}` : 'Transkrypcja',

    pairTitle: (name: string) => `Sparuj z urządzeniem „${name}”`,
    addTitle: "Dodaj przez adres",
    pairBody: "Odczytaj 6-cyfrowy kod z „Udostępniania tego Maca” na drugim komputerze i wpisz tutaj.",
    addressLabel: "Adres",
    addressPlaceholder: "192.168.1.31:47610",
    addressHint: (port: number) => `Nazwa hosta lub IP, opcjonalnie z portem; gdy go pominiesz, używany jest ${port}.`,
    codeLabel: "Kod parowania",
    codePlaceholder: "481 924",
    cancel: "Anuluj",
    pairing: "Parowanie…",
    pairedToast: "Sparowano · Teraz widoczny na liście modeli transkrypcji",
    addressEmpty: "Wpisz adres drugiego komputera",
    addressInvalid: "Nieprawidłowy format adresu: użyj 192.168.1.31 lub 192.168.1.31:47610",
    portInvalid: "Port musi być liczbą od 1 do 65535",
    codeInvalid: "Kod parowania ma 6 cyfr",
    pairErrors: {
      'pairing-code-invalid': "Kod parowania jest błędny lub nieważny. Poproś o nowy kod i spróbuj ponownie.",
      'pairing-locked': "Za dużo błędnych prób; tamten komputer tymczasowo zablokował parowanie. Poproś o kliknięcie „Wygeneruj ponownie”, aby odblokować.",
      version: "Komputery mają niezgodne wersje BaoCut. Najpierw zaktualizuj oba do najnowszej wersji.",
      'source-not-allowed': "Tamten komputer nie przyjmuje połączeń z adresu tego komputera.",
      lost: "Nie można połączyć z tamtym komputerem. Sprawdź adres i port oraz włączone „Udostępnianie tego Maca”.",
    },
    pairFailed: (message: string) => `Parowanie nie powiodło się: ${message}`,
  },
  /** 「提供给其他电脑的任务」的名字（键见 `REMOTE_TASK_COPY`）。`noun` 是缺模型提示里的那类模型。 */
  remoteTask: {
    asr: { name: "Transkrypcja", noun: "model transkrypcji" },
    tts: { name: "Dubbing", noun: "model dubbingu" },
    image: { name: "Generowanie obrazów", noun: "model obrazu" },
    separate: { name: "Separacja wokalu", noun: "model separacji" },
    download: { name: "Pobieranie wideo", noun: null },
    export: { name: "Eksport wideo", noun: null },
  },
  /** 帮助中心（原型 help-center.jsx）：外框、分类、搜索、快速上手、快捷键页与入口。 */
  help: {
    title: "Centrum pomocy",
    subtitle: "Sprawdzaj w dowolnej chwili i zaczynaj pracę",
    close: "Zamknij pomoc",
    navLabel: "Kategorie pomocy",
    navTitle: "Korzystanie z BaoCut",
    navNote: ["Czytaj tylko to, czego potrzebujesz.", "Zamknij, aby wrócić do pracy."] as [string, string],
    sections: { start: "Szybki start", guide: "Poradniki", keys: "Skróty klawiaturowe", faq: "Częste pytania" },
    searchLabel: "Szukaj w pomocy",
    searchPlaceholder: "Szukaj tego, co chcesz zrobić, np. styl napisów",
    results: "Wyniki wyszukiwania",
    found: (n: number) => `Znaleziono ${n} ${pluralForm('pl', n, {one: "poradnik", few: "poradniki", many: "poradników", other: "poradnika"})}`,
    emptyTitle: "Brak pasujących poradników",
    emptyBody: "Spróbuj „napisy”, „materiały”, „agent” lub „proporcje” – albo zacznij od szybkiego startu.",
    emptyAction: "Zobacz szybki start",
    welcomeEyebrow: "Pierwszy raz? Zacznij tutaj",
    welcomeTitle: "Stwórz pierwsze wideo z napisami",
    welcomeBody: (steps: number) => `Od klipu do eksportu z napisami; liczba kroków: ${steps}.`,
    welcomeAction: "Rozpocznij poradnik na start",
    welcomeDuration: (steps: number, minutes: number) => `${steps} ${pluralForm('pl', steps, {one: "krok", few: "kroki", many: "kroków", other: "kroku"})} · Około ${minutes} min czytania`,
    pathLabel: (steps: number) => `Pierwsze kroki; liczba kroków: ${steps}`,
    pathMinutes: (minutes: number) => `${minutes} min czytania`,
    moreTitle: "Może Ci się też przydać",
    allGuides: "Wszystkie poradniki",
    keysHintLead: "Nie możesz znaleźć działania?",
    keysHintLink: "Zobacz skróty klawiaturowe",
    keysHintNote: "Otwiera listę w edytorze",
    keysTitle: "Mniej kliknięć, trochę szybciej",
    keysIntro: "Te skróty działają w edytorze. Podczas pisania klawisze najpierw edytują tekst.",
    keysPlatform: "Styl skrótów",
    mac: "macOS",
    other: "Windows / Linux",
    guideTitle: "Znajdź tu to, co chcesz zrobić",
    guideIntro: "Każdy poradnik dotyczy jednej rzeczy, więc możesz wrócić do wideo i od razu spróbować.",
    faqTitle: "Masz problem? Zacznij tutaj",
    faqIntro: "Zacznij od najczęstszych przyczyn i sprawdzaj krok po kroku.",
    minutes: (minutes: number) => `${minutes} min`,
    readTime: (minutes: number) => `Około ${minutes} min czytania`,
    backToResults: "Wróć do wyników wyszukiwania",
    backTo: (section: string) => `Wróć do ${section}`,
    pickVideo: "Wybierz wideo",
    pickVideoNote: "Najpierw otwórz wideo, a potem postępuj według poradnika.",
    ctaNote: "Otwiera funkcję; dalej działasz samodzielnie.",
    backToVideo: "Wróć do wideo",
    backNote: "Zamknij pomoc i wypróbuj w swoim wideo.",
    next: (title: string) => `Czytaj dalej: ${title}`,
    footer: "Wbudowane poradniki · Dostępne offline",
    entry: "Centrum pomocy · F1",
    entryLabel: "Centrum pomocy",
    settingsEntry: "Pomoc",
  },
  /** 编辑器预览的监听音量与全屏（快捷键 ↑/↓、M、F；原型 editor-keys.jsx 借全屏播放器的键）。只是这个窗口听到、看到的，不进视频。 */
  previewKeys: {
    volume: (volume: number) => `Głośność podglądu ${volume}`,
    muted: "Podgląd wyciszony",
    unmuted: (volume: number) => `Dźwięk podglądu włączony · Głośność ${volume}`,
    fullscreenFailed: "Nie udało się pokazać podglądu pełnoekranowego",
  },
  /** 画布浮动工具条与多选页（原型 stage-toolbar.jsx、stage-toolbar-menu.jsx、panel-elements.jsx MultiSelectPanel）。 */
  stageToolbar: {
    label: "Pasek narzędzi klipu",
    more: "Więcej",
    back: "Wstecz",
    unavailable: "Jeszcze niedostępne",
    textColor: "Kolor tekstu",
    fillColor: "Kolor wypełnienia",
    strokeColor: "Kolor obrysu",
    strokeWidth: "Grubość",
    muted: "Wyciszony",
    firstGeometry: (name: string) => `Geometria tylko do odczytu pokazuje pierwszy klip „${name}”; zaznacz tylko ten klip, aby zmienić wartości.`,
    align: "Wyrównaj",
    alignTo: "Względem",
    toSelection: "Zaznaczenie",
    toCanvas: "Płótno",
    alignLeft: "Wyrównaj do lewej",
    alignHCenter: "Wyśrodkuj poziomo",
    alignRight: "Wyrównaj do prawej",
    alignTop: "Wyrównaj do góry",
    alignVCenter: "Wyśrodkuj pionowo",
    alignBottom: "Wyrównaj do dołu",
    distribute: "Rozmieść",
    distributeX: "Rozmieść poziomo",
    distributeY: "Rozmieść pionowo",
    alignNeed: "Wyrównywanie wymaga co najmniej dwóch ruchomych klipów lub jednego przy wyrównywaniu do płótna.",
    distributeNeed: "Równe rozmieszczenie wymaga co najmniej trzech ruchomych klipów.",
    labelAlign: "Wyrównaj klipy",
    labelDistribute: "Rozmieść klipy",
    aligned: (n: number) => `Wyrównano ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    distributed: (n: number) => `Rozmieszczono ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    inPlace: "Już na miejscu; brak klipów do przesunięcia",
    duplicate: "Duplikuj",
    copy: "Kopiuj",
    removeAll: (n: number) => n === 1 ? 'Usuń ten klip' : `Usuń ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}`,
    skipped: (n: number) => `Pomijane w wyrównywaniu i rozmieszczaniu: ${n} ${pluralForm('pl', n, {one: "klip", few: "klipy", many: "klipów", other: "klipa"})}. Główne wideo, audio i napisy nie są osobno umieszczane na płótnie, a zablokowane klipy się nie ruszają.`,
    dragNote: "Przeciągnij jeden z nich na płótnie, aby przesunąć razem. Zaznacz pojedynczy klip, aby zmieniać właściwości po kolei.",
    hint: "Wyrównanie, rozmieszczenie, duplikacja i usunięcie liczą się każde jako jeden krok cofnięcia.",
    labelFlip: "Odbij",
    labelFit: "Dopasuj do płótna",
    labelFill: "Wypełnij płótno",
  },
  /** @ 补全分组（设计稿 model-agent.js `mentionItems` 的本视频一组）：打开的视频里的章节与说话人在前。 */
  mentionGroups: {
    video: "To wideo",
    files: "Wideo i pliki",
  },
};
