import { pluralForm } from '@baocut/protocol';
import { MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_PER_MESSAGE } from '@baocut/protocol';
import type { CopyMessages } from './copy.ts';

export const fr: CopyMessages = {

  reveal: "Afficher dans le dossier",
  untitled: "Nouvelle session",

  sentAttachments: "Fichiers envoyés",

  accessModeToast: (label: string) => `Le prochain tour utilisera « ${label} ». Ce tour garde son mode d’accès.`,

  composerFoot: (name: string, account: string, foot: string) =>
    `Exécuté dans ${name} sur cet ordinateur, ${account ? `avec votre ${account}` : "avec votre propre abonnement"}. ${foot} Enter envoie, Shift+Enter ajoute une ligne, @ référence, / commandes.`,


  accessModeLabel: {
    plan: "Plan d’abord",
    ask: "Supervisé",
    autoAcceptEdits: "Accepter les modifications",
    auto: "Automatique",
    fullAccess: "Accès complet",
  },
  accessModeHint: {
    plan: "Lecture seule. Propose un plan sans modifier fichiers ni vidéos",
    ask: "Demande avant commandes ou modifications de fichiers",
    autoAcceptEdits: "Approuve automatiquement les fichiers, demande pour le reste",
    auto: "Approuve les actions courantes, demande pour les risques",
    fullAccess: "Commandes et modifications sans demande",
  },
  taskStatusLabel: {
    running: "En cours",
    stopping: "Arrêt",
    completed: "Terminé",
    stopped: "Arrêté",
    failed: "Échec",
  },

  accessModeFoot: {
    plan: "Plan seulement, vidéo inchangée.",
    ask: "Demande avant chaque écriture dans la vidéo.",
    autoAcceptEdits: "Fichiers vidéo automatiquement autorisés ; autres commandes demandées.",
    auto: "Actions courantes automatiques ; risques demandés.",
    fullAccess: "Écrit dans la vidéo sans demande répétée.",
  },

  modelTierLabel: { balanced: "Recommandé", max: "Le plus performant", fast: "Le plus rapide" },

  effort: {
    low: { label: "Faible", sub: "Rapide pour petites modifications" },
    medium: { label: "Moyen", sub: null },
    high: { label: "Élevé", sub: "Plus lent, réfléchit davantage" },
  },
  agentPicker: {
    group: "Agent de code",
    models: "Modèles",
    effort: (label: string) => `Effort de raisonnement · ${label}`,
    agentDefault: "Modèle par défaut de l’Agent",
    agentDefaultSub: "Choisi par les réglages CLI",
    configModelGate: (model: string) => `${model} nécessite une CLI plus récente`,
    notListed: "Ce modèle n’est pas dans la liste actuelle",
    defaultMark: "Par défaut",
    localAccount: "Cet ordinateur",
    settings: "Réglages › Agent…",
    settingsSub: "Agent de code · Abonnement · Politique d’approbation",

    locked: "La session a déjà démarré ; son Agent ne peut plus changer. Créez une session pour changer.",
    detecting: "Détection des Agents…",
  },

  driverStateReason: {
    disabled: "Désactivé dans Réglages",
    'not-installed': "Non installé",
    'signed-out': "Connexion requise · vérifier dans Réglages",
    outdated: "Version trop ancienne · vérifier dans Réglages",
    error: "Exécution impossible · vérifier dans Réglages",
  },

  slash: {
    polish: { label: "Améliorer la transcription", sub: "Corrige les fautes, ajoute la ponctuation, découpe en paragraphes" },
    chapters: { label: "Générer des chapitres", sub: "Diviser par sujet et ajouter des titres" },
    speakers: { label: "Identifier les intervenants", sub: "Nommer les locuteurs dans sous-titres et transcription" },
    retranscribe: { label: "Retranscrire", sub: "Relancer l’audio avec un autre modèle vocal" },
    clean: { label: "Trouver les parties à couper", sub: "Tics de langage, longues pauses, prises ratées" },
    translate: { label: "Traduire les sous-titres", sub: "Traduire dans une langue et aligner les horaires" },
    refresh: { label: "Rafraîchir les traductions obsolètes", sub: "Retraduire seulement les lignes modifiées à la source" },
    dub: { label: "Doublage traduit", sub: "Faire parler la vidéo dans une autre langue" },
    summary: { label: "Rédiger un résumé", sub: "Résumé et points clés horodatés" },
    blog: { label: "Rédiger un article de blog", sub: "Réécrire en article" },
    title: { label: "Proposer des titres", sub: "Plusieurs candidats sous différents angles" },
    desc: { label: "Rédiger une description", sub: "Avec codes temporels de chapitres et tags" },
    cover: { label: "Créer une miniature", sub: "Plusieurs candidats depuis les images clés" },
    export: { label: "Exporter", sub: "SRT / MP4 avec sous-titres incrustés" },
  },
  composerMenu: {
    insert: "Insérer",
    filesAndFolders: 'Fichiers et dossiers',
    files: 'Fichiers', folders: 'Dossiers',
    filesMessage: (paths) => `Fichiers et dossiers:\n${paths.map(path => JSON.stringify(path)).join('\n')}`,
    pickFailed: (message) => `Impossible de sélectionner les fichiers: ${message}`,
    webFilesUnsupported: 'Ajoutez les fichiers et dossiers locaux dans BaoCut pour ordinateur. L’envoi de fichiers n’est pas encore disponible dans le client Web.',

    mention: "Référencer une vidéo ou un fichier",
    slash: "Utiliser un outil",

    attachSection: 'Ajouter',
    referSection: "Références et commandes",
    imagesUnsupported: (driverName: string) => `${driverName} n’accepte pas les images`,
    noMentionCandidates: "Aucune vidéo ni fichier à référencer",
  },

  skill: {
    use: "Utiliser un Skill",
    manage: "Gérer les Skills…",
    loading: "Chargement des Skills…",
    none: "Aucun Skill. Ajoutez un dossier local dans Réglages ou importez depuis GitHub",
    loadFailed: "Impossible de charger les Skills",
    token: (name: string) => `Skill : ${name}`,
    remove: (name: string) => `Retirer le Skill : ${name}`,
  },

  attachment: {
    tooLarge: `Choisissez des images de taille inférieure à ${MAX_ATTACHMENT_BYTES / 1024 / 1024} Mio`,
    tooMany: `Vous pouvez joindre au plus ${MAX_ATTACHMENTS_PER_MESSAGE} images`,

    badType: "Seules les images PNG, JPEG, GIF ou WebP peuvent être jointes",
    uploadFailed: (message: string) => `Impossible d’envoyer l’image : ${message}`,
    httpFailed: (status: number) => `Envoi en échec (HTTP ${status})`,
    networkFailed: "Envoi en échec : Runtime inaccessible",
    uploading: "Envoi des images…",
  },

  queue: {
    title: (count: number) => `En file d’envoi · ${count}`,
    images: (count: number) => (pluralForm('fr', count, { one: `${count} image`, other: `${count} images` })),
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    remove: "Supprimer",
    sendNow: "Envoyer maintenant",
    editLabel: "Modifier le message en file",
    steerUnsupported: "Cet Agent ne reçoit pas de messages pendant une tâche ; envoi à sa fin",
    skillWaits: "Les messages avec Skill ne rejoignent pas le tour en cours ; envoi à sa fin",
    failed: (message: string) => `Impossible d’envoyer le message en file : ${message}`,
    busyPlaceholder: "L’Agent travaille. Les messages envoyés sont en file jusqu’à la fin du tour",
  },

  recovery: {
    authTitle: (name: string) => `${name} nécessite une nouvelle connexion`,
    authBody: (name: string) =>
      `Connectez-vous dans la fenêtre de ${name} ; BaoCut ne gère jamais compte ou mot de passe. Revenez renvoyer après connexion.`,
    openLogin: "Se connecter depuis Terminal",
    loginOpened: (command: string) => `Exécution de ${command} dans un terminal · revenez renvoyer après connexion`,
    loginCopied: "Impossible d’ouvrir un terminal. Commande de connexion copiée ; collez-la dans un terminal",
    loginManual: (command: string) => `Impossible d’ouvrir un terminal. Exécutez ${command} dans un terminal`,
    modelTitle: (model: string | null) => `${model ?? "Ce modèle"} est actuellement indisponible`,
    modelBody: "Choisissez un autre modèle et renvoyez. BaoCut ne change pas de modèle seul.",
    pickModel: "Renvoyer avec un autre modèle",
    resend: "Renvoyer",
    retry: "Réessayer",
    agentSettings: "Réglages Agent",
    nothingToResend: "Message de ce tour introuvable pour renvoi",
    resendFailed: (message: string) => `Impossible de renvoyer : ${message}`,
  },

  approval: {
    title: {
      command: "L’Agent veut exécuter une commande",
      'file-change': "L’Agent veut modifier des fichiers",
      tool: "L’Agent veut utiliser un outil",
      highRisk: "L’Agent veut une action risquée",
    },
    kind: { command: "Exécuter la commande", 'file-change': "Modifier les fichiers", tool: "Utiliser l’outil" },
    projectFiles: "Fichiers du projet",
    inDir: (dir: string) => `Dans ${dir}`,
    allow: "Autoriser",
    allowAlways: (rule: string) => `Toujours autoriser ${rule}`,
    decline: "Refuser",
    accepted: "Autorisé",
    acceptedAlways: (rule: string) => `Autorisé · aucune nouvelle demande pour ${rule}`,
    declined: "Refusé",
    cancelled: "Arrêté",
    autoRule: (rule: string | null) => (rule ? `Autorisé automatiquement · Règle ${rule}` : "Autorisé automatiquement · Règle"),
    autoMode: "Autorisé automatiquement · Mode d’accès",
    input: "Résumé des entrées",
    copyInput: "Copier le résumé d’entrée",
    failed: (message: string) => `Impossible de soumettre : ${message}`,
  },

  change: {
    undone: "Annulé · modifications rétablies",
    undo: "Annuler",
    restore: "Restaurer",
    openVideo: "Ouvrir la vidéo",
    confirmTitle: "Annuler cette étape ?",

    confirmBody: "Les modifications de cette étape seront retirées. Avant une nouvelle modification, vous pourrez les récupérer avec Restaurer.",
    cancel: "Annuler",
    undoneToast: "Annulé",
    restoredToast: "Rétabli",
    alreadyUndone: "Étape déjà annulée",
    undoFailed: (message: string) => `Impossible d’annuler : ${message}`,
    restoreFailed: (message: string) => `Impossible de restaurer : ${message}`,
  },

  threadEmpty: {
    greetVideo: (name: string) => `Que faire de « ${name} » ?`,
    greet: "Que peut faire l’Agent pour vous ?",
    subVideo: "Il lit la vidéo et propose un plan. Utilisez @ pour référencer d’autres vidéos ou fichiers.",
    sub: "Décrivez quoi faire. L’Agent de code fonctionne localement sur votre abonnement.",
    suggestions: "Essayez de demander",
    chipsVideo: [
      "Retirez les tics de langage de ce chapitre",
      "Donnez un titre plus court à chaque chapitre",
      "Trouvez les passages répétés à couper",
      "Alignez les termes sur le glossaire",
    ],
    chips: [
      "Sous-titrez cette vidéo et traduisez en anglais",
      "Trouvez les tics de langage et longues pauses, listez-les avant de couper",
      "Divisez cet épisode en chapitres titrés",
      "Exportez un SRT bilingue et un MP4 avec sous-titres incrustés",
    ],
  },

  output: {
    playVideo: (name: string) => `Lire la vidéo « ${name} »`,
    noThumbnail: "Aucune miniature",
    sourceMissing: "Fichier source introuvable",
    openEditor: "Ouvrir l’éditeur",
    openVideo: (name: string) => `Ouvrir la vidéo « ${name} »`,
    playHere: "Lire à droite",
    previewHere: "Aperçu à droite",
    reveal: "Afficher dans le dossier",
    messageOutputs: "Résultats du message",
  },

  videoCard: {
    agentTranslating: 'L’Agent traduit phrase par phrase',
    sentenceTotal: (n: number) => pluralForm('fr', n, { one: `${n} phrase au total`, other: `${n} phrases au total` }),
    status: { translating: 'Traduction en cours', transcribing: "Transcription en cours", queued: "En file", transcribed: "Transcrit", failed: "Échec" },
    rows: "Travailler sur cette vidéo",
    retranscribe: "Retranscrire",
    translate: "Traduire",
    linkImport: "Importer depuis un lien",
    tail: { queued: "En file", done: "Terminé", failed: "Échec", cancelled: "Annulé", interrupted: "Interrompu", unknown: "Résultat inconnu" },
    elapsed: (clock: string) => `${clock} écoulées`,
    recognized: (done: string, total: string | null) => (total ? `Reconnu : ${done} / ${total}` : `Reconnu : ${done}`),
    segments: (done: number, total: number | null) => (total != null ? `Reconnu : ${done} / ${total} segments` : `Reconnu : ${done} segments`),
    translated: (done: number, total: number | null) => (total != null ? `Traduit : ${done} / ${total} lignes` : `Traduit : ${done} lignes`),
    downloaded: (text: string) => `Téléchargé : ${text}`,
    documentWritten: "Transcription écrite dans la vidéo",
    notFinished: "Étape inachevée",
    retrying: "Nouvelle tentative automatique après erreur",
    play: "Lire",
    reveal: "Afficher dans le dossier",
    cancel: "Annuler",
    retry: "Réessayer",
    warning: {
      'no-speech': "Aucune parole détectée",
      'no-audio-track': "La vidéo n’a aucune piste audio",
      'diarization-unavailable': "Ce modèle ne distingue pas les locuteurs",
    } as Record<string, string>,
    download: {
      queued: "En attente de téléchargement",
      running: "Téléchargement de la vidéo",
      done: "Téléchargement terminé",
      failed: "Téléchargement inachevé",
      cancelled: "Téléchargement annulé",
      interrupted: "Téléchargement interrompu",
      fallbackName: "Vidéo",
    },
    openFailed: (message: string) => `Impossible d’ouvrir : ${message}`,
    retryFailed: (message: string) => `Impossible de réessayer : ${message}`,
  },

  home: {
    title: "Quelle vidéo voulez-vous créer ?",
    templates: "Modèles",
    quickStart: "Démarrage rapide",
    blankVideo: "Nouvelle vidéo vide",
    blankVideoTip: "Sans transcription ni file — directement dans l’éditeur",
    blankVideoCreated: "Vidéo vide créée",
    blankVideoFailed: (message: string) => `Impossible de créer une vidéo vide : ${message}`,

    blankVideoProject: "Vidéo vide",
    removeTemplate: "Retirer le modèle",
    templateToken: (title: string) => `Modèle : ${title}`,
    allTemplates: "Tous les modèles",
    searchTemplates: "Rechercher des modèles",
    templateKind: "Type",
    templateSource: "Source",
    templateCategories: "Catégories",
    viewTemplate: (title: string) => `Voir le modèle : ${title}`,
    useExampleLabel: (title: string) => `Utiliser le prompt : ${title}`,
    useTemplateLabel: (title: string) => `Utiliser le modèle : ${title}`,
    templatePicked: "Sélectionné",
    exampleBadge: "Exemple",
    templatePage: (page: number, pages: number, total: number) => `Page ${page} de ${pages} · ${total} au total`,
    prevPage: "Page précédente",
    nextPage: "Page suivante",
    noTemplates: "Aucun modèle correspondant. Changez mot ou catégorie.",
    templatesEmpty: "Le dossier ne contient aucun modèle.",
    templatesLoading: "Chargement des modèles…",
    templatesFailed: (message: string) => `Impossible de lire le dossier de modèles : ${message}`,
    retryTemplates: "Réessayer",
    templatesNote: "Modèles intégrés fournis ; ceux du dossier apparaissent comme « Les miens ».",
    templatesSkipped: (count: number) => (pluralForm('fr', count, { one: `${count} modèle n’a pas pu être chargé`, other: `${count} modèles n’ont pas pu être chargés` })),
    showSkipped: "Afficher le motif",
    hideSkipped: "Masquer",
    pickTemplateHint: "Choisissez un modèle à gauche pour voir aperçu et prompt.",
    templatePrompt: "Prompt",
    templatePromptLoading: "Chargement du prompt…",
    templatePromptFailed: (message: string) => `Impossible de lire le prompt : ${message}`,
    templateSay: "Essayez de dire",
    templateFields: 'À compléter',
    templateSkills: (list: string) => `Démarche : ${list}`,
    slotsLeft: (count: number, labels: string) =>
      `Encore ${count} à compléter : ${labels} · Vous pouvez envoyer quand même ; l’Agent vous posera d’abord la question`,
    fillNextSlot: 'Compléter le suivant',
    templateBriefNote: "Après sélection, l’Agent confirme sujet, objectif, public et sources avec vous, puis crée la vidéo.",
    templateAssets: "Médias",
    templatePromptOnly: "Prompt seul, sans médias",
    useTemplate: "Utiliser ce modèle",
    keepTemplate: "Continuer avec ce modèle",
    useExample: "Utiliser ce prompt",
    promptPlaced: "Prompt rempli",
    undo: "Annuler",
    playPreview: "Lire l'aperçu",
    pausePreview: "Mettre l'aperçu en pause",
    placeholder: "Décrivez la vidéo ou glissez des médias ici…",
    templatePlaceholder: "Quel sujet ? Ajoutez thème, public ou exigences…",
    localFiles: "Fichiers locaux",
    addMedia: "Vidéo ou audio",
    addDocument: "PDF ou document",
    addImage: "Images",
    recentVideos: "Vidéos récentes",

    recentReplaced: (title: string, removed: string) => `Travail sur « ${title} » ; « ${removed} »`,
    removeMaterial: (name: string) => `Retirer le média : ${name}`,
    materialsFull: (max: number, rejected: number) => `Vous pouvez ajouter au plus ${max} médias à la fois ; ${rejected} non ajoutés`,
    notLocalFile: "Ce fichier n’est pas local et ne peut pas être fourni à l’Agent",
    thisComputer: "Cet ordinateur",
    pickProject: "Choisir un projet",
    pickProjectLabel: (name: string | null) => `Choisir un projet : ${name ?? "Aucun"}`,
    currentProject: "Projet actuel",
    newProject: "Nouveau projet",
    noProject: "Sans projet, l’Agent travaille dans un dossier temporaire",
    enableFailed: (message: string) => `Impossible d’activer : ${message}`,
  },

  homeStarter: {
    sub: { title: "Ajouter des sous-titres", needs: "une vidéo", prompt: "Ajoutez des sous-titres à cette vidéo." },
    trans: { title: "Transcrire et traduire", needs: "une vidéo", prompt: "Transcrivez cette vidéo et traduisez en chinois sous forme de sous-titres bilingues." },
    clean: {
      title: "Raccourcir une vidéo face caméra",
      needs: "une vidéo",
      prompt: "Transcrivez cette vidéo et trouvez tics de langage, pauses et reprises. Montrez-moi avant de couper.",
    },
    a2v: { title: "Audio vers vidéo", needs: "un fichier audio", prompt: "Transformez cet audio en vidéo avec fond, forme d’onde et sous-titres." },
    tip: (needs: string) => `Remplit le prompt. Glissez ensuite ${needs} dans le champ de message`,
  },

  templateCategory: {
    all: "Tout",
    marketing: "Marketing",
    'product-launch': "Lancement produit",
    explainer: "Vulgarisation",
    'news-data': "Actualités et données",
    editing: "Montage",
    'creative-short': "Court créatif",
    'motion-design': "Motion design",
  },

  templateKind: { all: "Tout", scene: "Modèles de scène", example: "Exemples de démonstration" },
  templateSource: { all: "Toutes les sources", builtin: "Intégré", user: "Les miens", community: "Communauté" },

  templateAsset: { image: "Images", svg: "SVG", audio: "Audio", video: "Vidéo" },

  templateSpec: {
    allAuto: "Format et durée automatiques",
    ratioAuto: "Format automatique",
    lengthAuto: "Durée automatique",
    sceneDefault: (spec: string) => `${spec} par défaut ; pour changer, précisez-le dans votre message`,
    exampleAuto: "Format et durée automatiques, décidés par l’Agent selon votre contenu",
  },


  createProject: {
    title: "Créer un projet",
    close: "Fermer la création de projet",
    name: "Nom du projet",
    placeholder: "Nommez votre projet",
    location: "Enregistrer dans le dossier",
    preview: (path: string) => `Projet enregistré dans ${path}`,
    cancel: "Annuler",
    create: "Créer",
    created: (name: string) => `Projet créé « ${name} »`,
    failed: (message: string) => `Impossible de créer le projet : ${message}`,
  },

  taskKind: {
    agent: "Tâche de l’Agent",
    transcribe: "Transcrire",
    synthesizeSpeech: "Générer la parole",
    generateImage: "Générer une image",
    generateText: "Générer du texte",
    export: "Exporter",
    pipeline: "Flux",
    'pipeline-step': "Étape du flux",
    modelInstall: "Installer le modèle",
    modelTest: "Vérifier le modèle",
    modelsMove: "Déplacer le dossier des modèles",
    toolInstall: "Installer l’outil",
    toolUpdate: "Mettre l’outil à jour",
    fontDownload: "Télécharger la police",
    voiceClone: "Cloner la voix",
    agentTranslate: "Traduire",
    legacyImport: "Importer les anciens projets",
  },

  jobPhase: {
    queued: "En file",
    starting: "Démarrage",
    loading: "Chargement du modèle",
    decoding: "Décodage audio",
    vad: "Détection de parole",
    transcribing: "Reconnaissance",
    aligning: "Alignement des horaires",
    diarizing: "Identification des locuteurs",
    finalizing: "Finalisation",
    probing: "Lecture du média",
    encoding: "Encodage",
    downloading: "Téléchargement",
    moving: "Déplacement",
    generating: "Génération",
    validating: "Validation",
    publishing: "Enregistrement des résultats",
    applying: "Écriture dans la vidéo",
    done: "Terminé",
  },

  taskView: {
    queued: "En file",
    running: "En cours",
    awaitingApproval: "Votre approbation requise",
    cancelled: "Annulé",
    failed: "Échec",
    completed: "Terminé",
    interrupted: "Interrompu",
    needsReconciliation: "Résultat inconnu",
    retrying: "Nouvelle tentative automatique après erreur",
    costCharged: "Résultat reçu ; facturé une fois",
    costCancelUnsupported: "Annulation non prise en charge ; la requête peut finir à distance et être facturée",
    costUnknown: "Envoi incertain ; facturation possible",
    costPossible: "Facturation possible",
    chipAgent: "Agent",
    chipCli: "CLI",
    byAgent: "Session d’Agent",
    byCli: "CLI",
    byApp: "Application",
    byNode: "Nœud distant",
    local: "Cet ordinateur",
    cloud: "Cloud",
    node: "Nœud distant",
    noProject: "Sans projet",
    pageTitle: "Toutes les tâches",
    activeSection: "En cours",
    historySection: "Terminé",
    historyGroup: "Historique",
    emptyActive: "Aucune tâche en cours",
    emptyActiveBody: "Transcriptions, traductions et exports apparaissent ici.",
    emptyHistory: "Aucune tâche terminée",
    openConversation: "Ouvrir la session",
    details: "Détails",
    cancel: "Annuler",
    stop: "Arrêter",
    back: "Tâches en arrière-plan",
    notFound: "Tâche introuvable",
    notFoundBody: "Cette tâche n’est plus dans la liste",
    cancelTask: "Annuler la tâche",
    cancelExport: "Annuler l'export",
    stopTask: "Arrêter la tâche",
    cancelExportHint: "Fichier inachevé supprimé, vidéo inchangée. Après début d’enregistrement, impossible d’arrêter ; il se termine.",
    stopHint: "L’Agent s’arrête à l’étape actuelle ; fichiers déjà écrits inchangés.",
    conversationHint: "Exécution approuvée dans une session d’Agent ; conversation et approbations dans cette session.",
    agentTaskHint: "Tâche d’une session d’Agent ; conversation et approbations dans cette session.",
    cancelledBody: "La vidéo elle-même est inchangée.",
    interruptedBody: "Runtime arrêté ou redémarré avant la fin. Aucune reprise ; redémarrez si nécessaire.",
    needsReconciliationBody: "Runtime redémarré avant réponse cloud. Facturation possible ; aucun renvoi automatique.",
    configHint: "Problème de configuration ; réessayer la même méthode n’aide pas. Ajoutez le composant manquant, puis relancez.",
    sourceSection: "Source",
    imagesSection: "Images",
    outputsSection: "Résultats",
    factsSection: "Détails",
    reveal: "Afficher dans le dossier",
    open: "Ouvrir",
    copyPrompt: "Copier le prompt",
    promptCopied: "Prompt copié",
    copyFailed: "Impossible de copier. Sélectionnez et copiez manuellement",
    documentWritten: "Transcription écrite dans la vidéo",
    importedToVideo: "Importé dans la vidéo",
    imageName: (n: number) => `Image ${n}`,
    audioName: (n: number) => `Audio ${n}`,
    videoName: (n: number) => `Exporter ${n}`,
    fileName: (n: number) => `Fichier ${n}`,
    entries: (n: number) => (pluralForm('fr', n, { one: `${n} entrée`, other: `${n} entrées` })),
    packageFiles: (n: number) => (pluralForm('fr', n, { one: `Paquet portable · ${n} fichier`, other: `Paquet portable · ${n} fichiers` })),
    projectClips: (n: number) => (pluralForm('fr', n, { one: `Projet · ${n} clip`, other: `Projet · ${n} clips` })),
    documentName: "Transcription",
    stopFailed: (message: string) => `Impossible d’arrêter : ${message}`,
    cancelFailed: (message: string) => `Impossible d’annuler : ${message}`,

    reconcileRetry: "Réessayer",
    reconcileDiscard: "Abandonner ce résultat",
    reconcileApply: "Réécrire dans la vidéo",
    reconcileRetryHint: (charges: boolean): string =>
      charges ? "Rappelle le fournisseur, facturation possible à nouveau." : "Remet la même tâche en file et recommence au début.",
    reconcileDiscardHint: "Marqué annulé ; dépenses déjà engagées non remboursées.",
    reconcileApplyHint: "Résultat toujours disponible : revérifié et écrit dans la vidéo. Ouvrez-la d’abord.",
    reconcileFailed: (message: string) => `Impossible de traiter : ${message}`,
    openFailed: (message: string) => `Impossible d’ouvrir : ${message}`,
    remedyInstall: "Installer les composants",
    remedyCloud: "Configurer les modèles cloud",
    remedyDefault: "Choisir les modèles par défaut",
    remedyNode: "Voir les nœuds distants",
    remedyAgent: "Ouvrir les réglages Agent",
  },

  taskPill: {
    count: (n: number) => (pluralForm('fr', n, { one: `${n} tâche en arrière-plan`, other: `${n} tâches en arrière-plan` })),
    all: "Toutes les tâches",
    more: (n: number) => (pluralForm('fr', n, { one: `${n} autre tâche · tout voir dans Tâches en arrière-plan`, other: `${n} autres tâches · tout voir dans Tâches en arrière-plan` })),
    mine: "Cette vidéo",
    justStarted: "Vient de démarrer",
    startedAt: (ago: string) => `Démarré ${ago}`,
  },

  projectFiles: {
    region: "Fichiers du projet",

    scratchRoot: "Dossier de session",
    searchLabel: "Rechercher les fichiers du projet",
    searchPlaceholder: "Rechercher fichiers ou vidéos",
    listLabel: (where: string) => `Fichiers de « ${where} »`,
    resultsLabel: "Résultats de recherche",
    breadcrumbs: "Chemin du dossier",
    loading: "Chargement des fichiers…",
    emptyFolder: "Ce dossier est vide",
    noMatch: "Aucun fichier correspondant",
    noMatchHint: "Recherche par noms, sans fichiers cachés ni dossiers de dépendances.",
    failed: "Impossible de lire la liste des fichiers",
    retry: "Réessayer",
    truncatedList: (count: number) => `Trop de fichiers ; seulement les premiers ${count}.`,
    truncatedSearch: "Trop de résultats ; affichage partiel. Précisez la recherche.",
    inRoot: "Racine du projet",
  },

  webTab: {
    back: "Retour",
    forward: "En avant",
    stop: "Arrêter le chargement",
    reload: "Recharger la page",
    address: "Adresse web",
    placeholder: "Rechercher ou saisir une URL",
    go: "Aller",
    menu: "Options de page",
    copy: "Copier l’adresse de page",
    copied: "Adresse copiée",
    copyFailed: "Impossible de copier l’adresse",
    external: "Ouvrir dans un navigateur externe",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arrière",
    zoomReset: "Rétablir le zoom à 100 %",
    invalid: "Saisissez une URL http / https ou des termes. Aucun nom d’utilisateur ni mot de passe dans les URL.",
    loading: "Chargement de la page…",
    slow: "Chargement lent. Réessayez ou ouvrez dans un navigateur externe.",
    startTitle: "Rechercher ou ouvrir une page web",
    startBody: "Saisissez URL ou recherche ici pour continuer la conversation.",
    enterUrl: "Saisir une URL",
    stoppedTitle: "Chargement arrêté",
    failedTitle: "La page n’a pas pu être chargée",
    failedDetail: (description: string, code: number) => `${description} (${code})`,
    crashedTitle: "La page s’est fermée inopinément",
    crashedBody: "Essayez de recharger.",
    retry: "Recharger",
    blockedTitle: {
      loopback: "Adresses locales non ouvertes ici",
      scheme: "Seules les URL http / https peuvent être ouvertes",
      'app-origin': "Les pages BaoCut ne s’ouvrent pas dans un onglet web",
      invalid: "URL invalide",
    },
    blockedBody: {
      loopback: "Par sécurité, les pages intégrées n’accèdent pas aux services locaux (localhost, 127.0.0.1, etc.). Ouvrez dans un navigateur si nécessaire.",
      scheme: "Autres schémas (fichiers, liens d’application, etc.) non ouverts dans les pages intégrées.",
      'app-origin': "Les pages de l’application ne s’ouvrent pas dans un onglet web.",
      invalid: "Vérifiez l’écriture de l’URL.",
    },
    backToPage: "Retour à la page",
    footer: "Pages dans un environnement séparé sans accès à BaoCut ou services locaux ; connexions distinctes du navigateur système.",
    externalShort: "Ouvrir à l’extérieur",
    unsupportedTitle: "Pages web non intégrables ici",
    unsupportedBody: "L’application de bureau BaoCut peut naviguer directement ; pour l’instant, ouvrez dans un navigateur.",
    openInBrowser: "Ouvrir dans le navigateur",
    toolsTitle: 'Outils',
    newPageTitle: 'Nouvelle page web',
    newPageBody: 'Créer un fichier HTML dans le projet et le prévisualiser',
    browseFilesTitle: 'Parcourir les fichiers du projet',
    browseFilesBody: 'Afficher le dossier du projet dans cet onglet',
    newPageFileName: 'Nouvelle page',
    newPageHint: 'Rédigez la page ici, ou demandez à l’agent de la modifier.',
    newPageFailed: 'Impossible de créer la page web',
  },

  timelineEdit: {
    undo: "Annuler",

    pick: (verb: string) => `Sélectionnez les clips à ${verb.toLowerCase()} d’abord`,
    copied: (n: number) => (n > 1 ? `Copié : ${n} clips` : "Clip copié"),
    cut: (n: number) => (n > 1 ? `Coupé : ${n} clips` : "Clip coupé"),
    pasted: (n: number) => (n > 1 ? `Collé : ${n} clips` : "Clip collé"),
    duplicated: (n: number) => (n > 1 ? `Dupliqué : ${n} clips` : "Clip dupliqué"),
    deleted: (n: number) => (n > 1 ? `Supprimé : ${n} clips` : "Clip supprimé"),
    clipboardEmpty: (mod: string) => `Presse-papiers vide · appuyez ${mod}C pour copier un clip`,
    otherVideo: "Clips du presse-papiers issus d’une autre vidéo ; collables seulement dans celle-ci",
    selectedAtPlayhead: (n: number) => (pluralForm('fr', n, { one: `${n} clip sélectionné`, other: `Sélectionné : ${n} clips` })),
    nothingAtPlayhead: "Aucun clip à la tête de lecture",
    labelCut: "Couper les clips",
    labelPaste: "Coller les clips",
    labelDuplicate: "Dupliquer les clips",
    labelDelete: "Supprimer les clips",
    labelSplit: "Scinder le clip",
    labelNudge: "Décaler les horaires du clip",
    labelDisable: "Désactiver le clip",
    labelEnable: "Activer le clip",
    menuLabel: (name: string) => `Clip « ${name} »`,
    split: "Diviser au niveau de la tête de lecture",
    splitUnavailable: "La tête de lecture n’est pas dans ce clip",
    copy: "Copier",
    cutItem: "Couper",
    paste: "Coller",
    duplicate: "Dupliquer",
    disable: "Désactiver ce clip",
    enable: "Activer ce clip",
    disableHint: "Reste sur la timeline · ignoré dans l’image et les exports",
    enableHint: "Rétabli dans l’image et les exports",
    remove: "Supprimer",
  },

  timelineZoom: {
    menu: "Zoom",
    tip: "Options de zoom",
    in: "Zoom avant",
    out: "Zoom arrière",
    '100': "100%",
    fit: "Ajuster à la fenêtre",
    fitClip: "Ajuster au clip actuel",
    playhead: "Zoomer sur la tête de lecture",
    fitSelection: "Ajuster à la sélection",
    noClip: "Placez la tête de lecture dans un clip",
    noSelection: "Sélectionnez d’abord des clips",
  },

  shortcutSheet: {
    title: "Raccourcis clavier",
    done: "Je l'ai compris",
    hint: "Dans un champ texte, ces touches agissent sur le champ.",
    rows: [
      ["Supprimer la sélection (les trous vides sur toutes les pistes se referment)", "Supprimer"],
      ["Supprimer le passage sélectionné de toutes les pistes (la suite avance)", "⇧Supprimer"],
      ["Désélectionner / fermer la fenêtre contextuelle", "Esc"],
      ["Lecture / pause", "Space / K"],
      ["Annuler / rétablir", "⌘Z / ⇧⌘Z"],
      ["Copier / couper / coller", "⌘C / ⌘X / ⌘V"],
      ["Dupliquer", "⌘D"],
      ["Sélectionner tous les clips à la tête de lecture", "⌘A"],
      ["Tête de lecture d’une image en arrière/avant (en lecture : 5 secondes)", "← / →"],
      ["Tête de lecture d’une seconde en arrière/avant", "⇧← / ⇧→"],
      ["Reculer / avancer de 10 secondes", "J / L"],
      ["En lecture : volume +10 / −10 (augmenter rétablit le son)", "↑ / ↓"],
      ["Couper / rétablir le son", "M"],
      ["Déplacer l’élément sélectionné sur le canevas (cliquez le canevas d’abord)", "Flèches (⇧ déplace de 5 %, ⌥↑ / ⌥↓ de 0,1 %)"],
      ["Décaler l’horaire du clip (⇧ une seconde à la fois)", "⌥← / ⌥→"],
      ["Zoom timeline avant / arrière / 100 %", "⌘= / ⌘− / ⌘0"],
      ["Adapter timeline à fenêtre / clip / tête de lecture / sélection", "⌥⌘1 / ⌥⌘2 / ⌥⌘3 / ⌥⌘4"],
      ["Diviser au niveau de la tête de lecture", "S / ⌘B"],
      ["Lecture plein écran / quitter (sans sélection sur le canevas)", "F"],
      ["Mettre le clip sélectionné au premier plan / à l’arrière-plan", "F / B"],
      ["Avancer / reculer le clip sélectionné d’un niveau", "⌘↑ / ⌘↓"],
      ["Aller au début / à la fin", "Home / End"],
      ["Ouvrir les raccourcis de l’éditeur", " ?"],
    ] as [string, string][],
  },

  workspace: {
    tablist: "Onglets de travail",
    tablistHint: "Glissez pour réordonner ou Alt + Shift + Left/Right Arrow.",
    close: (name: string) => `Fermer l’onglet « ${name} »`,
    add: "Ouvrir un onglet",
    dragging: (name: string) => `Déplacement de « ${name} ». Relâchez pour déposer, Esc annule`,
    moved: (name: string) => `Déplacé « ${name} »`,
    dragCancelled: "Déplacement annulé",
    viewGroup: "Vue de travail",
    resize: "Redimensionner la colonne de session",
    conversation: "Session",

    conversationTabTip: (title: string, status: string | null) =>
      `Session « ${title} »${status ? ` · ${status}` : ""} · épinglée en tête, non déplaçable ni fermable`,
    conversationTabLabel: (title: string, status: string | null) => `Session « ${title} »${status ? `, ${status}` : ""}, épinglée en tête`,
    opening: "Ouverture de la vidéo…",
    showInSpace: "Afficher dans Space",
    reveal: "Afficher dans le dossier",
    fileMissing: "Fichier déplacé ou supprimé",
    filesNoConversation: "Les fichiers du dossier apparaissent après création de la session.",
  },

  stage: {
    label: "Objets du canevas",
    textEditor: "Modifier le texte",
    move: "Déplacer",
    resize: "Redimensionner",
    scale: "Échelle",
    rotate: "Rotation",
    rotateReset: "Réinitialiser la rotation",
    groupMove: "Déplacer ensemble",
    groupScale: "Redimensionner ensemble",
    nudge: "Décaler la position",
    edgeHeightTip: "Glisser pour la hauteur · ⌥ depuis le centre",
    edgeWidthTip: "Glisser pour la largeur · ⌥ depuis le centre",
    cornerFreeTip: "Glisser pour redimensionner · ⇧ proportions libres, ⌥ depuis le centre",
    cornerScaleTip: "Redimensionner proportionnellement · ⌥ depuis le centre",
    rotateTip: "Glisser pour tourner · pas de 15°, ⇧ rotation libre · double-clic réinitialise",
    groupCornerTip: "Tout redimensionner proportionnellement",
    picked: (n: number) => `${n} sélectionnées`,
    degrees: (n: number) => `${n}°`,
  },

  service: {
    mcp: {
      name: "Service MCP",
      scope: "Cet ordinateur uniquement",
      desc: "Permet aux applications IA de lire les vidéos et appeler les outils BaoCut",
      start: "Démarrer le service",
      stop: "Arrêter le service",
      starting: "Démarrage…",
      stopping: "Arrêt…",
    },
    remote: {
      name: "Calcul distant",
      scope: "Réseau local",
      desc: "Partage le calcul de ce Mac avec les ordinateurs du réseau local",
      start: "Commencer le partage",
      stop: "Arrêter le partage",
      starting: "Démarrage…",
      stopping: "Arrêt…",
    },
    web: {
      name: "Service web",
      scope: "Cet ordinateur uniquement",
      desc: "Ouvrir BaoCut Web dans un navigateur pour modifier les mêmes vidéos",
      start: "Démarrer le service",
      stop: "Arrêter le service",
      starting: "Démarrage…",
      stopping: "Arrêt…",
    },
    'model-api': {
      name: "API de modèles",
      scope: "Cet ordinateur uniquement",
      desc: "Permet aux outils OpenAI API d’utiliser les modèles BaoCut pour transcription, parole, images et texte",
      start: "Démarrer le service",
      stop: "Arrêter le service",
      starting: "Démarrage…",
      stopping: "Arrêt…",
    },
  },

  serviceState: {
    share: { starting: "Démarrage du partage…", stopping: "Arrêt du partage…", error: "Partage arrêté inopinément", on: "Partage actif", off: "Aucun partage" },
    service: { starting: "Démarrage…", stopping: "Arrêt…", error: "Échec du démarrage", on: "En cours", off: "Non démarré" },
    unavailable: "Pas encore disponible",
  },
  servicesPage: {
    title: "Services",
    overview: "Aperçu des services",
    lede: "Services BaoCut sur ce Mac pour connecter applications et appareils. Tous désactivés par défaut, arrêtés en quittant BaoCut.",
    allOff: "Aucun actif",
    errors: (n: number) => (pluralForm('fr', n, { one: `${n} erreur`, other: `${n} erreurs` })),
    running: (n: number) => `${n} actifs`,
    open: (name: string) => `Ouvrir ${name}`,

    restart: (verb: string) => `Re${verb.charAt(0).toLowerCase()}${verb.slice(1)}`,
    railAlert: (text: string) => `Services, ${text}`,
    railApprovals: (n: number) => (pluralForm('fr', n, { one: `Services, ${n} demande attend votre approbation`, other: `Services, ${n} demandes attendent votre approbation` })),
    loading: "Chargement de l’état…",
    disconnected: "Non connecté au Runtime BaoCut",
    failed: (message: string) => `Échec : ${message}`,

    unavailableDetail: "Cette version du Runtime ne fournit pas encore ce service",
    unavailableTitle: (name: string) => `${name} est encore indisponible`,
    notRunning: "Le service est arrêté. Démarrez-le d’abord",
    mcpRelated: "Pour apprendre les flux BaoCut à Claude Code ou Codex dans le terminal, installez le Skill BaoCut ; aucun service requis. Voir",
    mcpRelatedLink: "Réglages › Skills",
  },

  runtimeCard: {
    name: "Runtime BaoCut",
    version: "Version",
    versionValue: (runtime: string, protocol: number | string) => `${runtime} (protocole ${protocol})`,
    pid: "Processus",
    startedAt: "Démarré",
    home: "Dossier de données",
  },

  remote: {
    title: "Calcul distant",
    tabsLabel: "Vues de calcul distant",
    tabShare: "Partager ce Mac",
    tabNodes: "Utiliser d’autres ordinateurs",
    ledeShare: {
      before: "Partagez la transcription de ce Mac avec les ordinateurs locaux. ",
      strong: "Les fichiers restent sur votre réseau local",
      after: " ; seuls les résultats repartent, sans serveur.",
    },
    ledeNodes: {
      before: "Confiez la transcription à un ordinateur local plus rapide. ",
      strong: "Les fichiers restent sur votre réseau local",
      after: " ; seuls les résultats reviennent, sans serveur.",
    },

    cardOn: "Partage de ce Mac en cours",
    cardOff: "Le partage est désactivé",
    subOff: "Les autres appareils ne voient pas ce Mac.",
    subErrorFallback: "Le service de nœud n’écoute pas.",
    errorFix: "Fermez le programme utilisant ce port et redémarrez le partage, ou arrêtez si inutile.",
    foot: "Partage actif : BaoCut le reprend à sa prochaine ouverture.",
    footRight: "Le partage s’arrête quand vous quittez BaoCut.",
    privacy: "Entrées de tâches seulement sur le réseau local, résultats renvoyés ; rien ne reste sur ce Mac après la tâche.",
    offHint: "Un code de jumelage à 6 chiffres apparaît au démarrage ; saisissez-le sur l’autre appareil.",
    started: "Partage de ce Mac démarré",
    stopped: "Partage arrêté",

    nodeName: "Nom du nœud",
    address: "Adresse",
    noAddress: "Aucune adresse de réseau local",
    pairingTitle: "Code d’appairage",
    pairingHint: (left: string) => `Saisissez ce code sur l’autre appareil. Expire dans ${left}.`,
    pairingLocked: (until: string) => `Trop d’erreurs ; jumelage verrouillé jusqu’à ${until}. Générez un nouveau code pour déverrouiller.`,
    pairingNone:
      "Aucun code disponible. Régénérez après utilisation, expiration ou réouverture de BaoCut. Appareils jumelés inchangés.",
    regenerate: "Régénérer",
    generate: "Générer un code de jumelage",
    regenerated: "Nouveau code d’appairage généré",

    tasksTitle: "Tâches offertes aux autres ordinateurs",
    taskSummary: (on: number, total: number) => `Propose ${on} de ${total} types de tâches`,
    taskUnsupported: "Ce type de tâche n’est pas encore partageable",
    taskNoModel: (noun: string) => `Ce Mac n’a aucun ${noun} utilisable installé ; tâches distantes en échec`,
    taskSwitch: (name: string) => `Proposer ${name.toLowerCase()}`,
    taskOn: (name: string) => `Propose maintenant ${name.toLowerCase()}`,
    taskOff: (name: string) => `Ne propose plus ${name.toLowerCase()} · tâches déjà acceptées terminées normalement`,

    status: "Statut",
    idle: "Inactif",
    jobs: (running: number, queued: number) =>
      [running ? `${running} actifs` : "", queued ? `${queued} en file d’attente` : ""].filter(Boolean).join(" · "),

    clientsTitle: "Appareils appairés",
    clientsEmpty: "Aucun appareil jumelé avec ce Mac.",
    clientMeta: (paired: string, seen: string | null) => (seen ? `Jumelé ${paired} · Dernière présence ${seen}` : `Jumelé ${paired} · Jamais connecté`),
    revoke: "Révoquer",
    revokeLabel: (name: string) => `Révoquer « ${name} »`,
    revokeTitle: (name: string) => `Révoquer « ${name} » ?`,
    revokeBody: "Jeton invalidé immédiatement et ses tâches sur ce Mac annulées. Pour réutiliser, nouveau code de jumelage requis.",
    revoked: (name: string) => `Révoqué « ${name} »`,

    paired: "Appairé",
    pairedEmptyTitle: "Aucun nœud associé",
    pairedEmptyBody: "Activez « Partager ce Mac » ailleurs, puis jumelez ici.",
    nearby: "À proximité",
    nearbyIdle: "Cliquez « Trouver les ordinateurs proches » pour voir ceux qui partagent localement.",
    nearbyNone:
      "Aucun ordinateur partageur. Vérifiez « Partager ce Mac » et le même réseau, ou ajoutez par adresse.",
    search: "Trouver les ordinateurs proches",
    searching: "Recherche…",
    addByAddress: "Ajouter par adresse…",
    pair: "Appairer",
    pairLabel: (name: string) => `Jumeler avec « ${name} »`,
    online: "En ligne",
    offline: "Hors ligne",
    versionMismatch: "Version incompatible",
    unpaired: "Jumelage expiré",
    checking: "Vérification…",
    more: (name: string) => `Autres actions pour « ${name} »`,
    copyAddress: "Copier l’adresse",
    copied: (address: string) => `Copié : ${address}`,
    copyFailed: "Impossible de copier. Sélectionnez et copiez le texte",
    unpair: "Dissocier",
    unpairTitle: (name: string) => `Dissocier de « ${name} » ?`,
    unpairBody: "Cet ordinateur ne sera plus dans les modèles de transcription. Jumelage renouvelable à tout moment.",
    unpairDone: "Dissocié",

    problem: {
      unreachable: "Ordinateur inaccessible. Vérifiez BaoCut ouvert, « Partager ce Mac » actif et même réseau local.",
      version: "Versions BaoCut incompatibles. Mettez les deux à jour.",
      unpaired: "Jumelage invalide : autre côté révoqué, ou adresse d’un autre ordinateur. Dissociez et jumelez à nouveau.",
    },
    transcribeOff: "Transcription non proposée",
    transcribeModels: (n: number) => (n ? `Transcrire ${n}` : "Transcrire"),

    pairTitle: (name: string) => `Jumeler avec « ${name} »`,
    addTitle: "Ajouter par adresse",
    pairBody: "Lisez le code à 6 chiffres dans « Partager ce Mac » là-bas et saisissez-le ici.",
    addressLabel: "Adresse",
    addressPlaceholder: "192.168.1.31:47610",
    addressHint: (port: number) => `Nom d’hôte ou IP, port facultatif ; ${port} utilisé si omis.`,
    codeLabel: "Code d’appairage",
    codePlaceholder: "481 924",
    cancel: "Annuler",
    pairing: "Appairage…",
    pairedToast: "Jumelé · apparaît maintenant dans les modèles de transcription",
    addressEmpty: "Saisissez l’adresse de cet ordinateur",
    addressInvalid: "Adresse incorrecte : 192.168.1.31 ou 192.168.1.31:47610",
    portInvalid: "Le port doit être entre 1 et 65535",
    codeInvalid: "Le code de jumelage a 6 chiffres",
    pairErrors: {
      'pairing-code-invalid': "Code incorrect ou invalide. Demandez un nouveau code et réessayez.",
      'pairing-locked': "Trop d’erreurs ; jumelage verrouillé là-bas. Demandez un clic sur « Régénérer » pour déverrouiller.",
      version: "Versions BaoCut incompatibles. Mettez les deux à jour d’abord.",
      'source-not-allowed': "Cet ordinateur refuse les connexions depuis votre adresse.",
      lost: "Ordinateur inaccessible. Vérifiez adresse, port et « Partager ce Mac » actif.",
    },
    pairFailed: (message: string) => `Échec de jumelage : ${message}`,
  },

  remoteTask: {
    asr: { name: "Transcription", noun: "modèle de transcription" },
    tts: { name: "Voix off", noun: "modèle de doublage" },
    image: { name: "Génération d’images", noun: "modèle d’image" },
    separate: { name: "Séparation vocale", noun: "modèle de séparation" },
    download: { name: "Téléchargement vidéo", noun: null },
    export: { name: "Export vidéo", noun: null },
  },

  help: {
    title: "Centre d’aide",
    subtitle: "Consultez à tout moment pour avancer",
    close: "Fermer l’aide",
    navLabel: "Catégories d’aide",
    navTitle: "Utiliser BaoCut",
    navNote: ["Lisez seulement ce qu’il vous faut.", "Fermez pour revenir au travail."] as [string, string],
    sections: { start: "Démarrage rapide", guide: "Guides", keys: "Raccourcis clavier", faq: "FAQ" },
    searchLabel: "Rechercher dans l’aide",
    searchPlaceholder: "Recherchez quoi faire, ex. style de sous-titres",
    results: "Résultats de recherche",
    found: (n: number) => (pluralForm('fr', n, { one: `${n} guide trouvé`, other: `Trouvé : ${n} guides` })),
    emptyTitle: "Aucun guide correspondant",
    emptyBody: "Essayez « sous-titres », « médias », « Agent » ou « format », ou Démarrage rapide.",
    emptyAction: "Voir Démarrage rapide",
    welcomeEyebrow: "Nouveau ? Commencez ici",
    welcomeTitle: "Créez votre première vidéo sous-titrée",
    welcomeBody: (steps: number) => `Du clip à l’export sous-titré en ${steps} étapes.`,
    welcomeAction: "Commencer le guide de démarrage",
    welcomeDuration: (steps: number, minutes: number) => `${steps} étapes · Environ ${minutes} min de lecture`,
    pathLabel: (steps: number) => `Démarrage en ${steps} étapes`,
    pathMinutes: (minutes: number) => `${minutes} min de lecture`,
    moreTitle: "Vous pourriez aussi vouloir savoir",
    allGuides: "Tous les guides",
    keysHintLead: "Action introuvable ?",
    keysHintLink: "Voir les raccourcis clavier",
    keysHintNote: "Ouvre la liste dans l’éditeur",
    keysTitle: "Moins de clics, un peu plus vite",
    keysIntro: "Raccourcis de l’éditeur. Pendant la saisie, les touches servent d’abord au texte.",
    keysPlatform: "Style de raccourcis",
    mac: "macOS",
    other: "Windows / Linux",
    guideTitle: "Trouvez ici quoi faire",
    guideIntro: "Chaque guide traite un sujet pour retourner essayer dans votre vidéo.",
    faqTitle: "Un problème ? Commencez ici",
    faqIntro: "Vérifiez les causes courantes étape par étape.",
    minutes: (minutes: number) => `${minutes} min`,
    readTime: (minutes: number) => `À propos de ${minutes} min de lecture`,
    backToResults: "Retour aux résultats de recherche",
    backTo: (section: string) => `Retour à ${section}`,
    pickVideo: "Choisir une vidéo",
    pickVideoNote: "Ouvrez une vidéo, puis suivez le guide.",
    ctaNote: "Ouvre la fonction ; continuez vous-même.",
    backToVideo: "Retour à la vidéo",
    backNote: "Fermez l’aide et essayez dans votre vidéo.",
    next: (title: string) => `À lire ensuite : ${title}`,
    footer: "Guides intégrés · disponibles hors ligne",
    entry: "Centre d’aide · F1",
    entryLabel: "Centre d’aide",
    settingsEntry: "Aide",
  },

  previewKeys: {
    volume: (volume: number) => `Volume d’aperçu ${volume}`,
    muted: "Aperçu muet",
    unmuted: (volume: number) => `Son d’aperçu rétabli · volume ${volume}`,
    fullscreenFailed: "Impossible d’afficher l’aperçu en plein écran",
  },

  stageToolbar: {
    label: "Barre d’outils de clip",
    more: "Plus",
    back: "Retour",
    unavailable: "Pas encore disponible",
    textColor: "Couleur du texte",
    fillColor: "Couleur de remplissage",
    strokeColor: "Couleur du contour",
    strokeWidth: "Épaisseur",
    muted: "Muet",
    firstGeometry: (name: string) => `Géométrie en lecture seule, affiche le premier « ${name} » ; sélectionnez seulement celui-ci pour changer.`,
    align: "Alignement",
    alignTo: "Par rapport à",
    toSelection: "Sélection",
    toCanvas: "Canevas",
    alignLeft: "Aligner à gauche",
    alignHCenter: "Centrer horizontalement",
    alignRight: "Aligner à droite",
    alignTop: "Aligner en haut",
    alignVCenter: "Centrer verticalement",
    alignBottom: "Aligner en bas",
    distribute: "Répartir",
    distributeX: "Répartir horizontalement",
    distributeY: "Répartir verticalement",
    alignNeed: "Aligner nécessite deux clips mobiles, ou un pour le canevas.",
    distributeNeed: "Répartir nécessite trois clips mobiles.",
    labelAlign: "Aligner les clips",
    labelDistribute: "Répartir les clips",
    aligned: (n: number) => (pluralForm('fr', n, { one: `${n} clip aligné`, other: `Aligné : ${n} clips` })),
    distributed: (n: number) => (pluralForm('fr', n, { one: `${n} clip réparti`, other: `Réparti : ${n} clips` })),
    inPlace: "Déjà en place ; aucun clip à déplacer",
    duplicate: "Dupliquer",
    copy: "Copier",
    removeAll: (n: number) => (pluralForm('fr', n, { one: "Supprimer ce clip", other: `Supprimer ces ${n} clips` })),
    skipped: (n: number) =>
      `${pluralForm('fr', n, { one: `${n} clip n’est pas`, other: `${n} clips ne sont pas` })} inclus dans alignement/répartition : vidéo principale, audio et sous-titres non placés séparément sur le canevas ; clips verrouillés immobiles.`,
    dragNote: "Glissez un élément pour déplacer ensemble. Sélectionnez un clip pour changer ses propriétés.",
    hint: "Alignement, répartition, duplication et suppression comptent chacun comme une étape annulable.",
    labelFlip: "Retourner",
    labelFit: "Adapter au canevas",
    labelFill: "Remplir le canevas",
  },

  mentionGroups: {
    video: "Cette vidéo",
    files: "Vidéos et fichiers",
  },
};
