import { MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_PER_MESSAGE } from '@baocut/protocol';
import type { CopyMessages } from './copy.ts';

/** 帮助中心里「跟着这三步走」的中文数字；超出范围时用阿拉伯数字。 */
const CN_COUNT = ['零', '一', '两', '三', '四', '五', '六', '七', '八', '九', '十'];
const cnCount = (n: number) => CN_COUNT[n] ?? String(n);

export const zhHans: CopyMessages = {
  reveal: '在文件夹中显示',
  untitled: '新会话',
  sentAttachments: '已发送的文件',
  accessModeToast: (label: string) => `下一轮使用「${label}」，本轮继续按原访问模式执行。`,
  composerFoot: (name: string, account: string, foot: string) =>
    `在本机 ${name} 里运行，${account ? `用你的 ${account}` : '用你自己的订阅'}；${foot}Enter 发送，Shift+Enter 换行，@ 引用参考，/ 快捷命令。`,
  accessModeLabel: {
    plan: '先给方案',
    ask: '监督',
    autoAcceptEdits: '自动接受修改',
    auto: '自动',
    fullAccess: '完全访问',
  },
  accessModeHint: {
    plan: '只读，先给出方案；修改文件与视频一律不做',
    ask: '执行命令或修改文件前先征求许可',
    autoAcceptEdits: '自动批准文件修改，执行其他操作前先询问',
    auto: '常规操作自动批准；高风险操作仍会询问',
    fullAccess: '无需确认即可执行命令和修改文件',
  },
  taskStatusLabel: {
    running: '正在工作',
    stopping: '正在停止',
    completed: '已完成',
    stopped: '已停止',
    failed: '失败',
  },
  accessModeFoot: {
    plan: '只给方案，不改视频。',
    ask: '每次写入视频前都会先问你。',
    autoAcceptEdits: '改视频文件自动允许，其它命令仍会问你。',
    auto: '常规操作自动允许，高风险的仍会问你。',
    fullAccess: '写入视频不再逐次问你。',
  },
  modelTierLabel: { balanced: '推荐', max: '最强', fast: '最快' },
  effort: {
    low: { label: '低', sub: '快，适合小改动' },
    medium: { label: '中', sub: null },
    high: { label: '高', sub: '慢，想得更久' },
  },
  agentPicker: {
    group: '编码 Agent',
    models: '模型',
    effort: (label: string) => `推理强度 · ${label}`,
    agentDefault: 'Agent 默认模型',
    agentDefaultSub: '按 CLI 配置选择',
    configModelGate: (model: string) => `${model} 需要升级 CLI`,
    notListed: '当前列表未提供此模型',
    defaultMark: '默认',
    localAccount: '本机',
    settings: '设置 › Agent…',
    settingsSub: '编码 Agent · 订阅 · 允许策略',
    /** 会话有任务后 Agent 固定（架构设计 §3.11：原生会话不能跨 Agent 续）。 */
    locked: '这条会话已经开始，不能再换 Agent；要换请新建会话',
    detecting: '正在检测 Agent…',
  },
  driverStateReason: {
    disabled: '已在设置里停用',
    'not-installed': '未安装',
    'signed-out': '需要登录 · 去设置排查',
    outdated: '版本过旧 · 去设置排查',
    error: '无法运行 · 去设置排查',
  },
  slash: {
    polish: { label: '润色文稿', sub: '修错字、补标点、分段' },
    chapters: { label: '生成章节', sub: '按话题分章并起标题' },
    speakers: { label: '识别说话人', sub: '给字幕与文稿标上名字' },
    retranscribe: { label: '重新转录', sub: '换一个语音模型重跑音频' },
    clean: { label: '找可剪的口', sub: '口癖、长停顿、坏拍' },
    translate: { label: '翻译字幕', sub: '翻成一门语言并对齐时间码' },
    refresh: { label: '刷新过期译文', sub: '只重译原文变过的那几句' },
    dub: { label: '翻译配音', sub: '让视频用另一种语言开口' },
    summary: { label: '写总结', sub: '正文加带时间的要点' },
    blog: { label: '写博客', sub: '改写成一篇文章' },
    title: { label: '起标题', sub: '几个角度不同的候选' },
    desc: { label: '写简介', sub: '带章节时间码和标签' },
    cover: { label: '做封面', sub: '从关键帧出发做几张候选' },
    export: { label: '导出', sub: 'SRT / 烧录字幕的 MP4' },
  },
  composerMenu: {
    insert: '插入',
    filesAndFolders: '文件和文件夹',
    files: '文件', folders: '文件夹',
    filesMessage: (paths) => `文件和文件夹:\n${paths.map(path => JSON.stringify(path)).join('\n')}`,
    pickFailed: (message) => `无法选择文件: ${message}`,
    webFilesUnsupported: '本机文件和文件夹请在 BaoCut 桌面端添加；Web 客户端暂不支持上传。',
    /** 原型是「引用章节或文件」；章节、说话人这类数据 Runtime 还没有，只列视频与文件。 */
    mention: '引用视频或文件',
    slash: '使用工具',
    /** 「+」菜单的两组：附件类在上，引用与命令在下（原型 composer-insert-menu.jsx）。 */
    attachSection: '添加',
    referSection: '引用与命令',
    imagesUnsupported: (driverName: string) => `${driverName} 不接收图片`,
    noMentionCandidates: '这里还没有可以引用的视频或文件',
  },
  skill: {
    use: '使用 Skill',
    manage: '管理 Skills…',
    loading: '正在读取 Skills…',
    none: '还没有 skill：可以在设置里从本地文件夹添加，或从 GitHub 导入',
    loadFailed: '没能读取 Skills',
    token: (name: string) => `Skill：${name}`,
    remove: (name: string) => `移除 Skill：${name}`,
  },
  attachment: {
    tooLarge: `请选择不超过 ${MAX_ATTACHMENT_BYTES / 1024 / 1024} MiB 的图片`,
    tooMany: `最多附上 ${MAX_ATTACHMENTS_PER_MESSAGE} 张图片`,
    /** 原型只收 image/*；协议只收这四种（limits.ts），多出来的一句。 */
    badType: '只能附上 PNG、JPEG、GIF 或 WebP 图片',
    uploadFailed: (message: string) => `图片没能上传：${message}`,
    httpFailed: (status: number) => `上传失败（HTTP ${status}）`,
    networkFailed: '上传失败：连不上 Runtime',
    uploading: '正在上传图片…',
  },
  queue: {
    title: (count: number) => `排队等待发送 · ${count} 条`,
    images: (count: number) => `${count} 张图片`,
    edit: '编辑',
    save: '保存',
    cancel: '取消',
    remove: '删除',
    sendNow: '立即发送',
    editLabel: '修改排队的消息',
    steerUnsupported: '这个 Agent 不支持插话，会在当前任务结束后发送',
    skillWaits: '带 Skill 的消息不能插进正在进行的这一轮，会在它结束后发送',
    failed: (message: string) => `排队的消息没能发送：${message}`,
    busyPlaceholder: '智能体正在工作；现在发的话会排队，等这一轮结束再发',
  },
  recovery: {
    authTitle: (name: string) => `${name} 需要重新登录`,
    authBody: (name: string) => `登录在 ${name} 自己的窗口里完成，BaoCut 不经手你的账号和密码。登录后回到这里重新发送。`,
    openLogin: '打开终端登录',
    loginOpened: (command: string) => `已在终端里运行 ${command} · 登录完回到这里重新发送`,
    loginCopied: '没能打开终端，已复制登录命令，请在终端里粘贴运行',
    loginManual: (command: string) => `没能打开终端，请在终端里运行 ${command}`,
    modelTitle: (model: string | null) => `${model ?? '这个模型'} 现在用不了`,
    modelBody: '换一个模型重新发送；BaoCut 不会自己换模型。',
    pickModel: '换个模型重新发送',
    resend: '重新发送',
    retry: '重试',
    agentSettings: 'Agent 设置',
    nothingToResend: '找不到这一轮的消息，没法重发',
    resendFailed: (message: string) => `没能重新发送：${message}`,
  },
  approval: {
    title: {
      command: 'Agent 想要运行命令',
      'file-change': 'Agent 想要修改文件',
      tool: 'Agent 想要使用工具',
      highRisk: 'Agent 想要做一个高风险的操作',
    },
    kind: { command: '运行命令', 'file-change': '修改文件', tool: '使用工具' },
    projectFiles: '项目里的文件',
    inDir: (dir: string) => `在 ${dir}`,
    allow: '允许',
    allowAlways: (rule: string) => `总是允许 ${rule}`,
    decline: '拒绝',
    accepted: '已允许',
    acceptedAlways: (rule: string) => `已允许 · 之后 ${rule} 不再问`,
    declined: '已拒绝',
    cancelled: '已停止',
    autoRule: (rule: string | null) => (rule ? `自动允许 · 规则 ${rule}` : '自动允许 · 规则'),
    autoMode: '自动允许 · 访问模式',
    input: '输入摘要',
    copyInput: '复制输入摘要',
    failed: (message: string) => `没能提交：${message}`,
  },
  change: {
    undone: '已撤销 · 改动已还原',
    undo: '撤销',
    restore: '恢复',
    openVideo: '打开视频',
    confirmTitle: '撤销这一步？',
    /**
     * 原型是「这一跑写进视频的改动会被移除。随时可以按「恢复」放回去。」：「视频」按术语表写成「视频」；
     * 「恢复」只在这一笔还是你最近一次撤销、之后你没再改这个视频时才有（见 change-card.tsx），不说「随时」。
     */
    confirmBody: '这一步写进视频的改动会被移除。撤销之后、你接着改这个视频之前，可以按「恢复」放回去。',
    cancel: '取消',
    undoneToast: '已撤销',
    restoredToast: '已恢复',
    alreadyUndone: '这一步之前已经撤销过了',
    undoFailed: (message: string) => `没能撤销：${message}`,
    restoreFailed: (message: string) => `没能恢复：${message}`,
  },
  threadEmpty: {
    greetVideo: (name: string) => `对「${name}」做点什么？`,
    greet: '让 Agent 帮你做什么？',
    subVideo: '它会先读这个视频，给你一个计划；@ 可以引用别的视频或文件做参考。',
    sub: '先描述要做的事。它在你本机的编码 Agent 里跑，用的是你自己的订阅。',
    suggestions: '试着问问',
    chipsVideo: ['把这一章的口癖去掉', '给每章起个更短的标题', '找出可以剪掉的重复段落', '把术语统一成术语表里的写法'],
    chips: ['给这个视频加字幕并翻译成英文', '找出口癖和长停顿，先列出来再剪', '把这一期分成章节并起标题', '导出双语 SRT 和烧录字幕的 MP4'],
  },
  output: {
    playVideo: (name: string) => `播放视频「${name}」`,
    noThumbnail: '暂无缩略图',
    sourceMissing: '找不到源文件',
    openEditor: '打开编辑器',
    openVideo: (name: string) => `打开视频「${name}」`,
    playHere: '在右侧播放',
    previewHere: '在右侧预览',
    reveal: '在文件夹中显示',
    messageOutputs: '消息产物',
  },
  videoCard: {
    agentTranslating: 'Agent 逐句翻译',
    sentenceTotal: (n: number) => `共 ${n} 句`,
    status: { translating: '翻译中', transcribing: '转录中', queued: '排队中', transcribed: '已转录', failed: '失败' },
    rows: '这部视频上的活',
    retranscribe: '重新转录',
    translate: '翻译',
    linkImport: '从链接导入',
    tail: { queued: '排队中', done: '完成', failed: '失败', cancelled: '已取消', interrupted: '已中断', unknown: '结果不明' },
    elapsed: (clock: string) => `已用 ${clock}`,
    recognized: (done: string, total: string | null) => (total ? `已识别 ${done} / ${total}` : `已识别 ${done}`),
    segments: (done: number, total: number | null) => (total != null ? `已识别 ${done} / ${total} 段` : `已识别 ${done} 段`),
    translated: (done: number, total: number | null) => (total != null ? `已译 ${done} / ${total} 句` : `已译 ${done} 句`),
    downloaded: (text: string) => `已下载 ${text}`,
    documentWritten: '文稿已写进视频',
    notFinished: '这一步没有完成',
    retrying: '出错后自动重试',
    play: '播放',
    reveal: '在文件夹中显示',
    cancel: '取消',
    retry: '重试',
    warning: {
      'no-speech': '没有识别到人声',
      'no-audio-track': '视频没有音轨',
      'diarization-unavailable': '这个模型不能区分说话人',
    } as Record<string, string>,
    download: {
      queued: '等待下载',
      running: '正在下载视频',
      done: '下载完成',
      failed: '下载没有完成',
      cancelled: '下载已取消',
      interrupted: '下载中断了',
      fallbackName: '视频',
    },
    openFailed: (message: string) => `没能打开：${message}`,
    retryFailed: (message: string) => `没能重试：${message}`,
  },
  home: {
    title: '想做个什么视频？',
    templates: '模板',
    quickStart: '快捷开始',
    blankVideo: '新建空白视频',
    blankVideoTip: '不转录、不排队，直接进编辑器',
    blankVideoCreated: '空白视频已创建',
    blankVideoFailed: (message: string) => `没能新建空白视频：${message}`,
    /** 没选项目时新建空白视频，先建一个这样命名的项目。 */
    blankVideoProject: '空白视频',
    removeTemplate: '移除模板',
    templateToken: (title: string) => `模板：${title}`,
    allTemplates: '全部模板',
    searchTemplates: '搜索模板',
    templateKind: '类型',
    templateSource: '来源',
    templateCategories: '分类',
    viewTemplate: (title: string) => `查看模板：${title}`,
    useExampleLabel: (title: string) => `使用提示词：${title}`,
    useTemplateLabel: (title: string) => `使用模板：${title}`,
    templatePicked: '已选',
    exampleBadge: '示例',
    templatePage: (page: number, pages: number, total: number) => `第 ${page} / ${pages} 页 · 共 ${total} 个`,
    prevPage: '上一页',
    nextPage: '下一页',
    noTemplates: '没有找到匹配的模板，换个词或换个分类试试。',
    templatesEmpty: '模板目录里还没有模板。',
    templatesLoading: '正在读取模板…',
    templatesFailed: (message: string) => `没能读取模板目录：${message}`,
    retryTemplates: '重试',
    templatesNote: '内置模板随应用提供；放进模板目录的模板显示为「我的」。',
    templatesSkipped: (count: number) => `有 ${count} 个模板没能加载`,
    showSkipped: '查看原因',
    hideSkipped: '收起',
    pickTemplateHint: '在左边选一个模板，这里看它的预览与提示词。',
    templatePrompt: '提示词',
    templatePromptLoading: '正在读取提示词…',
    templatePromptFailed: (message: string) => `没能读取提示词：${message}`,
    templateSay: '可以这样说',
    templateFields: '需要你补充',
    templateSkills: (list: string) => `做法：${list}`,
    slotsLeft: (count: number, labels: string) => `还有 ${count} 处待填：${labels} · 不填也能发送，Agent 会先问你`,
    fillNextSlot: '填下一处',
    templateBriefNote: '选用后会先和你确认主题、目标、受众和材料，再开始制作。',
    templateAssets: '素材',
    templatePromptOnly: '只有提示词，不带素材',
    useTemplate: '使用这个模板',
    keepTemplate: '继续用这个模板',
    useExample: '使用这条提示词',
    promptPlaced: '已填入提示词',
    undo: '撤销',
    playPreview: '播放预览',
    pausePreview: '暂停预览',
    placeholder: '描述你想做的视频，或把素材拖到这里…',
    templatePlaceholder: '想讲什么内容？补充主题、受众或你的要求…',
    localFiles: '本地文件',
    addMedia: '视频或音频',
    addDocument: 'PDF 或文档',
    addImage: '图片',
    recentVideos: '最近的视频',
    /** 选了最近的视频，原先挂着的视频或音频素材让出位置（一句话只对一条视频说）。 */
    recentReplaced: (title: string, removed: string) => `已改为处理「${title}」，「${removed}」已移除`,
    removeMaterial: (name: string) => `移除素材：${name}`,
    materialsFull: (max: number, rejected: number) => `一次最多带 ${max} 份素材，${rejected} 份没有加上`,
    notLocalFile: '这份文件不在这台电脑上，没法交给 Agent',
    thisComputer: '这台电脑',
    pickProject: '选择项目',
    pickProjectLabel: (name: string | null) => `选择项目：${name ?? '未选择'}`,
    currentProject: '当前项目',
    newProject: '新建项目',
    noProject: '没选项目时，Agent 在一个临时目录里工作',
    enableFailed: (message: string) => `没能启用：${message}`,
  },
  homeStarter: {
    sub: { title: '加字幕', needs: '视频', prompt: '给这个视频加上字幕。' },
    trans: { title: '转录并翻译', needs: '视频', prompt: '转录这个视频，并翻译成中文，做成双语字幕。' },
    clean: { title: '剪口播', needs: '视频', prompt: '转录这个视频，找出口癖、长停顿和说错重来的地方，剪掉之前先让我看一遍。' },
    a2v: { title: '音频转视频', needs: '音频', prompt: '把这段音频做成视频，配上背景、声波和字幕。' },
    tip: (needs: string) => `填入提示词，再把${needs}拖进输入框`,
  },
  templateCategory: {
    all: '全部',
    marketing: '营销推广',
    'product-launch': '产品发布',
    explainer: '知识讲解',
    'news-data': '资讯与数据',
    editing: '剪辑整理',
    'creative-short': '创意短片',
    'motion-design': '动效设计',
  },
  templateKind: { all: '全部', scene: '场景模板', example: '作品示例' },
  templateSource: { all: '全部来源', builtin: '内置', user: '我的', community: '社区' },
  templateAsset: { image: '图片', svg: 'SVG', audio: '音频', video: '视频' },
  templateSpec: {
    allAuto: '画幅与时长自动',
    ratioAuto: '画幅自动',
    lengthAuto: '时长自动',
    sceneDefault: (spec: string) => `默认 ${spec}，要改就在消息里说`,
    exampleAuto: '画幅与时长自动，由 Agent 按内容决定',
  },
  createProject: {
    title: '创建项目',
    close: '关闭创建项目',
    name: '项目名称',
    placeholder: '给项目起个名字',
    location: '保存文件夹',
    preview: (path: string) => `项目将保存在 ${path}`,
    cancel: '取消',
    create: '创建',
    created: (name: string) => `已创建项目「${name}」`,
    failed: (message: string) => `没能创建项目：${message}`,
  },
  taskKind: {
    agent: 'Agent 任务',
    transcribe: '转录',
    synthesizeSpeech: '生成语音',
    generateImage: '生成图片',
    generateText: '生成文本',
    export: '导出',
    pipeline: '固定流程',
    'pipeline-step': '流程步骤',
    modelInstall: '安装模型',
    modelTest: '检查模型',
    modelsMove: '移动模型目录',
    toolInstall: '安装工具',
    toolUpdate: '更新工具',
    fontDownload: '下载字体',
    voiceClone: '克隆音色',
    agentTranslate: '翻译',
    legacyImport: '导入旧版项目',
  },
  jobPhase: {
    queued: '排队中',
    starting: '准备中',
    loading: '加载模型',
    decoding: '解码音频',
    vad: '检测人声',
    transcribing: '识别中',
    aligning: '对齐时间',
    diarizing: '区分说话人',
    finalizing: '整理结果',
    probing: '读取媒体',
    encoding: '编码中',
    downloading: '下载中',
    moving: '移动中',
    generating: '生成中',
    validating: '校验结果',
    publishing: '保存结果',
    applying: '写入视频',
    done: '已完成',
  },
  taskView: {
    queued: '排队中',
    running: '进行中',
    awaitingApproval: '需要你确认',
    cancelled: '已取消',
    failed: '失败',
    completed: '已完成',
    interrupted: '已中断',
    needsReconciliation: '结果不明',
    retrying: '出错后自动重试',
    costCharged: '已经拿到结果，按一次计费',
    costCancelUnsupported: '服务商不支持取消，请求可能照样在远端做完并计费',
    costUnknown: '不确定请求有没有发出，可能已经计费',
    costPossible: '可能已经计费',
    chipAgent: 'Agent',
    chipCli: '命令行',
    byAgent: 'Agent 会话',
    byCli: '命令行',
    byApp: 'App',
    byNode: '远端节点',
    local: '本机',
    cloud: '云端',
    node: '远端节点',
    noProject: '不属于任何项目',
    pageTitle: '全部任务',
    activeSection: '进行中',
    historySection: '已完成',
    historyGroup: '历史',
    emptyActive: '没有在跑的任务',
    emptyActiveBody: '转录、翻译与导出都会出现在这里。',
    emptyHistory: '还没有完成的任务',
    openConversation: '打开会话',
    details: '详情',
    cancel: '取消',
    stop: '停止',
    back: '后台任务',
    notFound: '任务不存在',
    notFoundBody: '这个任务已经不在列表里了',
    cancelTask: '取消任务',
    cancelExport: '取消导出',
    stopTask: '停止任务',
    cancelExportHint: '没写完的文件会删掉，视频本身不受影响。已经开始保存文件时停不下来，会照常保存完。',
    stopHint: '智能体停在当前这一步；已经写进项目的文件不受影响。',
    conversationHint: '这一跑是 Agent 会话里允许后执行的；对话与允许记录都在会话里。',
    agentTaskHint: '这个任务在 Agent 会话里；对话与允许记录都在会话里。',
    cancelledBody: '视频本身不受影响。',
    interruptedBody: 'Runtime 停止或重启时这一跑还没做完，不会续跑；需要的话重新发起。',
    needsReconciliationBody: 'Runtime 重启时这次云端调用还没有回音，可能已经计费；不会自动重发。',
    configHint: '这是配置问题，重试同一条链路不会好。先补上缺的组件，再跑一次。',
    sourceSection: '来源',
    imagesSection: '图片',
    outputsSection: '产物',
    factsSection: '详情',
    reveal: '在文件夹中显示',
    open: '打开',
    copyPrompt: '复制提示词',
    promptCopied: '已复制提示词',
    copyFailed: '没能复制，请手动选中复制',
    documentWritten: '文稿已写进视频',
    importedToVideo: '已导入视频',
    imageName: (n: number) => `图片 ${n}`,
    audioName: (n: number) => `语音 ${n}`,
    videoName: (n: number) => `成片 ${n}`,
    fileName: (n: number) => `文件 ${n}`,
    entries: (n: number) => `${n} 条`,
    packageFiles: (n: number) => `便携包 · ${n} 个文件`,
    projectClips: (n: number) => `工程 · ${n} 个片段`,
    documentName: '文稿',
    stopFailed: (message: string) => `没能停止：${message}`,
    cancelFailed: (message: string) => `没能取消：${message}`,
    /** 对账（`jobs.reconcile`）：重启后结果不明、中断或没有写进视频的任务，由用户决定。 */
    reconcileRetry: '再试一次',
    reconcileDiscard: '放弃这次结果',
    reconcileApply: '重新写入视频',
    reconcileRetryHint: (charges: boolean) => (charges ? '会重新调用一次服务商，可能再次计费。' : '同一个任务重新排队，从头再跑一次。'),
    reconcileDiscardHint: '记为已取消；可能已经发生的费用不退。',
    reconcileApplyHint: '产物还在：重新校验后写进视频。要先打开这个视频。',
    reconcileFailed: (message: string) => `没能处理：${message}`,
    openFailed: (message: string) => `没能打开：${message}`,
    remedyInstall: '去补装组件',
    remedyCloud: '去设置云端模型',
    remedyDefault: '去选默认模型',
    remedyNode: '去看远端节点',
    remedyAgent: '去 Agent 设置',
  },
  taskPill: {
    count: (n: number) => `${n} 个后台任务`,
    all: '全部任务',
    more: (n: number) => `还有 ${n} 个任务 · 在后台任务里看全部`,
    mine: '这个视频',
    justStarted: '刚开始',
    startedAt: (ago: string) => `${ago}开始`,
  },
  projectFiles: {
    region: '项目文件',
    /** 不属于项目的会话：根目录是它自己的工作目录。 */
    scratchRoot: '会话文件夹',
    searchLabel: '查找项目文件',
    searchPlaceholder: '查找文件或视频',
    listLabel: (where: string) => `「${where}」里的文件`,
    resultsLabel: '查找结果',
    breadcrumbs: '文件夹路径',
    loading: '正在读取文件…',
    emptyFolder: '这个文件夹是空的',
    noMatch: '没有匹配的文件',
    noMatchHint: '查找按文件名匹配，跳过隐藏文件与依赖目录。',
    failed: '没能读取文件列表',
    retry: '重试',
    truncatedList: (count: number) => `文件太多，只列出了前 ${count} 项。`,
    truncatedSearch: '匹配的文件太多，只列出了一部分；换个更具体的词试试。',
    inRoot: '项目根目录',
  },
  webTab: {
    back: '后退',
    forward: '前进',
    stop: '停止加载',
    reload: '重新加载网页',
    address: '网页地址',
    placeholder: '搜索或输入网址',
    go: '前往',
    menu: '网页选项',
    copy: '复制网页地址',
    copied: '已复制网页地址',
    copyFailed: '没能复制网页地址',
    external: '在外部浏览器打开',
    zoomIn: '放大',
    zoomOut: '缩小',
    zoomReset: '恢复 100% 缩放',
    invalid: '请输入 http / https 网址或搜索词；网址不能包含账号密码。',
    loading: '正在加载网页…',
    slow: '网页加载较慢，可重试或在外部浏览器打开。',
    startTitle: '搜索或打开网页',
    startBody: '输入网址或搜索词，在这里查看资料并继续对话。',
    enterUrl: '输入网址',
    stoppedTitle: '已停止加载',
    failedTitle: '网页未能加载',
    failedDetail: (description: string, code: number) => `${description}（${code}）`,
    crashedTitle: '网页意外退出了',
    crashedBody: '重新加载试试。',
    retry: '重新加载',
    blockedTitle: {
      loopback: '本机地址不在这里打开',
      scheme: '只能打开 http / https 网址',
      'app-origin': '不能在网页标签里打开 BaoCut 自己的页面',
      invalid: '这个网址无效',
    },
    blockedBody: {
      loopback: '为了安全，内嵌网页不访问本机服务（localhost、127.0.0.1 等）。需要时在浏览器中打开。',
      scheme: '其它协议（文件、应用链接等）不在内嵌网页里打开。',
      'app-origin': '应用自己的页面不在网页标签里打开。',
      invalid: '检查一下网址的写法。',
    },
    backToPage: '回到网页',
    footer: '网页在独立的环境里打开，读不到 BaoCut 与本机服务；登录状态与系统浏览器分开。',
    externalShort: '外部打开',
    unsupportedTitle: '这个环境不能内嵌网页',
    unsupportedBody: '在 BaoCut 桌面版里可以直接浏览网页；这里可以先在浏览器中打开。',
    openInBrowser: '在浏览器中打开',
    toolsTitle: '工具',
    newPageTitle: '新建网页',
    newPageBody: '在项目里新建一个 HTML 文件并预览',
    browseFilesTitle: '浏览项目文件',
    browseFilesBody: '在这个标签页里查看项目目录',
    newPageFileName: '新网页',
    newPageHint: '在这里编写网页内容，也可以让 Agent 帮你修改。',
    newPageFailed: '未能新建网页',
  },
  timelineEdit: {
    undo: '撤销',
    pick: (verb: string) => `先选中要${verb}的片段`,
    copied: (n: number) => (n > 1 ? `已复制 ${n} 个片段` : '已复制片段'),
    cut: (n: number) => (n > 1 ? `已剪切 ${n} 个片段` : '已剪切片段'),
    pasted: (n: number) => (n > 1 ? `已粘贴 ${n} 个片段` : '已粘贴片段'),
    duplicated: (n: number) => (n > 1 ? `已再制 ${n} 个片段` : '已再制片段'),
    deleted: (n: number) => (n > 1 ? `已删除 ${n} 个片段` : '已删除片段'),
    clipboardEmpty: (mod: string) => `剪贴板是空的 · 先按 ${mod}C 复制一个片段`,
    otherVideo: '剪贴板里的片段来自另一个视频 · 只能粘回原来的视频',
    selectedAtPlayhead: (n: number) => `已选中 ${n} 个片段`,
    nothingAtPlayhead: '播放头这一刻没有片段',
    labelCut: '剪切片段',
    labelPaste: '粘贴片段',
    labelDuplicate: '再制片段',
    labelDelete: '删除片段',
    labelSplit: '拆分片段',
    labelNudge: '微调片段时间',
    labelDisable: '停用片段',
    labelEnable: '启用片段',
    menuLabel: (name: string) => `片段「${name}」`,
    split: '在播放头分割',
    splitUnavailable: '播放头不在这一段里',
    copy: '复制',
    cutItem: '剪切',
    paste: '粘贴',
    duplicate: '再制',
    disable: '停用这个片段',
    enable: '启用这个片段',
    disableHint: '留在时间线上 · 画面与导出都跳过',
    enableHint: '回到画面与导出里',
    remove: '删除',
  },
  timelineZoom: {
    menu: '缩放',
    tip: '缩放选项',
    in: '放大',
    out: '缩小',
    '100': '100%',
    fit: '适应窗口',
    fitClip: '适应当前片段',
    playhead: '缩放到播放头',
    fitSelection: '适应所选',
    noClip: '把播放头移到一段视频内',
    noSelection: '先在时间线上选中片段',
  },
  shortcutSheet: {
    title: '快捷键',
    done: '知道了',
    hint: '光标在输入框里时这些键全部让位给输入。',
    rows: [
      ['删除选中', 'Delete'],
      ['取消选中 / 关闭弹层', 'Esc'],
      ['播放 / 暂停', 'Space / K'],
      ['撤销 / 重做', '⌘Z / ⇧⌘Z'],
      ['复制 / 剪切 / 粘贴', '⌘C / ⌘X / ⌘V'],
      ['再制', '⌘D'],
      ['全选播放头下的片段', '⌘A'],
      ['播放头前后一帧（播放中：前后 5 秒）', '← / →'],
      ['播放头前后一秒', '⇧← / ⇧→'],
      ['后退 / 前进 10 秒', 'J / L'],
      ['播放中：音量 +10 / −10（调大自动取消静音）', '↑ / ↓'],
      ['静音 / 取消静音', 'M'],
      ['微调画面上选中元素的位置（先点一下画面）', '方向键（⇧ 走 5%，⌥↑ / ⌥↓ 走 0.1%）'],
      ['微调选中片段的时间（⇧ 一次一秒）', '⌥← / ⌥→'],
      ['时间线放大 / 缩小 / 100%', '⌘= / ⌘− / ⌘0'],
      ['时间线适应窗口 / 当前片段 / 播放头 / 所选', '⌥⌘1 / ⌥⌘2 / ⌥⌘3 / ⌥⌘4'],
      ['在播放头处分割', 'S / ⌘B'],
      ['全屏播放 / 退出全屏（画布上没有选中片段时）', 'F'],
      ['选中的片段移到最前 / 移到最后', 'F / B'],
      ['选中的片段前移一层 / 后移一层', '⌘↑ / ⌘↓'],
      ['跳到片头 / 片尾', 'Home / End'],
      ['打开编辑器快捷键清单', '?'],
    ],
  },
  workspace: {
    tablist: '工作区标签页',
    tablistHint: '拖动标签调整顺序，也可按 Alt + Shift + 左右方向键。',
    close: (name: string) => `关闭标签页「${name}」`,
    add: '打开新标签页',
    dragging: (name: string) => `正在拖动「${name}」，松开放置，Esc 取消`,
    moved: (name: string) => `已移动「${name}」`,
    dragCancelled: '已取消拖动',
    viewGroup: '工作区视图',
    resize: '调整会话宽度',
    conversation: '会话',
    conversationTabTip: (title: string, status: string | null) =>
      `会话「${title}」${status ? ` · ${status}` : ''} · 固定在第一位，不能拖动或关闭`,
    conversationTabLabel: (title: string, status: string | null) => `会话「${title}」${status ? `，${status}` : ''}，固定在第一位`,
    opening: '正在打开视频…',
    showInSpace: '在 Space 中显示',
    reveal: '在文件夹中显示',
    fileMissing: '文件已移走或删除',
    filesNoConversation: '会话建好之后，这里列出它所在目录里的文件。',
  },
  stage: {
    label: '画面上的对象',
    textEditor: '改文字',
    move: '移动',
    resize: '调整大小',
    scale: '缩放',
    rotate: '旋转',
    rotateReset: '旋转归零',
    groupMove: '整体移动',
    groupScale: '整体缩放',
    nudge: '微调位置',
    edgeHeightTip: '拖动改高度 · ⌥ 以中心对称',
    edgeWidthTip: '拖动改宽度 · ⌥ 以中心对称',
    cornerFreeTip: '拖动改大小 · ⇧ 解锁比例、⌥ 以中心对称',
    cornerScaleTip: '等比缩放 · ⌥ 以中心对称',
    rotateTip: '拖动旋转 · 15° 吸附，⇧ 自由 · 双击归零',
    groupCornerTip: '整体等比缩放',
    picked: (n: number) => `已选 ${n} 个`,
    degrees: (n: number) => `${n}°`,
  },
  service: {
    mcp: {
      name: 'MCP 服务',
      scope: '仅本机',
      desc: '让其他 AI 应用读取视频、调用 BaoCut 工具',
      start: '启动服务',
      stop: '停止服务',
      starting: '正在启动…',
      stopping: '正在停止…',
    },
    remote: {
      name: '远端算力',
      scope: '局域网',
      desc: '把这台 Mac 的算力共享给局域网里的其他电脑',
      start: '开始共享',
      stop: '停止共享',
      starting: '正在开始…',
      stopping: '正在停止…',
    },
    web: {
      name: 'Web 服务',
      scope: '仅本机',
      desc: '在浏览器里打开 BaoCut Web，编辑同一批视频',
      start: '启动服务',
      stop: '停止服务',
      starting: '正在启动…',
      stopping: '正在停止…',
    },
    'model-api': {
      name: '模型接口',
      scope: '仅本机',
      desc: '让支持 OpenAI 接口的工具用 BaoCut 能用的模型转录、配音、出图与生成文本',
      start: '启动服务',
      stop: '停止服务',
      starting: '正在启动…',
      stopping: '正在停止…',
    },
  },
  serviceState: {
    share: { starting: '正在开始共享…', stopping: '正在停止共享…', error: '共享意外停止', on: '正在共享', off: '未共享' },
    service: { starting: '正在启动…', stopping: '正在停止…', error: '启动失败', on: '运行中', off: '未启动' },
    unavailable: '尚未提供',
  },
  servicesPage: {
    title: '服务',
    overview: '服务总览',
    lede: '这台 Mac 上由 BaoCut 提供、等别的应用或设备连进来的服务。都默认关闭；退出 BaoCut 时一起停止。',
    allOff: '全部未启动',
    errors: (n: number) => `${n} 项出错`,
    running: (n: number) => `${n} 项运行中`,
    open: (name: string) => `打开${name}`,
    restart: (verb: string) => `重新${verb}`,
    railAlert: (text: string) => `服务，${text}`,
    railApprovals: (n: number) => `服务，${n} 个请求等你确认`,
    loading: '正在读取状态…',
    disconnected: '没有连上 BaoCut Runtime',
    failed: (message: string) => `操作没有成功：${message}`,
    /** Runtime 列出了、但这个版本没有提供的服务（`available: false`）：总览行与详情页说清楚为什么不能起停。 */
    unavailableDetail: '这个版本的 BaoCut Runtime 还没有提供这项服务',
    unavailableTitle: (name: string) => `${name}尚未提供`,
    notRunning: '服务没有开着，先启动它',
    mcpRelated: '想让终端里的 Claude Code、Codex 学会 BaoCut 的工作流？那要给它们装 BaoCut 的 skill，不需要启动服务，说明在',
    mcpRelatedLink: '设置 › Skills',
  },
  runtimeCard: {
    name: 'BaoCut Runtime',
    version: '版本',
    versionValue: (runtime: string, protocol: number | string) => `${runtime}（协议 ${protocol}）`,
    pid: '进程',
    startedAt: '启动于',
    home: '数据目录',
  },
  remote: {
    title: '远端算力',
    tabsLabel: '远端算力的两面',
    tabShare: '共享这台 Mac',
    tabNodes: '使用其他电脑',
    ledeShare: { before: '把这台 Mac 的转录能力共享给局域网里的其他电脑。', strong: '文件只在你的局域网内传输', after: '，只有结果送回去——不经过任何服务器。' },
    ledeNodes: { before: '把转录交给局域网里另一台更快的电脑。', strong: '文件只在你的局域网内传输', after: '，只有结果回来——不经过任何服务器。' },

    cardOn: '正在共享这台 Mac',
    cardOff: '共享已关闭',
    subOff: '其他设备看不到这台 Mac。',
    subErrorFallback: '节点服务没有在监听。',
    errorFix: '先关掉占用这个端口的程序，再重新开始共享；不想共享了就停止。',
    foot: '开着共享时，下次打开 BaoCut 会自动继续共享。',
    footRight: '退出 BaoCut 时共享会一起停止。',
    privacy: '任务的输入只在局域网内传输，只有结果送回去；任务结束后不在这台 Mac 上留下任何内容。',
    offHint: '开始共享后会显示一个 6 位配对码，对方输入即可连上。',
    started: '已开始共享这台 Mac',
    stopped: '已停止共享',

    nodeName: '节点名',
    address: '地址',
    noAddress: '没有可用的局域网地址',
    pairingTitle: '配对码',
    pairingHint: (left: string) => `在对方设备上输入这个码。${left}后失效。`,
    pairingLocked: (until: string) => `输错次数太多，配对已锁定到 ${until}。重新生成配对码可以立即解锁。`,
    pairingNone: '现在没有可用的配对码：配对码用过一次、过期或重新打开 BaoCut 后都要重新生成。已配对的设备不受影响。',
    regenerate: '重新生成',
    generate: '生成配对码',
    regenerated: '已生成新的配对码',

    tasksTitle: '提供给其他电脑的任务',
    taskSummary: (on: number, total: number) => `提供 ${on} / ${total} 类任务`,
    taskUnsupported: '这个版本还不能共享这类任务',
    taskNoModel: (noun: string) => `这台 Mac 还没装可用的${noun}，对方发来的这类任务会失败`,
    taskSwitch: (name: string) => `提供${name}`,
    taskOn: (name: string) => `已开始提供${name}`,
    taskOff: (name: string) => `已停止提供${name} · 已经接下的任务照常跑完`,

    status: '状态',
    idle: '空闲',
    jobs: (running: number, queued: number) =>
      [running ? `${running} 个任务在跑` : '', queued ? `${queued} 个排队` : ''].filter(Boolean).join(' · '),

    clientsTitle: '已配对的设备',
    clientsEmpty: '还没有设备与这台 Mac 配对。',
    clientMeta: (paired: string, seen: string | null) => (seen ? `${paired}配对 · ${seen}见过` : `${paired}配对 · 还没连过`),
    revoke: '吊销',
    revokeLabel: (name: string) => `吊销「${name}」`,
    revokeTitle: (name: string) => `吊销「${name}」？`,
    revokeBody: '它的令牌立即失效，它交给这台 Mac 的任务会取消。要再用，对方得重新输入配对码。',
    revoked: (name: string) => `已吊销「${name}」`,

    paired: '已配对',
    pairedEmptyTitle: '还没有配对的节点',
    pairedEmptyBody: '在另一台电脑上打开「共享这台 Mac」，再从这里配对。',
    nearby: '附近',
    nearbyIdle: '点「查找附近的电脑」，看看局域网里有哪些电脑开着共享。',
    nearbyNone: '没有找到开着共享的电脑。确认对方打开了「共享这台 Mac」、两台电脑在同一个局域网里；也可以按地址添加。',
    search: '查找附近的电脑',
    searching: '正在查找…',
    addByAddress: '按地址添加…',
    pair: '配对',
    pairLabel: (name: string) => `与「${name}」配对`,
    online: '在线',
    offline: '离线',
    versionMismatch: '版本不兼容',
    unpaired: '配对已失效',
    checking: '正在检查…',
    more: (name: string) => `「${name}」的更多操作`,
    copyAddress: '复制地址',
    copied: (address: string) => `已复制 ${address}`,
    copyFailed: '复制失败，请选中文字后复制',
    unpair: '取消配对',
    unpairTitle: (name: string) => `取消与「${name}」的配对？`,
    unpairBody: '这台电脑之后不再出现在转录的模型列表里。随时可以重新配对。',
    unpairDone: '已取消配对',
    /** 节点卡上「为什么用不了」：按 `PairedNode.problem` 拼（没有诊断方法，不叫「诊断」）。 */
    problem: {
      unreachable: '连不上这台电脑：确认它开着 BaoCut 并打开了「共享这台 Mac」，两台电脑在同一个局域网里。',
      version: '两台电脑的 BaoCut 版本不兼容：把两边都更新到最新版本。',
      unpaired: '配对已经失效：对方吊销了这台电脑，或这个地址上换了另一台电脑。取消配对后重新配对。',
    },
    transcribeOff: '没有开放转录',
    transcribeModels: (n: number) => (n ? `转录 ${n}` : '转录'),

    pairTitle: (name: string) => `与「${name}」配对`,
    addTitle: '按地址添加',
    pairBody: '在那台电脑的「共享这台 Mac」里读出 6 位配对码，输在这里。',
    addressLabel: '地址',
    addressPlaceholder: '192.168.1.31:47610',
    addressHint: (port: number) => `主机名或 IP，后面可以跟端口；不写端口时用 ${port}。`,
    codeLabel: '配对码',
    codePlaceholder: '481 924',
    cancel: '取消',
    pairing: '正在配对…',
    pairedToast: '已配对 · 它现在会出现在转录的模型列表里',
    addressEmpty: '填上那台电脑的地址',
    addressInvalid: '地址的格式不对：写成 192.168.1.31 或 192.168.1.31:47610',
    portInvalid: '端口要填 1–65535 之间的数字',
    codeInvalid: '配对码是 6 位数字',
    pairErrors: {
      'pairing-code-invalid': '配对码不对，或已经失效。请对方重新生成后再试。',
      'pairing-locked': '输错次数太多，那台电脑暂时锁定了配对。请对方点「重新生成」解锁。',
      version: '两台电脑的 BaoCut 版本不兼容，先把两边都更新到最新版本。',
      'source-not-allowed': '那台电脑不接受来自这台电脑地址的连接。',
      lost: '连不上那台电脑：确认地址和端口，并且它开着「共享这台 Mac」。',
    },
    pairFailed: (message: string) => `配对没有成功：${message}`,
  },
  remoteTask: {
    asr: { name: '转录', noun: '转录模型' },
    tts: { name: '配音', noun: '配音模型' },
    image: { name: '生成图片', noun: '图像模型' },
    separate: { name: '分离人声', noun: '分离模型' },
    download: { name: '下载视频', noun: null },
    export: { name: '导出视频', noun: null },
  },
  help: {
    title: '帮助中心',
    subtitle: '随时查阅，轻松上手',
    close: '关闭帮助',
    navLabel: '帮助分类',
    navTitle: '使用 BaoCut',
    navNote: ['按需阅读就好。', '关闭后回到原来的工作。'],
    sections: { start: '快速上手', guide: '操作指南', keys: '快捷键', faq: '常见问题' },
    searchLabel: '搜索帮助',
    searchPlaceholder: '搜索你想做的事，例如：字幕样式',
    results: '搜索结果',
    found: (n: number) => `找到 ${n} 篇指南`,
    emptyTitle: '没有找到相关指南',
    emptyBody: '试试「字幕」「素材」「Agent」或「画幅」，也可以从快速上手开始。',
    emptyAction: '查看快速上手',
    welcomeEyebrow: '第一次使用？从这里开始',
    welcomeTitle: '做出你的第一条字幕视频',
    welcomeBody: (steps: number) => `从一段素材到带字幕的成片，跟着这${cnCount(steps)}步走。`,
    welcomeAction: '开始入门指南',
    welcomeDuration: (steps: number, minutes: number) => `${steps} 步 · 约 ${minutes} 分钟阅读`,
    pathLabel: (steps: number) => `入门${cnCount(steps)}步`,
    pathMinutes: (minutes: number) => `${minutes} 分钟阅读`,
    moreTitle: '你可能还想了解',
    allGuides: '全部指南',
    keysHintLead: '找不到某个操作？',
    keysHintLink: '查看快捷键',
    keysHintNote: '在编辑器中打开清单',
    keysTitle: '少点几次，更快一点',
    keysIntro: '以下快捷键在编辑器中使用。正在输入文字时，按键优先用于文本编辑。',
    keysPlatform: '快捷键写法',
    mac: 'macOS',
    other: 'Windows / Linux',
    guideTitle: '想做什么，就从这里找',
    guideIntro: '每篇只讲一件事，读完就能回到视频里试一试。',
    faqTitle: '遇到问题，先看看这里',
    faqIntro: '从最常见的原因开始，一步步检查。',
    minutes: (minutes: number) => `${minutes} 分钟`,
    readTime: (minutes: number) => `约 ${minutes} 分钟阅读`,
    backToResults: '返回搜索结果',
    backTo: (section: string) => `返回${section}`,
    pickVideo: '选择一个视频',
    pickVideoNote: '先打开视频，再按指南操作。',
    ctaNote: '打开对应功能，由你开始操作。',
    backToVideo: '回到视频',
    backNote: '关闭帮助，回到视频里试一试。',
    next: (title: string) => `继续阅读：${title}`,
    footer: '内置指南 · 可离线阅读',
    entry: '帮助中心 · F1',
    entryLabel: '帮助中心',
    settingsEntry: '帮助',
  },
  previewKeys: {
    volume: (volume: number) => `预览音量 ${volume}`,
    muted: '预览已静音',
    unmuted: (volume: number) => `预览取消静音 · 音量 ${volume}`,
    fullscreenFailed: '没能把预览放到全屏',
  },
  stageToolbar: {
    label: '片段工具条',
    more: '更多',
    back: '返回',
    unavailable: '现在还不能用',
    textColor: '文字颜色',
    fillColor: '填充颜色',
    strokeColor: '描边颜色',
    strokeWidth: '粗细',
    muted: '已静音',
    firstGeometry: (name: string) => `几何只读，显示第一个「${name}」；要改数值请只选它。`,
    align: '对齐',
    alignTo: '参照',
    toSelection: '选区',
    toCanvas: '画布',
    alignLeft: '左对齐',
    alignHCenter: '水平居中',
    alignRight: '右对齐',
    alignTop: '顶对齐',
    alignVCenter: '垂直居中',
    alignBottom: '底对齐',
    distribute: '分布',
    distributeX: '水平等距',
    distributeY: '垂直等距',
    alignNeed: '对齐至少要两个能挪的片段；参照画布时一个也行。',
    distributeNeed: '等距分布至少要三个能挪的片段。',
    labelAlign: '对齐片段',
    labelDistribute: '分布片段',
    aligned: (n: number) => `已对齐 ${n} 个片段`,
    distributed: (n: number) => `已分布 ${n} 个片段`,
    inPlace: '已经在这个位置了，没有要挪的片段',
    duplicate: '复制一份',
    copy: '拷贝',
    removeAll: (n: number) => `删除这 ${n} 个片段`,
    skipped: (n: number) => `有 ${n} 个不参与对齐与分布：主视频、音频与字幕不在画布上单独摆放，锁定的片段不动。`,
    dragNote: '在画面上拖动其中一个，它们一起移动。逐个改属性请只选一个片段。',
    hint: '对齐、分布、复制与删除都只记一步撤销。',
    labelFlip: '翻转',
    labelFit: '适应画布',
    labelFill: '填满画布',
  },
  mentionGroups: {
    video: '这个视频',
    files: '视频与文件',
  },
};
