import { MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_PER_MESSAGE } from '@baocut/protocol';
import type { CopyMessages } from './copy.ts';

const CN_COUNT = ['零', '一', '兩', '三', '四', '五', '六', '七', '八', '九', '十'];
const cnCount = (n: number) => CN_COUNT[n] ?? String(n);

export const zhHant: CopyMessages = {
  reveal: '在資料夾中顯示',
  untitled: '新對話',
  sentAttachments: '已傳送的檔案',
  accessModeToast: (label: string) => `下一輪會使用「${label}」，這一輪繼續沿用目前的存取模式。`,
  composerFoot: (name: string, account: string, foot: string) =>
    `在這台電腦的 ${name} 中執行，${account ? `使用你的 ${account}` : '使用你自己的訂閱'}；${foot}Enter 傳送，Shift+Enter 換行，@ 引用，/ 指令。`,
  accessModeLabel: {
    plan: '先提方案',
    ask: '監督',
    autoAcceptEdits: '自動接受修改',
    auto: '自動',
    fullAccess: '完全存取',
  },
  accessModeHint: {
    plan: '唯讀，先提出方案；不會修改任何檔案或影片',
    ask: '執行指令或修改檔案前先徵求你的許可',
    autoAcceptEdits: '自動核准檔案修改，其他動作會先詢問',
    auto: '一般動作自動核准；有風險的動作仍會詢問',
    fullAccess: '執行指令和修改檔案都不再詢問',
  },
  taskStatusLabel: {
    running: '處理中',
    stopping: '正在停止',
    completed: '已完成',
    stopped: '已停止',
    failed: '失敗',
  },
  accessModeFoot: {
    plan: '只提方案，不修改影片。',
    ask: '每次寫入影片前都會先詢問你。',
    autoAcceptEdits: '修改影片檔案會自動允許，其他指令仍會詢問你。',
    auto: '一般動作會自動允許，有風險的仍會詢問你。',
    fullAccess: '寫入影片不再逐次詢問你。',
  },
  modelTierLabel: { balanced: '推薦', max: '最強', fast: '最快' },
  effort: {
    low: { label: '低', sub: '快速，適合小修改' },
    medium: { label: '中', sub: null },
    high: { label: '高', sub: '較慢，思考得更久' },
  },
  agentPicker: {
    group: '程式設計 Agent',
    models: '模型',
    effort: (label: string) => `推理強度 · ${label}`,
    agentDefault: 'Agent 的預設模型',
    agentDefaultSub: '依 CLI 的設定選擇',
    configModelGate: (model: string) => `${model} 需要更新版的 CLI`,
    notListed: '目前的清單中沒有這個模型',
    defaultMark: '預設',
    localAccount: '這台電腦',
    settings: '設定 › Agent…',
    settingsSub: '程式設計 Agent · 訂閱 · 核准原則',
    locked: '這段對話已經開始，無法再更換 Agent；要更換請開始新對話',
    detecting: '正在偵測 Agent…',
  },
  driverStateReason: {
    disabled: '已在設定中停用',
    'not-installed': '未安裝',
    'signed-out': '需要重新登入 · 到設定中檢查',
    outdated: '版本過舊 · 到設定中檢查',
    error: '無法執行 · 到設定中檢查',
  },
  slash: {
    polish: { label: '潤飾逐字稿', sub: '修正錯字、補上標點、分段' },
    chapters: { label: '產生章節', sub: '依主題分章並加上標題' },
    speakers: { label: '辨識說話者', sub: '在字幕與逐字稿上標出名字' },
    retranscribe: { label: '重新轉錄', sub: '換一個語音模型重跑音訊' },
    clean: { label: '找出可剪片段', sub: '贅字、長停頓、說錯重來的地方' },
    translate: { label: '翻譯字幕', sub: '翻譯成一種語言並對齊時間碼' },
    refresh: { label: '更新過期譯文', sub: '只重新翻譯原文有變動的句子' },
    dub: { label: '翻譯配音', sub: '讓影片說另一種語言' },
    summary: { label: '寫摘要', sub: '摘要加上附時間的重點' },
    blog: { label: '寫部落格文章', sub: '改寫成一篇文章' },
    title: { label: '建議標題', sub: '幾個角度不同的候選' },
    desc: { label: '寫簡介', sub: '附章節時間碼和標籤' },
    cover: { label: '做封面', sub: '從關鍵影格做幾張候選' },
    export: { label: '匯出', sub: 'SRT / 燒錄字幕的 MP4' },
  },
  composerMenu: {
    insert: '插入',
    filesAndFolders: '檔案和資料夾',
    files: '檔案', folders: '資料夾',
    filesMessage: (paths) => `檔案和資料夾:\n${paths.map(path => JSON.stringify(path)).join('\n')}`,
    pickFailed: (message) => `無法選擇檔案: ${message}`,
    webFilesUnsupported: '本機檔案和資料夾請在 BaoCut 桌面版新增；Web 用戶端暫不支援上傳。',
    mention: '引用影片或檔案',
    slash: '使用工具',
    attachSection: '新增',
    referSection: '引用與指令',
    imagesUnsupported: (driverName: string) => `${driverName} 不接受圖片`,
    noMentionCandidates: '這裡還沒有可以引用的影片或檔案',
  },
  skill: {
    use: '使用 Skill',
    manage: '管理 Skills…',
    loading: '正在載入 Skills…',
    none: '還沒有 Skill：可以在設定中從本機資料夾新增，或從 GitHub 匯入',
    loadFailed: '無法載入 Skills',
    token: (name: string) => `Skill：${name}`,
    remove: (name: string) => `移除 Skill：${name}`,
  },
  attachment: {
    tooLarge: `請選擇不超過 ${MAX_ATTACHMENT_BYTES / 1024 / 1024} MiB 的圖片`,
    tooMany: `最多可以附加 ${MAX_ATTACHMENTS_PER_MESSAGE} 張圖片`,
    badType: '只能附加 PNG、JPEG、GIF 或 WebP 圖片',
    uploadFailed: (message: string) => `無法上傳圖片：${message}`,
    httpFailed: (status: number) => `上傳失敗（HTTP ${status}）`,
    networkFailed: '上傳失敗：無法連線到 Runtime',
    uploading: '正在上傳圖片…',
  },
  queue: {
    title: (count: number) => `排隊等待傳送 · ${count} 則`,
    images: (count: number) => `${count} 張圖片`,
    edit: '編輯',
    save: '儲存',
    cancel: '取消',
    remove: '刪除',
    sendNow: '立即傳送',
    editLabel: '編輯排隊中的訊息',
    steerUnsupported: '這個 Agent 無法在任務中途接收訊息，會在目前的任務結束後傳送',
    skillWaits: '附帶 Skill 的訊息無法加入進行中的這一輪，會在這一輪結束後傳送',
    failed: (message: string) => `無法傳送排隊中的訊息：${message}`,
    busyPlaceholder: 'Agent 正在工作；現在傳送的訊息會排隊，等這一輪結束後再傳送',
  },
  recovery: {
    authTitle: (name: string) => `${name} 需要重新登入`,
    authBody: (name: string) => `登入會在 ${name} 自己的視窗中完成，BaoCut 不會經手你的帳號和密碼。登入後回到這裡重新傳送。`,
    openLogin: '開啟終端機登入',
    loginOpened: (command: string) => `已在終端機中執行 ${command} · 登入後回到這裡重新傳送`,
    loginCopied: '無法開啟終端機，已複製登入指令，請貼到終端機中執行',
    loginManual: (command: string) => `無法開啟終端機，請在終端機中執行 ${command}`,
    modelTitle: (model: string | null) => `${model ? `${model} ` : '這個模型'}目前無法使用`,
    modelBody: '換一個模型重新傳送；BaoCut 不會自行更換模型。',
    pickModel: '換個模型重新傳送',
    resend: '重新傳送',
    retry: '重試',
    agentSettings: 'Agent 設定',
    nothingToResend: '找不到這一輪的訊息，無法重新傳送',
    resendFailed: (message: string) => `無法重新傳送：${message}`,
  },
  approval: {
    title: {
      command: 'Agent 想要執行指令',
      'file-change': 'Agent 想要修改檔案',
      tool: 'Agent 想要使用工具',
      highRisk: 'Agent 想要執行有風險的動作',
    },
    kind: { command: '執行指令', 'file-change': '修改檔案', tool: '使用工具' },
    projectFiles: '專案中的檔案',
    inDir: (dir: string) => `在 ${dir}`,
    allow: '允許',
    allowAlways: (rule: string) => `總是允許 ${rule}`,
    decline: '拒絕',
    accepted: '已允許',
    acceptedAlways: (rule: string) => `已允許 · 之後 ${rule} 不再詢問`,
    declined: '已拒絕',
    cancelled: '已停止',
    autoRule: (rule: string | null) => (rule ? `自動允許 · 規則 ${rule}` : '自動允許 · 規則'),
    autoMode: '自動允許 · 存取模式',
    input: '輸入摘要',
    copyInput: '複製輸入摘要',
    failed: (message: string) => `無法提交：${message}`,
  },
  change: {
    undone: '已還原 · 修改已移除',
    undo: '還原',
    restore: '回復',
    openVideo: '開啟影片',
    confirmTitle: '要還原這一步嗎？',
    confirmBody: '這一步寫入影片的修改會被移除。還原之後、在你繼續修改這部影片之前，可以按「回復」把它們放回來。',
    cancel: '取消',
    undoneToast: '已還原',
    restoredToast: '已回復',
    alreadyUndone: '這一步先前已經還原過了',
    undoFailed: (message: string) => `無法還原：${message}`,
    restoreFailed: (message: string) => `無法回復：${message}`,
  },
  threadEmpty: {
    greetVideo: (name: string) => `要對「${name}」做些什麼？`,
    greet: '要讓 Agent 幫你做什麼？',
    subVideo: '它會先讀取這部影片，再給你一份計畫；用 @ 可以引用其他影片或檔案作為參考。',
    sub: '先描述要做的事。它會在你電腦上的程式設計 Agent 中執行，使用你自己的訂閱。',
    suggestions: '試著問問',
    chipsVideo: ['去掉這一章的贅字', '幫每一章取更短的標題', '找出可以剪掉的重複段落', '把用語統一成術語表中的寫法'],
    chips: ['幫這部影片加上字幕並翻譯成英文', '找出贅字和長停頓，先列出來再剪', '把這一集分成章節並加上標題', '匯出雙語 SRT 和燒錄字幕的 MP4'],
  },
  output: {
    playVideo: (name: string) => `播放影片「${name}」`,
    noThumbnail: '沒有縮圖',
    sourceMissing: '找不到來源檔案',
    openEditor: '開啟編輯器',
    openVideo: (name: string) => `開啟影片「${name}」`,
    playHere: '在右側播放',
    previewHere: '在右側預覽',
    reveal: '在資料夾中顯示',
    messageOutputs: '訊息產出',
  },
  videoCard: {
    agentTranslating: 'Agent 逐句翻譯',
    sentenceTotal: (n: number) => `共 ${n} 句`,
    status: { translating: '翻譯中', transcribing: '轉錄中', queued: '排隊中', transcribed: '已轉錄', failed: '失敗' },
    rows: '這部影片上的工作',
    retranscribe: '重新轉錄',
    translate: '翻譯',
    linkImport: '從連結匯入',
    tail: { queued: '排隊中', done: '完成', failed: '失敗', cancelled: '已取消', interrupted: '已中斷', unknown: '結果不明' },
    elapsed: (clock: string) => `已用 ${clock}`,
    recognized: (done: string, total: string | null) => (total ? `已辨識 ${done} / ${total}` : `已辨識 ${done}`),
    segments: (done: number, total: number | null) => (total != null ? `已辨識 ${done} / ${total} 段` : `已辨識 ${done} 段`),
    translated: (done: number, total: number | null) => (total != null ? `已翻譯 ${done} / ${total} 句` : `已翻譯 ${done} 句`),
    downloaded: (text: string) => `已下載 ${text}`,
    documentWritten: '逐字稿已寫入影片',
    notFinished: '這一步沒有完成',
    retrying: '發生錯誤後自動重試',
    play: '播放',
    reveal: '在資料夾中顯示',
    cancel: '取消',
    retry: '重試',
    warning: {
      'no-speech': '沒有偵測到人聲',
      'no-audio-track': '影片沒有音軌',
      'diarization-unavailable': '這個模型無法區分說話者',
    } as Record<string, string>,
    download: {
      queued: '等待下載',
      running: '正在下載影片',
      done: '下載完成',
      failed: '下載沒有完成',
      cancelled: '已取消下載',
      interrupted: '下載中斷了',
      fallbackName: '影片',
    },
    openFailed: (message: string) => `無法開啟：${message}`,
    retryFailed: (message: string) => `無法重試：${message}`,
  },
  home: {
    title: '想做什麼樣的影片？',
    templates: '範本',
    quickStart: '快速開始',
    blankVideo: '新增空白影片',
    blankVideoTip: '不轉錄、不排隊，直接進入編輯器',
    blankVideoCreated: '已建立空白影片',
    blankVideoFailed: (message: string) => `無法建立空白影片：${message}`,
    blankVideoProject: '空白影片',
    removeTemplate: '移除範本',
    templateToken: (title: string) => `範本：${title}`,
    allTemplates: '全部範本',
    searchTemplates: '搜尋範本',
    templateKind: '類型',
    templateSource: '來源',
    templateCategories: '分類',
    viewTemplate: (title: string) => `檢視範本：${title}`,
    useExampleLabel: (title: string) => `使用提示詞：${title}`,
    useTemplateLabel: (title: string) => `使用範本：${title}`,
    templatePicked: '已選取',
    exampleBadge: '範例',
    templatePage: (page: number, pages: number, total: number) => `第 ${page} / ${pages} 頁 · 共 ${total} 個`,
    prevPage: '上一頁',
    nextPage: '下一頁',
    noTemplates: '沒有找到符合的範本，換個關鍵字或分類試試。',
    templatesEmpty: '範本資料夾中還沒有範本。',
    templatesLoading: '正在載入範本…',
    templatesFailed: (message: string) => `無法讀取範本資料夾：${message}`,
    retryTemplates: '重試',
    templatesNote: '內建範本隨應用程式提供；放進範本資料夾的範本會顯示為「我的」。',
    templatesSkipped: (count: number) => `有 ${count} 個範本無法載入`,
    showSkipped: '查看原因',
    hideSkipped: '收合',
    pickTemplateHint: '在左側選一個範本，這裡會顯示它的預覽與提示詞。',
    templatePrompt: '提示詞',
    templatePromptLoading: '正在載入提示詞…',
    templatePromptFailed: (message: string) => `無法讀取提示詞：${message}`,
    templateSay: '可以這樣說',
    templateFields: '需要你補充',
    templateSkills: (list: string) => `做法：${list}`,
    slotsLeft: (count: number, labels: string) => `還有 ${count} 處待填：${labels} · 不填也能傳送，Agent 會先問你`,
    fillNextSlot: '填下一處',
    templateBriefNote: '選用後，Agent 會先和你確認主題、目標、受眾和素材，再開始製作。',
    templateAssets: '素材',
    templatePromptOnly: '只有提示詞，不含素材',
    useTemplate: '使用這個範本',
    keepTemplate: '繼續使用這個範本',
    useExample: '使用這個提示詞',
    promptPlaced: '已填入提示詞',
    undo: '還原',
    playPreview: '播放預覽',
    pausePreview: '暫停預覽',
    placeholder: '描述你想做的影片，或把素材拖到這裡…',
    templatePlaceholder: '想講什麼內容？補充主題、受眾或你的要求…',
    localFiles: '本機檔案',
    addMedia: '影片或音訊',
    addDocument: 'PDF 或文件',
    addImage: '圖片',
    recentVideos: '最近的影片',
    recentReplaced: (title: string, removed: string) => `已改為處理「${title}」，並移除了「${removed}」`,
    removeMaterial: (name: string) => `移除素材：${name}`,
    materialsFull: (max: number, rejected: number) => `一次最多加入 ${max} 份素材，有 ${rejected} 份沒有加入`,
    notLocalFile: '這個檔案不在這台電腦上，無法交給 Agent',
    thisComputer: '這台電腦',
    pickProject: '選擇專案',
    pickProjectLabel: (name: string | null) => `選擇專案：${name ?? '未選擇'}`,
    currentProject: '目前的專案',
    newProject: '新增專案',
    noProject: '沒有選擇專案時，Agent 會在暫存資料夾中工作',
    enableFailed: (message: string) => `無法開啟：${message}`,
  },
  homeStarter: {
    sub: { title: '加字幕', needs: '影片', prompt: '幫這部影片加上字幕。' },
    trans: { title: '轉錄並翻譯', needs: '影片', prompt: '轉錄這部影片，並翻譯成中文，做成雙語字幕。' },
    clean: { title: '剪口播影片', needs: '影片', prompt: '轉錄這部影片，找出贅字、長停頓和說錯重來的地方，剪掉之前先讓我看一遍。' },
    a2v: { title: '音訊轉影片', needs: '音訊', prompt: '把這段音訊做成影片，配上背景、波形和字幕。' },
    tip: (needs: string) => `填入提示詞後，再把${needs}拖進輸入框`,
  },
  templateCategory: {
    all: '全部',
    marketing: '行銷推廣',
    'product-launch': '產品發表',
    explainer: '知識講解',
    'news-data': '新聞與數據',
    editing: '剪輯整理',
    'creative-short': '創意短片',
    'motion-design': '動態設計',
  },
  templateKind: { all: '全部', scene: '情境範本', example: '作品範例' },
  templateSource: { all: '全部來源', builtin: '內建', user: '我的', community: '社群' },
  templateAsset: { image: '圖片', svg: 'SVG', audio: '音訊', video: '影片' },
  templateSpec: {
    allAuto: '長寬比與時長自動',
    ratioAuto: '長寬比自動',
    lengthAuto: '時長自動',
    sceneDefault: (spec: string) => `預設 ${spec}，要改就在訊息裡說`,
    exampleAuto: '長寬比與時長自動，由 Agent 依內容決定',
  },
  createProject: {
    title: '建立專案',
    close: '關閉建立專案',
    name: '專案名稱',
    placeholder: '為專案命名',
    location: '儲存資料夾',
    preview: (path: string) => `專案會儲存在 ${path}`,
    cancel: '取消',
    create: '建立',
    created: (name: string) => `已建立專案「${name}」`,
    failed: (message: string) => `無法建立專案：${message}`,
  },
  taskKind: {
    agent: 'Agent 任務',
    transcribe: '轉錄',
    synthesizeSpeech: '生成語音',
    generateImage: '生成圖片',
    generateText: '生成文字',
    export: '匯出',
    pipeline: '固定流程',
    'pipeline-step': '流程步驟',
    modelInstall: '安裝模型',
    modelTest: '檢查模型',
    modelsMove: '移動模型資料夾',
    toolInstall: '安裝工具',
    toolUpdate: '更新工具',
    fontDownload: '下載字型',
    voiceClone: '克隆音色',
    agentTranslate: '翻譯',
  },
  jobPhase: {
    queued: '排隊中',
    starting: '準備中',
    loading: '載入模型',
    decoding: '解碼音訊',
    vad: '偵測人聲',
    transcribing: '辨識中',
    aligning: '對齊時間',
    diarizing: '區分說話者',
    finalizing: '整理結果',
    probing: '讀取媒體',
    encoding: '編碼中',
    downloading: '下載中',
    moving: '移動中',
    generating: '生成中',
    validating: '驗證結果',
    publishing: '儲存結果',
    applying: '寫入影片',
    done: '已完成',
  },
  taskView: {
    queued: '排隊中',
    running: '進行中',
    awaitingApproval: '需要你核准',
    cancelled: '已取消',
    failed: '失敗',
    completed: '已完成',
    interrupted: '已中斷',
    needsReconciliation: '結果不明',
    retrying: '發生錯誤後自動重試',
    costCharged: '已取得結果，計費一次',
    costCancelUnsupported: '供應商不支援取消，請求可能仍會在遠端完成並計費',
    costUnknown: '無法確定請求是否已送出，可能已經計費',
    costPossible: '可能已經計費',
    chipAgent: 'Agent',
    chipCli: '命令列',
    byAgent: 'Agent 對話',
    byCli: '命令列',
    byApp: '應用程式',
    byNode: '遠端節點',
    local: '這台電腦',
    cloud: '雲端',
    node: '遠端節點',
    noProject: '不屬於任何專案',
    pageTitle: '全部任務',
    activeSection: '進行中',
    historySection: '已完成',
    historyGroup: '歷史記錄',
    emptyActive: '沒有執行中的任務',
    emptyActiveBody: '轉錄、翻譯與匯出都會顯示在這裡。',
    emptyHistory: '還沒有已完成的任務',
    openConversation: '開啟對話',
    details: '詳細資訊',
    cancel: '取消',
    stop: '停止',
    back: '背景任務',
    notFound: '找不到任務',
    notFoundBody: '這個任務已經不在清單中了',
    cancelTask: '取消任務',
    cancelExport: '取消匯出',
    stopTask: '停止任務',
    cancelExportHint: '未完成的檔案會被刪除，影片本身不受影響。已經開始儲存檔案時無法停止，會照常儲存完成。',
    stopHint: 'Agent 會停在目前這一步；已經寫入專案的檔案不受影響。',
    conversationHint: '這次執行是在 Agent 對話中核准的；對話內容與核准記錄都在那段對話中。',
    agentTaskHint: '這個任務屬於一段 Agent 對話；對話內容與核准記錄都在那段對話中。',
    cancelledBody: '影片本身不受影響。',
    interruptedBody: 'Runtime 停止或重新啟動時，這次執行還沒有完成，不會自動接續；需要的話請重新開始。',
    needsReconciliationBody: 'Runtime 重新啟動時，這次雲端呼叫還沒有回應，可能已經計費；不會自動重新傳送。',
    configHint: '這是設定問題，重試同樣的流程不會解決。請先補上缺少的元件，再執行一次。',
    sourceSection: '來源',
    imagesSection: '圖片',
    outputsSection: '產出',
    factsSection: '詳細資訊',
    reveal: '在資料夾中顯示',
    open: '開啟',
    copyPrompt: '複製提示詞',
    promptCopied: '已複製提示詞',
    copyFailed: '無法複製，請手動選取文字後複製',
    documentWritten: '逐字稿已寫入影片',
    importedToVideo: '已匯入影片',
    imageName: (n: number) => `圖片 ${n}`,
    audioName: (n: number) => `音訊 ${n}`,
    videoName: (n: number) => `成品 ${n}`,
    fileName: (n: number) => `檔案 ${n}`,
    entries: (n: number) => `${n} 筆`,
    packageFiles: (n: number) => `可攜式套件 · ${n} 個檔案`,
    projectClips: (n: number) => `專案 · ${n} 個片段`,
    documentName: '逐字稿',
    stopFailed: (message: string) => `無法停止：${message}`,
    cancelFailed: (message: string) => `無法取消：${message}`,
    reconcileRetry: '重試',
    reconcileDiscard: '捨棄這次結果',
    reconcileApply: '重新寫入影片',
    reconcileRetryHint: (charges: boolean) => (charges ? '會再呼叫一次供應商，可能會再次計費。' : '把同一個任務重新排隊，從頭再執行一次。'),
    reconcileDiscardHint: '標記為已取消；可能已經產生的費用不會退還。',
    reconcileApplyHint: '產出還在：重新驗證後寫入影片。請先開啟這部影片。',
    reconcileFailed: (message: string) => `無法處理：${message}`,
    openFailed: (message: string) => `無法開啟：${message}`,
    remedyInstall: '安裝元件',
    remedyCloud: '設定雲端模型',
    remedyDefault: '選擇預設模型',
    remedyNode: '檢視遠端節點',
    remedyAgent: '開啟 Agent 設定',
  },
  taskPill: {
    count: (n: number) => `${n} 個背景任務`,
    all: '全部任務',
    more: (n: number) => `還有 ${n} 個任務 · 在背景任務中查看全部`,
    mine: '這部影片',
    justStarted: '剛開始',
    startedAt: (ago: string) => `${ago}開始`,
  },
  projectFiles: {
    region: '專案檔案',
    scratchRoot: '對話資料夾',
    searchLabel: '尋找專案檔案',
    searchPlaceholder: '尋找檔案或影片',
    listLabel: (where: string) => `「${where}」中的檔案`,
    resultsLabel: '搜尋結果',
    breadcrumbs: '資料夾路徑',
    loading: '正在載入檔案…',
    emptyFolder: '這個資料夾是空的',
    noMatch: '沒有符合的檔案',
    noMatchHint: '依檔名比對，略過隱藏檔案與相依套件資料夾。',
    failed: '無法讀取檔案清單',
    retry: '重試',
    truncatedList: (count: number) => `檔案太多，只列出前 ${count} 個。`,
    truncatedSearch: '符合的檔案太多，只列出一部分；換個更具體的關鍵字試試。',
    inRoot: '專案根目錄',
  },
  webTab: {
    back: '上一頁',
    forward: '下一頁',
    stop: '停止載入',
    reload: '重新載入網頁',
    address: '網址',
    placeholder: '搜尋或輸入網址',
    go: '前往',
    menu: '網頁選項',
    copy: '複製網址',
    copied: '已複製網址',
    copyFailed: '無法複製網址',
    external: '在外部瀏覽器中開啟',
    zoomIn: '放大',
    zoomOut: '縮小',
    zoomReset: '縮放比例回復為 100%',
    invalid: '請輸入 http / https 網址或搜尋字詞；網址不能包含帳號或密碼。',
    loading: '正在載入網頁…',
    slow: '網頁載入較慢，可以重試，或在外部瀏覽器中開啟。',
    startTitle: '搜尋或開啟網頁',
    startBody: '輸入網址或搜尋字詞，在這裡查閱資料並繼續對話。',
    enterUrl: '輸入網址',
    stoppedTitle: '已停止載入',
    failedTitle: '無法載入網頁',
    failedDetail: (description: string, code: number) => `${description}（${code}）`,
    crashedTitle: '網頁意外結束了',
    crashedBody: '請試著重新載入。',
    retry: '重新載入',
    blockedTitle: {
      loopback: '本機位址無法在這裡開啟',
      scheme: '只能開啟 http / https 網址',
      'app-origin': 'BaoCut 自己的頁面無法在網頁分頁中開啟',
      invalid: '這個網址無效',
    },
    blockedBody: {
      loopback: '為了安全，內嵌網頁不會存取本機服務（localhost、127.0.0.1 等）。需要時請在瀏覽器中開啟。',
      scheme: '其他協定（檔案、應用程式連結等）不會在內嵌網頁中開啟。',
      'app-origin': '應用程式自己的頁面不會在網頁分頁中開啟。',
      invalid: '請檢查網址的寫法。',
    },
    backToPage: '回到網頁',
    footer: '網頁會在獨立的環境中開啟，無法存取 BaoCut 與本機服務；登入狀態與系統瀏覽器分開。',
    externalShort: '在外部開啟',
    unsupportedTitle: '這個環境無法內嵌網頁',
    unsupportedBody: '在 BaoCut 桌面版中可以直接瀏覽網頁；這裡可以先在瀏覽器中開啟。',
    openInBrowser: '在瀏覽器中開啟',
    toolsTitle: '工具',
    newPageTitle: '新增網頁',
    newPageBody: '在專案裡新增一個 HTML 檔案並預覽',
    browseFilesTitle: '瀏覽專案檔案',
    browseFilesBody: '在這個分頁裡查看專案目錄',
    newPageFileName: '新網頁',
    newPageHint: '在這裡編寫網頁內容，也可以讓 Agent 幫你修改。',
    newPageFailed: '無法新增網頁',
  },
  timelineEdit: {
    undo: '還原',
    pick: (verb: string) => `請先選取要${verb}的片段`,
    copied: (n: number) => (n > 1 ? `已複製 ${n} 個片段` : '已複製片段'),
    cut: (n: number) => (n > 1 ? `已剪下 ${n} 個片段` : '已剪下片段'),
    pasted: (n: number) => (n > 1 ? `已貼上 ${n} 個片段` : '已貼上片段'),
    duplicated: (n: number) => (n > 1 ? `已再製 ${n} 個片段` : '已再製片段'),
    deleted: (n: number) => (n > 1 ? `已刪除 ${n} 個片段` : '已刪除片段'),
    clipboardEmpty: (mod: string) => `剪貼簿是空的 · 請先按 ${mod}C 複製一個片段`,
    otherVideo: '剪貼簿中的片段來自另一部影片 · 只能貼回原來的影片',
    selectedAtPlayhead: (n: number) => `已選取 ${n} 個片段`,
    nothingAtPlayhead: '播放頭所在位置沒有片段',
    labelCut: '剪下片段',
    labelPaste: '貼上片段',
    labelDuplicate: '再製片段',
    labelDelete: '刪除片段',
    labelSplit: '分割片段',
    labelNudge: '微調片段時間',
    labelDisable: '停用片段',
    labelEnable: '啟用片段',
    menuLabel: (name: string) => `片段「${name}」`,
    split: '在播放頭分割',
    splitUnavailable: '播放頭不在這個片段內',
    copy: '複製',
    cutItem: '剪下',
    paste: '貼上',
    duplicate: '再製',
    disable: '停用這個片段',
    enable: '啟用這個片段',
    disableHint: '保留在時間軸上 · 畫面與匯出都會略過',
    enableHint: '重新出現在畫面與匯出中',
    remove: '刪除',
  },
  timelineZoom: {
    menu: '縮放',
    tip: '縮放選項',
    in: '放大',
    out: '縮小',
    '100': '100%',
    fit: '適應視窗',
    fitClip: '適應目前片段',
    playhead: '縮放到播放頭',
    fitSelection: '適應所選範圍',
    noClip: '請把播放頭移到某個片段內',
    noSelection: '請先在時間軸上選取片段',
  },
  shortcutSheet: {
    title: '鍵盤快速鍵',
    done: '知道了',
    hint: '游標在輸入框中時，這些按鍵都會交給輸入框。',
    rows: [
      ['刪除所選項目', 'Delete'],
      ['取消選取 / 關閉彈出視窗', 'Esc'],
      ['播放 / 暫停', 'Space / K'],
      ['還原 / 重做', '⌘Z / ⇧⌘Z'],
      ['複製 / 剪下 / 貼上', '⌘C / ⌘X / ⌘V'],
      ['再製', '⌘D'],
      ['全選播放頭下的片段', '⌘A'],
      ['播放頭前後移動一個影格（播放中：前後 5 秒）', '← / →'],
      ['播放頭前後移動一秒', '⇧← / ⇧→'],
      ['倒退 / 快轉 10 秒', 'J / L'],
      ['播放中：音量 +10 / −10（調高時自動取消靜音）', '↑ / ↓'],
      ['靜音 / 取消靜音', 'M'],
      ['微調畫面上所選元素的位置（先按一下畫面）', '方向鍵（⇧ 移動 5%，⌥↑ / ⌥↓ 移動 0.1%）'],
      ['微調所選片段的時間（⇧ 一次一秒）', '⌥← / ⌥→'],
      ['時間軸放大 / 縮小 / 100%', '⌘= / ⌘− / ⌘0'],
      ['時間軸適應視窗 / 目前片段 / 播放頭 / 所選範圍', '⌥⌘1 / ⌥⌘2 / ⌥⌘3 / ⌥⌘4'],
      ['在播放頭分割', 'S / ⌘B'],
      ['全螢幕播放 / 結束全螢幕（畫布上沒有選取片段時）', 'F'],
      ['選取的片段移到最前 / 移到最後', 'F / B'],
      ['選取的片段前移一層 / 後移一層', '⌘↑ / ⌘↓'],
      ['跳到開頭 / 結尾', 'Home / End'],
      ['開啟編輯器快速鍵清單', '?'],
    ],
  },
  workspace: {
    tablist: '工作區分頁',
    tablistHint: '拖曳分頁可以調整順序，也可以按 Alt + Shift + 左右方向鍵。',
    close: (name: string) => `關閉分頁「${name}」`,
    add: '開啟新分頁',
    dragging: (name: string) => `正在拖曳「${name}」，放開即可放置，按 Esc 取消`,
    moved: (name: string) => `已移動「${name}」`,
    dragCancelled: '已取消拖曳',
    viewGroup: '工作區檢視',
    resize: '調整對話欄寬度',
    conversation: '對話',
    conversationTabTip: (title: string, status: string | null) =>
      `對話「${title}」${status ? ` · ${status}` : ''} · 固定在第一個，無法移動或關閉`,
    conversationTabLabel: (title: string, status: string | null) => `對話「${title}」${status ? `，${status}` : ''}，固定在第一個`,
    opening: '正在開啟影片…',
    showInSpace: '在 Space 中顯示',
    reveal: '在資料夾中顯示',
    fileMissing: '檔案已被移動或刪除',
    filesNoConversation: '對話建立後，這裡會列出它所在資料夾中的檔案。',
  },
  stage: {
    label: '畫面上的物件',
    textEditor: '編輯文字',
    move: '移動',
    resize: '調整大小',
    scale: '縮放',
    rotate: '旋轉',
    rotateReset: '重設旋轉',
    groupMove: '一起移動',
    groupScale: '一起縮放',
    nudge: '微調位置',
    edgeHeightTip: '拖曳以調整高度 · ⌥ 以中心為準',
    edgeWidthTip: '拖曳以調整寬度 · ⌥ 以中心為準',
    cornerFreeTip: '拖曳以調整大小 · ⇧ 解除比例鎖定，⌥ 以中心為準',
    cornerScaleTip: '等比例縮放 · ⌥ 以中心為準',
    rotateTip: '拖曳以旋轉 · 對齊 15°，⇧ 自由旋轉 · 按兩下重設',
    groupCornerTip: '全部等比例縮放',
    picked: (n: number) => `已選取 ${n} 個`,
    degrees: (n: number) => `${n}°`,
  },
  service: {
    mcp: {
      name: 'MCP 服務',
      scope: '僅限這台電腦',
      desc: '讓其他 AI 應用程式讀取影片、呼叫 BaoCut 工具',
      start: '啟動服務',
      stop: '停止服務',
      starting: '正在啟動…',
      stopping: '正在停止…',
    },
    remote: {
      name: '遠端算力',
      scope: '區域網路',
      desc: '把這台 Mac 的算力共享給區域網路中的其他電腦',
      start: '開始共享',
      stop: '停止共享',
      starting: '正在開始…',
      stopping: '正在停止…',
    },
    web: {
      name: 'Web 服務',
      scope: '僅限這台電腦',
      desc: '在瀏覽器中開啟 BaoCut Web，編輯同一批影片',
      start: '啟動服務',
      stop: '停止服務',
      starting: '正在啟動…',
      stopping: '正在停止…',
    },
    'model-api': {
      name: '模型 API',
      scope: '僅限這台電腦',
      desc: '讓支援 OpenAI API 的工具使用 BaoCut 的模型來轉錄、配音、生成圖片與文字',
      start: '啟動服務',
      stop: '停止服務',
      starting: '正在啟動…',
      stopping: '正在停止…',
    },
  },
  serviceState: {
    share: { starting: '正在開始共享…', stopping: '正在停止共享…', error: '共享意外停止', on: '共享中', off: '未共享' },
    service: { starting: '正在啟動…', stopping: '正在停止…', error: '無法啟動', on: '執行中', off: '未啟動' },
    unavailable: '尚未提供',
  },
  servicesPage: {
    title: '服務',
    overview: '服務總覽',
    lede: 'BaoCut 在這台 Mac 上提供、供其他應用程式或裝置連線的服務。預設全部關閉；結束 BaoCut 時會一起停止。',
    allOff: '全部未啟動',
    errors: (n: number) => `${n} 項發生錯誤`,
    running: (n: number) => `${n} 項執行中`,
    open: (name: string) => `開啟${name}`,
    restart: (verb: string) => `重新${verb}`,
    railAlert: (text: string) => `服務，${text}`,
    railApprovals: (n: number) => `服務，${n} 個要求等待你核准`,
    loading: '正在載入狀態…',
    disconnected: '沒有連線到 BaoCut Runtime',
    failed: (message: string) => `操作沒有成功：${message}`,
    unavailableDetail: '這個版本的 BaoCut Runtime 還沒有提供這項服務',
    unavailableTitle: (name: string) => `${name}尚未提供`,
    notRunning: '服務沒有執行，請先啟動',
    mcpRelated: '想讓終端機裡的 Claude Code、Codex 學會 BaoCut 的工作流程？那要為它們安裝 BaoCut 的 Skill，不需要啟動服務，說明在',
    mcpRelatedLink: '設定 › Skills',
  },
  runtimeCard: {
    name: 'BaoCut Runtime',
    version: '版本',
    versionValue: (runtime: string, protocol: number | string) => `${runtime}（協定 ${protocol}）`,
    pid: '行程',
    startedAt: '啟動時間',
    home: '資料位置',
  },
  remote: {
    title: '遠端算力',
    tabsLabel: '遠端算力的兩種檢視',
    tabShare: '共享這台 Mac',
    tabNodes: '使用其他電腦',
    ledeShare: { before: '把這台 Mac 的轉錄能力共享給區域網路中的其他電腦。', strong: '檔案只在你的區域網路內傳輸', after: '，只有結果會傳回去——不經過任何伺服器。' },
    ledeNodes: { before: '把轉錄交給區域網路中另一台更快的電腦。', strong: '檔案只在你的區域網路內傳輸', after: '，只有結果會傳回來——不經過任何伺服器。' },

    cardOn: '正在共享這台 Mac',
    cardOff: '共享已關閉',
    subOff: '其他裝置看不到這台 Mac。',
    subErrorFallback: '節點服務沒有在監聽。',
    errorFix: '請先結束佔用這個連接埠的程式，再重新開始共享；不想共享了就停止。',
    foot: '共享開啟時，下次開啟 BaoCut 會自動繼續共享。',
    footRight: '結束 BaoCut 時共享會一起停止。',
    privacy: '任務的輸入只在區域網路內傳輸，只有結果會傳回去；任務結束後不會在這台 Mac 上留下任何內容。',
    offHint: '開始共享後會顯示 6 位數配對碼，在對方裝置上輸入即可連線。',
    started: '已開始共享這台 Mac',
    stopped: '已停止共享',

    nodeName: '節點名稱',
    address: '位址',
    noAddress: '沒有可用的區域網路位址',
    pairingTitle: '配對碼',
    pairingHint: (left: string) => `在對方裝置上輸入這組配對碼。${left}後失效。`,
    pairingLocked: (until: string) => `輸入錯誤次數太多，配對已鎖定到 ${until}。重新產生配對碼即可立即解鎖。`,
    pairingNone: '目前沒有可用的配對碼：配對碼使用過一次、過期或重新開啟 BaoCut 後都需要重新產生。已配對的裝置不受影響。',
    regenerate: '重新產生',
    generate: '產生配對碼',
    regenerated: '已產生新的配對碼',

    tasksTitle: '提供給其他電腦的任務',
    taskSummary: (on: number, total: number) => `提供 ${on} / ${total} 類任務`,
    taskUnsupported: '這個版本還無法共享這類任務',
    taskNoModel: (noun: string) => `這台 Mac 還沒有安裝可用的${noun}，其他電腦傳來的這類任務會失敗`,
    taskSwitch: (name: string) => `提供${name}`,
    taskOn: (name: string) => `已開始提供${name}`,
    taskOff: (name: string) => `已停止提供${name} · 已經接下的任務會照常完成`,

    status: '狀態',
    idle: '閒置',
    jobs: (running: number, queued: number) =>
      [running ? `${running} 個任務執行中` : '', queued ? `${queued} 個排隊中` : ''].filter(Boolean).join(' · '),

    clientsTitle: '已配對的裝置',
    clientsEmpty: '還沒有裝置與這台 Mac 配對。',
    clientMeta: (paired: string, seen: string | null) => (seen ? `${paired}配對 · ${seen}連線過` : `${paired}配對 · 還沒連線過`),
    revoke: '撤銷',
    revokeLabel: (name: string) => `撤銷「${name}」`,
    revokeTitle: (name: string) => `要撤銷「${name}」嗎？`,
    revokeBody: '它的權杖會立即失效，它交給這台 Mac 的任務也會取消。要再使用，對方必須重新輸入配對碼。',
    revoked: (name: string) => `已撤銷「${name}」`,

    paired: '已配對',
    pairedEmptyTitle: '還沒有配對的節點',
    pairedEmptyBody: '在另一台電腦上開啟「共享這台 Mac」，再從這裡配對。',
    nearby: '附近',
    nearbyIdle: '按一下「尋找附近的電腦」，看看區域網路中有哪些電腦開啟了共享。',
    nearbyNone: '沒有找到開啟共享的電腦。請確認對方已開啟「共享這台 Mac」，且兩台電腦在同一個區域網路中；也可以依位址新增。',
    search: '尋找附近的電腦',
    searching: '正在尋找…',
    addByAddress: '依位址新增…',
    pair: '配對',
    pairLabel: (name: string) => `與「${name}」配對`,
    online: '線上',
    offline: '離線',
    versionMismatch: '版本不相容',
    unpaired: '配對已失效',
    checking: '正在檢查…',
    more: (name: string) => `「${name}」的更多動作`,
    copyAddress: '複製位址',
    copied: (address: string) => `已複製 ${address}`,
    copyFailed: '無法複製，請選取文字後複製',
    unpair: '取消配對',
    unpairTitle: (name: string) => `要取消與「${name}」的配對嗎？`,
    unpairBody: '這台電腦之後不會再出現在轉錄的模型清單中。隨時可以重新配對。',
    unpairDone: '已取消配對',
    problem: {
      unreachable: '無法連線到這台電腦：請確認它已開啟 BaoCut 並開啟「共享這台 Mac」，且兩台電腦在同一個區域網路中。',
      version: '兩台電腦的 BaoCut 版本不相容：請把兩邊都更新到最新版本。',
      unpaired: '配對已經失效：對方撤銷了這台電腦，或這個位址上換成了另一台電腦。請取消配對後重新配對。',
    },
    transcribeOff: '沒有開放轉錄',
    transcribeModels: (n: number) => (n ? `轉錄 ${n}` : '轉錄'),

    pairTitle: (name: string) => `與「${name}」配對`,
    addTitle: '依位址新增',
    pairBody: '在那台電腦的「共享這台 Mac」中找到 6 位數配對碼，輸入到這裡。',
    addressLabel: '位址',
    addressPlaceholder: '192.168.1.31:47610',
    addressHint: (port: number) => `主機名稱或 IP，後面可以加上連接埠；不填連接埠時使用 ${port}。`,
    codeLabel: '配對碼',
    codePlaceholder: '481 924',
    cancel: '取消',
    pairing: '正在配對…',
    pairedToast: '已配對 · 它現在會出現在轉錄的模型清單中',
    addressEmpty: '請填入那台電腦的位址',
    addressInvalid: '位址格式不正確：請寫成 192.168.1.31 或 192.168.1.31:47610',
    portInvalid: '連接埠必須是 1–65535 之間的數字',
    codeInvalid: '配對碼是 6 位數字',
    pairErrors: {
      'pairing-code-invalid': '配對碼不正確或已經失效。請對方重新產生後再試一次。',
      'pairing-locked': '輸入錯誤次數太多，那台電腦暫時鎖定了配對。請對方按一下「重新產生」解鎖。',
      version: '兩台電腦的 BaoCut 版本不相容，請先把兩邊都更新到最新版本。',
      'source-not-allowed': '那台電腦不接受來自這台電腦位址的連線。',
      lost: '無法連線到那台電腦：請確認位址和連接埠，並確認它已開啟「共享這台 Mac」。',
    },
    pairFailed: (message: string) => `配對沒有成功：${message}`,
  },
  remoteTask: {
    asr: { name: '轉錄', noun: '轉錄模型' },
    tts: { name: '配音', noun: '配音模型' },
    image: { name: '影像生成', noun: '影像模型' },
    separate: { name: '人聲分離', noun: '分離模型' },
    download: { name: '影片下載', noun: null },
    export: { name: '影片匯出', noun: null },
  },
  help: {
    title: '說明中心',
    subtitle: '隨時查閱，輕鬆上手',
    close: '關閉說明',
    navLabel: '說明分類',
    navTitle: '使用 BaoCut',
    navNote: ['需要時再讀就好。', '關閉後就能回到原本的工作。'],
    sections: { start: '快速入門', guide: '操作指南', keys: '鍵盤快速鍵', faq: '常見問題' },
    searchLabel: '搜尋說明',
    searchPlaceholder: '搜尋你想做的事，例如：字幕樣式',
    results: '搜尋結果',
    found: (n: number) => `找到 ${n} 篇指南`,
    emptyTitle: '沒有找到相關指南',
    emptyBody: '試試「字幕」「素材」「Agent」或「長寬比」，也可以從快速入門開始。',
    emptyAction: '檢視快速入門',
    welcomeEyebrow: '第一次使用？從這裡開始',
    welcomeTitle: '做出你的第一部字幕影片',
    welcomeBody: (steps: number) => `從一段素材到附字幕的成品，跟著這${cnCount(steps)}個步驟走。`,
    welcomeAction: '開始入門指南',
    welcomeDuration: (steps: number, minutes: number) => `${steps} 個步驟 · 約 ${minutes} 分鐘閱讀`,
    pathLabel: (steps: number) => `入門${cnCount(steps)}步`,
    pathMinutes: (minutes: number) => `${minutes} 分鐘閱讀`,
    moreTitle: '你可能還想了解',
    allGuides: '全部指南',
    keysHintLead: '找不到某個操作？',
    keysHintLink: '檢視鍵盤快速鍵',
    keysHintNote: '在編輯器中開啟清單',
    keysTitle: '少按幾下，快一點',
    keysIntro: '以下快速鍵在編輯器中使用。正在輸入文字時，按鍵會優先用於文字編輯。',
    keysPlatform: '快速鍵寫法',
    mac: 'macOS',
    other: 'Windows / Linux',
    guideTitle: '想做什麼，就從這裡找',
    guideIntro: '每篇只講一件事，讀完就能回到影片中試試看。',
    faqTitle: '遇到問題，先看看這裡',
    faqIntro: '從最常見的原因開始，一步步檢查。',
    minutes: (minutes: number) => `${minutes} 分鐘`,
    readTime: (minutes: number) => `約 ${minutes} 分鐘閱讀`,
    backToResults: '回到搜尋結果',
    backTo: (section: string) => `回到${section}`,
    pickVideo: '選擇一部影片',
    pickVideoNote: '先開啟影片，再依照指南操作。',
    ctaNote: '開啟對應的功能，接下來由你操作。',
    backToVideo: '回到影片',
    backNote: '關閉說明，回到影片中試試看。',
    next: (title: string) => `繼續閱讀：${title}`,
    footer: '內建指南 · 可離線閱讀',
    entry: '說明中心 · F1',
    entryLabel: '說明中心',
    settingsEntry: '說明',
  },
  previewKeys: {
    volume: (volume: number) => `預覽音量 ${volume}`,
    muted: '預覽已靜音',
    unmuted: (volume: number) => `預覽已取消靜音 · 音量 ${volume}`,
    fullscreenFailed: '無法以全螢幕顯示預覽',
  },
  stageToolbar: {
    label: '片段工具列',
    more: '更多',
    back: '返回',
    unavailable: '目前還無法使用',
    textColor: '文字顏色',
    fillColor: '填色',
    strokeColor: '外框顏色',
    strokeWidth: '粗細',
    muted: '已靜音',
    firstGeometry: (name: string) => `幾何資訊為唯讀，顯示的是第一個「${name}」；要修改數值，請只選取它。`,
    align: '對齊',
    alignTo: '參照',
    toSelection: '所選範圍',
    toCanvas: '畫布',
    alignLeft: '靠左對齊',
    alignHCenter: '水平置中',
    alignRight: '靠右對齊',
    alignTop: '靠上對齊',
    alignVCenter: '垂直置中',
    alignBottom: '靠下對齊',
    distribute: '分布',
    distributeX: '水平均分',
    distributeY: '垂直均分',
    alignNeed: '對齊至少需要兩個可移動的片段；參照畫布時一個也可以。',
    distributeNeed: '平均分布至少需要三個可移動的片段。',
    labelAlign: '對齊片段',
    labelDistribute: '分布片段',
    aligned: (n: number) => `已對齊 ${n} 個片段`,
    distributed: (n: number) => `已分布 ${n} 個片段`,
    inPlace: '已經在這個位置了，沒有需要移動的片段',
    duplicate: '再製',
    copy: '複製',
    removeAll: (n: number) => (n === 1 ? '刪除這個片段' : `刪除這 ${n} 個片段`),
    skipped: (n: number) => `有 ${n} 個片段不參與對齊與分布：主影片、音訊與字幕不會在畫布上單獨擺放，鎖定的片段不會移動。`,
    dragNote: '在畫面上拖曳其中一個，它們會一起移動。要逐一修改屬性，請只選取一個片段。',
    hint: '對齊、分布、再製與刪除都只算一步還原。',
    labelFlip: '翻轉',
    labelFit: '符合畫布',
    labelFill: '填滿畫布',
  },
  mentionGroups: {
    video: '這部影片',
    files: '影片與檔案',
  },
};
