import type { AcpCatalogMessages } from './acp-catalog.ts';

export const tr: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': "Amp kodlama ajanı ACP ile saran topluluk bağdaştırıcısı.",
    'auggie': "Augment Code komut satırı ajan; büyük kod tabanlarından bağlam bulmada başarılıdır.",
    'autohand': "Autohand kodlama ajan; kendi model hizmetini kullanır.",
    'cline': "Dosya düzenleyen ve komut çalıştıran açık kaynak, otonom kodlama ajan; kendi model hesabınızı kullanın.",
    'codebuddy-code': "Tencent Cloud komut satırı kodlama asistanı.",
    'codewhale': "DeepSeek ve açık modeller için geliştirilmiş terminal kodlama ajan.",
    'cortex-code': "Snowflake kullanan ekipler için Snowflake Cortex kodlama ajan.",
    'corust-agent': "Rust projelerine odaklanan kodlama ajan.",
    'crow-cli': "Başlangıçtan ACP için geliştirilmiş hafif kodlama ajan.",
    'deepagents': "LangChain tabanlı genel amaçlı Ajan; kod da yazabilir.",
    'devin': "Cognition Devin, terminalde.",
    'dimcode': "Birden fazla büyük model arasında geçiş yapabilen kodlama ajan.",
    'dirac': "Çağrı sayısını azaltmaya odaklanan açık kaynak kodlama ajan: paralel düzenleme ve sözdizimi ağacı düzenleme.",
    'factory-droid': "Factory Droid kodlama ajan.",
    'fast-agent': "Birçok model hizmetine bağlanan, yerleşik kodlama yeteneği olan Ajan çerçevesi. uv gerekir.",
    'gjc': "Mevcut kodlama aboneliğinizi kullanır, işlemden önce planlar ve riskli işlemlerden önce sorar.",
    'glm-acp-agent': "Zhipu GLM Coding Plan modellerini kullanır; oturum sırasında model değiştirilebilir.",
    'goose': "Mühendislik işlerini uçtan uca otomatikleştiren açık kaynak, genişletilebilir yerel Ajan.",
    'hermes': "Tamamladığı görevlerden kendini geliştiren Nous Research ajan.",
    'junie': "JetBrains kodlama ajan.",
    'kilo': "Komut satırı ve düzenleyici arasında paylaşılan açık kaynak kodlama ajan.",
    'kiro': "Yerleşik ACP desteğiyle Amazon kodlama ajan.",
    'minimax-code': "MiniMax terminal kodlama ajan.",
    'minion-code': "Minion çerçevesi tabanlı, geliştirici araçları içeren kodlama asistanı. uv gerekir.",
    'mistral-vibe': "Mistral açık kaynak kodlama asistanı.",
    'nova': "Compass AI yazılım mühendisliği ajan.",
    'poolside': "Poolside kodlama ajan.",
    'qoder': "Görevleri kendi başına bölüp uygulayan Qoder komut satırı kodlama asistanı.",
    'qwen-code': "Alibaba Qwen kodlama asistanı.",
    'sigit': "Tamamen bilgisayarınızda çalışan, cihazdaki yerel modelleri kullanabilen kodlama ajan.",
    'stakpak': "Rust ile yazılmış, güvenliğe odaklanan açık kaynak DevOps ajan.",
    'traecli': "ByteDance TRAE komut satırı kodlama ajan.",
    'vtcode': "Kod yapısını anlayan, güvenlik sınırlarıyla komut çalıştıran ve birçok modelle çalışan açık kaynak kodlama ajan.",
  },
};
