import type { AcpCatalogMessages } from './acp-catalog.ts';

export const ja: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': 'Amp のコーディング Agent を ACP で包むコミュニティ製アダプタ。',
    'auggie': 'Augment Code のコマンドライン Agent。大規模なコードベースからのコンテキスト取得が得意です。',
    'autohand': 'Autohand のコーディング Agent。独自のモデルサービスを使います。',
    'cline': 'ファイルの編集やコマンドの実行をこなす、オープンソースの自律型コーディング Agent。モデルのアカウントはご自身で用意します。',
    'codebuddy-code': 'Tencent Cloud のコマンドライン向けコーディングアシスタント。',
    'codewhale': 'DeepSeek とオープンモデル向けに作られたターミナル用コーディング Agent。',
    'cortex-code': 'Snowflake の Cortex コーディング Agent。すでに Snowflake を使っているチーム向けです。',
    'corust-agent': 'Rust プロジェクトに特化したコーディング Agent。',
    'crow-cli': '最初から ACP 向けに作られた軽量なコーディング Agent。',
    'deepagents': 'LangChain をベースにした汎用 Agent。コードも書けます。',
    'devin': 'Cognition の Devin をターミナルで。',
    'dimcode': '主要な複数のモデルを切り替えて使えるコーディング Agent。',
    'dirac': '呼び出し回数の削減を重視したオープンソースのコーディング Agent。並列編集と構文木ベースの編集を行います。',
    'factory-droid': 'Factory の Droid コーディング Agent。',
    'fast-agent': '多くのモデルサービスに接続できる Agent フレームワーク。コーディング機能を内蔵しています。uv が必要です。',
    'gjc': 'お使いのコーディング向けサブスクリプションを使い、計画を立ててから動き、危険な操作の前には確認します。',
    'glm-acp-agent': 'Zhipu GLM Coding Plan のモデルを使います。セッションの途中でモデルを切り替えられます。',
    'goose': 'エンジニアリングの雑務を最初から最後まで自動化する、オープンソースで拡張可能なローカル Agent。',
    'hermes': 'こなしたタスクから自己改善する Nous Research の Agent。',
    'junie': 'JetBrains のコーディング Agent。',
    'kilo': 'コマンドラインとエディタで共通に使える、オープンソースのコーディング Agent。',
    'kiro': 'Amazon のコーディング Agent。ACP をネイティブでサポートしています。',
    'minimax-code': 'MiniMax のターミナル用コーディング Agent。',
    'minion-code': 'Minion フレームワークをベースに、開発ツール一式を備えたコーディングアシスタント。uv が必要です。',
    'mistral-vibe': 'Mistral のオープンソースのコーディングアシスタント。',
    'nova': 'Compass AI のソフトウェアエンジニアリング Agent。',
    'poolside': 'Poolside のコーディング Agent。',
    'qoder': 'タスクを自分で分解して実行する、Qoder のコマンドライン向けコーディングアシスタント。',
    'qwen-code': 'Alibaba の Qwen コーディングアシスタント。',
    'sigit': 'すべてお使いのコンピュータ上で動作し、デバイス上のローカルモデルも使えるコーディング Agent。',
    'stakpak': 'Rust で書かれた、セキュリティ重視のオープンソース DevOps Agent。',
    'traecli': 'ByteDance TRAE のコマンドライン向けコーディング Agent。',
    'vtcode': 'コード構造を理解し、安全ガードレール付きでコマンドを実行し、多くのモデルに対応するオープンソースのコーディング Agent。',
  },
};
