import type { AcpCatalogMessages } from './acp-catalog.ts';

export const zhHans: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': '给 Amp 编码智能体套一层 ACP 的社区适配器。',
    'auggie': 'Augment Code 的命令行智能体，长于在大型代码库里检索上下文。',
    'autohand': 'Autohand 出品的编码智能体，用它自己的模型服务。',
    'cline': '开源的自主编码智能体，能改文件、跑命令，模型账号自己接。',
    'codebuddy-code': '腾讯云的命令行编码助手。',
    'codewhale': '面向 DeepSeek 与开源模型的终端编码智能体。',
    'cortex-code': 'Snowflake 的 Cortex 编码智能体，适合已经在用 Snowflake 的团队。',
    'corust-agent': '偏重 Rust 项目的编码智能体。',
    'crow-cli': '一个从一开始就按 ACP 写的轻量编码智能体。',
    'deepagents': '基于 LangChain 的通用智能体，也能写代码。',
    'devin': 'Cognition 的 Devin 在终端里的版本。',
    'dimcode': '可以在几家主流模型之间切换的编码智能体。',
    'dirac': '开源编码智能体，主打省调用量：并行改动、按语法树编辑。',
    'factory-droid': 'Factory 的 Droid 编码智能体。',
    'fast-agent': '可接多家模型服务的智能体框架，自带编码能力。需要 uv。',
    'gjc': '借用你已有的编码订阅，先列计划再动手，危险操作前会先问。',
    'glm-acp-agent': '用智谱 GLM 编码套餐里的模型，会话可以中途换模型。',
    'goose': '开源、可扩展的本地智能体，能把工程上的杂活自动做完。',
    'hermes': 'Nous Research 的智能体，会从用过的任务里自我改进。',
    'junie': 'JetBrains 的编码智能体。',
    'kilo': '开源编码智能体，命令行与编辑器共用一套。',
    'kiro': 'Amazon 的编码智能体，原生支持 ACP。',
    'minimax-code': 'MiniMax 的终端编码智能体。',
    'minion-code': '基于 Minion 框架、带一套开发工具的编码助手。需要 uv。',
    'mistral-vibe': 'Mistral 的开源编码助手。',
    'nova': 'Compass AI 的软件工程智能体。',
    'poolside': 'Poolside 的编码智能体。',
    'qoder': 'Qoder 的命令行编码助手，能自己拆任务、连续执行。',
    'qwen-code': '阿里通义千问的编码助手。',
    'sigit': '完全在本机运行的编码智能体，可以选用设备上的本地模型。',
    'stakpak': '用 Rust 写的开源运维智能体，偏重安全。',
    'traecli': '字节跳动 TRAE 的命令行编码智能体。',
    'vtcode': '开源编码智能体，懂代码结构，跑命令有安全护栏，可接多家模型。',
  },
};
