import type { AcpCatalogMessages } from './acp-catalog.ts';

export const ptBR: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': 'Um adaptador comunitário que envolve o agente de código Amp em ACP.',
    'auggie': 'O agente de linha de comando do Augment Code, bom em recuperar contexto de grandes bases de código.',
    'autohand': 'Um agente de código do Autohand que usa seu próprio serviço de modelos.',
    'cline': 'Um agente de código autônomo de código aberto que edita arquivos e executa comandos; use sua própria conta de modelo.',
    'codebuddy-code': 'O assistente de código de linha de comando da Tencent Cloud.',
    'codewhale': 'Um agente de código no terminal feito para DeepSeek e modelos abertos.',
    'cortex-code': 'O agente de código Cortex da Snowflake, para equipes que já usam Snowflake.',
    'corust-agent': 'Um agente de código focado em projetos Rust.',
    'crow-cli': 'Um agente de código leve feito para ACP desde o início.',
    'deepagents': 'Um agente de uso geral feito com LangChain que também escreve código.',
    'devin': 'O Devin da Cognition no terminal.',
    'dimcode': 'Um agente de código que alterna entre vários modelos principais.',
    'dirac': 'Um agente de código aberto focado em menos chamadas: edições paralelas e edição por árvore sintática.',
    'factory-droid': 'O agente de código Droid da Factory.',
    'fast-agent': 'Um framework de agentes que conecta vários serviços de modelos, com recursos de código integrados. Exige uv.',
    'gjc': 'Usa sua assinatura de código existente, planeja antes de agir e pergunta antes de operações arriscadas.',
    'glm-acp-agent': 'Usa modelos do Zhipu GLM Coding Plan; você pode trocar de modelo durante a sessão.',
    'goose': 'Um agente local extensível de código aberto que automatiza tarefas de engenharia de ponta a ponta.',
    'hermes': 'O agente da Nous Research que melhora a si mesmo com as tarefas realizadas.',
    'junie': 'O agente de código da JetBrains.',
    'kilo': 'Um agente de código aberto compartilhado entre a linha de comando e o editor.',
    'kiro': 'O agente de código da Amazon, com suporte nativo a ACP.',
    'minimax-code': 'O agente de código no terminal da MiniMax.',
    'minion-code': 'Um assistente de código feito com o framework Minion e um conjunto de ferramentas de desenvolvimento. Exige uv.',
    'mistral-vibe': 'O assistente de código aberto da Mistral.',
    'nova': 'O agente de engenharia de software da Compass AI.',
    'poolside': 'O agente de código da Poolside.',
    'qoder': 'O assistente de código de linha de comando da Qoder, que divide e executa tarefas sozinho.',
    'qwen-code': 'O assistente de código Qwen da Alibaba.',
    'sigit': 'Um agente de código que executa inteiramente no seu computador e pode usar modelos locais do dispositivo.',
    'stakpak': 'Um agente DevOps de código aberto escrito em Rust, com foco em segurança.',
    'traecli': 'O agente de código de linha de comando TRAE da ByteDance.',
    'vtcode': 'Um agente de código aberto que entende a estrutura do código, executa comandos com proteções de segurança e trabalha com vários modelos.',
  },
};
