import type { AcpCatalogMessages } from './acp-catalog.ts';

export const zhHant: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': '社群製作的轉接器，把 Amp 程式設計 Agent 包裝成 ACP。',
    'auggie': 'Augment Code 的命令列 Agent，擅長從大型程式碼庫中擷取脈絡。',
    'autohand': 'Autohand 推出的程式設計 Agent，使用它自己的模型服務。',
    'cline': '開源的自主程式設計 Agent，能修改檔案、執行指令；模型帳號自備。',
    'codebuddy-code': '騰訊雲的命令列程式設計助理。',
    'codewhale': '為 DeepSeek 與開放模型打造的終端機程式設計 Agent。',
    'cortex-code': 'Snowflake 的 Cortex 程式設計 Agent，適合已在使用 Snowflake 的團隊。',
    'corust-agent': '專注於 Rust 專案的程式設計 Agent。',
    'crow-cli': '從一開始就為 ACP 打造的輕量程式設計 Agent。',
    'deepagents': '以 LangChain 打造的通用 Agent，也能寫程式。',
    'devin': 'Cognition 的 Devin，在終端機裡使用。',
    'dimcode': '可以在幾個主流模型之間切換的程式設計 Agent。',
    'dirac': '開源程式設計 Agent，主打減少呼叫次數：平行修改、依語法樹編輯。',
    'factory-droid': 'Factory 的 Droid 程式設計 Agent。',
    'fast-agent': '可連接多家模型服務的 Agent 框架，內建程式設計能力。需要 uv。',
    'gjc': '沿用你現有的程式設計訂閱，先規劃再動手，執行高風險操作前會先詢問。',
    'glm-acp-agent': '使用智譜 GLM Coding Plan 的模型，對話中途可以切換模型。',
    'goose': '開源、可擴充的本機 Agent，能把工程上的雜務從頭到尾自動完成。',
    'hermes': 'Nous Research 的 Agent，會從做過的任務中自我改進。',
    'junie': 'JetBrains 的程式設計 Agent。',
    'kilo': '開源程式設計 Agent，命令列與編輯器共用同一套。',
    'kiro': 'Amazon 的程式設計 Agent，原生支援 ACP。',
    'minimax-code': 'MiniMax 的終端機程式設計 Agent。',
    'minion-code': '以 Minion 框架打造、附一套開發工具的程式設計助理。需要 uv。',
    'mistral-vibe': 'Mistral 的開源程式設計助理。',
    'nova': 'Compass AI 的軟體工程 Agent。',
    'poolside': 'Poolside 的程式設計 Agent。',
    'qoder': 'Qoder 的命令列程式設計助理，能自行拆解並執行任務。',
    'qwen-code': '阿里巴巴通義千問的程式設計助理。',
    'sigit': '完全在你的電腦上執行的程式設計 Agent，可以使用裝置上的本機模型。',
    'stakpak': '以 Rust 撰寫的開源 DevOps Agent，注重安全。',
    'traecli': '字節跳動 TRAE 的命令列程式設計 Agent。',
    'vtcode': '開源程式設計 Agent，理解程式碼結構，執行指令時有安全防護，可搭配多家模型。',
  },
};
