import type { AcpCatalogMessages } from './acp-catalog.ts';

export const de: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': "Community-Adapter für den Amp-Coding-Agenten über ACP.",
    'auggie': "CLI-Agent von Augment Code, besonders für Kontextsuche in großen Codebeständen.",
    'autohand': "Coding-Agent von Autohand mit eigenem Modelldienst.",
    'cline': "Autonomer Open-Source-Coding-Agent für Dateiänderungen und Befehle; eigenes Modellkonto nötig.",
    'codebuddy-code': "CLI-Coding-Assistent von Tencent Cloud.",
    'codewhale': "Terminal-Coding-Agent für DeepSeek und offene Modelle.",
    'cortex-code': "Snowflakes Cortex-Coding-Agent für Teams mit Snowflake.",
    'corust-agent': "Coding-Agent mit Fokus auf Rust-Projekte.",
    'crow-cli': "Leichter Coding-Agent, von Anfang an für ACP entwickelt.",
    'deepagents': "Allgemeiner LangChain-Agent mit Programmierfähigkeiten.",
    'devin': "Cognitions Devin im Terminal.",
    'dimcode': "Coding-Agent mit Wechsel zwischen mehreren führenden Modellen.",
    'dirac': "Open-Source-Coding-Agent mit weniger Aufrufen durch parallele Änderungen und Syntaxbaum-Bearbeitung.",
    'factory-droid': "Factorys Droid-Coding-Agent.",
    'fast-agent': "Agentenframework für viele Modelldienste mit integrierten Programmierfähigkeiten. Benötigt uv.",
    'gjc': "Verwendet vorhandenes Coding-Abonnement, plant zuerst und fragt vor riskanten Aktionen.",
    'glm-acp-agent': "Verwendet Zhipu-GLM-Coding-Plan-Modelle; Modellwechsel während Sitzung möglich.",
    'goose': "Erweiterbarer lokaler Open-Source-Agent für vollständige Automatisierung technischer Aufgaben.",
    'hermes': "Nous-Research-Agent, der sich anhand erledigter Aufgaben verbessert.",
    'junie': "Coding-Agent von JetBrains.",
    'kilo': "Open-Source-Coding-Agent für Befehlszeile und Editor.",
    'kiro': "Amazons Coding-Agent mit nativer ACP-Unterstützung.",
    'minimax-code': "Terminal-Coding-Agent von MiniMax.",
    'minion-code': "Coding-Assistent auf Minion mit Entwicklerwerkzeugen. Benötigt uv.",
    'mistral-vibe': "Open-Source-Coding-Assistent von Mistral.",
    'nova': "Softwareentwicklungsagent von Compass AI.",
    'poolside': "Coding-Agent von Poolside.",
    'qoder': "Qoders CLI-Coding-Assistent, der Aufgaben selbstständig aufteilt und ausführt.",
    'qwen-code': "Coding-Assistent Qwen von Alibaba.",
    'sigit': "Vollständig auf Ihrem Computer laufender Coding-Agent mit lokalen Modellen.",
    'stakpak': "Sicherheitsorientierter Open-Source-DevOps-Agent in Rust.",
    'traecli': "CLI-Coding-Agent von ByteDance TRAE.",
    'vtcode': "Open-Source-Coding-Agent für Codestruktur, geschützte Befehlsausführung und viele Modelle.",
  } as Record<string, string>,
};
