import type { AcpCatalogMessages } from './acp-catalog.ts';

export const fr: AcpCatalogMessages = {
  descriptions: {
    'amp-acp': "Adaptateur communautaire intégrant l’Agent de code Amp dans ACP.",
    'auggie': "Agent CLI Augment Code, efficace pour récupérer le contexte de grandes bases de code.",
    'autohand': "Agent de code Autohand utilisant son propre service de modèles.",
    'cline': "Agent de code autonome open source, modifie les fichiers et exécute des commandes ; compte de modèle à fournir.",
    'codebuddy-code': "Assistant de code CLI Tencent Cloud.",
    'codewhale': "Agent de code terminal pour DeepSeek et modèles ouverts.",
    'cortex-code': "Agent de code Cortex de Snowflake, pour les équipes déjà sur Snowflake.",
    'corust-agent': "Agent de code spécialisé dans les projets Rust.",
    'crow-cli': "Agent de code léger conçu pour ACP.",
    'deepagents': "Agent général sur LangChain pouvant aussi coder.",
    'devin': "Devin de Cognition, dans le terminal.",
    'dimcode': "Agent de code pouvant changer entre plusieurs grands modèles.",
    'dirac': "Agent de code open source réduisant les appels : modifications parallèles et arbres syntaxiques.",
    'factory-droid': "Agent de code Droid de Factory.",
    'fast-agent': "Cadre d’Agents connecté à de nombreux modèles, avec capacités de code intégrées. Nécessite uv.",
    'gjc': "Utilise votre abonnement de code, planifie avant d’agir et demande avant les opérations risquées.",
    'glm-acp-agent': "Modèles du GLM Coding Plan de Zhipu ; changement possible en session.",
    'goose': "Agent local open source et extensible automatisant les tâches d’ingénierie de bout en bout.",
    'hermes': "Agent Nous Research s’améliorant depuis ses tâches accomplies.",
    'junie': "Agent de code JetBrains.",
    'kilo': "Agent de code open source partagé entre CLI et éditeur.",
    'kiro': "Agent de code Amazon, avec ACP natif.",
    'minimax-code': "Agent de code terminal MiniMax.",
    'minion-code': "Assistant sur le cadre Minion avec outils de développement. Nécessite uv.",
    'mistral-vibe': "Assistant de code open source Mistral.",
    'nova': "Agent d’ingénierie logicielle Compass AI.",
    'poolside': "Agent de code Poolside.",
    'qoder': "Assistant CLI Qoder décomposant et exécutant les tâches seul.",
    'qwen-code': "Assistant de code Qwen d’Alibaba.",
    'sigit': "Agent de code entièrement local, pouvant utiliser des modèles locaux.",
    'stakpak': "Agent DevOps open source axé sécurité, écrit en Rust.",
    'traecli': "Agent de code CLI TRAE de ByteDance.",
    'vtcode': "Agent de code open source comprenant la structure du code, exécutant des commandes avec garde-fous, compatible avec de nombreux modèles.",
  } as Record<string, string>,
};
