import type { AgentSkillsMessages } from './agent-skills.ts';

export const vi: AgentSkillsMessages = {
  origin: { builtin: "Có sẵn", personal: "Của tôi", 'third-party': "Bên thứ ba" },
  all: "Tất cả",
  commit: (sha: string) => ` (${sha})`,
  bytes: (n) => `${n} byte`,
  action: {
    load: "tải Skill",
    toggle: "bật hoặc tắt",
    add: "thêm",
    import: "nhập",
    remove: "gỡ",
    read: "mở tệp",
    send: "gửi",
  },
  exists: (id) => `Đã có Skill tên “${id ?? 'này'}”, sẽ không ghi đè. Gỡ bản cũ trước hoặc đổi tên thư mục rồi thêm lại.`,
  invalid: (issue) => `Đây không phải Skill dùng được: ${issue}. Thư mục gốc cần SKILL.md bắt đầu bằng name và description.`,
  tooLarge: (files,total,skillFile) => `Skill này quá lớn: tối đa ${files} tệp với tổng dung lượng ${total}, riêng SKILL.md tối đa ${skillFile}.`,
  githubNotFound: "Không tìm thấy kho, nhánh hoặc thư mục này trên GitHub (có thể là riêng tư). Kiểm tra địa chỉ.",
  folderNotFound: "Không tìm thấy thư mục này. Có thể đã di chuyển hoặc xóa.",
  urlInvalid: "Không nhận dạng được địa chỉ. Dùng owner/repo hoặc https://github.com/owner/repo/tree/branch/folder.",
  network: "Không thể truy cập GitHub. Kiểm tra mạng và thử lại.",
  rateLimited: "Đã đạt giới hạn truy cập ẩn danh của GitHub. Thử nhập lại sau.",
  offline: "Chế độ ngoại tuyến nghiêm ngặt đang bật, không thể nhập từ GitHub.",
  builtinNotRemovable: "Không thể gỡ Skill tích hợp, nhưng có thể tắt.",
  notFound: "Skill này không còn; có thể vừa bị gỡ.",
  fileNotFound: "Tệp này không còn.",
  fileTooLarge: "Tệp này quá lớn để hiển thị tại đây. Bạn có thể mở trong thư mục.",
  fileNotText: "Đây không phải tệp văn bản nên không hiển thị tại đây.",
  webNotAllowed: "Không thể làm trong trình duyệt. Dùng ứng dụng BaoCut trên máy tính.",
  webReadOnly: "Phiên trình duyệt này chỉ đọc, không thể thay đổi.",
  failed: (action,raw) => `Không thể ${action}: ${raw}`,
  sendFailed: (raw) => `Không thể gửi: ${raw}`,
};
