import type { AgentToolStepsMessages } from './agent-tool-steps.ts';

export const ko: AgentToolStepsMessages = {
  label: {
    translate: '번역',
    cut: '컷 편집',
    importAssets: '소재 가져오기',
    editVideo: '영상 수정',
    listVideos: '영상 목록 보기',
    newVideo: '새 영상',
    readVideo: '영상 읽기',
    deleteVideo: '영상 삭제',
    readTranscript: '전사본 읽기',
    undoEdit: '수정 실행 취소',
    captions: '자막 레이어 만들기',
    transcribe: '전사',
    dub: '번역 및 더빙',
    mergeFiles: '파일 합치기',
    extractAudio: '오디오 추출',
    compressFiles: '파일 압축',
    speech: '음성 합성',
    image: '이미지 생성',
    models: '모델 보기',
    installModel: '로컬 모델 다운로드',
    export: '내보내기',
    downloadVideo: '영상 다운로드',
    saveToDownloads: '다운로드 폴더에 저장',
    viewTask: '작업 보기',
    cancelTask: '작업 취소',
    saveOutput: '결과물 저장',
    browseSpace: 'Space 둘러보기',
    searchSpace: 'Space 검색',
    readSkill: 'Skill 읽기',
    requestGrant: '허가 요청',
    readContract: '작업 계약 읽기',
    refineContract: '작업 계약 구체화',
    recordCheck: '검수 결과 기록',
  },
  exportKind: {
    subtitles: '자막',
    transcript: '전사본',
    audio: '오디오',
    video: '내보내기',
    portable: '휴대용 패키지',
    project: '프로젝트 파일',
  },
  places: (n: number) => `${n}곳`,
  count: (n: number) => `${n}개`,
  bilingual: '이중 언어',
  images: (n: number) => `${n}장`,
  files: (n: number) => `파일 ${n}개`,
};
