import type { AiToolsMessages } from './ai-tools.ts';
import { pluralForm } from '@baocut/protocol';

const soonTail = 'Il Runtime non ha ancora questo flusso e sul video non c’è un livello per regolare l’inquadratura, quindi non c’è ancora un modulo da compilare qui.';
const scopeOf = (o: { scope: string | null; p: string }) => o.scope ? `${o.scope} di ${o.p}` : o.p;

export const it: AiToolsMessages = {
  groups: { frame: 'Fotogramma', transcript: 'Trascrizione', translate: 'Traduzione', writing: 'Scrittura', publish: 'Pubblicazione' },
  tools: {
    crop: { name: 'Ritaglio intelligente', desc: 'Cambia il rapporto d’aspetto mantenendo parlanti, lavagne e altri soggetti principali nell’inquadratura', why: `Il ritaglio intelligente deve seguire parlanti, lavagne e altri soggetti principali nel video, poi ritagliare al nuovo rapporto d’aspetto. ${soonTail}` },
    shortscut: { name: 'Dividi in video brevi', desc: 'Scegli alcuni segmenti di questo video e trasformali ciascuno in un video breve verticale', why: `Dividere in video brevi significa scegliere alcuni segmenti, ritagliarli in verticale e regolare l’inquadratura segmento per segmento sul video. ${soonTail}` },
    polish: { name: 'Migliora trascrizione', desc: 'Correggi refusi, aggiungi punteggiatura e dividi in paragrafi senza riscrivere le tue parole', setup: ['Correggi i refusi evidenti, aggiungi la punteggiatura mancante e dividi in paragrafi per argomento.', 'Le tue parole non vengono riscritte e nulla viene rimosso; si correggono solo errori evidenti.'] },
    chapters: { name: 'Genera capitoli', desc: 'Dividi un video lungo in capitoli con titoli', setup: ['Raggruppa i paragrafi in capitoli per argomento e assegna un titolo a ciascuno.', 'L’esportazione e la pagina di condivisione usano gli stessi capitoli.'] }, speakers: { name: 'Identifica parlanti', desc: 'Riconosci chi parla; sottotitoli e trascrizione hanno i nomi' }, retranscribe: { name: 'Ritrascrivi', desc: 'Rielabora l’audio con un altro modello, anche un solo capitolo o segmento', setup: ['Rielabora con un altro modello vocale e sostituisci i dati delle singole parole in questo intervallo.', 'Trascrizione, sottotitoli e traduzioni fuori dall’intervallo rimangono esattamente invariati.'] }, cleanup: { name: 'Trova tagli', desc: 'Trova intercalari, pause lunghe e riprese non riuscite; rivedi i suggerimenti prima di tagliare', setup: ['Cerca intercalari, pause di 0,8 s o più e inizi di frase ripetuti.', 'Ricevi un elenco di tagli proposti da confermare prima di tagliare.'] },
    translate: { name: 'Traduci sottotitoli', desc: 'Traduci frase per frase e allinea i timecode usando i dati delle singole parole' }, stale: { name: 'Aggiorna traduzioni non aggiornate', desc: 'Ritraduci solo le frasi con origine modificata o tagliata', setup: ['Ritraduci solo le frasi con origine cambiata: quelle modificate e quelle in cui un taglio ha rimosso una parte della frase.', 'Traduci dall’originale tagliato; le traduzioni di frasi interamente tagliate vengono tagliate insieme. Il resto non cambia.'] }, dub: { name: 'Traduci doppiaggio', desc: 'Scegli una lingua e fai parlare il video con una voce simile al parlante originale o a un madrelingua; i valori predefiniti bastano per iniziare' }, summary: { name: 'Scrivi riepilogo', desc: 'Testo e punti principali con timestamp; fai clic su un tempo per raggiungerlo' }, blog: { name: 'Scrivi articolo blog', desc: 'Riscrivi come articolo dal punto di vista dell’autore o dello spettatore' }, title: { name: 'Suggerisci titoli', desc: 'Ottieni diversi candidati da angolazioni diverse, poi scegline uno' }, desc: { name: 'Scrivi descrizione', desc: 'Descrizione per la pubblicazione, con timecode dei capitoli e tag' }, cover: { name: 'Crea copertina', desc: 'Crea alcuni candidati di copertina da fotogrammi principali, poi scegline uno' },
  },
  unknownTool: (id: string) => `Nessuno strumento IA corrispondente: ${id}`, cleanup: { fillers: { label: 'Intercalari', sub: 'Parole come «eh», «uh», «tipo» e «sai»', off: 'intercalari' }, pauses: { label: 'Pause lunghe ≥ 0,8 s', sub: 'Trovate dai tempi delle singole parole', off: 'pause lunghe' }, repeats: { label: 'Inizi ripetuti', sub: 'Una frase iniziata due volte; viene conservata la seconda', off: 'inizi ripetuti' } }, cleanupOff: (offs: readonly string[]) => `Non cercare ${new Intl.ListFormat('it', { type: 'conjunction' }).format(offs)}`, lengths: { short: 'Breve', medium: 'Media', long: 'Lunga' }, styles: { plain: 'Semplice', pop: 'Divulgativo', sharp: 'Sarcastico', light: 'Informale', pro: 'Professionale', custom: 'Personalizzato…' }, views: { auto: 'Automatico', author: 'Sono l’autore', viewer: 'Sono uno spettatore' }, coverText: { none: 'Nessun testo', phrase: 'Una frase breve', 'phrase-sub': 'Una frase e una riga di testo piccolo' }, viewName: { author: 'autore', viewer: 'spettatore' },
  extraScope: (scope: string) => `Concentrati solo su ${scope}`, extraLength: (label: string) => `Lunghezza: ${label}`, extraStyle: (style: string) => `Stile: ${style}`, extraLanguage: (language: string) => `Scrivi in ${language}`, extraView: (view: string) => `Punto di vista: ${view}`, extraPlatform: (platform: string) => `Pubblicazione su: ${platform}. Segui le sue regole e ricordami di verificare al termine`, extraIdea: (idea: string) => `La cosa da dire sulla copertina: ${idea}`, extraRatio: (ratio: string) => `Rapporto d’aspetto ${ratio}`, extraCoverText: (label: string) => `Testo sulla copertina: ${label}`, titled: (title: string) => `«${title}»`, thisVideo: 'questo video', sourceEdited: (n: number | null) => n === null ? 'origine modificata' : pluralForm('it', n, { one: `${n} frase modificata nell’originale`, other: `${n} frasi modificate nell’originale` }), sourceCut: (n: number | null) => n === null ? 'origine tagliata' : pluralForm('it', n, { one: `${n} frase tagliata nell’originale`, other: `${n} frasi tagliate nell’originale` }), sourceJoin: (parts: readonly string[]) => parts.join(', '),
  intents: {
    stale: (o) => `Alcune traduzioni in ${o.p} non sono aggiornate${o.why ? ` (${o.why})` : ' perché l’originale è stato modificato'}. Ritraduci solo quelle frasi${o.cut ? '; ritraduci quelle tagliate dall’originale tagliato e rimuovi insieme le traduzioni delle frasi interamente tagliate' : ''}. Lascia tutto il resto esattamente invariato.`, polish: (o) => `Migliora la trascrizione di ${scopeOf(o)}: correggi refusi, aggiungi punteggiatura e dividi in paragrafi per argomento, senza riscrivere le mie parole.`, chapters: (o) => `Dividi ${o.p} in capitoli per argomento e assegna a ciascuno un titolo breve.`, speakers: (o) => `Identifica i parlanti in ${scopeOf(o)}. Mostrami i risultati da confermare prima di scriverli nel video.`, retranscribe: (o) => `Ritrascrivi ${scopeOf(o)} con un altro modello vocale e lascia tutto fuori dall’intervallo esattamente invariato.`, cleanup: (o) => `Trova intercalari, pause lunghe e inizi di frase ripetuti in ${scopeOf(o)}. Elencali prima; confermerò prima di tagliare.`, summary: (o) => `Scrivi un riepilogo dei punti principali con timecode dalla trascrizione di ${o.p}.`, blog: (o) => `Riscrivi ${o.p} come articolo blog pronto per la pubblicazione.`, title: (o) => `Suggerisci ${pluralForm('it', o.count, { one: `${o.count} titolo candidato`, other: `${o.count} titoli candidati` })} per ${o.p}, ciascuno da un’angolazione diversa, con un motivo di una riga per ognuno, e consigliamene uno.`, desc: (o) => `Scrivi una descrizione di ${o.p} per la pubblicazione, con timecode dei capitoli e una riga di tag.`, cover: (o) => `Crea ${pluralForm('it', o.count, { one: `${o.count} candidato di copertina`, other: `${o.count} candidati di copertina` })} per ${o.p}: scegli prima fotogrammi principali, usa un approccio diverso all’immagine di base per ogni candidato e verifica ogni copertina a piccole dimensioni prima di mostrarmele.`,
  }, endSentence: (text: string) => /[.!?]$/.test(text) ? text : `${text}.`, joinPrompt: (head: string, extra: readonly string[]) => [head, ...extra].join(' '),
 groupSub: { writing: 'Per chi legge: sapere di cosa parla il video senza guardarlo', publish: 'Per chi pubblica il video: far venire voglia di aprirlo e mantenere la promessa' },
 laterNote: 'Traduci sottotitoli è ancora nel pannello Sottotitoli e Traduci doppiaggio nel pannello Audio; arriveranno qui più avanti.',
 effect: { polish: 'Modifica la trascrizione: applicata alla fine, annullabile in un passo', chapters: 'Modifica i capitoli: applicati alla fine, annullabili in un passo', speakers: 'Confermi prima il risultato; viene scritto nel video solo quando lo applichi', retranscribe: 'Sostituisce la trascrizione in questo intervallo: applicata alla fine, annullabile in un passo', cleanup: 'Propone solo tagli; non si taglia nulla finché non confermi', stale: 'Ritraduce solo le frasi non aggiornate; il resto non cambia', summary: 'Non modifica il video: il risultato è da leggere e copiare', blog: 'Non modifica il video: il risultato è da leggere e copiare', title: 'Non modifica il video: scegline uno da usare', desc: 'Non modifica il video: il risultato è da leggere e copiare', cover: 'Non modifica il video: scegline una da usare' },
 standMarkdown: (language) => (language ? `Scrivi in Markdown, in ${language}.` : 'Scrivi in Markdown, nella stessa lingua della trascrizione.'),
 standLanguage: (language) => (language ? `Scrivi in ${language}.` : 'Scrivi nella stessa lingua della trascrizione.'),
 standing: { summary: ['Comincia dalla conclusione, poi elenca i punti chiave, ciascuno con il suo timecode (mm:ss).', 'Lunghezza moderata: da tre a cinque paragrafi.'], blog: ['Scegli il punto di vista in base alla provenienza del video: come autore se il video è mio, come spettatore se è di altri.', 'Stile semplice, senza toni pubblicitari.'], title: ['Metti ogni candidato su una riga.'], desc: ['Includi i timecode dei capitoli e una riga di tag.'], cover: ['Il testo della copertina è nella lingua della trascrizione.'], polish: ['Non riscrivere le mie parole e non togliere nulla; correggi solo gli errori evidenti.'], chapters: ['Raggruppa per argomento, con un titolo breve per ogni capitolo.'] },
 sessionNew: 'Nuova sessione', sessionNewSub: 'Usa questo video come contesto; un compito per sessione, senza reinviare una lunga cronologia', sessionCurrent: (title) => `Continua «${title}»`, sessionUntitled: 'la sessione di questo video',
 sessionCurrentSub: (messages) => messages === null ? 'Reinvia la cronologia della sessione, che costa di più quando la cache del prompt scade' : `${messages === 1 ? '1 messaggio' : `${messages} messaggi`} finora · reinvia la cronologia, che costa di più quando la cache del prompt scade`,
 hintNew: 'Avvia una nuova sessione con questo video come contesto. Seguila lì; ogni modifica dell’agente al video si può annullare.',
 hintCurrent: 'Invia alla sessione attuale di questo video, con il video come contesto. Seguila lì; ogni modifica dell’agente al video si può annullare.',
};
