import type { AppUpdateMessages } from './app-update.ts';

export const zhHant: AppUpdateMessages = {
  justNow: '剛剛',
  minutesAgo: (n: number) => `${n} 分鐘前`,
  hoursAgo: (n: number) => `${n} 小時前`,
  daysAgo: (n: number) => `${n} 天前`,
  failure: {
    check: '無法連線到更新伺服器，請檢查網路後再試。',
    download: '下載沒有完成，請檢查網路後再試。',
    verify: '下載的檔案沒有通過驗證，已經刪除。',
    signature: '新版本的簽章與目前的應用程式不一致，所以沒有安裝。請從下載頁手動安裝。',
    install: '無法完成安裝，請從下載頁手動安裝。',
    manual: '這份 BaoCut 無法自行替換：已開啟下載好的檔案和下載頁，請手動安裝。',
  },
  version: (version: string, build: number) => `${version}（Build ${build}）`,
  appStore: 'App Store 版本由 App Store 負責更新',
  devBuild: '開發建置版不檢查更新',
  checking: '正在檢查…',
  upToDate: '已是最新版本',
  checkForUpdates: '檢查更新',
  available: (version: string) => `有新版本 ${version}`,
  needsMacOS: (version: string) => `需要 macOS ${version}`,
  downloadAndInstall: '下載並安裝',
  verifyingVersion: (version: string) => `正在驗證 ${version}…`,
  downloadingVersion: (version: string, pct: number) => `正在下載 ${version} · ${pct}%`,
  cancel: '取消',
  readyWaiting: (version: string) => `${version} 已下載，背景任務結束後安裝`,
  restartAndUpdate: '重新啟動並更新',
  stopWaiting: '不等了',
  readyOnQuit: (version: string) => `${version} 已下載，結束 BaoCut 時自動安裝`,
  installing: '正在安裝…',
  retry: '重試',
  downloadPage: '前往下載頁',
  lastCheck: (when: string) => `上次檢查：${when}`,
  waitingRunning: (n: number) => `還有 ${n} 個背景任務在執行，全部結束後會自動安裝更新。`,
  waitingDone: '背景任務都已結束，正在安裝…',
  tipAvailable: (version: string) => `有新版本 · BaoCut ${version}`,
  tipVerifying: '正在驗證更新…',
  tipDownloading: (pct: number) => `正在下載更新 · ${pct}%`,
  tipReady: '更新已下載 · 結束時自動安裝',
  tipError: '更新失敗 · 按一下查看',
  later: '稍後',
  verifying: '正在驗證…',
  downloading: (pct: number) => `正在下載 · ${pct}%`,
  titleReady: '更新已下載',
  titleAvailable: '有新版本',
  current: (version: string) => `你目前使用的是 BaoCut ${version}。`,
  noteOnQuit: '結束 BaoCut 時會自動安裝，不用現在重新啟動。',
  notesTitle: '更新內容',
  readyToast: (version: string) => `BaoCut ${version} 已下載，結束時自動安裝`,
  availableToast: (version: string) => `BaoCut ${version} 可以更新了`,
  view: '檢視',
  restartTitle: '現在重新啟動並更新？',
  restartBody: (n: number) => `有 ${n} 個背景任務正在執行，重新啟動會中斷它們，之後可以重新開始。`,
  remoteTitle: '下列項目在遠端執行，停止後供應商那邊可能仍在執行或計費：',
  stopAndInstall: '現在停止並安裝',
  waitAndInstall: '等任務結束後安裝',
  autoRow: {
    label: '自動檢查並下載更新',
    desc: '啟動時以及之後每 6 小時檢查一次。下載好的更新會在你下次結束 BaoCut 時安裝，也可以立即重新啟動來更新。BaoCut 不會自行重新啟動。',
  },
};
