import type { AppUpdateMessages } from './app-update.ts';

export const tr: AppUpdateMessages = {
  justNow: "Az önce",
  minutesAgo: (n) => `${n} dakika önce`,
  hoursAgo: (n) => `${n} saat önce`,
  daysAgo: (n) => `${n} gün önce`,
  failure: {
    check: "Güncelleme sunucusuna erişilemiyor. Ağınızı denetleyip yeniden deneyin.",
    download: "İndirme tamamlanmadı. Ağınızı denetleyip yeniden deneyin.",
    verify: "İndirilen dosya doğrulamayı geçemedi ve silindi.",
    signature: "Yeni sürümün imzası bu uygulamayla eşleşmedi; yüklenmedi. İndirme sayfasından elle yükleyin.",
    install: "Yükleme tamamlanamadı. İndirme sayfasından elle yükleyin.",
    manual: "Bu BaoCut kopyası kendini değiştiremiyor. İndirilen dosya ve indirme sayfası açıldı; elle yükleyin.",
  },
  version: (version: string, build: number) => `${version} (Derleme ${build})`,
  appStore: "App Store sürümleri App Store üzerinden güncellenir",
  devBuild: "Geliştirme sürümleri güncelleme denetlemez",
  checking: "Denetleniyor…",
  upToDate: "Güncelsiniz",
  checkForUpdates: "Güncellemeleri denetle",
  available: (version) => `Yeni ${version} sürümü kullanılabilir`,
  needsMacOS: (version) => `macOS ${version} gerekir`,
  downloadAndInstall: "İndir ve yükle",
  verifyingVersion: (version) => `${version} doğrulanıyor…`,
  downloadingVersion: (version,pct) => `${version} indiriliyor · %${pct}`,
  cancel: "İptal",
  readyWaiting: (version) => `${version} indirildi; arka plan görevleri bitince kurulur`,
  restartAndUpdate: "Yeniden başlat ve güncelle",
  stopWaiting: "Bekleme",
  readyOnQuit: (version) => `${version} indirildi; BaoCut uygulamasından çıkınca otomatik kurulur`,
  installing: "Yükleniyor…",
  retry: "Yeniden dene",
  downloadPage: "İndirme sayfasına git",
  lastCheck: (when) => `Son denetim: ${when}`,
  waitingRunning: (n) => `${n} arka plan görevi hâlâ çalışıyor; hepsi bitince güncelleme otomatik kurulur.`,
  waitingDone: "Arka plan görevleri tamamlandı. Kuruluyor…",
  tipAvailable: (version) => `Yeni sürüm · BaoCut ${version}`,
  tipVerifying: "Güncelleme doğrulanıyor…",
  tipDownloading: (pct) => `Güncelleme indiriliyor · %${pct}`,
  tipReady: "Güncelleme indirildi · çıkışta kurulur",
  tipError: "Güncelleme başarısız · görmek için tıklayın",
  later: "Daha sonra",
  verifying: "Doğrulanıyor…",
  downloading: (pct) => `İndiriliyor · %${pct}`,
  titleReady: "Güncelleme indirildi",
  titleAvailable: "Yeni sürüm var",
  current: (version) => `BaoCut ${version} kullanıyorsunuz.`,
  noteOnQuit: "BaoCut uygulamasından çıkınca otomatik kurulur; şimdi yeniden başlatmanız gerekmez.",
  notesTitle: "Yenilikler",
  readyToast: (version) => `BaoCut ${version} indirildi; çıkınca otomatik kurulur`,
  availableToast: (version) => `BaoCut ${version} güncellemeye hazır`,
  view: "Gör",
  restartTitle: "Şimdi yeniden başlatıp güncellensin mi?",
  restartBody: (n) => `${n} arka plan görevi çalışıyor. Yeniden başlatma görevleri keser; ardından yeniden başlatabilirsiniz.`,
  remoteTitle: "Bunlar uzaktan çalışıyor. Durdurduktan sonra sağlayıcı tarafında çalışmaya veya ücret oluşturmaya devam edebilirler:",
  stopAndInstall: "Şimdi durdur ve yükle",
  waitAndInstall: "Görevler bitince yükle",
  autoRow: {
    label: "Güncellemeleri otomatik denetle ve indir",
    desc: "Başlangıçta ve ardından her 6 saatte denetler. İndirilen güncellemeler sonraki çıkışta kurulur; hemen güncellemek için yeniden başlatabilirsiniz. BaoCut kendiliğinden yeniden başlamaz.",
  },
};
