import { pluralForm } from '@baocut/protocol';
import type { AppUpdateMessages } from './app-update.ts';

export const pl: AppUpdateMessages = {
  justNow: "Właśnie teraz",
  minutesAgo: (n: number) => pluralForm('pl', n, { one: `${n} minutę temu`, few: `${n} minuty temu`, many: `${n} minut temu`, other: `${n} minuty temu` }),
  hoursAgo: (n: number) => pluralForm('pl', n, { one: `${n} godzinę temu`, few: `${n} godziny temu`, many: `${n} godzin temu`, other: `${n} godziny temu` }),
  daysAgo: (n: number) => pluralForm('pl', n, { one: `${n} dzień temu`, few: `${n} dni temu`, many: `${n} dni temu`, other: `${n} dnia temu` }),
  failure: {
    check: "Brak dostępu do serwera aktualizacji. Sprawdź sieć i spróbuj ponownie.",
    download: "Pobieranie nie zostało ukończone. Sprawdź sieć i spróbuj ponownie.",
    verify: "Pobrany plik nie przeszedł weryfikacji i został usunięty.",
    signature: "Podpis nowej wersji nie odpowiada aplikacji, nie zainstalowano. Zainstaluj ręcznie ze strony pobierania.",
    install: "Instalacja nie została ukończona. Zainstaluj ręcznie ze strony pobierania.",
    manual: "Ta kopia BaoCut nie może zastąpić się sama. Pobrany plik i strona pobierania są otwarte; zainstaluj ręcznie.",
  },
  version: (version: string, build: number) => `${version} (Build ${build})`,
  appStore: "Wersje App Store są aktualizowane przez App Store",
  devBuild: "Wersje deweloperskie nie sprawdzają aktualizacji",
  checking: "Sprawdzanie…",
  upToDate: "Masz najnowszą wersję",
  checkForUpdates: "Sprawdź aktualizacje",
  available: (version: string) => `Nowa wersja ${version} dostępna`,
  needsMacOS: (version: string) => `Wymaga macOS ${version}`,
  downloadAndInstall: "Pobierz i zainstaluj",
  verifyingVersion: (version: string) => `Weryfikowanie ${version}…`,
  downloadingVersion: (version: string, pct: number) => `Pobieranie ${version} · ${pct}%`,
  cancel: "Anuluj",
  readyWaiting: (version: string) => `${version} pobrana; zostanie zainstalowana po ukończeniu zadań w tle`,
  restartAndUpdate: "Uruchom ponownie i zaktualizuj",
  stopWaiting: "Nie czekaj",
  readyOnQuit: (version: string) => `${version} pobrana; zainstaluje się automatycznie po wyjściu z BaoCut`,
  installing: "Instaluję…",
  retry: "Spróbuj ponownie",
  downloadPage: "Przejdź do strony pobierania",
  lastCheck: (when: string) => `Ostatnie sprawdzenie: ${when}`,
  waitingRunning: (n: number) => pluralForm('pl', n, { one: `Jeszcze ${n} zadanie w tle trwa; aktualizacja zainstaluje się automatycznie po ukończeniu.`, few: `Jeszcze ${n} zadania w tle trwają; aktualizacja zainstaluje się automatycznie po ukończeniu.`, many: `Jeszcze ${n} zadań w tle trwa; aktualizacja zainstaluje się automatycznie po ukończeniu.`, other: `Jeszcze ${n} zadania w tle trwa; aktualizacja zainstaluje się automatycznie po ukończeniu.` }),
  waitingDone: "Zadania w tle ukończone. Instalowanie…",
  tipAvailable: (version: string) => `Nowa wersja · BaoCut ${version}`,
  tipVerifying: "Weryfikowanie aktualizacji…",
  tipDownloading: (pct: number) => `Pobieranie aktualizacji · ${pct}%`,
  tipReady: "Aktualizacja pobrana · Instalacja przy wyjściu",
  tipError: "Aktualizacja nie powiodła się · Kliknij, aby zobaczyć",
  later: "Później",
  verifying: "Weryfikowanie…",
  downloading: (pct: number) => `Pobieranie · ${pct}%`,
  titleReady: "Pobrano aktualizację",
  titleAvailable: "Dostępna nowa wersja",
  current: (version: string) => `Używasz BaoCut ${version}.`,
  noteOnQuit: "Zainstaluje się automatycznie po wyjściu z BaoCut; nie trzeba teraz restartować.",
  notesTitle: "Co nowego",
  readyToast: (version: string) => `BaoCut ${version} pobrany; zainstaluje się automatycznie przy wyjściu`,
  availableToast: (version: string) => `BaoCut ${version} gotowy do aktualizacji`,
  view: "Pokaż",
  restartTitle: "Uruchomić ponownie i zaktualizować teraz?",
  restartBody: (n: number) => pluralForm('pl', n, { one: `Trwa ${n} zadanie w tle. Restart je przerwie; potem możesz uruchomić ponownie.`, few: `Trwają ${n} zadania w tle. Restart je przerwie; potem możesz uruchomić ponownie.`, many: `Trwa ${n} zadań w tle. Restart je przerwie; potem możesz uruchomić ponownie.`, other: `Trwa ${n} zadania w tle. Restart je przerwie; potem możesz uruchomić ponownie.` }),
  remoteTitle: "Te zadania działają zdalnie. Po zatrzymaniu mogą nadal działać lub naliczać opłaty u dostawcy:",
  stopAndInstall: "Zatrzymaj i zainstaluj teraz",
  waitAndInstall: "Zainstaluj po ukończeniu zadań",
  autoRow: {
    label: "Automatycznie sprawdzaj i pobieraj aktualizacje",
    desc: "Sprawdza przy starcie i co 6 godzin. Pobrane aktualizacje instalują się przy następnym wyjściu lub możesz od razu restartować. BaoCut nigdy nie restartuje się sam.",
  },
};
