import { pluralForm } from '@baocut/protocol';
import type { AppUpdateFailure, AppUpdateInfo, AppUpdateState } from '../host.ts';
import type { AppUpdateMessages } from './app-update.ts';

export const fr: AppUpdateMessages = {
  justNow: "Juste maintenant",
  minutesAgo: (n: number) => (pluralForm('fr', n, { one: `il y a ${n} minute`, other: `${n} minutes` })),
  hoursAgo: (n: number) => (pluralForm('fr', n, { one: `il y a ${n} heure`, other: `${n} heures` })),
  daysAgo: (n: number) => (pluralForm('fr', n, { one: `il y a ${n} jour`, other: `${n} jours` })),
  failure: {
    check: "Serveur de mise à jour inaccessible. Vérifiez le réseau et réessayez.",
    download: "Téléchargement inachevé. Vérifiez le réseau et réessayez.",
    verify: "Fichier téléchargé non vérifié et supprimé.",
    signature: "Signature différente de cette application ; installation refusée. Installez manuellement depuis la page de téléchargement.",
    install: "Installation inachevée. Installez manuellement depuis la page de téléchargement.",
    manual: "Cette copie ne peut pas se remplacer. Fichier et page de téléchargement ouverts ; installez manuellement.",
  } as Record<AppUpdateFailure, string>,
  version: (version: string, build: number) => `${version} (Build ${build})`,
  appStore: "Versions App Store mises à jour par l’App Store",
  devBuild: "Versions de développement sans recherche de mises à jour",
  checking: "Vérification…",
  upToDate: "Vous êtes à jour",
  checkForUpdates: "Rechercher des mises à jour",
  available: (version: string) => `Nouvelle version ${version} disponibles`,
  needsMacOS: (version: string) => `Nécessite macOS ${version}`,
  downloadAndInstall: "Télécharger et installer",
  verifyingVersion: (version: string) => `Vérification de ${version}…`,
  downloadingVersion: (version: string, pct: number) => `Téléchargement de ${version} · ${pct}%`,
  cancel: "Annuler",
  readyWaiting: (version: string) => `${version} téléchargé ; installation après les tâches en arrière-plan`,
  restartAndUpdate: "Redémarrer et mettre à jour",
  stopWaiting: "Ne pas attendre",
  readyOnQuit: (version: string) => `${version} téléchargé ; installation automatique en quittant BaoCut`,
  installing: "Installation…",
  retry: "Réessayer",
  downloadPage: "Aller à la page de téléchargement",
  lastCheck: (when: string) => `Dernière vérification : ${when}`,
  waitingRunning: (n: number) =>
    `${pluralForm('fr', n, { one: `${n} tâche en arrière-plan est`, other: `${n} tâches en arrière-plan sont` })} encore en cours ; mise à jour automatique quand ${pluralForm('fr', n, { one: "elle se termine", other: "elles se terminent toutes" })}.`,
  waitingDone: "Tâches terminées. Installation…",
  tipAvailable: (version: string) => `Nouvelle version · BaoCut ${version}`,
  tipVerifying: "Vérification de la mise à jour…",
  tipDownloading: (pct: number) => `Téléchargement de mise à jour · ${pct}%`,
  tipReady: "Mise à jour téléchargée · installation à la fermeture",
  tipError: "Mise à jour en échec · cliquez pour voir",
  later: "Plus tard",
  verifying: "Vérification…",
  downloading: (pct: number) => `Téléchargement · ${pct}%`,
  titleReady: "Mise à jour téléchargée",
  titleAvailable: "Nouvelle version disponible",
  current: (version: string) => `Vous utilisez BaoCut ${version}.`,
  noteOnQuit: "Installation automatique en quittant BaoCut ; inutile de redémarrer maintenant.",
  notesTitle: "Nouveautés",
  readyToast: (version: string) => `BaoCut ${version} téléchargé ; installation automatique à la fermeture`,
  availableToast: (version: string) => `BaoCut ${version} est prêt pour la mise à jour`,
  view: "Voir",
  restartTitle: "Redémarrer et mettre à jour maintenant ?",
  restartBody: (n: number) =>
    `${pluralForm('fr', n, { one: `${n} tâche en arrière-plan est`, other: `${n} tâches en arrière-plan sont` })} en cours. Redémarrer interrompra ${pluralForm('fr', n, { one: "elle", other: "elles" })} ; vous pourrez relancer ${pluralForm('fr', n, { one: "elle", other: "elles" })} ensuite.`,
  remoteTitle: "Exécutions distantes : après arrêt, traitement et facturation peuvent continuer côté fournisseur :",
  stopAndInstall: "Arrêter et installer maintenant",
  waitAndInstall: "Installer après les tâches",
  autoRow: {
    label: "Rechercher et télécharger les mises à jour automatiquement",
    desc: "Vérification au lancement puis toutes les 6 heures. Téléchargements installés à la fermeture, ou redémarrage manuel immédiat. BaoCut ne redémarre jamais seul.",
  },
};
