import type { AppUpdateMessages } from './app-update.ts';

export const ja: AppUpdateMessages = {
  justNow: 'たった今',
  minutesAgo: (n: number) => `${n} 分前`,
  hoursAgo: (n: number) => `${n} 時間前`,
  daysAgo: (n: number) => `${n} 日前`,
  failure: {
    check: '更新サーバに接続できません。ネットワークを確認して、もう一度お試しください。',
    download: 'ダウンロードが完了しませんでした。ネットワークを確認して、もう一度お試しください。',
    verify: 'ダウンロードしたファイルが検証に通らなかったため、削除しました。',
    signature: '新しいバージョンの署名がこのアプリと一致しないため、インストールしませんでした。ダウンロードページから手動でインストールしてください。',
    install: 'インストールを完了できませんでした。ダウンロードページから手動でインストールしてください。',
    manual: 'この BaoCut は自身を置き換えられません。ダウンロードしたファイルとダウンロードページを開いたので、手動でインストールしてください。',
  },
  version: (version: string, build: number) => `${version}（Build ${build}）`,
  appStore: 'App Store 版は App Store が更新します',
  devBuild: '開発ビルドは更新を確認しません',
  checking: '確認中…',
  upToDate: '最新の状態です',
  checkForUpdates: '更新を確認',
  available: (version: string) => `新しいバージョン ${version} があります`,
  needsMacOS: (version: string) => `macOS ${version} が必要です`,
  downloadAndInstall: 'ダウンロードしてインストール',
  verifyingVersion: (version: string) => `${version} を検証中…`,
  downloadingVersion: (version: string, pct: number) => `${version} をダウンロード中 · ${pct}%`,
  cancel: 'キャンセル',
  readyWaiting: (version: string) => `${version} をダウンロードしました。バックグラウンドタスクの終了後にインストールします`,
  restartAndUpdate: '再起動して更新',
  stopWaiting: '待たない',
  readyOnQuit: (version: string) => `${version} をダウンロードしました。BaoCut の終了時に自動でインストールします`,
  installing: 'インストール中…',
  retry: '再試行',
  downloadPage: 'ダウンロードページへ',
  lastCheck: (when: string) => `最終確認：${when}`,
  waitingRunning: (n: number) => `バックグラウンドタスクが ${n} 件実行中です。すべて終わると更新が自動でインストールされます。`,
  waitingDone: 'バックグラウンドタスクが終了しました。インストール中…',
  tipAvailable: (version: string) => `新しいバージョン · BaoCut ${version}`,
  tipVerifying: '更新を検証中…',
  tipDownloading: (pct: number) => `更新をダウンロード中 · ${pct}%`,
  tipReady: '更新をダウンロードしました · 終了時にインストール',
  tipError: '更新に失敗しました · クリックして表示',
  later: '後で',
  verifying: '検証中…',
  downloading: (pct: number) => `ダウンロード中 · ${pct}%`,
  titleReady: '更新をダウンロードしました',
  titleAvailable: '新しいバージョンがあります',
  current: (version: string) => `現在お使いのバージョンは BaoCut ${version} です。`,
  noteOnQuit: 'BaoCut の終了時に自動でインストールされるので、今すぐ再起動する必要はありません。',
  notesTitle: '新機能',
  readyToast: (version: string) => `BaoCut ${version} をダウンロードしました。終了時に自動でインストールします`,
  availableToast: (version: string) => `BaoCut ${version} に更新できます`,
  view: '表示',
  restartTitle: '今すぐ再起動して更新しますか？',
  restartBody: (n: number) => `バックグラウンドタスクが ${n} 件実行中です。再起動すると中断されますが、後でもう一度開始できます。`,
  remoteTitle: '以下はリモートで実行されています。停止しても、プロバイダ側では実行や課金が続く場合があります：',
  stopAndInstall: '今すぐ停止してインストール',
  waitAndInstall: 'タスクの終了後にインストール',
  autoRow: {
    label: '更新を自動で確認してダウンロード',
    desc: '起動時と、その後 6 時間ごとに確認します。ダウンロードした更新は次回の終了時にインストールされます。すぐに再起動して更新することもできます。BaoCut が勝手に再起動することはありません。',
  },
};
