import type { AppUpdateMessages } from './app-update.ts';

export const ko: AppUpdateMessages = {
  justNow: '방금 전',
  minutesAgo: (n: number) => `${n}분 전`,
  hoursAgo: (n: number) => `${n}시간 전`,
  daysAgo: (n: number) => `${n}일 전`,
  failure: {
    check: '업데이트 서버에 연결할 수 없습니다. 네트워크를 확인한 뒤 다시 시도하세요.',
    download: '다운로드가 끝나지 않았습니다. 네트워크를 확인한 뒤 다시 시도하세요.',
    verify: '다운로드한 파일이 검증을 통과하지 못해 삭제했습니다.',
    signature: '새 버전의 서명이 현재 앱과 일치하지 않아 설치하지 않았습니다. 다운로드 페이지에서 직접 설치하세요.',
    install: '설치를 완료하지 못했습니다. 다운로드 페이지에서 직접 설치하세요.',
    manual: '이 BaoCut 사본은 스스로 교체할 수 없습니다. 다운로드한 파일과 다운로드 페이지를 열었으니 직접 설치하세요.',
  },
  version: (version: string, build: number) => `${version}(Build ${build})`,
  appStore: 'App Store 버전은 App Store에서 업데이트합니다',
  devBuild: '개발 빌드는 업데이트를 확인하지 않습니다',
  checking: '확인 중…',
  upToDate: '최신 버전입니다',
  checkForUpdates: '업데이트 확인',
  available: (version: string) => `새 버전 ${version} 사용 가능`,
  needsMacOS: (version: string) => `macOS ${version} 필요`,
  downloadAndInstall: '다운로드 및 설치',
  verifyingVersion: (version: string) => `${version} 검증 중…`,
  downloadingVersion: (version: string, pct: number) => `${version} 다운로드 중 · ${pct}%`,
  cancel: '취소',
  readyWaiting: (version: string) => `${version} 버전을 다운로드했습니다. 백그라운드 작업이 끝나면 설치됩니다`,
  restartAndUpdate: '다시 시작하고 업데이트',
  stopWaiting: '기다리지 않기',
  readyOnQuit: (version: string) => `${version} 버전을 다운로드했습니다. BaoCut을 종료하면 자동으로 설치됩니다`,
  installing: '설치 중…',
  retry: '다시 시도',
  downloadPage: '다운로드 페이지로 이동',
  lastCheck: (when: string) => `마지막 확인: ${when}`,
  waitingRunning: (n: number) => `백그라운드 작업 ${n}개가 아직 실행 중입니다. 모두 끝나면 업데이트가 자동으로 설치됩니다.`,
  waitingDone: '백그라운드 작업이 끝났습니다. 설치 중…',
  tipAvailable: (version: string) => `새 버전 · BaoCut ${version}`,
  tipVerifying: '업데이트 검증 중…',
  tipDownloading: (pct: number) => `업데이트 다운로드 중 · ${pct}%`,
  tipReady: '업데이트 다운로드 완료 · 종료 시 설치',
  tipError: '업데이트 실패 · 클릭해서 보기',
  later: '나중에',
  verifying: '검증 중…',
  downloading: (pct: number) => `다운로드 중 · ${pct}%`,
  titleReady: '업데이트 다운로드 완료',
  titleAvailable: '새 버전이 있습니다',
  current: (version: string) => `현재 BaoCut ${version} 버전을 사용 중입니다.`,
  noteOnQuit: 'BaoCut을 종료하면 자동으로 설치되므로 지금 다시 시작하지 않아도 됩니다.',
  notesTitle: '업데이트 내용',
  readyToast: (version: string) => `BaoCut ${version} 버전을 다운로드했습니다. 종료하면 자동으로 설치됩니다`,
  availableToast: (version: string) => `BaoCut ${version} 버전으로 업데이트할 수 있습니다`,
  view: '보기',
  restartTitle: '지금 다시 시작하고 업데이트할까요?',
  restartBody: (n: number) => `백그라운드 작업 ${n}개가 실행 중입니다. 다시 시작하면 작업이 중단되며, 이후에 작업을 다시 실행할 수 있습니다.`,
  remoteTitle: '다음 항목은 원격에서 실행됩니다. 중지한 뒤에도 공급자 쪽에서 계속 실행되거나 요금이 청구될 수 있습니다:',
  stopAndInstall: '지금 중지하고 설치',
  waitAndInstall: '작업이 끝나면 설치',
  autoRow: {
    label: '업데이트 자동 확인 및 다운로드',
    desc: '시작할 때와 그 후 6시간마다 확인합니다. 다운로드한 업데이트는 다음에 종료할 때 설치되며, 바로 다시 시작해 업데이트할 수도 있습니다. BaoCut은 스스로 다시 시작하지 않습니다.',
  },
};
