import type { AppUpdateMessages } from './app-update.ts';
import { pluralForm } from '@baocut/protocol';

export const it: AppUpdateMessages = {
  justNow: 'Ora', minutesAgo: (n: number) => pluralForm('it', n, { one: `${n} minuto fa`, other: `${n} minuti fa` }), hoursAgo: (n: number) => pluralForm('it', n, { one: `${n} ora fa`, other: `${n} ore fa` }), daysAgo: (n: number) => pluralForm('it', n, { one: `${n} giorno fa`, other: `${n} giorni fa` }),
  failure: { check: 'Impossibile raggiungere il server degli aggiornamenti. Controlla la rete e riprova.', download: 'Il download non è terminato. Controlla la rete e riprova.', verify: 'Il file scaricato non ha superato la verifica ed è stato eliminato.', signature: 'La firma della nuova versione non corrisponde a questa app, quindi non è stata installata. Installala manualmente dalla pagina di download.', install: 'Impossibile completare l’installazione. Installala manualmente dalla pagina di download.', manual: 'Questa copia di BaoCut non può sostituire sé stessa. Il file scaricato e la pagina di download sono aperti; installala manualmente.' },
  version: (version: string, build: number) => `${version} (build ${build})`, appStore: 'Le versioni App Store vengono aggiornate dall’App Store', devBuild: 'Le build di sviluppo non verificano gli aggiornamenti', checking: 'Verifica in corso…', upToDate: 'La versione è aggiornata', checkForUpdates: 'Verifica aggiornamenti', available: (version: string) => `Nuova versione ${version} disponibile`, needsMacOS: (version: string) => `Richiede macOS ${version}`, downloadAndInstall: 'Scarica e installa',
  verifyingVersion: (version: string) => `Verifica di ${version}…`, downloadingVersion: (version: string, pct: number) => `Download di ${version} · ${pct}%`, cancel: 'Annulla', readyWaiting: (version: string) => `${version} scaricata; verrà installata al termine delle attività in background`, restartAndUpdate: 'Riavvia e aggiorna', stopWaiting: 'Non attendere', readyOnQuit: (version: string) => `${version} scaricata; verrà installata automaticamente quando esci da BaoCut`, installing: 'Installazione in corso…', retry: 'Riprova', downloadPage: 'Vai alla pagina di download', lastCheck: (when: string) => `Ultima verifica: ${when}`,
  waitingRunning: (n: number) => pluralForm('it', n, { one: `${n} attività in background è ancora in corso; l’aggiornamento si installerà automaticamente al suo termine.`, other: `${n} attività in background sono ancora in corso; l’aggiornamento si installerà automaticamente quando termineranno tutte.` }), waitingDone: 'Le attività in background sono terminate. Installazione in corso…',
  tipAvailable: (version: string) => `Nuova versione · BaoCut ${version}`, tipVerifying: 'Verifica dell’aggiornamento…', tipDownloading: (pct: number) => `Download dell’aggiornamento · ${pct}%`, tipReady: 'Aggiornamento scaricato · Si installa all’uscita', tipError: 'Aggiornamento non riuscito · Fai clic per visualizzare', later: 'Più tardi', verifying: 'Verifica in corso…', downloading: (pct: number) => `Download · ${pct}%`, titleReady: 'Aggiornamento scaricato', titleAvailable: 'Nuova versione disponibile',
  current: (version: string) => `Stai usando BaoCut ${version}.`, noteOnQuit: 'Verrà installato automaticamente quando esci da BaoCut; non serve riavviare ora.', notesTitle: 'Novità', readyToast: (version: string) => `BaoCut ${version} scaricato; verrà installato automaticamente all’uscita`, availableToast: (version: string) => `BaoCut ${version} è pronto per l’aggiornamento`, view: 'Visualizza', restartTitle: 'Riavviare e aggiornare ora?',
  restartBody: (n: number) => pluralForm('it', n, { one: `${n} attività in background è in corso. Il riavvio la interromperà; potrai riavviarla in seguito.`, other: `${n} attività in background sono in corso. Il riavvio le interromperà; potrai riavviarle in seguito.` }),
  remoteTitle: 'Queste vengono eseguite da remoto. Dopo l’interruzione potrebbero continuare o generare addebiti dal lato del provider:', stopAndInstall: 'Interrompi ora e installa', waitAndInstall: 'Installa al termine delle attività',
  autoRow: { label: 'Verifica e scarica automaticamente gli aggiornamenti', desc: 'Verifica all’avvio e ogni 6 ore. Gli aggiornamenti scaricati si installano alla prossima uscita; puoi anche riavviare per aggiornare subito. BaoCut non si riavvia mai da solo.' },
};
