import type { DubSetupMessages } from './dub-setup.ts';

export const ru: DubSetupMessages = {
  useExisting: (name: string) => `Использовать существующий перевод · ${name}`,
  translateFirst: (language: string) => `${language} · Сначала перевести`,
  sameAsSource: "Тот же язык, что у оригинала",
  missingLibraryVoice: (id: string) => `Голос библиотеки (${id}, больше нет в библиотеке)`,
  voiceRemoved: "Этого голоса больше нет в библиотеке",
  noConsent: "Нет заявления о согласии говорящего, поэтому запись не будет отправлена поставщику",
  notCloned: (provider: string) => `Не клонировано у поставщика ${provider} пока`,
  cloneExpired: (provider: string) => `Клон у поставщика ${provider} просрочен; клонируйте снова`,
  modelDefaultNamed: (voice: string) => `По умолчанию модели · ${voice}`,
  modelDefault: "По умолчанию модели",
  noDefaultVoice: "У этой модели нет голоса по умолчанию",
  needsVoice: "Для этой модели нужно указать голос",
  presetVoice: "Готовый голос",
  myVoiceProblem: (problem: string) => `Мои голоса · ${problem}`,
  myVoice: "Мои голоса",
  customVoice: "Введите ID голоса…",
  customVoiceDesc: "Голос в вашем аккаунте поставщика",
  purpose: (language: string, videoName: string | null) => `Озвучка: озвучить ${videoName ? `«${videoName}»` : "это видео"} на ${language}`,
  kindList: (kinds: readonly string[]) => kinds.join(", "),
  transcriptNote: " (перевод для синтеза; при предварительном переводе также исходный текст)",
  factWhat: "Отправляемые данные",
  factTo: "Получатель",
  factScope: "Область",
  factPurpose: "Назначение",
  factBudget: "Бюджет",
  factRevoke: "Отзыв",
  scopeVideoNamed: (name: string) => `Только видео «${name}»`,
  scopeThisVideo: "Только это видео",
  budget: "Учёт по вызовам, стоимость неизвестна, число вызовов не ограничено; поставщик взимает плату за использование как обычно",
  revoke: "Отозвать можно в любой момент в Настройки › Конфиденциальность › Разрешения на передачу данных; уже отправленные данные вернуть нельзя",
};
