import type { DubSetupMessages } from './dub-setup.ts';

export const pl: DubSetupMessages = {
  useExisting: (name: string) => `Użyj istniejącego tłumaczenia · ${name}`,
  translateFirst: (language: string) => `${language} · Najpierw przetłumacz`,
  sameAsSource: "Ten sam język co oryginał",
  missingLibraryVoice: (id: string) => `Głos z biblioteki (${id}, nie ma już w bibliotece)`,
  voiceRemoved: "Tego głosu nie ma już w bibliotece",
  noConsent: "Brak oświadczenia zgody mówcy, więc nagranie nie zostanie przesłane dostawcy",
  notCloned: (provider: string) => `Nie sklonowano u dostawcy ${provider} jeszcze`,
  cloneExpired: (provider: string) => `Klon u dostawcy ${provider} wygasł; sklonuj ponownie`,
  modelDefaultNamed: (voice: string) => `Domyślny modelu · ${voice}`,
  modelDefault: "Domyślny modelu",
  noDefaultVoice: "Ten model nie ma domyślnego głosu",
  needsVoice: "Ten model wymaga podania głosu",
  presetVoice: "Gotowy głos",
  myVoiceProblem: (problem: string) => `Moje głosy · ${problem}`,
  myVoice: "Moje głosy",
  customVoice: "Wpisz ID głosu…",
  customVoiceDesc: "Głos na Twoim koncie dostawcy",
  purpose: (language: string, videoName: string | null) => `Dubbing: utwórz dubbing ${videoName ? `„${videoName}”` : "tego wideo"} na ${language}`,
  kindList: (kinds: readonly string[]) => kinds.join(", "),
  transcriptNote: " (tłumaczenie do syntezy; przy wcześniejszym tłumaczeniu także tekst oryginalny)",
  factWhat: "Wysyłane dane",
  factTo: "Odbiorca",
  factScope: "Zakres",
  factPurpose: "Cel",
  factBudget: "Budżet",
  factRevoke: "Cofanie",
  scopeVideoNamed: (name: string) => `Tylko wideo „${name}”`,
  scopeThisVideo: "Tylko to wideo",
  budget: "Liczone na wywołanie, koszt nieznany, wywołania bez limitu; dostawca nalicza opłaty za użycie jak zwykle",
  revoke: "Cofnij w dowolnym momencie w Ustawienia › Prywatność › Uprawnienia do udostępniania danych; wysłanych danych nie można cofnąć",
};
