import type { DubSetupMessages } from './dub-setup.ts';

export const ko: DubSetupMessages = {
  useExisting: (name: string) => `기존 번역 사용 · ${name}`,
  translateFirst: (language: string) => `${language} · 먼저 번역`,
  sameAsSource: '원문과 같은 언어',
  missingLibraryVoice: (id: string) => `라이브러리 목소리(${id}, 더 이상 라이브러리에 없음)`,
  voiceRemoved: '이 목소리는 더 이상 라이브러리에 없습니다',
  noConsent: '화자의 동의 문구가 없어 공급자에게 업로드하지 않습니다',
  notCloned: (provider: string) => `아직 ${provider}에서 복제하지 않았습니다`,
  cloneExpired: (provider: string) => `${provider}의 복제가 만료되었습니다 · 다시 복제하세요`,
  modelDefaultNamed: (voice: string) => `모델 기본값 · ${voice}`,
  modelDefault: '모델 기본값',
  noDefaultVoice: '이 모델에는 기본 목소리가 없습니다',
  needsVoice: '이 모델은 목소리를 지정해야 합니다',
  presetVoice: '프리셋 목소리',
  myVoiceProblem: (problem: string) => `내 목소리 · ${problem}`,
  myVoice: '내 목소리',
  customVoice: '목소리 ID 입력…',
  customVoiceDesc: '공급자 계정에 있는 목소리',
  purpose: (language: string, videoName: string | null) =>
    `더빙: ${videoName ? `“${videoName}” 영상` : '이 영상'}을 ${language}(으)로 더빙`,
  kindList: (kinds: readonly string[]) => kinds.join(', '),
  transcriptNote: '(합성할 번역문, 먼저 번역하는 경우에는 원문도 포함)',
  factWhat: '보내는 데이터',
  factTo: '받는 곳',
  factScope: '범위',
  factPurpose: '용도',
  factBudget: '예산',
  factRevoke: '철회',
  scopeVideoNamed: (name: string) => `“${name}” 영상만`,
  scopeThisVideo: '이 영상만',
  budget: '호출 단위로 계산 · 비용 알 수 없음 · 호출 횟수 무제한 · 공급자는 평소처럼 사용량에 따라 요금을 청구합니다',
  revoke: '설정 › 개인 정보 보호 및 권한 › 데이터 공유 허가에서 언제든지 철회할 수 있습니다 · 이미 보낸 데이터는 되돌릴 수 없습니다',
};
