import type { DubSetupMessages } from './dub-setup.ts';

export const de: DubSetupMessages = {
  useExisting: (name: string) => `Vorhandene Übersetzung verwenden · ${name}`,
  translateFirst: (language: string) => `${language} · zuerst übersetzen`,
  sameAsSource: "Gleiche Sprache wie das Original",
  missingLibraryVoice: (id: string) => `Bibliotheksstimme (${id}, nicht mehr in der Bibliothek)`,
  voiceRemoved: "Diese Stimme ist nicht mehr in der Bibliothek",
  noConsent: "Keine Einwilligungserklärung des Sprechers; wird nicht an den Anbieter hochgeladen",
  notCloned: (provider: string) => `Noch nicht geklont bei ${provider} noch`,
  cloneExpired: (provider: string) => `Der Klon bei ${provider} ist abgelaufen; erneut klonen`,
  modelDefaultNamed: (voice: string) => `Modellstandard · ${voice}`,
  modelDefault: "Modellstandard",
  noDefaultVoice: "Dieses Modell hat keine Standardstimme",
  needsVoice: "Dieses Modell benötigt eine Stimmangabe",
  presetVoice: "Stimmvorlage",
  myVoiceProblem: (problem: string) => `Meine Stimmen · ${problem}`,
  myVoice: "Meine Stimmen",
  customVoice: "Stimmen-ID eingeben…",
  customVoiceDesc: "Eine Stimme in Ihrem Anbieterkonto",
  purpose: (language: string, videoName: string | null) =>
    `Vertonung: vertonen mit ${videoName ? `„${videoName}“` : "dieses Video"} nach ${language}`,
  kindList: (kinds: readonly string[]) => kinds.join(", "),
  transcriptNote: " (zu synthetisierende Übersetzung; bei vorheriger Übersetzung auch Originaltext)",
  factWhat: "Gesendete Daten",
  factTo: "Gesendet an",
  factScope: "Bereich",
  factPurpose: "Zweck",
  factBudget: "Budget",
  factRevoke: "Wird widerrufen",
  scopeVideoNamed: (name: string) => `Nur das Video „${name}“`,
  scopeThisVideo: "Nur dieses Video",
  budget: "Pro Aufruf gezählt; Kosten unbekannt, unbegrenzte Aufrufe. Anbieter berechnet Nutzung wie üblich",
  revoke: "Jederzeit unter Einstellungen › Datenschutz und Berechtigungen › Berechtigungen zur Datenweitergabe widerrufen; gesendete Daten sind nicht zurücknehmbar",
};
