import type { ElementCatalogMessages } from './element-catalog.ts';

export const ko: ElementCatalogMessages = {
  stickers: {
    badge_check: '체크 배지',
    badge_cross: 'X 배지',
    star_burst: '스타버스트',
    speech_bubble: '말풍선',
    heart: '하트',
    bolt: '번개',
    pin: '압정',
    sparkle: '반짝임',
    arrow_curved: '곡선 화살표',
    crown: '왕관',
  },
  shapes: {
    rect: '직사각형',
    ellipse: '타원',
    triangle: '삼각형',
    rombus: '마름모',
    pentagon: '오각형',
    hex: '육각형',
    octagon: '팔각형',
    squig: '물결 테두리 원',
    squig2: '블록 화살표',
    tick: '체크 표시',
    tick2: 'X 표시',
    chevron: '셰브런',
    chevron2: '지그재그 띠',
    cross2: '둥근 더하기',
    cross: '더하기',
    love2: '둥근 하트',
    love: '하트',
    diamond: '보석',
    star: '오각별',
    sharp: '십각별',
    star2: '십이각별',
    sharp2: '말풍선',
  },
  progress: {
    normal: '각진 막대',
    rounded: '둥근 막대',
    circle: '링',
    donut: '도넛',
    border: '테두리',
    reverse_border: '역방향 테두리',
    rainbow_border: '무지개 테두리',
    reverse_rainbow_border: '역방향 무지개 테두리',
    strobe_border: '스트로브 테두리',
    reverse_strobe_border: '역방향 스트로브 테두리',
    snake: '스네이크',
    snake_spin: '회전 스네이크',
    snake_rainbow: '무지개 스네이크',
    snake_spin_rainbow: '회전 무지개 스네이크',
  },
  waves: {
    bars: '막대',
    bars_rounded: '둥근 막대',
    bars_bottom: '아래 정렬 막대',
    ring_bars: '원형 막대',
    oscilloscope: '오실로스코프',
    ring_wave: '원형 파동',
    spectrum_area: '스펙트럼 영역',
    dots: '도트 매트릭스',
    pulse_rings: '펄스 링',
    ribbons: '리본',
  },
  colors: {
    bar: '막대',
    track: '바탕',
    background: '배경',
    color1: '색 1',
    color2: '색 2',
    foreground: '전경',
    bars: '막대',
    waveform: '파형',
    fill: '채우기',
    line: '선',
    dots: '점',
    peak: '피크',
    core: '코어',
    rings: '링',
    ribbonA: '리본 A',
    ribbonB: '리본 B',
  },
  roundedRect: '둥근 직사각형',
  countdown: '카운트다운',
  countup: '카운트업',
  progressName: (label: string) => `진행 표시줄 · ${label}`,
  waveName: (label: string) => `파형 · ${label}`,
  confettiName: (label: string) => `색종이 · ${label}`,
  shapeName: (name: string) => `도형 · ${name}`,
  stickerName: (label: string) => `스티커 · ${label}`,
  sections: {
    sticker: { title: '스티커', note: '기본 제공 10개 + 브랜드 라이브러리' },
    dynamic: { title: '애니메이션 스티커', note: '색종이 10개 + 브랜드 라이브러리의 Lottie' },
    shape: { title: '도형', note: '타일 23개 · 5색 순환' },
    visualizer: { title: '비주얼라이저', note: '진행 표시줄 14개 + 타이머 2개 + 파형 10개' },
  },
};
