import type { ElementCatalogMessages } from './element-catalog.ts';

export const pl: ElementCatalogMessages = {
  stickers: {
    badge_check: "Znaczek zaznaczenia",
    badge_cross: "Znaczek krzyżyka",
    star_burst: "Rozbłysk gwiazdy",
    speech_bubble: "Dymek",
    heart: "Serce",
    bolt: "Błyskawica",
    pin: "Pinezka",
    sparkle: "Iskra",
    arrow_curved: "Zakrzywiona strzałka",
    crown: "Korona",
  },
  shapes: {
    rect: "Prostokąt",
    ellipse: "Elipsa",
    triangle: "Trójkąt",
    rombus: "Romb",
    pentagon: "Pięciokąt",
    hex: "Sześciokąt",
    octagon: "Ośmiokąt",
    squig: "Koło z falistym brzegiem",
    squig2: "Strzałka blokowa",
    tick: "Znacznik wyboru",
    tick2: "Krzyż",
    chevron: "Szewron",
    chevron2: "Zygzakowata wstęga",
    cross2: "Zaokrąglony plus",
    cross: "Plus",
    love2: "Zaokrąglone serce",
    love: "Serce",
    diamond: "Klejnot",
    star: "Gwiazda pięcioramienna",
    sharp: "Gwiazda dziesięcioramienna",
    star2: "Gwiazda dwunastoramienna",
    sharp2: "Dymek",
  },
  progress: {
    normal: "Prostokątny pasek",
    rounded: "Zaokrąglony pasek",
    circle: "Pierścień",
    donut: "Oponka",
    border: "Obramowanie",
    reverse_border: "Odwrotne obramowanie",
    rainbow_border: "Tęczowe obramowanie",
    reverse_rainbow_border: "Odwrotne tęczowe obramowanie",
    strobe_border: "Migające obramowanie",
    reverse_strobe_border: "Odwrotne migające obramowanie",
    snake: "Wąż",
    snake_spin: "Obracający się wąż",
    snake_rainbow: "Tęczowy wąż",
    snake_spin_rainbow: "Obracający się tęczowy wąż",
  },
  waves: {
    bars: "Słupki",
    bars_rounded: "Zaokrąglone paski",
    bars_bottom: "Paski wyrównane do dołu",
    ring_bars: "Paski pierścieniowe",
    oscilloscope: "Oscyloskop",
    ring_wave: "Fala pierścieniowa",
    spectrum_area: "Obszar widma",
    dots: "Matryca punktowa",
    pulse_rings: "Pulsujące pierścienie",
    ribbons: "Wstążki",
  },
  colors: {
    bar: "Pasek",
    track: "Ścieżka",
    background: "Tło",
    color1: "Kolor 1",
    color2: "Kolor 2",
    foreground: "Pierwszy plan",
    bars: "Słupki",
    waveform: "Przebieg fali",
    fill: "Wypełnienie",
    line: "Interlinia",
    dots: "Kropki",
    peak: "Szczyt",
    core: "Rdzeń",
    rings: "Pierścienie",
    ribbonA: "Wstążka A",
    ribbonB: "Wstążka B",
  },
  roundedRect: "Zaokrąglony prostokąt",
  countdown: "Odliczanie wstecz",
  countup: "Odliczanie w przód",
  progressName: (label: string) => `Pasek postępu · ${label}`,
  waveName: (label: string) => `Przebieg fali · ${label}`,
  confettiName: (label: string) => `Konfetti · ${label}`,
  shapeName: (name: string) => `Kształt · ${name}`,
  stickerName: (label: string) => `Naklejka · ${label}`,
  sections: {
    sticker: { title: "Naklejki", note: "10 wbudowanych + biblioteka marki" },
    dynamic: { title: "Animowane naklejki", note: "10 konfetti + Lottie z biblioteki marki" },
    shape: { title: "Kształty", note: "23 kafelki · cykl 5 kolorów" },
    visualizer: { title: "Wizualizatory", note: "14 pasków + 2 zegary + 10 przebiegów fali" },
  },
};
