import type { ElementCatalogMessages } from './element-catalog.ts';

export const zhHant: ElementCatalogMessages = {
  stickers: {
    badge_check: '打勾徽章',
    badge_cross: '叉號徽章',
    star_burst: '星芒',
    speech_bubble: '對話框',
    heart: '愛心',
    bolt: '閃電',
    pin: '圖釘',
    sparkle: '閃光',
    arrow_curved: '彎曲箭頭',
    crown: '皇冠',
  },
  shapes: {
    rect: '矩形',
    ellipse: '橢圓形',
    triangle: '三角形',
    rombus: '菱形',
    pentagon: '五邊形',
    hex: '六邊形',
    octagon: '八邊形',
    squig: '波浪邊圓形',
    squig2: '區塊箭頭',
    tick: '打勾',
    tick2: '叉號',
    chevron: 'V 形',
    chevron2: '鋸齒帶',
    cross2: '圓角加號',
    cross: '加號',
    love2: '圓角愛心',
    love: '愛心',
    diamond: '寶石',
    star: '五角星',
    sharp: '十角星',
    star2: '十二角星',
    sharp2: '對話框',
  },
  progress: {
    normal: '直角長條',
    rounded: '圓角長條',
    circle: '圓環',
    donut: '甜甜圈',
    border: '邊框',
    reverse_border: '反向邊框',
    rainbow_border: '彩虹邊框',
    reverse_rainbow_border: '反向彩虹邊框',
    strobe_border: '頻閃邊框',
    reverse_strobe_border: '反向頻閃邊框',
    snake: '遊走',
    snake_spin: '旋轉遊走',
    snake_rainbow: '彩虹遊走',
    snake_spin_rainbow: '旋轉彩虹遊走',
  },
  waves: {
    bars: '長條',
    bars_rounded: '圓角長條',
    bars_bottom: '底部對齊長條',
    ring_bars: '環形長條',
    oscilloscope: '示波器',
    ring_wave: '環形波',
    spectrum_area: '頻譜面積',
    dots: '點陣',
    pulse_rings: '脈衝環',
    ribbons: '緞帶',
  },
  colors: {
    bar: '長條',
    track: '底條',
    background: '背景',
    color1: '顏色 1',
    color2: '顏色 2',
    foreground: '前景',
    bars: '長條',
    waveform: '波形',
    fill: '填色',
    line: '線條',
    dots: '圓點',
    peak: '峰值',
    core: '核心',
    rings: '圓環',
    ribbonA: '緞帶 A',
    ribbonB: '緞帶 B',
  },
  roundedRect: '圓角矩形',
  countdown: '倒數計時',
  countup: '正數計時',
  progressName: (label: string) => `進度列 · ${label}`,
  waveName: (label: string) => `波形 · ${label}`,
  confettiName: (label: string) => `彩紙 · ${label}`,
  shapeName: (name: string) => `形狀 · ${name}`,
  stickerName: (label: string) => `貼紙 · ${label}`,
  sections: {
    sticker: { title: '貼紙', note: '內建 10 款 + 品牌庫' },
    dynamic: { title: '動態貼紙', note: '10 款彩紙 + 品牌庫中的 Lottie' },
    shape: { title: '形狀', note: '23 格 · 5 色循環' },
    visualizer: { title: '視覺化', note: '14 種進度 + 2 種計時 + 10 種波形' },
  },
};
