import type { ElementCatalogMessages } from './element-catalog.ts';

export const ja: ElementCatalogMessages = {
  stickers: {
    badge_check: 'チェックバッジ',
    badge_cross: 'バツ印バッジ',
    star_burst: 'スターバースト',
    speech_bubble: '吹き出し',
    heart: 'ハート',
    bolt: '稲妻',
    pin: '画鋲',
    sparkle: 'きらめき',
    arrow_curved: '曲がった矢印',
    crown: '王冠',
  },
  shapes: {
    rect: '長方形',
    ellipse: '楕円',
    triangle: '三角形',
    rombus: 'ひし形',
    pentagon: '五角形',
    hex: '六角形',
    octagon: '八角形',
    squig: '波縁の円',
    squig2: 'ブロック矢印',
    tick: 'チェックマーク',
    tick2: 'バツ印',
    chevron: 'シェブロン',
    chevron2: 'ジグザグ帯',
    cross2: '角丸のプラス',
    cross: 'プラス',
    love2: '丸みのあるハート',
    love: 'ハート',
    diamond: '宝石',
    star: '五芒星',
    sharp: '十芒星',
    star2: '十二芒星',
    sharp2: '吹き出し',
  },
  progress: {
    normal: '角型バー',
    rounded: '角丸バー',
    circle: 'リング',
    donut: 'ドーナツ',
    border: '枠線',
    reverse_border: '逆回りの枠線',
    rainbow_border: '虹色の枠線',
    reverse_rainbow_border: '逆回りの虹色の枠線',
    strobe_border: 'ストロボ枠線',
    reverse_strobe_border: '逆回りのストロボ枠線',
    snake: 'スネーク',
    snake_spin: '回転スネーク',
    snake_rainbow: '虹色スネーク',
    snake_spin_rainbow: '回転する虹色スネーク',
  },
  waves: {
    bars: 'バー',
    bars_rounded: '角丸バー',
    bars_bottom: '下揃えバー',
    ring_bars: 'リングバー',
    oscilloscope: 'オシロスコープ',
    ring_wave: 'リング波形',
    spectrum_area: 'スペクトラムエリア',
    dots: 'ドットマトリクス',
    pulse_rings: 'パルスリング',
    ribbons: 'リボン',
  },
  colors: {
    bar: 'バー',
    track: '下地',
    background: '背景',
    color1: 'カラー 1',
    color2: 'カラー 2',
    foreground: '前景',
    bars: 'バー',
    waveform: '波形',
    fill: '塗り',
    line: '線',
    dots: 'ドット',
    peak: 'ピーク',
    core: 'コア',
    rings: 'リング',
    ribbonA: 'リボン A',
    ribbonB: 'リボン B',
  },
  roundedRect: '角丸長方形',
  countdown: 'カウントダウン',
  countup: 'カウントアップ',
  progressName: (label: string) => `プログレスバー · ${label}`,
  waveName: (label: string) => `波形 · ${label}`,
  confettiName: (label: string) => `紙吹雪 · ${label}`,
  shapeName: (name: string) => `図形 · ${name}`,
  stickerName: (label: string) => `ステッカー · ${label}`,
  sections: {
    sticker: { title: 'ステッカー', note: '内蔵 10 種 + ブランドキット' },
    dynamic: { title: 'アニメーションステッカー', note: '紙吹雪 10 種 + ブランドキットの Lottie' },
    shape: { title: '図形', note: '23 種 · 5 色を循環' },
    visualizer: { title: 'ビジュアライザ', note: 'プログレス 14 + タイマー 2 + 波形 10' },
  },
};
