import type { ExportJobMessages } from './export-job.ts';

export const ja: ExportJobMessages = {
  tabVideo: '動画',
  tabAudio: '音声',
  tabSubtitles: '字幕',
  tabTranscript: '文字起こし',
  tabProject: 'プロジェクトファイル',
  export: '書き出し',
  queued: '書き出し待機中',
  exporting: '書き出し中…',
  exportingPct: (pct: number) => `書き出し中 · ${pct}%`,
  formats: { md: 'Markdown', txt: 'プレーンテキスト', xmeml: 'FCP7 XML' },
  titleVideo: (format: string) => `動画を書き出し · ${format}`,
  titleAudio: (format: string) => `音声を書き出し · ${format}`,
  titleSubtitles: (format: string) => `字幕を書き出し · ${format}`,
  titleTranscript: (format: string) => `文字起こしを書き出し · ${format}`,
  titlePortable: 'ポータブルパッケージを書き出し',
  titleProject: (format: string) => `プロジェクトファイルを書き出し · ${format}`,
  generating: {
    video: 'エンコード中',
    audio: 'ミックス中',
    subtitles: 'ファイルを書き込み中',
    transcript: 'ファイルを書き込み中',
    portable: 'パッケージ化中',
    project: 'プロジェクトファイルを書き込み中',
  },
  retrying: 'エラーのため自動で再試行中',
  saving: 'ファイルを保存中',
  framesOf: (done: string, total: string) => `${done} / ${total} フレームをレンダリング済み`,
  frames: (done: string) => `${done} フレームをレンダリング済み`,
  secondsOf: (done: string, total: string) => `${done} / ${total} を処理済み`,
  seconds: (done: string) => `${done} を処理済み`,
  outputsOf: (done: number, total: number) => `${done} / ${total} 個のファイルを書き込み済み`,
  outputs: (done: number) => `${done} 個のファイルを書き込み済み`,
  bytesOf: (done: string, total: string) => `${done} / ${total} をパッケージ化済み`,
  bytes: (done: string) => `${done} をパッケージ化済み`,
  mono: 'モノラル',
  stereo: 'ステレオ',
  entries: (n: number) => `${n} 件`,
  files: (n: number) => `ファイル ${n} 個`,
  assetRevisions: (n: number) => `素材のバージョン ${n} 個`,
  missing: (n: number) => `${n} 個が見つかりません`,
  clips: (n: number) => `クリップ ${n} 個`,
  omitted: (n: number) => `${n} 個の項目はプロジェクトファイルに書き込まれていません`,
  doneMany: (n: number, total: string) => `ファイル ${n} 個 · 合計 ${total}`,
  cancelledKept: (n: number) => `保存済みのファイル ${n} 個は残しました · 動画自体には影響ありません`,
  cancelledRemoved: '未完了のファイルは削除しました · 動画自体には影響ありません',
};
