import type { ExportRejectionMessages } from './export-rejection.ts';

export const ru: ExportRejectionMessages = {
  portableReason: {
    missing: "Файл не найден",
    changed: "Содержимое изменилось после добавления",
    unreadable: "Не удалось прочитать",
  },
  titles: {
    VIDEO_NOT_OPEN: "Видео не открыто",
    EXPORT_KIND_UNSUPPORTED: "Эта версия ещё не экспортирует этот вид содержимого",
    EXPORT_SOURCE_UNSUPPORTED: "Этот документ нельзя экспортировать таким способом",
    EXPORT_NOTHING_TO_EXPORT: "В диапазоне нечего экспортировать",
    EXPORT_SOURCE_NOT_FOUND: "Нет документа для экспорта",
    EXPORT_SOURCE_AMBIGUOUS: "Несколько документов доступны для экспорта",
    EXPORT_TOOL_MISSING: "На компьютере нет инструмента для экспорта",
    EXPORT_UNSUPPORTED_CONTENT: "Часть содержимого нельзя отрендерить для экспорта",
    ASSET_MISSING: "Часть материалов не читается",
    ASSET_CHANGED: "Часть материалов изменилась",
    ENTITY_NOT_FOUND: "Последовательность не существует",
    DUB_GROUP_NOT_FOUND: "Группа озвучки не найдена",
    EXPORT_PACKAGE_LOCAL_PATH: "Часть документов содержит пути на этом компьютере",
    EXPORT_PACKAGE_UNSUPPORTED: "Часть файлов нельзя включить в переносимый пакет",
    EXPORT_INSUFFICIENT_SPACE: "Недостаточно места на диске экспорта",
    EXPORT_DESTINATION_EXISTS: "Одноимённый файл уже есть",
    EXPORT_DESTINATION_UNWRITABLE: "Не удалось записать в место экспорта",
    EXPORT_RENDER_FAILED: "Не удалось отрендерить видео",
    EXPORT_VALIDATION_FAILED: "Экспортированный файл не прошёл проверку",
    EXPORT_PUBLISH_FAILED: "Не удалось сохранить файлы в место экспорта",
    EXPORT_PARTIALLY_PUBLISHED: "Сохранена только часть файлов",
    RESOURCE_ADMISSION_UNSATISFIABLE: "На компьютере недостаточно ресурсов для экспорта",
  },
  resources: {
    memory: "Память",
    gpuMemory: "Память GPU",
    cpuThreads: "Потоки CPU",
    scratchDisk: "Место для временных файлов",
  },
  problemSeparator: "; ",
  fileProblems: (file: string, problems: string) => `${file}: ${problems}`,
  notStarted: "Экспорт не начался",
  failed: "Экспорт не удался",
  missingTool: (tool: string) => `Отсутствует: ${tool}`,
  assetMissingHint: "Найдите файл или привяжите заново в «Материалы», затем экспортируйте снова.",
  assetChangedHint: "Привяжите материал заново или верните исходный файл, затем экспортируйте снова.",
  nothingHint: "Выберите другой диапазон или сначала добавьте содержимое на таймлайн.",
  space: (required: string, available: string) => `Требуется около ${required}; осталось только ${available}`,
  notEnough: (resource: string) => `Недостаточно: ${resource}`,
  resourceHint: "Экспортируйте более короткий диапазон или выберите меньшее разрешение и повторите попытку.",
};
