import type { ExportRejectionMessages } from './export-rejection.ts';

export const ja: ExportRejectionMessages = {
  portableReason: {
    missing: 'ファイルが見つかりません',
    changed: '追加したときと内容が異なります',
    unreadable: '読み取れません',
  },
  titles: {
    VIDEO_NOT_OPEN: '動画が開かれていません',
    EXPORT_KIND_UNSUPPORTED: 'このバージョンではこの種類の内容をまだ書き出せません',
    EXPORT_SOURCE_UNSUPPORTED: 'このドキュメントはこの方法では書き出せません',
    EXPORT_NOTHING_TO_EXPORT: '範囲内に書き出せる内容がありません',
    EXPORT_SOURCE_NOT_FOUND: '書き出せるドキュメントがありません',
    EXPORT_SOURCE_AMBIGUOUS: '書き出せるドキュメントが複数あります',
    EXPORT_TOOL_MISSING: 'このコンピュータには書き出しに必要なツールがありません',
    EXPORT_UNSUPPORTED_CONTENT: '書き出し用にレンダリングできない内容があります',
    ASSET_MISSING: '読み取れない素材があります',
    ASSET_CHANGED: '内容が変わった素材があります',
    ENTITY_NOT_FOUND: 'シーケンスが存在しません',
    DUB_GROUP_NOT_FOUND: 'この吹き替えグループが見つかりません',
    EXPORT_PACKAGE_LOCAL_PATH: 'このコンピュータ上のパスを含むドキュメントがあります',
    EXPORT_PACKAGE_UNSUPPORTED: 'ポータブルパッケージに入れられないファイルがあります',
    EXPORT_INSUFFICIENT_SPACE: '書き出し先のディスクの空き容量が足りません',
    EXPORT_DESTINATION_EXISTS: '同じ名前のファイルがすでにあります',
    EXPORT_DESTINATION_UNWRITABLE: '書き出し先に書き込めません',
    EXPORT_RENDER_FAILED: '動画をレンダリングできませんでした',
    EXPORT_VALIDATION_FAILED: '書き出したファイルが検証に通りませんでした',
    EXPORT_PUBLISH_FAILED: 'ファイルを書き出し先に保存できませんでした',
    EXPORT_PARTIALLY_PUBLISHED: '一部のファイルだけが保存されました',
    RESOURCE_ADMISSION_UNSATISFIABLE: 'このコンピュータにはこの書き出しに必要なリソースが足りません',
  },
  resources: {
    memory: 'メモリ',
    gpuMemory: 'GPU メモリ',
    cpuThreads: 'CPU スレッド',
    scratchDisk: '一時ファイル用のディスク容量',
  },
  problemSeparator: '、',
  fileProblems: (file: string, problems: string) => `${file}：${problems}`,
  notStarted: '書き出しを開始できませんでした',
  failed: '書き出しに失敗しました',
  missingTool: (tool: string) => `不足：${tool}`,
  assetMissingHint: 'ファイルを見つけるか「素材」で再リンクしてから、もう一度書き出してください。',
  assetChangedHint: 'この素材を再リンクするか元のファイルを戻してから、もう一度書き出してください。',
  nothingHint: '別の範囲を選ぶか、先にタイムラインに何か配置してください。',
  space: (required: string, available: string) => `約 ${required} 必要ですが、残りは ${available} だけです`,
  notEnough: (resource: string) => `不足：${resource}`,
  resourceHint: '短い範囲を書き出すか低い解像度を選んでから、もう一度試してください。',
};
