import type { ExportJobMessages } from './export-job.ts';

export const zhHant: ExportJobMessages = {
  tabVideo: '影片',
  tabAudio: '音訊',
  tabSubtitles: '字幕',
  tabTranscript: '逐字稿',
  tabProject: '專案檔',
  export: '匯出',
  queued: '匯出排隊中',
  exporting: '匯出中…',
  exportingPct: (pct: number) => `匯出中 · ${pct}%`,
  formats: { md: 'Markdown', txt: '純文字', xmeml: 'FCP7 XML' },
  titleVideo: (format: string) => `匯出影片 · ${format}`,
  titleAudio: (format: string) => `匯出音訊 · ${format}`,
  titleSubtitles: (format: string) => `匯出字幕 · ${format}`,
  titleTranscript: (format: string) => `匯出逐字稿 · ${format}`,
  titlePortable: '匯出可攜式套件',
  titleProject: (format: string) => `匯出專案檔 · ${format}`,
  generating: {
    video: '編碼中',
    audio: '混音中',
    subtitles: '寫入檔案中',
    transcript: '寫入檔案中',
    portable: '封裝中',
    project: '寫入專案檔中',
  },
  retrying: '發生錯誤後自動重試',
  saving: '儲存檔案中',
  framesOf: (done: string, total: string) => `已渲染 ${done} / ${total} 個影格`,
  frames: (done: string) => `已渲染 ${done} 個影格`,
  secondsOf: (done: string, total: string) => `已處理 ${done} / ${total}`,
  seconds: (done: string) => `已處理 ${done}`,
  outputsOf: (done: number, total: number) => `已寫入 ${done} / ${total} 個檔案`,
  outputs: (done: number) => `已寫入 ${done} 個檔案`,
  bytesOf: (done: string, total: string) => `已封裝 ${done} / ${total}`,
  bytes: (done: string) => `已封裝 ${done}`,
  mono: '單聲道',
  stereo: '立體聲',
  entries: (n: number) => `${n} 個項目`,
  files: (n: number) => `${n} 個檔案`,
  assetRevisions: (n: number) => `${n} 個素材版本`,
  missing: (n: number) => `${n} 個遺失`,
  clips: (n: number) => `${n} 段片段`,
  omitted: (n: number) => `${n} 個項目未寫入專案檔`,
  doneMany: (n: number, total: string) => `${n} 個檔案 · 共 ${total}`,
  cancelledKept: (n: number) => `已儲存的 ${n} 個檔案已保留 · 影片本身不受影響`,
  cancelledRemoved: '未完成的檔案已刪除 · 影片本身不受影響',
};
