import type { ExportJobMessages } from './export-job.ts';
import { pluralForm } from '@baocut/protocol';
const filesFr = (n: number) => `${n} ${pluralForm('fr', n, { one: 'fichier', other: 'fichiers' })}`;

export const fr: ExportJobMessages = {
  tabVideo: 'Vidéo', tabAudio: 'Audio', tabSubtitles: 'Sous-titres', tabTranscript: 'Transcription', tabProject: 'Fichier de projet', export: 'Exporter', queued: 'Export en file d’attente', exporting: 'Export…', exportingPct: (pct) => `Export · ${pct} %`, formats: { md: 'Markdown', txt: 'Texte brut', xmeml: 'FCP7 XML' }, titleVideo: (format) => `Exporter la vidéo · ${format}`, titleAudio: (format) => `Exporter l’audio · ${format}`, titleSubtitles: (format) => `Exporter les sous-titres · ${format}`, titleTranscript: (format) => `Exporter la transcription · ${format}`, titlePortable: 'Exporter le paquet portable', titleProject: (format) => `Exporter le fichier de projet · ${format}`,
  generating: { video: 'Encodage', audio: 'Mixage', subtitles: 'Écriture des fichiers', transcript: 'Écriture des fichiers', portable: 'Création du paquet', project: 'Écriture du fichier de projet' }, retrying: 'Nouvelle tentative automatique après une erreur', saving: 'Enregistrement des fichiers', framesOf: (done, total) => `${done} / ${total} images rendues`, frames: (done) => `${done} images rendues`, secondsOf: (done, total) => `${done} / ${total} traités`, seconds: (done) => `${done} traités`, outputsOf: (done, total) => `${done} / ${total} ${pluralForm('fr', total, { one: 'fichier écrit', other: 'fichiers écrits' })}`, outputs: (done) => `${filesFr(done)} ${pluralForm('fr', done, { one: 'écrit', other: 'écrits' })}`, bytesOf: (done, total) => `${done} / ${total} empaquetés`, bytes: (done) => `${done} empaquetés`, mono: 'Mono', stereo: 'Stéréo',
  entries: (n) => `${n} ${pluralForm('fr', n, { one: 'entrée', other: 'entrées' })}`, files: filesFr, assetRevisions: (n) => `${n} ${pluralForm('fr', n, { one: 'version de média', other: 'versions de médias' })}`, missing: (n) => `${n} manquants`, clips: (n) => `${n} ${pluralForm('fr', n, { one: 'clip', other: 'clips' })}`, omitted: (n) => `${n} ${pluralForm('fr', n, { one: 'élément non écrit', other: 'éléments non écrits' })} dans le fichier de projet`, doneMany: (n, total) => `${filesFr(n)} · ${total} au total`, cancelledKept: (n) => `${n === 1 ? 'Le fichier enregistré est conservé' : `Les ${n} fichiers enregistrés sont conservés`} · La vidéo elle-même est inchangée`, cancelledRemoved: 'Les fichiers non terminés ont été supprimés · La vidéo elle-même est inchangée',
};
