import type { ExportRejectionMessages } from './export-rejection.ts';

export const zhHans: ExportRejectionMessages = {
  portableReason: {
    missing: '文件不在',
    changed: '内容与登记时不一样',
    unreadable: '读不出来',
  },
  titles: {
    VIDEO_NOT_OPEN: '视频没有打开',
    EXPORT_KIND_UNSUPPORTED: '这个版本还不能导出这种内容',
    EXPORT_SOURCE_UNSUPPORTED: '这份文档不能这样导出',
    EXPORT_NOTHING_TO_EXPORT: '范围里没有可以导出的内容',
    EXPORT_SOURCE_NOT_FOUND: '找不到可以导出的文档',
    EXPORT_SOURCE_AMBIGUOUS: '有几份文档都可以导出',
    EXPORT_TOOL_MISSING: '这台电脑缺导出要用的工具',
    EXPORT_UNSUPPORTED_CONTENT: '有内容导出时画不出来',
    ASSET_MISSING: '有素材读不到',
    ASSET_CHANGED: '有素材的内容变了',
    ENTITY_NOT_FOUND: '序列不存在',
    DUB_GROUP_NOT_FOUND: '找不到这一组配音',
    EXPORT_PACKAGE_LOCAL_PATH: '有文档写着这台电脑上的路径',
    EXPORT_PACKAGE_UNSUPPORTED: '有文件写不进便携包',
    EXPORT_INSUFFICIENT_SPACE: '导出位置所在的盘空间不够',
    EXPORT_DESTINATION_EXISTS: '同名文件已经存在',
    EXPORT_DESTINATION_UNWRITABLE: '导出位置写不进去',
    EXPORT_RENDER_FAILED: '画面没有渲染出来',
    EXPORT_VALIDATION_FAILED: '导出的文件没通过校验',
    EXPORT_PUBLISH_FAILED: '文件没能保存到导出位置',
    EXPORT_PARTIALLY_PUBLISHED: '只保存了一部分文件',
    RESOURCE_ADMISSION_UNSATISFIABLE: '这台电脑的资源放不下这次导出',
  },
  resources: {
    memory: '内存',
    gpuMemory: 'GPU 内存',
    cpuThreads: 'CPU 线程',
    scratchDisk: '临时文件所在的磁盘空间',
  },
  problemSeparator: '；',
  fileProblems: (file: string, problems: string) => `${file}：${problems}`,
  notStarted: '导出没有开始',
  failed: '导出失败',
  missingTool: (tool: string) => `缺：${tool}`,
  assetMissingHint: '找回文件，或在素材里重新链接它，再导一次。',
  assetChangedHint: '重新链接这个素材，或换回原来的文件，再导一次。',
  nothingHint: '换一段范围，或先在时间轴上放点内容。',
  space: (required: string, available: string) => `需要约 ${required}，只剩 ${available}`,
  notEnough: (resource: string) => `不够：${resource}`,
  resourceHint: '导短一点的范围，或选低一点的分辨率再导。',
};
