import { pluralForm } from '@baocut/protocol';
import type { FontLibraryMessages } from './font-library.ts';

export const ru: FontLibraryMessages = {
  state: {
    'built-in': "Встроенный",
    installed: "Установлено",
    downloaded: "Скачано",
    downloadable: "Доступен для скачивания",
    downloading: "Скачивание",
    failed: "Ошибка",
    unavailable: "Шрифт не найден",
  },
  source: {
    'built-in': "Поставляется с приложением",
    local: "Установлен на этом компьютере",
    'google-fonts': "Google Fonts",
  },
  categories: {
    'sans-serif': "Без засечек",
    serif: "С засечками",
    display: "Декоративный",
    handwriting: "Рукописный",
    monospace: "Моноширинный",
  },
  scripts: {
    chinese: "китайский",
    japanese: "японский",
    korean: "корейский",
    latin: "латинский",
    cyrillic: "кириллица",
    greek: "греческий",
    vietnamese: "вьетнамский",
    arabic: "арабский",
    hebrew: "иврит",
    thai: "тайский",
    devanagari: "деванагари",
  },
  privacyNote: "Скачивается из Google Fonts; отправляются только имя семейства и насыщенности. Хранится в данных приложения, вне папки видео.",
  offlineNote: "Вы офлайн · Для скачивания шрифтов нужно соединение",
  strictOfflineNote: "Строгий офлайн включён · Шрифты не скачиваются; доступные для скачивания показаны резервным шрифтом",
  waiting: "Ожидание",
  sections: { search: "Результаты поиска", video: "Используется в видео", recent: "Недавно использованные", all: "Все шрифты" },
  cancelled: "Отменено",
  downloadFailed: "Ошибка скачивания",
  pickToast: (family: string, fallback: string) => `«${family}» отображается шрифтом «${fallback}» до скачивания, затем переключается автоматически`,
  alreadyDownloaded: (family: string) => `«${family}» уже скачан`,
  detail: { status: "Статус", source: "Источник", category: "Категория", weights: "Насыщенности", size: "Размер", licence: "Лицензия" },
  scriptJoin: (labels: readonly string[]) => labels.join(", "),
  withItalics: " (с курсивом)",
  downloadedSize: (size: string) => `${size} скачано`,
  unknownLicence: "Неизвестно (локальный шрифт; сами проверьте право на публикацию)",
  mirrorInvalid: "Недопустимый адрес",
  mirrorHttps: "Принимаются только адреса с https://",
  mirrorCredentials: "Адрес не может содержать имя пользователя или пароль",
  mirrorQuery: "Адрес не может содержать параметры запроса или #",
  italic: " курсив",
  cleared: (removed: number, freed: string, kept: number) => `Очищено: ${pluralForm('ru', removed, { one: `${removed} семейство`, few: `${removed} семейства`, many: `${removed} семейств`, other: `${removed} семейства` })}, освобождено ${freed}${kept ? ` · Сохранено для экспорта: ${pluralForm('ru', kept, { one: `${kept} семейство`, few: `${kept} семейства`, many: `${kept} семейств`, other: `${kept} семейства` })}` : ''}`,
  clearConfirm: (count: number, size: string, inUse: boolean) => `Удалить: ${pluralForm('ru', count, { one: `${count} семейство`, few: `${count} семейства`, many: `${count} семейств`, other: `${count} семейства` })}, ${size} всего. Видео с этими шрифтами показывают резервный до повторного скачивания.${inUse ? " Шрифты незавершённого экспорта сохранятся." : ''}`,
  barOff: (total: number) => `Не скачано для видео: ${pluralForm('ru', total, { one: `${total} шрифт`, few: `${total} шрифта`, many: `${total} шрифтов`, other: `${total} шрифта` })}; отображается резервным шрифтом`,
  autoOff: "Автоскачивание отключено",
  barRunning: "Скачивание шрифтов этого видео",
  barReady: (total: number) => total === 1 ? "Шрифт этого видео готов" : `Для видео готовы: ${pluralForm('ru', total, { one: `${total} шрифт`, few: `${total} шрифта`, many: `${total} шрифтов`, other: `${total} шрифта` })}`,
  barMissed: (n: number) => `Не удалось получить: ${pluralForm('ru', n, { one: `${n} шрифт`, few: `${n} шрифта`, many: `${n} шрифтов`, other: `${n} шрифта` })}; отображается резервным шрифтом`,
  skipped: "Пропущено",
  notDownloaded: "Не скачано",
  quoteList: (names: readonly string[]) => new Intl.ListFormat('ru', { type: 'conjunction' }).format(names.map(n => `«${n}»`)),
  exportPending: (names: string, n) => `${n === 1 ? 'Шрифт' : 'Шрифты'} ${names} ${n === 1 ? 'скачивается' : 'скачиваются'} · Экспорт ждёт ${n === 1 ? 'его' : 'их'} перед рендерингом`,
  exportFailed: (names: string, fallbacks: string) => `${names} не скачан · ${fallbacks} будет использован при экспорте вместо него`,
  exportMissingAuto: (names: string, n) => `${n === 1 ? 'Шрифт' : 'Шрифты'} ${names} ещё не ${n === 1 ? 'скачан' : 'скачаны'} · Скачивание при запуске экспорта; при ошибке используется резервный шрифт`,
  exportMissingOff: (names: string, n) => `${n === 1 ? 'Шрифт' : 'Шрифты'} ${names} не ${n === 1 ? 'скачан' : 'скачаны'} (автоскачивание отключено) · Экспорт использует резервный шрифт`,
  actionRetry: "Повторить попытку",
  actionDownloadNow: "Скачать сейчас",
  actionDownload: "Скачать",
  exportFallback: (family: string, fallback: string, reason: string) => `«${family}» заменён на «${fallback}» · ${reason}`,
  exportFallbackSeparator: "; ",
  exportPhase: (detail: string | null) => (detail ? `Скачивание шрифтов · ${detail}` : "Скачивание шрифтов"),
  systemFont: "Системный шрифт",
  errorFallback: "Операция не завершена",
  removed: (family: string) => `Удалены скачанные файлы шрифта «${family}»`,
  removeInUse: (family: string) => `Незавершённый экспорт использует «${family}» · Удалите после завершения экспорта`,
};
