import type { FontLibraryMessages } from './font-library.ts';

export const zhHant: FontLibraryMessages = {
  state: {
    'built-in': '內建',
    installed: '已安裝',
    downloaded: '已下載',
    downloadable: '可下載',
    downloading: '下載中',
    failed: '失敗',
    unavailable: '找不到字型',
  },
  source: {
    'built-in': '隨應用程式提供',
    local: '已安裝在這台電腦',
    'google-fonts': 'Google Fonts',
  },
  categories: {
    'sans-serif': '無襯線',
    serif: '襯線',
    display: '標題',
    handwriting: '手寫',
    monospace: '等寬',
  },
  scripts: {
    chinese: '中文',
    japanese: '日文',
    korean: '韓文',
    latin: '拉丁文',
    cyrillic: '西里爾文',
    greek: '希臘文',
    vietnamese: '越南文',
    arabic: '阿拉伯文',
    hebrew: '希伯來文',
    thai: '泰文',
    devanagari: '天城文',
  },
  privacyNote: '從 Google Fonts 下載，只會傳送字族名稱和字重。儲存在應用程式資料中，不會放入影片資料夾。',
  offlineNote: '目前離線 · 可下載的字型需要網路連線才能下載',
  strictOfflineNote: '已開啟嚴格離線模式 · 不會下載字型，可下載的字型會以替代字型顯示',
  waiting: '等待中',
  sections: { search: '搜尋結果', video: '這部影片使用的', recent: '最近使用', all: '所有字型' },
  cancelled: '已取消',
  downloadFailed: '下載失敗',
  pickToast: (family: string, fallback: string) => `「${family}」下載完成前先以「${fallback}」顯示，下載後會自動切換`,
  alreadyDownloaded: (family: string) => `「${family}」已下載`,
  detail: { status: '狀態', source: '來源', category: '類別', weights: '字重', size: '大小', licence: '授權條款' },
  scriptJoin: (labels: readonly string[]) => labels.join('、'),
  withItalics: '（含斜體）',
  downloadedSize: (size: string) => `已下載 ${size}`,
  unknownLicence: '不明（這台電腦上的字型，請自行確認能否用於發布）',
  mirrorInvalid: '不是有效的網址',
  mirrorHttps: '只接受以 https:// 開頭的網址',
  mirrorCredentials: '網址不能包含使用者名稱或密碼',
  mirrorQuery: '網址不能包含查詢參數或 #',
  italic: ' 斜體',
  cleared: (removed: number, freed: string, kept: number) =>
    `已清除 ${removed} 個字族，釋放 ${freed}${kept ? ` · 已保留匯出正在使用的 ${kept} 個` : ''}`,
  clearConfirm: (count: number, size: string, inUse: boolean) =>
    `刪除 ${count} 個字族，共 ${size}。使用這些字型的影片會先以替代字型顯示，需要時再重新下載。` +
    (inUse ? '未完成的匯出正在使用的字型會保留。' : ''),
  barOff: (total: number) => `這部影片使用了 ${total} 個未下載的字型，目前以替代字型顯示`,
  autoOff: '自動下載已關閉',
  barRunning: '正在下載這部影片使用的字型',
  barReady: (total: number) => (total === 1 ? '這部影片使用的字型已就緒' : `這部影片使用的 ${total} 個字型都已就緒`),
  barMissed: (n: number) => `${n} 個字型無法取得，目前以替代字型顯示`,
  skipped: '已略過',
  notDownloaded: '未下載',
  quoteList: (names: readonly string[]) => names.map((n) => `「${n}」`).join(''),
  exportPending: (names: string) => `${names}仍在下載 · 匯出會等下載完成後才開始渲染`,
  exportFailed: (names: string, fallbacks: string) => `${names}下載失敗 · 匯出時會改用${fallbacks}`,
  exportMissingAuto: (names: string) => `${names}尚未下載 · 匯出開始時會先下載，若失敗則使用替代字型`,
  exportMissingOff: (names: string) => `${names}未下載（自動下載已關閉）· 匯出時會使用替代字型`,
  actionRetry: '重試',
  actionDownloadNow: '立即下載',
  actionDownload: '下載',
  exportFallback: (family: string, fallback: string, reason: string) => `「${family}」已以「${fallback}」替代 · ${reason}`,
  exportFallbackSeparator: '；',
  exportPhase: (detail: string | null) => (detail ? `正在下載字型 · ${detail}` : '正在下載字型'),
  systemFont: '系統字型',
  errorFallback: '操作未完成',
  removed: (family: string) => `已刪除「${family}」的下載檔案`,
  removeInUse: (family: string) => `未完成的匯出正在使用「${family}」· 請在匯出完成後再刪除`,
};
