import type { FontLibraryMessages } from './font-library.ts';

export const ja: FontLibraryMessages = {
  state: {
    'built-in': '内蔵',
    installed: 'インストール済み',
    downloaded: 'ダウンロード済み',
    downloadable: 'ダウンロード可能',
    downloading: 'ダウンロード中',
    failed: '失敗',
    unavailable: 'フォントが見つかりません',
  },
  source: {
    'built-in': 'アプリに付属',
    local: 'このコンピュータにインストール済み',
    'google-fonts': 'Google Fonts',
  },
  categories: {
    'sans-serif': 'サンセリフ',
    serif: 'セリフ',
    display: 'ディスプレイ',
    handwriting: '手書き',
    monospace: '等幅',
  },
  scripts: {
    chinese: '中国語',
    japanese: '日本語',
    korean: '韓国語',
    latin: 'ラテン文字',
    cyrillic: 'キリル文字',
    greek: 'ギリシャ文字',
    vietnamese: 'ベトナム語',
    arabic: 'アラビア文字',
    hebrew: 'ヘブライ文字',
    thai: 'タイ文字',
    devanagari: 'デーヴァナーガリー',
  },
  privacyNote: 'Google Fonts からダウンロードします。送信するのはファミリー名とウェイトだけです。アプリのデータに保存され、動画フォルダには入りません。',
  offlineNote: 'オフラインです · ダウンロード可能なフォントをダウンロードするにはネットワーク接続が必要です',
  strictOfflineNote: '厳格オフラインモードがオンです · フォントはダウンロードせず、ダウンロード可能なフォントは代替フォントで表示します',
  waiting: '待機中',
  sections: { search: '検索結果', video: 'この動画で使用中', recent: '最近使用したフォント', all: 'すべてのフォント' },
  cancelled: 'キャンセル済み',
  downloadFailed: 'ダウンロード失敗',
  pickToast: (family: string, fallback: string) => `「${family}」はダウンロードが終わるまで「${fallback}」で表示し、完了後に自動で切り替わります`,
  alreadyDownloaded: (family: string) => `「${family}」はダウンロード済みです`,
  detail: { status: '状態', source: '提供元', category: 'カテゴリ', weights: 'ウェイト', size: 'サイズ', licence: 'ライセンス' },
  scriptJoin: (labels: readonly string[]) => labels.join('、'),
  withItalics: '（イタリックあり）',
  downloadedSize: (size: string) => `${size} ダウンロード済み`,
  unknownLicence: '不明（このコンピュータのフォントです。公開に使えるかはご自身で確認してください）',
  mirrorInvalid: '有効なアドレスではありません',
  mirrorHttps: 'https:// で始まるアドレスのみ使用できます',
  mirrorCredentials: 'アドレスにユーザ名やパスワードは含められません',
  mirrorQuery: 'アドレスにクエリパラメータや # は含められません',
  italic: ' イタリック',
  cleared: (removed: number, freed: string, kept: number) =>
    `${removed} 個のファミリーを消去し、${freed} を解放しました${kept ? ` · 書き出しで使用中の ${kept} 個は残しました` : ''}`,
  clearConfirm: (count: number, size: string, inUse: boolean) =>
    `${count} 個のファミリー（合計 ${size}）を削除します。これらを使う動画は、必要なときに再ダウンロードされるまで代替フォントで表示されます。` +
    (inUse ? '未完了の書き出しで使用中のフォントは残します。' : ''),
  barOff: (total: number) => `この動画はダウンロードされていないフォントを ${total} 個使っているため、代替フォントで表示しています`,
  autoOff: '自動ダウンロードはオフです',
  barRunning: 'この動画で使うフォントをダウンロード中',
  barReady: (total: number) => `この動画で使うフォント ${total} 個の準備ができました`,
  barMissed: (n: number) => `${n} 個のフォントを取得できなかったため、代替フォントで表示しています`,
  skipped: 'スキップ済み',
  notDownloaded: '未ダウンロード',
  quoteList: (names: readonly string[]) => names.map((n) => `「${n}」`).join('、'),
  exportPending: (names: string) => `${names}はまだダウンロード中です · 書き出しはダウンロードの完了を待ってからレンダリングします`,
  exportFailed: (names: string, fallbacks: string) => `${names}をダウンロードできませんでした · 書き出しでは代わりに${fallbacks}を使います`,
  exportMissingAuto: (names: string) =>
    `${names}はまだダウンロードされていません · 書き出し開始時にダウンロードし、失敗した場合は代替フォントを使います`,
  exportMissingOff: (names: string) => `${names}はダウンロードされていません（自動ダウンロードはオフ） · 書き出しでは代替フォントを使います`,
  actionRetry: '再試行',
  actionDownloadNow: '今すぐダウンロード',
  actionDownload: 'ダウンロード',
  exportFallback: (family: string, fallback: string, reason: string) => `「${family}」を「${fallback}」で代替 · ${reason}`,
  exportFallbackSeparator: '、',
  exportPhase: (detail: string | null) => (detail ? `フォントをダウンロード中 · ${detail}` : 'フォントをダウンロード中'),
  systemFont: 'システムフォント',
  errorFallback: '操作を完了できませんでした',
  removed: (family: string) => `「${family}」のダウンロード済みファイルを削除しました`,
  removeInUse: (family: string) => `未完了の書き出しが「${family}」を使用中です · 書き出しが終わってから削除してください`,
};
