import type { FontLibraryMessages } from './font-library.ts';
import { pluralForm } from '@baocut/protocol';

const familiesN = (n: number) => pluralForm('it', n, { one: `${n} famiglia`, other: `${n} famiglie` });

export const it: FontLibraryMessages = {
  state: { 'built-in': 'Integrato', installed: 'Installato', downloaded: 'Scaricato', downloadable: 'Disponibile per il download', downloading: 'Download in corso', failed: 'Non riuscito', unavailable: 'Font non trovato' }, source: { 'built-in': 'Incluso nell’app', local: 'Installato su questo computer', 'google-fonts': 'Google Fonts' }, categories: { 'sans-serif': 'Senza grazie', serif: 'Con grazie', display: 'Da titolazione', handwriting: 'Scrittura a mano', monospace: 'Monospaziato' }, scripts: { chinese: 'cinese', japanese: 'giapponese', korean: 'coreano', latin: 'latino', cyrillic: 'cirillico', greek: 'greco', vietnamese: 'vietnamita', arabic: 'arabo', hebrew: 'ebraico', thai: 'thai', devanagari: 'devanagari' },
  privacyNote: 'Scaricati da Google Fonts; vengono inviati solo nome della famiglia e pesi. Memorizzati nei dati dell’app, non nella cartella del video.', offlineNote: 'Sei offline · I font scaricabili richiedono una connessione di rete', strictOfflineNote: 'Modalità rigorosamente offline attiva · I font non vengono scaricati; quelli scaricabili vengono mostrati con un font alternativo', waiting: 'In attesa', sections: { search: 'Risultati di ricerca', video: 'Usati in questo video', recent: 'Usati di recente', all: 'Tutti i font' }, cancelled: 'Annullato', downloadFailed: 'Download non riuscito',
  pickToast: (family: string, fallback: string) => `«${family}» viene mostrato con «${fallback}» fino al download, poi cambia automaticamente`, alreadyDownloaded: (family: string) => `«${family}»: download già completato`, detail: { status: 'Stato', source: 'Origine', category: 'Categoria', weights: 'Pesi', size: 'Dimensione', licence: 'Licenza' }, scriptJoin: (labels: readonly string[]) => labels.join(', '), withItalics: ' (con corsivo)', downloadedSize: (size: string) => `Scaricati: ${size}`, unknownLicence: 'Sconosciuta (font di questo computer; verifica tu se può essere usato per la pubblicazione)', mirrorInvalid: 'Indirizzo non valido', mirrorHttps: 'Sono accettati solo indirizzi che iniziano con https://', mirrorCredentials: 'L’indirizzo non può includere un nome utente o una password', mirrorQuery: 'L’indirizzo non può includere parametri di query o #', italic: ' corsivo',
  cleared: (removed: number, freed: string, kept: number) => `${pluralForm('it', removed, { one: `Cancellata ${familiesN(removed)}`, other: `Cancellate ${familiesN(removed)}` })}, spazio liberato ${freed}${kept ? ` · ${pluralForm('it', kept, { one: `${kept} conservata, in uso nelle esportazioni`, other: `${kept} conservate, in uso nelle esportazioni` })}` : ''}`,
  clearConfirm: (count: number, size: string, inUse: boolean) => `Elimina ${familiesN(count)}, ${size} in totale. I video che le usano mostrano un font alternativo finché non vengono scaricate di nuovo quando necessario.${inUse ? ' I font usati da esportazioni non completate vengono conservati.' : ''}`,
  barOff: (total: number) => pluralForm('it', total, { one: `Questo video usa ${total} font non scaricato; viene mostrato un font alternativo`, other: `Questo video usa ${total} font non scaricati; viene mostrato un font alternativo` }), autoOff: 'Download automatico disattivato', barRunning: 'Download dei font usati in questo video', barReady: (total: number) => total === 1 ? 'Il font usato in questo video è pronto' : pluralForm('it', total, { other: `Tutti i ${total} font usati in questo video sono pronti` }), barMissed: (n: number) => pluralForm('it', n, { one: `Impossibile recuperare ${n} font; viene mostrato un font alternativo`, other: `Impossibile recuperare ${n} font; viene mostrato un font alternativo` }), skipped: 'Saltato', notDownloaded: 'Non scaricato',
  quoteList: (names: readonly string[]) => new Intl.ListFormat('it', { type: 'conjunction' }).format(names.map((n) => `«${n}»`)),
  exportPending: (names: string, n: number) => pluralForm('it', n, { one: `${names} è ancora in download · L’esportazione ne attende il completamento prima del rendering`, other: `${names} sono ancora in download · L’esportazione ne attende il completamento prima del rendering` }), exportFailed: (names: string, fallbacks: string) => `Download di ${names} non riuscito · Nell’esportazione verranno usati ${fallbacks}`,
  exportMissingAuto: (names: string, n: number) => pluralForm('it', n, { one: `${names} non è ancora scaricato · Verrà scaricato all’avvio dell’esportazione; in caso di errore viene usato un font alternativo`, other: `${names} non sono ancora scaricati · Verranno scaricati all’avvio dell’esportazione; in caso di errore viene usato un font alternativo` }), exportMissingOff: (names: string, n: number) => pluralForm('it', n, { one: `${names} non è scaricato (download automatico disattivato) · L’esportazione userà un font alternativo`, other: `${names} non sono scaricati (download automatico disattivato) · L’esportazione userà un font alternativo` }), actionRetry: 'Riprova', actionDownloadNow: 'Scarica ora', actionDownload: 'Scarica',
  exportFallback: (family: string, fallback: string, reason: string) => `«${family}» sostituito con «${fallback}» · ${reason}`, exportFallbackSeparator: '; ', exportPhase: (detail: string | null) => detail ? `Download dei font · ${detail}` : 'Download dei font', systemFont: 'Font di sistema', errorFallback: 'L’operazione non è stata completata', removed: (family: string) => `File scaricati di «${family}» eliminati`, removeInUse: (family: string) => `Un’esportazione non completata sta usando «${family}» · Eliminalo al termine dell’esportazione`,
};
