import type { FontLibraryMessages } from './font-library.ts';

export const ko: FontLibraryMessages = {
  state: {
    'built-in': '기본 제공',
    installed: '설치됨',
    downloaded: '다운로드됨',
    downloadable: '다운로드 가능',
    downloading: '다운로드 중',
    failed: '실패',
    unavailable: '글꼴을 찾을 수 없음',
  },
  source: {
    'built-in': '앱에 포함',
    local: '이 컴퓨터에 설치됨',
    'google-fonts': 'Google Fonts',
  },
  categories: {
    'sans-serif': '산세리프',
    serif: '세리프',
    display: '디스플레이',
    handwriting: '손글씨',
    monospace: '고정폭',
  },
  scripts: {
    chinese: '중국어',
    japanese: '일본어',
    korean: '한국어',
    latin: '라틴 문자',
    cyrillic: '키릴 문자',
    greek: '그리스 문자',
    vietnamese: '베트남어',
    arabic: '아랍 문자',
    hebrew: '히브리 문자',
    thai: '태국 문자',
    devanagari: '데바나가리 문자',
  },
  privacyNote: 'Google Fonts에서 다운로드하며 글꼴 패밀리 이름과 굵기만 전송합니다. 영상 폴더가 아니라 앱 데이터에 저장됩니다.',
  offlineNote: '오프라인 상태입니다 · 다운로드 가능한 글꼴은 네트워크에 연결해야 다운로드할 수 있습니다',
  strictOfflineNote: '엄격한 오프라인 모드가 켜져 있습니다 · 글꼴을 다운로드하지 않으며, 다운로드 가능한 글꼴은 대체 글꼴로 표시합니다',
  waiting: '대기 중',
  sections: { search: '검색 결과', video: '이 영상에서 사용', recent: '최근 사용', all: '모든 글꼴' },
  cancelled: '취소됨',
  downloadFailed: '다운로드 실패',
  pickToast: (family: string, fallback: string) => `“${family}” 글꼴은 다운로드될 때까지 “${fallback}” 글꼴로 표시되고, 다운로드되면 자동으로 바뀝니다`,
  alreadyDownloaded: (family: string) => `“${family}” 글꼴은 이미 다운로드되었습니다`,
  detail: { status: '상태', source: '출처', category: '분류', weights: '굵기', size: '크기', licence: '라이선스' },
  scriptJoin: (labels: readonly string[]) => labels.join(', '),
  withItalics: '(이탤릭 포함)',
  downloadedSize: (size: string) => `${size} 다운로드됨`,
  unknownLicence: '알 수 없음(이 컴퓨터의 글꼴입니다. 게시에 사용할 수 있는지 직접 확인하세요)',
  mirrorInvalid: '올바른 주소가 아닙니다',
  mirrorHttps: 'https://로 시작하는 주소만 사용할 수 있습니다',
  mirrorCredentials: '주소에 사용자 이름이나 비밀번호를 넣을 수 없습니다',
  mirrorQuery: '주소에 쿼리 매개변수나 #을 넣을 수 없습니다',
  italic: ' 이탤릭',
  cleared: (removed: number, freed: string, kept: number) =>
    `글꼴 패밀리 ${removed}개를 지워 ${freed}의 공간을 확보했습니다${kept ? ` · 내보내기에서 사용 중인 ${kept}개는 남겨 두었습니다` : ''}`,
  clearConfirm: (count: number, size: string, inUse: boolean) =>
    `글꼴 패밀리 ${count}개(총 ${size})를 삭제합니다. 이 글꼴을 쓰는 영상은 필요할 때 다시 다운로드될 때까지 대체 글꼴로 표시됩니다.` +
    (inUse ? ' 아직 끝나지 않은 내보내기에서 사용 중인 글꼴은 남겨 둡니다.' : ''),
  barOff: (total: number) => `이 영상에서 쓰는 글꼴 ${total}개가 다운로드되지 않아 대체 글꼴로 표시하고 있습니다`,
  autoOff: '자동 다운로드가 꺼져 있습니다',
  barRunning: '이 영상에서 쓰는 글꼴을 다운로드하는 중',
  barReady: (total: number) => (total === 1 ? '이 영상에서 쓰는 글꼴이 준비되었습니다' : `이 영상에서 쓰는 글꼴 ${total}개가 모두 준비되었습니다`),
  barMissed: (n: number) => `글꼴 ${n}개를 가져오지 못해 대체 글꼴로 표시하고 있습니다`,
  skipped: '건너뜀',
  notDownloaded: '다운로드 안 됨',
  quoteList: (names: readonly string[]) => names.map((n) => `“${n}”`).join(', '),
  exportPending: (names: string) => `${names} 글꼴은 아직 다운로드 중입니다 · 내보내기는 다운로드가 끝난 뒤 렌더링을 시작합니다`,
  exportFailed: (names: string, fallbacks: string) => `${names} 글꼴을 다운로드하지 못했습니다 · 내보내기에는 대신 ${fallbacks} 글꼴을 사용합니다`,
  exportMissingAuto: (names: string) =>
    `${names} 글꼴은 아직 다운로드되지 않았습니다 · 내보내기를 시작할 때 다운로드하며, 실패하면 대체 글꼴을 사용합니다`,
  exportMissingOff: (names: string) => `${names} 글꼴은 다운로드되지 않았습니다(자동 다운로드 꺼짐) · 내보내기에 대체 글꼴을 사용합니다`,
  actionRetry: '다시 시도',
  actionDownloadNow: '지금 다운로드',
  actionDownload: '다운로드',
  exportFallback: (family: string, fallback: string, reason: string) => `“${family}” 대신 “${fallback}” 사용 · ${reason}`,
  exportFallbackSeparator: '; ',
  exportPhase: (detail: string | null) => (detail ? `글꼴 다운로드 중 · ${detail}` : '글꼴 다운로드 중'),
  systemFont: '시스템 글꼴',
  errorFallback: '요청을 완료하지 못했습니다',
  removed: (family: string) => `“${family}” 글꼴의 다운로드한 파일을 삭제했습니다`,
  removeInUse: (family: string) => `아직 끝나지 않은 내보내기에서 “${family}” 글꼴을 사용하고 있습니다 · 내보내기가 끝난 뒤 삭제하세요`,
};
