import type { GeneralSettingsModelMessages } from './general-settings.ts';

export const ja: GeneralSettingsModelMessages = {
  lineShort: '短',
  lineMedium: '中',
  lineLong: '長',
  lineLength: (cjk: number, other: number) => `CJK テキスト：1 行 ${cjk} 文字 · その他のテキスト：1 行 ${other} 文字`,
  endpointTooLong: (max: number) => `長すぎます：最大 ${max} 文字です`,
  endpointNotUrl: 'Web アドレスではありません：http:// または https:// で始めてください',
  endpointScheme: 'http:// または https:// で始まるアドレスのみ対応しています',
  endpointCredentials: 'アドレスにユーザ名やパスワードは含められません',
  endpointQuery: 'アドレスにクエリパラメータ（? 以降の部分）は含められません',
  endpointHash: 'アドレスにフラグメント（# 以降の部分）は含められません',
  saveDir: {
    label: '既定の保存場所',
    desc: 'ツールの結果、ダウンロードした動画、Agent から渡されたファイルはここに保存されます。既定はダウンロードフォルダです。',
    systemDefault: 'ダウンロードフォルダ',
    isDefault: '既定',
    change: '変更…',
    reset: '既定に戻す',
    pickTitle: '既定の保存場所を選択',
    changed: '既定の保存場所を変更しました',
    resetDone: 'ダウンロードフォルダに戻しました',
    pickFailed: (message: string) => `フォルダを選択できませんでした：${message}`,
    webNote: 'ブラウザではこのコンピュータのフォルダを選択できません。BaoCut デスクトップアプリで設定してください。',
  },
  source: {
    system: 'システムにインストール済み',
    user: '指定した場所',
    managed: 'BaoCut がダウンロード',
    env: '環境変数で指定',
  },
  notInstalled: '未インストール',
  missingDesc: 'yt-dlp はまだインストールされていません。Agent がリンクから読み込むときは、まずダウンロードへの同意を求めます（提供元、バージョン、サイズ、ライセンスを表示）。',
  consentRevoked: '同意を撤回済み',
  revokedDesc: (facts: string) => `${facts}。使用への同意を撤回したため、リンクから読み込む前にもう一度確認します。`,
  available: '使用可能',
  needsUpdate: '更新が必要',
  cannotRun: '実行できません',
  factsWhy: (facts: string, why: string) => `${facts}。${why}`,
};
