import type { HelpGuidesMessages } from './help-guides.ts';
export const nl: HelpGuidesMessages = { guides: {
 import: { title: 'Video maken en media importeren', short: 'Maken en importeren', summary: 'Maak een video in Space, voeg media toe aan de bibliotheek en plaats deze op de tijdlijn.', keywords: 'nieuw bestand media bibliotheek importeren slepen audio afbeelding import video asset', steps: [
 ['Een video maken', 'Open Space links en kies Nieuw → Lege video maken. Kies het project en daarna op de startpagina de beeldverhouding en Lege video maken. Heb je al video of audio, kies dan Video maken uit bestand. De startpagina laat je voor dat bestand kiezen tussen ondertitels toevoegen of transcriberen en vertalen. Open eerst een projectmap op Home als je nog geen project hebt. Je kunt ook Agent vragen een video te maken.'],
 ['Media importeren in de bibliotheek', 'Open Video, Audio of Afbeeldingen rechts in de editor. Kies Importeren of sleep bestanden naar het gestippelde vak. Importeren kopieert bestanden alleen naar de videomap; de oorspronkelijke bestanden blijven behouden.'],
 ['Op de tijdlijn plaatsen', 'Klik op + rechts van de media om deze bij de afspeelkop te plaatsen. Je kunt media ook naar een tijdlijnspoor slepen of bestanden vanaf je computer rechtstreeks op de tijdlijn slepen.'] ], tip: 'Importeren en op de tijdlijn plaatsen zijn twee stappen. Nieuwe imports staan in de mediabibliotheek en verschijnen nog niet in beeld.', cta: 'Video maken uit bestand' },
 subtitle: { title: 'Ondertitels toevoegen en nakijken', short: 'Ondertitels toevoegen', summary: 'Importeer ondertitels of laat Agent transcriberen en corrigeer de tekst terwijl je luistert.', keywords: 'transcriptie transcriberen herkenning srt vtt webvtt ass typefout splitsen samenvoegen zoeken vervangen transcript subtitle caption', steps: [
 ['Eerst ondertitels verkrijgen', 'Open Ondertitels rechts. Als de video media bevat, kies Ondertitels genereren om te transcriberen met een lokaal spraakmodel of verbonden clouddienst. Na afloop verschijnen de ondertitels automatisch in beeld. Transcriptie-instellingen onder de knop biedt taal, spraakmodel en herkenningshints. Heb je al ondertitels, kies Ondertitelbestand importeren; SRT, WebVTT en ASS worden ondersteund. Gebruik Tools › Transcriberen om sprekers te labelen. Open Meer opties onder het spraakmodel en schakel Sprekers identificeren in. MOSS Transcribe scheidt sprekers zelf en houdt dit altijd aan. Andere lokale modellen gebruiken Sprekers scheiden; bij het eerste gebruik wordt een download aangeboden.'],
 ['Op een zin klikken en wijzigen', 'Klik op de tijd van een zin om de afspeelkop erheen te verplaatsen. Klik op de tekst om deze te wijzigen. Enter splitst in twee zinnen, Backspace aan het regelbegin voegt samen met de vorige zin, Shift+Enter maakt een regeleinde en Esc annuleert de wijziging.'],
 ['Terugluisteren en herhaalde fouten corrigeren', 'Verlaat het invoerveld en druk op spatie om af te spelen. Controleer tekst tegen de spraak. Bovenaan staat hoeveel ondertitels de leessnelheid overschrijden. Gebruik Zoeken en vervangen (⌘F / Ctrl+F) om dezelfde fout op meerdere plaatsen te corrigeren.'] ], tip: 'Alleen transcripts gestart via Ondertitels genereren verschijnen automatisch in beeld. Agent-transcripties uit een sessie worden eerst als document opgeslagen. Kies daarna Ondertitels genereren om deze te gebruiken. Bij meerdere ondertitelversies op de tijdlijn kies je de gewenste versie via de keuzelijst bovenaan Ondertitels.', cta: 'Ondertitelpaneel openen' },
 translate: { title: 'Vertaling en tweetalige ondertitels toevoegen', short: 'Vertaling en beide talen', summary: 'Kies doeltaal en tekstmodel in het ondertitelpaneel. De vertaling verschijnt als nieuwe ondertitelspoor in beeld.', keywords: 'vertalen vertaling Engels Chinees beide talen taal brontekst vergelijken woordenlijst tekstmodel translate bilingual', steps: [
 ['Eerst de brontekst nakijken', 'Vertaling werkt zin voor zin op de transcriptie. Corrigeer eerst namen, vaktermen en duidelijke herkenningsfouten om later minder te hoeven aanpassen. De ondertitels moeten uit transcriptie komen: geïmporteerde ondertitelbestanden hebben geen woordtiming en kunnen niet direct worden vertaald.'],
 ['+ Vertalen naar… kiezen in de spoorbalk', 'Open Ondertitels rechts en kies + Vertalen naar… in de spoorbalk. Kies doeltaal en tekstmodel, voeg eventueel een stijlhint toe en selecteer woordenlijsten. Kies daarna de startknop onderaan. Verbind eerst een dienst bij Modellen › Tekstgeneratie als er geen tekstmodel beschikbaar is. Online modellen rekenen per token.'],
 ['Vertaling controleren en beide talen aanpassen', 'Na afloop verschijnt de vertaling automatisch in beeld. De resultaatkaart biedt ongedaan maken met één klik. Kies Brontekst + vertaling onder Lijst om zin voor zin te vergelijken. Klik op een vertaalde zin om deze te herschrijven. Selecteer een ondertitel; de sectie Tweetalig in Ondertiteleigenschappen bepaalt de bovenste regel en de afstand tussen regels.'] ], tip: 'Alleen de vertaling tonen? Schakel Beide talen tonen vóór het starten uit of klik op × bij de brontekst in de spoorbalk om deze uit beeld te halen. De brontekst blijft behouden. Gewijzigde brontekst maakt betrokken vertalingen Verouderd. Herschrijf deze direct om de status te herstellen, kies Verouderde vertalingen bijwerken op de waarschuwing in de desktopapp of voer /refresh in een sessie in om Agent die zinnen opnieuw te laten vertalen.', cta: 'Ondertitelpaneel openen' },
 export: { title: 'Video, ondertitels of transcriptie exporteren', short: 'Resultaat exporteren', summary: 'Kies de uitvoer die bij je doel past. Video en audio kunnen ook per hoofdstuk of clip worden geëxporteerd.', keywords: 'exporteren opslaan downloaden eindvideo mp4 wav mp3 m4a srt vtt ass json markdown transcriptie hoofdstuk fragment luidheid project premiere davinci resolve draagbaar pakket export', steps: [
 ['Exporteren kiezen in de videobalk', 'Klik rechts in de videobalk op Exporteren. Vijf uitvoertypen hebben een eigen pagina: video (MP4), audio (WAV, MP3 of M4A), ondertitels (SRT, VTT, ASS of JSON), transcriptie (Markdown of platte tekst) en project (XML voor Premiere Pro en DaVinci Resolve, of een BaoCut draagbaar pakket).'],
 ['Bereik kiezen en instellingen controleren', 'Voor video en audio kies je de volledige video, hoofdstukken, clips of een eigen begin en einde. Ondertitels, transcriptie en project gebruiken de volledige sequentie. Controleer bij video resolutie, grootte en het inbranden van ondertitels. Schakel indien nodig luidheidnormalisatie in. Twee geselecteerde ondertitelsporen kunnen één tweetalig bestand vormen.'],
 ['Export starten en wachten op voltooiing', 'Bestanden gaan standaard naar exports/ in het project. Je kunt vooraf Locatie kiezen gebruiken. Sluit het exportvenster om verder te werken. De knop Exporteren toont de voortgang; deze staat ook bij Achtergrondtaken. Kies na afloop Weergeven in map om bestanden te vinden. Bij fouten staan oorzaak en volgende stap in het venster.'] ], tip: 'Een ondertitelbestand en een video met ondertitels zijn verschillende uitvoertypen. Andere software laadt het ondertitelbestand; de video is direct afspeelbaar en deelbaar.' },
 workspace: { title: 'De editor leren kennen', short: null, summary: 'Bekijk het resultaat in het beeld, zoek momenten op de tijdlijn en wijzig inhoud in het rechterpaneel.', keywords: 'podium canvas voorbeeld tijdlijn timeline paneel eigenschappen spoor afspelen niet gevonden', steps: [
 ['Midden: beeldvoorbeeld', 'Toont het beeld bij de afspeelkop. Bovenaan staan afmetingen en framesnelheid. De bediening onderaan biedt afspelen, één frame vooruit of terug, ongedaan maken, opnieuw uitvoeren en splitsen bij de afspeelkop.'],
 ['Onder: tijdlijn', 'Klik om de afspeelkop te verplaatsen. Sleep clips om hun tijd of spoor te wijzigen en sleep de randen om bij te snijden. Rechtsklik voor splitsen, kopiëren, uitschakelen of verwijderen.'],
 ['Rechts: inhoud en eigenschappen', 'De verticale werkbalk bevat van boven naar beneden Transcriptie, Ondertitels, Elementen, Tekst, Afbeeldingen, Video, Audio, Merk en Eigenschappen. Selecteer een clip om zijn eigenschappen te zien. Zonder selectie toont Eigenschappen de Video-eigenschappen van de volledige video.'] ], tip: 'Maak fouten eerst ongedaan (⌘Z / Ctrl+Z). Versie in de videobalk opent de geschiedenis, waar je een specifieke wijziging kunt terugdraaien.' },
 style: { title: 'Ondertitels vormgeven', short: null, summary: 'Selecteer ondertitels en wijzig positie, tekststijl en weergavetiming in de eigenschappen.', keywords: 'stijl lettertype lettergrootte kleur contour achtergrond schaduw gloed positie beide talen regelafstand leestekens style font', steps: [
 ['Een ondertitel selecteren', 'Klik op een ondertitel op de tijdlijn om Ondertiteleigenschappen rechts te openen. Wijzigingen gelden voor de ondertitelstijl; alle ondertitels met dezelfde stijl veranderen mee.'],
 ['Positie en tekststijl aanpassen', 'Positie bepaalt verticale en horizontale plaats en breedte. Tekststijl bepaalt lettertype, grootte, kleur en uitlijning, met opties voor achtergrond, contour, gloed en schaduw. Slepen werkt het voorbeeld direct bij; opslaan gebeurt bij loslaten.'],
 ['Weergavetiming aanpassen', 'Vroeger en Later onder Weergave bepalen hoeveel eerder een ondertitel verschijnt en hoeveel later deze verdwijnt ten opzichte van de spraak. Leestekens kan komma’s en punten vervangen door spaties.'] ], tip: 'Als brontekst en vertaling tegelijk op de tijdlijn staan, bevat Ondertiteleigenschappen ook Tweetalig voor de bovenste regel en regelafstand. Maak ongewenste wijzigingen ongedaan (⌘Z / Ctrl+Z).', cta: 'Ondertiteleigenschappen openen' },
 elements: { title: 'Tekst, stickers en vormen toevoegen', short: null, summary: 'Voeg inhoud toe vanuit het rechterpaneel en pas positie en stijl aan in de eigenschappen.', keywords: 'element sticker vorm visualisatie voortgang tijd timer aftellen golfvorm tekst tekstvak titel lower third voorinstelling elements sticker shape text', steps: [
 ['Een element kiezen', 'Elementen rechts bevat stickers, vormen en visualisaties, met een zoekfunctie. Visualisaties biedt voortgangsbalken, timers en golfvormen. Klik om toe te voegen aan de tijdlijn. De meeste beginnen bij de afspeelkop; voortgangsbalken en vergelijkbare elementen lopen over de hele video.'],
 ['Tekst toevoegen', 'Kies Tekstvak toevoegen onder Tekst rechts of kies een voorinstelling zoals Eenvoudig, Titel of Lower third.'],
 ['Tijd en positie aanpassen', 'Elk element krijgt een clip op de tijdlijn. Sleep dit om de weergavetijd te wijzigen. Selecteer het voor de eigenschappen rechts. Geometrie biedt numerieke instellingen voor positie, breedte, hoogte, rotatie en spiegelen.'] ], tip: 'Selectie toont de elementeigenschappen rechts. Esc heft de selectie op en herstelt Video-eigenschappen.' },
 reframe: { title: 'Van horizontale naar verticale video', short: null, summary: 'Wijzig de beeldverhouding in Video-eigenschappen. Clips volgen het canvas naar verhouding.', keywords: 'verticaal horizontaal verhouding 9:16 1:1 4:3 16:9 canvas compositie reframe vertical aspect', steps: [
 ['Video-eigenschappen openen', 'Druk op Esc om de clipselectie op te heffen en open Eigenschappen rechts. Dit toont nu Video-eigenschappen.'],
 ['Een andere beeldverhouding kiezen', 'Beeldverhouding biedt 16:9, 9:16, 1:1 en 4:3. De korte zijde blijft gelijk. Clips worden naar verhouding verplaatst en geschaald met het canvas; beeldvullende clips blijven beeldvullend en vergrendelde clips blijven behouden.'],
 ['Compositie per clip aanpassen', 'Selecteer een clip dat een nieuwe compositie nodig heeft en wijzig positie en grootte bij Geometrie in zijn eigenschappen.'] ], tip: 'De beeldverhouding wijzigen is een gewone bewerking die je kunt terugdraaien (⌘Z / Ctrl+Z). Slim bijsnijden met automatische onderwerpdetectie is hier niet beschikbaar; pas de compositie zelf aan.' },
 aitools: { title: 'Agent je transcriptie laten ordenen', short: null, summary: 'Verbeteren, hoofdstukken, sprekers, knipsuggesties, vertaling, nasynchronisatie en schrijven starten via / in een sessie of de knop in het bijbehorende paneel. Standaard voert Agent dit uit.', keywords: 'AI tools slash verbeteren alinea hoofdstuk spreker stopwoord stilte opnieuw transcriberen verouderde vertaling nasynchronisatie samenvatting blog titel beschrijving omslag polish chapters speakers cleanup', steps: [
 ['/ invoeren in de sessie', 'Voer / aan het begin van het invoerveld in of kies Tool gebruiken via + om beschikbare tools voor deze video te zien: Transcript verbeteren, Hoofdstukken genereren, Sprekers identificeren, Opnieuw transcriberen, Knipsuggesties zoeken, Ondertitels vertalen, Verouderde vertalingen bijwerken, Vertalen en nasynchroniseren, Samenvatting schrijven, Blog schrijven, Titels voorstellen, Beschrijving schrijven, Omslag maken en Exporteren. Kies er een, voeg je eisen toe en verstuur; Agent begint. Voor video’s geopend vanuit Space staat de sessie rechtsonder. Deze tools zijn niet beschikbaar op het web.'],
 ['Of vanuit het bijbehorende paneel openen', 'Transcript ordenen rechtsboven in het transcriptpaneel bevat Opnieuw transcriberen, Transcript verbeteren, Hoofdstukken genereren en Sprekers identificeren, plus schrijven vanuit de transcriptie: samenvatting, blog, titels, beschrijving en omslag. De hintbalk in knipmodus biedt Knipsuggesties zoeken. Open een tool, kies bereik en opties en kies Aan Agent overlaten om de opdracht direct naar het videosessie te sturen. Ondertitels vertalen staat bij + Vertalen naar… in het ondertitelpaneel. Vertalen en nasynchroniseren staat in het audiopaneel en nasynchronisatiespoormenu. Deze twee starten rechtstreeks vanuit hun instellingen met een gekozen model.'],
 ['Resultaten controleren', 'Elke Agent-wijziging aan de video geeft een wijzigingskaart in de sessie met direct ongedaan maken. Verbeter eerst de transcriptie en genereer daarna hoofdstukken uit de alinea’s. Schrijf- en publicatieresultaten lees, kies en kopieer je in de sessie; ze wijzigen de transcriptie niet. Gebruik na bronwijzigingen Verouderde vertalingen bijwerken om alleen de gemarkeerde zinnen opnieuw te vertalen.'] ], tip: 'Beschrijf werk buiten de lijst direct in één zin in de sessie. Slim bijsnijden en Korte video’s maken zijn in deze versie nog niet beschikbaar.' },
 agent: { title: 'Agent laten helpen met video’s', short: null, summary: 'Beschrijf je doel in één zin, volg de stappen en controleer het resultaat.', keywords: 'AI assistent agent sessie automatisch goedkeuring toestemming ongedaan codex claude agent', steps: [
 ['Eerst een Agent verbinden', 'Open Instellingen › Agentaanbieders. BaoCut controleert Claude Code en Codex op deze computer. Volg voor ontbrekende installaties de stappen op de kaart, log in en controleer hier opnieuw.'],
 ['Je doel beschrijven in de sessie', 'Start een sessie op Home of open een video in Space. Rechtsonder staat een standaard geopend zwevend sessie. Na minimaliseren kun je dit via het pictogram rechtsonder weer openen. Beschrijf bereik en wat behouden moet blijven, bijvoorbeeld: ‘Controleer de ondertitelspelling van dit interview en behoud de spreektaal.’'],
 ['Proces volgen en resultaat controleren', 'Je kunt elke Agent-stap uitklappen. Afhankelijk van de toegangsmodus wordt vóór opdrachten of wijzigingen om toestaan of weigeren gevraagd. Elke videowijziging geeft een kaart in de sessie met direct ongedaan maken.'] ], tip: 'Agent kan alleen video’s in de sessiemap gebruiken: de projectmap of de eigen werkmap van de sessie. Bij versturen worden geschikte video’s die in de editor openstaan met selectie en afspeelkop meegestuurd. Je kunt de verwijzing boven het invoerveld verwijderen.', cta: 'Agent-instellingen openen' },
 missing: { title: 'Waarom zie ik geen ondertitels in beeld?', short: null, summary: 'Controleer achtereenvolgens plaatsing op de tijdlijn, afspeelpositie en sporenchakelaars.', keywords: 'onzichtbaar verdwenen verborgen uitgeschakeld leeg ondertitel transcriptie', steps: [
 ['Controleren of ondertitels op de tijdlijn staan', 'Transcripties via Agent of de opdrachtregel slaan alleen het document op en wijzigen de tijdlijn niet. Open Ondertitels rechts. Als Nog geen ondertitels verschijnt, kies Ondertitels genereren of importeer een ondertitelbestand. Je kunt ook Agent vragen de transcriptieresultaten op de tijdlijn te plaatsen.'],
 ['Naar een gesproken zin gaan', 'Klik op de tijd van een zin in Ondertitels om de afspeelkop daarheen te verplaatsen. Stiltes hebben vanzelf geen ondertitels.'],
 ['Spoor- en clipschakelaars controleren', 'Bekijk de kop van de ondertitelspoor. Een uitgeschakeld oogpictogram verbergt de spoor in het voorbeeld. Uitgeschakelde clips worden ook overgeslagen. Rechtsklik en kies Dit clip inschakelen.'] ], tip: 'Nog steeds niets zichtbaar? Selecteer de ondertitels en controleer positie en kleur in Ondertiteleigenschappen. Tekst kan buiten beeld staan of te weinig van de achtergrond verschillen.', cta: 'Ondertitelpaneel controleren' },
 model: { title: 'Transcriptie of generatie start niet. Wat nu?', short: null, summary: 'Bekijk eerst de oorzaak bij achtergrondtaken en voeg ontbrekende modeldiensten toe.', keywords: 'mislukt fout transcriptie transcriberen spraaksynthese afbeeldingsgeneratie model dienst component netwerk taak model', steps: [
 ['Achtergrondtaken openen', 'Achtergrondtaken links toont alle taken van editor, startpagina, Agent en opdrachtregel. Open Details van de taak. Bij mislukken vermeldt de titel van het rode vak de oorzaak.'],
 ['De aangegeven oplossing volgen', 'De details geven een volgende stap passend bij de oorzaak, zoals componenten installeren, cloudmodellen instellen, een standaardmodel kiezen of Agent-instellingen controleren.'],
 ['Teruggaan en opnieuw proberen', 'Ga na herstel terug en probeer opnieuw. Kies Ondertitels genereren in het ondertitelpaneel of laat Agent de taak opnieuw indienen. Als geen dienst beschikbaar is, legt Agent eerst uit welke dienst moet worden ingeschakeld.'] ], tip: 'Transcriptie, spraaksynthese en afbeeldingsgeneratie vereisen modeldiensten. Het helpcentrum is offline leesbaar; clouddiensten vereisen internet.', cta: 'Modellen bekijken' },
} };
