import type { LegacyImportRunMessages } from './legacy-import-run.ts';

export const vi: LegacyImportRunMessages = {
  offlineTitle: (name) => `Ổ “${name}” chưa được kết nối`,
  offlineWhy: (n, root) =>
    `Video mà ${n === 1 ? 'dự án này' : `${n} dự án này`} dùng nằm trên ổ này (${root}), hiện không đọc được.`,
  offlineFix:
    'Kết nối ổ rồi nhấp “Thử lại”. Nếu để nguyên, BaoCut sẽ thử lại ở lần khởi động sau. Nếu không cần tư liệu nữa, nhấp “Bỏ qua” để không nhập.',
  offlineShort: (n, name) => `${n} dự án có tư liệu trên “${name}” chưa được kết nối`,
  missingTitle: 'Tệp tư liệu không còn ở chỗ cũ',
  missingWhy: 'Các tệp mà dự án dùng đã bị chuyển, đổi tên hoặc xóa, nên đường dẫn lưu trong dự án cũ không tìm thấy chúng nữa.',
  missingFix: 'Đặt các tệp về chỗ cũ rồi nhấp “Thử lại”. Nếu không lấy lại được, nhấp “Bỏ qua”.',
  missingShort: (n) => `${n} dự án không tìm thấy tệp tư liệu`,
  unreadableTitle: 'Không đọc được tệp dự án cũ',
  unreadableWhy: 'Tệp dự án cũ có thể đã bị hỏng, nên thử lại nhiều khả năng cũng không được.',
  unreadableFix:
    'Hiện tệp trong thư mục để kiểm tra tệp gốc còn ở đó không và có mở được bằng phiên bản cũ không. Nếu không cần, nhấp “Bỏ qua”.',
  unreadableShort: (n) => `${n} tệp dự án không đọc được`,
  failedTitle: 'Việc nhập dừng giữa chừng',
  failedWhy: 'Đã đọc được dự án nhưng việc nhập dừng giữa chừng. Báo cáo nhập ghi lại những gì đã xảy ra.',
  failedFix: 'Nhấp “Thử lại” để thử lần nữa. Nếu vẫn lỗi, hãy hiện báo cáo trong thư mục. Nếu không cần dự án, nhấp “Bỏ qua”.',
  failedShort: (n) => `${n} dự án bị dừng giữa chừng khi nhập`,
  missingMany: (n, first) => `Thiếu ${n} tệp, ví dụ ${first}`,
  missingOne: (file) => `Thiếu ${file}`,
  missingNone: 'Không tìm thấy tệp tư liệu',
  failedReport: (report) => `Báo cáo nhập: ${report}`,
  failedNoReport: 'Không có báo cáo nhập nào được ghi',
  note: (parts) => `${parts.join('; ')}.`,
  hintOffline: (name) =>
    `Kết nối “${name}” rồi nhấp “Thử lại tất cả”. Nếu để nguyên, BaoCut sẽ thử lại ở lần khởi động sau. Để xử lý từng dự án, hãy mở chi tiết.`,
  hintOther: 'Lý do và cách xử lý từng dự án có trong chi tiết. Có thể bỏ qua những dự án không cần.',
  subProgress: (done, total) => `Đã nhập ${done}/${total}`,
  subImported: (n) => `Đã nhập ${n}`,
  subPending: (n) => `Cần xử lý ${n}`,
  subSkipped: (n) => `Đã bỏ qua ${n}`,
  subDest: (dest) => `Nhập vào ${dest}`,
  attention: (n) => `${n} cần xử lý`,
  phaseImporting: 'Đang nhập',
  phaseWaiting: 'Đang chờ tác vụ khác',
  detailImporting: (title) => `Đang nhập “${title}”`,
  detailWaiting: 'Có tác vụ khác đang chạy nên việc nhập tạm dừng. Việc nhập sẽ tự tiếp tục khi chúng xong.',
  bannerRunning: (done, total) => `Đang nhập dự án cũ · ${done}/${total}`,
  bannerResult: (imported, pending) => `Đã nhập xong dự án cũ: ${imported} đã nhập, ${pending} không nhập được`,
  doneAll: (n) => `Đã nhập ${n} dự án cũ`,
  doneSome: (imported, pending) => `Nhập xong: ${imported} đã nhập, ${pending} không nhập được`,
  retriedAll: (n) => (n === 1 ? 'Dự án thử lại đã được nhập' : `Cả ${n} dự án thử lại đều đã được nhập`),
  retriedSome: (n, ok) => `Trong ${n} dự án thử lại, ${ok} đã nhập, ${n - ok} vẫn không nhập được`,
  retriedNone: (n) => (n === 1 ? 'Dự án thử lại vẫn không nhập được' : `${n} dự án thử lại vẫn không nhập được`),
  retrying: (n) => `Đang nhập lại ${n} dự án`,
  skipped: (n) => `Đã bỏ qua ${n} dự án. Sẽ không tự động nhập.`,
  actionFailed: (message) => `Không thực hiện được: ${message}`,
  undo: 'Hoàn tác',
  viewReasons: 'Xem lý do',
  viewInSpace: 'Xem trong Space',
  viewProgress: 'Xem tiến độ',
  close: 'Đóng',
  retryAll: 'Thử lại tất cả',
  skipAll: 'Bỏ qua tất cả',
  retry: 'Thử lại',
  skip: 'Bỏ qua',
  reveal: 'Hiện trong thư mục',
  importInstead: 'Nhập',
  statImported: 'Đã nhập',
  statPending: 'Không nhập được',
  statSkipped: 'Đã bỏ qua',
  statLive: 'Chưa nhập',
  pendingSection: 'Dự án không nhập được',
  pendingHint: 'Nếu để nguyên, BaoCut sẽ thử lại ở lần khởi động sau. Dự án đã bỏ qua sẽ không được nhập.',
  howTo: 'Cách xử lý: ',
  groupTitle: (title, n) => `${title} · ${n}`,
  liveSection: 'Đang nhập',
  importingChip: 'Đang nhập',
  queuedChip: 'Đang chờ',
  importedSection: 'Đã nhập',
  skippedSection: 'Đã bỏ qua',
  skippedHint: 'Sẽ không tự động nhập. Tệp gốc vẫn ở nguyên chỗ cũ.',
  expand: (n) => `Hiện thêm ${n}`,
  collapse: 'Thu gọn',
};
