import type { LegacyImportRunMessages } from './legacy-import-run.ts';

export const zhHant: LegacyImportRunMessages = {
  offlineTitle: (name) => `外接磁碟「${name}」未連接`,
  offlineWhy: (n, root) => `${n === 1 ? '這個專案' : `這 ${n} 個專案`}用到的影片在這個磁碟上（${root}），目前讀取不到。`,
  offlineFix: '連接磁碟後點選「重試」。不處理的話，下次啟動 BaoCut 會自動再試；素材不需要了就點選「略過」，以後不再匯入。',
  offlineShort: (n, name) => `${n} 個專案的素材在未連接的「${name}」上`,
  missingTitle: '素材檔案不在原本的位置',
  missingWhy: '專案用到的檔案被移動、重新命名或刪除了，舊專案裡記錄的路徑找不到它們。',
  missingFix: '把檔案放回原本的位置後點選「重試」；找不回來就點選「略過」。',
  missingShort: (n) => `${n} 個專案的素材檔案找不到`,
  unreadableTitle: '舊專案檔案無法讀取',
  unreadableWhy: '舊專案檔案可能已損壞，重試多半還是不行。',
  unreadableFix: '可以在資料夾中看看原檔案還在不在、能不能用舊版開啟；不需要了就點選「略過」。',
  unreadableShort: (n) => `${n} 個專案的檔案無法讀取`,
  failedTitle: '匯入到一半出錯了',
  failedWhy: '專案已讀取，但匯入到一半停了，經過記在匯入記錄裡。',
  failedFix: '點選「重試」再試一次；還是不行就在資料夾中查看匯入記錄，不需要了就點選「略過」。',
  failedShort: (n) => `${n} 個專案匯入到一半出錯`,
  missingMany: (n, first) => `缺少 ${n} 個檔案，例如 ${first}`,
  missingOne: (file) => `缺少 ${file}`,
  missingNone: '找不到素材檔案',
  failedReport: (report) => `匯入記錄：${report}`,
  failedNoReport: '沒有留下匯入記錄',
  note: (parts) => `${parts.join('，')}。`,
  hintOffline: (name) => `連接「${name}」後點選「全部重試」；不處理的話，下次啟動會自動再試。要逐個處理請到詳細資訊。`,
  hintOther: '每個專案的原因和處理方式都在詳細資訊裡；不需要的可以略過。',
  subProgress: (done, total) => `已匯入 ${done}/${total}`,
  subImported: (n) => `已匯入 ${n}`,
  subPending: (n) => `待處理 ${n}`,
  subSkipped: (n) => `已略過 ${n}`,
  subDest: (dest) => `匯入到 ${dest}`,
  attention: (n) => `${n} 個待處理`,
  phaseImporting: '匯入中',
  phaseWaiting: '等待其他任務',
  detailImporting: (title) => `正在匯入「${title}」`,
  detailWaiting: '其他任務正在執行，匯入先暫停，等它們結束後會自動繼續',
  bannerRunning: (done, total) => `正在匯入舊版專案 · ${done}/${total}`,
  bannerResult: (imported, pending) => `舊版專案匯入結束：${imported} 個已匯入，${pending} 個未匯入`,
  doneAll: (n) => `${n} 個舊版專案已匯入`,
  doneSome: (imported, pending) => `匯入結束：${imported} 個已匯入，${pending} 個未匯入`,
  retriedAll: (n) => `重試的 ${n} 個專案都已匯入`,
  retriedSome: (n, ok) => `重試的 ${n} 個中有 ${ok} 個已匯入，${n - ok} 個仍未匯入`,
  retriedNone: (n) => `重試的 ${n} 個仍未匯入`,
  retrying: (n) => `重新匯入 ${n} 個專案`,
  skipped: (n) => `已略過 ${n} 個專案，以後不再自動匯入`,
  actionFailed: (message) => `無法完成：${message}`,
  undo: '還原',
  viewReasons: '查看原因',
  viewInSpace: '在 Space 中檢視',
  viewProgress: '查看進度',
  close: '關閉',
  retryAll: '全部重試',
  skipAll: '全部略過',
  retry: '重試',
  skip: '略過',
  reveal: '在資料夾中顯示',
  importInstead: '改為匯入',
  statImported: '已匯入',
  statPending: '未匯入',
  statSkipped: '已略過',
  statLive: '尚未匯入',
  pendingSection: '未匯入的專案',
  pendingHint: '不處理的話，下次啟動會自動再試；略過的不再匯入',
  howTo: '怎麼辦：',
  groupTitle: (title, n) => `${title} · ${n} 個`,
  liveSection: '正在匯入',
  importingChip: '正在匯入',
  queuedChip: '排隊中',
  importedSection: '已匯入',
  skippedSection: '已略過',
  skippedHint: '不會再自動匯入；舊檔案仍在原處',
  expand: (n) => `展開其餘 ${n} 個`,
  collapse: '收合',
};
