import type { LegacyImportRunMessages } from './legacy-import-run.ts';

export const ja: LegacyImportRunMessages = {
  offlineTitle: (name) => `ドライブ「${name}」が接続されていません`,
  offlineWhy: (n, root) =>
    `${n === 1 ? 'このプロジェクト' : `この ${n} 件のプロジェクト`}で使う動画はこのドライブ（${root}）にあり、今は読み取れません。`,
  offlineFix:
    'ドライブを接続してから「再試行」をクリックしてください。そのままにすると、次回 BaoCut の起動時に自動でもう一度試します。素材が不要なら「スキップ」をクリックすると、今後は読み込みません。',
  offlineShort: (n, name) => `${n} 件のプロジェクトの素材が、接続されていない「${name}」にあります`,
  missingTitle: '素材ファイルが元の場所にありません',
  missingWhy: 'プロジェクトで使うファイルが移動、名前変更、または削除されたため、以前のプロジェクトに保存されたパスでは見つかりません。',
  missingFix: 'ファイルを元の場所に戻してから「再試行」をクリックしてください。戻せない場合は「スキップ」をクリックしてください。',
  missingShort: (n) => `${n} 件のプロジェクトの素材ファイルが見つかりません`,
  unreadableTitle: '以前のプロジェクトファイルを読み取れません',
  unreadableWhy: '以前のプロジェクトファイルが壊れている可能性があり、再試行してもおそらく解決しません。',
  unreadableFix:
    'フォルダで表示して、元のファイルが残っているか、以前のバージョンで開けるかを確認してください。不要なら「スキップ」をクリックしてください。',
  unreadableShort: (n) => `${n} 件のプロジェクトファイルを読み取れません`,
  failedTitle: '読み込みが途中で止まりました',
  failedWhy: 'プロジェクトは読み取れましたが、読み込みが途中で止まりました。経緯は読み込みレポートに記録されています。',
  failedFix:
    '「再試行」をクリックしてもう一度試してください。それでも失敗する場合は、フォルダでレポートを確認してください。プロジェクトが不要なら「スキップ」をクリックしてください。',
  failedShort: (n) => `${n} 件のプロジェクトの読み込みが途中で止まりました`,
  missingMany: (n, first) => `${n} 個のファイルが見つかりません（例：${first}）`,
  missingOne: (file) => `${file} が見つかりません`,
  missingNone: '素材ファイルが見つかりません',
  failedReport: (report) => `読み込みレポート：${report}`,
  failedNoReport: '読み込みレポートは作成されませんでした',
  note: (parts) => `${parts.join('。')}。`,
  hintOffline: (name) =>
    `「${name}」を接続してから「すべて再試行」をクリックしてください。そのままにすると、次回の起動時に自動でもう一度試します。1 件ずつ対処するには詳細を開いてください。`,
  hintOther: '各プロジェクトの理由と対処方法は詳細にあります。不要なものはスキップできます。',
  subProgress: (done, total) => `読み込み済み ${done}/${total}`,
  subImported: (n) => `読み込み済み ${n}`,
  subPending: (n) => `要対応 ${n}`,
  subSkipped: (n) => `スキップ済み ${n}`,
  subDest: (dest) => `読み込み先 ${dest}`,
  attention: (n) => `要対応 ${n} 件`,
  phaseImporting: '読み込み中',
  phaseWaiting: '他のタスクを待機中',
  detailImporting: (title) => `「${title}」を読み込んでいます`,
  detailWaiting: '他のタスクが実行中のため、読み込みを一時停止しています。終わると自動で再開します',
  bannerRunning: (done, total) => `以前のプロジェクトを読み込んでいます · ${done}/${total}`,
  bannerResult: (imported, pending) =>
    `以前のプロジェクトの読み込みが終わりました：${imported} 件を読み込み、${pending} 件は読み込めませんでした`,
  doneAll: (n) => `以前のプロジェクト ${n} 件を読み込みました`,
  doneSome: (imported, pending) => `読み込みが終わりました：${imported} 件を読み込み、${pending} 件は読み込めませんでした`,
  retriedAll: (n) => `再試行した ${n} 件のプロジェクトをすべて読み込みました`,
  retriedSome: (n, ok) => `再試行した ${n} 件のうち ${ok} 件を読み込み、${n - ok} 件はまだ読み込めていません`,
  retriedNone: (n) => `再試行した ${n} 件はまだ読み込めていません`,
  retrying: (n) => `${n} 件のプロジェクトをもう一度読み込んでいます`,
  skipped: (n) => `${n} 件のプロジェクトをスキップしました。今後は自動で読み込みません`,
  actionFailed: (message) => `実行できませんでした：${message}`,
  undo: '取り消す',
  viewReasons: '理由を表示',
  viewInSpace: 'Space で表示',
  viewProgress: '進行状況を表示',
  close: '閉じる',
  retryAll: 'すべて再試行',
  skipAll: 'すべてスキップ',
  retry: '再試行',
  skip: 'スキップ',
  reveal: 'フォルダで表示',
  importInstead: '読み込む',
  statImported: '読み込み済み',
  statPending: '読み込めなかった',
  statSkipped: 'スキップ済み',
  statLive: '読み込み待ち',
  pendingSection: '読み込めなかったプロジェクト',
  pendingHint: 'そのままにすると、次回の起動時に自動でもう一度試します。スキップしたものは読み込みません',
  howTo: '対処方法：',
  groupTitle: (title, n) => `${title} · ${n} 件`,
  liveSection: '読み込み中',
  importingChip: '読み込み中',
  queuedChip: '待機中',
  importedSection: '読み込み済み',
  skippedSection: 'スキップしたプロジェクト',
  skippedHint: '今後は自動で読み込みません。元のファイルはそのままの場所にあります',
  expand: (n) => `残り ${n} 件を表示`,
  collapse: '折りたたむ',
};
