import type { LibraryGlossaryMessages } from './library-glossary.ts';

export const ja: LibraryGlossaryMessages = {
  kinds: {
    transcription: { label: '文字起こし用語集', a: '正しい表記', b: 'よくある聞き間違い' },
    translation: { label: '翻訳用語集', a: '原文', b: '訳語' },
  },
  anyLanguage: '任意の言語',
  spoken: (language: string) => `${language} の音声`,
  newTranscription: '新しい文字起こし用語集',
  fieldCanonical: '正しい表記',
  fieldSource: '原文',
  fieldTarget: '訳語',
  fieldEmpty: (label: string) => `${label} は空にできません`,
  fieldTooLong: (label: string, max: number) => `${label} は ${max} 文字以内にしてください`,
  fieldNewline: (label: string) => `${label} に改行は使えません`,
  duplicate: (term: string) => `「${term}」はすでに用語集にあります`,
  misheardSame: '聞き間違いの表記を正しい表記と同じにはできません',
  misheardTooMany: (max: number) => `聞き間違いの表記は最大 ${max} 個です`,
  misheardTooLong: (max: number) => `各表記は ${max} 文字以内にしてください`,
  noteTooLong: (max: number) => `メモは ${max} 文字以内にしてください`,
  nameEmpty: '用語集の名前は空にできません',
  nameTooLong: (max: number) => `用語集の名前は ${max} 文字以内にしてください`,
  skipPunctuation: '句読点のみ',
  skipTooLong: (max: number) => `${max} 文字を超えています`,
  skipMerged: '前の行と同じ用語のため統合しました',
  skipNoTarget: '訳語がありません',
  skipKeptFirst: '前の行と同じ用語のため、最初の行を残しました',
  allExist: 'これらの用語はすでに用語集にあります',
  added: (n: number) => `${n} 件を追加しました`,
  merged: (n: number) => `${n} 件はすでに用語集にあります`,
  overflow: (n: number, limit: number) => `${n} 件は追加されませんでした：1 つの用語集に入る用語は最大 ${limit} 件です`,
  fileName: '用語集',
  misheardSeparator: '、',
};
