import type { LibraryBrandMessages } from './library-brand.ts';

export const de: LibraryBrandMessages = {
  videoTitle: "Videos",
  videoEmpty: "Noch keine gespeicherten Videos",
  videoHint: "Intros, Outros, Übergänge und weitere wiederverwendbare Videoclips.",
  imageTitle: "Bilder",
  imageEmpty: "Noch keine gespeicherten Bilder",
  imageHint: "Logos, QR-Codes, Avatare und andere häufig verwendete Bilder.",
  stickerTitle: "Sticker",
  stickerEmpty: "Noch keine hochgeladenen Sticker",
  stickerHint: "Akzeptiert Bilder (PNG, WebP, GIF, JPG) und Lottie-Animationen (.json oder .lottie). Der Typ wird am Inhalt erkannt, nicht an der Dateiendung.",
  colorTitle: "Markenfarben",
  colorEmpty: "Noch keine Markenfarben",
  colorHint: "Markenfarben erscheinen in jedem Farbwähler des Inspektors.",
  fontTitle: "Markenschriften",
  fontEmpty: "Noch keine Markenschriften",
  fontHint: "Akzeptiert TTF, OTF und WOFF2 (kein WOFF). Hinzufügen zum Video kopiert in die Materialbibliothek.",
  captionStyleTitle: "Untertitelstile",
  captionStyleEmpty: "Noch keine gespeicherten Untertitelstile",
  captionStyleHint: "Aktuellen Untertitelstil hier speichern und mit einem Klick auf andere Videos anwenden.",
  filterImages: "Bilder",
  filterVideos: "Videos",
  filterStickers: "Bilder und Lottie-Animationen",
  filterFonts: "Schriften",
  untitled: "Unbenannt",
  captionStyle: "Untertitelstil",
  lottie: "Lottie-Animation",
  image: "Bild",
  noRevision: "Dieses Material hat keine nutzbare Version",
  embedded: "Dieses Material wurde in den Videoordner kopiert; Originaldatei nicht verfügbar. Original vom Computer hinzufügen.",
  styleEmpty: "Das Untertitelstildokument ist leer",
  styleNoSchema: "Das Untertitelstildokument hat kein schema und kann nicht im Marken-Kit gespeichert werden",
  styleTooLarge: "Der Untertitelstil ist größer als 64 KiB",
};
