import type { LibraryBrandMessages } from './library-brand.ts';

export const fr: LibraryBrandMessages = {
  videoTitle: "Vidéos",
  videoEmpty: "Aucune vidéo enregistrée",
  videoHint: "Intros, fins, transitions et clips réutilisés dans chaque vidéo.",
  imageTitle: "Images",
  imageEmpty: "Aucune image enregistrée",
  imageHint: "Logos, QR codes, avatars et images fréquentes.",
  stickerTitle: "Autocollants",
  stickerEmpty: "Aucun sticker envoyé",
  stickerHint: "Images PNG, WebP, GIF, JPG et animations Lottie .json ou .lottie. Type détecté par contenu, pas extension.",
  colorTitle: "Couleurs de marque",
  colorEmpty: "Aucune couleur de marque",
  colorHint: "Couleurs de marque dans chaque sélecteur de l’Inspecteur.",
  fontTitle: "Polices de marque",
  fontEmpty: "Aucune police de marque",
  fontHint: "TTF, OTF et WOFF2, pas WOFF. Ajouter à une vidéo copie dans les médias.",
  captionStyleTitle: "Styles de sous-titres",
  captionStyleEmpty: "Aucun style de sous-titres enregistré",
  captionStyleHint: "Enregistrez le style actuel pour l’appliquer ailleurs en un clic.",
  filterImages: "Images",
  filterVideos: "Vidéos",
  filterStickers: "Images et animations Lottie",
  filterFonts: "Polices",
  untitled: "Sans titre",
  captionStyle: "Style de sous-titre",
  lottie: "Animation Lottie",
  image: "Images",
  noRevision: "Ce média n’a aucune version utilisable",
  embedded: "Ce média a déjà été copié dans le dossier vidéo ; original indisponible. Ajoutez le fichier original depuis votre ordinateur.",
  styleEmpty: "Document de style de sous-titres vide",
  styleNoSchema: "Document sans schema ; enregistrement dans le kit impossible",
  styleTooLarge: "Style de sous-titres dépassant 64 Kio",
};
