import type { LibraryBrandMessages } from './library-brand.ts';

export const ko: LibraryBrandMessages = {
  videoTitle: '영상',
  videoEmpty: '아직 저장된 영상이 없습니다',
  videoHint: '인트로, 아웃트로, 전환처럼 영상마다 쓰는 영상 소재입니다.',
  imageTitle: '이미지',
  imageEmpty: '아직 저장된 이미지가 없습니다',
  imageHint: '로고, QR 코드, 아바타처럼 자주 쓰는 이미지입니다.',
  stickerTitle: '스티커',
  stickerEmpty: '아직 업로드한 스티커가 없습니다',
  stickerHint: '이미지(PNG, WebP, GIF, JPG)와 Lottie 애니메이션(.json 또는 .lottie)을 지원합니다. 종류는 확장자가 아니라 파일 내용으로 판별합니다.',
  colorTitle: '브랜드 색상',
  colorEmpty: '아직 브랜드 색상이 없습니다',
  colorHint: '브랜드 색상은 인스펙터의 모든 색 선택기에 표시됩니다.',
  fontTitle: '브랜드 글꼴',
  fontEmpty: '아직 브랜드 글꼴이 없습니다',
  fontHint: 'TTF, OTF, WOFF2를 지원합니다(WOFF는 지원하지 않음). 영상에 추가하면 소재 라이브러리로 복사됩니다.',
  captionStyleTitle: '자막 스타일',
  captionStyleEmpty: '아직 저장된 자막 스타일이 없습니다',
  captionStyleHint: '이 영상의 현재 자막 스타일을 여기에 저장해 두면 다른 영상에 한 번에 적용할 수 있습니다.',
  filterImages: '이미지',
  filterVideos: '영상',
  filterStickers: '이미지 및 Lottie 애니메이션',
  filterFonts: '글꼴',
  untitled: '제목 없음',
  captionStyle: '자막 스타일',
  lottie: 'Lottie 애니메이션',
  image: '이미지',
  noRevision: '이 소재에는 사용할 수 있는 버전이 없습니다',
  embedded: '이 소재는 이미 영상 폴더로 복사되어 원본 파일을 사용할 수 없습니다. 컴퓨터에서 원본 파일을 추가하세요.',
  styleEmpty: '자막 스타일 문서가 비어 있습니다',
  styleNoSchema: '자막 스타일 문서에 스키마가 없어 브랜드 키트에 저장할 수 없습니다',
  styleTooLarge: '자막 스타일이 64 KiB보다 큽니다',
};
