import type { LibraryBrandMessages } from './library-brand.ts';

export const pl: LibraryBrandMessages = {
  videoTitle: "Wideo",
  videoEmpty: "Nie ma jeszcze zapisanych wideo",
  videoHint: "Wstępy, zakończenia, przejścia i inne klipy używane w każdym wideo.",
  imageTitle: "Obrazy",
  imageEmpty: "Nie ma jeszcze zapisanych obrazów",
  imageHint: "Logotypy, kody QR, awatary i inne często używane obrazy.",
  stickerTitle: "Naklejki",
  stickerEmpty: "Nie ma jeszcze przesłanych naklejek",
  stickerHint: "Obsługuje obrazy (PNG, WebP, GIF, JPG) i animacje Lottie (.json lub .lottie). Typ jest wykrywany z zawartości pliku, nie rozszerzenia.",
  colorTitle: "Kolory marki",
  colorEmpty: "Nie ma jeszcze kolorów marki",
  colorHint: "Kolory marki pojawiają się w każdym selektorze kolorów Inspektora.",
  fontTitle: "Czcionki marki",
  fontEmpty: "Nie ma jeszcze czcionek marki",
  fontHint: "Obsługuje TTF, OTF i WOFF2 (bez WOFF). Dodanie do wideo kopiuje do biblioteki materiałów.",
  captionStyleTitle: "Style napisów",
  captionStyleEmpty: "Nie ma jeszcze zapisanych stylów napisów",
  captionStyleHint: "Zapisz tutaj obecny styl napisów wideo i stosuj w innych wideo jednym kliknięciem.",
  filterImages: "Obrazy",
  filterVideos: "Wideo",
  filterStickers: "Obrazy i animacje Lottie",
  filterFonts: "Czcionki",
  untitled: "Bez tytułu",
  captionStyle: "Styl napisów",
  lottie: "Animacja Lottie",
  image: "Obraz",
  noRevision: "Ten materiał nie ma użytecznej wersji",
  embedded: "Ten materiał został już skopiowany do folderu wideo, więc oryginalny plik jest niedostępny. Dodaj oryginalny plik z komputera.",
  styleEmpty: "Dokument stylu napisów jest pusty",
  styleNoSchema: "Dokument stylu napisów nie ma schema, więc nie można go zapisać w zestawie marki",
  styleTooLarge: "Styl napisów jest większy niż 64 KiB",
};
