import type { LibraryBrandMessages } from './library-brand.ts';

export const ru: LibraryBrandMessages = {
  videoTitle: "Видео",
  videoEmpty: "Сохранённых видео пока нет",
  videoHint: "Заставки, концовки, переходы и другие видеоклипы, используемые в каждом видео.",
  imageTitle: "Изображения",
  imageEmpty: "Сохранённых изображений пока нет",
  imageHint: "Логотипы, QR-коды, аватары и другие часто используемые изображения.",
  stickerTitle: "Наклейки",
  stickerEmpty: "Загруженных стикеров пока нет",
  stickerHint: "Поддерживает изображения (PNG, WebP, GIF, JPG) и анимацию Lottie (.json или .lottie). Тип определяется по содержимому файла, а не расширению.",
  colorTitle: "Цвета бренда",
  colorEmpty: "Цветов бренда пока нет",
  colorHint: "Цвета бренда появляются во всех палитрах Инспектора.",
  fontTitle: "Шрифты бренда",
  fontEmpty: "Шрифтов бренда пока нет",
  fontHint: "Поддерживает TTF, OTF и WOFF2 (кроме WOFF). При добавлении в видео файл копируется в библиотеку материалов.",
  captionStyleTitle: "Стили субтитров",
  captionStyleEmpty: "Сохранённых стилей субтитров пока нет",
  captionStyleHint: "Сохраните здесь текущий стиль субтитров видео и применяйте к другим видео одним нажатием.",
  filterImages: "Изображения",
  filterVideos: "Видео",
  filterStickers: "Изображения и анимация Lottie",
  filterFonts: "Шрифты",
  untitled: "Без названия",
  captionStyle: "Стиль субтитров",
  lottie: "Анимация Lottie",
  image: "Изображение",
  noRevision: "У этого материала нет пригодной версии",
  embedded: "Материал уже скопирован в папку видео, поэтому исходный файл недоступен. Добавьте исходный файл с компьютера.",
  styleEmpty: "Документ стиля субтитров пуст",
  styleNoSchema: "У документа стиля субтитров нет schema, его нельзя сохранить в бренд-кит",
  styleTooLarge: "Стиль субтитров превышает 64 КиБ",
};
