import type { LinkImportMessages } from './link-import-copy.ts';

export const zhHans: LinkImportMessages = {
  title: (name: string | null) => (name ? `从链接导入 · ${name}` : '从链接导入'),

  phase: {
    starting: '准备中',
    probing: '解析链接',
    downloading: '下载视频',
    validating: '确认文件能播放',
    publishing: '放进下载目录',
    applying: '导入视频',
    transcribing: '提交转录',
  },
  phaseFallback: '处理中',
  downloaded: (bytes: string) => `已下载 ${bytes}`,

  stageDownload: '下载视频',
  stageVideo: '确认媒体并建视频',
  stageSubs: '生成字幕',

  issue: {
    TOOL_NOT_INSTALLED: {
      title: '准备一次，以后直接粘贴',
      body: 'BaoCut 需要视频下载工具 yt-dlp 来读取这个网站。装好之后重新开始这次导入。',
    },
    TOOL_CONSENT_REQUIRED: { title: '使用下载工具之前要你同意', body: '下载工具已经在这台电脑上，同意之后才会用它从网站下载视频。' },
    TOOL_UNAVAILABLE: { title: '下载工具不能运行', body: '找到了下载工具，但它运行不了。重新安装或指定一份能用的。' },
    TOOL_OUTDATED: { title: '下载工具需要更新', body: '版本太旧，可能读不了这个网站。更新之后再试一次。' },
    OFFLINE_STRICT: { title: '严格离线模式下不能从链接下载', body: '严格离线时 BaoCut 不联网。先在浏览器里把视频下载好，再选本地文件。' },
    LINK_UNSUPPORTED: {
      title: '还不支持这个来源',
      body: '下载工具认不出这个网站或页面。换成视频页面本身的链接（不是播放列表、直播或搜索页），或改用本地文件。',
    },
    LINK_LOGIN_REQUIRED: {
      title: '这个视频需要登录才能看',
      body: '先在浏览器登录目标网站，再回到下载视频，在「网站登录」里勾选该浏览器后重新下载。',
    },
    LINK_COOKIES_UNAVAILABLE: {
      title: '浏览器 Cookie 读取失败',
      body: '确认浏览器已登录；数据库被占用时完全退出浏览器（包括在后台运行的），检查系统密钥权限（Safari 要在完全磁盘访问权限里允许 BaoCut）。Windows 上 Chrome、Edge、Brave 用应用绑定加密保护 Cookie 时读不到，改勾 Firefox。或勾选别的浏览器后重新下载。',
    },
    LINK_TOOL_UPDATE_REQUIRED: { title: '需要更新 yt-dlp', body: '网站解析方式已变化。按原安装方式更新 yt-dlp，重新检测后重试。' },
    LINK_UNAVAILABLE: {
      title: '这个视频不可用',
      body: '视频可能已删除、有地区限制，或没有可下载的格式。换个链接或改用本地文件。',
    },
    LINK_NETWORK_ERROR: { title: '连接中断了', body: '检查网络后重试；已经下载的部分会续传。' },
    LINK_DISK_FULL: { title: '磁盘空间不够', body: '下载目录所在的磁盘满了。清理出空间后重试。' },
    LINK_DOWNLOAD_FAILED: {
      title: '下载工具报错了',
      body: '可能是网站改版或临时限制。先重试；仍失败时检查下载工具有没有更新，或改用本地文件。',
    },
    LINK_DOWNLOAD_UNREADABLE: {
      title: '下载到的文件不能用',
      body: '文件不完整、没有音轨，或格式解不开，可能是网站给了占位内容。重新下载一次，或换个链接、改用本地文件。',
    },
    LINK_DESTINATION_UNAVAILABLE: {
      title: '下载目录不能写入',
      body: '检查下载目录是否存在、可写；换一个目录之后重新开始导入。',
    },
    MEDIA_TOOL_UNAVAILABLE: {
      title: '没法检查下载的文件',
      body: '确认媒体要用 ffprobe（随 ffmpeg 一起），这台电脑上找不到。装好 ffmpeg 之后重试。',
    },
    LINK_SOURCE_EXPIRED: {
      title: '原始链接已经不在了',
      body: 'Runtime 重启后不再保留完整链接（只留脱敏后的）。粘贴链接重新开始一次导入。',
    },
    INTERRUPTED: { title: '导入中断了', body: 'Runtime 停止或重启时还没做完。重试会从停下的那一步接着做。' },
  },
  issueUnknownTitle: '导入没有完成',
  issueUnknownBody: (message: string | null, remedy: string | null) => [message, remedy].filter(Boolean).join('。') || '流程出错了。',

  headingStopped: '导入已停止',
  headingFailed: '导入没有完成',
  headingRunning: '把这条链接变成可编辑的视频',
  headingDownloaded: '视频已下载',
  headingVideoFailed: '文件已下载，视频没建成',
  headingCreatingVideo: '文件已下载，正在新建视频',
  headingTranscribing: '视频已就绪，正在生成字幕',
  headingTranscribeFailed: '视频已就绪，转录需要处理',
  headingReady: '视频已就绪',
  headingSubsReady: '字幕准备好了',

  toolSource: {
    system: '系统里装的',
    user: '你指定的',
    managed: 'BaoCut 下载的',
    env: '环境变量指定的',
  },
  factVersion: (version: string, size: string | null) => `版本 ${version}${size ? ` · 约 ${size}` : ''}`,
  factFrom: (host: string) => `从 ${host} 下载`,
  factLicense: (license: string) => `${license} 许可`,
  factIsolated: '放在 BaoCut 自己的目录里，校验摘要后才运行，不改系统',
  factInstalledWith: (method: string) => `${method} 安装`,

  cardChecking: '正在检查下载工具…',
  cardCheckingBody: '只在本机看一眼版本，不联网。',
  cardUnknown: '没找到下载工具的登记',
  cardUnknownBody: '这个 Runtime 不认识 yt-dlp，暂时不能从链接导入。',
  cardInstalling: '正在准备下载工具…',
  cardInstallingBody: '下载 → 校验 → 试运行，完成后这里会变成「已就绪」。',
  cardUpdating: '正在更新下载工具…',
  cardUpdatingBody: '输出显示在命令下面，完成后会重新检测版本。',
  cardBlockedWhy: '这台电脑上 BaoCut 不能替你下载它。',
  cardMissing: '下载工具还没装',
  cardMissingBody: (why: string) => `${why}可以自己装好 yt-dlp，再点「重新检测」或指定它的位置。`,
  cardInstall: '准备一次，以后直接粘贴',
  cardInstallBody: 'BaoCut 需要视频下载工具 yt-dlp 来读取视频网站。同意后下载并记下你的同意，之后从链接导入不再问。',
  cardInstallAction: '同意并安装',
  cardOutdatedReason: (reason: string | null, version: string | null, minVersion: string | null) =>
    `${reason ?? `版本 ${version ?? '未知'} 低于需要的 ${minVersion ?? ''}`}。`,
  cardOutdated: '下载工具需要更新',
  cardOutdatedBlocked: (reason: string, why: string) => `${reason}${why}`,
  cardOutdatedRunnable: '它不是 BaoCut 下载的，可以用下面这条命令按原安装方式更新。',
  cardOutdatedManual: '它不是 BaoCut 下载的，请按下面的说明在终端里更新，再点「重新检测」。',
  cardOutdatedUpdate: (reason: string) => `${reason}更新后才能开始。`,
  cardUpdateAction: '同意并更新',
  cardBroken: '下载工具不能运行',
  cardBrokenBody: (reason: string | null, remedy: string | null) => [reason, remedy].filter(Boolean).join('。') || '找到了，但运行不了。',
  cardReinstallAction: '同意并重新安装',
  cardConsentRevoked: '你撤回过对下载工具的同意',
  cardConsent: '使用下载工具之前要你同意',
  cardConsentBody: 'BaoCut 只在你同意之后用它从网站下载视频；同意会记在 Runtime 里，之后从链接导入不再问。',
  cardConsentAction: '同意使用',
  cardReady: '下载工具已就绪',
  cardReadyBody: '开始后先检查链接、获取视频信息，再下载。',
};
