import type { ModelsDirMessages } from './models-dir-copy.ts';
import { pluralForm } from '@baocut/protocol';

const and = (items: readonly string[]) => new Intl.ListFormat('it', { type: 'conjunction' }).format(items);
const models = (n: number) => pluralForm('it', n, { one: `${n} modello`, other: `${n} modelli` });
const capitalize = (text: string) => text.charAt(0).toUpperCase() + text.slice(1);

export const it: ModelsDirMessages = {
  dir: {
    title: 'Cartella dei modelli', defaultChip: 'Predefinita', envChip: 'Variabile d’ambiente', change: 'Cambia…', restore: 'Ripristina predefinita', envNote: 'Impostata dalla variabile d’ambiente BAOCUT_MODELS_DIR. Per cambiarla, modifica la variabile e riavvia BaoCut.',
    shareHint: 'Se altre app condividono questa cartella, eliminare qui un modello elimina i file dalla cartella e anche quelle app non li troveranno più.', blockedPrefix: 'Impossibile cambiare al momento:', viewTasks: 'Visualizza attività', changeTitle: 'Cambia cartella dei modelli', restoreTitle: 'Ripristina posizione predefinita', restoreLead: 'Riporta la cartella dei modelli a', checking: 'Verifica della cartella…', cancel: 'Annulla', howTo: 'Cosa fare con i modelli esistenti', moveOption: 'Sposta lì i modelli esistenti', switchOption: 'Cambia solo posizione', confirmMove: 'Sposta e cambia', confirmSwitch: 'Cambia posizione', movingLabel: 'Spostamento dei modelli', stayOpen: 'Non uscire da BaoCut nel frattempo',
    missingDir: 'Questa cartella non esiste (accade anche quando un’unità esterna non è collegata). I modelli funzioneranno di nuovo quando sarà collegata oppure puoi scegliere un’altra posizione.', notWritableDir: 'BaoCut non ha il permesso di scrivere in questa cartella, quindi non può scaricarvi modelli.', loading: 'Lettura della cartella dei modelli…', pickFailed: (message: string) => `Impossibile scegliere la cartella: ${message}`, same: 'È già la cartella dei modelli attuale',
  },
  stats: (used: string, free: string | null, count: number) => [`${used} in uso`, ...(free !== null ? [`${free} liberi su disco`] : []), `${models(count)} trovati`].join(' · '),
  blocker: (downloading: readonly string[], testing: readonly string[], tasks: number) => { const parts: string[] = []; if (downloading.length) parts.push(`download di ${and(downloading)}`); if (testing.length) parts.push(`verifica di ${and(testing)}`); if (tasks) parts.push(pluralForm('it', tasks, { one: `${tasks} attività sta usando modelli locali`, other: `${tasks} attività stanno usando modelli locali` })); return `${capitalize(parts.join('; '))}. Attendi il completamento prima di cambiare, altrimenti i file verrebbero spostati durante l’uso.`; },
  missingTitle: 'Impossibile trovare questa cartella', missingText: 'Questa cartella non esiste. Accade anche quando un’unità esterna non è collegata; collegala e scegli di nuovo.', notWritableTitle: 'Questa cartella non è scrivibile', notWritableText: 'BaoCut non ha il permesso di scrivere in questa cartella, quindi non può scaricarvi modelli. Scegli una posizione scrivibile o cambia prima i permessi.', nestedTitle: 'Impossibile usare questa posizione', nestedText: 'La nuova posizione e la cartella dei modelli attuale si contengono a vicenda (una è dentro l’altra). Scegli una cartella che non sia al suo interno e non la contenga.',
  found: (count: number, bytes: string, free: string | null) => `${count ? pluralForm('it', count, { one: `${count} modello scaricato trovato (${bytes}), pronto all’uso.`, other: `${count} modelli scaricati trovati (${bytes}), pronti all’uso.` }) : 'Non ci sono ancora modelli in questa cartella. I modelli che scaricherai in seguito andranno qui.'}${free !== null ? ` ${free} liberi su disco.` : ''}`,
  moveNoFit: (required: string, free: string, short: string) => `Lo spostamento richiede ${required}, ma l’unità di destinazione ha solo ${free} liberi (mancano ${short}). Non c’è spazio sufficiente.`, moveSameVolume: (size: string) => `Sposta ${size} sulla stessa unità, quindi è rapido. I file non rimarranno nella vecchia posizione.`, moveOther: (size: string) => `Sposta ${size}. I file non rimarranno nella vecchia posizione.`,
  switchDescription: (count: number) => `I file nella vecchia posizione vengono conservati, senza eliminarli. Si possono usare solo ${count ? `${models(count)} ` : 'i modelli '}già nella nuova posizione; gli altri appaiono come non installati.`,
  appliedMoving: (where: string) => `Spostamento dei modelli in ${where} avviato`, appliedKept: (where: string) => `Cartella dei modelli cambiata in ${where} · File nella vecchia posizione conservati`, applied: (where: string) => `Cartella dei modelli cambiata in ${where}`,
  moveWaiting: (to: string | null) => `In attesa di iniziare lo spostamento${to ? ` in ${to}` : ''}…`, moveValidating: (amount: string | null) => `Verifica dei file copiati${amount ? ` (${amount})` : ''}…`, movePublishing: 'Completamento dello spostamento…', moving: (amount: string | null, to: string | null) => `Spostamento${amount ? ` di ${amount}` : ''}${to ? ` in ${to}` : ''}…`,
};
