import type { ModelsLocalMessages } from './models-local-copy.ts';

export const ru: ModelsLocalMessages = {
  reason: {
    unsupported: "Не поддерживается на этом компьютере",
    resource: "Отключено",
    'worker-missing': "Отсутствует Model Worker",
    'missing-manifest': "Отсутствует манифест",
    'missing-file': "Отсутствуют файлы",
    'size-mismatch': "Несовпадение размера файла",
    'hash-mismatch': "Несовпадение контрольной суммы",
    incomplete: "Отсутствуют компоненты",
    'load-failed': "Не удалось загрузить",
    relocating: "Перемещение",
  },
  chipDefault: "По умолчанию",
  chipLoading: "Загрузка",
  chipReady: "Загружено",
  chipBusy: "Выполняется",
  chipUnloading: "Выгрузка",
  chipUnavailable: "Недоступно",
  chipMissing: (names) => `Не хватает: ${names.join(', ')}`,
  capability: {
    transcribe: "Расшифровать",
    align: "Выравнивание",
    synthesize: "Синтезировать",
    image: "Изображение",
    separate: "Разделение",
    diarize: "Разделение говорящих",
  },
  auto: "Автоматически",
  notInstalled: (name) => `${name} (не установлено)`,
  componentName: { aligner: "Принудительное выравнивание", speaker: "Эмбеддинг говорящего", vad: "VAD (обнаружение голосовой активности)", tokenizer: "Токенизатор", segmentation: "Сегментация говорящих", codec: "Речевой кодек", aux: "Вспомогательные модели" },
  componentDesc: { vad: "Находит участки, где кто-то говорит", aligner: "Привязывает текст ко времени каждого слова", tokenizer: "Переводит текст в токены модели и обратно", speaker: "Различает говорящих", segmentation: "Находит, где каждый говорящий начинает и заканчивает речь", codec: "Превращает акустические токены обратно в звуковую волну", aux: "Дополнительные модели, нужные основной модели" },
  weights: "Веса модели",
};
