import type { ServicesMcpMessages } from './services-mcp-copy.ts';

export const ja: ServicesMcpMessages = {
  levels: {
    read: { title: '読み取りのみ', desc: '動画の情報、文字起こし、処理状況を表示します' },
    ask: { title: '変更前に確認', desc: '文字起こし、編集、書き出し、生成の前に BaoCut で確認します' },
    auto: { title: '確認せずに許可', desc: '書き込み、タスク、生成を確認なしですぐに実行します。ご自身だけが使う場合に適しています' },
  },
  scopeAll: (total) => `すべての動画（${total}）`,
  scopeNone: '公開している動画はありません',
  scopeOne: (name) => `「${name}」`,
  scopeSome: (n) => `選択した動画 ${n} 本`,
  access: (level) => `${level} · トークンが必要`,
  subOn: (scope, access) => `${scope} · ${access}`,
  subOff: (scope, access) => `起動時：${scope} · ${access}`,
  groups: {
    read: { label: '読み取り', hint: '読み取りのみ。動画は変更せず、すぐに応答します' },
    edit: { label: '編集', hint: '動画に書き込みます。呼び出しごとに、取り消せる 1 ステップになります' },
    job: { label: 'タスク', hint: '時間のかかる処理です。すぐにタスク ID を返します。進行状況と結果は jobs_inspect で確認します' },
    generate: { label: '生成', hint: 'テキストから音声を合成し、プロンプトから画像を作成します。動画は不要です' },
  },
  tools: {
    videos_list: '動画を一覧表示',
    videos_create: '動画を作成',
    videos_inspect: '動画の詳細を表示',
    documents_read: 'ドキュメントを読み取る',
    edits_apply: '動画を編集',
    edits_undo: '編集を取り消す',
    captions_create: '字幕レイヤーを作成',
    videos_frames: '動画のフレームを取得',
    videos_history: '編集履歴を表示',
    documents_put: 'ドキュメントを書き込む',
    assets_import: '素材を読み込む',
    compositions_import: 'モーショングラフィックを読み込む',
    compositions_preview: 'モーショングラフィックをプレビュー',
    assets_prune: '未使用の素材を整理',
    chapters_adopt: '配信元のチャプターを採用',
    edits_ops: '編集操作を表示',
    models_capabilities: 'モデルの機能を表示',
    models_list: 'ローカルのモデルパッケージを一覧表示',
    transcribe: '文字起こし',
    translate: '翻訳',
    dub: '翻訳して吹き替え',
    speak: '音声を合成',
    image: '画像を生成',
    jobs_inspect: 'タスクを確認',
    jobs_wait: 'タスクを待機',
    jobs_list: 'タスクを一覧表示',
    jobs_cancel: 'タスクをキャンセル',
    jobs_retry: '失敗したパイプラインを再試行',
    export: '書き出す',
    space_list: 'Space の項目を一覧表示',
    space_search: '動画をまたいで文字起こしを検索',
    projects_list: 'プロジェクトを一覧表示',
    skills_list: 'Skill を一覧表示',
    skills_read: 'Skill を読み取る',
    library_list: 'ライブラリを一覧表示',
    library_show: 'ライブラリの項目を表示',
    download: 'リンクからダウンロード',
  },
  gates: {
    answer: 'そのまま応答',
    auto: 'そのまま実行',
    ask: '呼び出し前に確認',
    hidden: '読み取りのみの権限では提供しません',
  },
  toolsSummary: (exposed, total, ask, writes) => {
    const tail = ask ? ` · ${ask} 個は呼び出し前に確認` : writes ? ' · 確認は不要' : ' · すべて読み取りのみ';
    return `${total} 個中 ${exposed} 個のツールを提供${tail}`;
  },
  outcomes: {
    ok: '成功',
    denied: '許可されていません',
    videoNotFound: '動画が範囲外です',
    unknownTool: '提供されていないツール',
  },
  requestLine: (tool, video) => `${tool} · 「${video}」`,
  joinKinds: (labels) => labels.join('、'),
  grantLine: (kinds, recipient, purpose, estimate) =>
    `${kinds}${/[A-Za-z0-9]$/.test(kinds) ? ' ' : ''}を ${recipient} に送信します（${purpose}）${estimate ? ` · 約 ${estimate.amount} ${estimate.currency}` : ''}`,
};
