import type { ServicesMcpMessages } from './services-mcp-copy.ts';

export const pl: ServicesMcpMessages = {
  levels: {
    read: { title: "Tylko do odczytu", desc: "Zobacz informacje o wideo, transkrypcje i stan przetwarzania" },
    ask: { title: "Pytaj przed zmianami", desc: "Potwierdź w BaoCut przed transkrypcją, edycją, eksportem lub generowaniem" },
    auto: { title: "Zezwalaj bez pytania", desc: "Zapis, zadania i generowanie ruszają od razu bez potwierdzenia; najlepiej do własnego użytku" },
  },
  scopeAll: (total) => `Wszystkie wideo (${total})`,
  scopeNone: "Nie udostępniono wideo",
  scopeOne: (name) => `„${name}”`,
  scopeSome: (n) => `${n} wybranych wideo`,
  access: (level) => `${level} · Wymagany token`,
  subOn: (scope, access) => `${scope} · ${access}`,
  subOff: (scope, access) => `Po uruchomieniu: ${scope} · ${access}`,
  groups: {
    read: { label: "Odczyt", hint: "Tylko odczyt; nie zmienia wideo, odpowiada od razu" },
    edit: { label: "Edytuj", hint: "Zapisuje w wideo; każde wywołanie to jeden krok możliwy do cofnięcia" },
    job: { label: "Zadania", hint: "Długie zadanie; od razu zwraca ID. Użyj jobs_inspect dla postępu i wyników" },
    generate: { label: "Wygeneruj", hint: "Syntezuje mowę z tekstu i tworzy obrazy z promptów; wideo niepotrzebne" },
  },
  tools: {
    videos_list: "Wyświetl wideo",
    videos_create: "Utwórz wideo",
    videos_inspect: "Sprawdź wideo",
    documents_read: "Odczytaj dokumenty",
    edits_apply: "Edytuj wideo",
    edits_undo: "Cofnij zmiany",
    captions_create: "Utwórz warstwę napisów",
    videos_frames: "Pobierz klatki wideo",
    videos_history: "Zobacz historię zmian",
    documents_put: "Zapisz dokument",
    assets_import: "Importuj materiały",
    compositions_import: "Importuj grafikę animowaną",
    compositions_preview: "Podgląd grafiki animowanej",
    assets_prune: "Usuń nieużywane materiały",
    chapters_adopt: "Użyj rozdziałów ze źródła",
    edits_ops: "Zobacz operacje edycji",
    models_capabilities: "Zobacz możliwości modeli",
    models_list: "Wyświetl pakiety modeli lokalnych",
    transcribe: "Transkrybuj",
    translate: "Przetłumacz",
    dub: "Przetłumacz i utwórz dubbing",
    speak: "Synteza mowy",
    image: "Generuj obraz",
    jobs_inspect: "Sprawdź zadania",
    jobs_wait: "Poczekaj na zadanie",
    jobs_list: "Wyświetl zadania",
    jobs_cancel: "Anuluj zadanie",
    jobs_retry: "Ponów nieudany potok",
    export: "Eksportuj",
    space_list: "Wyświetl elementy Space",
    space_search: "Szukaj w transkrypcjach wideo",
    projects_list: "Lista projektów",
    skills_list: "Wyświetl Skills",
    skills_read: "Odczytaj Skill",
    library_list: "Wyświetl bibliotekę",
    library_show: "Zobacz element biblioteki",
    download: "Pobierz z linku",
  },
  gates: {
    answer: "Odpowiada bezpośrednio",
    auto: "Wykonanie bezpośrednie",
    ask: "Pyta przed wywołaniem",
    hidden: "Niedostępne przy dostępie tylko do odczytu",
  },
  toolsSummary: (exposed, total, ask, writes) => {
    const tail = ask ? ` · ${ask} pytają przed wywołaniem` : writes ? " · Potwierdzenie niepotrzebne" : " · Wszystko tylko do odczytu";
    return `${exposed} z ${total} narzędzi dostępnych${tail}`;
  },
  outcomes: {
    ok: "Powodzenie",
    denied: "Niedozwolone",
    videoNotFound: "Wideo poza zakresem",
    unknownTool: "Narzędzie niedostępne",
  },
  requestLine: (tool, video) => `${tool} · „${video}”`,
  joinKinds: (labels) => labels.join(", "),
  grantLine: (kinds, recipient, purpose, estimate) => `Zostanie wysłane ${kinds} do ${recipient} (${purpose})${estimate ? ` · Około ${estimate.amount} ${estimate.currency}` : ""}`,
};
