import type { ServicesMcpMessages } from './services-mcp-copy.ts';

export const ru: ServicesMcpMessages = {
  levels: {
    read: { title: "Только чтение", desc: "Просмотр сведений о видео, расшифровок и статуса обработки" },
    ask: { title: "Спрашивать перед изменениями", desc: "Подтверждать в BaoCut перед расшифровкой, правками, экспортом или генерацией" },
    auto: { title: "Разрешать без вопросов", desc: "Запись, задачи и генерация выполняются сразу без подтверждения; подходит для личного использования" },
  },
  scopeAll: (total) => `Все видео (${total})`,
  scopeNone: "Видео не предоставлены",
  scopeOne: (name) => `«${name}»`,
  scopeSome: (n) => `${n} выбранных видео`,
  access: (level) => `${level} · Нужен токен`,
  subOn: (scope, access) => `${scope} · ${access}`,
  subOff: (scope, access) => `После запуска: ${scope} · ${access}`,
  groups: {
    read: { label: "Чтение", hint: "Только чтение; не меняет видео, отвечает сразу" },
    edit: { label: "Изменить", hint: "Записывает в видео; каждый вызов — один отменяемый шаг" },
    job: { label: "Задачи", hint: "Долгая работа; сразу возвращает ID задачи. Прогресс и результаты через jobs_inspect" },
    generate: { label: "Создать", hint: "Синтезирует речь из текста и создаёт изображения по запросам; видео не нужно" },
  },
  tools: {
    videos_list: "Показать список видео",
    videos_create: "Создать видео",
    videos_inspect: "Проверить видео",
    documents_read: "Прочитать документы",
    edits_apply: "Редактировать видео",
    edits_undo: "Отменить правки",
    captions_create: "Создать слой субтитров",
    videos_frames: "Получить кадры видео",
    videos_history: "Показать историю правок",
    documents_put: "Записать документ",
    assets_import: "Импортировать материалы",
    compositions_import: "Импортировать анимированную графику",
    compositions_preview: "Предпросмотр анимированной графики",
    assets_prune: "Удалить неиспользуемые материалы",
    chapters_adopt: "Взять главы из источника",
    edits_ops: "Показать операции редактирования",
    models_capabilities: "Показать возможности моделей",
    models_list: "Показать пакеты локальных моделей",
    transcribe: "Расшифровать",
    translate: "Перевести",
    dub: "Перевести и озвучить",
    speak: "Синтез речи",
    image: "Сгенерировать изображение",
    jobs_inspect: "Проверить задачи",
    jobs_wait: "Дождаться задачи",
    jobs_list: "Показать задачи",
    jobs_cancel: "Отменить задачу",
    jobs_retry: "Повторить неудачный пайплайн",
    export: "Экспорт",
    space_list: "Показать элементы Space",
    space_search: "Поиск по расшифровкам видео",
    projects_list: "Список проектов",
    skills_list: "Показать Skills",
    skills_read: "Прочитать Skill",
    library_list: "Показать библиотеку",
    library_show: "Показать элемент библиотеки",
    download: "Скачать по ссылке",
  },
  gates: {
    answer: "Отвечает напрямую",
    auto: "Выполняется сразу",
    ask: "Спрашивает перед вызовом",
    hidden: "Недоступно при доступе только для чтения",
  },
  toolsSummary: (exposed, total, ask, writes) => {
    const tail = ask ? ` · ${ask} спрашивают перед вызовом` : writes ? " · Подтверждение не нужно" : " · Всё только для чтения";
    return `${exposed} из ${total} инструментов доступно${tail}`;
  },
  outcomes: {
    ok: "Успешно",
    denied: "Запрещено",
    videoNotFound: "Видео вне области доступа",
    unknownTool: "Инструмент недоступен",
  },
  requestLine: (tool, video) => `${tool} · «${video}»`,
  joinKinds: (labels) => labels.join(", "),
  grantLine: (kinds, recipient, purpose, estimate) => `Будет отправлено ${kinds} до ${recipient} (${purpose})${estimate ? ` · Около ${estimate.amount} ${estimate.currency}` : ""}`,
};
