import type { ServicesMcpMessages } from './services-mcp-copy.ts';

export const zhHant: ServicesMcpMessages = {
  levels: {
    read: { title: '唯讀', desc: '查看影片資訊、逐字稿與處理狀態' },
    ask: { title: '變更前詢問', desc: '轉錄、編輯、匯出或生成前，先在 BaoCut 中確認' },
    auto: { title: '直接允許', desc: '寫入、任務與生成會立即執行，不需確認；適合只有你自己使用時' },
  },
  scopeAll: (total) => `所有影片（${total}）`,
  scopeNone: '未開放任何影片',
  scopeOne: (name) => `「${name}」`,
  scopeSome: (n) => `已選取 ${n} 部影片`,
  access: (level) => `${level} · 需要權杖`,
  subOn: (scope, access) => `${scope} · ${access}`,
  subOff: (scope, access) => `啟動後：${scope} · ${access}`,
  groups: {
    read: { label: '讀取', hint: '唯讀；不會變更影片，並會立即回應' },
    edit: { label: '編輯', hint: '寫入影片；每次呼叫算一個可還原的步驟' },
    job: { label: '任務', hint: '耗時的工作；會立即傳回任務 ID。用 jobs_inspect 查看進度與結果' },
    generate: { label: '生成', hint: '依文字合成語音、依提示詞生成圖片；不需要影片' },
  },
  tools: {
    videos_list: '列出影片',
    videos_create: '建立影片',
    videos_inspect: '查看影片',
    documents_read: '讀取文件',
    edits_apply: '修改影片',
    edits_undo: '還原修改',
    captions_create: '建立字幕層',
    videos_frames: '擷取影片影格',
    videos_history: '查看編輯記錄',
    documents_put: '寫入文件',
    assets_import: '匯入素材',
    compositions_import: '匯入程式碼畫面',
    compositions_preview: '預覽程式碼畫面',
    assets_prune: '清理未使用的素材',
    chapters_adopt: '採用來源章節',
    edits_ops: '查看編輯操作',
    models_capabilities: '查看模型能力',
    models_list: '列出本機模型套件',
    transcribe: '轉錄',
    translate: '翻譯',
    dub: '翻譯並配音',
    speak: '合成語音',
    image: '生成圖片',
    jobs_inspect: '查看任務',
    jobs_wait: '等待任務',
    jobs_list: '列出任務',
    jobs_cancel: '取消任務',
    jobs_retry: '重新執行失敗的流程',
    export: '匯出',
    space_list: '列出 Space 中的項目',
    space_search: '跨影片搜尋逐字稿',
    projects_list: '列出專案',
    skills_list: '列出 Skill',
    skills_read: '讀取 Skill',
    library_list: '列出資料庫',
    library_show: '查看資料庫項目',
    download: '從連結下載',
  },
  gates: {
    answer: '直接回應',
    auto: '直接執行',
    ask: '呼叫前詢問',
    hidden: '唯讀權限下不提供',
  },
  toolsSummary: (exposed, total, ask, writes) => {
    const tail = ask ? ` · ${ask} 個呼叫前詢問` : writes ? ' · 不需要確認' : ' · 全部唯讀';
    return `提供 ${exposed} / ${total} 個工具${tail}`;
  },
  outcomes: {
    ok: '成功',
    denied: '未獲允許',
    videoNotFound: '影片不在範圍內',
    unknownTool: '未提供此工具',
  },
  requestLine: (tool, video) => `${tool} · 「${video}」`,
  joinKinds: (labels) => labels.join('、'),
  grantLine: (kinds, recipient, purpose, estimate) =>
    `將把${kinds}傳送給 ${recipient}（${purpose}）${estimate ? ` · 約 ${estimate.amount} ${estimate.currency}` : ''}`,
};
