import type { SpaceMessages } from './space-copy.ts';

export const it: SpaceMessages = {
  kind: {
    video: "Video",
    export: "Esportazione",
    'video-file': "Materiale video",
    image: "Immagine",
    audio: "Audio",
    subtitle: "Sottotitoli",
    document: "Documento",
    package: "Pacchetto video",
    template: "Template",
  },
  categoryAll: "Tutti",
  favorite: "Preferiti",
  trash: "Cestino",
  sort: { created: 'Data di creazione', updated: 'Data di aggiornamento', recent: "Attività recente", name: "Nome", kind: "Tipo" },
  status: {
    generating: "Generazione in corso",
    candidate: "Candidato",
    applied: "Applicato",
    published: "Pubblicato",
    'source-changed': "Origine modificata",
    missing: "Mancante",
    failed: "Non riuscito",
  },
  statusAny: "Tutti gli stati",
  statusNone: "Nessuno stato",
  noProject: "Non in un progetto",
  removedProject: "Progetto rimosso",
  conversation: (title: string) => `Sessione «${title}»`,
  kindCount: (kind: string, n: number) => `${kind} ${n}`,
  foundFiles: (name: string, n: number) => (n === 1 ? `Trovato: ${name}` : `Trovato: ${name} e altri ${n - 1}`),
  fileStatus: (kind: string, status: string) => `${kind}: ${status}`,
  filesStatus: (n: number, status: string) => `${n} file: ${status}`,
};
