import type { StageToolbarMessages } from './stage-toolbar-copy.ts';

export const pl: StageToolbarMessages = {
  toolLabel: {
    color: "Kolor",
    font: "Czcionka",
    size: "Rozmiar",
    'text-styles': "Style",
    animation: "Animuj",
    transitions: "Przejścia",
    volume: "Głośność",
    speed: "Prędkość",
    adjust: "Dostosuj",
    border: "Obrys",
    'fill-list': "Kolory wypełnienia",
    'progress-colors': "Kolor",
    'progress-picker': "Style",
    'wave-colors': "Kolor",
    'wave-picker': "Style",
    'counter-mode': "Tryb",
    'volume-levels': "Poziomy głośności",
    properties: "Właściwości",
    copy: "Duplikuj",
    arrange: "Kolejność",
    'save-to-brand-kit': "Zapisz w zestawie marki",
    'adjust-timing': "Dostosuj czas",
    delete: "Usuń",
    bold: "Pogrubienie",
    italic: "Kursywa",
    'align-left': "Wyrównaj do lewej",
    'align-center': "Środek",
    'align-right': "Wyrównaj do prawej",
    'line-height': "Wysokość wiersza",
    'letter-spacing': "Odstęp między literami",
    'flip-vertical': "Odbij w pionie",
    'flip-horizontal': "Odbij w poziomie",
    'fit-canvas': "Dopasuj do obszaru",
    'fill-canvas': "Wypełnij obszar",
    opacity: "Nieprzezroczystość",
    'round-corners': "Zaokrąglenie rogów",
    filters: "Filtry",
    effects: "Efekty",
    'crop-video': "Inteligentne kadrowanie",
    'replace-video': "Zastąp wideo",
    'replace-image': "Zamień obraz",
    'detach-audio': "Oddziel audio",
    'sub-scope': 'Wiersz do edycji',
    'sub-edit': 'Edytuj',
    'sub-style': 'Style',
    'sub-animation': 'Animuj',
    case: 'Wielkość liter',
    'hide-subs': 'Ukryj napisy',
  },
  offReason: {
    animation: "Format wideo nie ma jeszcze animacji: brak pola do zapisu i operacji edycji.",
    brand: "Zestaw marki nie przechowuje jeszcze klipów.",
    roundCorners: "Nie można jeszcze zapisać promienia narożników wideo i obrazów (operacja appearance nie przyjmuje promienia).",
    filters: "Filtry (LUT) są zarezerwowaną nazwą w formacie wideo i są odrzucane przy zapisie.",
    crop: "Inteligentne kadrowanie wymaga modelu i nie ma jeszcze punktu wejścia. Wkrótce.",
    replace: "Nie ma jeszcze operacji zamiany materiału klipu.",
    detach: "Oddzielanie audio nie jest jeszcze podłączone: wymaga dodania klipu audio i wyciszenia wideo w tej samej zmianie.",
    speed: "Klip nie odtwarza się ze stałą prędkością, więc nie można tu jej zmienić.",
    sound: "Ten klip nie ma dźwięku.",
    captionAnimation: 'Format wideo nie ma jeszcze animacji napisów: styl napisów nie ma na nie pola.',
    captionDefaultStyle: 'Te napisy nadal używają stylu domyślnego. Najpierw zmień dowolne ustawienie, a potem zapisz go w zestawie marki.',
    brandText: 'Zestaw marki nie ma jeszcze sekcji stylów tekstu.',
  },
  arrange: { front: 'Przenieś na wierzch', forward: 'Przesuń do przodu', backward: 'Przesuń do tyłu', back: 'Przenieś na spód', label: 'Zmień kolejność warstw' },
  subtitleBar: 'Pasek narzędzi napisów',
  textStyleLocked: (schema: string) => `Ten tekst używa ${schema} – formatu stylu, którego nie można jeszcze tu edytować.`,
};
