import type { StageToolbarMessages } from './stage-toolbar-copy.ts';

export const tr: StageToolbarMessages = {
  toolLabel: {
    color: 'Renk',
    font: 'Yazı tipi',
    size: 'Boyut',
    'text-styles': 'Stiller',
    animation: 'Animasyon',
    transitions: 'Geçişler',
    volume: 'Ses düzeyi',
    speed: 'Hız',
    adjust: 'Ayarla',
    border: 'Kontur',
    'fill-list': 'Dolgu renkleri',
    'progress-colors': 'Renk',
    'progress-picker': 'Stiller',
    'wave-colors': 'Renk',
    'wave-picker': 'Stiller',
    'counter-mode': 'Mod',
    'volume-levels': 'Ses düzeyleri',
    properties: 'Özellikler',
    copy: 'Çoğalt',
    arrange: 'Sıra',
    'save-to-brand-kit': 'Marka kitine kaydet',
    'adjust-timing': 'Zamanlamayı ayarla',
    disable: 'Klibi devre dışı bırak',
    delete: 'Sil',
    bold: 'Kalın',
    italic: 'İtalik',
    'align-left': 'Sola hizala',
    'align-center': 'Ortala',
    'align-right': 'Sağa hizala',
    'line-height': 'Satır yüksekliği',
    'letter-spacing': 'Harf aralığı',
    'flip-vertical': 'Dikey çevir',
    'flip-horizontal': 'Yatay çevir',
    'fit-canvas': 'Tuvale sığdır',
    'fill-canvas': 'Tuvali doldur',
    opacity: 'Opaklık',
    'round-corners': 'Köşe yarıçapı',
    filters: 'Filtreler',
    effects: 'Efektler',
    'crop-video': 'Akıllı kırpma',
    'replace-video': 'Videoyu değiştir',
    'replace-image': 'Görseli değiştir',
    'detach-audio': 'Sesi ayır',
    'sub-scope': 'Düzenlenecek satır',
    'sub-edit': 'Düzenle',
    'sub-style': 'Stiller',
    'sub-animation': 'Animasyon',
    case: 'Büyük/küçük harf',
    'hide-subs': 'Altyazıları gizle',
  },
  offReason: {
    animation: 'Animasyonlar henüz düzenleyicide seçilemiyor.',
    brand: 'Bu klibin medyası marka kitine kaydedilemez.',
    roundCorners: 'Önizleme henüz yuvarlak köşeleri çizemiyor, bu yüzden burada ayarlanamaz.',
    filters: 'Filtreler (LUT) video biçiminde ayrılmış bir addır ve yazılırken reddedilir.',
    crop: 'Akıllı kırpma model gerektirir ve henüz giriş noktası yok. Yakında.',
    speed: 'Bu klip sabit hızda oynatılmadığından hızı burada değiştirilemez.',
    sound: 'Bu klipte ses yok.',
    captionDefaultStyle: 'Bu altyazılar hâlâ varsayılan stili kullanıyor. Önce herhangi bir ayarı değiştirin, sonra marka kitine kaydedin.',
    brandText: 'Marka kitinde henüz metin stilleri bölümü yok.',
    brandWeb: 'Marka kiti yalnızca masaüstü uygulamasında ve CLI’da kullanılabilir.',
  },
  arrange: { front: 'En öne getir', forward: 'Öne getir', backward: 'Arkaya gönder', back: 'En arkaya gönder', label: 'Yığılma sırasını değiştir' },
  subtitleBar: 'Altyazı araç çubuğu',
  disabledNotice: 'Klip devre dışı bırakıldı. Yeniden etkinleştirmek için zaman çizelgesinde sağ tıklayın.',
  detachedNotice: 'Ses yeni bir ses izine ayrıldı. Video klibin sesi kapatıldı.',
  textStyleLocked: (schema: string) => `Bu metin ${schema} stil biçimini kullanıyor ve henüz burada düzenlenemiyor.`,
};
