import type { StageToolbarMessages } from './stage-toolbar-copy.ts';

export const ko: StageToolbarMessages = {
  toolLabel: {
    color: '색상',
    font: '글꼴',
    size: '크기',
    'text-styles': '스타일',
    animation: '애니메이션',
    transitions: '전환',
    volume: '볼륨',
    speed: '속도',
    adjust: '조정',
    border: '테두리',
    'fill-list': '채우기 색상',
    'progress-colors': '색상',
    'progress-picker': '스타일',
    'wave-colors': '색상',
    'wave-picker': '스타일',
    'counter-mode': '모드',
    'volume-levels': '볼륨 단계',
    properties: '속성',
    copy: '복제',
    arrange: '순서',
    'save-to-brand-kit': '브랜드 키트에 저장',
    'adjust-timing': '타이밍 조정',
    disable: '클립 비활성화',
    delete: '삭제',
    bold: '굵게',
    italic: '기울임',
    'align-left': '왼쪽 정렬',
    'align-center': '가운데',
    'align-right': '오른쪽 정렬',
    'line-height': '줄 간격',
    'letter-spacing': '자간',
    'flip-vertical': '상하 반전',
    'flip-horizontal': '좌우 반전',
    'fit-canvas': '캔버스에 맞춤',
    'fill-canvas': '캔버스 채우기',
    opacity: '불투명도',
    'round-corners': '모서리 반경',
    filters: '필터',
    effects: '효과',
    'crop-video': '스마트 자르기',
    'replace-video': '영상 교체',
    'replace-image': '이미지 교체',
    'detach-audio': '오디오 분리',
    'sub-scope': '편집할 줄',
    'sub-edit': '편집',
    'sub-style': '스타일',
    'sub-animation': '애니메이션',
    case: '대소문자',
    'hide-subs': '자막 숨기기',
  },
  offReason: {
    animation: '편집기에서는 아직 애니메이션을 고를 수 없습니다.',
    brand: '이 클립의 소재는 브랜드 키트에 저장할 수 없습니다.',
    roundCorners: '미리보기에서 아직 둥근 모서리를 그릴 수 없어 여기서 설정할 수 없습니다.',
    filters: '필터(LUT)는 영상 형식에서 예약된 이름이라 기록할 때 거부됩니다.',
    crop: '스마트 자르기는 모델이 필요하며 아직 진입점이 없습니다. 곧 제공됩니다.',
    speed: '이 클립은 일정한 속도로 재생되지 않으므로 여기서 속도를 바꿀 수 없습니다.',
    sound: '이 클립에는 소리가 없습니다.',
    captionAnimation: '편집기에서는 아직 자막 애니메이션을 고를 수 없습니다.',
    captionDefaultStyle: '이 자막은 아직 기본 스타일을 사용합니다. 먼저 설정을 하나 바꾼 다음 브랜드 키트에 저장하세요.',
    brandText: '브랜드 키트에는 아직 텍스트 스타일 섹션이 없습니다.',
    brandWeb: '브랜드 키트는 데스크톱 앱과 CLI에서만 사용할 수 있습니다.',
  },
  arrange: { front: '맨 앞으로 가져오기', forward: '앞으로 가져오기', backward: '뒤로 보내기', back: '맨 뒤로 보내기', label: '쌓임 순서 변경' },
  subtitleBar: '자막 도구 모음',
  disabledNotice: '클립을 비활성화했습니다. 타임라인에서 마우스 오른쪽 버튼을 클릭하면 다시 활성화할 수 있습니다.',
  detachedNotice: '소리를 새 오디오 트랙으로 분리했습니다. 비디오 클립은 음소거되었습니다.',
  textStyleLocked: (schema: string) => `이 텍스트는 ${schema} 스타일 형식을 사용하므로 아직 여기서 편집할 수 없습니다.`,
};
