import type { StageToolbarMessages } from './stage-toolbar-copy.ts';

export const zhHans: StageToolbarMessages = {
  toolLabel: {
    color: '颜色',
    font: '字体',
    size: '字号',
    'text-styles': '样式',
    animation: '动画',
    transitions: '转场',
    volume: '音量',
    speed: '变速',
    adjust: '调整',
    border: '描边',
    'fill-list': '填充色',
    'progress-colors': '颜色',
    'progress-picker': '样式',
    'wave-colors': '颜色',
    'wave-picker': '样式',
    'counter-mode': '模式',
    'volume-levels': '音量档位',
    properties: '属性',
    copy: '复制一份',
    arrange: '层级',
    'save-to-brand-kit': '存到品牌库',
    'adjust-timing': '调整时间',
    delete: '删除',
    bold: '粗体',
    italic: '斜体',
    'align-left': '左对齐',
    'align-center': '居中',
    'align-right': '右对齐',
    'line-height': '行高',
    'letter-spacing': '字距',
    'flip-vertical': '垂直翻转',
    'flip-horizontal': '水平翻转',
    'fit-canvas': '适应画布',
    'fill-canvas': '填满画布',
    opacity: '不透明度',
    'round-corners': '圆角',
    filters: '滤镜',
    effects: '效果',
    'crop-video': '智能裁剪',
    'replace-video': '替换视频',
    'replace-image': '替换图片',
    'detach-audio': '分离音频',
  },
  offReason: {
    animation: '视频格式里还没有动画：没有可写的字段，也没有对应的修改操作。',
    arrange: '叠放次序由引擎按轨道上下排（paintOrder），还没有修改它的操作；要换前后，在时间线上把片段挪到上面或下面的轨道。',
    brand: '品牌库还没有存入片段的接口。',
    roundCorners: '视频与图片的圆角还没有可写的操作（改外观的操作不收圆角）。',
    filters: '滤镜（LUT）在视频格式里是保留名，写入时会被拒绝。',
    crop: '智能裁剪要跑模型，还没有可用的入口，即将推出。',
    replace: '还没有给片段换素材的操作。',
    detach: '分离音频还没接上：要在同一笔里新建音频片段并关掉视频自带的声音。',
    speed: '这一段的时间映射不是恒定速率，不能在这里变速。',
    sound: '这一件没有声音。',
  },
  textStyleLocked: (schema: string) => `这段文字的样式是 ${schema}，还不能在这里改。`,
};
