import type { ToolsTtsMessages } from './tools-tts-copy.ts';

export const tr: ToolsTtsMessages = {
  emptyText: 'Önce okunacak metni yazın',
  vibes: {
    radio: { name: 'Gece radyosu', style: 'Gece radyosu gibi: biraz daha yavaş, alçak sesle' },
    launch: { name: 'Ürün lansmanı', style: 'Ürün lansmanı: daha sıcak ve enerjik, önemli noktaları vurgulayarak' },
    bedtime: { name: 'Uyku öncesi hikâye', style: 'Yumuşak bir uyku öncesi hikâye: yavaş tempo, nazik ton' },
    news: { name: 'Haber bülteni', style: 'Haber bülteni: net telaffuz, düzenli ritim' },
    teach: { name: 'Ders', style: 'Ders gibi anlat: konuşma diliyle, önemli noktalarda duraklayarak' },
    vlog: { name: 'Enerjik anlatım', style: 'Hafif ve enerjik, biraz daha hızlı, gülümseyen bir sesle' },
  },
  statsEmpty: (max) => `0 / ${max} karakter`,
  stats: (n, max, segments, seconds) => `${n} / ${max} karakter · ${segments} bölüm · yaklaşık ${seconds} sn`,
  defaultVoiceOption: (name) => `Varsayılan · ${name}`,
  customVoiceOption: 'Ses ID gir…',
  presetOnly: (model) => `${model} yalnızca ön ayarlı sesleri kabul eder; Seslerim kullanılamaz`,
  cannotClone: (provider) => `${provider} klonlayamaz · ön ayarlı seslerini kullanın`,
  noConsent: 'Kendi sesiniz olduğu veya izinle kullanıldığı belirtilmediği için üçüncü tarafa yüklenmez · Seslerim kısmında beyanı ekleyin',
  cloneStale: (provider) => `${provider} sağlayıcısındaki klon güncel değil (referans kayıt değişti) · Seslerim kısmında yeniden yükleyin`,
  notCloned: (provider) => `${provider} sağlayıcısında henüz klonlanmadı · Seslerim kısmında bir kez yükleyin`,
  customVoice: 'Özel ses',
  deletedVoice: 'Silinen ses',
  myVoices: 'Seslerim',
  defaultVoice: 'Varsayılan ses',
  cannotSpeak: (model, language) => `${model}, ${language} okuyamaz`,
  voiceDeleted: 'Seçilen ses silindi; başka birini seçin',
  tooLong: (model, max) => `${model} bir seferde en fazla ${max} karakter kabul eder; önce metni kısaltın`,
  enterVoiceId: 'Önce ses ID girin',
  pickVoice: 'Önce bir ses seçin',
  noVoices: 'Bu modelin kullanılabilir sesi yok',
  seedInteger: 'Tohum tam sayı olmalı',
  noModel: 'Henüz kullanılabilir konuşma sentezi modeli yok',
  connectFirst: (provider) => `Önce ${provider} sağlayıcısını bağlayın`,
  readsMaterial: (model, voice, name) => `${model} · ${voice} · “${name}” metnini okur`,
  estimate: (seconds, chars) => ` · yaklaşık ${seconds} sn · yaklaşık ${chars} karakter`,
  chars: (n) => `${n} karakter`,
  speech: 'Konuşma',
  presetVoices: (n) => `${n} ön ayarlı ses`,
  customVoiceId: 'Özel ses ID',
  takesStyle: 'Stil notları kabul eder',
  speedRange: (min, max) => `Hız ${min}–${max}×`,
  maxChars: (max) => `Bir seferde en fazla ${max} karakter`,
  headerChip: (provider) => `Çevrimiçi · ${provider} · kullanıma göre ücretlendirilir`,
};
