import type { ToolsTtsMessages } from './tools-tts-copy.ts';

export const vi: ToolsTtsMessages = {
  emptyText: 'Viết văn bản cần đọc trước',
  vibes: {
    radio: { name: 'Radio đêm khuya', style: 'Như radio đêm khuya: chậm hơn một chút, giữ giọng thấp' },
    launch: { name: 'Ra mắt sản phẩm', style: 'Ra mắt sản phẩm: ấm áp và sôi nổi hơn, nhấn mạnh điểm chính' },
    bedtime: { name: 'Truyện trước giờ ngủ', style: 'Truyện trước giờ ngủ nhẹ nhàng: nhịp chậm, giọng dịu dàng' },
    news: { name: 'Bản tin', style: 'Bản tin: phát âm rõ, nhịp đều' },
    teach: { name: 'Bài học', style: 'Giải thích như bài học: giọng trò chuyện, dừng ở điểm chính' },
    vlog: { name: 'Lời dẫn vui tươi', style: 'Nhẹ nhàng và vui tươi, nhanh hơn một chút, giọng có nét cười' },
  },
  statsEmpty: (max) => `0 / ${max} ký tự`,
  stats: (n, max, segments, seconds) => `${n} / ${max} ký tự · ${segments} đoạn · khoảng ${seconds} giây`,
  defaultVoiceOption: (name) => `Mặc định · ${name}`,
  customVoiceOption: 'Nhập ID giọng…',
  presetOnly: (model) => `${model} chỉ nhận giọng thiết lập sẵn nên không dùng được Giọng của tôi`,
  cannotClone: (provider) => `${provider} không thể nhân bản · dùng giọng thiết lập sẵn của họ`,
  noConsent: 'Chưa xác nhận là giọng của bạn hoặc được phép sử dụng nên không tải lên bên thứ ba · thêm tuyên bố trong Giọng của tôi',
  cloneStale: (provider) => `Bản nhân trên ${provider} đã lỗi thời (bản ghi tham chiếu đã đổi) · tải lên lại trong Giọng của tôi`,
  notCloned: (provider) => `Chưa nhân bản trên ${provider} · tải lên một lần trong Giọng của tôi`,
  customVoice: 'Giọng tùy chỉnh',
  deletedVoice: 'Giọng đã xóa',
  myVoices: 'Giọng của tôi',
  defaultVoice: 'Giọng mặc định',
  cannotSpeak: (model, language) => `${model} không thể đọc ${language}`,
  voiceDeleted: 'Giọng đã chọn bị xóa; chọn giọng khác',
  tooLong: (model, max) => `${model} nhận tối đa ${max} ký tự mỗi lần; rút ngắn văn bản trước`,
  enterVoiceId: 'Nhập ID giọng trước',
  pickVoice: 'Chọn giọng trước',
  noVoices: 'Mô hình này không có giọng khả dụng',
  seedInteger: 'Seed phải là số nguyên',
  noModel: 'Chưa có mô hình tổng hợp giọng nói khả dụng',
  connectFirst: (provider) => `Kết nối ${provider} trước`,
  readsMaterial: (model, voice, name) => `${model} · ${voice} · đọc văn bản của “${name}”`,
  estimate: (seconds, chars) => ` · khoảng ${seconds} giây · khoảng ${chars} ký tự`,
  chars: (n) => `${n} ký tự`,
  speech: 'Giọng nói',
  presetVoices: (n) => `${n} giọng thiết lập sẵn`,
  customVoiceId: 'ID giọng tùy chỉnh',
  takesStyle: 'Nhận mô tả phong cách',
  speedRange: (min, max) => `Tốc độ ${min}–${max}×`,
  maxChars: (max) => `Tối đa ${max} ký tự mỗi lần`,
  headerChip: (provider) => `Trực tuyến · ${provider} · tính phí theo mức sử dụng`,
};
