import type { ToolRunsMessages } from './tool-runs-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const fr: ToolRunsMessages = {
  diarizeStep: 'Identifier les locuteurs',
  phaseDone: 'Terminé', phaseQueued: 'En file d’attente', phaseCancelled: 'Annulé', phaseUnfinished: 'Non terminé', phasePreparing: 'Préparation',
  stepAt: (cur, total) => `Étape ${cur} sur ${total}`,
  cancelledAt: (step, at) => `Annulé à « ${step} » · ${at}`, stoppedAt: (step, at) => `Arrêté à « ${step} » · ${at}`,
  runningAt: (step, at) => `${step} · ${at}`, stepDone: 'Terminé', stepStopped: 'Arrêté ici', stepRunning: 'En cours', stepWaiting: 'En attente',
  costEstimate: (amount, currency) => `Environ ${amount} ${currency}`, costSubscription: (recipient) => `Inclus dans votre abonnement ${recipient}`,
  costFree: 'Gratuit', costMetered: (recipient) => `Facturé aux tarifs de ${recipient} ; aucune estimation disponible ici`,
  grantWhat: (kinds, purpose) => `${kinds.join(', ')} (${purpose})`,
  grantLoop: 'Vous avez déjà approuvé ces demandes, mais le Runtime les refuse toujours. Vérifiez ces autorisations dans Réglages › Confidentialité et autorisations, ou choisissez un autre modèle.',
  noStructuredOutput: 'Ce modèle ne prend pas en charge les sorties structurées et ne peut donc pas traduire',
  captionsCreated: (p) => `Un calque de sous-titres ${p.language ? `en ${p.language}` : 'modifiable'} a été créé${p.bilingual ? ', avec affichage bilingue' : ''}${p.disabled ? ' (ce média affiche déjà des sous-titres ; le nouveau calque est donc désactivé au départ)' : ''}`,
  captionsExistingTranslation: 'Cette traduction a déjà un calque de sous-titres ; aucun nouveau calque n’a été créé',
  captionsExistingTranscript: 'Cette transcription a déjà un calque de sous-titres ; aucun nouveau calque n’a été créé',
  captionsNotOnTimeline: 'Aucun clip sur la timeline n’utilise ce média ; aucun calque de sous-titres n’a été créée',
  captionsEmpty: 'Il n’y a aucun sous-titre à afficher ; aucun calque de sous-titres n’a été créée',
  originalAudio: { duck: 'Audio original atténué', mute: 'Audio original coupé', keep: 'Audio original conservé' },
  thisVideo: 'cette vidéo', newVideo: 'Nouvelle vidéo', fallbackVideo: 'Vidéo', media: 'média',
  savedFiles: (names) => `Transcription et sous-titres enregistrés : ${names.join(', ')}`,
  transcriptLanguage: (language, model) => `Langue de la transcription : ${language}${model ? ` (${model})` : ''}`,
  createdVideoLinked: (video, project) => `Vidéo « ${video} » créée${project ? ` dans « ${project} »` : ''} ; le média reste à son emplacement et seul un lien est créé`,
  wroteTranscript: (video) => `Transcription ajoutée à « ${video} »`,
  speakersFound: (n) => `${n} ${pluralForm('fr', n, { one: 'locuteur identifié', other: 'locuteurs identifiés' })} ; les sous-titres et la transcription portent les noms`,
  wroteTranslation: (video, language, source) => `Traduction en ${language} ajoutée à « ${video} »${source ? ` (depuis la transcription en ${source})` : ''} ; l’original est inchangé`,
  unitCount: (n) => `${n} ${pluralForm('fr', n, { one: 'phrase', other: 'phrases' })}`,
  subtitleFileWritten: (file, dir) => `Fichier de sous-titres traduit ${file} enregistré dans ${dir} ; nombre de segments et codes temporels inchangés`,
  bilingualLayout: 'Bilingue : original en haut, traduction en bas',
  markupStripped: (n) => `Balisage intégré retiré de ${n} ${pluralForm('fr', n, { one: 'segment original', other: 'segments originaux' })}`,
  dubTranslated: (language) => `Traduction préalable en ${language} : une nouvelle traduction a été ajoutée`,
  dubReusedTranslation: (language) => `Traduction existante en ${language} utilisée`,
  dubWritten: (video, language, engine) => `Nouveau doublage en ${language} ajouté à « ${video} »${engine ? ` (${engine})` : ''} ; les doublages précédents sont conservés`,
  dubPlaced: (placed, total) => `${placed} ${pluralForm('fr', placed, { one: `phrase sur ${total} placée`, other: `phrases sur ${total} placées` })} sur la timeline`,
  linkCreatedVideo: (video, project) => `Vidéo « ${video} » créée${project ? ` dans « ${project} »` : ''} ; le média téléchargé est sur la timeline`,
  linkAddedTo: (file, video) => `${file} ajouté à « ${video} » ; le fichier reste dans votre dossier de téléchargements`,
  linkDownloaded: (file, dir) => `${file} téléchargé${dir ? ` dans ${dir}` : ''}`,
  linkTranscribedFiles: 'Transcription terminée ; une transcription TXT et des sous-titres SRT ont été enregistrés',
  linkTranscribed: 'Transcription terminée ; une transcription a été ajoutée. Cette méthode ne crée pas de calque de sous-titres ; vous pouvez en générer une dans le panneau Sous-titres de l’éditeur',
  replacedTranscript: (video) => `Transcription de « ${video} » remplacée : une seule modification, que vous pouvez annuler`,
  newVideoFrom: (video, project, original) =>
    `Vidéo « ${video} » créée${project ? ` dans « ${project} »` : ''}, liée au même média ; ${original ? `« ${original} »` : 'la vidéo d’origine'} et ses traductions ne changent pas`,
  carryTranslation: (language, kept, reviewed, stale) =>
    `Traduction en ${language} · conservées : ${kept} (relues : ${reviewed}) · obsolètes : ${stale}`,
  carryPins: (reanchored, orphaned) => `Pins de sous-titres · réancrés : ${reanchored} · orphaned : ${orphaned}`,
  carryDub: (language, kept, stale) => `Doublage en ${language} · conservées : ${kept} · obsolètes : ${stale}`,
  nothingToCarry: 'Cette vidéo n’avait ni traductions, ni pins de sous-titres, ni doublages à reporter',
  refreshHint: 'Retraduisez les phrases obsolètes avec « Actualiser les traductions obsolètes »',
};
