import type { ToolRunsMessages } from './tool-runs-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const es: ToolRunsMessages = {
  diarizeStep: 'Identificar hablantes',
  phaseDone: 'Completado', phaseQueued: 'En cola', phaseCancelled: 'Cancelado', phaseUnfinished: 'Sin terminar', phasePreparing: 'Preparando',
  stepAt: (cur: number, total: number) => `Paso ${cur} de ${total}`,
  cancelledAt: (step: string, at: string) => `Cancelado en «${step}» · ${at}`,
  stoppedAt: (step: string, at: string) => `Detenido en «${step}» · ${at}`,
  runningAt: (step: string, at: string) => `${step} · ${at}`,
  stepDone: 'Completado', stepStopped: 'Detenido aquí', stepRunning: 'En curso', stepWaiting: 'En espera',
  costEstimate: (amount: number | string, currency: string) => `Unos ${amount} ${currency}`,
  costSubscription: (recipient: string) => `Incluido en tu suscripción a ${recipient}`,
  costFree: 'Gratis',
  costMetered: (recipient: string) => `Facturado según las tarifas de ${recipient}; aquí no hay una estimación disponible`,
  grantWhat: (kinds: readonly string[], purpose: string) => `${kinds.join(', ')} (${purpose})`,
  grantLoop: 'Ya lo has aprobado, pero el Runtime sigue rechazándolo. Revisa estos permisos en Ajustes › Privacidad y permisos o cambia de modelo.',
  noStructuredOutput: 'Este modelo no admite salida estructurada, por lo que no puede traducir',
  captionsCreated: (p: { language: string | null; bilingual: boolean; disabled: boolean }) =>
    `Se creó ${p.language ? `una capa de subtítulos en ${p.language}` : 'una capa de subtítulos editable'}${p.bilingual ? ', mostrada en dos idiomas' : ''}${p.disabled ? ' (este material ya muestra subtítulos, por lo que la nueva capa empieza desactivada)' : ''}`,
  captionsExistingTranslation: 'Esta traducción ya tiene una capa de subtítulos, por lo que no se creó otra',
  captionsExistingTranscript: 'Esta transcripción ya tiene una capa de subtítulos, por lo que no se creó otra',
  captionsNotOnTimeline: 'Ningún clip de la línea de tiempo usa este material, por lo que no se creó una capa de subtítulos',
  captionsEmpty: 'No hay subtítulos que mostrar, por lo que no se creó una capa de subtítulos',
  originalAudio: { duck: 'Audio original atenuado', mute: 'Audio original silenciado', keep: 'Audio original conservado' },
  thisVideo: 'este vídeo', newVideo: 'Nuevo vídeo', fallbackVideo: 'Vídeo', media: 'material',
  savedFiles: (names: readonly string[]) => `Transcripción y subtítulos guardados: ${names.join(', ')}`,
  transcriptLanguage: (language: string, model: string | null) => `Idioma de la transcripción: ${language}${model ? ` (${model})` : ''}`,
  createdVideoLinked: (video: string, project: string | null) => `Se creó el vídeo «${video}»${project ? ` en «${project}»` : ''}; el material permanece donde está y solo se vincula`,
  wroteTranscript: (video: string) => `Se añadió una transcripción a «${video}»`,
  speakersFound: (n: number) => `${pluralForm('es', n, { one: `Se encontró ${n} hablante`, other: `Se encontraron ${n} hablantes` })}; los subtítulos y la transcripción están etiquetados con nombres`,
  wroteTranslation: (video: string, language: string, source: string | null) => `Se añadió una traducción en ${language} a «${video}»${source ? ` (de la transcripción en ${source})` : ''}; el original no cambia`,
  unitCount: (n: number) => `${n} ${pluralForm('es', n, { one: 'frase', other: 'frases' })}`,
  subtitleFileWritten: (file: string, dir: string) => `Archivo de subtítulos traducido ${file} guardado en ${dir}; se conservan la cantidad de entradas y los códigos de tiempo`,
  bilingualLayout: 'Bilingüe: original arriba, traducción abajo',
  markupStripped: (n: number) => `Se eliminó el marcado en línea de ${n} ${pluralForm('es', n, { one: 'entrada original', other: 'entradas originales' })}`,
  dubTranslated: (language: string) => `Primero se tradujo a ${language}: se añadió una traducción nueva`,
  dubReusedTranslation: (language: string) => `Se usó la traducción existente en ${language}`,
  dubWritten: (video: string, language: string, engine: string) => `Se añadió un nuevo doblaje en ${language} a «${video}»${engine ? ` (${engine})` : ''}; se conservan los doblajes anteriores`,
  dubPlaced: (placed: number, total: number) => `${placed} de ${total} frases colocadas en la línea de tiempo`,
  linkCreatedVideo: (video: string, project: string | null) => `Se creó el vídeo «${video}»${project ? ` en «${project}»` : ''}; el material descargado está en la línea de tiempo`,
  linkAddedTo: (file: string, video: string) => `Se añadió ${file} a «${video}»; el archivo permanece en tu carpeta de descargas`,
  linkDownloaded: (file: string, dir: string | null) => `Se descargó ${file}${dir ? ` en ${dir}` : ''}`,
  linkTranscribedFiles: 'Transcripción completada; se guardaron una transcripción TXT y subtítulos SRT',
  linkTranscribed: 'Transcripción completada; se añadió una transcripción. Esta ruta no crea una capa de subtítulos; puedes generar una en el panel Subtítulos del editor',
  replacedTranscript: (video: string) => `Se sustituyó la transcripción de «${video}»: un único cambio que puedes deshacer`,
  newVideoFrom: (video: string, project: string | null, original: string | null) =>
    `Se creó el vídeo «${video}»${project ? ` en «${project}»` : ''}, enlazado al mismo recurso; ${original ? `«${original}»` : 'el vídeo original'} y sus traducciones no cambian`,
  carryTranslation: (language: string, kept: number, reviewed: number, stale: number) =>
    `Traducción al ${language} · conservadas: ${kept} (revisadas: ${reviewed}) · desactualizadas: ${stale}`,
  carryPins: (reanchored: number, orphaned: number) => `Pins de subtítulos · reanclados: ${reanchored} · orphaned: ${orphaned}`,
  carryDub: (language: string, kept: number, stale: number) => `Doblaje en ${language} · conservadas: ${kept} · desactualizadas: ${stale}`,
  nothingToCarry: 'Este vídeo no tenía traducciones, pins de subtítulos ni doblajes que trasladar',
  refreshHint: 'Vuelve a traducir las frases desactualizadas con «Actualizar traducciones desactualizadas»',
};
