import type { ToolsTranscodeMessages } from './tools-transcode-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const it: ToolsTranscodeMessages = {
  quality: { smaller: { name: 'Più piccolo', sub: 'Sufficiente per messaggistica e archiviazione cloud' }, balanced: { name: 'Bilanciato', sub: 'La differenza è difficile da notare' }, high: { name: 'Alta qualità', sub: 'Conservalo per modifiche successive' } }, heightOriginal: 'Originale', heightOriginalLong: 'Risoluzione originale', codecSub: { h264: 'Si riproduce ovunque', hevc: '40% più piccolo alla stessa qualità; i dispositivi meno recenti potrebbero non riprodurlo' },
  notVideoFiles: (names: readonly string[]) => `${names.join(', ')} ${pluralForm('it', names.length, { one: 'non è un file video', other: 'non sono file video' })}`, notAbsolute: (paths: readonly string[]) => `${paths.join(', ')} ${pluralForm('it', paths.length, { one: 'non è un percorso assoluto', other: 'non sono percorsi assoluti' })}`, alreadyListed: (names: readonly string[]) => `${names.join(', ')} ${pluralForm('it', names.length, { one: 'è già nell’elenco', other: 'sono già nell’elenco' })}`, overflow: (limit: number, extra: number) => `Fino a ${limit} file alla volta; ${pluralForm('it', extra, { one: `${extra} altro non aggiunto`, other: `${extra} altri non aggiunti` })}`, joinNotices: (bits: readonly string[]) => bits.join('; '),
  needTwoVideos: 'Aggiungi almeno due video', needMediaFile: 'Scegli prima un file video o audio', needVideoFile: 'Scegli prima un file video', needOneMore: 'L’unione richiede almeno due video; aggiungine un altro', tooManyFiles: (limit: number) => `Fino a ${limit} file alla volta`, videoKbpsRange: (min: number, max: number) => `Il bitrate video deve essere compreso tra ${min} e ${max} kbps`, audioKbpsRange: (min: number, max: number) => `Il bitrate audio deve essere compreso tra ${min} e ${max} kbps`, outDirAbsolute: 'La cartella di output deve essere un percorso assoluto', ffmpegUnusable: (message: string) => `ffmpeg non è disponibile: ${message}`, audioKbps: (kbps: number) => `Audio ${kbps} kbps`,
  ffmpegNeeded: 'Installa prima ffmpeg', ffmpegInstallHint: 'Installa ffmpeg o imposta il percorso con BAOCUT_FFMPEG', ffmpegReady: (version: string) => `ffmpeg${version} è pronto`, ffmpegOutdated: (version: string) => `ffmpeg${version} è troppo vecchio`, ffmpegCannotRun: 'ffmpeg non può essere eseguito', filesTitle: (first: string, count: number) => `${first} e ${pluralForm('it', count - 1, { one: `${count - 1} altro`, other: `${count - 1} altri` })}`, defaultTitle: 'Conversione di file', mergeTitle: (first: string, more: number) => `${first} + ${pluralForm('it', more, { one: `${more} altro`, other: `${more} altri` })}`, qualityWithCrf: (name: string, crf: number) => `${name} (CRF ${crf})`,
  mergeStreamCopy: (n: number) => `Unisci ${n} clip · Copia del flusso`, extractAudioMany: (n: number) => `Estrai audio da ${n} file`, extractAudio: 'Estrai audio', mergeClips: (n: number) => `Unisci ${n} clip`, compressMany: (n: number) => `Comprimi ${n} file`, compress: 'Comprimi', stepQueued: (step: string, detail: string | null) => `${step} · ${detail ?? 'In coda'}`, stepOf: (step: string, cur: number, total: number) => `${step} · Passaggio ${cur} di ${total}`, noAudioTrack: 'Nessun audio', mergedSize: (after: string, before: string) => `${after} (origini in totale ${before})`, savedSize: (before: string, after: string, saved: number | null) => `${before} → ${after} (${saved === null ? 'non più piccolo' : saved === 0 ? 'circa uguale' : `${saved}% più piccolo`})`, streamCopyLine: 'Tutte le clip corrispondono: copia del flusso senza ricodifica, qualità invariata', reencodeLine: (reason: string | null) => reason ? `Ricodificato: ${reason}` : 'Ricodificato', underASecond: 'Meno di 1 secondo', took: (duration: string) => `Tempo impiegato: ${duration}`, stateQueued: 'In coda', stateProcessing: 'Elaborazione in corso',
  remedyThenRetry: (remedy: string) => `${remedy}, poi riprova`, inputUnreadable: 'Impossibile leggere fotogrammi da questo file. Verifica che si riproduca in un lettore multimediale o scegli un altro file', transcodeFailed: 'ffmpeg non è riuscito a completare; l’output originale è sotto. Se il disco è pieno, libera spazio; se un file di origine è stato spostato, selezionalo di nuovo', validationFailed: 'L’output non ha superato la validazione ed è stato scartato, quindi nulla è stato scritto nella cartella di output. Riprova o cambia le impostazioni',
};
