import type { ToolsTranscodeMessages } from './tools-transcode-copy.ts';

export const ja: ToolsTranscodeMessages = {
  quality: {
    smaller: { name: '小さめ', sub: 'メッセージ送信やクラウドストレージには十分' },
    balanced: { name: 'バランス', sub: '違いはほとんど分かりません' },
    high: { name: '高画質', sub: '後で編集するために保存' },
  },
  heightOriginal: 'オリジナル',
  heightOriginalLong: '元の解像度',
  codecSub: {
    h264: 'どこでも再生できます',
    hevc: '同じ画質で 40% 小さく、古いデバイスでは再生できない場合があります',
  },

  notVideoFiles: (names) => `${names.join('、')} は動画ファイルではありません`,
  notAbsolute: (paths) => `${paths.join('、')} は絶対パスではありません`,
  alreadyListed: (names) => `${names.join('、')} はすでにリストにあります`,
  overflow: (limit, extra) => `一度に追加できるファイルは最大 ${limit} 個です。残りの ${extra} 個は追加されませんでした`,
  joinNotices: (bits) => bits.join('。'),

  needTwoVideos: '動画を 2 本以上追加してください',
  needMediaFile: '先に動画または音声ファイルを選んでください',
  needVideoFile: '先に動画ファイルを選んでください',
  needOneMore: '結合には 2 本以上の動画が必要です。もう 1 本追加してください',
  tooManyFiles: (limit) => `一度に扱えるファイルは最大 ${limit} 個です`,
  videoKbpsRange: (min, max) => `動画のビットレートは ${min}～${max} kbps にしてください`,
  audioKbpsRange: (min, max) => `音声のビットレートは ${min}～${max} kbps にしてください`,
  outDirAbsolute: '出力先フォルダは絶対パスで指定してください',
  ffmpegUnusable: (message) => `ffmpeg を使用できません：${message}`,
  audioKbps: (kbps) => `音声 ${kbps} kbps`,

  ffmpegNeeded: '先に ffmpeg をインストールしてください',
  ffmpegInstallHint: 'ffmpeg をインストールするか、BAOCUT_FFMPEG でパスを指定してください',
  ffmpegReady: (version) => `ffmpeg${version} の準備ができています`,
  ffmpegOutdated: (version) => `ffmpeg${version} は古すぎます`,
  ffmpegCannotRun: 'ffmpeg を実行できません',

  filesTitle: (first, count) => `${first} ほか ${count - 1} 個`,
  defaultTitle: 'ファイル変換',
  mergeTitle: (first, more) => `${first} ほか ${more} 本`,
  qualityWithCrf: (name, crf) => `${name}（CRF ${crf}）`,
  mergeStreamCopy: (n) => `${n} 個のクリップを結合 · ストリームコピー`,
  extractAudioMany: (n) => `${n} 個のファイルから音声を抽出`,
  extractAudio: '音声を抽出',
  mergeClips: (n) => `${n} 個のクリップを結合`,
  compressMany: (n) => `${n} 個のファイルを圧縮`,
  compress: '圧縮',
  stepQueued: (step, detail) => `${step} · ${detail ?? '待機中'}`,
  stepOf: (step, cur, total) => `${step} · ステップ ${cur} / ${total}`,
  noAudioTrack: '音声なし',
  mergedSize: (after, before) => `${after}（元ファイル合計 ${before}）`,
  savedSize: (before, after, saved) => `${before} → ${after}（${saved === null ? '小さくなっていません' : saved === 0 ? 'ほぼ同じ' : `${saved}% 縮小`}）`,
  streamCopyLine: 'すべてのクリップの設定が一致：再エンコードせずにストリームコピーしました。画質は変わりません',
  reencodeLine: (reason) => (reason ? `再エンコード：${reason}` : '再エンコード'),
  underASecond: '1 秒未満',
  took: (duration) => `所要時間 ${duration}`,
  stateQueued: '待機中',
  stateProcessing: '処理中',

  remedyThenRetry: (remedy) => `${remedy}。その後、再試行してください`,
  inputUnreadable: 'このファイルからフレームを読み取れませんでした。メディアプレーヤで再生できるか確認するか、別のファイルを選んでください',
  transcodeFailed: 'ffmpeg が途中で失敗しました。元の出力は下にあります。ディスクがいっぱいなら空き容量を確保し、元ファイルを移動した場合は選び直してください',
  validationFailed: '出力が検証に通らなかったため破棄しました。出力先フォルダには何も書き込まれていません。再試行するか、設定を変更してください',
};
