import { pluralForm } from '@baocut/protocol';
import type { ToolsTtsMessages } from './tools-tts-copy.ts';

export const ru: ToolsTtsMessages = {
  emptyText: "Сначала введите текст",
  vibes: {
    radio: { name: "Ночное радио", style: "Как ночное радио: чуть медленнее, голос ниже" },
    launch: { name: "Презентация", style: "Презентация продукта: теплее и энергичнее, акцент на главном" },
    bedtime: { name: "Сказка на ночь", style: "Мягкая сказка на ночь: медленнее, нежный тон" },
    news: { name: "Выпуск новостей", style: "Выпуск новостей: чёткая дикция, ровный ритм" },
    teach: { name: "Урок", style: "Объясните как на уроке: разговорный тон, паузы на главном" },
    vlog: { name: "Бодрое повествование", style: "Легко и бодро, чуть быстрее, с улыбкой в голосе" },
  },
  statsEmpty: (max) => `Символы: 0 / ${max}`,
  stats: (n, max, segments, seconds) => `Символы: ${n} / ${max} · ${pluralForm('ru', segments, { one: `${segments} сегмент`, few: `${segments} сегмента`, many: `${segments} сегментов`, other: `${segments} сегмента` })} · около ${seconds} с`,
  defaultVoiceOption: (name) => `По умолчанию · ${name}`,
  customVoiceOption: "Введите ID голоса…",
  presetOnly: (model) => `${model} принимает только готовые голоса, «Мои голоса» недоступны`,
  cannotClone: (provider) => `${provider} не клонирует · используйте готовые голоса`,
  noConsent: "Не указано, что голос ваш или есть разрешение, он не будет отправлен третьей стороне · добавьте заявление в «Мои голоса»",
  cloneStale: (provider) => `Клон у поставщика ${provider} устарел (эталонная запись изменена) · отправьте снова в «Мои голоса»`,
  notCloned: (provider) => `Не клонировано у поставщика ${provider} пока · отправьте один раз в «Мои голоса»`,
  customVoice: "Свой голос",
  deletedVoice: "Удалённый голос",
  myVoices: "Мои голоса",
  defaultVoice: "Голос по умолчанию",
  cannotSpeak: (model, language) => `${model} не может прочитать ${language}`,
  voiceDeleted: "Выбранный голос удалён; выберите другой",
  tooLong: (model, max) => `${model} принимает не более ${max} символов за раз; сначала сократите текст`,
  enterVoiceId: "Сначала введите ID голоса",
  pickVoice: "Сначала выберите голос",
  noVoices: "У модели нет доступных голосов",
  seedInteger: "Сид должен быть целым числом",
  noModel: "Пока нет доступной модели синтеза речи",
  connectFirst: (provider) => `Сначала подключите ${provider}`,
  readsMaterial: (model, voice, name) => `${model} · ${voice} · читает текст «${name}»`,
  estimate: (seconds, chars) => ` · около ${seconds} с · около ${pluralForm('ru', chars, { one: `${chars} символ`, few: `${chars} символа`, many: `${chars} символов`, other: `${chars} символа` })}`,
  chars: (n) => pluralForm('ru', n, { one: `${n} символ`, few: `${n} символа`, many: `${n} символов`, other: `${n} символа` }),
  speech: "Речь",
  presetVoices: (n) => pluralForm('ru', n, { one: `${n} готовый голос`, few: `${n} готовых голоса`, many: `${n} готовых голосов`, other: `${n} готового голоса` }),
  customVoiceId: "Свой ID голоса",
  takesStyle: "Принимает инструкции стиля",
  speedRange: (min, max) => `Скорость ${min}–${max}×`,
  maxChars: (max) => `До ${max} символов за раз`,
  headerChip: (provider) => `Онлайн · ${provider} · оплата по использованию`,
};
