import type { ToolsTtsMessages } from './tools-tts-copy.ts';
import { pluralForm } from '@baocut/protocol';
export const es: ToolsTtsMessages = {
  emptyText: 'Primero escribe el texto que quieres leer',
  vibes: {
    radio: { name: 'Radio nocturna', style: 'Como la radio nocturna: un poco más despacio y con la voz baja' },
    launch: { name: 'Lanzamiento de producto', style: 'Un lanzamiento de producto: más calidez y energía, destacando los puntos clave' },
    bedtime: { name: 'Cuento para dormir', style: 'Un cuento suave para dormir: ritmo más lento y tono delicado' },
    news: { name: 'Boletín informativo', style: 'Un boletín informativo: dicción clara y ritmo constante' },
    teach: { name: 'Lección', style: 'Explícalo como una lección: tono conversacional, con pausas en los puntos clave' },
    vlog: { name: 'Narración animada', style: 'Ligera y animada, un poco más rápida y con una sonrisa en la voz' },
  },
  statsEmpty: (max: number) => `0 / ${max} caracteres`,
  stats: (n: number, max: number, segments: number, seconds: string) => `${n} / ${max} caracteres · ${segments} ${pluralForm('es', segments, { one: 'segmento', other: 'segmentos' })} · unos ${seconds} s`,
  defaultVoiceOption: (name: string) => `Predeterminada · ${name}`, customVoiceOption: 'Introducir un ID de voz…',
  presetOnly: (model: string) => `${model} solo admite voces predefinidas, por lo que no se puede usar Mis voces`,
  cannotClone: (provider: string) => `${provider} no puede clonar · usa sus voces predefinidas`,
  noConsent: 'No se ha indicado que sea tu voz o que tengas permiso para usarla, por lo que no se subirá a un tercero · añade la declaración en Mis voces',
  cloneStale: (provider: string) => `El clon de ${provider} está desactualizado (la grabación de referencia cambió) · vuelve a subirlo en Mis voces`,
  notCloned: (provider: string) => `Aún no se ha clonado en ${provider} · súbelo una vez en Mis voces`,
  customVoice: 'Voz personalizada', deletedVoice: 'Voz eliminada', myVoices: 'Mis voces', defaultVoice: 'Voz predeterminada',
  cannotSpeak: (model: string, language: string) => `${model} no puede leer ${language}`,
  voiceDeleted: 'La voz elegida se eliminó; elige otra',
  tooLong: (model: string, max: number) => `${model} admite como máximo ${max} caracteres a la vez; primero acorta el texto`,
  enterVoiceId: 'Primero introduce un ID de voz', pickVoice: 'Primero elige una voz', noVoices: 'Este modelo no tiene voces disponibles',
  seedInteger: 'La semilla debe ser un número entero', noModel: 'Aún no hay un modelo de síntesis de voz disponible',
  connectFirst: (provider: string) => `Primero conecta ${provider}`,
  readsMaterial: (model: string, voice: string, name: string) => `${model} · ${voice} · lee el texto de «${name}»`,
  estimate: (seconds: string, chars: number) => ` · unos ${seconds} s · unos ${chars} caracteres`,
  chars: (n: number) => `${n} ${pluralForm('es', n, { one: 'carácter', other: 'caracteres' })}`,
  speech: 'Voz', presetVoices: (n: number) => `${n} ${pluralForm('es', n, { one: 'voz predefinida', other: 'voces predefinidas' })}`,
  customVoiceId: 'ID de voz personalizada', takesStyle: 'Admite indicaciones de estilo',
  speedRange: (min: number, max: number) => `Velocidad ${min}–${max}×`,
  maxChars: (max: number) => `Hasta ${max} caracteres a la vez`,
  headerChip: (provider: string) => `En línea · ${provider} · facturado por uso`,
};
