import { pluralForm } from '@baocut/protocol';
import type { PlayerMessages } from './player-copy.ts';

export const ru: PlayerMessages = {
  surface: (fileName) => `${fileName}: Space — воспроизведение или пауза, стрелки влево и вправо — назад или вперёд`,
  loading: "Загрузка",
  buffering: "Буферизация",
  openFailed: (message) => `Не удалось открыть этот файл: ${message}`,
  subtitles: "Субтитры",
  cueCount: (n) => pluralForm('ru', n, { one: `${n} строка`, few: `${n} строки`, many: `${n} строк`, other: `${n} строки` }),
  subtitleFile: "Файл субтитров",
  noSubtitles: "Без субтитров",
  listFailed: (message) => `Не удалось получить список файлов субтитров: ${message}`,
  finding: "Поиск файлов субтитров…",
  noneNearby: (isAudio) => `В этой папке нет файлов субтитров. Поместите .srt, .vtt или .ass рядом с ${isAudio ? "звук" : "видео"}; файл с тем же именем выбирается автоматически.`,
  noneSelected: "Субтитры не выбраны.",
  reading: (fileName) => `Чтение «${fileName}»…`,
  readFailed: (fileName, message) => `Не удалось прочитать «${fileName}»: ${message}`,
  empty: (fileName) => `Строки не найдены в файле «${fileName}». Поддерживаются SRT, WebVTT и ASS.`,
  unknownFormat: "Нераспознанный формат субтитров",
  tooLarge: "Файл слишком большой",
  fetchFailed: (status) => `Не удалось прочитать файл (${status})`,
  play: "Воспроизвести",
  pause: "Пауза",
  playTip: "Воспроизвести (Space)",
  pauseTip: "Пауза (Space)",
  replayTip: "Воспроизвести снова (Space)",
  overlay: "Наложить субтитры",
  showTip: "Показать субтитры (C)",
  hideTip: "Скрыть субтитры (C)",
  rateCurrent: (rate) => `Скорость воспроизведения ${rate}×`,
  rate: "Скорость воспроизведения",
  rateNormal: "1× (Обычная)",
  mute: "Без звука",
  unmute: "Включить звук",
  muteTip: "Отключить звук (M)",
  unmuteTip: "Включить звук (M)",
  volume: "Громкость",
  fullscreen: "Полный экран",
  exitFullscreen: "Выйти из полного экрана",
  fullscreenTip: "Полный экран (F)",
  exitFullscreenTip: "Выйти из полного экрана (F)",
  position: "Позиция воспроизведения",
  backToCurrent: "Вернуться к текущей строке",
  mediaError: {
    aborted: "Загрузка прервана",
    network: "Ошибка чтения файла",
    decode: "Ошибка декодирования; возможно, файл повреждён",
    unsupported: "BaoCut пока не воспроизводит этот формат или кодек",
    other: "Не удалось воспроизвести этот файл",
  },
};
