import { pluralForm } from '@baocut/protocol';
import type { PlayerMessages } from './player-copy.ts';

export const fr: PlayerMessages = {
  surface: (fileName: string) => `${fileName} : Espace pour lire ou mettre en pause, flèches gauche/droite pour reculer/avancer`,
  loading: "Chargement",
  buffering: "Mise en mémoire tampon",
  openFailed: (message: string) => `Impossible d’ouvrir ce fichier : ${message}`,
  subtitles: "Sous-titres",
  cueCount: (n: number) => `${n} ${pluralForm('fr', n, { one: "ligne", other: "lignes" })}`,
  subtitleFile: "Fichier de sous-titres",
  noSubtitles: "Sans sous-titres",
  listFailed: (message: string) => `Impossible de lister les sous-titres : ${message}`,
  finding: "Recherche de fichiers de sous-titres…",
  noneNearby: (isAudio: boolean) =>
    `Aucun sous-titre dans ce dossier. Placez un .srt, .vtt ou .ass à côté du fichier ${isAudio ? "audio" : "vidéo"} ; celui de même nom sera choisi automatiquement.`,
  noneSelected: "Aucun sous-titre sélectionné.",
  reading: (fileName: string) => `Lecture de « ${fileName} »…`,
  readFailed: (fileName: string, message: string) => `Impossible de lire « ${fileName} » : ${message}`,
  empty: (fileName: string) => `Aucune ligne dans « ${fileName} ». SRT, WebVTT et ASS pris en charge.`,
  unknownFormat: "Format de sous-titres non reconnu",
  tooLarge: "Le fichier est trop volumineux",
  fetchFailed: (status: number) => `Impossible de lire le fichier (${status})`,
  play: "Lire",
  pause: "Pause",
  playTip: "Lire (Space)",
  pauseTip: "Pause (Space)",
  replayTip: "Relire (Space)",
  overlay: "Superposer les sous-titres",
  showTip: "Afficher les sous-titres (C)",
  hideTip: "Masquer les sous-titres (C)",
  rateCurrent: (rate: number) => `Vitesse de lecture ${rate}×`,
  rate: "Vitesse de lecture",
  rateNormal: "1× (normale)",
  mute: "Couper le son",
  unmute: "Réactiver le son",
  muteTip: "Couper le son (M)",
  unmuteTip: "Rétablir le son (M)",
  volume: "Volume",
  fullscreen: "Plein écran",
  exitFullscreen: "Quitter le plein écran",
  fullscreenTip: "Plein écran (F)",
  exitFullscreenTip: "Quitter le plein écran (F)",
  position: "Position de lecture",
  backToCurrent: "Revenir à la ligne actuelle",
  mediaError: {
    aborted: "Chargement interrompu",
    network: "Erreur de lecture du fichier",
    decode: "Décodage en échec ; fichier peut-être endommagé",
    unsupported: "BaoCut ne lit pas encore ce format ou codec",
    other: "Impossible de lire ce fichier",
  },
};
