import { pluralForm } from '@baocut/protocol';
import type { PlayerMessages } from './player-copy.ts';

export const de: PlayerMessages = {
  surface: (fileName: string) => `${fileName}: Space zum Abspielen oder Pausieren, Pfeil links/rechts zum Zurück- oder Vorspringen`,
  loading: "Wird geladen",
  buffering: "Wird gepuffert",
  openFailed: (message: string) => `Diese Datei konnte nicht geöffnet werden: ${message}`,
  subtitles: "Untertitel",
  cueCount: (n: number) => `${n} ${pluralForm('de', n, { one: "Zeile", other: "Zeilen" })}`,
  subtitleFile: "Untertiteldatei",
  noSubtitles: "Ohne Untertitel",
  listFailed: (message: string) => `Untertiteldateien konnten nicht aufgelistet werden: ${message}`,
  finding: "Untertiteldateien werden gesucht…",
  noneNearby: (isAudio: boolean) =>
    `Keine Untertiteldateien im selben Ordner. Eine .srt-, .vtt- oder .ass-Datei neben diese Datei legen: ${isAudio ? "Ton" : "Video"}; gleicher Name wird automatisch ausgewählt.`,
  noneSelected: "Keine Untertitel ausgewählt.",
  reading: (fileName: string) => `Wird gelesen: „${fileName}“…`,
  readFailed: (fileName: string, message: string) => `Lesen fehlgeschlagen: „${fileName}“: ${message}`,
  empty: (fileName: string) => `Keine Zeilen gefunden in „${fileName}“. SRT, WebVTT und ASS werden unterstützt.`,
  unknownFormat: "Nicht erkanntes Untertitelformat",
  tooLarge: "Die Datei ist zu groß",
  fetchFailed: (status: number) => `Datei konnte nicht gelesen werden (${status})`,
  play: "Abspielen",
  pause: "Pause",
  playTip: "Abspielen (Space)",
  pauseTip: "Pause (Space)",
  replayTip: "Erneut abspielen (Space)",
  overlay: "Untertitel überlagern",
  showTip: "Untertitel anzeigen (C)",
  hideTip: "Untertitel ausblenden (C)",
  rateCurrent: (rate: number) => `Wiedergabegeschwindigkeit ${rate}×`,
  rate: "Wiedergabegeschwindigkeit",
  rateNormal: "1× (Normal)",
  mute: "Stummschalten",
  unmute: "Stummschaltung aufheben",
  muteTip: "Stummschalten (M)",
  unmuteTip: "Stummschaltung aufheben (M)",
  volume: "Lautstärke",
  fullscreen: "Vollbild",
  exitFullscreen: "Vollbild verlassen",
  fullscreenTip: "Vollbild (F)",
  exitFullscreenTip: "Vollbild verlassen (F)",
  position: "Wiedergabeposition",
  backToCurrent: "Zurück zur aktuellen Zeile",
  mediaError: {
    aborted: "Laden unterbrochen",
    network: "Beim Lesen der Datei ist ein Fehler aufgetreten",
    decode: "Decodierung fehlgeschlagen; möglicherweise ist die Datei beschädigt",
    unsupported: "BaoCut kann Format oder Codec dieser Datei noch nicht abspielen",
    other: "Diese Datei konnte nicht abgespielt werden",
  },
};
