import type { NodesServerMessages } from './nodes-server.ts';
export const es: NodesServerMessages = {
 taskRequestInvalid: 'Solicitud de tarea no válida', transcribeNotShared: 'El nodo no comparte transcripción', bundleNotReady: 'El paquete de modelos no está disponible en el nodo', inputTooLarge: 'Los medios superan el límite del nodo', diskLow: 'El nodo tiene poco espacio en disco',
 uploadExpired: 'La subida no terminó a tiempo después de crear la tarea', notAwaitingUpload: 'La tarea no está esperando una subida', lengthMismatch: 'La longitud subida no coincide con la declarada', noLongerAwaitingUpload: 'La tarea ya no está esperando una subida', digestMismatch: 'El contenido subido no coincide con el resumen declarado', digestOrLengthMismatch: 'El contenido subido no coincide con el resumen o la longitud declarados',
 notAccepted: 'El nodo no pudo aceptar esta tarea', resultDeleted: 'El resultado se eliminó', taskNotFound: 'La tarea no existe', taskNotCompleted: 'La tarea no ha terminado', idempotencyConflict: 'Mismo clientJobId, pero contenido de solicitud diferente', queueFull: 'Este cliente ha alcanzado su límite de tareas', completedWithoutResult: 'La tarea terminó sin un resultado',
 sourceNotAllowed: 'La dirección de origen no está permitida', protocolTooOld: 'La versión del protocolo es demasiado antigua o falta', pairRequestInvalid: 'Solicitud de emparejamiento no válida', tokenInvalid: 'El token no es válido o está revocado', noEndpoint: 'No existe ese endpoint', methodNotAllowed: 'Este endpoint no admite este método', contentLengthRequired: 'Las subidas deben incluir Content-Length',
 badUrl: 'URL de solicitud no válida', requestFailed: 'El procesamiento de la solicitud falló', bodyTooLarge: 'El cuerpo de la solicitud supera 64 KiB', bodyNotJson: 'El cuerpo de la solicitud no es JSON válido', sinceInvalid: 'since debe ser un entero no negativo', runtimeStopping: 'El Runtime se está deteniendo', sharingOff: 'Compartir no está activado', clientNotFound: 'No existe ese cliente', listSeparator: ', ',
 capabilityNotShareable: (p) => `El nodo no puede compartir esta capacidad: ${p.capability} (compartibles: ${p.shareable})`, pairingLocked: 'El emparejamiento está bloqueado', pairingCodeInvalid: 'El código de emparejamiento es incorrecto, ha caducado o falta', portInUse: (p) => `El puerto ${p.port} ya está en uso`, shareFileUnreadable: (p) => `No se puede leer el archivo de ajustes de uso compartido (node-share.json) (${p.reason}). Se dejó intacto; corrígelo o elimínalo para cambiar el uso compartido`, cannotListen: (p) => `El servicio del nodo no puede escuchar: ${p.code}`,
};
