import type { NodesClientMessages } from './nodes-client.ts';

export const it: NodesClientMessages = {
  badEventStream: (p) => `Il nodo ${p.label} ha restituito una risposta del flusso di eventi non valida`, badResultResponse: (p) => `Il nodo ${p.label} ha restituito una risposta del risultato non valida`, badJson: (p) => `Il nodo ${p.label} non ha restituito JSON valido`, responseTooLarge: (p) => `La risposta del nodo ${p.label} è troppo grande`, nodeReturnedStatus: (p) => `Il nodo ha restituito ${p.status}`, timedOut: (p) => `Il nodo ${p.label} non ha risposto in tempo`, idleTimeout: (p) => `La connessione al nodo ${p.label} è scaduta durante l’inattività`, connectionFailed: (p) => `La connessione al nodo ${p.label} non è riuscita`, connectionFailedCode: (p) => `La connessione al nodo ${p.label} non è riuscita (${p.code})`,
  badStreamLine: 'Il flusso di eventi ha una riga non valida', noHeartbeat: 'Il flusso di eventi ha smesso di inviare heartbeat', streamInterrupted: 'Il flusso di eventi è stato interrotto', streamInterruptedCode: (p) => `Il flusso di eventi è stato interrotto (${p.code})`, labelVersionIncompatible: (p) => `La versione del protocollo del nodo ${p.label} non è compatibile con questo computer`, badPairResponse: (p) => `Il nodo ${p.label} ha restituito una risposta di abbinamento non valida`, pairedNodeNotFound: (p) => `Nessun nodo abbinato: ${p.id}`, labelUnreachable: (p) => `Impossibile raggiungere il nodo ${p.label}`, pairRejected: (p) => `Il nodo ${p.label} ha rifiutato l’abbinamento: ${p.message}`, pairFailed: (p) => `Abbinamento con il nodo ${p.label} non riuscito`, nodeLabel: (p) => `Nodo ${p.alias}`, bundleLabel: (p) => `${p.bundleId} (${p.backend}/${p.device})`,
  tokenUnreadable: (p) => `Questo computer non può leggere il token del nodo: ${p.problem}`, unreachable: 'Impossibile raggiungere questo nodo', versionIncompatible: 'La versione del protocollo del nodo non è compatibile con questo computer', pairingRevoked: 'Il nodo non riconosce più questo abbinamento', transcribeSharingOff: 'Il nodo ha disattivato la condivisione della trascrizione. Attivala su quel computer (baocut share capability transcribe on)', noTranscribeBundle: 'Il nodo non ha un pacchetto di modelli di trascrizione pronto', aliasTaken: (p) => `Un altro nodo usa già questo alias: ${p.alias}`, aliasLength: (p) => `L’alias deve contenere da 1 a ${p.max} caratteri`, tokenNotSaved: (p) => `Il token del nodo non è stato salvato: ${p.message}`, noNodeSpecified: 'Nessun nodo remoto specificato', nodeNotPaired: 'Questo nodo non è più nell’elenco degli abbinamenti su questo computer', tokenUnreadableDefault: 'Impossibile leggere il token', nodeTokenUnavailable: (p) => `Il token del nodo ${p.alias} non è disponibile: ${p.reason}`, noToken: 'Questo computer non ha un token per questo nodo. Abbinalo di nuovo',
  mediaUnreadable: 'Impossibile leggere il file multimediale', mediaTypeMissing: 'Manca il tipo del file multimediale', noBundle: 'Nessun pacchetto di modelli specificato', remoteTaskFailed: 'L’attività non è riuscita sul nodo', cancelledBySharingOff: 'Il nodo ha interrotto la condivisione e annullato l’attività', nodeRestarted: 'Il nodo si è riavviato e l’attività è stata interrotta', completedWithoutOutput: 'Il nodo ha segnalato l’attività come terminata ma non ha fornito un risultato', resultMismatch: 'Il risultato scaricato non corrisponde all’hash o alla lunghezza segnalati dal nodo', badHealth: 'La risposta sullo stato del nodo non è valida', otherNodeAtAddress: 'Ora c’è un nodo diverso a questo indirizzo', bundleNotReady: 'Il pacchetto di modelli non è disponibile sul nodo', capabilityDisabled: (p) => `Il nodo ${p.name} ha disattivato la condivisione della trascrizione. Attivala su quel computer (baocut share capability transcribe on) oppure trascrivi su questo computer o su un altro nodo`, taskGone: 'L’attività non esiste più sul nodo', streamEndedEarly: 'Il flusso di eventi è terminato prima del completamento dell’attività',
  reconnectFailed: (p) => `Connessione al nodo ${p.label} persa e ancora impossibile riconnettersi dopo ${p.seconds} s`, retryFailed: (p) => `Connessione al nodo ${p.label} persa e nuovi tentativi ancora non riusciti dopo ${p.seconds} s`,
};
