import type { RcModelsMessages } from './rc-models.ts';
import { pluralForm } from '../../i18n.ts';

export const it: RcModelsMessages = {
  offlineStrict: 'I modelli non vengono scaricati in modalità rigorosamente offline', sizeChanged: 'Il numero di byte da scaricare è cambiato. Conferma di nuovo con il nuovo piano', bundleInUse: 'Il pacchetto di modelli è in uso. Eliminalo dopo il completamento o l’annullamento delle attività', diarizationNoCheck: 'Il pacchetto del modello di diarizzazione dei parlanti non ha una verifica propria: viene usato insieme al modello di riconoscimento durante la trascrizione', bundleUnavailable: 'Il pacchetto di modelli non è disponibile al momento', installFailed: 'Si è verificato un errore nell’installazione del modello', noSuchBundle: (p) => `Nessun pacchetto di modelli: ${p.bundleId}`, movingDirWait: 'La cartella dei modelli viene spostata. Riprova al termine',
  dirMissing: 'La cartella dei modelli non esiste (accade anche quando un’unità esterna non è collegata). Collegala e riprova oppure scegli un’altra cartella dei modelli nelle Impostazioni', selfTestSampleLabel: 'il campione di verifica del riconoscimento',
  workerFailed: (p) => `Worker non riuscito: ${p.reason}`, workerCancelledCheck: 'Il Worker ha annullato autonomamente la verifica', noWorkerOutput: 'Il Worker non ha prodotto alcun output', outputMissing: 'Il file di output non esiste', outputMismatch: 'La lunghezza o sha256 del file di output non corrisponde alla risposta del Worker', namedOutputMissing: (p) => `Il file di output ${p.file} non esiste`, namedOutputMismatch: (p) => `La lunghezza o sha256 di ${p.file} non corrisponde alla risposta del Worker`, outputNotJson: 'L’output non è JSON valido', outputNotAsrResult: 'L’output non segue il contratto asr-result', transcriptMissingExpected: (p) => `Il testo riconosciuto non contiene «${p.expected}»`,
  separationPassed: (p) => `${p.duration} s · ${p.sampleRate} Hz · voce ${p.finite ? `${p.ratio} dB` : 'molto'} sopra il sottofondo`, speechPassed: (p) => `${p.duration} s · ${p.sampleRate} Hz`, imagePassed: (p) => `${p.width}×${p.height} · ${pluralForm('it', p.steps, { one: `${p.steps} passaggio`, other: `${p.steps} passaggi` })}`,
  envLocked: 'La cartella dei modelli è impostata dalla variabile d’ambiente BAOCUT_MODELS_DIR. Per cambiarla, modifica la variabile e riavvia BaoCut', movingDirWaitOrCancel: 'La cartella dei modelli viene spostata. Cambiala dopo il completamento o l’annullamento dello spostamento', folderMissing: 'Questa cartella non esiste (accade anche quando un’unità esterna non è collegata)', folderNotWritable: 'BaoCut non ha il permesso di scrivere in questa cartella', dirNested: 'La nuova posizione e la cartella dei modelli attuale si contengono a vicenda. Scegli una cartella che non sia al suo interno e non la contenga', noSpaceForMove: 'Il disco della nuova posizione non ha spazio per spostare i modelli', noSpaceRemedy: 'Libera spazio, scegli un’altra posizione o scegli «Cambia solo posizione»', dirInUse: 'Le attività stanno usando modelli locali. Cambia la cartella dopo il completamento o l’annullamento delle attività',
  sourceKept: (p) => pluralForm('it', p.count, { one: `Impossibile eliminare ${p.count} repository nella vecchia cartella. Puoi eliminarlo manualmente`, other: `Impossibile eliminare ${p.count} repository nella vecchia cartella. Puoi eliminarli manualmente` }), moveNoSpace: 'Il disco della nuova posizione si è riempito. Lo spostamento è stato annullato', moveFailed: 'Si è verificato un errore nello spostamento dei modelli. Lo spostamento è stato annullato', moveFailedRemedy: 'La cartella dei modelli originale non è cambiata e i modelli funzionano ancora',
  noAlignableFormat: (p) => `Il modello ${p.modelId} non produce un formato audio allineabile`, synthOutputCount: (p) => pluralForm('it', p.count, { one: `La sintesi vocale ha prodotto ${p.count} risultato; deve produrne 1`, other: `La sintesi vocale ha prodotto ${p.count} risultati; deve produrne 1` }), synthOutputOutsideStaging: 'L’output della sintesi vocale non è nella cartella staging',
  dubGrantHint: (p) => `Il doppiaggio invia la trascrizione (la traduzione e l’originale dove manca una traduzione) a ${p.recipient}. L’autorizzazione predefinita creata all’attivazione di un provider non include trascrizioni, quindi l’utente deve concederla esplicitamente (con il comando sotto o nelle Impostazioni di BaoCut), poi eseguire di nuovo questo doppiaggio.`, voiceRemoved: (p) => `${p.reason}: voce ${p.voice}`,
  notSpeakersJob: 'Questa attività non è un riconoscimento dei parlanti', jobNotForVideo: 'Questo riconoscimento non appartiene a questo video', speakersNotDone: 'Il riconoscimento dei parlanti non è terminato', speakersCleaned: 'I risultati del riconoscimento sono stati rimossi. Riconosci di nuovo i parlanti', recoveryPrincipalName: 'Ripristino dell’attività',
};
