import type { RcModelsMessages } from './rc-models.ts';
import { pluralForm } from '../../i18n.ts';
export const es: RcModelsMessages = {
 offlineStrict: 'No se descargan modelos en modo sin conexión estricto', sizeChanged: 'La cantidad de bytes que descargar cambió. Confirma de nuevo con el plan nuevo', bundleInUse: 'El paquete de modelos está en uso. Elimínalo cuando las tareas terminen o se cancelen', diarizationNoCheck: 'El paquete de modelos de diarización de hablantes no tiene una comprobación propia: se usa junto con el paquete de reconocimiento al transcribir', bundleUnavailable: 'El paquete de modelos no está disponible ahora', installFailed: 'Algo salió mal al instalar el modelo', noSuchBundle: (p) => `No hay un paquete de modelos: ${p.bundleId}`, movingDirWait: 'La carpeta de modelos se está moviendo. Vuelve a intentarlo al terminar', dirMissing: 'La carpeta de modelos no existe (también ocurre cuando una unidad externa no está conectada). Conéctala y vuelve a intentarlo o elige otra carpeta de modelos en Ajustes', selfTestSampleLabel: 'la muestra de comprobación de reconocimiento',
 workerFailed: (p) => `El Worker falló: ${p.reason}`, workerCancelledCheck: 'El Worker canceló la comprobación por sí mismo', noWorkerOutput: 'El Worker no produjo ningún resultado', outputMissing: 'El archivo de resultado no existe', outputMismatch: 'La longitud o sha256 del archivo de resultado no coincide con la respuesta del Worker', namedOutputMissing: (p) => `El archivo de resultado ${p.file} no existe`, namedOutputMismatch: (p) => `La longitud o sha256 de ${p.file} no coincide con la respuesta del Worker`, outputNotJson: 'El resultado no es JSON válido', outputNotAsrResult: 'El resultado no cumple el contrato asr-result', transcriptMissingExpected: (p) => `El texto reconocido no contiene «${p.expected}»`,
 separationPassed: (p) => `${p.duration} s · ${p.sampleRate} Hz · voces ${p.finite ? `${p.ratio} dB` : 'muy'} por encima del fondo`, speechPassed: (p) => `${p.duration} s · ${p.sampleRate} Hz`, imagePassed: (p) => `${p.width}×${p.height} · ${p.steps} pasos`,
 envLocked: 'La carpeta de modelos está establecida por la variable de entorno BAOCUT_MODELS_DIR. Para cambiarla, cambia la variable y reinicia BaoCut', movingDirWaitOrCancel: 'La carpeta de modelos se está moviendo. Cámbiala después de terminar o cancelar el traslado', folderMissing: 'Esta carpeta no existe (también ocurre cuando una unidad externa no está conectada)', folderNotWritable: 'BaoCut no tiene permiso para escribir en esta carpeta', dirNested: 'La ubicación nueva y la carpeta de modelos actual se contienen entre sí. Elige una carpeta que no esté dentro de ella ni la contenga', noSpaceForMove: 'El disco de la ubicación nueva no tiene espacio para mover los modelos', noSpaceRemedy: 'Libera espacio, elige otra ubicación o elige «Cambiar solo la ubicación»', dirInUse: 'Hay tareas usando modelos locales. Cambia la carpeta de modelos cuando terminen o se cancelen',
 sourceKept: (p) => `No se pudieron eliminar ${p.count} ${pluralForm('es', p.count, { one: 'repositorio', other: 'repositorios' })} de la carpeta anterior. Puedes eliminarlos manualmente`, moveNoSpace: 'El disco de la ubicación nueva se llenó. Se revirtió el traslado', moveFailed: 'Algo salió mal al mover los modelos. Se revirtió el traslado', moveFailedRemedy: 'La carpeta de modelos original no ha cambiado y los modelos siguen funcionando',
 noAlignableFormat: (p) => `El modelo ${p.modelId} no produce un formato de audio que se pueda alinear`, synthOutputCount: (p) => `La síntesis de voz produjo ${p.count} resultados; debe producir 1`, synthOutputOutsideStaging: 'El resultado de síntesis de voz no está en la carpeta staging',
 dubGrantHint: (p) => `El doblaje envía la transcripción (la traducción y el original donde falta traducción) a ${p.recipient}. La autorización predeterminada creada al activar un proveedor no incluye transcripciones, por lo que el usuario debe crear una autorización explícita (con el comando de abajo o en Ajustes de BaoCut) y después ejecutar este doblaje de nuevo.`, voiceRemoved: (p) => `${p.reason}: voz ${p.voice}`,
 notSpeakersJob: 'Esta tarea no es reconocimiento de hablantes', jobNotForVideo: 'Este reconocimiento no pertenece a este vídeo', speakersNotDone: 'El reconocimiento de hablantes no ha terminado', speakersCleaned: 'Se limpiaron los resultados de reconocimiento. Reconoce a los hablantes de nuevo', recoveryPrincipalName: 'Recuperación de tareas',
};
