import type { RcPackageMessages } from './rc-package.ts';
import { pluralForm } from '../../i18n.ts';
export const es: RcPackageMessages = {
 localPathPlaceholder: '<ruta local eliminada>', assetsUnreadable: (p) => `No se pueden leer ${p.count} ${pluralForm('es', p.count, { one: 'versión de material', other: 'versiones de material' })}, por lo que el paquete estaría incompleto; búscalas o vuelve a vincularlas, o elige omitir los materiales ausentes`,
 assetsUnreadableRecovery: 'Vuelve a vincular (relinkAsset) o recupera los archivos; o exporta con missingAssets: skip y el manifiesto los marca como ausentes', documentDigestMismatch: (p) => `El cuerpo del documento ${p.documentId}, revisión ${p.revision}, no coincide con su resumen registrado`, documentsContainLocalPaths: 'Algunos documentos contienen rutas locales que un paquete portable no puede incluir; edita esos documentos primero', missingNote: (p) => `No se pudo leer al exportar (${p.reason})`,
 localPathsRemoved: (p) => `Se reemplazaron ${p.count} ${pluralForm('es', p.count, { one: 'ruta local', other: 'rutas locales' })} de la instantánea con un marcador: ${p.places}${p.more ? '…' : ''}`,
 assetNotPackaged: (p) => `No se puede leer la versión de material ${p.key} (${p.reason}); se omitió del paquete y se marcó como ausente en el manifiesto`, filesNotArchivable: 'Algunos archivos no se pueden escribir en el archivo .baocut', insufficientSpace: (p) => `No hay suficiente espacio en el disco de la carpeta de exportación: se necesitan unos ${p.required} y solo quedan ${p.available}`,
 assetReadIncomplete: (p) => `El material «${p.name}» no se pudo leer por completo o se modificó durante la exportación`, assetContentChanged: (p) => `El material «${p.name}» no coincide con su contenido registrado (${p.linked ? 'se modificó el archivo vinculado' : 'el archivo del vídeo está dañado'})`, diskFullWhileWriting: 'El disco de la carpeta de exportación se llenó al escribir el paquete', packageVerifyFailed: (p) => `El paquete escrito no superó la verificación: ${p.error}`, manifestReadBackMismatch: 'El manifiesto leído del paquete escrito difiere del que se escribió',
 tarFileTooLarge: 'Un archivo individual no puede superar 8 GiB (los archivos mayores necesitan encabezados extendidos pax que esta versión no admite)', tarPathTooLong: (p) => `Una ruta del paquete es demasiado larga (máximo ${p.max} bytes)`, archivePathTooLong: (p) => `Una ruta del paquete es demasiado larga: ${p.path}`, archiveFileTooLarge: (p) => `Archivo demasiado grande: ${p.path}`, entryLongerThanExpected: (p) => `${p.path} es más largo de lo esperado: se modificó durante la lectura`, entryShorterThanExpected: (p) => `${p.path} es más corto de lo esperado: se modificó durante la lectura`, archiveHeaderCorrupt: 'El encabezado del archivo está dañado', archiveTruncated: 'El archivo está truncado', archiveChecksumMismatch: 'La suma de verificación del encabezado es incorrecta: el archivo está dañado o no es un paquete .baocut', notUstar: 'No es un archivo POSIX ustar',
 archiveHasLink: (p) => `El paquete contiene un enlace (${p.path}), que no se acepta`, unsafePath: (p) => `Ruta insegura en el paquete: ${p.path}`, unsupportedEntryType: (p) => `El paquete tiene un tipo de entrada no compatible (${p.path})`, duplicateEntry: (p) => `${p.path} aparece dos veces en el paquete`, entryTooLarge: (p) => `${p.path} es demasiado grande`,
 manifestNotJson: 'El manifiesto del paquete no es JSON', notBaocutPackage: 'No es un paquete portable de BaoCut', invalidPackageVersion: 'La versión del paquete no es válida', packageVersionTooNew: (p) => `Este paquete es la versión ${p.version}, pero esta versión de BaoCut solo admite ${p.supported}; ábrelo con un BaoCut más reciente`, manifestMissingFileList: 'El manifiesto del paquete no tiene lista de archivos', manifestIncompleteFile: 'El manifiesto del paquete tiene un registro de archivo incompleto', manifestUnsafePath: (p) => `Ruta insegura en el manifiesto del paquete: ${p.path}`, manifestIncompleteEntry: 'El manifiesto del paquete tiene un registro de revisión incompleto', manifestMissingKey: (p) => `Falta ${p.key} en el manifiesto del paquete`, packageNoManifest: 'El paquete no tiene manifiesto (video.manifest.json)', manifestDuplicate: (p) => `${p.path} aparece dos veces en el manifiesto del paquete`,
 fileNotInManifest: (p) => `El paquete tiene un archivo que no está en el manifiesto: ${p.path}`, fileMissingFromPackage: (p) => `Falta en el paquete un archivo listado en el manifiesto: ${p.path}`, fileLengthMismatch: (p) => `La longitud de ${p.path} no coincide con el manifiesto`, packageNoSnapshot: 'El paquete no tiene instantánea del vídeo (video.snapshot.json)', fileDigestMismatch: (p) => `El contenido de ${p.path} no coincide con el resumen del manifiesto`,
 entryAsset: (p) => `material ${p.ref}`, entryDocument: (p) => `documento ${p.ref}`, entryIncludedWithoutPath: (p) => `${p.what.charAt(0).toUpperCase() + p.what.slice(1)} está marcado como incluido, pero no tiene ruta`, entryDigestMismatch: (p) => `El resumen de contenido de ${p.what} no coincide con el archivo del paquete`, entryFileMissing: (p) => `Falta en el paquete el archivo de ${p.what}`,
};
