import type { RcRuntimeMessages } from './rc-runtime.ts';

export const it: RcRuntimeMessages = {
  noSuchRun: (p) => `Nessuna esecuzione ${p.runId}`, noLoginCommand: (p) => `${p.agent} non ha un comando di accesso`, installKindRequired: 'Specifica come installare o aggiornare (kind)', driverNotRegistered: (p) => `Nessun motore di agente registrato come ${p.driverId}`, runtimeStopping: 'Il Runtime si sta interrompendo',
  scriptNotRun: 'I comandi che scaricano ed eseguono uno script dalla rete non vengono eseguiti in BaoCut: copia il comando ed eseguilo in un terminale oppure usa agents.openTerminal', commandAlreadyRunning: (p) => `${p.agent} ha già un comando in esecuzione`, noInstallKind: (p) => `${p.agent} non ha l’opzione di installazione «${p.kind}»`, commandNotRunnable: (p) => `Questo comando per ${p.agent} non può essere eseguito`, projectNotFound: 'Progetto non trovato', newVideoNeedsTarget: 'Specifica un progetto o una sessione per il nuovo video', attachmentNotFound: 'Allegato non trovato', outputNotFound: 'Risultato non trovato', settingManaged: (p) => `Cambia l’impostazione ${p.key} con ${p.method}`,
  assetHashInvalid: 'L’hash del contenuto del materiale non è valido', assetHasNoPicture: 'Il materiale non ha immagini', onlyAudioVideoAnalyzable: 'Si possono analizzare solo materiali audio e video', noFramesForFileType: 'Non vengono estratti fotogrammi da questo tipo di file', thumbnailTooLarge: 'La miniatura è troppo grande', noFrameAtTime: 'Nessun fotogramma disponibile in questo momento', ffmpegTimeout: 'ffmpeg è scaduto', ffmpegMissing: 'ffmpeg non trovato: installalo, poi riavvia BaoCut', ffmpegCannotRun: (p) => `Impossibile eseguire ffmpeg: ${p.reason}`, ffmpegCannotRead: 'ffmpeg non può leggere questo materiale', cachedThumbnailBroken: 'La miniatura in cache è danneggiata',
  fileNotFound: 'File non trovato', onlyWorkingFolderFiles: 'Si possono aprire solo file nella cartella di lavoro', notAFile: 'Non è un file', folderPathInvalid: 'Percorso della cartella non valido', folderPathMustBeRelative: 'Usa un percorso di cartella relativo alla cartella del progetto', folderOutsideProject: 'La cartella non è nel progetto', folderNotBrowsable: 'Questa cartella non può essere esplorata', folderNotFound: 'Cartella non trovata', notAFolder: 'Non è una cartella', folderUnreadable: 'Impossibile leggere questa cartella', projectFolderNotFound: 'Cartella del progetto non trovata',
  alreadyRunning: (p) => `Il Runtime è già in esecuzione (pid ${p.pid})`, harnessNotReady: 'Harness non è ancora pronto', spaceNotReady: 'Il catalogo dello Space non è ancora pronto', externalToolsNotReady: 'Il servizio degli strumenti esterni non è ancora pronto', externalToolNotRegistered: (p) => `Lo strumento esterno ${p.name} non è registrato`, offlineStrictNoDownload: 'La modalità rigorosamente offline non scarica da link', offlineStrictRemedy: 'Scarica prima il video nel browser, poi scegli il file locale oppure disattiva la modalità rigorosamente offline nelle Impostazioni', noSuchTool: (p) => `Nessuno strumento corrispondente: ${p.toolId}`,
  statusLocalOnly: 'Lo stato del Runtime è disponibile solo alla CLI locale e all’app desktop', stopCliOnly: 'Solo la CLI può chiedere l’interruzione del Runtime', stopNotCliLaunched: 'Questo Runtime non è stato avviato dalla CLI (è stato avviato dall’app desktop o manualmente), quindi la CLI non lo interrompe', runtimeInUse: (p) => `Questo Runtime è ancora in uso (app desktop: ${p.desktop}, altre connessioni CLI: ${p.cli}, attività non completate: ${p.activeJobs}). Attendi il completamento o chiudile, poi interrompilo`, stopNotSupported: 'Questo Runtime non può essere interrotto tramite il gateway',
  legacyPromptGone: "Questa domanda di importazione ha già ricevuto risposta o non è più aperta",
  legacyImportFolderReserved: "Scegli una cartella esterna alle cartelle dati di BaoCut e delle versioni precedenti",
  legacyImportFolderUnwritable: "Impossibile creare questa cartella o scriverci",
  legacyImportLocalOnly: "Solo l’app desktop e la CLI locale possono rispondere alla domanda sull’importazione dei progetti precedenti",
};
