import type { RcSpaceMessages } from './rc-space.ts';

export const fr: RcSpaceMessages = {
  dirUnreadable: (p) => `Impossible de lire le dossier (${p.code})`, tooManyDirEntries: (p) => `Plus de ${p.max} éléments dans le dossier ; seule une partie est listée`, tooManyFiles: (p) => `Plus de ${p.max} fichiers ; seule une partie est listée`, entryGone: 'Cet élément n’est plus dans Space', trashVideoUseDelete: 'Pour supprimer une vidéo, utilisez videos.delete', restoreVideoUseRestore: 'Pour restaurer une vidéo supprimée, utilisez videos.restore', videoDeletedRestoreFirst: 'Cette vidéo a été supprimée. Restaurez-la d’abord', videoDeleted: 'Cette vidéo a été supprimée',
  notInSourceDir: 'Cet élément ne se trouve pas dans un dossier de projet ou de session', stillGeneratingNoFile: 'Génération en cours ; aucun fichier pour le moment', noReadableFile: 'Cet élément n’a pas de fichier lisible', entryStillGeneratingNoFile: 'Cet élément est encore en cours de génération ; aucun fichier pour le moment', entryInTrash: 'Cet élément est dans la corbeille. Restaurez-le d’abord', entryKindNotAccepted: (p) => `Un élément ${p.kind} ne peut pas être utilisé ici`, notVideo: 'Cet élément n’est pas une vidéo',
  projectNotFound: 'Le projet n’existe pas', needAbsolutePath: 'Indiquez le chemin absolu du fichier', fileNotFound: 'Le fichier n’existe pas', unrecognizedFileType: 'Impossible de déterminer le type de ce fichier. Seuls les fichiers vidéo, image, audio, sous-titres et document peuvent être ajoutés', projectDirNotFound: 'Le dossier du projet n’existe pas', hiddenDirFile: 'Les fichiers dans des dossiers cachés ou de dépendances ne peuvent pas être ajoutés', videoDirFile: 'Les fichiers dans un dossier de vidéo appartiennent à la vidéo et ne peuvent pas être ajoutés séparément', tooManySameName: 'Trop de fichiers portant le même nom dans imports/ du projet',
  purgeVideoDeleteFirst: 'Supprimez d’abord la vidéo (videos.delete) pour la déplacer dans la corbeille, puis supprimez-la définitivement depuis la corbeille', purgeTaskRunning: 'La tâche est toujours en cours. Annulez-la d’abord (jobs.cancel)', purgeNotTrashed: 'Déplacez-la d’abord dans la corbeille, puis supprimez-la depuis la corbeille', videoSourceGone: 'La source de cette vidéo a disparu', refRunningTaskUsesVideo: (p) => `La tâche ${p.jobId} en cours utilise cette vidéo`, refTaskAwaitsDecision: (p) => `La tâche ${p.jobId} a des résultats en attente de votre décision pour les ajouter à cette vidéo`,
  refStrayFiles: (p) => `Le dossier de la vidéo contient des fichiers non gérés par la vidéo (${new Intl.ListFormat('fr', { style: 'long', type: 'conjunction' }).format(p.names.split('/'))}${p.total > 3 ? `, ${p.total} au total` : ''}). Restaurez la vidéo et déplacez ces fichiers ailleurs avant la suppression`, refRunningTaskUsesOutput: (p) => `La tâche ${p.jobId} en cours utilise ce résultat`, refVideoUnreadable: (p) => `La vidéo ${p.dir} est illisible pour le moment (ou son index est encore en cours de mise à jour) ; il est donc impossible de confirmer qu’elle n’utilise pas ce fichier`, refVideoAssetLinks: (p) => `Le média « ${p.asset} » de la vidéo « ${p.video} » est lié à ce fichier`,
  importedFileGone: 'Le fichier ajouté n’est plus dans le dossier du projet', resultNotApplied: 'Le résultat n’a pas été appliqué à la vidéo', taskNotFinished: 'La tâche n’est pas terminée', outputFileGone: 'Le fichier de résultat a disparu', exportedFileGone: 'Le fichier exporté a disparu', labelSynthesizeSpeech: 'Voix synthétisée', labelGenerateImage: 'Image générée', labelGenerateText: 'Texte généré', labelExport: 'Export', engineUnavailable: 'Le moteur vidéo est indisponible',
  continueFromTrash: 'Les éléments dans la corbeille ne peuvent pas être poursuivis. Restaurez l’élément d’abord', conversationCantSee: 'Cette session ne peut pas voir cet élément. Les éléments appartenant à un projet doivent être placés dans une session du même projet', serviceUsesMcp: 'Les services externes accèdent à Space via les outils MCP', materialTextOnly: (p) => `Seul le texte des documents .txt et .md et des sous-titres .srt et .vtt peut être lu : ${p.fileName}`, materialTooLarge: (p) => `${p.fileName} fait ${p.bytes} octets, au-delà de la limite de source de ${p.limit}`, afterMaterial: (p) => `Après l’ajout de la source : ${p.reason}`, invalidParams: 'Paramètres invalides',
};
