import type { RcSpaceMessages } from './rc-space.ts';
export const es: RcSpaceMessages = {
 dirUnreadable: (p) => `No se pudo leer la carpeta (${p.code})`, tooManyDirEntries: (p) => `Más de ${p.max} elementos de carpeta; solo se listan algunos`, tooManyFiles: (p) => `Más de ${p.max} archivos; solo se listan algunos`,
 entryGone: 'Este elemento ya no está en Space', trashVideoUseDelete: 'Para eliminar un vídeo, usa videos.delete', restoreVideoUseRestore: 'Para restaurar un vídeo eliminado, usa videos.restore', videoDeletedRestoreFirst: 'Este vídeo se eliminó. Restáuralo primero', videoDeleted: 'Este vídeo se eliminó', notInSourceDir: 'Este elemento no está en una carpeta de proyecto o sesión', stillGeneratingNoFile: 'Aún se está generando; todavía no hay un archivo', noReadableFile: 'Este elemento no tiene un archivo legible', entryStillGeneratingNoFile: 'Este elemento aún se está generando; todavía no hay un archivo', entryInTrash: 'Este elemento está en la Papelera. Restáuralo primero', entryKindNotAccepted: (p) => `No se puede usar aquí un elemento de tipo ${p.kind}`, notVideo: 'Este elemento no es un vídeo',
 projectNotFound: 'El proyecto no existe', needAbsolutePath: 'Proporciona la ruta absoluta del archivo', fileNotFound: 'El archivo no existe', unrecognizedFileType: 'No se puede determinar el tipo de este archivo. Solo se pueden añadir archivos de vídeo, imagen, audio, subtítulos y documentos', projectDirNotFound: 'La carpeta del proyecto no existe', hiddenDirFile: 'No se pueden añadir archivos de carpetas ocultas o de dependencias', videoDirFile: 'Los archivos de una carpeta de vídeo pertenecen al vídeo y no se pueden añadir por separado', tooManySameName: 'Demasiados archivos con el mismo nombre en imports/ del proyecto',
 purgeVideoDeleteFirst: 'Elimina el vídeo primero (videos.delete) para moverlo a la Papelera; después elimínalo permanentemente de ella', purgeTaskRunning: 'La tarea sigue en curso. Cancélala primero (jobs.cancel)', purgeNotTrashed: 'Muévelo a la Papelera primero y después elimínalo de ella', videoSourceGone: 'El origen de este vídeo ya no está', refRunningTaskUsesVideo: (p) => `La tarea ${p.jobId} en curso está usando este vídeo`, refTaskAwaitsDecision: (p) => `La tarea ${p.jobId} tiene resultados pendientes de tu decisión sobre añadirlos a este vídeo`,
 refStrayFiles: (p) => `La carpeta del vídeo tiene archivos que el vídeo no gestiona (${new Intl.ListFormat('es', { style: 'long', type: 'conjunction' }).format(p.names.split('/'))}${p.total > 3 ? `, ${p.total} en total` : ''}). Restaura el vídeo y sácalos antes de eliminar`, refRunningTaskUsesOutput: (p) => `La tarea ${p.jobId} en curso está usando este resultado`, refVideoUnreadable: (p) => `El vídeo ${p.dir} no se puede leer ahora (o su índice sigue actualizándose), por lo que no se puede confirmar que no use este archivo`, refVideoAssetLinks: (p) => `El material «${p.asset}» del vídeo «${p.video}» está vinculado a este archivo`,
 importedFileGone: 'El archivo añadido ya no está en la carpeta del proyecto', resultNotApplied: 'El resultado no se aplicó al vídeo', taskNotFinished: 'La tarea no terminó', outputFileGone: 'El archivo de resultado ya no está', exportedFileGone: 'El archivo exportado ya no está', labelSynthesizeSpeech: 'Voz sintetizada', labelGenerateImage: 'Imagen generada', labelGenerateText: 'Texto generado', labelExport: 'Exportación',
 engineUnavailable: 'El motor de vídeo no está disponible', continueFromTrash: 'No se puede continuar con elementos de la Papelera. Restáuralo primero', conversationCantSee: 'Esta sesión no puede ver este elemento. Los elementos que pertenecen a un proyecto deben ir a una sesión del mismo proyecto', serviceUsesMcp: 'Los servicios externos acceden a Space mediante herramientas MCP', materialTextOnly: (p) => `Solo se puede leer texto de documentos .txt y .md y subtítulos .srt y .vtt: ${p.fileName}`, materialTooLarge: (p) => `${p.fileName} tiene ${p.bytes} bytes, por encima del límite de material de ${p.limit}`, afterMaterial: (p) => `Después de añadir el material: ${p.reason}`, invalidParams: 'Parámetros no válidos',
};
