import type { RcVideoMessages } from './rc-video.ts';
export const es: RcVideoMessages = {
 engineExited: 'El motor de vídeo terminó, por lo que puede que el cambio no se haya confirmado. Reintenta con el mismo comando', engineStartFailed: (p) => `No se pudo iniciar el motor de vídeo: ${p.reason}`, engineNotRunning: 'El motor de vídeo no está en ejecución', engineRequestFailed: (p) => `El motor no pudo procesar ${p.method}`, engineRestarting: 'El motor de vídeo se está reiniciando. Reintenta con el mismo comando en un momento', runtimeStopping: 'El Runtime se está deteniendo', engineNotFound: 'No se encontró el motor de vídeo (engine-host). Primero ejecuta npm run build:engine',
 defaultDirName: 'Vídeo', untitledVideo: 'Vídeo sin título', sourceDirNotFound: 'La carpeta de origen no existe', reservedDirOutsideSource: 'La carpeta reservada no está en la carpeta de origen', videoInUse: 'Este vídeo está abierto', videoNotOpenOpenFirst: 'El vídeo no está abierto. Ábrelo primero', assetVersionNotFound: 'El material o esta versión no existe', videoNotFound: 'El vídeo no existe', onlyWorkspaceVideos: 'Solo se pueden abrir vídeos de la carpeta de trabajo', videoDeletedRestoreFromTrash: 'Este vídeo se eliminó. Restáuralo de la Papelera primero', dirNotVideo: 'Esta carpeta no es un vídeo', linkedPreviewUnsupported: 'Solo se puede previsualizar imágenes, audio, vídeo, fuentes y animaciones Lottie vinculados',
 packageNotFound: 'El paquete portable no existe', packageNotFile: 'El paquete portable debe ser un archivo .baocut', videoInTrash: 'Este vídeo está en la Papelera. Restáuralo primero', videoNotInSourceDir: 'El vídeo no está en una carpeta de proyecto o sesión', cantCreateInSession: 'Este Runtime no puede crear vídeos en una sesión', targetLocationIncomplete: 'La ubicación del vídeo de destino está incompleta', reservedDirOutsideProject: 'La carpeta reservada no está en esta carpeta de proyecto o sesión', pipelinePrincipalName: 'Flujo',
 openElsewhere: 'Este vídeo está abierto en otra ventana o conexión. Ciérralo allí primero', videoBusy: 'Este vídeo aún tiene tareas o exportaciones en curso. Cancélalas primero', crossDevice: 'La carpeta del vídeo y la de origen no están en el mismo disco, por lo que no se puede mover a la Papelera', videoEntryNotFound: 'No se encuentra este vídeo (no está en Space o Space sigue explorando)', notDeletedVideo: 'Este elemento no es un vídeo eliminado', restoreRootGone: 'El proyecto o la sesión donde estaba este vídeo ya no existe, por lo que no se puede restaurar', trashDirGone: 'La carpeta del vídeo en la Papelera ya no está',
 sourceRootInTrash: 'Esta carpeta de vídeo es una carpeta de proyecto o de trabajo de una sesión (o contiene una), por lo que no se puede mover a la Papelera', sourceRootRemedy: 'En BaoCut, primero quita el proyecto o la sesión que la usa como carpeta y después elimina este vídeo desde el proyecto superior',
  compositionImportFailed: (p) => `No se pudo importar el gráfico animado (${p.code})`,
  compositionPreviewFailed: (p) => `No se pudo previsualizar el gráfico animado (${p.code})`,
};
