import type { MainMessages } from './main-copy.ts';

export const fr: MainMessages = {

  about: (app: string) => `À propos de ${app}`,
  services: "Services",
  hide: (app: string) => `Masquer ${app}`,
  hideOthers: "Masquer les autres",
  showAll: "Tout afficher",
  quit: (app: string) => `Quitter ${app}`,
  exit: "Sortie",
  fileMenu: "Fichier",
  closeWindow: "Fermer la fenêtre",
  close: "Fermer",
  editMenu: "Modifier",
  undo: "Annuler",
  redo: "Rétablir",
  cut: "Couper",
  copy: "Copier",
  paste: "Coller",
  pasteAndMatchStyle: "Coller et adapter le style",
  delete: "Supprimer",
  selectAll: "Sélectionner tout",
  speech: "Voix",
  startSpeaking: "Commencer la lecture",
  stopSpeaking: "Arrêter la lecture",
  viewMenu: "Voir",
  reload: "Recharger",
  forceReload: "Forcer le rechargement",
  toggleDevTools: "Afficher les outils de développement",
  actualSize: "Taille réelle",
  zoomIn: "Agrandir",
  zoomOut: "Réduire",
  toggleFullScreen: "Basculer en plein écran",
  windowMenu: "Fenêtre",
  minimize: "Réduire",
  zoom: "Zoom",
  bringAllToFront: "Tout ramener au premier plan",

  openProjectTitle: "Ouvrir le dossier du projet",
  open: "Ouvrir",
  choose: "Choisir",
  importAssetsTitle: "Importer des médias",
  importButton: "Importer",
  mediaFilter: "Vidéos, audio et images",
  allFilesFilter: "Tous les fichiers",
  openFileTitle: "Ouvrir un fichier",
  save: "Enregistrer",

  runtimeNoDiscovery: "Le Runtime a démarré sans écrire son fichier de découverte",
  runtimeTimeout: "Le démarrage du Runtime a pris trop de temps",
  runtimeExited: (code: number | null) => `Le démarrage du Runtime a échoué (code de sortie ${code})`,
  runtimeQuitting: 'L’application se ferme',

  webCreateNotWindow: "Seules les fenêtres de l’application peuvent créer des onglets web",
  webTooManyTabs: "Trop d’onglets web ouverts",
  webTabMissing: "Cet onglet web n’existe plus",
  webClearNotWindow: "Seules les fenêtres de l’application peuvent effacer les données web",
  webOpenNotWindow: "Seules les fenêtres de l’application peuvent ouvrir des liens externes",
  webOpenScheme: "Seules les URL http et https peuvent être ouvertes",
};
