import type { MainMessages } from './main-copy.ts';

export const ko: MainMessages = {
  about: (app: string) => `${app}에 관하여`,
  services: '서비스',
  hide: (app: string) => `${app} 가리기`,
  hideOthers: '기타 가리기',
  showAll: '모두 보기',
  quit: (app: string) => `${app} 종료`,
  exit: '종료',
  fileMenu: '파일',
  closeWindow: '윈도우 닫기',
  close: '닫기',
  editMenu: '편집',
  undo: '실행 취소',
  redo: '다시 실행',
  cut: '잘라내기',
  copy: '복사',
  paste: '붙여넣기',
  pasteAndMatchStyle: '붙여넣고 스타일 일치시키기',
  delete: '삭제',
  selectAll: '모두 선택',
  speech: '말하기',
  startSpeaking: '말하기 시작',
  stopSpeaking: '말하기 중단',
  viewMenu: '보기',
  reload: '새로 고침',
  forceReload: '강력 새로 고침',
  toggleDevTools: '개발자 도구 전환',
  actualSize: '실제 크기',
  zoomIn: '확대',
  zoomOut: '축소',
  toggleFullScreen: '전체 화면 전환',
  windowMenu: '윈도우',
  minimize: '최소화',
  zoom: '확대/축소',
  bringAllToFront: '모두 앞으로 가져오기',

  openProjectTitle: '프로젝트 폴더 열기',
  open: '열기',
  choose: '선택',
  importAssetsTitle: '소재 가져오기',
  importButton: '가져오기',
  mediaFilter: '영상, 오디오, 이미지',
  allFilesFilter: '모든 파일',
  openFileTitle: '파일 열기',
  save: '저장',

  runtimeNoDiscovery: 'Runtime이 시작되었지만 디스커버리 파일을 쓰지 않았습니다',
  runtimeTimeout: 'Runtime이 시작하는 데 너무 오래 걸렸습니다',
  runtimeExited: (code: number | null) => `Runtime을 시작하지 못했습니다(종료 코드 ${code})`,
  runtimeQuitting: '앱을 종료하는 중입니다',

  webCreateNotWindow: '앱 윈도우에서만 웹 탭을 만들 수 있습니다',
  webTooManyTabs: '열린 웹 탭이 너무 많습니다',
  webTabMissing: '이 웹 탭은 더 이상 없습니다',
  webClearNotWindow: '앱 윈도우에서만 웹 데이터를 지울 수 있습니다',
  webOpenNotWindow: '앱 윈도우에서만 외부 링크를 열 수 있습니다',
  webOpenScheme: 'http와 https URL만 열 수 있습니다',
};
