import type { LocalModelsMessages } from './local-models-copy.ts';
export const nl: LocalModelsMessages = { install: {
  availableNote: 'Voor het downloaden zie je de downloadgrootte en de vrije schijfruimte. Je kunt de download pauzeren; gedownloade delen blijven bewaard om later verder te gaan.', download: 'Downloaden', complete: 'Aanvullen', downloadSize: (size: string) => `${size} downloaden`, completeSize: (size: string) => `${size} aanvullen`, resume: 'Download hervatten', pause: 'Pauzeren', cancelDownload: 'Download annuleren', discard: 'Gedownloade delen verwijderen', repair: 'Herstellen…', remove: 'Verwijderen…', more: (id) => `Meer · ${id}`, details: 'Details', hideDetails: 'Details verbergen',
  componentLine: (state, size) => state === 'installed' ? `Geïnstalleerd${size ? ` · ${size}` : ''}` : `Ontbreekt${size ? ` · ${size}` : ''}`, sharedWith: (ids) => `Gedeeld met ${ids.join(', ')}`, noComponents: 'Deze runtime heeft geen componentdetails gemeld.',
  installTitle: (id) => `${id} downloaden`, repairTitle: (id) => `‘${id}’ herstellen?`, completeTitle: (id) => `${id} aanvullen`, planning: 'Download voorbereiden…', verifying: 'Beschadigde of ontbrekende bestanden zoeken. Dit kan bij grote bestanden even duren…', planFailed: 'Kan het downloadplan niet ophalen', upToDate: 'Alle bestanden zijn aanwezig en gecontroleerd. Downloaden is niet nodig.', completeNote: 'Alleen de ontbrekende onderdelen worden gedownload; geïnstalleerde bestanden blijven ongewijzigd.', repairUpToDate: 'Alle bestanden zijn intact. Er hoeft niets opnieuw te worden gedownload.', repairThenCheck: 'Alleen beschadigde of ontbrekende bestanden worden opnieuw gedownload. Intacte bestanden blijven behouden. Na het herstel wordt automatisch opnieuw gecontroleerd.', replanned: 'De downloadgrootte is zojuist veranderd. Controleer het nieuwe plan hieronder en bevestig opnieuw.', source: (url) => `Downloadbron: ${url}`, confirmInstall: (size) => `${size} downloaden`, confirmRepair: 'Herstellen', cancel: 'Annuleren', close: 'Sluiten', started: (id) => `Download van ${id} gestart · De voortgang staat in deze rij en bij de achtergrondtaken`,
  paused: (id) => `${id} gepauzeerd · Gedownloade delen blijven bewaard`, discardTitle: (id) => `De gedownloade delen van ${id} verwijderen?`, discardBody: 'De volgende download begint opnieuw. Componenten die met andere pakketten in download worden gedeeld, blijven behouden.', discarded: (id) => `Gedownloade delen van ${id} verwijderd`, removeTitle: (id) => `${id} verwijderen?`, removeConfirm: 'Verwijderen', stopFailed: (text) => `Kan niet stoppen: ${text}`, removeFailed: (text) => `Kan niet verwijderen: ${text}`, installFailed: (text) => `De vorige download is niet voltooid: ${text}`,
},
  shared: {
    title: 'Gedeelde onderdelen',
    note: 'Meerdere modellen in deze categorie gebruiken ze. Elk onderdeel wordt één keer geïnstalleerd en verwijderd met het laatste model dat het gebruikt.',
    summaryRepair: (n: number) => (n === 1 ? '1 onderdeel aan te vullen' : `${n} onderdelen aan te vullen`),
    summaryCount: (n: number) => (n === 1 ? '1 gedeeld onderdeel' : `${n} gedeelde onderdelen`),
    usage: (live: number, all: number) => `${live === 1 ? '1 geïnstalleerd model gebruikt het' : `${live} geïnstalleerde modellen gebruiken het`} · ${all} hebben het nodig`,
    usageNone: (all: number) => `${all} modellen gaan het gebruiken · nog geen geïnstalleerd`,
    withModel: (size: string | null) => `Wordt gedownload met het eerste model dat je installeert${size ? ` · ${size}` : ''}`,
    completeNote: (name: string) => `Gedeelde onderdelen worden gedownload met een model dat ze gebruikt. Alleen wat ‘${name}’ mist wordt aangevuld; geïnstalleerde bestanden blijven ongewijzigd.`,
  },
};
