import { pluralForm } from '@baocut/protocol';
import type { LocalModelsMessages } from './local-models-copy.ts';

export const pl: LocalModelsMessages = {
  install: {
    availableNote: "Przed pobieraniem zobaczysz rozmiar i wolne miejsce na dysku. Możesz wstrzymać pobieranie; pobrana część zostaje zachowana i jest wznawiana następnym razem.",
    download: "Pobierz",
    complete: "Uzupełnij",
    downloadSize: (size: string) => `Pobierz ${size}`,
    completeSize: (size: string) => `Uzupełnij ${size}`,
    resume: "Wznów pobieranie",
    pause: "Wstrzymaj",
    cancelDownload: "Anuluj pobieranie",
    discard: "Odrzuć pobrane pliki",
    repair: "Napraw…",
    remove: "Usuń…",
    more: (id: string) => `Więcej · ${id}`,
    details: "Szczegóły",
    hideDetails: "Ukryj szczegóły",
    componentLine: (state: 'installed' | 'missing', size: string | null) => (state === 'installed' ? `Zainstalowany${size ? ` · ${size}` : ""}` : `Brak${size ? ` · ${size}` : ""}`),
    sharedWith: (ids: string[]) => `Współdzielone z ${ids.join(", ")}`,
    noComponents: "Ten Runtime nie zgłosił szczegółów komponentów.",

    installTitle: (id: string) => `Najpierw pobierz ${id}`,
    repairTitle: (id: string) => `Napraw „${id}”?`,
    completeTitle: (id: string) => `Uzupełnij ${id}`,
    planning: "Ustalanie plików do pobrania…",
    verifying: "Szukanie uszkodzonych lub brakujących plików. Duże pliki mogą wymagać czasu…",
    planFailed: "Nie udało się uzyskać planu pobierania",
    upToDate: "Wszystkie pliki są obecne i zweryfikowane. Nic do pobrania.",
    completeNote: "Pobierane są tylko brakujące komponenty; zainstalowane pliki pozostają bez zmian.",
    repairUpToDate: "Wszystkie pliki są poprawne. Nic do ponownego pobrania.",
    repairThenCheck: "Ponownie pobierane są tylko uszkodzone lub brakujące pliki; poprawne pozostają bez zmian. Po naprawie następuje automatyczna weryfikacja.",
    replanned: "Rozmiar pobierania właśnie się zmienił. Oto nowy plan; potwierdź ponownie.",
    source: (url: string) => `Źródło pobierania: ${url}`,
    confirmInstall: (size: string) => `Najpierw pobierz ${size}`,
    confirmRepair: "Napraw",
    cancel: "Anuluj",
    close: "Zamknij",
    started: (id: string) => `Pobieranie ${id} · postęp w tym wierszu i w „Zadania w tle”`,

    paused: (id: string) => `Wstrzymano ${id} · pobrana część zachowana`,
    discardTitle: (id: string) => `Odrzuć pobraną część ${id}?`,
    discardBody: "Kolejne pobieranie zacznie się od zera. Pliki pobierane przez inne pakiety modeli i komponenty współdzielone nie zostaną usunięte.",
    discarded: (id: string) => `Odrzucono pobraną część: ${id}`,
    removeTitle: (id: string) => `Usuń ${id}?`,
    removeConfirm: "Usuń",
    stopFailed: (text: string) => `Nie udało się zatrzymać: ${text}`,
    removeFailed: (text: string) => `Nie udało się usunąć: ${text}`,
    installFailed: (text: string) => `Ostatnie pobieranie nie zostało ukończone: ${text}`,
  },
  shared: {
    title: "Wspólne komponenty",
    note: "Korzysta z nich kilka modeli tej kategorii. Każdy instaluje się raz i jest usuwany razem z ostatnim modelem, który go używa.",
    summaryRepair: (n: number) => `Do uzupełnienia: ${pluralForm("pl", n, { one: `${n} komponent`, few: `${n} komponenty`, many: `${n} komponentów`, other: `${n} komponentu` })}`,
    summaryCount: (n: number) => pluralForm("pl", n, { one: `${n} wspólny komponent`, few: `${n} wspólne komponenty`, many: `${n} wspólnych komponentów`, other: `${n} wspólnego komponentu` }),
    usage: (live: number, all: number) => `Używany przez zainstalowane modele: ${live} · potrzebny modelom: ${all}`,
    usageNone: (all: number) => `Potrzebny modelom: ${all} · żaden nie jest jeszcze zainstalowany`,
    withModel: (size: string | null) => `Pobierany razem z pierwszym instalowanym modelem${size ? ` · ${size}` : ""}`,
    completeNote: (name: string) => `Wspólne komponenty pobierają się razem z modelem, który ich używa. Uzupełniane jest tylko to, czego brakuje modelowi „${name}”; zainstalowane pliki pozostają bez zmian.`,
  },
};
