import type { LocalModelsMessages } from './local-models-copy.ts';

export const zhHans: LocalModelsMessages = {
  install: {
    availableNote: '下载前先给你看要下载多少、磁盘还剩多少。下载中可以暂停，已经下载的部分留着，下次接着下。',
    download: '下载',
    complete: '补齐',
    downloadSize: (size: string) => `下载 ${size}`,
    completeSize: (size: string) => `补齐 ${size}`,
    resume: '继续下载',
    pause: '暂停',
    cancelDownload: '取消下载',
    discard: '丢掉已下载的',
    repair: '修复…',
    remove: '删除…',
    more: (id: string) => `更多 · ${id}`,
    details: '详情',
    hideDetails: '收起详情',
    componentLine: (state: 'installed' | 'missing', size: string | null) => (state === 'installed' ? `已装${size ? ` · ${size}` : ''}` : `缺${size ? ` · ${size}` : ''}`),
    sharedWith: (ids: string[]) => `与 ${ids.join('、')} 共用`,
    noComponents: '这个 Runtime 没有报告组件明细。',
    // 确认对话框
    installTitle: (id: string) => `下载 ${id}`,
    repairTitle: (id: string) => `修复「${id}」？`,
    completeTitle: (id: string) => `补齐 ${id}`,
    planning: '正在算要下载什么…',
    verifying: '正在找出坏掉或缺失的文件，文件大时要一会儿…',
    planFailed: '没能拿到下载计划',
    upToDate: '文件都齐全、校验无误，不用下载。',
    completeNote: '模型已经装好，只下载缺的可选组件，装好的文件不动。',
    repairUpToDate: '文件都完好，没有要重新下载的。',
    repairThenCheck: '只重新下载坏掉或缺失的文件，完好的不动。修好后会自动再检查一次。',
    replanned: '要下载的大小刚刚变了，下面是新的计划，再确认一次。',
    source: (url: string) => `下载来源：${url}`,
    confirmInstall: (size: string) => `下载 ${size}`,
    confirmRepair: '修复',
    cancel: '取消',
    close: '关闭',
    started: (id: string) => `开始下载 ${id} · 进度在这一行，也在后台任务里`,
    // 停下与删除
    paused: (id: string) => `已暂停 ${id} · 已经下载的部分留着`,
    discardTitle: (id: string) => `丢掉 ${id} 已下载的部分？`,
    discardBody: '下次要从头下载。别的模型包正在下载、共用的组件不会删。',
    discarded: (id: string) => `已丢掉 ${id} 已下载的部分`,
    removeTitle: (id: string) => `删除 ${id}？`,
    removeConfirm: '删除',
    stopFailed: (text: string) => `没能停下：${text}`,
    removeFailed: (text: string) => `没能删除：${text}`,
    installFailed: (text: string) => `上次下载没有完成：${text}`,
  },
  shared: {
    title: '公共组件',
    note: '这一类的多只模型共用，装一次就够；最后一只用它的模型删除时一起回收。',
    summaryRepair: (n: number) => `${n} 个组件待补全`,
    summaryCount: (n: number) => `${n} 个共享组件`,
    usage: (live: number, all: number) => `${live} 个已装模型在用 · 共 ${all} 个需要`,
    usageNone: (all: number) => `${all} 个模型会用到 · 暂无已装`,
    withModel: (size: string | null) => `装模型时一起下载${size ? ` · ${size}` : ''}`,
    completeNote: (name: string) => `公共组件跟着用到它的模型下载：这次只补上「${name}」缺的部分，装好的文件不动。`,
  },
};
