import type { LocalModelsMessages } from './local-models-copy.ts';

export const pl: LocalModelsMessages = {
  install: {
    availableNote: "Przed pobieraniem zobaczysz rozmiar i wolne miejsce na dysku. Możesz wstrzymać pobieranie; pobrana część zostaje zachowana i jest wznawiana następnym razem.",
    download: "Pobierz",
    resume: "Wznów pobieranie",
    pause: "Wstrzymaj",
    cancelDownload: "Anuluj pobieranie",
    discard: "Odrzuć pobrane pliki",
    repair: "Napraw…",
    remove: "Usuń…",
    more: (id: string) => `Więcej · ${id}`,
    details: "Szczegóły",
    hideDetails: "Ukryj szczegóły",
    componentLine: (state: 'installed' | 'missing', size: string | null) => (state === 'installed' ? `Zainstalowany${size ? ` · ${size}` : ""}` : "Brak"),
    sharedWith: (ids: string[]) => `Współdzielone z ${ids.join(", ")}`,
    noComponents: "Ten Runtime nie zgłosił szczegółów komponentów.",

    installTitle: (id: string) => `Najpierw pobierz ${id}`,
    repairTitle: (id: string) => `Napraw „${id}”?`,
    planning: "Ustalanie plików do pobrania…",
    verifying: "Szukanie uszkodzonych lub brakujących plików. Duże pliki mogą wymagać czasu…",
    planFailed: "Nie udało się uzyskać planu pobierania",
    upToDate: "Wszystkie pliki są obecne i zweryfikowane. Nic do pobrania.",
    repairUpToDate: "Wszystkie pliki są poprawne. Nic do ponownego pobrania.",
    repairThenCheck: "Ponownie pobierane są tylko uszkodzone lub brakujące pliki; poprawne pozostają bez zmian. Po naprawie następuje automatyczna weryfikacja.",
    replanned: "Rozmiar pobierania właśnie się zmienił. Oto nowy plan; potwierdź ponownie.",
    source: (url: string) => `Źródło pobierania: ${url}`,
    confirmInstall: (size: string) => `Najpierw pobierz ${size}`,
    confirmRepair: "Napraw",
    cancel: "Anuluj",
    close: "Zamknij",
    started: (id: string) => `Pobieranie ${id} · postęp w tym wierszu i w „Zadania w tle”`,

    paused: (id: string) => `Wstrzymano ${id} · pobrana część zachowana`,
    discardTitle: (id: string) => `Odrzuć pobraną część ${id}?`,
    discardBody: "Kolejne pobieranie zacznie się od zera. Pliki pobierane przez inne pakiety modeli i komponenty współdzielone nie zostaną usunięte.",
    discarded: (id: string) => `Odrzucono pobraną część: ${id}`,
    removeTitle: (id: string) => `Usuń ${id}?`,
    removeConfirm: "Usuń",
    stopFailed: (text: string) => `Nie udało się zatrzymać: ${text}`,
    removeFailed: (text: string) => `Nie udało się usunąć: ${text}`,
    installFailed: (text: string) => `Ostatnie pobieranie nie zostało ukończone: ${text}`,
  },
};
