import type { LocalModelsMessages } from './local-models-copy.ts';

export const ru: LocalModelsMessages = {
  install: {
    availableNote: "Перед скачиванием будет показан размер и свободное место на диске. Можно приостановить скачивание; скачанная часть сохраняется и будет использована при продолжении.",
    download: "Скачать",
    resume: "Продолжить скачивание",
    pause: "Пауза",
    cancelDownload: "Отменить скачивание",
    discard: "Отбросить скачанные файлы",
    repair: "Восстановить…",
    remove: "Удалить…",
    more: (id: string) => `Ещё · ${id}`,
    details: "Подробности",
    hideDetails: "Скрыть подробности",
    componentLine: (state: 'installed' | 'missing', size: string | null) => (state === 'installed' ? `Установлено${size ? ` · ${size}` : ""}` : "Отсутствует"),
    sharedWith: (ids: string[]) => `Общее с ${ids.join(", ")}`,
    noComponents: "Этот Runtime не сообщил сведения о компонентах.",

    installTitle: (id: string) => `Сначала скачайте ${id}`,
    repairTitle: (id: string) => `Восстановить «${id}»?`,
    planning: "Определение файлов для скачивания…",
    verifying: "Поиск повреждённых или отсутствующих файлов. Для больших файлов это может занять время…",
    planFailed: "Не удалось получить план скачивания",
    upToDate: "Все файлы присутствуют и проверены. Скачивать нечего.",
    repairUpToDate: "Все файлы целы. Скачивать заново нечего.",
    repairThenCheck: "Заново скачиваются только повреждённые или отсутствующие файлы; целые не изменяются. После восстановления проверка выполняется автоматически.",
    replanned: "Размер скачивания изменился. Новый план ниже; подтвердите снова.",
    source: (url: string) => `Источник скачивания: ${url}`,
    confirmInstall: (size: string) => `Сначала скачайте ${size}`,
    confirmRepair: "Восстановить",
    cancel: "Отмена",
    close: "Закрыть",
    started: (id: string) => `Скачивание ${id} · прогресс в этой строке и в «Фоновые задачи»`,

    paused: (id: string) => `Приостановлено ${id} · скачанная часть сохранена`,
    discardTitle: (id: string) => `Отбросить скачанную часть ${id}?`,
    discardBody: "Следующее скачивание начнётся с нуля. Файлы, скачиваемые другими пакетами моделей, и общие компоненты не удаляются.",
    discarded: (id: string) => `Скачанная часть отброшена: ${id}`,
    removeTitle: (id: string) => `Удалить ${id}?`,
    removeConfirm: "Удалить",
    stopFailed: (text: string) => `Не удалось остановить: ${text}`,
    removeFailed: (text: string) => `Не удалось удалить: ${text}`,
    installFailed: (text: string) => `Последнее скачивание не завершено: ${text}`,
  },
};
