import { pluralForm } from '@baocut/protocol';
import type { OnlineCapability } from '@baocut/protocol';
import type { RefreshKind } from '../../model/models-cloud.ts';
import type { ModelsMessages } from './models-copy.ts';

export const pl: ModelsMessages = {
  page: {
    title: "Modele",
    nav: "Nawigacja modeli",
    navSection: "Funkcje",
    categories: "Kategorie modeli",
    tabs: (label: string) => `${label} – zarządzanie modelami`,
    offline: "Modele pojawią się po połączeniu z Runtime.",
    loading: "Wczytywanie modeli…",
    goAgent: "Przejdź do Ustawienia › Agent",
  },
  local: {
    defaultLabel: "Domyślny model",
    defaultDesc: "Wstępnie wybrane dla nowych wideo i używane do transkrypcji z wiersza poleceń.",

    separateDefaultDesc: "Używane do oddzielania audio tła tłumaczonego lektora bez wskazanego modelu oraz do lektora z wiersza poleceń.",
    auto: "Automatycznie",
    autoUses: (id: string) => `Wybór automatyczny używa teraz ${id}.`,
    otherDefault: (name: string) => `Domyślnie teraz ${name} (ustawione w modelach chmurowych); wybór lokalnego modelu zastąpi to ustawienie.`,
    defaultSet: "Ustawiono model domyślny",
    defaultFailed: (message: string) => `Nie udało się ustawić modelu domyślnego: ${message}`,
    installed: "Zainstalowany",
    available: "Dostępna do pobrania",
    emptyInstalled: "Nie zainstalowano jeszcze modeli.",
    emptyAvailable: "Wszystkie modele tej kategorii są zainstalowane.",
    remove: "Usuń",
    reenable: "Włącz ponownie",
    reenabled: (id: string) => `Włączono ponownie ${id}`,
    reenableFailed: (message: string) => `Nie udało się włączyć ponownie: ${message}`,
    emptyTitle: (label: string) => `Brak lokalnych modeli dla ${label} jeszcze`,
    emptyBody: "Folder modeli na tym komputerze przechowuje tylko pakiety rozpoznawania i syntezy mowy, generowania obrazów oraz separacji źródeł. Lokalne modele tej kategorii nie są jeszcze obsługiwane.",
  },
  imageLocal: {
    defaultDesc: "Wstępnie wybrane dla nowych zadań obrazów. Bez modelu domyślnego wybierasz za każdym razem; ręczny wybór ma pierwszeństwo.",
    cloudDefault: (name: string) => `Domyślny jest model w chmurze (${name}); zmień w Ustawienia › Modele w chmurze. Wybranie lokalnego przełącza na niego.`,
    noInstalled: "Nie zainstalowano jeszcze modelu obrazów. Najpierw pobierz go poniżej.",
    licenseUse: "Wygenerowane obrazy można używać tylko niekomercyjnie; do komercyjnych wideo wybierz inny model obrazów.",

    tryButton: "Wypróbuj",
    tryTitle: (name: string) => `Wypróbuj ${name}`,
    tryPromptTitle: "Prompt testowy · jeden obraz 512 × 512",
    tryPromptLabel: "Podpowiedź testowa",
    tryPlaceholder: "Opisz obraz",
    tryChars: (n: number, max: number) => `${n} / ${max} znaków`,
    trySample: "Inny przykład",
    tryFacts: (steps: number) => `1:1 · 512 × 512 · ${steps} kroków · 1 obraz · offline · zajmuje miejsce ciężkich zadań tego komputera`,
    tryNote: "Tworzy mały obraz na tym komputerze bez sieci, aby sprawdzić efekt. Zajmuje miejsce ciężkich zadań, więc inne lokalne zadania modeli czekają. Zamknięcie okna nie zatrzymuje działania; jest też na liście zadań w tle.",
    tryReady: "Gotowe do uruchomienia",
    tryRunning: (steps: number) => `Tworzenie 512² · ${steps} kroków…`,
    tryDone: (seconds: number | null) => (seconds !== null ? `Gotowe · ${seconds}s` : "Gotowe"),
    tryFailed: "Nie udało się utworzyć obrazu",
    tryResult: "Wynik testu",
    tryImageAlt: "Obraz wygenerowany w teście",
    tryOpenFailed: (message: string) => `Nie udało się otworzyć obrazu wyniku: ${message}`,
    tryWhere: "Jak inne generowane obrazy, wynik jest w Narzędzia › Generuj obraz i nie trafia do wideo",
    tryDownload: "Pobierz obraz",
    tryCopy: "Kopiuj prompt",
    tryClose: "Zamknij",
    tryStopWaiting: "Przestań czekać",
    tryStart: "Rozpocznij generowanie",
    tryAgain: "Wygeneruj kolejny",
    tryBusy: "Generowanie…",
    tryFileName: (id: string) => `image-try-${id}`,
  },
  cloud: {
    heading: {
      transcribe: "Zmień mowę w transkrypcję",
      synthesizeSpeech: "Czytanie tekstu na głos",
      generateImage: "Zamieniaj opisy w obrazy",
      generateText: "Tłumacz napisy i generuj tekst",
    } satisfies Record<OnlineCapability, string>,
    lede: {
      transcribe: "Przyjmuje audio i zwraca rozpoznany tekst. Rozpoznawanie mowy ma jeden model domyślny, wspólny ze stroną lokalnych modeli.",
      synthesizeSpeech: "Przyjmuje tekst i zwraca mowę. Dostępne przy generowaniu mowy i lektora; online i płatne, zwykle za znak.",
      generateImage:
        "Przyjmuje prompt i zwraca obraz. Dostępne przy generowaniu obrazów; online, płatne za obraz. Codex CLI też rysuje bez klucza, korzystając z abonamentu Codex. Przełącznik jest na pierwszej karcie dostawców poniżej.",
      generateText: "Przyjmuje instrukcje tekstowe i zwraca tekst. Używane do tłumaczenia napisów, tłumaczonego lektora i Narzędzia › Generuj tekst; online, płatne za token.",
    } satisfies Record<OnlineCapability, string>,
    defaultLabel: {
      transcribe: "Domyślny model mowy w chmurze",
      synthesizeSpeech: "Domyślny chmurowy model syntezy mowy",
      generateImage: "Domyślny chmurowy model obrazów",
      generateText: "Domyślny model tekstowy",
    } satisfies Record<OnlineCapability, string>,
    defaultDesc: {
      transcribe: "Używane przy transkrypcji bez wskazanego modelu. Model domyślny jest jeden: chmurowy zastępuje wybór lokalny; „Użyj lokalnego modelu” usuwa chmurowy wybór i przywraca lokalny wybór automatyczny.",
      synthesizeSpeech: "Dla mowy lub lektora bez wskazanego modelu. „Wybieraj za każdym razem” oznacza brak domyślnego modelu: żądania bez modelu są odrzucane, wybierasz przy użyciu.",
      generateImage:
        "Dla obrazów, bcut image lub agenta bez wskazanego modelu. Codex nigdy nie jest wybierany automatycznie; wybierz go tutaj jako domyślny. „Wybieraj za każdym razem” oznacza wybór podczas generowania.",
      generateText:
        "Dla tłumaczenia napisów, tłumaczonego lektora lub tekstu bez wskazanego modelu. „Wybieraj za każdym razem” oznacza brak domyślnego modelu: Runtime nie wybiera za ciebie i odrzuca żądania bez modelu.",
    } satisfies Record<OnlineCapability, string>,

    localDefaultDesc: "Ustawione na stronie lokalnych modeli · „Wybieraj za każdym razem” usuwa wybór",
    none: { transcribe: "Użyj lokalnego modelu", synthesizeSpeech: "Wybieraj za każdym razem", generateImage: "Wybieraj za każdym razem", generateText: "Wybieraj za każdym razem" } satisfies Record<OnlineCapability, string>,
    noneDesc: {
      transcribe: "Wróć do automatycznego wyboru na stronie lokalnych modeli",
      synthesizeSpeech: "Wybieraj przy generowaniu mowy lub lektora",
      generateImage: "Wybieraj przy generowaniu obrazów",
      generateText: "Wybieraj przy użyciu (Runtime nie wybierze za ciebie)",
    } satisfies Record<OnlineCapability, string>,
    codexItem: "Codex CLI · Obrazy",
    codexItemDesc: "Abonament Codex · jeden obraz naraz · 5–10× wolniej",
    unavailable: "Niedostępne",
    pickerEmpty: { image: "Połącz dostawcę lub włącz obrazy Codex, aby wybrać", other: "Podłącz dostawcę, aby wybrać" },
    defaultSet: "Zmieniono model domyślny",
    defaultFailed: (message: string) => `Nie udało się zmienić modelu domyślnego: ${message}`,
    providers: "Dostawcy",
    providersDesc: "Wszystkie typy modeli dostawcy używają wspólnego klucza. Wynik testu dotyczy tylko testowanego modelu.",
    providersExtra: {
      transcribe: "",
      synthesizeSpeech: " Synteza mowy jest zwykle płatna za znak.",
      generateImage: " Obrazy są płatne za obraz; obowiązują warunki użycia dostawcy.",
      generateText: " Tekst jest płatny za token.",
    } satisfies Record<OnlineCapability, string>,
    addCustom: "Dodaj niestandardowego dostawcę",
    connected: "Połączono",
    manageKey: "Zarządzaj kluczem",
    connect: "Połącz",
    addModel: "Dodaj model",
    defaultChip: "Domyślny",
    expand: (name: string) => `Pokaż ${name} modeli`,
    collapse: (name: string) => `Ukryj ${name} modeli`,
    probe: { transcribe: "Próbna mowa", synthesizeSpeech: "Testuj syntezę", generateImage: "Testuj obraz", generateText: "Generowanie testów" } satisfies Record<OnlineCapability, string>,
    probeUnsupported: "Osobny test nie jest jeszcze dostępny",
    headNoModels: (kind: string) => `Brak modeli dla ${kind} · dodaj poniżej; używa tego klucza`,
    headCustomOff: "Niepołączone · Własne · po połączeniu dodaj modele dla każdego zastosowania",
    headOff: (first: string, total: number) => `Niepołączone · ${first}${total > 1 ? ` i ${pluralForm('pl', total - 1, { one: `${total - 1} dodatkowy model`, few: `${total - 1} dodatkowe modele`, many: `${total - 1} dodatkowych modeli`, other: `${total - 1} dodatkowego modelu` })}` : ""} · połącz, aby testować i ustawić domyślny model`,
    headCount: (total: number) => pluralForm('pl', total, { one: `${total} model`, few: `${total} modele`, many: `${total} modeli`, other: `${total} modelu` }),
    headDefault: (id: string) => ` · Domyślnie: ${id}`,

    refresh: { models: "Odśwież modele", voices: "Odśwież katalog głosów" } satisfies Record<RefreshKind, string>,
    refreshNeedsKey: (label: string) => `${label} (najpierw połącz klucz)`,
    refreshing: { models: "Odświeżanie modeli…", voices: "Odświeżanie katalogu głosów…" } satisfies Record<RefreshKind, string>,
    refreshFailedLine: { models: "Nie udało się odświeżyć modeli", voices: "Nie udało się odświeżyć głosów" } satisfies Record<RefreshKind, string>,
    builtinModels: "Lista wbudowana · odśwież, aby zobaczyć modele dostępne dla tego klucza",
    builtinVoices: (models: number, voices: number) => `${pluralForm('pl', models, { one: `${models} model`, few: `${models} modele`, many: `${models} modeli`, other: `${models} modelu` })} · ${pluralForm('pl', voices, { one: `${voices} głos`, few: `${voices} głosy`, many: `${voices} głosów`, other: `${voices} głosu` })} · katalog wbudowany · odśwież, aby zobaczyć głosy dostępne dla tego klucza`,
    freshModels: (models: number, ago: string) => `${pluralForm('pl', models, { one: `${models} model`, few: `${models} modele`, many: `${models} modeli`, other: `${models} modelu` })} · zaktualizowano ${ago}`,
    freshVoices: (models: number, voices: number, ago: string) => `${pluralForm('pl', models, { one: `${models} model`, few: `${models} modele`, many: `${models} modeli`, other: `${models} modelu` })} · ${pluralForm('pl', voices, { one: `${voices} głos`, few: `${voices} głosy`, many: `${voices} głosów`, other: `${voices} głosu` })} · odświeżono ${ago}`,
    unusable: (n: number) => ` · ${n} niedostępne dla tego klucza`,
    refreshFailed: (message: string) => `Nie udało się odświeżyć: ${message}`,
    modelVoices: (n: number) => (n ? `${pluralForm('pl', n, { one: `${n} gotowy głos`, few: `${n} gotowe głosy`, many: `${n} gotowych głosów`, other: `${n} gotowego głosu` })}` : "Brak gotowych głosów · test wymaga ID głosu"),
    modelSizes: (sizes: string[], max: number) => `${sizes.length ? sizes.join(" / ") : "Rozmiar ustala usługa"} · do ${pluralForm('pl', max, { one: `${max} obraz`, few: `${max} obrazy`, many: `${max} obrazów`, other: `${max} obrazu` })} naraz`,
    customTag: "Niestandardowe",
    emptyProviders: "Brak chmurowych dostawców tej kategorii. Można dodać własną usługę zgodną z OpenAI.",
    noCloud: "Ta kategoria nie ma modeli chmurowych.",
  },
  textParams: {
    effort: "Intensywność rozumowania",
    effortDesc: "Dotyczy tylko modeli z rozumowaniem: brak poziomu oznacza najbliższy, modele bez regulacji go ignorują. „Auto” używa domyślnego ustawienia modelu.",
    effortCount: (tunable: number, total: number) => total ? `Można dostroić ${tunable} z ${pluralForm('pl', total, { one: `${total} połączonego modelu`, few: `${total} połączonych modeli`, many: `${total} połączonych modeli`, other: `${total} połączonego modelu` })}.` : "",
    concurrency: "Równoczesne żądania",
    concurrencyDesc: (min: number, max: number) => `Maksimum równoczesnych żądań tekstowych do każdego dostawcy (${min}–${max}), wspólne dla tłumaczenia napisów i generowania tekstu. Zmniejsz przy limitach częstotliwości.`,
    saved: "Zapisano",
    failed: (message: string) => `Nie udało się zapisać: ${message}`,
  },
  codexCard: {
    title: "Codex CLI",
    on: "Włączone · abonament Codex, bez klucza · jeden obraz naraz · ignoruje rozmiar · 5–10× wolniej",
    off: "Wyłączone · włącz, aby wybierać przy generowaniu obrazów i jako domyślny model",
    missing: "Nie znaleziono Codex · zainstaluj Codex CLI i zaloguj się przed rysowaniem.",
    switchLabel: "Rysuj z Codex",
    toggleFailed: (enabled: boolean, message: string) => `Nie udało się ${enabled ? "wł." : "wył."} obrazy Codex: ${message}`,
  },
  key: {
    title: (name: string) => `${name} · klucz API`,
    shared: (name: string, kinds: string) => `Ten klucz jest wspólny dla wszystkich ${name} modeli (${kinds}); wpisz raz dla wszystkich list.`,
    sharedCustom: (name: string) => `Ten klucz jest wspólny dla wszystkich ${name} modeli. Można dodać rozpoznawanie mowy, tekst, syntezę mowy i obrazy; klucz wpisujesz raz.`,
    field: "Klucz API",
    fieldCustom: "Zostaw puste, jeśli usługa nie wymaga klucza.",
    endpoint: (url: string) => `Base URL · ${url}`,
    keep: "Klucz już zapisano. Zostaw puste, aby go zachować i tylko ponownie zweryfikować.",
    verifyNote: "Przed zapisaniem do dostawcy trafia żądanie tylko odczytu sprawdzające klucz; błąd oznacza brak zapisu. Klucz jest tylko na tym komputerze i nie zostanie pokazany ponownie.",
    removeKey: "Usuń klucz",
    removeProvider: "Usuń dostawcę",
    cancel: "Anuluj",
    save: "Zweryfikuj i zapisz",
    saved: (name: string) => `Połączono: ${name}`,
    failed: (message: string) => message,
    removed: (name: string) => `Usunięto ${name} klucz`,
    providerRemoved: (name: string) => `Usunięto: ${name}`,
    removeFailed: (message: string) => `Nie udało się usunąć: ${message}`,
    confirmTitle: (name: string) => `Usuń „${name}”?`,
    confirmBody: "Zadeklarowane modele są usuwane z kluczem. Wskazujące na nie ustawienia domyślne zostają i są pokazane jako niedostępne.",
    confirm: "Usuń",
  },
  custom: {
    title: "Dodaj niestandardowego dostawcę",
    name: "Nazwa dostawcy",
    url: "Podstawa URL",
    urlPlaceholder: "https://api.example.com/v1",
    model: "ID pierwszego modelu",
    kind: "Wybierz",
    voices: "ID głosów",
    voicesPlaceholder: "Oddzielone przecinkami (opcjonalne) · np. zh-female, zh-male",
    taken: (name: string) => `Ten URL już dodano jako „${name}”. Dodaj w nim modele, aby używać wspólnego klucza.`,
    takenAction: (name: string) => `Dodaj do „${name}”`,
    note: {
      transcribe: "Wymagana transkrypcja audio (/v1/audio/transcriptions); endpointy tylko czatu nie rozpoznają mowy.",
      synthesizeSpeech: "Wymagane /v1/audio/speech; bez ID głosów podaj głos przy użyciu.",
      generateImage: "Wymagane /v1/images/generations; zachowawcze ustawienia rozmiaru (1024 × 1024, jeden obraz naraz).",
      generateText: "Wymagane /v1/chat/completions; zachowawcze limity kontekstu i wyjścia (32K i 4K tokenów).",
    } satisfies Record<OnlineCapability, string>,
    noteHead: "Usługa zgodna z OpenAI. ",
    noteTail: " Po dodaniu połącz (wpisz klucz lub zostaw puste) i przetestuj model.",
    add: "Dodaj",
    added: (name: string) => `Dodano: ${name} · następnie połącz`,
    failed: (message: string) => `Nie udało się dodać: ${message}`,
  },
  kindLabel: {
    transcribe: "Rozpoznawanie mowy · ASR",
    generateText: "Generowanie tekstu · LLM",
    synthesizeSpeech: "Synteza mowy · TTS",
    generateImage: "Generowanie obrazów · Image",
  } satisfies Record<OnlineCapability, string>,
  addModel: {
    title: "Dodaj model",
    model: "Identyfikator modelu",
    taken: "Dostawca już ma ten ID modelu.",
    note: "Zastosowanie określa listę modelu i to, czy test wysyła tekst, czy otrzymuje obraz. Przetestuj po dodaniu.",
    added: (id: string) => `Dodano: ${id}`,
    failed: (message: string) => `Nie udało się dodać modelu: ${message}`,
  },
  probe: {
    title: { synthesizeSpeech: "Test syntezy mowy", generateImage: "Testuj generowanie obrazów", generateText: "Testowe generowanie tekstu" } as Partial<Record<OnlineCapability, string>>,
    chip: { transcribe: "ASR", synthesizeSpeech: "TTS", generateImage: "Obraz", generateText: "LLM" } satisfies Record<OnlineCapability, string>,
    sample: { synthesizeSpeech: "Tekst testowy · chiński uproszczony", generateImage: "Prompt testowy · jeden obraz · rozmiar domyślny", generateText: "Podpowiedź testowa" } as Partial<
      Record<OnlineCapability, string>
    >,
    voice: (voice: string) => `Głos · ${voice}`,
    voiceField: "ID głosu",
    voiceDesc: "Model nie ma gotowych głosów; test wymaga ID głosu rozpoznawanego przez dostawcę.",
    note: {
      synthesizeSpeech: "Wysyła ten tekst do wybranego modelu syntezy i sprawdza, czy wraca audio.",
      generateImage: "Wysyła ten prompt do wybranego modelu obrazów i sprawdza, czy wraca obraz.",
      generateText: "Wysyła powyższy prompt do wybranego modelu i sprawdza, czy wraca tekst.",
    } as Partial<Record<OnlineCapability, string>>,
    cost: "Dostawca może naliczać opłaty. Zamknięcie okna nie wycofuje wysłanego żądania; test jest też w zadaniach w tle.",
    ready: "Gotowe do uruchomienia",
    running: { synthesizeSpeech: "Wysyłanie tekstu i oczekiwanie na dźwięk…", generateImage: "Wysyłanie promptu i oczekiwanie na obraz…", generateText: "Oczekiwanie na odpowiedź modelu…" } as Partial<
      Record<OnlineCapability, string>
    >,
    done: (seconds: number | null) => (seconds !== null ? `Test zaliczony · ${seconds}s` : "Test zaliczony"),
    failed: "Test nie powiódł się",
    result: "Wynik testu",
    resultNote: "Wynik jest tylko tutaj i nie trafia do wideo.",

    textResultNote: "Odpowiedź nie trafia do wideo; jak inny wygenerowany tekst, zostaje zapisana jako dokument w Space.",
    start: "Rozpocznij test",
    retry: "Przetestuj ponownie",
    testing: "Testowanie…",
    close: "Zamknij",
    openFailed: (message: string) => `Nie udało się otworzyć wyniku: ${message}`,
    asrUnsupported: "Rozpoznawania mowy nie można jeszcze testować osobno",
  },
  voices: {
    title: "Moje głosy",
    lede: "Zapisz nagranie wzorcowe jako głos i wybieraj go po nazwie przy mowie lub tłumaczonym lektorze; nagranie zostaje na tym komputerze. Dla silnika chmurowego (ElevenLabs) najpierw prześlij je tutaj, aby utworzyć klon. Możesz go usunąć w dowolnej chwili.",
    emptyTitle: "Brak głosów",
    emptyBody: "Wybierz nagranie wzorcowe 5–12 sekund lub zaimportuj wyeksportowany pakiet głosów. Po zapisaniu można go wybierać wszędzie.",
  },
  quoted: (text: string) => `„${text}”`,
};
