import type { OnlineCapability } from '@baocut/protocol';
import type { RefreshKind } from '../../model/models-cloud.ts';
import type { ModelsMessages } from './models-copy.ts';

export const zhHant: ModelsMessages = {
  page: {
    title: '模型',
    nav: '模型導覽',
    navSection: '能力',
    categories: '模型類別',
    tabs: (label: string) => `${label}模型管理`,
    offline: '連上 Runtime 後就會顯示模型。',
    loading: '正在載入模型…',
    goAgent: '前往「設定 › Agent」',
  },
  local: {
    defaultLabel: '預設模型',
    defaultDesc: '建立新影片時會預先選取它，命令列轉錄也會使用它。',
    separateDefaultDesc: '未指定模型時，翻譯配音會用它分離背景音，命令列配音也會使用它。',
    auto: '自動',
    autoUses: (id: string) => `自動目前使用 ${id}。`,
    otherDefault: (name: string) => `目前的預設是 ${name}（在雲端模型中設定）；在這裡選擇本機模型會取代它。`,
    defaultSet: '已設為預設',
    defaultFailed: (message: string) => `無法設定預設：${message}`,
    installed: '已安裝',
    available: '可下載',
    emptyInstalled: '還沒有安裝任何模型。',
    emptyAvailable: '這個類別的模型都已安裝。',
    remove: '刪除',
    reenable: '重新啟用',
    reenabled: (id: string) => `已重新啟用 ${id}`,
    reenableFailed: (message: string) => `無法重新啟用：${message}`,
    emptyTitle: (label: string) => `還沒有${label}的本機模型`,
    emptyBody: '這台電腦的模型資料夾目前只存放語音辨識、語音合成、影像生成與音源分離的模型套件。這個類別還不支援本機模型。',
  },
  imageLocal: {
    defaultDesc: '建立新的影像任務時會預先選取它。沒有預設時每次都要選擇模型；手動選擇一律優先。',
    cloudDefault: (name: string) => `預設是雲端模型（${name}），請在「設定 › 雲端模型」中變更。選擇本機模型就會改用它。`,
    noInstalled: '還沒有安裝影像生成模型。請先從下方下載一個。',
    licenseUse: '用它生成的圖片只能用於非商業內容；打算商用的影片，請改用其他影像模型。',
    tryButton: '試畫',
    tryTitle: (name: string) => `試畫 ${name}`,
    tryPromptTitle: '測試提示詞 · 一張 512 × 512',
    tryPromptLabel: '測試提示詞',
    tryPlaceholder: '描述想要的畫面',
    tryChars: (n: number, max: number) => `${n} / ${max} 字`,
    trySample: '換一個範例',
    tryFacts: (steps: number) => `1:1 · 512 × 512 · ${steps} 步 · 1 張 · 離線 · 使用這台電腦的重活槽`,
    tryNote:
      '在這台電腦上畫一張小圖看看效果，不會連上網路。它會佔用重活槽，其他本機模型任務要等它完成。關閉對話框不會停止它；這次執行也會列在背景任務中。',
    tryReady: '準備開始',
    tryRunning: (steps: number) => `正在繪製 512² · ${steps} 步…`,
    tryDone: (seconds: number | null) => (seconds !== null ? `完成 · ${seconds} 秒` : '完成'),
    tryFailed: '無法畫出圖片',
    tryResult: '測試結果',
    tryImageAlt: '測試生成的圖片',
    tryOpenFailed: (message: string) => `無法開啟結果圖片：${message}`,
    tryWhere: '和其他生成的圖片一樣，結果會列在「工具 › 生成圖片」中，不會加入影片',
    tryDownload: '下載圖片',
    tryCopy: '複製提示詞',
    tryClose: '關閉',
    tryStopWaiting: '停止等待',
    tryStart: '開始生成',
    tryAgain: '再生成一張',
    tryBusy: '生成中…',
    tryFileName: (id: string) => `圖片-試畫-${id}`,
  },
  cloud: {
    heading: {
      transcribe: '把語音變成逐字稿',
      synthesizeSpeech: '把文字唸出來',
      generateImage: '把描述變成圖片',
      generateText: '翻譯字幕與生成文字',
    } satisfies Record<OnlineCapability, string>,
    lede: {
      transcribe: '接收音訊並傳回辨識出的文字。語音辨識只有一個預設模型，與本機模型頁共用。',
      synthesizeSpeech: '接收文字並傳回語音。生成語音與配音時可以使用；需連上網路並計費，通常按字元計費。',
      generateImage:
        '接收提示詞並傳回圖片。生成圖片時可以使用；需連上網路並按張計費。Codex CLI 也能繪圖：不需要金鑰，使用你的 Codex 訂閱。它的開關在下方供應商清單的第一張卡片上。',
      generateText: '接收文字指令並傳回生成的文字。用於字幕翻譯、翻譯配音與「工具 › 文字生成」；需連上網路並依 token 計費。',
    } satisfies Record<OnlineCapability, string>,
    defaultLabel: {
      transcribe: '預設雲端語音模型',
      synthesizeSpeech: '預設雲端語音合成模型',
      generateImage: '預設雲端影像模型',
      generateText: '預設文字模型',
    } satisfies Record<OnlineCapability, string>,
    defaultDesc: {
      transcribe:
        '轉錄沒有指定模型時使用。語音辨識只有一個預設：在這裡選擇雲端模型會取代本機頁的選擇；「使用本機模型」會清除雲端預設，回到本機的自動選擇。',
      synthesizeSpeech: '生成語音或配音沒有指定模型時使用。「每次選擇」表示沒有預設：沒有指定模型的請求會被拒絕，使用時再挑選。',
      generateImage:
        '生成圖片、bcut image 或 Agent 沒有指定模型時使用。不會自動替你選 Codex；若要預設使用它，請在這裡選擇。「每次選擇」表示沒有預設，生成時再挑選。',
      generateText:
        '字幕翻譯、翻譯配音或文字生成沒有指定模型時使用。「每次選擇」表示沒有預設：Runtime 不會替你挑選，沒有指定模型的請求會被拒絕，使用時再挑選。',
    } satisfies Record<OnlineCapability, string>,
    localDefaultDesc: '在本機模型頁設定 · 選擇「每次選擇」即可清除預設',
    none: {
      transcribe: '使用本機模型',
      synthesizeSpeech: '每次選擇',
      generateImage: '每次選擇',
      generateText: '每次選擇',
    } satisfies Record<OnlineCapability, string>,
    noneDesc: {
      transcribe: '回到本機模型頁的自動選擇',
      synthesizeSpeech: '生成語音或配音時再挑選',
      generateImage: '生成圖片時再挑選',
      generateText: '使用時再挑選（Runtime 不會替你挑選）',
    } satisfies Record<OnlineCapability, string>,
    codexItem: 'Codex CLI · 圖片',
    codexItemDesc: '使用你的 Codex 訂閱 · 一次一張 · 慢 5–10 倍',
    unavailable: '無法使用',
    pickerEmpty: { image: '連接供應商或開啟 Codex 圖片後即可選擇', other: '連接供應商後即可選擇' },
    defaultSet: '已變更預設模型',
    defaultFailed: (message: string) => `無法變更預設模型：${message}`,
    providers: '供應商',
    providersDesc: '同一供應商的所有模型類型共用它的金鑰。測試結果只適用於受測的模型。',
    providersExtra: {
      transcribe: '',
      synthesizeSpeech: '語音合成通常按字元計費。',
      generateImage: '影像生成按張計費；生成的圖片適用各供應商的使用條款。',
      generateText: '文字生成依 token 計費。',
    } satisfies Record<OnlineCapability, string>,
    addCustom: '新增自訂供應商',
    connected: '已連接',
    manageKey: '管理金鑰',
    connect: '連接',
    addModel: '新增模型',
    defaultChip: '預設',
    expand: (name: string) => `顯示 ${name} 的模型`,
    collapse: (name: string) => `隱藏 ${name} 的模型`,
    probe: {
      transcribe: '測試語音',
      synthesizeSpeech: '測試合成',
      generateImage: '測試圖片',
      generateText: '測試生成',
    } satisfies Record<OnlineCapability, string>,
    probeUnsupported: '目前還無法單獨測試',
    headNoModels: (kind: string) => `還沒有${kind}模型 · 在下方新增，會使用這組金鑰`,
    headCustomOff: '未連接 · 自訂 · 連接後可在各用途下新增模型',
    headOff: (first: string, total: number) =>
      `未連接 · ${first}${total > 1 ? `等 ${total} 個模型` : ''} · 連接後即可測試並設為預設`,
    headCount: (total: number) => `${total} 個模型`,
    headDefault: (id: string) => ` · 預設：${id}`,
    refresh: { models: '重新整理模型', voices: '重新整理音色目錄' } satisfies Record<RefreshKind, string>,
    refreshNeedsKey: (label: string) => `${label}（請先連接金鑰）`,
    refreshing: { models: '正在重新整理模型…', voices: '正在重新整理音色目錄…' } satisfies Record<RefreshKind, string>,
    refreshFailedLine: { models: '無法重新整理模型', voices: '無法重新整理音色' } satisfies Record<RefreshKind, string>,
    builtinModels: '內建清單 · 重新整理後會顯示這組金鑰可用的模型',
    builtinVoices: (models: number, voices: number) =>
      `${models} 個模型 · ${voices} 個音色 · 內建目錄 · 重新整理後會顯示這組金鑰可用的音色`,
    freshModels: (models: number, ago: string) => `${models} 個模型 · ${ago}更新`,
    freshVoices: (models: number, voices: number, ago: string) => `${models} 個模型 · ${voices} 個音色 · ${ago}重新整理`,
    unusable: (n: number) => ` · ${n} 個無法用這組金鑰使用`,
    refreshFailed: (message: string) => `無法重新整理：${message}`,
    modelVoices: (n: number) => (n ? `${n} 個內建音色` : '沒有內建音色 · 測試時需要提供音色 ID'),
    modelSizes: (sizes: string[], max: number) => `${sizes.length ? sizes.join(' / ') : '尺寸由服務決定'} · 一次最多 ${max} 張`,
    customTag: '自訂',
    emptyProviders: '這個類別還沒有雲端供應商。你可以新增一個 OpenAI 相容的自訂服務。',
    noCloud: '這個類別沒有雲端模型。',
  },
  textParams: {
    effort: '推理強度',
    effortDesc: '只適用於支援推理的模型：模型沒有這個等級時會使用最接近的等級；無法調整的模型會忽略此設定。「自動」使用模型本身的預設。',
    effortCount: (tunable: number, total: number) => (total ? `已連接的 ${total} 個模型中有 ${tunable} 個可以調整。` : ''),
    concurrency: '並行請求數',
    concurrencyDesc: (min: number, max: number) =>
      `每家供應商同時傳送的文字請求上限（${min}–${max}），字幕翻譯與文字生成共用。遇到速率限制時請調低。`,
    saved: '已儲存',
    failed: (message: string) => `無法儲存：${message}`,
  },
  codexCard: {
    title: 'Codex CLI',
    on: '已開啟 · 使用你的 Codex 訂閱，不需要金鑰 · 一次一張 · 忽略尺寸 · 慢 5–10 倍',
    off: '已關閉 · 開啟後即可在生成圖片中選擇它，並在這裡設為預設模型',
    missing: '找不到 Codex · 用它繪圖前，請先安裝並登入 Codex CLI。',
    switchLabel: '用 Codex 繪圖',
    toggleFailed: (enabled: boolean, message: string) => `無法${enabled ? '開啟' : '關閉'} Codex 圖片：${message}`,
  },
  key: {
    title: (name: string) => `${name} · API 金鑰`,
    shared: (name: string, kinds: string) => `這組金鑰由 ${name} 的所有模型共用（${kinds}）；輸入一次，每個清單都能使用。`,
    sharedCustom: (name: string) =>
      `這組金鑰由 ${name} 的所有模型共用。語音辨識、文字、語音合成與影像模型都可以新增在它底下；金鑰只需輸入一次。`,
    field: 'API 金鑰',
    fieldCustom: '如果服務不需要金鑰，請留空。',
    endpoint: (url: string) => `Base URL · ${url}`,
    keep: '已經儲存過金鑰。留空即可保留原金鑰，只重新驗證。',
    verifyNote: '儲存前會向供應商傳送一個唯讀請求來驗證金鑰；驗證失敗就不會儲存。金鑰只儲存在這台電腦上，之後不會再顯示。',
    removeKey: '移除金鑰',
    removeProvider: '刪除供應商',
    cancel: '取消',
    save: '驗證並儲存',
    saved: (name: string) => `已連接 ${name}`,
    failed: (message: string) => message,
    removed: (name: string) => `已移除 ${name} 的金鑰`,
    providerRemoved: (name: string) => `已刪除 ${name}`,
    removeFailed: (message: string) => `無法移除：${message}`,
    confirmTitle: (name: string) => `要刪除「${name}」嗎？`,
    confirmBody: '它宣告的模型會和金鑰一起刪除。指向它的預設模型會保留，並顯示為無法使用。',
    confirm: '刪除',
  },
  custom: {
    title: '新增自訂供應商',
    name: '供應商名稱',
    url: 'Base URL',
    urlPlaceholder: 'https://api.example.com/v1',
    model: '第一個模型 ID',
    kind: '用途',
    voices: '音色 ID',
    voicesPlaceholder: '以逗號分隔（選填） · 例如 zh-female, zh-male',
    taken: (name: string) => `這個 URL 已經新增為「${name}」。在它底下新增模型，即可沿用同一組金鑰。`,
    takenAction: (name: string) => `新增到「${name}」`,
    note: {
      transcribe: '必須支援音訊轉錄（/v1/audio/transcriptions）；只支援聊天的端點無法辨識語音。',
      synthesizeSpeech: '必須支援 /v1/audio/speech；沒有填音色 ID 的話，使用時需要另外提供。',
      generateImage: '必須支援 /v1/images/generations；尺寸使用保守的預設值（1024 × 1024，一次一張）。',
      generateText: '必須支援 /v1/chat/completions；上下文與輸出長度使用保守的預設值（32K 與 4K token）。',
    } satisfies Record<OnlineCapability, string>,
    noteHead: 'OpenAI 相容的服務。',
    noteTail: '新增後請連接（輸入金鑰或留空）並測試模型。',
    add: '新增',
    added: (name: string) => `已新增 ${name} · 下一步請連接`,
    failed: (message: string) => `無法新增：${message}`,
  },
  kindLabel: {
    transcribe: '語音辨識 · ASR',
    generateText: '文字生成 · LLM',
    synthesizeSpeech: '語音合成 · TTS',
    generateImage: '影像生成 · Image',
  } satisfies Record<OnlineCapability, string>,
  addModel: {
    title: '新增模型',
    model: '模型 ID',
    taken: '這個供應商已經有這個模型 ID。',
    note: '用途決定模型會出現在哪個清單，以及測試時是傳送文字還是取回圖片。新增後請測試。',
    added: (id: string) => `已新增 ${id}`,
    failed: (message: string) => `無法新增模型：${message}`,
  },
  probe: {
    title: {
      synthesizeSpeech: '測試語音合成',
      generateImage: '測試影像生成',
      generateText: '測試文字生成',
    } as Partial<Record<OnlineCapability, string>>,
    chip: { transcribe: 'ASR', synthesizeSpeech: 'TTS', generateImage: 'Image', generateText: 'LLM' } satisfies Record<OnlineCapability, string>,
    sample: {
      synthesizeSpeech: '測試文字 · 簡體中文',
      generateImage: '測試提示詞 · 一張 · 預設尺寸',
      generateText: '測試提示詞',
    } as Partial<Record<OnlineCapability, string>>,
    voice: (voice: string) => `音色 · ${voice}`,
    voiceField: '音色 ID',
    voiceDesc: '這個模型沒有內建音色；測試需要一個供應商認得的音色 ID。',
    note: {
      synthesizeSpeech: '把這段文字傳送給所選模型合成，並檢查是否傳回音訊。',
      generateImage: '把這段提示詞傳送給所選模型繪製，並檢查是否傳回圖片。',
      generateText: '把上方的提示詞傳送給所選模型，並檢查是否傳回生成的文字。',
    } as Partial<Record<OnlineCapability, string>>,
    cost: '供應商可能會依用量計費。關閉對話框不會撤回已傳送的請求；這次測試也會出現在背景任務中。',
    ready: '準備開始',
    running: {
      synthesizeSpeech: '正在傳送文字並等候音訊…',
      generateImage: '正在傳送提示詞並等候圖片…',
      generateText: '正在等候模型回覆…',
    } as Partial<Record<OnlineCapability, string>>,
    done: (seconds: number | null) => (seconds !== null ? `測試通過 · ${seconds} 秒` : '測試通過'),
    failed: '測試失敗',
    result: '測試結果',
    resultNote: '結果只會顯示在這裡，不會加入影片。',
    textResultNote: '回覆不會加入影片；和其他生成的文字一樣，會儲存為 Space 中的一份文件。',
    start: '開始測試',
    retry: '再測試一次',
    testing: '測試中…',
    close: '關閉',
    openFailed: (message: string) => `無法開啟結果：${message}`,
    asrUnsupported: '語音辨識目前還無法單獨測試',
  },
  voices: {
    title: '我的音色',
    lede: '把一段參考錄音儲存為音色，之後生成語音或翻譯配音時就能依名稱選用；參考錄音會留在這台電腦上。若要讓雲端引擎（ElevenLabs）用這個音色說話，請先在這裡上傳參考錄音以建立克隆。你隨時都可以刪除它。',
    emptyTitle: '還沒有音色',
    emptyBody: '選擇一段 5–12 秒的參考錄音，或匯入別人匯出的音色套件。儲存後，在任何地方都能選用。',
  },
  quoted: (text: string) => `「${text}」`,
};
