import type { TtsLocalMessages } from './tts-local-copy.ts';

export const ru: TtsLocalMessages = {
  ttsLocal: {

    unset: "Не задано",
    defaultDesc: "Предвыбрана для новых задач синтеза. Без значения по умолчанию модель выбирается каждый раз; ручной выбор всегда приоритетен.",
    cloudDefault: (name: string) => `По умолчанию облачная модель (${name}); измените в Настройки › Облачные модели. Выбор локальной переключает на неё.`,
    noInstalled: "Модели синтеза речи ещё не установлены. Сначала скачайте ниже.",

    audition: "Предварительный просмотр",
    hideAudition: "Скрыть предпросмотр",
    engine: "Движок",
    license: "Лицензия",
    components: "Компоненты",

    licenseTitle: "Лицензия",
    licenseUse: "Созданная речь только для некоммерческого содержимого; для коммерческих видео выберите другую речевую модель.",
    licenseConfirm: (size: string) => `Понятно, скачать ${size}`,

    voice: "Голос",
    tone: "Тон",
    say: "Что сказать",
    lines: "Фразы",
    more: "Другие голоса",
    cloneNew: "Клонировать новый голос…",
    writeOwn: "Написать свой",
    ownPlaceholder: "Введите предложение для прослушивания",
    ownLabel: "Текст предпросмотра",
    describeLabel: "Описание голоса",
    describePlaceholder: "например, глубокий неторопливый голос пожилого мужчины",
    builtinRef: (label: string, seconds: number | null) => `Эталонная запись · ${label}${seconds !== null ? ` · ${seconds}с` : ""} · расшифровка добавляется автоматически`,
    describedBuiltin: (label: string) => `Голос по описанию · использует описание из «${label}»`,
    describePreset: (text: string) => `Описание: ${text}`,
    myVoice: (name: string) => `Мои голоса · ${name} · клон по эталонной записи и расшифровке`,
    presetOnly: (models: string | null) => models
        ? `У модели только встроенные говорящие · попробуйте «Мои голоса» с моделью клонирования: ${models} (предпросмотр в строке каждого)`
        : "У модели только встроенные говорящие · для «Мои голоса» сначала скачайте модель клонирования",
    nameList: (names: readonly string[]) => names.join(", "),
    cloneHint: "Укажите 5–15 секунд чистой речи: один человек, без фоновой музыки. Подходят WAV, MP3, M4A, FLAC и видеофайл.",
    yourFile: (name: string) => `Ваша запись · ${name}`,
    sampleFile: (label: string) => `Образец записи · ${label} · поставляется с BaoCut, не нужно искать файл`,
    pickFile: "Выбрать запись…",
    changeFile: "Выберите другой…",
    useSample: "Использовать образец записи",
    crossLang: "Работает между языками: китайская запись может читать на английском.",
    noPicker: "В браузере нельзя выбрать файлы компьютера. Для разовой записи выберите в настольном приложении; либо используйте образец или сначала сохраните в «Мои голоса».",
    pickTitle: "Выбрать эталонную запись",
    pickButton: "Выбрать",
    pickFilter: "Аудио или видео",
    transcriptLabel: "Расшифровка записи (по желанию)",
    transcriptHint: "Текст записи повышает сходство голоса",
    fileChip: (name: string, sample: boolean) => (sample ? `Образец · ${name}` : name),
    generate: "Сгенерировать предпросмотр",
    again: "Сгенерировать снова",
    cancel: "Отмена",
    busy: (phase: string) => `Синтез · ${phase}`,
    stalePrefix: "Предыдущий · ",
    stale: "Клип создан с предыдущим выбором. После смены голоса или текста нажмите «Сгенерировать предпросмотр» для нового.",
    download: "Скачать",
    resultLabel: "Результат предпросмотра",
    credit: (credit: string) => `Запись встроенного голоса: ${credit}`,
    loadingAudio: "Загрузка аудио…",
    audioFailed: (message: string) => `Не удалось загрузить аудио: ${message}`,
    downloadFailed: (message: string) => `Не удалось скачать: ${message}`,
    fileName: (name: string) => `${name.replace(/[^\w.-]+/g, "-")}-preview.wav`,

    handoffFrom: (name: string) => `Из предпросмотра «${name}» · запишите или возьмите из видео; после сохранения вернётесь`,
    handoffSaved: (name: string) => `Сохранено · вернитесь к предпросмотру «${name}», этот голос будет выбран`,
    handoffBack: "Вернуться и использовать",
    handoffCancel: "Нет, вернуться",
    auditionClone: "Предпросмотр клона",
    auditionCloneLabel: (name: string) => `Предпросмотр клона · ${name}`,
    noCloneModel: "Локальная модель клонирования ещё не установлена. Сначала скачайте на странице локальных моделей (IndexTTS2, Qwen3-TTS Base, GPT-SoVITS…).",
    goLocal: "Перейти к локальным моделям",
  },
};
