import type { TtsLocalMessages } from './tts-local-copy.ts';

export const tr: TtsLocalMessages = {
ttsLocal: {
  // 默认模型（语音合成没有出厂默认，菜单里没有「自动选择」）
  unset: 'Ayarlı değil', defaultDesc: 'Yeni sentez görevlerinde önceden seçilir. Varsayılan yoksa her seferinde model seçersiniz; elle seçim önceliklidir.', cloudDefault: (name) => `Varsayılan bulut modeli (${name}); Ayarlar › Bulut modelleri kısmında değiştirin. Yerel model seçmek ona geçer.`, noInstalled: 'Henüz konuşma sentezi modeli yüklü değil. Önce aşağıdan indirin.',
  // 行
  audition: 'Önizleme', hideAudition: 'Önizlemeyi gizle', engine: 'Motor', license: 'Lisans', components: 'Bileşenler',
  // 下载前的许可确认（设计稿 withModelLicense）
  licenseTitle: 'Lisans', licenseUse: 'Üretilen konuşma yalnızca ticari olmayan içerikte kullanılabilir; ticari videolar için başka konuşma modeli seçin.', licenseConfirm: (size) => `Anladım, ${size} indir`,
  // 试听面板
  voice: 'Ses', tone: 'Ton', say: 'Söylenecek metin', lines: 'Satırlar', more: 'Diğer sesler', cloneNew: 'Yeni ses klonla…', writeOwn: 'Kendim yazayım', ownPlaceholder: 'Dinlemek için cümle yazın', ownLabel: 'Önizleme metni', describeLabel: 'Ses tarifi', describePlaceholder: 'örneğin kalın, yavaş konuşan yaşlı erkek sesi', builtinRef: (label, seconds) => `Referans kayıt · ${label}${seconds !== null ? ` · ${seconds} sn` : ''} · dökümü otomatik eklenir`, describedBuiltin: (label) => `Tariften ses · “${label}” ile gelen tarifi kullanır`, describePreset: (text) => `Tarif: ${text}`, myVoice: (name) => `Seslerim · ${name} · referans kayıt ve dökümünden klonlandı`, presetOnly: (models) => models ? `Bu modelde yalnızca yerleşik konuşmacılar var · klonlayabilen modelde “Seslerim” deneyin: ${models} (her modelin satırındaki önizleme)` : 'Bu modelde yalnızca yerleşik konuşmacılar var · “Seslerim” denemek için önce klonlayabilen model indirin', nameList: (names) => names.join(', '), cloneHint: '5–15 saniye temiz konuşma verin: tek kişi, arka plan müziği yok. WAV, MP3, M4A, FLAC veya video dosyası kullanılabilir.', yourFile: (name) => `Kaydınız · ${name}`, sampleFile: (label) => `Örnek kayıt · ${label} · BaoCut ile gelir, dosya bulmak gerekmez`, pickFile: 'Kayıt seç…', changeFile: 'Başkasını seç…', useSample: 'Örnek kaydı kullan', crossLang: 'Diller arasında da çalışır: Çince kayıt İngilizce okuyabilir.', noPicker: 'Tarayıcı bu bilgisayarda dosya seçemez. Kaydı tek sefer kullanmak için masaüstü uygulamasında seçin; veya örnek kaydı kullanın ya da önce “Seslerim” içine kaydedin.', pickTitle: 'Referans kayıt seç', pickButton: 'Seç', pickFilter: 'Ses veya video', transcriptLabel: 'Kayıt dökümü (isteğe bağlı)', transcriptHint: 'Kayıtta söylenenleri yazmak daha yakın ses verir', fileChip: (name, sample) => sample ? `Örnek · ${name}` : name, generate: 'Önizleme oluştur', again: 'Yeniden oluştur', cancel: 'İptal', busy: (phase) => `Sentezleniyor · ${phase}`, stalePrefix: 'Önceki · ', stale: 'Bu klip önceki seçimlerinizle yapıldı. Ses veya metni değiştirince yenisini duymak için “Önizleme oluştur” tıklayın.', download: 'İndir', resultLabel: 'Önizleme sonucu', credit: (credit) => `Yerleşik ses kaydı: ${credit}`, loadingAudio: 'Ses yükleniyor…', audioFailed: (message) => `Ses yüklenemedi: ${message}`, downloadFailed: (message) => `İndirilemedi: ${message}`, fileName: (name) => `${name.replace(/[^\w.-]+/g, '-')}-onizleme.wav`,
  // 「我的声音」那一侧：`name` 是发起克隆的那只本地模型的名字
  handoffFrom: (name) => `“${name}” önizlemesinden · kayıt yapın veya videodan alın; kaydedince geri dönersiniz`, handoffSaved: (name) => `Kaydedildi · “${name}” önizlemesine dönün, bu ses seçilmiş olacak`, handoffBack: 'Dön ve kullan', handoffCancel: 'İstemiyorum, geri dön', auditionClone: 'Klonu dinle', auditionCloneLabel: (name) => `Klonu dinle · ${name}`, noCloneModel: 'Henüz klonlayabilen yerel model yüklü değil. Önce yerel modeller sayfasında indirin (IndexTTS2, Qwen3-TTS Base, GPT-SoVITS…).', goLocal: 'Yerel modellere git' },
};
