import type { VoicesMessages } from './voices-copy.ts';

export const it: VoicesMessages = {
  myVoices: {
    offline: 'Le voci compaiono quando il Runtime è connesso.', add: 'Aggiungi voce', fromFile: 'Nuova da file audio…', fromFileHint: 'WAV, MP3 o FLAC, fino a 20 MB; ideale una frase completa di 5–12 secondi', importPackage: 'Importa pacchetto voce…', importHint: 'Un .bcvoice esportato da qualcuno', record: 'Registra con il microfono',
    recordWhy: 'La registrazione nell’app non è ancora disponibile: prima di inviarla al Runtime deve essere salvata come file, e quel passaggio non è ancora implementato. Registra prima con un’altra app (WAV, MP3 o FLAC), poi usa «Nuova da file audio…».', recordWhyNoPicker: 'La registrazione nell’app non è ancora disponibile: prima di inviarla al Runtime deve essere salvata come file, e quel passaggio non è ancora implementato. Registra prima con un’altra app (WAV, MP3 o FLAC), poi usa «Nuova da file audio…». Per importare un pacchetto voce, questa finestra non può aprire il selettore di file del sistema; usa l’app desktop.', noPicker: 'Questa finestra non può aprire il selettore di file del sistema; usa l’app desktop.', pickAudioTitle: 'Scegli una registrazione di riferimento', pickAudioFilter: 'Audio (WAV, MP3, FLAC)', pickPackageTitle: 'Scegli un pacchetto voce', pickPackageFilter: 'Pacchetto voce', pickButton: 'Scegli', notAudio: 'Le registrazioni di riferimento devono essere file WAV, MP3 o FLAC.',
    imported: (name: string) => `«${name}» importata · disponibile per generare voce e doppiaggi`, importFailed: (text: string) => `Impossibile importare: ${text}`, foot: 'Una voce = una registrazione di riferimento + ciò che dice + una dichiarazione di consenso. La registrazione rimane su questo computer; un pacchetto voce esportato (name.bcvoice) include la registrazione e può essere inviato ad altri per l’importazione, ma i cloni non lo accompagnano. Le voci senza dichiarazione sulla loro appartenenza al parlante non vengono mai caricate su terze parti.',
    play: (name: string) => `Anteprima di ${name}`, stop: (name: string) => `Interrompi anteprima di ${name}`, playFailed: (text: string) => `Impossibile riprodurre l’anteprima: ${text}`, more: (name: string) => `Altro · ${name}`, edit: 'Modifica…', cloneTo: (label: string) => `Carica su ${label} per clonare…`, recloneTo: (label: string) => `Carica di nuovo su ${label}…`, recloneHint: 'La registrazione di riferimento è cambiata, quindi il vecchio clone non è aggiornato', removeClone: (label: string) => `Elimina clone da ${label}…`, export: 'Esporta pacchetto voce…', remove: 'Elimina…', cloning: (label: string) => `Caricamento su ${label} per clonare…`, cloneFailed: (label: string, text: string) => `L’ultima clonazione su ${label} non è riuscita: ${text}`, loadingMeta: 'Caricamento in corso…',
    createTitle: 'Nuova voce', editTitle: (name: string) => `Modifica «${name}»`, referenceFile: (file: string) => `Registrazione di riferimento: ${file}`, name: 'Nome', language: 'Lingua', languageHint: 'La lingua parlata nella registrazione di riferimento', transcript: 'Trascrizione', transcriptHint: 'Ciò che viene detto nella registrazione. Alcuni motori ne hanno bisogno per clonare; lascia vuoto se non sei sicuro.', consentHint: 'Puoi salvare senza selezionare questa opzione, ma la voce non verrà caricata su terze parti per la clonazione.', save: 'Salva come voce', saveEdit: 'Salva', cancel: 'Annulla', loading: 'Caricamento della voce…', loadFailed: (text: string) => `Impossibile caricare questa voce: ${text}`, saved: (name: string) => `«${name}» salvata · disponibile per generare voce e doppiaggi`, updated: (name: string) => `«${name}» salvata`, unchanged: 'Nessuna modifica',
    uploadTitle: (label: string) => `Caricare su ${label}?`, upload: 'Carica', cloneStarted: (label: string) => `Caricamento su ${label} · avanzamento in «Attività in background»`, cloneRejected: (text: string) => `Impossibile avviare la clonazione: ${text}`, removeCloneTitle: (label: string) => `Eliminare il clone da ${label}?`, removeCloneBody: (label: string) => `A ${label} verrà chiesto di eliminare questa voce clonata. Per usare di nuovo la voce su ${label}, dovrai caricarla nuovamente.`, removeCloneConfirm: 'Elimina clone', cloneRemoved: (label: string) => `Clone eliminato da ${label}`, cloneGoneRemote: (label: string) => `${label} non ha più questo clone; anche il registro su questo computer è stato cancellato`, cloneRemoveFailed: (text: string) => `Impossibile eliminare il clone: ${text}`,
    exportTitle: 'Esporta pacchetto voce', exportButton: 'Esporta', exported: (path: string) => `Esportato in ${path}`, exportFailed: (text: string) => `Impossibile esportare: ${text}`, exportExists: 'BaoCut non sovrascrive file esistenti. Scegli un altro nome o posizione ed esporta di nuovo.', exportFailedExists: (text: string) => `Impossibile esportare: ${text}. BaoCut non sovrascrive file esistenti. Scegli un altro nome o posizione ed esporta di nuovo.`,
    deleteTitle: (name: string) => `Eliminare «${name}»?`, deleteConfirm: 'Elimina', deleted: (name: string) => `«${name}» eliminata`, deleteFailed: (text: string) => `Impossibile eliminare: ${text}`, localOnlyTitle: (label: string) => `Il clone su ${label} non è stato eliminato`, localOnlyBody: (label: string, text: string) => `${text}

La voce è ancora qui. Puoi riprovare più tardi o eliminare solo il registro e la voce su questo computer. Il clone nel tuo account ${label} rimarrà e dovrai eliminarlo direttamente su ${label}.`, localOnlyConfirm: 'Elimina solo su questo computer', later: 'Riprova più tardi',
  },
};
