import type { VoicesMessages } from './voices-copy.ts';

export const zhHant: VoicesMessages = {
  myVoices: {
    offline: '連上 Runtime 後就會顯示音色。',
    add: '新增音色',
    fromFile: '從音訊檔新增…',
    fromFileHint: 'WAV、MP3 或 FLAC，最大 20 MB；5–12 秒的一個完整句子效果最好',
    importPackage: '匯入音色套件…',
    importHint: '別人匯出的 .bcvoice',
    record: '用麥克風錄音',
    recordWhy:
      '目前還無法在應用程式中錄音：錄音必須先儲存成檔案才能交給 Runtime，而這一步還沒有完成。請先用其他應用程式錄好（WAV、MP3 或 FLAC），再使用「從音訊檔新增」。',
    recordWhyNoPicker:
      '目前還無法在應用程式中錄音：錄音必須先儲存成檔案才能交給 Runtime，而這一步還沒有完成。請先用其他應用程式錄好（WAV、MP3 或 FLAC），再使用「從音訊檔新增」。匯入音色套件：這個視窗無法開啟系統的檔案對話框，請使用桌面版。',
    noPicker: '這個視窗無法開啟系統的檔案對話框，請使用桌面版。',
    pickAudioTitle: '選擇參考錄音',
    pickAudioFilter: '音訊（WAV、MP3、FLAC）',
    pickPackageTitle: '選擇音色套件',
    pickPackageFilter: '音色套件',
    pickButton: '選擇',
    notAudio: '參考錄音必須是 WAV、MP3 或 FLAC 檔案。',
    imported: (name: string) => `已匯入「${name}」 · 生成語音與配音時都能選用`,
    importFailed: (text: string) => `無法匯入：${text}`,
    foot:
      '音色 = 一段參考錄音 + 錄音中說的話 + 同意聲明。參考錄音會留在這台電腦上；匯出的音色套件（名稱.bcvoice）包含錄音，可以傳給別人匯入，但克隆不會一起帶走。' +
      '沒有聲明是否為說話者本人聲音的音色，絕不會上傳給任何第三方。',
    // 一行
    play: (name: string) => `試聽 ${name}`,
    stop: (name: string) => `停止試聽 ${name}`,
    playFailed: (text: string) => `無法試聽：${text}`,
    more: (name: string) => `更多 · ${name}`,
    edit: '編輯…',
    cloneTo: (label: string) => `上傳到 ${label} 以克隆…`,
    recloneTo: (label: string) => `重新上傳到 ${label}…`,
    recloneHint: '參考錄音已變更，舊的克隆已過期',
    removeClone: (label: string) => `從 ${label} 刪除克隆…`,
    export: '匯出音色套件…',
    remove: '刪除…',
    cloning: (label: string) => `正在上傳到 ${label} 以克隆…`,
    cloneFailed: (label: string, text: string) => `上次在 ${label} 上的克隆沒有成功：${text}`,
    loadingMeta: '正在載入…',
    // 新建与编辑
    createTitle: '新增音色',
    editTitle: (name: string) => `編輯「${name}」`,
    referenceFile: (file: string) => `參考錄音：${file}`,
    name: '名稱',
    language: '語言',
    languageHint: '參考錄音中所說的語言',
    transcript: '逐字稿',
    transcriptHint: '參考錄音中說的話。有些引擎克隆時需要它；如果不確定，可以留空。',
    consentHint: '不勾選也可以儲存，但這個音色不會上傳給任何第三方進行克隆。',
    save: '儲存為音色',
    saveEdit: '儲存',
    cancel: '取消',
    loading: '正在載入音色…',
    loadFailed: (text: string) => `無法載入這個音色：${text}`,
    saved: (name: string) => `已儲存「${name}」 · 生成語音與配音時都能選用`,
    updated: (name: string) => `已儲存「${name}」`,
    unchanged: '沒有變更',
    // 克隆
    uploadTitle: (label: string) => `要上傳到 ${label} 嗎？`,
    upload: '上傳',
    cloneStarted: (label: string) => `正在上傳到 ${label} · 進度在背景任務中`,
    cloneRejected: (text: string) => `無法開始克隆：${text}`,
    removeCloneTitle: (label: string) => `要從 ${label} 刪除克隆嗎？`,
    removeCloneBody: (label: string) => `會要求 ${label} 刪除這個克隆的音色。之後若要在 ${label} 上使用這個音色，需要重新上傳。`,
    removeCloneConfirm: '刪除克隆',
    cloneRemoved: (label: string) => `已從 ${label} 刪除克隆`,
    cloneGoneRemote: (label: string) => `${label} 上已經沒有這個克隆；這台電腦上的記錄也一併清除了`,
    cloneRemoveFailed: (text: string) => `無法刪除克隆：${text}`,
    // 导出
    exportTitle: '匯出音色套件',
    exportButton: '匯出',
    exported: (path: string) => `已匯出到 ${path}`,
    exportFailed: (text: string) => `無法匯出：${text}`,
    exportExists: 'BaoCut 不會覆寫現有的檔案。請選擇其他名稱或位置，再匯出一次。',
    exportFailedExists: (text: string) => `無法匯出：${text}。BaoCut 不會覆寫現有的檔案。請選擇其他名稱或位置，再匯出一次。`,
    // 删除
    deleteTitle: (name: string) => `要刪除「${name}」嗎？`,
    deleteConfirm: '刪除',
    deleted: (name: string) => `已刪除「${name}」`,
    deleteFailed: (text: string) => `無法刪除：${text}`,
    localOnlyTitle: (label: string) => `${label} 上的克隆沒有刪除`,
    localOnlyBody: (label: string, text: string) =>
      `${text}\n\n音色仍然保留。你可以稍後再試，或只刪除這台電腦上的記錄與音色。這樣一來，你在 ${label} 帳號中的克隆仍會保留，需要自行到 ${label} 刪除。`,
    localOnlyConfirm: '只從這台電腦刪除',
    later: '稍後再試',
  },
};
