import type { VoicesMessages } from './voices-copy.ts';

export const vi: VoicesMessages = {
myVoices: { offline: 'Giọng hiện sau khi Runtime kết nối.', add: 'Thêm giọng', fromFile: 'Mới từ tệp âm thanh…', fromFileHint: 'WAV, MP3 hoặc FLAC, tối đa 20 MB; câu đầy đủ 5–12 giây phù hợp nhất', importPackage: 'Nhập gói giọng…', importHint: 'Tệp .bcvoice người khác xuất', record: 'Ghi bằng micro', recordWhy: 'Chưa ghi trong ứng dụng được: cần lưu ghi âm thành tệp trước khi gửi Runtime, bước đó chưa có. Ghi bằng ứng dụng khác (WAV, MP3 hoặc FLAC) rồi dùng “Mới từ tệp âm thanh…”.', recordWhyNoPicker: 'Chưa ghi trong ứng dụng được: cần lưu ghi âm thành tệp trước khi gửi Runtime, bước đó chưa có. Ghi bằng ứng dụng khác (WAV, MP3 hoặc FLAC) rồi dùng “Mới từ tệp âm thanh…”. Nhập gói giọng: cửa sổ này không mở được hộp thoại tệp hệ thống; dùng ứng dụng máy tính.', noPicker: 'Cửa sổ này không mở được hộp thoại tệp hệ thống; dùng ứng dụng máy tính.', pickAudioTitle: 'Chọn bản ghi tham chiếu', pickAudioFilter: 'Âm thanh (WAV, MP3, FLAC)', pickPackageTitle: 'Chọn gói giọng', pickPackageFilter: 'Gói giọng', pickButton: 'Chọn', notAudio: 'Ghi âm tham chiếu phải là WAV, MP3 hoặc FLAC.', imported: (name) => `Đã nhập “${name}” · dùng được khi tạo giọng nói và lồng tiếng`, importFailed: (text) => `Không nhập được: ${text}`, foot: 'Giọng = ghi âm tham chiếu + nội dung nói + tuyên bố cho phép. Ghi âm giữ trên máy tính này; gói xuất (name.bcvoice) có ghi âm, có thể gửi người khác nhập nhưng bản nhân không đi cùng. Giọng chưa tuyên bố có phải của người nói không sẽ không tải lên bên thứ ba.',
  // 一行
  play: (name) => `Nghe thử ${name}`, stop: (name) => `Dừng nghe thử ${name}`, playFailed: (text) => `Không nghe thử được: ${text}`, more: (name) => `Thêm · ${name}`, edit: 'Chỉnh sửa…', cloneTo: (label) => `Tải lên ${label} để nhân bản…`, recloneTo: (label) => `Tải lên ${label} lại…`, recloneHint: 'Ghi âm tham chiếu đổi nên bản nhân cũ lỗi thời', removeClone: (label) => `Xóa bản nhân từ ${label}…`, export: 'Xuất gói giọng…', remove: 'Xóa…', cloning: (label) => `Đang tải lên ${label} để nhân bản…`, cloneFailed: (label, text) => `Bản nhân cuối trên ${label} chưa thành công: ${text}`, loadingMeta: 'Đang tải…',
  // 新建与编辑
  createTitle: 'Giọng mới', editTitle: (name) => `Chỉnh sửa “${name}”`, referenceFile: (file) => `Bản ghi tham chiếu: ${file}`, name: 'Tên', language: 'Ngôn ngữ', languageHint: 'Ngôn ngữ trong ghi âm tham chiếu', transcript: 'Bản chép lời', transcriptHint: 'Nội dung ghi âm tham chiếu. Một số bộ máy cần để nhân bản; để trống nếu không chắc.', consentHint: 'Có thể lưu không chọn nhưng giọng không tải lên bên thứ ba để nhân bản.', save: 'Lưu thành giọng', saveEdit: 'Lưu', cancel: 'Hủy', loading: 'Đang tải giọng…', loadFailed: (text) => `Không tải được giọng này: ${text}`, saved: (name) => `Đã lưu “${name}” · dùng được khi tạo giọng nói và lồng tiếng`, updated: (name) => `Đã lưu “${name}”`, unchanged: 'Không thay đổi',
  // 克隆
  uploadTitle: (label) => `Tải lên ${label}?`, upload: 'Tải lên', cloneStarted: (label) => `Đang tải lên ${label} · tiến độ trong Tác vụ nền`, cloneRejected: (text) => `Không bắt đầu nhân bản được: ${text}`, removeCloneTitle: (label) => `Xóa bản nhân từ ${label}?`, removeCloneBody: (label) => `Sẽ yêu cầu ${label} xóa giọng nhân bản. Để dùng giọng trên ${label} sau đó cần tải lên lại.`, removeCloneConfirm: 'Xóa bản nhân', cloneRemoved: (label) => `Đã xóa bản nhân từ ${label}`, cloneGoneRemote: (label) => `${label} không còn bản nhân; cũng đã xóa bản ghi trên máy này`, cloneRemoveFailed: (text) => `Không xóa bản nhân được: ${text}`,
  // 导出
  exportTitle: 'Xuất gói giọng', exportButton: 'Xuất', exported: (path) => `Đã xuất đến ${path}`, exportFailed: (text) => `Không xuất được: ${text}`, exportExists: 'BaoCut không ghi đè tệp hiện có. Chọn tên hoặc vị trí khác rồi xuất lại.', exportFailedExists: (text) => `Không xuất được: ${text}. BaoCut không ghi đè tệp hiện có. Chọn tên hoặc vị trí khác rồi xuất lại.`,
  // 删除
  deleteTitle: (name) => `Xóa “${name}”?`, deleteConfirm: 'Xóa', deleted: (name) => `Đã xóa “${name}”`, deleteFailed: (text) => `Không xóa được: ${text}`, localOnlyTitle: (label) => `Bản nhân trên ${label} chưa xóa`, localOnlyBody: (label, text) => `${text}\n\nGiọng vẫn ở đây. Có thể thử lại sau hoặc chỉ xóa bản ghi và giọng trên máy tính này. Bản nhân trong tài khoản ${label} vẫn còn, bạn phải tự xóa trên ${label}.`, localOnlyConfirm: 'Chỉ xóa trên máy tính này', later: 'Thử lại sau' },
};
