import type { VoicesMessages } from './voices-copy.ts';

export const pl: VoicesMessages = {
  myVoices: {
    offline: "Głosy pojawią się po połączeniu Runtime.",
    add: "Dodaj głos",
    fromFile: "Nowy z pliku audio…",
    fromFileHint: "WAV, MP3 lub FLAC do 20 MB; najlepiej pełne zdanie 5–12 sekund",
    importPackage: "Importuj pakiet głosu…",
    importHint: "Wyeksportowany plik .bcvoice",
    record: "Nagraj mikrofonem",
    recordWhy: "Nagrywanie w aplikacji jeszcze niedostępne: przed Runtime nagranie trzeba zapisać jako plik, ten krok niezaimplementowany. Nagraj inną aplikacją (WAV, MP3 lub FLAC) i wybierz „Nowy z pliku audio…”.",
    recordWhyNoPicker:
      "Nagrywanie w aplikacji jeszcze niedostępne: przed Runtime nagranie trzeba zapisać jako plik, ten krok niezaimplementowany. Nagraj inną aplikacją (WAV, MP3 lub FLAC) i wybierz „Nowy z pliku audio…”. Dla importu pakietu: okno nie otwiera systemowego wyboru plików, użyj aplikacji komputerowej.",
    noPicker: "Okno nie otwiera systemowego wyboru plików; użyj aplikacji komputerowej.",
    pickAudioTitle: "Wybierz nagranie referencyjne",
    pickAudioFilter: "Audio (WAV, MP3, FLAC)",
    pickPackageTitle: "Wybierz pakiet głosu",
    pickPackageFilter: "Pakiet głosu",
    pickButton: "Wybierz",
    notAudio: "Nagrania referencyjne muszą być WAV, MP3 lub FLAC.",
    imported: (name: string) => `Zaimportowano „${name}” · dostępne przy generowaniu mowy i dubbingu`,
    importFailed: (text: string) => `Nie udało się zaimportować: ${text}`,
    foot:
      'A voice = a reference recording + what it says + a consent statement. The reference recording stays on this computer; an exported voice pack (name.bcvoice) includes the recording and can be sent to others to import, but clones don’t travel with it. ' +
      'Voices without a statement on whether they’re the speaker’s own are never uploaded to any third party.',

    play: (name: string) => `Odsłuchaj ${name}`,
    stop: (name: string) => `Zatrzymaj odsłuch ${name}`,
    playFailed: (text: string) => `Nie udało się odsłuchać: ${text}`,
    more: (name: string) => `Więcej · ${name}`,
    edit: "Edytuj…",
    cloneTo: (label: string) => `Prześlij do ${label} dla klonowania…`,
    recloneTo: (label: string) => `Prześlij do ${label} ponownie…`,
    recloneHint: "Nagranie referencyjne zmieniono, stary klon nieaktualny",
    removeClone: (label: string) => `Usuń klon u dostawcy ${label}…`,
    export: "Eksportuj pakiet głosu…",
    remove: "Usuń…",
    cloning: (label: string) => `Przesyłanie do ${label} dla klonowania…`,
    cloneFailed: (label: string, text: string) => `Ostatni klon u dostawcy ${label} nie powiódł się: ${text}`,
    loadingMeta: "Wczytywanie…",

    createTitle: "Nowy głos",
    editTitle: (name: string) => `Edytuj „${name}”`,
    referenceFile: (file: string) => `Nagranie referencyjne: ${file}`,
    name: "Nazwa",
    language: "Język",
    languageHint: "Język nagrania referencyjnego",
    transcript: "Transkrypcja",
    transcriptHint: "Tekst nagrania referencyjnego. Niektóre silniki wymagają do klonowania; pozostaw puste, jeśli nie wiesz.",
    consentHint: "Możesz zapisać bez zaznaczenia, ale głos nie zostanie przesłany do klonowania stronie trzeciej.",
    save: "Zapisz jako głos",
    saveEdit: "Zapisz",
    cancel: "Anuluj",
    loading: "Wczytywanie głosu…",
    loadFailed: (text: string) => `Nie udało się wczytać głosu: ${text}`,
    saved: (name: string) => `Zapisano „${name}” · dostępne przy generowaniu mowy i dubbingu`,
    updated: (name: string) => `Zapisano „${name}”`,
    unchanged: "Bez zmian",

    uploadTitle: (label: string) => `Prześlij do ${label}?`,
    upload: "Prześlij",
    cloneStarted: (label: string) => `Przesyłanie do ${label} · postęp w zadaniach w tle`,
    cloneRejected: (text: string) => `Nie udało się rozpocząć klonowania: ${text}`,
    removeCloneTitle: (label: string) => `Usuń klon u dostawcy ${label}?`,
    removeCloneBody: (label: string) => `${label} otrzyma prośbę usunięcia klonu. Aby użyć głosu u dostawcy ${label} potem trzeba przesłać ponownie.`,
    removeCloneConfirm: "Usuń klon",
    cloneRemoved: (label: string) => `Usunięto klon u dostawcy ${label}`,
    cloneGoneRemote: (label: string) => `${label} nie ma już klonu; zapis na komputerze także wyczyszczono`,
    cloneRemoveFailed: (text: string) => `Nie udało się usunąć klonu: ${text}`,

    exportTitle: "Eksportuj pakiet głosu",
    exportButton: "Eksportuj",
    exported: (path: string) => `Wyeksportowano do ${path}`,
    exportFailed: (text: string) => `Nie udało się eksportować: ${text}`,
    exportExists: "BaoCut nie nadpisuje plików. Wybierz inną nazwę lub lokalizację i eksportuj ponownie.",
    exportFailedExists: (text: string) => `Nie udało się eksportować: ${text}. BaoCut nie nadpisuje plików. Wybierz inną nazwę lub lokalizację i eksportuj ponownie.`,

    deleteTitle: (name: string) => `Usuń „${name}”?`,
    deleteConfirm: "Usuń",
    deleted: (name: string) => `Usunięto czcionkę „${name}”`,
    deleteFailed: (text: string) => `Nie udało się usunąć: ${text}`,
    localOnlyTitle: (label: string) => `Klon u dostawcy ${label} nie został usunięty`,
    localOnlyBody: (label: string, text: string) => `${text}

Głos nadal tutaj. Spróbuj później lub usuń tylko zapis i głos na komputerze. Klon u dostawcy ${label} pozostanie na koncie, trzeba usunąć samodzielnie u dostawcy ${label}`,
    localOnlyConfirm: "Usuń tylko na tym komputerze",
    later: "Spróbuj później",
  },
};
