import type { CliMessages } from './cli-copy.ts';

export const ru: CliMessages = {
  helpTagline: "baocut — расшифровка, перевод, правки, озвучка и экспорт видео с BaoCut. Сначала выполните `baocut status` для возможностей компьютера.",
  helpFlows: "Процессы (возвращают задание; по умолчанию ждут завершения)",
  helpObjects: "Объекты",
  helpAdmin: "Локальное управление (для людей; агенты сначала спрашивают пользователя)",
  helpMore: "Подробнее",
  helpMoreHelp: "параметры, действие и примеры",
  helpMoreSpec: "машиночитаемый каталог (JSON)",
  helpMoreStatus: "что компьютер может сейчас",
  helpGlobalFlags: "--json --project <dir> --yes --max-bytes <n> --result-file <file> --no-start",
  helpJobFlags: "задания: --no-wait --timeout <s> --progress jsonl",
  helpAdminVerbs: "Локальное управление",
  helpGroupMore: (noun) => `baocut help ${noun} <command> для параметров и примеров.`,
  helpFlagsPlaceholder: "[flags]",
  effectLabel: (effect) => `действие: ${effect}`,
  effectQuery: "запрос (только чтение)",
  effectMutation: "изменение (меняет состояние)",
  effectJob: "задание (возвращает задание; по умолчанию ждёт завершения)",
  effectDestructive: "необратимое (нельзя отменить; требует --yes)",
  helpParameters: "Параметры",
  helpNoParameters: "(нет)",
  helpRequired: "обязательно",
  helpRepeatable: "можно повторять",
  helpPositionalNote: (positional, flag) => `${positional} можно указать позиционно или как ${flag}, только одно.`,
  helpExamples: "Примеры",
  helpCommonFlags: "Общие параметры",

  nextLabel: "далее",
  errorLabel: "ошибка",
  runtimeStartedNote: "(Runtime BaoCut запущен в фоне; сам завершится при простое)",
  spilledNote: (maxBytes) => `Результат больше ${maxBytes} байт: полный результат в файле path (JSON). coverage — ключи верхнего уровня и длины массивов, summary — короткие поля. Прочитайте файл, сузьте запрос параметрами continueWith.paging или повторите с --max-bytes continueWith.maxBytes.`,
  resultFileWritten: "Полный результат в файле path (JSON) по --result-file. coverage — ключи верхнего уровня и длины массивов, summary — короткие поля.",

  unknownCommand: (command) => `Неизвестная команда: ${command}. Выполните baocut --help для списка команд.`,
  unknownFlag: (flag, command) => `Неизвестный параметр ${flag} для baocut ${command}. См. baocut help ${command}.`,
  missingValue: (flag) => `${flag} требует значение.`,
  noValueExpected: (flag) => `${flag} — переключатель, без значения.`,
  duplicateFlag: (flag) => `${flag} указан несколько раз.`,
  badNumber: (flag, value) => `${flag} требует число, получено «${value}".`,
  badInteger: (flag, value) => `${flag} требует целое число, получено «${value}".`,
  badBoolean: (flag, value) => `${flag} требует true или false, получено «${value}".`,
  badChoice: (flag, value, choices) => `${flag} должен быть одним из ${choices.join(", ")}; получено «${value}".`,
  badValue: (flag, value) => `«${value}» — недопустимое значение для ${flag}.`,
  badJson: (flag, reason) => `${flag} требует JSON (литерал, @file или - для stdin): ${reason}`,
  expectedObject: (flag) => `${flag} требует объект JSON.`,
  readFileFailed: (flag, file, reason) => `Не удалось прочитать ${file} для ${flag}: ${reason}`,
  stdinTwice: (flag) => `Стандартный ввод читается только раз (${flag} запросил снова).`,
  noPositional: (command, value) => `baocut ${command} не принимает позиционный аргумент (получено «${value}»); используйте параметры.`,
  tooManyPositionals: (command, extra) => `baocut ${command} принимает один позиционный аргумент; лишний: ${extra}`,
  positionalAndFlag: (field, flag) => `${field} указан позиционно и как ${flag}; укажите только одно.`,
  missingRequired: (names, command) => `Не указано ${names}. См. baocut help ${command}.`,
  dryRunUnsupported: (command) => `baocut ${command} не имеет --dry-run.`,
  projectNotDirectory: (value) => `--project ${value} не является папкой.`,
  confirmationRequired: (command, summary) => `baocut ${command} нельзя отменить, не выполнено. Выполнило бы: ${summary} Повторите с --yes после согласия пользователя.`,
  confirmationNext: (command) => `baocut ${command} … --yes (после согласия пользователя)`,
  unknownSpec: (name) => `Нет инструмента с именем ${name}. baocut spec показывает весь каталог.`,
  unknownEditOp: (op) => `У edits apply нет операции с именем ${op}. baocut edits ops показывает список.`,
  catalogUnavailable: (command) => `Нет офлайн-снимка каталога и запущенного Runtime. Создайте через \`${command}\` (в репозитории) либо запустите Runtime через baocut runtime ensure.`,
  runtimeUsage: "Использование: baocut runtime ensure | status | stop",
  installConfirmationRequired: (bundleId, size, source) => `Установка локальной модели ${bundleId} скачивает ${size} из ${source}; ничего не скачано. Сообщите размер пользователю и повторите с --yes после согласия.`,
  sizeEstimated: " (оценка)",

  metaHelp: {
    help: "baocut help [<command>]\n\nБез команды: краткий обзор на одном экране. С командой (`help videos`, `help videos inspect`, `help runtime`): параметры, действие и примеры. Использует каталог запущенного Runtime, иначе офлайн-снимок; никогда не запускает Runtime.",
    spec: "baocut spec [<name>]\n\nМашиночитаемый каталог чистым JSON (без оболочки) с версией интерфейса. <name> — имя инструмента (videos_inspect), имя с точкой (videos.inspect), команда (videos inspect) или edits.<operation> для одной операции edits apply. Использует каталог запущенного Runtime, иначе офлайн-снимок; никогда не запускает Runtime.",
    version: "baocut version\n\nВерсии CLI и запущенного Runtime, обе версии интерфейса инструментов и их совместимость. Чистый JSON; никогда не запускает Runtime.",
    status:
      "baocut status [--full] [--no-start]\n\nВозможности компьютера сейчас: Runtime, каждая возможность со значением по умолчанию и доступностью, локальные пакеты моделей и внешние инструменты, команды решения недостающего. Возможности и пакеты кратко; --full добавляет всех поставщиков с моделями, параметрами и лимитами, а также детали пакетов. Запускает Runtime при отсутствии; с --no-start отвечает running: false.",
    runtime: [
      "baocut runtime ensure | status | stop",
      "",
      "Runtime BaoCut для этого CLI (один на BAOCUT_HOME).",
      "  ensure   найти Runtime или запустить в фоне; запущенный CLI Runtime завершается сам",
      "           после runtime.idleExitMinutes простоя (нет подключений, заданий или сервисов)",
      "  status   работа, инициатор, подключения, активные задания, сервисы и выход при простое; не запускает",
      "  stop     остановить Runtime CLI. RUNTIME_NOT_OWNED при запуске настольным приложением или другим,",
      "           RUNTIME_IN_USE при использовании приложением, другим CLI или незавершённым заданием (код выхода 1)",
      "",
      "Параметры: --json  --no-start (ensure: код выхода 3 вместо запуска)",
    ].join("\n"),
  },

  runtimeNotRunning: (home) => `Нет запущенного Runtime BaoCut для ${home}, указан --no-start.`,
  runtimeNoEntry:
    "Runtime BaoCut не запущен и не запускается: установите приложение, запустите из репозитория или задайте точку входа в BAOCUT_RUNTIME_ENTRY.",
  runtimeStartFailed: (reason, log) => `Не удалось запустить Runtime BaoCut (${reason}). См. ${log}.`,
  runtimeStartTimeout: (seconds, log) => `Runtime BaoCut не был готов за ${seconds} с. См. ${log}.`,
  exitedWith: (code) => `завершился с кодом ${code ?? 'unknown'}`,
  runtimeConnectFailed: (reason) => `Не удалось подключиться к Runtime BaoCut: ${reason}`,
  runtimeLost: (reason) => `Потеряно соединение с Runtime BaoCut: ${reason}`,
  protocolMismatch: (reason) => `Версии протокола CLI и Runtime BaoCut различаются: ${reason}. Обновите старую.`,
  interfaceMismatch: (cli, runtime, update) => `CLI использует версию интерфейса инструментов ${cli}, Runtime использует ${runtime}. ${update === 'cli' ? "Обновите CLI." : "Обновите BaoCut (или перезапустите Runtime из той же рабочей копии, что CLI)."}`,

  jobCancelling: (jobId) => `Отмена ${jobId}… (нажмите Ctrl-C снова для немедленной остановки ожидания)`,
  jobCancelFailed: (reason) => `Не удалось отменить задание: ${reason}`,
  jobEnded: (state) => `Задание завершено: ${state}.`,
  statusFullNext:
    "baocut status --full показывает всех поставщиков и модели по возможностям; для одной выполните baocut models capabilities --capability <capability>, для пакетов baocut models list.",
  waitTimeout: (seconds, jobId) => `Ожидание остановлено спустя ${seconds} с; задание ${jobId} продолжает работу.`,

  noRuntimeClient: "Команда не подключается к Runtime",
};
