import type { CliMessages } from './cli-copy.ts';

export const vi: CliMessages = {
helpTagline: 'baocut · chép lời, dịch, chỉnh sửa, lồng tiếng và xuất video bằng BaoCut. Chạy `baocut status` trước để xem máy này có thể làm gì.', helpFlows: 'Quy trình (trả về công việc; mặc định chờ hoàn tất)', helpObjects: 'Đối tượng', helpAdmin: 'Quản trị cục bộ (dành cho người; Agent hỏi người dùng trước)', helpMore: 'Thêm', helpMoreHelp: 'tham số, tác động và ví dụ', helpMoreSpec: 'danh mục máy đọc được (JSON)', helpMoreStatus: 'máy này hiện có thể làm gì', helpGlobalFlags: '--json --project <dir> --yes --max-bytes <n> --result-file <file> --no-start', helpJobFlags: 'công việc: --no-wait --timeout <s> --progress jsonl', helpAdminVerbs: 'Quản trị cục bộ', helpGroupMore: (noun) => `baocut help ${noun} <command> để xem tham số và ví dụ.`, helpFlagsPlaceholder: '[flags]', effectLabel: (effect) => `tác động: ${effect}`, effectQuery: 'truy vấn (chỉ đọc)', effectMutation: 'thay đổi (đổi trạng thái)', effectJob: 'công việc (trả về công việc; mặc định chờ hoàn tất)', effectDestructive: 'phá hủy (không thể hoàn tác; cần --yes)', helpParameters: 'Tham số', helpNoParameters: '(không có)', helpRequired: 'bắt buộc', helpRepeatable: 'có thể lặp', helpPositionalNote: (positional, flag) => `${positional} có thể cung cấp làm đối số vị trí hoặc ${flag}, không dùng cả hai.`, helpExamples: 'Ví dụ', helpCommonFlags: 'Cờ chung',
nextLabel: 'tiếp theo', errorLabel: 'lỗi', runtimeStartedNote: '(đã khởi chạy Runtime BaoCut trong nền; tự thoát khi nhàn rỗi)', spilledNote: (maxBytes) => `Kết quả lớn hơn ${maxBytes} byte: kết quả đầy đủ trong tệp tại path (JSON). coverage liệt kê khóa cấp cao nhất và độ dài mảng, summary liệt kê trường ngắn. Đọc tệp, thu hẹp yêu cầu bằng cờ trong continueWith.paging hoặc chạy lại với --max-bytes continueWith.maxBytes.`, resultFileWritten: 'Kết quả đầy đủ trong tệp tại path (JSON) theo yêu cầu --result-file. coverage liệt kê khóa cấp cao nhất và độ dài mảng, summary liệt kê trường ngắn.',
unknownCommand: (command) => `Lệnh không xác định: ${command}. Chạy baocut --help để xem lệnh.`, unknownFlag: (flag, command) => `Cờ ${flag} không xác định cho baocut ${command}. Xem baocut help ${command}.`, missingValue: (flag) => `${flag} cần giá trị.`, noValueExpected: (flag) => `${flag} là công tắc và không nhận giá trị.`, duplicateFlag: (flag) => `${flag} đã được cung cấp nhiều lần.`, badNumber: (flag, value) => `${flag} cần số, nhận được “${value}”.`, badInteger: (flag, value) => `${flag} cần số nguyên, nhận được “${value}”.`, badBoolean: (flag, value) => `${flag} cần true hoặc false, nhận được “${value}”.`, badChoice: (flag, value, choices) => `${flag} phải là một trong ${choices.join(', ')}; nhận được “${value}”.`, badValue: (flag, value) => `“${value}” không phải giá trị hợp lệ cho ${flag}.`, badJson: (flag, reason) => `${flag} cần JSON (giá trị trực tiếp, @file hoặc - cho stdin): ${reason}`, expectedObject: (flag) => `${flag} cần đối tượng JSON.`, readFileFailed: (flag, file, reason) => `Không đọc được ${file} cho ${flag}: ${reason}`, stdinTwice: (flag) => `Đầu vào chuẩn chỉ đọc được một lần (${flag} yêu cầu lại).`, noPositional: (command, value) => `baocut ${command} không nhận đối số vị trí (nhận được “${value}”); dùng cờ.`, tooManyPositionals: (command, extra) => `baocut ${command} nhận một đối số vị trí; phần thừa: ${extra}`, positionalAndFlag: (field, flag) => `${field} được cung cấp cả làm đối số vị trí và ${flag}; chỉ dùng một.`, missingRequired: (names, command) => `Thiếu ${names}. Xem baocut help ${command}.`, dryRunUnsupported: (command) => `baocut ${command} không có --dry-run.`, projectNotDirectory: (value) => `--project ${value} không phải thư mục.`, confirmationRequired: (command, summary) => `baocut ${command} không thể hoàn tác và chưa chạy. Sẽ thực hiện: ${summary} Chạy lại với --yes sau khi người dùng đồng ý.`, confirmationNext: (command) => `baocut ${command} … --yes (sau khi người dùng đồng ý)`, unknownSpec: (name) => `Không có công cụ tên ${name}. baocut spec liệt kê toàn bộ danh mục.`, unknownEditOp: (op) => `edits apply không có thao tác tên ${op}. baocut edits ops liệt kê chúng.`, catalogUnavailable: (command) => `Thiếu ảnh chụp danh mục ngoại tuyến và Runtime chưa chạy. Tạo bằng \`${command}\` (trong kho) hoặc khởi chạy Runtime bằng baocut runtime ensure.`, runtimeUsage: 'Cách dùng: baocut runtime ensure | status | stop', installConfirmationRequired: (bundleId, size, source) => `Cài mô hình cục bộ ${bundleId} sẽ tải ${size} từ ${source}; chưa tải gì. Báo kích thước cho người dùng và chạy lại với --yes sau khi đồng ý.`, sizeEstimated: ' (ước tính)',
metaHelp: {
 help: 'baocut help [<command>]\n\nKhông có lệnh: tổng quan một màn hình. Có lệnh (`help videos`, `help videos inspect`, `help runtime`): tham số, tác động và ví dụ. Dùng danh mục Runtime đang chạy nếu có, nếu không dùng ảnh chụp ngoại tuyến; không khởi chạy Runtime.',
 spec: 'baocut spec [<name>]\n\nDanh mục máy đọc được dạng JSON thuần (không có lớp bao), kèm phiên bản giao diện. <name> là tên công cụ (videos_inspect), tên có dấu chấm (videos.inspect), lệnh (videos inspect) hoặc edits.<operation> cho một thao tác edits apply. Dùng danh mục Runtime đang chạy nếu có, nếu không dùng ảnh chụp ngoại tuyến; không khởi chạy Runtime.',
 version: 'baocut version\n\nPhiên bản CLI này và Runtime nếu đang chạy, cùng phiên bản giao diện công cụ của cả hai và có khớp hay không. JSON thuần; không khởi chạy Runtime.',
 status: 'baocut status [--full] [--no-start]\n\nMáy này hiện có thể làm gì: Runtime, từng khả năng với mặc định và tính khả dụng, gói mô hình cục bộ và công cụ ngoài, kèm lệnh khắc phục phần thiếu. Khả năng và gói mô hình là tóm tắt; --full thêm mọi nhà cung cấp cùng mô hình, tham số, giới hạn và chi tiết gói. Khởi chạy Runtime nếu chưa chạy; với --no-start trả lời running: false thay thế.',
 runtime: ['baocut runtime ensure | status | stop', '', 'Runtime BaoCut mà CLI này liên lạc (một cho mỗi BAOCUT_HOME).', '  ensure   tìm Runtime đang chạy hoặc khởi chạy trong nền; Runtime do CLI khởi chạy tự thoát', '           sau runtime.idleExitMinutes nhàn rỗi (không có kết nối, công việc hoặc dịch vụ mở)', '  status   có chạy không, ai khởi chạy, kết nối, công việc hoạt động, dịch vụ mở và tự thoát; không khởi chạy', '  stop     dừng Runtime do CLI khởi chạy. RUNTIME_NOT_OWNED khi ứng dụng máy tính hoặc người khác khởi chạy,', '           RUNTIME_IN_USE khi ứng dụng máy tính, CLI khác hoặc công việc chưa xong đang dùng (mã thoát 1)', '', 'Cờ: --json  --no-start (ensure: thất bại với mã thoát 3 thay vì khởi chạy)'].join('\n'),
},
runtimeNotRunning: (home) => `Không có Runtime BaoCut chạy cho ${home} và đã cung cấp --no-start.`, runtimeNoEntry: 'Không có Runtime BaoCut đang chạy và không khởi chạy được: cài ứng dụng BaoCut, chạy từ kho hoặc đặt BAOCUT_RUNTIME_ENTRY đến điểm vào Runtime.', runtimeStartFailed: (reason, log) => `Không khởi chạy được Runtime BaoCut (${reason}). Xem ${log}.`, runtimeStartTimeout: (seconds, log) => `Runtime BaoCut chưa sẵn sàng trong ${seconds} giây. Xem ${log}.`, exitedWith: (code) => `đã thoát với mã ${code ?? 'chưa rõ'}`, runtimeConnectFailed: (reason) => `Không kết nối được Runtime BaoCut: ${reason}`, runtimeLost: (reason) => `Mất kết nối Runtime BaoCut: ${reason}`, protocolMismatch: (reason) => `CLI này và Runtime BaoCut dùng phiên bản giao thức khác nhau: ${reason}. Cập nhật bản cũ hơn.`, interfaceMismatch: (cli, runtime, update) => `CLI này dùng phiên bản giao diện công cụ ${cli}, Runtime dùng ${runtime}. ${update === 'cli' ? 'Cập nhật CLI.' : 'Cập nhật ứng dụng BaoCut (hoặc khởi động lại Runtime từ cùng bản sao kho với CLI).'}`,
jobCancelling: (jobId) => `Đang hủy ${jobId}… (nhấn Ctrl-C lần nữa để dừng chờ ngay)`, jobCancelFailed: (reason) => `Không hủy được công việc: ${reason}`, jobEnded: (state) => `Công việc đã kết thúc: ${state}.`, statusFullNext: 'baocut status --full liệt kê mọi nhà cung cấp và mô hình cho từng khả năng; cho một khả năng chạy baocut models capabilities --capability <capability>, chi tiết gói dùng baocut models list.', waitTimeout: (seconds, jobId) => `Đã dừng chờ sau ${seconds} giây; công việc ${jobId} vẫn chạy.`, noRuntimeClient: 'Lệnh này không kết nối Runtime',
};
