import type { AgentPolicy } from '@baocut/protocol';
import { revealLabel } from '../../copy.ts';
import type { AgentMessages } from './agent-copy.ts';

export const ko: AgentMessages = {
  pageTitle: 'Agent 공급자',
  factsLabel: 'Agent 작동 방식',
  permissionsTitle: 'Agent 권한',
  lede: 'Agent는 Claude Code나 Codex처럼 내 컴퓨터에 설치된 AI 코딩 어시스턴트입니다. BaoCut이 이를 직접 호출하므로 한 문장으로 전사, 번역, 편집을 마칠 수 있습니다.',
  facts: [
    { key: 'cli', title: '이미 설치된 것을 사용', body: 'BaoCut은 따로 설치하지 않고 이 컴퓨터의 명령줄 Agent를 호출합니다.' },
    { key: 'plan', title: '내 구독을 사용', body: 'BaoCut에 추가로 결제할 필요가 없고 API 키를 입력할 필요도 없습니다.' },
    { key: 'ask', title: '변경하기 전에 먼저 확인', body: '영상에 쓰기 전에 멈추고 허락을 기다리며, 언제든지 실행 취소할 수 있습니다.' },
  ],

  providersHeading: '이 컴퓨터의 Agent',
  providersHint:
    'BaoCut이 이미 설치된 Agent를 찾아 줍니다. 작동하는 Agent 하나면 충분하며 모두 설치할 필요는 없습니다. 잘 모르겠다면 Claude Code나 Codex를 선택하세요. 내장 Agent는 비활성화만 할 수 있고, 직접 추가한 Agent는 제거할 수 있습니다.',
  providersMeta: (checked: string | null, builtin: number, added: number, found: number) =>
    `${checked ? `${checked} 확인 · ` : ''}BaoCut 내장 Agent ${builtin}개${added ? `, 직접 추가한 Agent ${added}개` : ''}, 이 컴퓨터에서 감지된 Agent ${found}개`,
  statusLabel: 'Agent 상태',
  scanDone: (n: number) => (n ? `확인 완료 · 이 컴퓨터의 Agent ${n}개` : '확인 완료 · 설치된 Agent를 찾지 못했습니다'),
  scanFailed: (message: string) => `다시 확인하지 못했습니다: ${message}`,
  enableFailed: (message: string) => `활성화하지 못했습니다: ${message}`,
  scanning: '확인 중…',
  rescan: '다시 확인',
  emptyDisconnected: 'Runtime에 연결하면 이 컴퓨터의 Agent를 확인합니다.',
  emptyNoDrivers: '이 버전의 Runtime에는 Agent가 포함되어 있지 않습니다.',
  emptyNoneFound: '이 컴퓨터에서 감지된 Agent가 없습니다. 자주 쓰는 Agent는 아래에 있습니다.',
  scanProgress: 'Agent 확인 중',
  faqLabel: '자주 묻는 질문',
  goCloudModels: '클라우드 모델로 이동',
  goSkills: 'Skills로 이동',

  moreProviders: {
    title: (count: number) => `지원되는 다른 Agent · ${count}개`,
    sub: (names: string) => `${names} · 이 컴퓨터에서 감지되지 않음`,
    expand: '보기',
    collapse: '숨기기',
  },

  fullAccessOnly:
    '단계별로 승인을 요청할 방법이 없어 BaoCut은 “전체 접근” 모드로만 실행할 수 있습니다. 명령을 실행하거나 파일을 변경하기 전에 묻지 않습니다.',

  untested: {
    badge: 'BaoCut에서 테스트되지 않음',
    body: '이 Agent는 BaoCut에서 실제 기기로 전체 세션을 완료한 적이 없습니다. 감지, 로그인, 모델 목록은 평소대로 작동하며, 세션 중 문제가 생기면 해당 Agent의 문서를 따르세요.',
  },

  catalog: {
    heading: 'Agent 더 추가',
    hint: 'ACP(Agent Client Protocol)를 지원하는 다른 명령줄 Agent도 추가할 수 있습니다. BaoCut이 하나하나 검증하지는 않았으며, 사용 가능 여부는 확인 결과에 따릅니다.',
    custom: '사용자 지정 명령…',
    search: '추가할 Agent 검색',
    searchPlaceholder: '이름, 설명 또는 명령으로 검색',
    count: (total: number) => `카탈로그에 ${total}개`,
    found: (n: number) => `${n}개 찾음`,
    list: '추가할 수 있는 Agent',
    add: '추가',
    addTo: (name: string) => `${name} 추가`,
    added: '추가됨',
    empty: (query: string) => `카탈로그에 “${query}”에 해당하는 항목이 없습니다. 목록에 없는 Agent는 실행 명령을 입력해 추가하세요.`,
    landed: (name: string, custom: boolean) => `${name}${custom ? '(사용자 지정 명령)' : ''} 추가됨 · 감지되면 세션에서 사용할 수 있습니다`,
    addFailed: (message: string) => `추가하지 못했습니다: ${message}`,
    webNote: '이 설정에 따라 이 컴퓨터에서 실행할 명령이 정해지므로 브라우저에서는 Agent를 추가하거나 제거할 수 없습니다. BaoCut 데스크톱 앱을 사용하세요.',
  },

  customDialog: {
    title: '사용자 지정 명령으로 Agent 추가',
    lede: '터미널에서 ACP 모드로 시작하는 명령을 입력하세요. BaoCut은 터미널을 거치지 않고 프로그램을 직접 시작합니다.',
    name: '이름',
    namePlaceholder: '예: 내 Agent',
    id: 'id',
    idPlaceholder: 'my-agent',
    idHint: '설정과 진단에서 이 Agent를 구분하는 데 쓰입니다. 영문 소문자로 시작하고 소문자, 숫자, 하이픈만 사용하세요.',
    command: '명령',
    commandPlaceholder: 'my-agent --acp',
    commandHint: '공백을 기준으로 프로그램과 인수로 나뉩니다. 공백이 들어 있는 인수는 따옴표로 감싸세요.',
    commandParts: (exe: string, args: string[]) => `다음과 같이 시작합니다: 프로그램 ${exe}, 인수 ${args.join(' · ')}`,
    env: '환경 변수(선택)',
    envPlaceholder: 'MY_AGENT_TOKEN_FILE=~/.config/my-agent/token\nMY_AGENT_LOG=0',
    envHint: '한 줄에 KEY=VALUE 하나씩 입력하세요. BaoCut이 이 Agent를 시작할 때만 추가됩니다.',
    note: '추가한 뒤 BaoCut이 시작되는지, 로그인이 필요한지, 어떤 모델이 있는지 확인합니다. 감지되면 세션에 표시됩니다.',
    cancel: '취소',
    submit: '추가',
    exists: (id: string) => `“${id}” id를 이미 사용하는 Agent가 있습니다. 다른 id를 입력하세요.`,
  },

  added: {
    chip: '직접 추가함',
    detect: '확인',
    detecting: '확인 중…',
    remove: '제거',
    subFound: (version: string | null) => ['감지됨', version ? `v${version}` : null, 'ACP로 연결됨'].filter(Boolean).join(' · '),
    subLauncher: (launcher: string, needs: string) => `아직 확인 안 함 · 실행할 때 ${launcher} 명령으로 다운로드, ${needs} 필요`,
    subMissing: (command: string) => `아직 확인 안 함 · 이 컴퓨터에서 ${command} 명령을 찾을 수 없음`,
    note: (name: string) =>
      `${name}은(는) ACP(Agent Client Protocol)로 연결됩니다. BaoCut이 검증하지 않았으므로 설치 방법과 로그인할 계정은 해당 Agent의 문서를 따르세요.`,
    noInstall: '따로 설치할 필요 없음',
    noInstallBody: (launcher: string, spec: string, needs: string) =>
      `BaoCut이 시작할 때 ${launcher} 명령이 ${spec} 패키지를 자동으로 다운로드합니다. 이 컴퓨터에 ${needs}이(가) 있어야 합니다.`,
    install: '공식 안내에 따라 이 컴퓨터에 설치',
    installBody: (command: string) => `설치가 끝나면 터미널에서 ${command} 명령을 실행할 수 있어야 합니다.`,
    docs: '공식 안내 열기',
    launch: 'BaoCut은 이 명령으로 시작합니다',
    launchCopy: '실행 명령',
    envNote: (keys: string[]) => `실행할 때 환경 변수를 추가합니다: ${keys.join(', ')}. 값은 여기에 표시되지 않습니다.`,
    login: '로그인이 필요하면 해당 Agent에서 로그인',
    loginBody: '터미널에서 해당 Agent의 안내를 따르세요. 로그인은 해당 Agent의 창에서 이루어지며 BaoCut은 계정이나 비밀번호를 다루지 않습니다.',
    detectStep: '확인',
    detectBody: 'BaoCut이 한 번 시작해 연결되는지, 로그인이 필요한지 확인하고 모델 목록을 가져옵니다.',
    launchRow: '실행 명령',
    launchRowHint: 'BaoCut은 ACP(Agent Client Protocol)를 통해 이 명령으로 시작합니다.',
    versionPinned: (spec: string) => `실행 명령이 ${spec}에 고정되어 있습니다. 버전을 바꾸려면 제거한 뒤 사용자 지정 명령으로 다시 추가하세요.`,
    versionOwn: '업그레이드는 해당 Agent의 안내를 따른 뒤 여기서 다시 확인하세요.',
    account: (name: string, signedOut: boolean) =>
      `${signedOut ? '로그인하지 않았거나 로그인이 만료되었습니다. ' : ''}로그인과 결제는 모두 ${name}에서 이루어지며, BaoCut은 계정을 다루지 않고 추가 요금도 받지 않습니다.`,
    removeTitle: (name: string) => `${name}을(를) 제거할까요?`,
    removeBody: (name: string) =>
      `${name}이(가) BaoCut의 Agent 목록에서 제거되며, 활성화 상태와 기본 모델도 함께 지워집니다. 새 세션이 기본으로 이 Agent를 사용하고 있었다면 사용 가능한 다른 Agent가 대신합니다. 이 Agent를 사용하는 작업은 종료됩니다. 이 컴퓨터에 설치된 프로그램은 영향을 받지 않으며 나중에 다시 추가할 수 있습니다.`,
    removed: (name: string) => `${name}을(를) 제거했습니다`,
    removeFailed: (message: string) => `제거하지 못했습니다: ${message}`,
  },

  codexImage: {
    title: 'Codex로 그리기',
    body: '키가 필요 없으며 Codex 구독을 사용합니다. 한 번에 한 장씩 생성하고 크기와 품질 설정은 무시하며 API보다 5–10배 느립니다. 켜면 bcut image와 세션의 Agent 모두 이 모델(이름: “Codex”)을 선택할 수 있습니다. 자동으로 선택되지는 않으므로 기본으로 사용하려면 모델 › 이미지 생성 › 클라우드 모델에서 기본값으로 설정하세요.',
    checking: '이 컴퓨터의 Codex가 그림을 그릴 수 있는지 확인 중…',
    on: '켜짐',
    period: '.',
    probeFailed: 'Codex가 그림을 그릴 수 있는지 확인하지 못했습니다 · “다시 확인”을 클릭해 다시 시도하세요.',
    outdated: 'Codex 버전이 너무 오래되었습니다 · Codex CLI를 업그레이드한 뒤 켜세요',
    signedOut: 'Codex에 아직 로그인하지 않았습니다 · 그리기에는 Codex 계정을 사용하므로 로그인한 뒤 켜세요.',
    notInstalled: 'Codex를 찾지 못했습니다 · 그리려면 Codex CLI를 설치하고 로그인하세요.',
    unavailable: (detail: string | null) =>
      detail ? `지금은 Codex로 그릴 수 없습니다 · ${detail}` : '지금은 Codex로 그릴 수 없습니다 · “다시 확인”을 클릭해 다시 시도하세요.',
    turnedOn: 'Codex로 그리기를 켰습니다 · 이제 이미지 생성 모델 메뉴에 Codex가 있습니다',
    turnedOff: 'Codex로 그리기를 껐습니다',
    toggleFailed: (enabled: boolean, message: string) =>
      enabled ? `Codex로 그리기를 켜지 못했습니다: ${message}` : `Codex로 그리기를 끄지 못했습니다: ${message}`,
  },

  faq: [
    {
      key: 'cost',
      title: 'BaoCut에 따로 결제하거나 구독해야 하나요?',
      body: '아니요. Agent는 이미 사용 중인 Claude 또는 ChatGPT 구독을 사용하며, 비용과 사용 한도도 그쪽에서 계산됩니다. BaoCut은 자체 모델을 제공하지 않고, 키를 수집하지 않으며, 클라우드로 중계하지도 않습니다. 그런 구독이 없다면 Agent를 사용하지 않아도 되며 BaoCut의 다른 기능은 평소대로 작동합니다.',
    },
    {
      key: 'account',
      title: 'BaoCut이 내 계정과 비밀번호를 볼 수 있나요?',
      body: '아니요. 로그인은 Agent 자체 창에서 이루어집니다. BaoCut은 내 컴퓨터에서 해당 프로그램을 시작하고 영상을 넘겨줄 뿐입니다. 영상을 변경하기 전에는 먼저 묻습니다. 규칙은 설정 › 개인 정보 보호 및 권한에 있습니다.',
    },
    {
      key: 'cloud',
      title: 'Agent는 클라우드 모델과 어떻게 다른가요?',
      body: 'Agent는 내 컴퓨터의 코딩 어시스턴트와 그 구독을 사용하며 여러 단계의 작업을 수행할 수 있습니다. 클라우드 모델은 API 키로 단일 도구를 직접 실행하며 사용량에 따라 요금이 부과됩니다. 둘은 따로 설정합니다.',
      link: 'models',
    },
    {
      key: 'terminal',
      title: '터미널에서 이 Agent로 BaoCut을 다루고 싶나요?',
      body: 'BaoCut 안의 세션은 따로 준비할 필요가 없습니다. 터미널이나 다른 앱에서 사용하려면 해당 Agent에 BaoCut Skill을 설치하세요. 설정 › Skills를 참고하세요.',
      link: 'skills',
    },
  ],

  permissionsHeading: '언제 먼저 물을지 직접 정하세요',
  policyHeading: '반복되는 확인 줄이기',
  policyHint: '아래 규칙에 해당하는 작업은 자동으로 허용됩니다. 접근 모드도 확인 여부에 영향을 줍니다.',
  policy: {
    read: { label: '영상 콘텐츠 읽기', desc: '어시스턴트가 매번 묻지 않고 전사본과 영상 설정을 볼 수 있습니다.' },
    bcutro: { label: '영상과 진행 상황 조회', desc: '정보와 진행 상황을 확인할 수 있습니다. 이 명령은 영상을 변경하지 않습니다.' },
    loop: { label: '실행 중인 AI 작업에 응답', desc: '작업을 받고 답변을 제출할 수 있어 여러 단계 작업에서 중단이 줄어듭니다.' },
  } satisfies Record<keyof AgentPolicy, { label: string; desc: string }>,
  accessModes: '접근 모드',
  firstDefault: '처음 기본값',
  alwaysAllowed: '항상 허용하는 명령',
  saveFailed: (message: string) => `저장하지 못했습니다: ${message}`,
  ruleRemoved: (rule: string) => `${rule} 규칙을 제거했습니다`,
  ruleRemoveFailed: (message: string) => `규칙을 제거하지 못했습니다: ${message}`,
  modeHint: (firstDefault: string, last: string | null) =>
    `각 세션의 입력창 아래에서 접근 모드를 선택하세요. 처음에는 “${firstDefault}” 모드가 기본이며, 이후 새 세션은 가장 최근 선택을 따릅니다${last ? `(현재 “${last}”)` : ''}.`,

  advancedHeading: '고급 및 문제 해결',
  advancedHint: '연결이 정상이면 여기서 바꿀 것은 없습니다.',
  modelAutoUpdate: {
    label: '모델 목록 자동 업데이트',
    desc: '시작할 때와 실행 중에 활성화된 각 Agent의 모델 목록을 정기적으로 업데이트합니다. 끄더라도 각 Agent의 세부 정보에서 직접 새로 고칠 수 있습니다.',
  },
  executableHint:
    'BaoCut은 PATH와 일반적인 설치 위치(Homebrew, npm 전역 폴더, ~/.local/bin)에서 찾습니다. 버전 관리자(nvm, asdf, mise)로 설치한 경우 다른 위치에 있을 수 있으니 여기에 실행 파일의 전체 경로를 입력하세요. 비워 두면 다시 자동으로 찾습니다.',
  techPanel: '기술 정보 및 위치',
  techTitle: 'Agent 기술 정보',
  techSubtitle: '버전, 경로, 사용 가능한 모델',
  techEmpty: '아직 확인 결과가 없습니다.',
  techNotInstalled: '· 설치 안 됨',
  techNoModels: '보고된 모델 목록 없음',
  pathLabel: '경로',
  diagnosticsLabel: '진단 정보',
  copyDiagnostics: '진단 정보 복사',
  locateTitle: 'Agent 위치 직접 지정',
  locateSubtitle: '자동 감지로 찾지 못할 때 사용',

  command: {
    copied: (label: string) => `${label}을(를) 복사했습니다`,
    copyFailed: '복사하지 못했습니다. 텍스트를 선택해 직접 복사하세요.',
    copy: (label: string) => `${label} 복사`,
    stop: '중지',
    run: '이 명령 실행',
    output: '명령 출력',
    running: '실행 중',
    runningText: '실행 중…',
    done: '완료',
    stopped: '중지했습니다. 이미 실행된 부분은 되돌리지 않으며 다시 실행할 수 있습니다.',
    failed: (reason: string) => `성공하지 못했습니다(${reason}). 위 출력에 이유가 있습니다. 비밀번호가 필요하면 터미널에서 실행하세요.`,
    runInTerminal: '터미널에서 실행',
    exitCode: (code: number) => `종료 코드 ${code}`,
    startFailed: (error: string) => `시작하지 못함: ${error}`,
    killed: '프로세스가 종료됨',
    confirmInstall: (name: string) => `${name} 설치 명령을 실행할까요?`,
    confirmUpgrade: (name: string) => `${name} 업그레이드 명령을 실행할까요?`,
    confirmRun: '실행',
    cancel: '취소',
    confirmBefore: 'BaoCut이 이 컴퓨터에서 아래 명령을 실행합니다. 출력은 명령 아래에 표시되며 언제든지 중지할 수 있습니다.',
    confirmAfter: '비밀번호가 필요한 명령은 여기서 실패하므로 터미널에서 실행하세요.',
    restored: (name: string) => `${name} 위치를 다시 자동으로 찾습니다`,
    switched: (path: string) => `이제 ${path} 경로를 사용합니다`,
    notFoundAt: (path: string, command: string) => `${path}에서 실행할 수 있는 ${command} 명령을 찾지 못했습니다`,
    saveFailed: (message: string) => `위치를 저장하지 못했습니다: ${message}`,
    locationLabel: (name: string) => `${name} 위치`,
    locationPlaceholder: (command: string) => `/전체/경로/${command}`,
    locationSaved: '직접 지정했습니다. 비우고 저장하면 다시 자동으로 찾습니다.',
    locationAuto: '비움 = 자동 찾기',
    save: '저장',
    restoreAuto: '자동 찾기 사용',
  },

  skills: {
    lede: 'Skill은 BaoCut의 Agent에게 특정 방식으로 일하는 법을 알려 주는 폴더(SKILL.md와 선택적 참고 파일)입니다. 스위치를 켜 두면 Agent가 작업과 관련 있다고 판단할 때 알아서 사용하고, 끄면 입력창의 “+”에서 직접 선택할 때만 사용합니다. Skill을 켜거나 끄고, 추가하거나 제거한 내용은 다음에 새로 시작하는 Agent 세션부터 적용됩니다.',
    search: 'Skill 검색',
    filter: '출처별 필터',
    tab: (label: string, count: number) => `${label} ${count}`,
    tabLabel: (label: string, count: number) => `${label}, ${count}개`,
    add: 'Skill 추가',
    addFolder: '로컬 폴더에서 추가',
    addGithub: 'GitHub에서 가져오기',
    loading: 'Skill 불러오는 중…',
    loadFailed: (message: string) => `Skill을 불러오지 못했습니다: ${message}`,
    retry: '다시 시도',
    disconnected: 'BaoCut Runtime에 연결되지 않았습니다. 연결되면 Skill 목록이 표시됩니다.',
    emptyTitle: '아직 Skill이 없습니다',
    emptyBody:
      '아직 사용할 수 있는 Skill이 없습니다. 직접 작성한 Skill 폴더를 추가하거나 GitHub에서 다른 사람이 공유한 Skill을 가져오세요. 서드파티 Skill은 가져온 뒤 꺼져 있으니 내용을 살펴본 뒤 켜세요.',
    emptyWeb: '아직 사용할 수 있는 Skill이 없습니다. 브라우저에서는 보기와 켜고 끄기만 할 수 있으니 추가와 가져오기는 BaoCut 데스크톱 앱에서 하세요.',
    noMatch: (query: string) => `“${query}”에 해당하는 Skill이 없습니다`,
    noMatchHint: '다른 단어로 검색하거나 “전체”로 전환하세요.',
    noneInTab: (label: string) => `“${label}”에 아직 Skill이 없습니다`,
    webNote: '브라우저에서는 Skill을 보고 켜거나 끌 수 있습니다. 추가, 가져오기, 제거는 BaoCut 데스크톱 앱에서 하세요.',
    view: (name: string) => `${name} 보기`,
    enable: (name: string) => `${name} 활성화`,
    toggledOn: (name: string) => `“${name}” Skill을 켰습니다: 다음에 새로 시작하는 세션부터 관련 있을 때 Agent가 알아서 사용합니다`,
    toggledOff: (name: string) => `“${name}” Skill을 껐습니다: 이제 입력창의 “+”에서 선택할 때만 사용합니다`,
    added: (name: string) => `“${name}” Skill을 추가했습니다`,
    imported: (name: string) => `“${name}” Skill을 가져왔습니다. 기본으로 꺼져 있습니다`,
    removed: (name: string) => `“${name}” Skill을 제거했습니다`,
    diagnosticsTitle: (count: number) => `폴더 ${count}개를 불러오지 못했습니다`,
    diagnosticsHint: '이 폴더들은 사용할 수 있는 Skill이 아니어서 건너뛰었습니다. 고친 뒤 이 페이지로 돌아오면 다시 불러옵니다.',
    diagnosticCode: { invalid: '잘못된 형식', 'duplicate-id': '중복된 이름', 'builtin-conflict': '내장 Skill과 이름이 같음' },
    diagnosticLine: (dir: string, reason: string, issue: string) => `${dir} · ${reason}: ${issue}`,
    externalTitle: '터미널이나 다른 앱의 Agent에서 BaoCut 사용',
    externalBody:
      '위의 Skill은 BaoCut 안의 Agent용입니다. 터미널의 Claude Code나 Codex가 BaoCut으로 전사, 번역, 편집, 내보내기를 하도록 하려면 해당 Agent에 BaoCut Skill을 설치하세요. 이 Agent들의 전역 위치에 한 번에 설치하고, 설치 위치와 업데이트 필요 여부를 확인하는 기능은 이후 버전에서 제공됩니다.',
  },

  skillDetail: {
    close: '닫기',
    stateOn: '켜짐: 관련 있을 때 Agent가 알아서 사용합니다.',
    stateOff: '꺼짐: 입력창의 “+”에서 선택할 때만 사용합니다.',
    thirdPartyNote:
      '서드파티 Skill은 다른 사람이 공유한 저장소에서 가져온 것입니다. 켜기 전에 내용을 살펴보세요. BaoCut은 Skill 안의 어떤 파일도 실행하지 않으며, Skill이 Agent의 권한을 넓힐 수도 없습니다.',
    source: '출처',
    location: '위치',
    version: '버전',
    noVersion: '지정되지 않음',
    get reveal() {
      return revealLabel();
    },
    body: 'SKILL.md',
    emptyBody: 'SKILL.md에는 맨 위의 이름과 설명 외에 다른 내용이 없습니다.',
    files: (count: number) => `파일(${count})`,
    back: '뒤로',
    notText: '텍스트 파일이 아니어서 여기에 표시하지 않습니다',
    tooLarge: '파일이 너무 커서 여기에 표시하지 않습니다',
    loading: '불러오는 중…',
    loadFailed: (message: string) => `불러오지 못했습니다: ${message}`,
    remove: '제거',
    removeBuiltin: '내장 Skill은 제거할 수 없지만 끌 수는 있습니다.',
    removeTitle: (name: string) => `“${name}” Skill을 제거할까요?`,
    removeBody: (path: string) => `${path} 폴더와 그 안의 모든 파일을 삭제하며 되돌릴 수 없습니다. 이미 진행 중인 세션은 영향을 받지 않습니다.`,
    cancel: '취소',
  },

  skillGithub: {
    title: 'GitHub에서 가져오기',
    label: '저장소 URL',
    placeholder: 'owner/repo',
    description: '전체 URL을 붙여 넣어도 됩니다. 예: https://github.com/owner/repo/tree/main/skills/name',
    note: '이 URL이 가리키는 폴더의 파일만 다운로드하며 어떤 파일도 실행하지 않습니다. 가져온 Skill은 “서드파티”로 분류되고 기본으로 꺼져 있어 입력창의 “+”에서 선택할 때만 사용됩니다. 내용을 살펴본 뒤 켤지 결정하세요.',
    submit: '가져오기',
    pending: 'GitHub에서 다운로드 중…',
    cancel: '취소',
  },
};
