import type { AgentPolicy } from '@baocut/protocol';
import { revealLabel } from '../../copy.ts';
import type { AgentMessages } from './agent-copy.ts';

export const tr: AgentMessages = {
  pageTitle: "Ajan sağlayıcıları",
  factsLabel: "Ajanlar nasıl çalışır",
  permissionsTitle: "Ajan izinleri",
  lede: "Ajan, Claude Code veya Codex gibi bilgisayarınıza yüklü bir AI kodlama asistanıdır. BaoCut doğrudan çağırır; tek cümleyle yazıya dökme, çeviri ve düzenleme yaptırabilirsiniz.",
  facts: [
    { key: 'cli', title: "Mevcut aracınızı kullanır", body: "BaoCut bu bilgisayardaki komut satırı ajanı çağırır; kendisi için ayrı kopya kurmaz." },
    { key: 'plan', title: "Kendi aboneliğinizi kullanır", body: "BaoCut için ek ücret veya API anahtarı gerekmez." },
    { key: 'ask', title: "Değiştirmeden önce sorar", body: "Videoya yazmadan önce durur ve onayınızı bekler; istediğiniz zaman geri alabilirsiniz." },
  ],

  providersHeading: "Bu bilgisayardaki ajanlar",
  providersHint:
    "BaoCut yüklü olanları bulur. Çalışan bir Ajan yeterlidir; hepsine ihtiyacınız yok. Emin değilseniz Claude Code veya Codex seçin. Yerleşik olanlar yalnızca devre dışı bırakılabilir; ekledikleriniz kaldırılabilir.",
  providersMeta: (checked,builtin,added,found) => `${checked ? `Denetlendi: ${checked} · ` : ''}BaoCut içinde ${builtin} yerleşik Ajan var${added ? `, siz ${added} tane eklediniz` : ''}; bu bilgisayarda ${found} algılandı`,
  statusLabel: "Ajan durumu",
  scanDone: (n) => n ? `Denetim tamamlandı · bu bilgisayarda ${n} Ajan` : "Denetim tamamlandı · yüklü Ajan bulunamadı",
  scanFailed: (message) => `Yeniden denetlenemedi: ${message}`,
  enableFailed: (message) => `Etkinleştirilemedi: ${message}`,
  scanning: "Denetleniyor…",
  rescan: "Yeniden denetle",
  emptyDisconnected: "Bu bilgisayardaki ajanları denetlemek için Runtime bağlantısı kurun.",
  emptyNoDrivers: "Bu Runtime sürümü Ajan içermiyor.",
  emptyNoneFound: "Bu bilgisayarda Ajan algılanmadı; yaygın olanlar aşağıda listelenir.",
  scanProgress: "Ajanlar denetleniyor",
  faqLabel: "Sık sorulan sorular",
  goCloudModels: "Bulut modellerine git",
  goSkills: "Skill bölümüne git",

  moreProviders: {
    title: (count) => `Desteklenen diğer ajanlar · ${count}`,
    sub: (names) => `${names} · bu bilgisayarda hiçbiri algılanmadı`,
    expand: "Göster",
    collapse: "Gizle",
  },

  fullAccessOnly: "Adım adım onay isteme imkânı yok; BaoCut yalnızca Tam erişim modunda çalıştırabilir. Komut çalıştırmadan veya dosya değiştirmeden önce size sormaz.",

  untested: {
    badge: "BaoCut içinde denenmedi",
    body: "Bu Ajan gerçek bilgisayarda BaoCut içinde tam bir oturumu tamamlamadı. Algılama, oturum açma ve model listesi normal çalışır; oturumdaki sorunlar için kendi belgelerini izleyin.",
  },

  catalog: {
    heading: "Daha fazla Ajan ekle",
    hint: "ACP (Agent Client Protocol) destekleyen diğer komut satırı ajanlar de eklenebilir. BaoCut bunları tek tek doğrulamadı; çalışmaları denetim sonucuna bağlıdır.",
    custom: "Özel komut…",
    search: "Eklenecek Ajan ara",
    searchPlaceholder: "Ad, açıklama veya komuta göre ara",
    count: (total) => `Katalogda ${total}`,
    found: (n) => `${n} bulundu`,
    list: "Ekleyebileceğiniz ajanlar",
    add: "Ekle",
    addTo: (name) => `${name} adlı ajanı ekle`,
    added: "Eklendi",
    empty: (query) => `Katalogda “${query}” ile eşleşme yok. Listelenmeyen Ajan için başlatma komutunu girerek ekleyin.`,
    landed: (name,custom) => `${name} eklendi${custom ? ' (özel komut)' : ''} · algılanınca oturumlarda kullanılabilir`,
    addFailed: (message) => `Eklenemedi: ${message}`,
    webNote: "Tarayıcıda Ajan eklenemez veya kaldırılamaz; bu ayar bilgisayarda çalıştırılacak komutları belirler. BaoCut masaüstü uygulamasını kullanın.",
  },

  customDialog: {
    title: "Özel komutla Ajan ekle",
    lede: "Terminalde ACP modunda başlatan komutu girin. BaoCut programı terminal olmadan doğrudan başlatır.",
    name: "Ad",
    namePlaceholder: "ör. Benim Ajan",
    id: 'id',
    idPlaceholder: 'my-agent',
    idHint: "Bu ajanı ayar ve tanılarda tanımlar: küçük harfle başlayın; yalnızca küçük harf, rakam ve kısa çizgi kullanın.",
    command: "Komut",
    commandPlaceholder: 'my-agent --acp',
    commandHint: "Boşluklarda program ve argümanlara bölünür; boşluk içeren argümanları tırnak içine alın.",
    commandParts: (exe,args) => `Başlatılacak program: ${exe}, argümanlar: ${args.join(' · ')}`,
    env: "Ortam değişkenleri (isteğe bağlı)",
    envPlaceholder: 'MY_AGENT_TOKEN_FILE=~/.config/my-agent/token\nMY_AGENT_LOG=0',
    envHint: "Satır başına bir KEY=VALUE; yalnızca BaoCut başlattığında eklenir.",
    note: "Ekledikten sonra BaoCut başlayıp başlamadığını, oturum açma gereğini ve model listesini denetler. Algılandığında oturumlarda görünür.",
    cancel: "İptal",
    submit: "Ekle",
    exists: (id) => `${id} kimliğini zaten bir Ajan kullanıyor. Başka kimlik seçin.`,
  },

  added: {
    chip: "Siz eklediniz",
    detect: "Denetle",
    detecting: "Denetleniyor…",
    remove: "Kaldır",
    subFound: (version) => ['Algılandı',version ? `v${version}` : null,'ACP üzerinden bağlı'].filter(Boolean).join(' · '),
    subLauncher: (launcher,needs) => `Henüz denetlenmedi · ${launcher} başlatmada indirir; ${needs} gerekir`,
    subMissing: (command) => `Henüz denetlenmedi · ${command} bu bilgisayarda bulunamadı`,
    note: (name) => `${name}, ACP (Agent Client Protocol) üzerinden bağlanır. BaoCut doğrulamadı; yükleme ve kullanılacak hesap için kendi belgelerini izleyin.`,
    noInstall: "Ayrı yükleme gerekmez",
    noInstallBody: (launcher,spec,needs) => `BaoCut başlattığında ${launcher}, ${spec} paketini otomatik indirir. Bu bilgisayarda ${needs} gerekir.`,
    install: "Resmi talimatları izleyerek bu bilgisayara yükleyin",
    installBody: (command) => `Yüklendikten sonra ${command} komutu terminalde çalışmalıdır.`,
    docs: "Resmi talimatları aç",
    launch: "BaoCut bu komutla başlatır",
    launchCopy: "başlatma komutu",
    envNote: (keys) => `Başlatmada şu ortam değişkenleri eklenir: ${keys.join(', ')} (değerler burada gösterilmez).`,
    login: "Oturum açma gerekiyorsa kendi aracı üzerinden açın",
    loginBody: "Terminalde kendi talimatlarını izleyin. Oturum açma aracın kendi penceresinde olur; BaoCut hesabınızı veya parolanızı işlemez.",
    detectStep: "Denetle",
    detectBody: "BaoCut bağlantıyı doğrulamak, oturum açma gereğini görmek ve model listesini almak için bir kez başlatır.",
    launchRow: "Başlatma komutu",
    launchRowHint: "BaoCut bu komutla ACP (Agent Client Protocol) üzerinden başlatır.",
    versionPinned: (spec) => `Başlatma komutu ${spec} sürümünü sabitler. Sürüm değiştirmek için kaldırıp özel komutla yeniden ekleyin.`,
    versionOwn: "Yükseltmek için kendi talimatlarını izleyin, ardından burada yeniden denetleyin.",
    account: (name,signedOut) => `${signedOut ? 'Oturum açılmadı veya oturumun süresi doldu. ' : ''}Oturum açma ve ücretlendirme ${name} içinde gerçekleşir; BaoCut hesabınızı işlemez ve ek ücret almaz.`,
    removeTitle: (name) => `${name} kaldırılsın mı?`,
    removeBody: (name) => `${name}, etkinlik durumu ve varsayılan modeliyle BaoCut Ajan listesinden kaldırılır. Yeni oturumların varsayılanıysa başka kullanılabilir Ajan devralır. Onu kullanan görevler sona erer. Bilgisayarda yüklü program etkilenmez; sonra yeniden ekleyebilirsiniz.`,
    removed: (name) => `${name} kaldırıldı`,
    removeFailed: (message) => `Kaldırılamadı: ${message}`,
  },

  codexImage: {
    title: "Codex ile görsel oluştur",
    body: "Anahtar gerekmez; Codex aboneliğinizi kullanır. Her seferinde bir görsel oluşturur, boyut ve kaliteyi yok sayar, API üzerinden oluşturmaya göre 5–10 kat yavaştır. Açılınca hem bcut image hem oturumlardaki ajanlar seçebilir (“Codex” adıyla). Sizin yerinize seçilmez; varsayılan kullanmak için Modeller › Görsel oluşturma › Bulut modelleri bölümünde varsayılan yapın.",
    checking: "Bu bilgisayardaki Codex ile görsel oluşturulabildiği denetleniyor…",
    on: "Açık",
    period: '.',
    probeFailed: "Codex ile görsel oluşturulabildiği denetlenemedi · yeniden denemek için “Yeniden denetle” düğmesine tıklayın.",
    outdated: "Codex çok eski · Codex CLI yükseltin, ardından bunu açın",
    signedOut: "Codex henüz oturum açmadı · görsel oluşturma Codex hesabınızı kullanır; açmadan önce oturum açın.",
    notInstalled: "Codex bulunamadı · görsel oluşturmadan önce Codex CLI yükleyin ve oturum açın.",
    unavailable: (detail) => detail ? `Codex şu anda görsel oluşturamıyor · ${detail}` : 'Codex şu anda görsel oluşturamıyor · yeniden denemek için “Yeniden denetle” düğmesine tıklayın.',
    turnedOn: "Codex ile görsel oluştur açıldı · Codex artık görsel oluşturma model menüsünde",
    turnedOff: "Codex ile görsel oluştur kapatıldı",
    toggleFailed: (enabled,message) => `Codex ile görsel oluştur ${enabled ? 'açılamadı' : 'kapatılamadı'}: ${message}`,
  },

  faq: [
    {
      key: 'cost',
      title: "BaoCut için ek ödeme veya abonelik gerekir mi?",
      body: "Hayır. Ajan mevcut Claude veya ChatGPT aboneliğinizi kullanır; ücret ve kota orada hesaplanır. BaoCut model içermez, anahtar toplamaz veya bulut üzerinden aracı olmaz. Bu abonelikler yoksa Ajan kullanmadan BaoCut diğer özelliklerini kullanabilirsiniz.",
    },
    {
      key: 'account',
      title: "BaoCut hesabımı veya parolamı görür mü?",
      body: "Hayır. Oturum açma ajanın kendi penceresinde olur. BaoCut yalnızca bilgisayarınızdaki programı başlatıp videoyu işlemesi için verir. Videoyu değiştirmeden önce sorar; kurallar Ayarlar › Gizlilik ve izinler bölümündedir.",
    },
    {
      key: 'cloud',
      title: "Ajan ile “Bulut modelleri” arasındaki fark nedir?",
      body: "Ajan yerel kodlama asistanınızı ve kendi aboneliğinizi kullanır; çok adımlı görevleri art arda tamamlayabilir. “Bulut modelleri”, API anahtarıyla tek araç çalıştırır ve kullanıma göre ücretlendirilir. Ayrı ayarlanırlar.",
      link: 'models',
    },
    {
      key: 'terminal',
      title: "Terminalde bu ajanlaryle doğrudan BaoCut kullanmak mı istiyorsunuz?",
      body: "BaoCut içinde oturum açmak için ek hazırlık gerekmez. Terminalde veya başka uygulamalarda kullanmak için BaoCut Skill kurmanız gerekir; Ayarlar › Skills bölümüne bakın.",
      link: 'skills',
    },
  ],

  permissionsHeading: "Önce ne zaman soracağını siz seçersiniz",
  policyHeading: "Daha az tekrar eden onay istemi",
  policyHint: "Bu kurallar eşleşen eylemlere otomatik izin verir; erişim modu da soru sorulmasını etkiler.",
  policy: {
    read: { label: "Video içeriğini oku", desc: "Asistanın her seferinde sormadan dökümleri ve video ayarlarını görmesini sağlar." },
    bcutro: { label: "Videoları ve ilerlemeyi sorgula", desc: "Bilgi ve ilerlemeyi denetlemesini sağlar. Bu komutlar videoyu değiştirmez." },
    loop: { label: "Çalışan AI görevlerine yanıt ver", desc: "Görev almasını ve yanıt göndermesini sağlar; çok adımlı işlerde kesintileri azaltır." },
  } satisfies Record<keyof AgentPolicy, { label: string; desc: string }>,
  accessModes: "Erişim modları",
  firstDefault: "İlk varsayılan",
  alwaysAllowed: "Her zaman izin verilen komutlar",
  saveFailed: (message) => `Kaydedilemedi: ${message}`,
  ruleRemoved: (rule) => `${rule} kuralı kaldırıldı`,
  ruleRemoveFailed: (message) => `Kural kaldırılamadı: ${message}`,
  modeHint: (firstDefault,last) => `Her oturumun giriş kutusu altından erişim modunu seçin. İlk seferde varsayılan “${firstDefault}” olur; ardından yeni oturumlar son seçiminizi korur${last ? ` (şu anda “${last}”)` : ''}.`,

  advancedHeading: "Gelişmiş ve sorun giderme",
  advancedHint: "Bağlantı çalışıyorsa burada değişiklik gerekmez.",
  modelAutoUpdate: {
    label: "Model listelerini otomatik güncelle",
    desc: "Başlangıçta ve çalışırken etkin ajanların kendi model listelerini düzenli günceller. Kapalıyken her Ajan ayrıntısından elle yenileyebilirsiniz.",
  },
  executableHint:
    "BaoCut PATH ve yaygın yükleme konumlarına (Homebrew, npm genel klasörü, ~/.local/bin) bakar. Sürüm yöneticisiyle (nvm, asdf, mise) kurulanlar başka yerde olabilir; çalıştırılabilir dosyanın tam yolunu girin. Otomatik aramaya dönmek için boş bırakın.",
  techPanel: "Teknik bilgiler ve konumlar",
  techTitle: "Ajan teknik bilgileri",
  techSubtitle: "Sürümler, yollar ve kullanılabilir modeller",
  techEmpty: "Henüz denetim sonucu yok.",
  techNotInstalled: "· Yüklü değil",
  techNoModels: "Model listesi bildirilmedi",
  pathLabel: "yol",
  diagnosticsLabel: "tanılar",
  copyDiagnostics: "Tanıları kopyala",
  locateTitle: "Ajan konumunu elle ayarla",
  locateSubtitle: "Otomatik algılama bulamadığında",

  command: {
    copied: (label) => `${label} kopyalandı`,
    copyFailed: "Kopyalanamadı. Metni seçip kendiniz kopyalayın.",
    copy: (label) => `${label} kopyala`,
    stop: "Durdur",
    run: "Bu komutu çalıştır",
    output: "Komut çıktısı",
    running: "İşleniyor",
    runningText: "Çalışıyor…",
    done: "Tamamlandı",
    stopped: "Durduruldu. Çalışmış işlemler geri alınmaz; yeniden çalıştırabilirsiniz.",
    failed: (reason) => `Başarısız (${reason}). Yukarıdaki çıktı nedenini açıklar; parola gerekiyorsa terminalde çalıştırın.`,
    runInTerminal: "Terminalde çalıştır",
    exitCode: (code) => `çıkış kodu ${code}`,
    startFailed: (error) => `başlatılamadı: ${error}`,
    killed: "işlem sonlandırıldı",
    confirmInstall: (name) => `${name} için yükleme komutu çalıştırılsın mı?`,
    confirmUpgrade: (name) => `${name} için yükseltme komutu çalıştırılsın mı?`,
    confirmRun: "Çalıştır",
    cancel: "İptal",
    confirmBefore: "BaoCut aşağıdaki komutu bu bilgisayarda çalıştırır. Çıktısı komutun altında görünür; istediğiniz zaman durdurabilirsiniz.",
    confirmAfter: "Parola isteyen komutlar burada başarısız olur; terminalde çalıştırın.",
    restored: (name) => `${name} için otomatik aramaya dönüldü`,
    switched: (path) => `Artık ${path} kullanılıyor`,
    notFoundAt: (path,command) => `${path} konumunda çalıştırılabilir ${command} bulunamadı`,
    saveFailed: (message) => `Konum kaydedilemedi: ${message}`,
    locationLabel: (name) => `${name}: konum`,
    locationPlaceholder: (command) => `/tam/yol/${command}`,
    locationSaved: "Elle ayarlandı. Otomatik aramaya dönmek için temizleyip kaydedin.",
    locationAuto: "Boş = otomatik arama",
    save: "Kaydet",
    restoreAuto: "Otomatik aramayı kullan",
  },

  skills: {
    lede: "Skill, BaoCut içindeki ajanlarne belirli bir yöntemle iş yapmayı öğreten bir klasördür (SKILL.md ve isteğe bağlı referans dosyaları). Anahtar açıkken Ajan, görevle ilgili gördüğünde kendiliğinden kullanır; kapalıyken yalnızca giriş kutusundaki “+” üzerinden seçtiğinizde kullanılır. Skill açma, kapatma, ekleme ve kaldırma sonraki yeni Ajan oturumunda geçerli olur.",
    search: "Skill ara",
    filter: "Kaynağa göre filtrele",
    tab: (label: string, count: number) => `${label} ${count}`,
    tabLabel: (label,count) => `${label}, ${count}`,
    add: "Skill ekle",
    addFolder: "Yerel klasörden ekle",
    addGithub: "GitHub üzerinden içe aktar",
    loading: "Skill’ler yükleniyor…",
    loadFailed: (message) => `Skill’ler yüklenemedi: ${message}`,
    retry: "Yeniden dene",
    disconnected: "BaoCut Runtime bağlı değil. Bağlanınca Skill’ler listelenir.",
    emptyTitle: "Henüz Skill yok",
    emptyBody:
      "Henüz kullanılabilir Skill yok. Yazdığınız Skill klasörünü ekleyin veya GitHub üzerinde paylaşılanı içe aktarın. Üçüncü taraf Skill’ler içe aktarma sonrası kapalıdır; açmadan önce inceleyin.",
    emptyWeb: "Henüz kullanılabilir Skill yok. Tarayıcıda yalnızca görüntüleyip açıp kapatabilirsiniz; ekleme ve içe aktarma için BaoCut masaüstü uygulamasını kullanın.",
    noMatch: (query) => `“${query}” için Skill bulunamadı`,
    noMatchHint: "Başka sözcük deneyin veya “Tümü” sekmesine geçin.",
    noneInTab: (label) => `${label} kategorisinde henüz Skill yok`,
    webNote: "Tarayıcıda Skill’leri görüntüleyip açıp kapatabilirsiniz; ekleme, içe aktarma ve kaldırma için BaoCut masaüstü uygulamasını kullanın.",
    view: (name) => `${name} adlı Skill öğesini gör`,
    enable: (name) => `${name} adlı Skill öğesini etkinleştir`,
    toggledOn: (name) => `${name} adlı Skill açıldı: sonraki yeni oturumdan itibaren Ajan ilgili olduğunda kendiliğinden kullanır`,
    toggledOff: (name) => `${name} adlı Skill kapatıldı: artık yalnızca giriş kutusundaki “+” üzerinden seçtiğinizde kullanılır`,
    added: (name) => `${name} adlı Skill eklendi`,
    imported: (name) => `${name} adlı Skill içe aktarıldı; varsayılan kapalı`,
    removed: (name) => `${name} adlı Skill kaldırıldı`,
    diagnosticsTitle: (count) => `${count} klasör yüklenemedi`,
    diagnosticsHint: "Bu klasörler kullanılabilir Skill değil; atlandı. Düzeltip yeniden yüklemek için bu sayfaya dönün.",
    diagnosticCode: { invalid: "Geçersiz biçim", 'duplicate-id': "Yinelenen ad", 'builtin-conflict': "Yerleşik Skill ile aynı ad" },
    diagnosticLine: (dir: string, reason: string, issue: string) => `${dir} · ${reason}: ${issue}`,
    externalTitle: "BaoCut aracını terminaldeki veya diğer uygulamalardaki ajanlarnden kullanın",
    externalBody:
      "Yukarıdaki Skill’ler BaoCut içindeki ajanlar içindir. Terminaldeki Claude Code veya Codex aracına BaoCut ile yazıya dökme, çeviri, düzenleme ve dışa aktarma öğretmek için BaoCut Skill yükleyin. Bu ajanların genel konumlarına tek tıkla yükleme, yüklü yeri görme ve güncelleme gereğini denetleme sonraki sürümde gelecek.",
  },

  skillDetail: {
    close: "Kapat",
    stateOn: "Açık: Ajan ilgili olduğunda kendiliğinden kullanır.",
    stateOff: "Kapalı: yalnızca giriş kutusundaki “+” üzerinden seçtiğinizde kullanılır.",
    thirdPartyNote: "Üçüncü taraf Skill’ler başkalarının paylaştığı depolardan gelir; açmadan önce inceleyin. BaoCut Skill içindeki dosyaları çalıştırmaz; Skill, Ajan izinlerini genişletemez.",
    source: "Kaynak",
    location: "Konum",
    version: "Sürüm",
    noVersion: "Belirtilmedi",
    get reveal() {
      return revealLabel();
    },
    body: 'SKILL.md',
    emptyBody: "Üstteki ad ve açıklama dışında SKILL.md başka içerik taşımıyor.",
    files: (count) => `Dosyalar (${count})`,
    back: "Geri",
    notText: "Metin dosyası değil; burada gösterilmez",
    tooLarge: "Dosya çok büyük; burada gösterilmez",
    loading: "Yükleniyor…",
    loadFailed: (message) => `Yüklenemedi: ${message}`,
    remove: "Kaldır",
    removeBuiltin: "Yerleşik Skill kaldırılamaz, ancak kapatabilirsiniz.",
    removeTitle: (name) => `${name} adlı Skill kaldırılsın mı?`,
    removeBody: (path) => `${path} klasörü ve içindeki tüm dosyalar silinir; geri alınamaz. Çalışmakta olan oturumlar etkilenmez.`,
    cancel: "İptal",
  },

  skillGithub: {
    title: "GitHub üzerinden içe aktar",
    label: "Depo URL adresi",
    placeholder: 'owner/repo',
    description: "Tam URL de yapıştırabilirsiniz, ör. https://github.com/owner/repo/tree/main/skills/name",
    note: "Yalnızca bu URL adresinin gösterdiği klasördeki dosyaları indirir; hiçbirini çalıştırmaz. İçe aktarılan Skill’ler “Üçüncü taraf” sayılır ve varsayılan kapalıdır; yalnızca giriş kutusundaki “+” üzerinden seçildiğinde kullanılır. Açmaya karar vermeden önce içeriği inceleyin.",
    submit: "İçe aktar",
    pending: "GitHub üzerinden indiriliyor…",
    cancel: "İptal",
  },
};
