import type { AgentSetupMessages } from './agent-setup-copy.ts';
import { pluralForm } from '@baocut/protocol';

export const it: AgentSetupMessages = {
  badge: { 'not-installed': 'Non installato', error: 'Impossibile eseguire', outdated: 'Non aggiornato', 'signed-out': 'Accesso richiesto', disabled: 'Disattivato' }, badgeNotChecked: 'Non ancora verificato', badgeReady: 'Disponibile', badgeModelUpgrade: 'Disponibile · Modello predefinito da aggiornare', badgeModelUnavailable: 'Disponibile · Modello predefinito non disponibile', badgeUpdate: 'Disponibile · Aggiornamento disponibile', errorTitle: (name: string) => `${name} trovato, ma non può essere eseguito`, errorBody: (detail: string | null) => `${detail ? `${detail} ` : ''}Di solito accade dopo la disinstallazione o l’aggiornamento di Node.js o un cambiamento dei permessi dei file. Le verifiche possono individuare il passaggio non riuscito.`, errorCta: 'Esegui verifiche',
  outdatedTitle: (name: string, version: string | null) => version ? `La versione ${version} di ${name} è troppo vecchia per essere controllata da BaoCut` : `Questa versione di ${name} è troppo vecchia per essere controllata da BaoCut`, outdatedBody: (detail: string | null, minVersion: string) => `${detail ? `${detail} ` : `Richiede ${minVersion} o successiva. `}L’aggiornamento riguarda solo questo strumento da riga di comando; account e impostazioni rimangono invariati.`, outdatedCta: (version: string) => `Aggiorna a ${version}`, signedOutTitle: (name: string) => `${name} richiede di accedere di nuovo`, signedOutBody: (name: string) => `L’accesso avviene nella finestra di ${name}; BaoCut non gestisce mai account o password. Torna qui per verificare dopo l’accesso.`, signedOutCta: 'Apri un terminale per accedere',
  stepSkipped: 'Verificato dopo il superamento del passaggio precedente', stepFind: 'Trovato su questo computer', stepFindFail: (command: string) => `${command} non è nelle posizioni di installazione usuali né su PATH`, stepRun: 'Si avvia', stepRunOk: (command: string, version: string) => `${command} --version ha restituito ${version}`, stepRunFail: 'Avvio non riuscito', stepVersion: 'Versione supportata da BaoCut', stepVersionOk: (version: string, min: string) => `${version}, minimo ${min}`, stepVersionFail: (version: string, min: string) => `Attuale ${version}, minimo ${min}`, stepLogin: 'Accesso al tuo account effettuato', stepLoginOk: 'Accesso effettuato', stepLoginFail: 'Segnala che l’accesso non è effettuato o è scaduto', stepModels: 'Elenco dei modelli disponibile', stepModelsOk: (n: number) => pluralForm('it', n, { one: `${n} modello`, other: `${n} modelli` }), stepModelsNone: 'Non ha riportato un elenco dei modelli; le sessioni usano il modello predefinito dell’agente', verdictFail: (label: string, detail: string) => `Bloccato a «${label}»: ${detail}`, verdictOk: 'Tutte le cinque verifiche superate. Puoi avviare una sessione.', moreSummary: (names: string[], more: boolean) => names.join(', ') + (more ? ' e altri' : ''),
  readyTitle: 'Pronto', readyBody: (name: string, model: string, plan: string) => `Le nuove sessioni usano ${name} · ${model}. Esegue con ${name} già installato su questo computer e il tuo ${plan}; BaoCut non applica addebiti aggiuntivi.`, readyCta: 'Avvia sessione', attentionBody: (name: string) => `È già installato su questo computer, quindi non serve reinstallarlo. La causa e il rimedio sono nella riga «${name}» sotto.`, attentionCta: 'Visualizza problema', offTitle: (name: string) => `L’agente ${name} è installato ma disattivato`, offBody: 'Attivalo per passare il lavoro da BaoCut con una sola frase.', offCta: (name: string) => `Attiva ${name}`, missingTitle: 'Nessun agente ancora rilevato su questo computer', missingBodyMany: 'Installa uno qualsiasi dei seguenti e accedi con un account che hai già. Non servono tutti.', missingBodyOne: 'Installalo seguendo i passaggi sotto e accedi con un account che hai già.',
  logDropped: (n: number) => pluralForm('it', n, { one: `… (${n} riga precedente omessa)`, other: `… (${n} righe precedenti omesse)` }), doneNotDetected: (name: string) => `Il comando è terminato, ma ${name} non viene ancora rilevato. Se è installato altrove, puoi impostarne manualmente la posizione.`, doneSignIn: (name: string, version: string) => `Rilevato ${name} ${version} · Accedi una volta per completare`, doneInstalled: (name: string, version: string) => `Rilevato ${name} ${version}`, doneUpgraded: (name: string, version: string) => `${name} è ora ${version} · Aggiornamento dell’elenco dei modelli`,
  tier: { balanced: { label: 'Consigliato', description: 'Sufficiente per trascrivere, tradurre e modificare; veloce e usa meno quota dell’abbonamento' }, max: { label: 'Più capace', description: 'Più lento e usa più quota dell’abbonamento; raramente necessario' }, fast: { label: 'Più veloce', description: 'Ideale per piccole modifiche come cambiare qualche sottotitolo' } }, agentDefaultModel: 'Modello predefinito dell’agente', cliConfigGate: (model: string) => `Segue le impostazioni CLI · ${model} richiede un aggiornamento della CLI`, cliConfigModel: (model: string) => `Segue le impostazioni CLI · ${model}`, cliConfig: 'Segue le impostazioni CLI', modelMissing: 'Non nell’elenco dei modelli attuale; le nuove sessioni usano il modello consigliato', effort: { minimal: 'Minimo', low: 'Basso', medium: 'Medio', high: 'Alto', xhigh: 'Molto alto', max: 'Massimo' }, modelDefaultEffort: 'Predefinito del modello', modelDefaultEffortOf: (label: string) => `Predefinito del modello (${label})`,
  rulesTitle: (n: number) => `Comandi sempre consentiti · ${n}`, rulesBody: 'Queste regole derivano dalla scelta «Consenti sempre» nelle sessioni. Dopo la rimozione, una regola non approva più automaticamente le azioni; modalità di accesso e altre regole continuano a valere.', rulesEmpty: 'Nessuna regola ancora salvata. Scegli «Consenti sempre» su una scheda di approvazione nella sessione e comparirà qui.',
};
