import { createElement, Fragment, type ReactNode } from 'react';
import type { AgentCardMessages } from './agent-card-copy.ts';

export const pl: AgentCardMessages = {
  runFailed: (message: string) => `Nie udało się uruchomić: ${message}`,
  stopFailed: (message: string) => `Nie udało się zatrzymać: ${message}`,
  loginCommand: "polecenie logowania",
  installCommand: "polecenie instalacji",
  upgradeCommand: "polecenie aktualizacji",
  linkLabel: "link",
  terminalLogin: (command: string) => `Uruchamianie ${command} w terminalu · Wróć po zalogowaniu`,
  terminalRun: (command: string) => `Uruchamianie ${command} w terminalu · Wróć po ukończeniu`,
  terminalCopied: (label: string) => `Nie udało się otworzyć terminalu. Skopiowano ${label}; wklej w terminalu, aby uruchomić.`,
  terminalManual: (command: string) => `Nie udało się otworzyć terminalu. Uruchom ${command} w terminalu.`,
  terminalFailed: (message: string) => `Nie udało się otworzyć terminalu: ${message}`,
  enableFailed: (message: string) => `Nie udało się włączyć: ${message}`,
  disableFailed: (message: string) => `Nie udało się wyłączyć: ${message}`,
  recheckFailed: (message: string) => `Nie udało się sprawdzić ponownie: ${message}`,
  saveModelFailed: (message: string) => `Nie udało się zapisać modelu domyślnego: ${message}`,
  saveEffortFailed: (message: string) => `Nie udało się zapisać domyślnej intensywności: ${message}`,
  refreshFailed: (message: string) => `Nie udało się odświeżyć modeli: ${message}`,
  setDefaultFailed: (message: string) => `Nie udało się ustawić domyślnego: ${message}`,
  openFailed: (message: string) => `Nie udało się otworzyć: ${message}`,
  enabled: (name: string) => `Włączono: ${name}`,
  disabled: (name: string) => `Wyłączono: ${name} · Nowe sesje już nie pokazują`,

  defaultBadge: "Domyślny",
  subInstalled: (version: string | null, account: string | null) => ["Zainstalowana na tym komputerze", version ? `v${version}` : null, account].filter(Boolean).join(" · "),
  subMissing: (command: string, plan: string) => `${command} niewykryty na komputerze · Wystarczy posiadany ${plan}`,
  enable: (name: string) => `Włącz ${name}`,
  details: "Szczegóły",
  install: "Zainstaluj",
  checking: "Sprawdzanie…",
  gateTitle: (name: string, model: string) => `${name} – skonfigurowany model domyślny ${model} wymaga nowszej wersji`,
  gateBody: (version: string, model: string) => `Na komputerze jest ${version}, lista modeli tej wersji nie zawiera ${model}. Sesje z „Domyślny model agenta” używają ustawienia i są odrzucane przy wysyłaniu; konkretne modele bez zmian.`,
  gateUpgrade: "Aktualizowane jest tylko narzędzie CLI; konto i jego ustawienia bez zmian.",
  gateNoUpgrade: "Nie ma jeszcze nowszej wersji. Na razie wybierz model z listy sesji.",
  upgradeTo: (version: string) => `Zaktualizuj do ${version}`,
  updateStrip: (latest: string, current: string) => `Wersja ${latest} dostępny (obecny: ${current}). Możesz używać bez aktualizacji.`,
  viewUpgrade: "Zobacz sposób aktualizacji",
  cancel: "Anuluj",

  defaultModel: "Domyślny model",
  defaultModelDesc: "Nowe sesje zaczynają z nim; można zmienić pod polem wpisywania. Poziom „Zalecany” wystarczy do transkrypcji, tłumaczenia i edycji; najmocniejszy model niepotrzebny.",
  defaultModelOf: (name: string) => `${name} – model domyślny`,
  defaultEffortOf: (name: string) => `${name} – domyślna intensywność rozumowania`,
  modelsOf: (name: string, count: number) => `${name} modeli · ${count}`,
  modelsList: (list: string) => `${list}. Odświeżane przy każdej kontroli.`,
  modelsNone: "Brak listy modeli, sesje używają domyślnego modelu agenta. Ponowny odczyt przy następnej kontroli.",
  refreshing: "Odświeżanie…",
  refreshModels: "Odśwież modele",
  refreshed: (name: string) => `Odświeżono listę modeli ${name}`,
  nowDefault: (name: string) => `Nowe sesje używają teraz ${name}`,
  version: (version: string | null) => (version ? `Wersja · v${version}` : "Wersja"),
  versionDesc: (latest: string | null, min: string | null, source: string) => `${latest ? `Możesz zaktualizować do ${latest}. ` : ""}${min ? `BaoCut wymaga co najmniej ${min}. ` : ""}Aktualizowane tylko narzędzie CLI; konto i ustawienia bez zmian. ${source}`,
  account: "Konto",
  accountDesc: (signedOut: boolean, account: string | null, plan: string) => `${signedOut ? "Niezalogowany lub logowanie wygasło" : (account ?? 'Signed in')}. Używa własnej subskrypcji ${plan}; BaoCut nie pobiera dodatkowych opłat. Logowanie w terminalu.`,
  loginInTerminal: "Otwórz terminal do logowania",
  switchAccount: "Zmień konto…",
  location: "Lokalizacja instalacji",
  locationDesc: "BaoCut wywołuje program na komputerze bezpośrednio, nie instaluje innej kopii.",
  realLocation: "Rzeczywista lokalizacja",
  setLocation: "Ustaw lokalizację ręcznie",
  troubleshoot: "Diagnostyka",
  troubleshootDesc: "Sprawdza kolejno instalację, wersję, logowanie i listę modeli, wskazuje problem.",
  setDefault: "Ustaw domyślny",
  runChecks: "Uruchom kontrole",

  sourceKnown: (label: string) => `Ta kopia zainstalowana przez „${label}”, aktualizuj tą samą metodą. Inne metody zainstalują inną kopię, nie tę.`,
  sourceUnknown: "Aktualizuj metodą instalacji.",
  scriptInstall: "Polecenie pobiera i uruchamia skrypt oficjalnej strony. BaoCut nie wykonuje skryptów internetowych za Ciebie: skopiuj i uruchom w terminalu.",
  scriptUpgrade: "Polecenie pobiera i uruchamia skrypt oficjalnej strony. Skopiuj i uruchom w terminalu.",
  copyUpgrade: "Skopiuj polecenie, uruchom w terminalu, wróć i sprawdź ponownie.",
  runnableHint: "Kliknij ▶ po lewej, aby uruchomić tutaj; wynik poniżej. Lub skopiuj i uruchom w terminalu.",
  copyHint: "Skopiuj polecenie poniżej i uruchom w terminalu.",
  installMethod: "Metoda instalacji",
  upgradeMethod: "Metoda aktualizacji",
  needs: (needs: string) => `Wymaga ${needs} na tym komputerze.`,

  installIntro: (name: string, plan: string) => `${name} – asystent AI w CLI na komputerze z logowaniem subskrypcją ${plan}, którą już masz. BaoCut tylko wywołuje: bez dopłat i klucza API w BaoCut.`,
  stepInstall: "Zainstaluj na tym komputerze",
  stepInstallOfficial: "Zainstaluj na komputerze według oficjalnych instrukcji",
  installOfficialBody: (command: ReactNode) => createElement(Fragment, null, "Zainstaluj według oficjalnych instrukcji. Po instalacji ", command, " powinien działać w terminalu."),
  stepLogin: "Zaloguj na konto",
  stepLoginBody: "Po instalacji uruchom polecenie poniżej w terminalu i zaloguj w przeglądarce. Logowanie we własnym oknie; BaoCut nie obsługuje konta ani hasła.",
  stepBack: "Wróć tutaj",
  stepBackBody: "Gotowe po wykryciu instalacji i logowania.",
  detecting: "Sprawdzanie…",
  recheck: "Zainstalowano, sprawdź ponownie",
  notDetected: "Zainstalowane, ale niewykryte?",
  notDetectedBody:
    "BaoCut szuka w PATH i zwykłych lokalizacjach (Homebrew, globalny folder npm, ~/.local/bin). Menedżery wersji (nvm, asdf, mise) czasem instalują gdzie indziej; wskaż ręcznie.",
  diagnosisOf: (name: string) => `Wyniki kontroli ${name}`,
};
