import type { FontSettingsMessages } from './font-settings-copy.ts';
import { intlLocale, pluralForm } from '@baocut/protocol';

export const fr: FontSettingsMessages = {
  lead: (total) => `Les polices proviennent de trois sources : celles fournies avec l’application, celles installées sur cet ordinateur et le répertoire Google Fonts (${total === null ? 'environ deux mille' : `environ ${total.toLocaleString(intlLocale())}`} familles, licences open source, téléchargement à la demande). Les téléchargements envoient uniquement le nom de famille et la graisse et ne nécessitent aucun compte ; les polices sont stockées dans les données de l’application, pas dans le dossier de la vidéo.`,
  download: 'Télécharger', autoDownload: 'Télécharger les polices automatiquement', autoDownloadDesc: 'Télécharge depuis Google Fonts lorsque l’aperçu, l’ouverture d’une vidéo ou l’export nécessite une police absente de cet ordinateur. Si désactivé, les polices de remplacement sont d’abord utilisées pour l’affichage et l’export ; vous pouvez toujours télécharger manuellement lors du choix d’une police. Aucun téléchargement en mode hors ligne strict.',
  cssEndpoint: 'URL de la feuille de style', cssEndpointDesc: 'URL de base d’un miroir. Laissez vide pour utiliser https://fonts.googleapis.com.', fileEndpoint: 'URL du fichier de police', fileEndpointDesc: 'Les fichiers de polices sont uniquement récupérés sous cette URL. Laissez vide pour utiliser https://fonts.gstatic.com.',
  downloaded: 'Polices téléchargées', summary: (families, size) => `${families} ${pluralForm('fr', families, { one: 'famille', other: 'familles' })} · ${size}`, none: 'Aucune', clearAll: 'Tout effacer', empty: 'Les polices téléchargées lors du choix d’une police, ou automatiquement à l’ouverture d’une vidéo ou à l’export, sont listées ici.',
  clearTitle: 'Effacer les polices téléchargées ?', clear: 'Effacer', cancel: 'Annuler', removed: (family, size) => `« ${family} » supprimée · ${size} libérés`, inUseTip: 'Un export non terminé l’utilise ; supprimez-la après la fin de l’export', removeTip: 'Supprimer les fichiers téléchargés de cette police', removeLabel: (tip, family) => `${tip} : ${family}`, facts: (weights, size, licence, ago) => `Graisses ${weights} · ${size} · ${licence}${ago ? ` · Téléchargé ${ago}` : ''}`, inUse: 'Utilisée par un export',
};
