import { pluralForm } from '@baocut/protocol';
import { createElement, Fragment, type ReactNode } from 'react';
import type { GlossaryMessages } from './glossary-copy.ts';

export const ru: GlossaryMessages = {
  list: {
    importFilter: "Глоссарий (Markdown)",
    otherLibrary: { voices: "Мои голоса", brand: "Бренд-кит" },
    userLibrary: "пользовательская библиотека",
    createAction: "создать глоссарий",
    importTitle: "Импортировать глоссарий",
    importButton: "Импортировать",
    imported: (name: string, count: number) => `Импортировано «${name}» · ${count} ${pluralForm('ru', count, { one: "запись", few: "записи", many: "записей", other: "записи" })}`,
    notGlossary: (library: string) => `Файл не является глоссарием; сохранён в ${library}`,
    importAction: "импортировать",
    lede: "Речевые модели плохо слышат имена, названия продуктов и профессиональные термины, а перевод может отличаться от принятого в вашей области. Запишите здесь один раз для всех видео. Расшифровка и перевод используют отдельные глоссарии.",
    loadingLabel: "Загрузка глоссариев",
    loading: "Загрузка глоссариев…",
    transcriptionHint: "Правильное написание и частые ошибки распознавания. Передаётся речевым моделям с подсказками при расшифровке, исправляет каждое вхождение при редактировании расшифровки.",
    transcriptionEmpty: "Глоссариев расшифровки ещё нет.",
    newTranscription: "Новый глоссарий расшифровки",
    translationHint: "Источник → перевод, отдельный глоссарий на направление языков. При переводе модели передаются только используемые в материале записи.",
    translationEmpty: "Глоссариев перевода ещё нет.",
    newTranslation: "Новый глоссарий перевода",
    importFile: "Импортировать из файла…",
    importUnavailable: "Здесь нельзя выбрать файлы; импортируйте в настольном приложении.",
    foot: "Глоссарии видео выбираются в его настройках расшифровки, редактирования или перевода. Библиотека ваша; включение задаётся для каждого видео. Экспорт — таблица Markdown для передачи, редактирования и повторного импорта.",
    translationTitle: "Глоссарии перевода",
    transcriptionTitle: "Глоссарии расшифровки",
    defaultOnAction: "использовать по умолчанию в новых видео",
    defaultOffAction: "не использовать по умолчанию в новых видео",
    stats: (count: number, ago: string) => `${count} ${pluralForm('ru', count, { one: "запись", few: "записи", many: "записей", other: "записи" })} · Обновлено ${ago}`,
    defaultForNew: "По умолчанию для новых видео",
    open: (name: string) => `Открыть «${name}»`,
    from: "От",
    to: "на",
    sourceLanguage: "Исходный язык",
    targetLanguage: "Целевой язык",
    sameLanguage: "Исходный и целевой языки должны различаться",
    create: "Создать",
    cancel: "Отмена",
  },
  detail: {
    exportExists: "Файл с таким именем уже есть. BaoCut не перезаписывает файлы; выберите другое имя и экспортируйте снова.",
    loadFailed: "Не удалось прочитать глоссарий",
    loadingLabel: "Загрузка",
    loading: "Загрузка…",
    addAction: "добавить",
    saveTermAction: "сохранить запись",
    termGone: "Запись только что удалена в другом месте, не сохранена.",
    deleteTermAction: "удалить запись",
    termDeleted: "Запись удалена",
    exportTitle: "Экспортировать глоссарий",
    exportButton: "Экспорт",
    exported: (path: string) => `Экспортировано в ${path}`,
    exportAction: "экспортировать",
    reversed: (name: string, count: number) => `Создано «${name}» · ${count} ${pluralForm('ru', count, { one: "запись", few: "записи", many: "записей", other: "записи" })}. Удалите записи, не подходящие для обратного направления.`,
    reverseAction: "создать обратный глоссарий",
    deleted: "Глоссарий удалён",
    deleteAction: "удалить глоссарий",
    renameAction: "переименовать",
    sourceLanguage: "Исходный язык",
    targetLanguage: "Целевой язык",
    sameLanguage: "Исходный и целевой языки должны различаться",
    sourceAction: "сменить исходный язык",
    targetAction: "сменить целевой язык",
    spokenLanguage: "Разговорный язык",
    spokenAction: "сменить язык речи",
    saving: "Сохранение",
    stats: (count: number, ago: string) => `${count} ${pluralForm('ru', count, { one: "запись", few: "записи", many: "записей", other: "записи" })} · Обновлено ${ago}`,
    exportTable: "Экспортировать глоссарий",
    reverse: (from: string, to: string) => `Создать: ${from} → ${to} — глоссарий`,
    deleteTable: "Удалить глоссарий",
    exportUnavailable: "Здесь нельзя выбрать место сохранения; экспортируйте в настольном приложении.",
    deleteTitle: (name: string) => `Удалить «${name}»?`,
    delete: "Удалить",
    cancel: "Отмена",
    deleteBody: "Глоссарий удалится из библиотеки и не будет использоваться в будущих расшифровках и переводах. Готовые не изменятся.",
    back: "Все глоссарии",
    name: "Имя глоссария",
  },
  terms: {
    sourcePlaceholder: "Источник, например commit",
    canonicalPlaceholder: "Правильное написание, например KV cache",
    targetPlaceholder: "Перевод, например confirmación",
    misheardPlaceholder: "Ошибки распознавания (по желанию), например KB cache, cave cache",
    add: "Добавить",
    problems: (list: readonly string[]) => list.join("; "),
    bulkOpen: "Вставить список…",
    bulkLabel: "Вставить список",
    translationSample: "commit = confirmación\nWyckoff = Wyckoff\nspring = resorte = не «manantial»",
    transcriptionSample: "KV cache = KB cache, cave cache\nLoRA = Laura\ninference framework",
    bulkHow: (translation: boolean, eq: ReactNode, arrow: ReactNode) => createElement(
        Fragment,
        null,
        `Одна запись на строку. Разделяйте ${translation ? "источник и перевод" : "правильное написание и варианты ошибок"} через `,
        eq,
        ", ",
        arrow,
        ` или Tab${translation ? "; третий столбец — необязательное примечание" : "; можно только правильное написание"}. Вставьте два столбца из таблицы или экспортированную таблицу Markdown без изменений.`,
      ),
    moreSkipped: (count: number) => `${count} ещё ${pluralForm('ru', count, { one: "строка", few: "строки", many: "строк", other: "строки" })}`,
    addBatch: (count: number) => (count ? `Добавить в глоссарий · ${count} ${pluralForm('ru', count, { one: "запись", few: "записи", many: "записей", other: "записи" })}` : "Добавить в глоссарий"),
    cancel: "Отмена",
    search: "Поиск записей",
    searchTranslation: "Поиск источника, перевода, примечаний",
    searchTranscription: "Поиск правильных и ошибочных написаний",
    noMatch: (query: string) => `Нет записей по запросу «${query}».`,
    emptyTranslation: "Записей ещё нет. Введите источник и перевод выше и нажмите Enter.",
    emptyTranscription: "Записей ещё нет. Введите правильное написание выше и нажмите Enter.",
    moreHidden: (count: number) => pluralForm('ru', count, { one: `Ещё ${count} запись не показана; уточните поиск выше.`, few: `Ещё ${count} записи не показаны; уточните поиск выше.`, many: `Ещё ${count} записей не показаны; уточните поиск выше.`, other: `Ещё ${count} записи не показано; уточните поиск выше.` }),
    misheardAs: (list: readonly string[]) => `Распознаётся как ${list.join(" · ")}`,
    editLabel: (main: string) => `Редактировать «${main}»`,
    edit: "Изменить",
    misheardHint: "По желанию; варианты через запятую",
    misheardTip: "Указывайте только реальные ошибки распознавания. Выдуманные варианты испортят правильные предложения.",
    note: "Примечание",
    notePlaceholder: "Предложение для модели, например в этой школе это не означает «отправить»",
    flexible: "По контексту",
    flexibleHint: "В глоссариях этого ещё нет: модель использует записи без изменений. Для зависимости от контекста укажите в примечании.",
    more: "Ещё · Примечание, по контексту",
    save: "Сохранить",
    deleteEntry: "Удалить запись",
  },
};
