import { createElement, Fragment, type ReactNode } from 'react';
import type { GlossaryMessages } from './glossary-copy.ts';

export const zhHant: GlossaryMessages = {
  list: {
    importFilter: '術語表（Markdown）',
    otherLibrary: { voices: '我的音色', brand: '品牌庫' },
    userLibrary: '使用者資料庫',
    createAction: '建立術語表',
    importTitle: '匯入術語表',
    importButton: '匯入',
    imported: (name: string, count: number) => `已匯入「${name}」 · ${count} 個詞條`,
    notGlossary: (library: string) => `這個檔案不是術語表，已存入${library}`,
    importAction: '匯入',
    lede: '專業內容中的人名、產品名稱和行話，語音模型很難聽準，翻譯時也不會照你這一行的慣例譯。在這裡記錄一次，之後每部影片都會使用。轉錄和翻譯各自使用自己的術語表。',
    loadingLabel: '正在載入術語表',
    loading: '正在載入術語表…',
    transcriptionHint:
      '正確寫法，以及它常被誤聽為什麼。轉錄時會交給接受提示詞的語音模型，潤飾逐字稿時也會用它逐處修正。',
    transcriptionEmpty: '還沒有轉錄術語表。',
    newTranscription: '新增轉錄術語表',
    translationHint: '原文 → 譯文，每個語言方向一張表。翻譯時只會把這份內容用得到的詞條交給模型。',
    translationEmpty: '還沒有翻譯術語表。',
    newTranslation: '新增翻譯術語表',
    importFile: '從檔案匯入…',
    importUnavailable: '這個環境無法選擇檔案；請在桌面應用程式中匯入。',
    foot: '每部影片要用哪些術語表，在該影片的轉錄、潤飾或翻譯設定中選擇。資料庫是你的；要不要啟用由每部影片自己決定。匯出的檔案是一張 Markdown 表格，可以直接傳給別人，也可以用文字編輯器修改後再匯入。',
    translationTitle: '翻譯術語表',
    transcriptionTitle: '轉錄術語表',
    defaultOnAction: '設為新影片預設使用',
    defaultOffAction: '取消新影片預設使用',
    stats: (count: number, ago: string) => `${count} 個詞條 · ${ago}更新`,
    defaultForNew: '新影片預設使用',
    open: (name: string) => `開啟「${name}」`,
    from: '從',
    to: '譯成',
    sourceLanguage: '原文語言',
    targetLanguage: '譯文語言',
    sameLanguage: '原文和譯文不能是同一種語言',
    create: '建立',
    cancel: '取消',
  },
  detail: {
    exportExists: '該位置已有同名檔案。BaoCut 不會覆寫現有檔案；請換個名稱再匯出。',
    loadFailed: '無法讀取這張術語表',
    loadingLabel: '正在載入',
    loading: '正在載入…',
    addAction: '新增',
    saveTermAction: '儲存這個詞條',
    termGone: '這個詞條剛在其他地方被刪除，所以沒有儲存。',
    deleteTermAction: '刪除這個詞條',
    termDeleted: '已刪除這個詞條',
    exportTitle: '匯出術語表',
    exportButton: '匯出',
    exported: (path: string) => `已匯出到 ${path}`,
    exportAction: '匯出',
    reversed: (name: string, count: number) => `已建立「${name}」 · ${count} 個詞條。反過來不適用的詞條請自行刪除。`,
    reverseAction: '建立反向術語表',
    deleted: '已刪除這張術語表',
    deleteAction: '刪除這張術語表',
    renameAction: '重新命名',
    sourceLanguage: '原文語言',
    targetLanguage: '譯文語言',
    sameLanguage: '原文和譯文不能是同一種語言',
    sourceAction: '更改原文語言',
    targetAction: '更改譯文語言',
    spokenLanguage: '口說語言',
    spokenAction: '更改口說語言',
    saving: '正在儲存',
    stats: (count: number, ago: string) => `${count} 個詞條 · ${ago}更新`,
    exportTable: '匯出這張術語表',
    reverse: (from: string, to: string) => `建立 ${from} → ${to} 的術語表`,
    deleteTable: '刪除這張術語表',
    exportUnavailable: '這個環境無法選擇儲存位置；請在桌面應用程式中匯出。',
    deleteTitle: (name: string) => `要刪除「${name}」嗎？`,
    delete: '刪除',
    cancel: '取消',
    deleteBody: '這張術語表會從資料庫中刪除，之後的轉錄和翻譯不會再使用它。已完成的轉錄和翻譯不受影響。',
    back: '所有術語表',
    name: '術語表名稱',
  },
  terms: {
    sourcePlaceholder: '原文，例如 commit',
    canonicalPlaceholder: '正確寫法，例如 KV cache',
    targetPlaceholder: '譯文，例如 突破確認',
    misheardPlaceholder: '常被誤聽為（選填），例如 開維快取、KV 快去',
    add: '新增',
    problems: (list: readonly string[]) => list.join('；'),
    bulkOpen: '批次貼上…',
    bulkLabel: '批次貼上',
    translationSample: 'commit = 突破確認\nWyckoff = 威科夫\nspring = 彈簧效應 = 不要譯成「泉水」',
    transcriptionSample: 'KV cache = 開維快取、KV 快去\nLoRA = 蘿拉\n推理框架',
    bulkHow: (translation: boolean, eq: ReactNode, arrow: ReactNode): ReactNode =>
      createElement(
        Fragment,
        null,
        `每行一個詞條。${translation ? '原文和譯文' : '正確寫法和誤聽寫法'}之間用 `,
        eq,
        '、',
        arrow,
        ` 或 Tab 分隔${translation ? '；第三欄是選填的備註' : '；只寫正確寫法也可以'}。從試算表複製的兩欄內容，或匯出的 Markdown 表格，都可以直接貼上。`,
      ),
    moreSkipped: (count: number) => `還有 ${count} 行`,
    addBatch: (count: number) => (count ? `加入這張術語表 · ${count} 個詞條` : '加入這張術語表'),
    cancel: '取消',
    search: '搜尋詞條',
    searchTranslation: '搜尋原文、譯文、備註',
    searchTranscription: '搜尋正確寫法與誤聽寫法',
    noMatch: (query: string) => `沒有符合「${query}」的詞條。`,
    emptyTranslation: '還沒有詞條。在上方填入原文和譯文，按 Enter 即可新增。',
    emptyTranscription: '還沒有詞條。在上方填入正確寫法，按 Enter 即可新增。',
    moreHidden: (count: number) => `還有 ${count} 個詞條沒有列出；請用上方的搜尋縮小範圍。`,
    misheardAs: (list: readonly string[]) => `常被誤聽為 ${list.join(' · ')}`,
    editLabel: (main: string) => `編輯「${main}」`,
    edit: '編輯',
    misheardHint: '選填；多個寫法用頓號分隔',
    misheardTip: '只填寫真的被誤聽過的寫法。自己編造的變體會把原本正確的句子改壞。',
    note: '備註',
    notePlaceholder: '給模型看的一句話，例如：在這個學派中不是「提交」的意思',
    flexible: '可變通',
    flexibleHint: '術語表目前還沒有這個選項：翻譯模型會照用每個詞條。如果可以依語境變換，請寫在備註中。',
    more: '更多 · 備註、可變通',
    save: '儲存',
    deleteEntry: '刪除這個詞條',
  },
};
