import { pluralForm } from '@baocut/protocol';
import { createElement, Fragment, type ReactNode } from 'react';
import type { GlossaryMessages } from './glossary-copy.ts';

export const de: GlossaryMessages = {
  list: {
    importFilter: "Glossar (Markdown)",

    otherLibrary: { voices: "Meine Stimmen", brand: "Marken-Kit" } as Record<string, string>,
    userLibrary: "die Benutzerbibliothek",
    createAction: "Glossar erstellen",
    importTitle: "Glossar importieren",
    importButton: "Importieren",
    imported: (name: string, count: number) => `Importiert: „${name}“ · ${count} ${pluralForm('de', count, { one: "Eintrag", other: "Einträge" })}`,
    notGlossary: (library: string) => `Diese Datei ist kein Glossar; gespeichert unter ${library}`,
    importAction: "importieren",
    lede: "Namen, Produktnamen und Fachbegriffe sind für Sprachmodelle schwer zu erkennen und werden nicht fachgerecht übersetzt. Hier einmal erfassen; anschließend für jedes Video verwendbar. Transkription und Übersetzung haben eigene Glossare.",
    loadingLabel: "Glossare werden geladen",
    loading: "Glossare werden geladen…",
    transcriptionHint:
      "Richtige Schreibweise und häufige Fehlerkennung. Bei Transkription an Sprachmodelle mit Prompt-Unterstützung übergeben; bei Transkriptüberarbeitung wird jedes Vorkommen korrigiert.",
    transcriptionEmpty: "Noch keine Transkriptionsglossare.",
    newTranscription: "Neues Transkriptionsglossar",
    translationHint: "Quelle → Übersetzung; ein Glossar je Sprachrichtung. Beim Übersetzen werden nur die in diesem Text verwendeten Einträge an das Modell übergeben.",
    translationEmpty: "Noch keine Übersetzungsglossare.",
    newTranslation: "Neues Übersetzungsglossar",
    importFile: "Aus Datei importieren…",
    importUnavailable: "In dieser Umgebung sind keine Dateien auswählbar; in der Desktop-App importieren.",
    foot: "Die Glossarauswahl erfolgt in den Transkriptions-, Überarbeitungs- oder Übersetzungseinstellungen jedes Videos. Die Bibliothek gehört Ihnen; Aktivierung entscheidet jedes Video selbst. Export erzeugt eine Markdown-Tabelle zum Weitergeben oder zum Bearbeiten und erneuten Importieren.",
    translationTitle: "Übersetzungsglossare",
    transcriptionTitle: "Transkriptionsglossare",
    defaultOnAction: "standardmäßig für neue Videos verwenden",
    defaultOffAction: "nicht mehr standardmäßig für neue Videos verwenden",
    stats: (count: number, ago: string) => `${count} ${pluralForm('de', count, { one: "Eintrag", other: "Einträge" })} · Aktualisiert ${ago}`,
    defaultForNew: "Standard für neue Videos",
    open: (name: string) => `Öffnen: „${name}“`,
    from: "Von",
    to: "nach",
    sourceLanguage: "Quellsprache",
    targetLanguage: "Zielsprache",
    sameLanguage: "Quell- und Zielsprache dürfen nicht identisch sein",
    create: "Erstellen",
    cancel: "Abbrechen",
  },
  detail: {
    exportExists: "Eine Datei mit diesem Namen ist bereits vorhanden. BaoCut überschreibt keine Dateien; anderen Namen wählen und erneut exportieren.",
    loadFailed: "Dieses Glossar konnte nicht gelesen werden",
    loadingLabel: "Wird geladen",
    loading: "Wird geladen…",
    addAction: "hinzufügen",
    saveTermAction: "diesen Eintrag speichern",
    termGone: "Dieser Eintrag wurde gerade anderswo gelöscht; er wurde nicht gespeichert.",
    deleteTermAction: "diesen Eintrag löschen",
    termDeleted: "Diesen Eintrag gelöscht",
    exportTitle: "Glossar exportieren",
    exportButton: "Exportieren",
    exported: (path: string) => `Exportiert nach ${path}`,
    exportAction: "Export",
    reversed: (name: string, count: number) =>
      `Erstellt: „${name}“ · ${count} ${pluralForm('de', count, { one: "Eintrag", other: "Einträge" })}. Einträge ohne umgekehrte Gültigkeit löschen.`,
    reverseAction: "umgekehrtes Glossar erstellen",
    deleted: "Dieses Glossar gelöscht",
    deleteAction: "dieses Glossar löschen",
    renameAction: "umbenennen",
    sourceLanguage: "Quellsprache",
    targetLanguage: "Zielsprache",
    sameLanguage: "Quell- und Zielsprache dürfen nicht identisch sein",
    sourceAction: "Quellsprache ändern",
    targetAction: "Zielsprache ändern",
    spokenLanguage: "Gesprochene Sprache",
    spokenAction: "gesprochene Sprache ändern",
    saving: "Wird gespeichert",
    stats: (count: number, ago: string) => `${count} ${pluralForm('de', count, { one: "Eintrag", other: "Einträge" })} · Aktualisiert ${ago}`,
    exportTable: "Dieses Glossar exportieren",
    reverse: (from: string, to: string) => `Glossar erstellen: ${from} → ${to}`,
    deleteTable: "Dieses Glossar löschen",
    exportUnavailable: "In dieser Umgebung ist kein Speicherort auswählbar; in der Desktop-App exportieren.",
    deleteTitle: (name: string) => `Löschen: „${name}“?`,
    delete: "Löschen",
    cancel: "Abbrechen",
    deleteBody:
      "Dieses Glossar wird aus der Bibliothek gelöscht und nicht mehr für spätere Transkriptionen und Übersetzungen verwendet. Bereits abgeschlossene bleiben unverändert.",
    back: "Alle Glossare",
    name: "Glossarname",
  },
  terms: {
    sourcePlaceholder: "Quelle, z. B. commit",
    canonicalPlaceholder: "Richtige Schreibweise, z. B. KV cache",
    targetPlaceholder: "Übersetzung, z. B. confirmación",
    misheardPlaceholder: "Falsch erkannt als (optional), z. B. KB cache, cave cache",
    add: "Hinzufügen",

    problems: (list: readonly string[]) => list.join("; "),
    bulkOpen: "Mehrere einfügen…",
    bulkLabel: "Mehrere einfügen",
    translationSample: "commit = confirmación\\nWyckoff = Wyckoff\\nspring = resorte = nicht „manantial“",
    transcriptionSample: "KV cache = KB cache, cave cache\\nLoRA = Laura\\ninference framework",

    bulkHow: (translation: boolean, eq: ReactNode, arrow: ReactNode): ReactNode =>
      createElement(
        Fragment,
        null,
        `Ein Eintrag pro Zeile. Trennen: ${translation ? "Quelle und Übersetzung" : "richtige Schreibweise und fehlerhafte Varianten"} mit `,
        eq,
        ", ",
        arrow,
        ` oder Tab${translation ? "; dritte Spalte ist eine optionale Notiz" : "; nur die richtige Schreibweise genügt ebenfalls"}. Zwei kopierte Tabellenspalten oder eine exportierte Markdown-Tabelle unverändert einfügen.`,
      ),
    moreSkipped: (count: number) => `${count} weitere ${pluralForm('de', count, { one: "Zeile", other: "Zeilen" })}`,
    addBatch: (count: number) => (count ? `Zu diesem Glossar hinzufügen · ${count} ${pluralForm('de', count, { one: "Eintrag", other: "Einträge" })}` : "Zu diesem Glossar hinzufügen"),
    cancel: "Abbrechen",
    search: "Einträge suchen",
    searchTranslation: "Quelle, Übersetzung und Notizen suchen",
    searchTranscription: "Richtige und fehlerhafte Schreibweisen suchen",
    noMatch: (query: string) => `Keine Einträge für „${query}”.`,
    emptyTranslation: "Noch keine Einträge. Oben Quelle und Übersetzung eingeben und mit Enter hinzufügen.",
    emptyTranscription: "Noch keine Einträge. Oben richtige Schreibweise eingeben und mit Enter hinzufügen.",
    moreHidden: (count: number) => `${count} weitere ${pluralForm('de', count, { one: "Eintrag ist", other: "Einträge sind" })} nicht aufgeführt; Suche oben zum Eingrenzen verwenden.`,
    misheardAs: (list: readonly string[]) => `Falsch erkannt als ${list.join(" · ")}`,
    editLabel: (main: string) => `Bearbeiten: „${main}“`,
    edit: "Bearbeiten",
    misheardHint: "Optional; Varianten mit Kommas trennen",
    misheardTip: "Nur tatsächlich falsch erkannte Schreibweisen eingeben. Erfundenes beschädigt zuvor richtige Sätze.",
    note: "Notiz",
    notePlaceholder: "Ein Satz für das Modell, z. B. in diesem Fachgebiet bedeutet es nicht „einreichen“",
    flexible: "Flexibel",
    flexibleHint: "Für Glossare noch nicht verfügbar: Das Übersetzungsmodell verwendet jeden Eintrag unverändert. Kontextabhängigkeit in der Notiz angeben.",
    more: "Weitere · Notiz, flexibel",
    save: "Speichern",
    deleteEntry: "Diesen Eintrag löschen",
  },
};
