import type { TasksMessages } from './tasks-copy.ts';

export const ja: TasksMessages = {
  progress: (title, label) => `「${title}」${label}`,
  imageRunning: '生成中',
  imageLoading: '画像を読み込み中',
  link: {
    stage: {
      pending: '未開始',
      current: '処理中',
      done: '完了',
      failed: '問題が発生しました',
      skipped: '不要',
    },
    action: {
      retry: 'ダウンロードを再試行',
      'change-link': '別のリンクを使う',
      'use-file': '代わりにローカルファイルを使う',
      tools: 'ダウンロードツールを確認',
      restart: '読み込みを最初からやり直す',
      downloads: 'ダウンロード先を変更…',
    },
    retryFailed: (message) => `再試行できませんでした：${message}`,
    redownload: 'もう一度ダウンロード',
    finish: '残りを完了する',
    retryImport: '読み込みを再試行',
    hideTools: 'ツールのチェックを隠す',
    copied: 'コピーしました',
    copyFailed: 'コピーできませんでした。テキストを選択してコピーしてください',
    copyError: 'エラーの詳細をコピー',
    queued: '待機中：前のタスクが終わると開始します。',
    probing: 'リンクを読み取れるか、ダウンロードツールの準備ができているかを確認中…',
    validating: 'ファイルの整合性、音声トラック、再生情報を確認中…',
    kept: 'リンクと設定は保持されています。',
    cancelledNote: '動画は作成されませんでした。リンクはこの記録に残っています。',
    keptNoVideo: 'リンクと設定は保持されています。動画は作成されませんでした。',
    imported: 'ダウンロードした動画ファイルを動画に読み込みました。',
    inDownloads:
      '動画ファイルはダウンロードフォルダにあります。今回の実行では動画の作成まで進みませんでした（アプリが再起動したか、読み込みが別の場所で開始されました）。',
    followFailed: '後続のステップで問題が発生しました。',
    creating: 'ダウンロードしたファイルから動画を作成中…',
    transcribing: '動画を開きました。字幕は準備できたものから順にエディタに表示されます。',
    translating: '字幕の準備ができました。翻訳中です。',
    ready: '文字起こしの校正、字幕スタイルの調整、動画の書き出しができるようになりました。',
    untitled: '動画リンク',
    audioOnly: '音声のみ',
    cancelFailed: (message) => `キャンセルできませんでした：${message}`,
    adoptFailed: (message) => `動画を作成できませんでした：${message}`,
    videoFailed: '動画は作成されませんでした',
    subsFailed: '文字起こしに対応が必要です',
    translateFailed: '翻訳に対応が必要です',
    stepCreate: '動画を作成',
    stepSubs: '字幕を生成',
    stepTranslate: '翻訳',
    downloaded: 'ダウンロード完了',
    stopped: '停止済み',
    unfinished: '完了しませんでした',
    savedLead: '動画ファイルは動画に追加済みです。すぐにプレビューでき、字幕は準備できたものから順に表示されます。',
    pendingLead: 'まず動画ファイルをダウンロードし、再生できることを確認してから動画を作成します。',
    steps: '読み込みのステップ',
    stepState: (label, state) => `${label}：${state}`,
    skippedMark: '（不要）',
    saved: '動画を保存しました',
    notSaved: '動画はまだありません',
    openVideo: '動画を開く',
    adopt: 'ダウンロードしたファイルから動画を作成',
    later: 'ほかの作業をする',
    cancel: '読み込みをキャンセル',
    reimport: 'もう一度読み込む',
    noteBusy: 'このページを離れても、タスクはバックグラウンドタスクに残ります',
    noteIssue: 'リンクと設定は保持されています。動画は作成されませんでした',
    noteDone: 'タスクの記録は保持されます',
    downloadTo: (path) => `${path} にダウンロード`,
    downloadToDefault: '設定のダウンロードフォルダにダウンロード',
    tool: (name, version) => `動画ダウンロードツール：${name} · ${version}`,
  },
};
